### ISSUE TITLE
<wxc-tabbar>组件中的selectedIndex，selectedColor，unselectedColor三个属性无法修改

### ISSUE THREAD

**Issue by wangleigithub** [alibaba/weex#1001]
weex-components ver.0.2.0版本中，尝试修改selectedIndex，selectedColor，unselectedColor三个属性的值，结果没作用；
尝试的方法：
上级调用者data中设置三个属性，无作用；
在组件style中设置三个值，无作用；
在组件class中设置三个值，无作用；
开发环境：chrome ver.51

**Comment by vczero** [comment]
@wangleigithub selectedColor 和 unselectedColor 的确需要暴露出来。

**Comment by wanghongyun** [comment]
`<wxc-tabbar tab-items={{tabItems}} selected-color={{selectColor}} unselect-color={{unselectColor}}></wxc-tabbar>`

根据wxc-tabbar的源码看，可以通过传selected-color和unselect-color来设置颜色。
weex确实还是很给力的，不过文档部分确实也写的很不清楚。。。

**Comment by vczero** [comment]
@wanghongyun 这块，我记下了，我来修改。：）
