### ISSUE TITLE
Weex对于styles非法值(NaN/Infinity)的处理

### ISSUE THREAD

**Issue by exolution** [alibaba/weex#1003]
首先，业务代码中 使用一个表达式计算style的部分值是很常见的，而进行计算的时候就非常容易出现一些非法值如NaN（undefined参与运算）Infinity（除0）。
那么第一个问题是，【weex如何处理width 和height等于NaN的情况？】

先描述下一个具体场景，某应用的一个页面执行好好的。但是使用weex devtool调试后却出现部分样式出错。经过排查是由于两点问题。
1、业务代码中 计算withd/height时得到了NaN。（然而，用此非法值渲染时 竟然得到正常页面结果，这也是为什么有上述问题，猜测是NaN的时候 相当于auto/initial？）
2、weex devtool调试时，是通过类似JSON RPC的方式进行js与native通信的的。JSON不支持NaN,因此js执行环境(chrome v8)跟native通信时,NaN被转换成null，导致native渲染异常。（ios端代码分析，witdh等值为null时，会报错，同时会把这个值修正成0。这个应该是引起渲染错误的原因）

那么 关于上述案例如何处理方案就需要讨论了。
1、devtool 对NaN特殊编码，相当于让JSON支持NaN，native不变，将错就错，至少让weex devtool表现跟native一致。
2、把这种非法值扼杀于摇篮中，由js framework层（或者devtool的js runtime层）进行检测 style的非法值，发现则直接抛异常。
3、其他？

个人觉得第二种方法可取。因为在上述案例中，NaN可能是运气好，没出现问题。那如果某次NaN运气不好引起了样式问题呢？此时无论devtool调试器还是 weex native的log 都无法提供任何的错误提示，从而无法引导用户找到bug所在。

**Comment by Hanks10100** [comment]
我支持第二种方式，宽高出现了 NaN 肯定是计算有误，应该报出错误不能将错就错。不过我觉得 JS Framework 不应当因此中断执行，应该提示错误信息并且修正成 0，防止 Native 抛错。

**Comment by exolution** [comment]
@Hanks10100 我觉得不应该修正为0，因为这个毕竟不是用户期待的值。非法值肯定是隐患，中断执行应该有利于debug。

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
