### ISSUE TITLE
gitbook serve fails as data-binding syntax {{...}} conflicts with the templating syntax used by GitBook

### ISSUE THREAD

**Issue by airyland** [alibaba/weex#101]
Strange issue. Works on Mac but fails on Windows.

``` bash
TemplateError: Error compiling template "syntax/main.md": (E:\workspace\weex-dev\doc\syntax\main.md) [Line 81, Column 18]
  Error: Unable to call `getTitle`, which is undefined or falsey
```

**Comment by zhoukekestar** [comment]
yeah, @Jinjiang ,it works, and there are four places need to fixed for Windows.
-------1--------
https://github.com/alibaba/weex/blame/dev/doc/syntax/main.md#L91
```bash
Template render error: (D:\Temp-Doc\weex\weex-repo\doc\syntax\main.md) [Line 90, Column 18]
  Error: Unable to call `getTitle`, which is undefined or falsey
```

-------2--------

https://github.com/alibaba/weex/blame/dev/doc/syntax/display-logic.md#L115

https://github.com/alibaba/weex/blame/dev/doc/syntax/display-logic.md#L121
```bash
Template render error: (D:\Temp-Doc\weex\weex-repo\doc\syntax\display-logic.md)
  Error: Cannot use "in" operator to search for "undefined" in unexpected types.
```
-------3-------
https://github.com/alibaba/weex/blame/dev/doc/components/text.md#L59
```bash
Template render error: (D:\Temp-Doc\weex\weex-repo\doc\components\text.md) [Line 59, Column 16]
  unexpected token: .
```
-------4------
https://github.com/alibaba/weex/blame/dev/doc/components/wxc-navpage.md#L51
```bash
Template render error: (D:\Temp-Doc\weex\weex-repo\doc\components\wxc-navpage.md) [Line 51, Column 23]
  unexpected token: .
```
