### ISSUE TITLE
如何实现客户端主动调起JS端的函数

### ISSUE THREAD

**Issue by iceyao** [alibaba/weex#1016]
weex前端逻辑这块可以实现这样的功能么：webview场景下，应用商店是通过客户端主动调起页端暴露出去的全局函数，这个全局函数能接收到app的一些状态信息（下载中、安装中等）然后进行更改页面上app下载按钮的状态信息的。如果接入weex的话，客户端主动发送app状态数据给js代码，js可以用什么方式来接收数据并传递给相应组件么？

**Comment by Bijiabo** [comment]
可以参考一下 #866

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
