### ISSUE TITLE
input控件的两个问题

### ISSUE THREAD

**Issue by squirrelx** [alibaba/weex#1030]
1.发布到手机上（Android，ios没有测试）输入光标不显示
2.value值如果绑定如value={{mytext}}   后续修改mytext input的显示并没有跟随修改

**Comment by MrRaindrop** [comment]
Hi,

我们需要更多环境信息来定位你说的问题：

1. 执行平台（native, ios还是weex-html5?）
2. sdk版本，如果是h5看下控制台开始显示的版本信息 (旧版本出现的问题可能已经fix掉了)
3. 如果是适配问题，报下设备信息

**Comment by squirrelx** [comment]
@MrRaindrop 
1.执行平台是android手机 （we文件transform为js文件 用android工具发布到手机调试）
2.weex toolkit 0.4.3  sdk版本0.70
3.测试代码如下，相当于input框后跟随一个删除按钮，用来清除输入框的文字
<template>
  <div class="top">
      <input type="text" class="input" value="{{mytext}}"></input>	
	  <text onclick="deletetext">delete</text>
  </div>
</template>


<style>
  .top {
      flex-direction: column;
	  justify-content: center;
  }
  
</style>

<script>
    module.exports = {
	    data: {
            mytext: 'textneed2delete',
        },
		methods: {
			deletetext: function() {
			    //alert("123");
			    this.mytext="";
			}
		}
    }
</script>

**Comment by MrRaindrop** [comment]
开focus()的接口需要一个注册组件方法的机制: https://github.com/alibaba/weex/issues/969

**Comment by squirrelx** [comment]
@MrRaindrop 没有看懂，点击一个按钮删除input输入框的内容和focus接口有什么关系。。

**Comment by sospartan** [comment]
之前android平台的数据更新有点问题,已经在 faffb617c164b393d60bc354bc9248d150013536 修复,光标的问题也fix了

**Comment by jiangfei891111** [comment]
input光标不显示的问题，在哪个版本修复了啊

**Comment by sospartan** [comment]
@jiangfei891111 可以使用android分支的代码  或者mavn仓库 0.8.0+版本

**Comment by misakuo** [comment]
@jiangfei891111 在Android上，必须保证input的高度大于内容高度才可以显示出光标

**Comment by squirrelx** [comment]
@sospartan 新发的0.8.0版本的光标问题修复了  但是数据绑定仍然有问题

**Comment by sospartan** [comment]
@squirrelx 如果是用数据绑定,并且会有js端进行更新的,需要添加input事件监听并更新你的绑定对象,如下:
```
<input oninput="input" ....
.....
input:function(e){
this.mytext = e.value;
}
```
这样才能触发mytext的值修改,否则实际上mytext一直是初始值,赋值后不会触发更新.

**Comment by squirrelx** [comment]
@sospartan  这数据绑定有问题吧。。   比如我想点一个删除按钮就能把input框里边的东西全部删除就实现不了啊    this.mytext='',  没用的。。
这是一个太常用的场景了吧

**Comment by sospartan** [comment]
@squirrelx weex(以及其他的js框架)的数据绑定都是这样的套路,`this.mytext`得现有原始值,重新赋值才会触发数据同步,这是必须的. 一开始知道的时候我也很震惊

**Comment by squirrelx** [comment]
@sospartan  那根本没法通过修改this.mytext的值来改变input框的显示值了。 text控件的值就可以这么做。难道这不是一个bug？

**Comment by sospartan** [comment]
@squirrelx 不一样的,text的绑定是单向的,它不会自己发生变化(除非绑定的数据变了), input会由于用户输入发生改变,所以需要通过oninput时进行赋值来保持数据同步. 

@Jinjiang

**Comment by squirrelx** [comment]
@sospartan  就是说对于input框   我只能在光标位置输入的时候触发事件然后修改绑定的值，但是我如果反过来修改绑定的值  input框显示值木有变化喽？     那这就不是双向绑定啊  angularjs就可以啊

**Comment by sospartan** [comment]
@squirrelx 在这个角度看,的确与angularjs不同,我们(weex,react)等是'单向绑定'~

**Comment by Jinjiang** [comment]
@squirrelx 我们没有直接提供“双向绑定”是希望给开发者机会选择，决定在 oninput 的时候更新数据还是 onchange 的时候更新数据，再上层的语法设计和组件设计我们希望持相对保守的态度。同时基于 vue 2.0 的双向绑定支持已经提上日程了，https://github.com/weexteam/weex-vue-framework/issues/ 可以移步这里关注我们的后续进展。

加上光标的问题已经修复，这个 issue 我先关掉了

谢谢

**Comment by squirrelx** [comment]
@jinjiang  恩   但是请教一下，比如我想点一个删除按钮就能把input框里边的东西全部删除  这种场景请问是否有建议的实现方法？

**Comment by sospartan** [comment]
@squirrelx 就是 我前面回复的方式 https://github.com/alibaba/weex/issues/1030#issuecomment-256246097

**Comment by lipeishang** [comment]
所以那个删除input框内容的问题最后是怎么实现的呢？ @squirrelx

**Comment by JackLiu0001** [comment]
所以解决办法是什么啊？

**Comment by SamZSL** [comment]
有解决方案么。。。。表示开发了个把月，各种一脸懵逼。。。。。虽然说基于vue，但是。。。。看来我还是太水了
