### ISSUE TITLE
package.json 配置问题

### ISSUE THREAD

**Issue by 1340641314** [alibaba/weex#1035]
> _``_
![1](https://cloud.githubusercontent.com/assets/8424643/17829234/0ee1ee1a-66db-11e6-9481-7c07e47e18c5.png)

**Comment by 1340641314** [comment]
这里为何要写成"true"，而不是true

**Comment by luics** [comment]
@terrykingcha  github 的格式？

**Comment by 1340641314** [comment]
@luics 只是看编辑器出现警告，没明白为何要这么写，原理是什么

**Comment by Jinjiang** [comment]
我们主仓库没有发布到 npm，所以这个字段建议还是先留着吧 @luics

**Comment by Jinjiang** [comment]
@1340641314 确实应该是 `true` 而不是 `"true"`，我们尽快更新一下

ref: https://docs.npmjs.com/files/package.json#private

**Comment by Jinjiang** [comment]
https://github.com/alibaba/weex/pull/1046

这里先关闭了，多谢反馈
