### ISSUE TITLE
用weex-toolkit 运行tech_list.we报Object.assign is not a function 错误

### ISSUE THREAD

**Issue by ldllidonglin** [alibaba/weex#1036]
完全按照官网http://alibaba.github.io/weex/doc/tutorial.html的步骤来，在命令行运行
`weex tech-list.we`
浏览器打开空白，看console
![360 20160820172334135](https://cloud.githubusercontent.com/assets/8075271/17830324/da03c892-66fa-11e6-8f32-e26300ab3502.png)

 #weex-toolkit是0.4.6版本

**Comment by ldllidonglin** [comment]
这是编译后的js
![qq 20160822091415](https://cloud.githubusercontent.com/assets/8075271/17841217/f35a3ba6-6848-11e6-8ca7-fba8c59d92cc.png)

**Comment by ldllidonglin** [comment]
@Jinjiang

**Comment by Jinjiang** [comment]
1. Weex 中间有一个版本 JS Runtime 没有加入 Object.assign 的 polyfill，最新版已经加回来了
2. 最新版 weex-loader@0.3.0 打包出来的 JS 代码已经不会用到 Object.assign 了

**Comment by Jinjiang** [comment]
@ldllidonglin 可以有劳确认一下

**Comment by ldllidonglin** [comment]
好的，我update了一下，果然可以了，谢谢勾股，谢谢各位

**Comment by Jinjiang** [comment]
不客气，这个 issue 我做关闭处理了：）
