### ISSUE TITLE
slider 组件在android playground只有两个页面的时候无法循环

### ISSUE THREAD

**Issue by Hello2015** [alibaba/weex#1039]
***Bug***
*slider* 组件在Android playground中只有两个页面的时候，无法循环播放，播放至第二张图片的时候停止了。

**Comment by sospartan** [comment]
这是个已知的问题,受限于目前整个slider的实现方式,正在考虑对slider的实现进行重构,也欢迎大家来发PR.

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
