### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by 738998656** [alibaba/weex#1043]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8081
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at net.js:1395:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)

为什么默认端口地址和文档不一致

--port        http listening port number ,default is 8081         [默认值: -1]
  --wsport      websocket listening port number ,default is 8082    [默认值: -1]
  --np          do not open preview browser automatic                  [boolean]
  -f, --force   [for create sub cmd]force to replace exsisting file(s) [boolean]
  --help        显示帮助信息                                           [boolean]
  -h, --host                                               [默认值: "127.0.0.1"]

这个配置问题是什么原因导致的，我确认我本机端口8081是未被占用的呀

**Comment by lvscar** [comment]
可能是你之前的weex-toolkit进程还在运行，造成这个情况.  

建议你把本机的全部node进程关闭后，再试试
