### ISSUE TITLE
Storage.getItem如何同步执行（或者如何在取值操作完成后再渲染界面）

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#1044]
示例代码如下
```
computed: {
      bar: {
        get: function() {
          var result;
          storage.getItem('bar',function(e) {
            var obj = JSON.parse(e.data);
            result = obj;
          });
            return result;
        }
      }
    },
```
bar的值储存在key为bar的storage里面，现在需要从storage里面拿出。但是Storage.getItem默认采用异步回调的方式，这就导致result尚未被正确赋值就被返回了（返回 undefined）。

（之所以这里需要采用这种方法获取 bar的值，是因为bar的值是用于tabbar循环输出使用的，经测试，如果值尚未获取成功就渲染界面的话，会导致tabbar里面的embed标签的src赋值异常，就不能够正常的显示tabbar了）

**Comment by yuanyan** [comment]
技术上目前做不到同步执行，设置初始为空，等数据返回了重置状态

**Comment by SimonTal** [comment]
已摸索到一种解决方案，在data中定义show:false，然后在需要输出数据的元素上设置if={{show}}，storage.getItem的回调函数的末尾设置show为true，即可触发相应的元素渲染。

**Comment by Jinjiang** [comment]
同步执行的 issue 其实是有的，可以移步这里继续讨论，确实有技术上的难点，但是大家可以发表更多的观点和看法，一起把这个问题讨论更充分 #968 

谢谢，这个 issue 我先关掉了：）
