### ISSUE TITLE
对weex性能优化的一个设想

### ISSUE THREAD

**Issue by liyunkai** [alibaba/weex#1045]
***新需求***
我理解weex的性能瓶颈会包括以下两个方面：
1. 复杂的操作需要频繁的callNative和callJS（比如自定义动画这种使用场景）
2. 复杂的计算只能通过JS去做（算法、数据处理等场景）
那能否将常用的math方法或者动画方法封装，预置一个native的lib或者dylib，利用JS call native的能力将这些操作交给native本身处理呢。
这种优化是否有可行性?

**Comment by Jinjiang** [comment]
是一种很棒的思路，我们在设计 slider 组件的时候其实就是运用了类似的思路，相当于把用户频繁操作的 touchmove 封装在了 native 端，通过一些简单的 attribute 来定制 slider 的行为。我们在将来更多的组件设计中确实会考虑更多的运用 native 本身的机能，有机会抽象和减少 js-native 交流的尽量都在这一层做简化。

再次感谢您的建议：）

**Comment by liyunkai** [comment]
看了下现在的slider代码。我理解目前手势相关的操作还是需要依赖js的计算，有没有可能把calculate and modify attribute这一套行为都封装到native端呢？而且不限于pan这种，像scaleWithTouch也是一种很常用的动画效果。主要在对手势相关的操作的封装。
类似下面这种完全不需要js参与的感觉
```
function pan(view){
    bind(viewOffsetX&Y, toucher){
           modifyAttr();
    }
}

function touchMove(){
    update(toucher.moveVector)
}

function modifyAttr(){
}

```

**Comment by Genffy** [comment]
这样就类似加了个jsbrige？然后到html5版呢？

**Comment by liyunkai** [comment]
这个设想的前提是跳过jscallNative这一环后，纯Native处理的性能是明显高于js的(虽然现在没法确定是否会有这种优化作用)。
H5上不存在这个过程，js直接run的。

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
