### ISSUE TITLE
返回数据里有html标签的支持问题

### ISSUE THREAD

**Issue by lanxiner123** [alibaba/weex#1047]
weex怎么支持返回的数据里有html标签的数据呀
像这种`"html_desc": "目前已投<font color = \"#d7ff00\">160</font>财富，还差<font color = \"#d7ff00\">40</font>财富开奖"`,
我起初用webview  但是html_desc不是src
前端的可以通过`jpag.find(".bd").html("目前已投<font color = \"#d7ff00\">160</font>财富，还差<font color = \"#d7ff00\">40</font>财富开奖")`
请问weex怎么来实现呢

**Comment by Jinjiang** [comment]
您好，Weex 中没有 innerHTML (即你这里的 `.html(xxx)` 背后用到的 DOM 接口) 的概念，即便在今天的 HTML5 开发当中，这也是一个非常不推荐使用的 API 了。

我们建议您通过模板 `<template>` 定义数据和视图的关系，然后通过管理数据来改变不同状态下的视图

谢谢

**Comment by YL2014** [comment]
意思是不打算支持对数据里的html结构进行解析了吗？比如系统的管理后台的富文本编辑，如果服务端将输入的html结构存起来供客户端调用，客户端还是需要这个功能的啊

**Comment by Jinjiang** [comment]
服务端可以输出 JS Bundle 文件来完成这个操作，这件事情上我们不会照搬web的经验，也不打算直接支持数据里的html结构

**Comment by cooliean** [comment]
@Jinjiang  服务端可以输出 JS Bundle 文件来完成这个操作，这件事情上我们不会照搬web的经验，也不打算直接支持数据里的html结构
  请问 js bundle的方法哪里又教程呢，想看看能不能达到我想要的效果，谢谢了。
