### ISSUE TITLE
当前list下面的cell没有设置宽度的时候，如果进行复用，宽度显示的时候会出现显示问题

### ISSUE THREAD

**Issue by xiangbingXB** [alibaba/weex#1048]
<!--
0. It's ***RECOMMENDED*** to [submit PR](https://github.com/alibaba/weex/pulls) for typo, new demo or tiny bugfix.
0. If this's a ***BUG***, pls provide: course repetition, error/crash log, device model, OS version, App version (playground or other apps).
0. If this's a ***FEATURE***, pls provide: details, pseudo codes if necessary.

---

**Comment by luics** [comment]
请贴一下环境，比如 ios 、android、h5？

**Comment by xiangbingXB** [comment]
在weex示例代码的安卓版本中的list-demo.js中，搜索“Ruskin”，里面可以看到“yesterday”显示不全

**Comment by YorkShen** [comment]
复用的cell不会重新layout。如果两个cell的layout不同，不要进行复用。
