### ISSUE TITLE
关于 script type="data"

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1051]
大部分的编辑器会根据 script 标签的 type 属性来判断使用什么语法支持.
当使用 `<script type="data"></script>` 的时候，编辑器就无法获得语法支持了，建议使用@type 或者其他属性来代替 type，且语法上建议使用普通 script 标签内的 module.exports 的方式导出，而不是直接写个花括号。

**Comment by Jinjiang** [comment]
很好的建议，我们会讨论一个更合理的方案出来
谢谢

cc @terrykingcha @songsiqi

**Comment by songsiqi** [comment]
`weex-transformer` 在编译的时候会把 `module.exports=` 去掉，`weex-loader` 也可以这么做 @Jinjiang @terrykingcha

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
