### ISSUE TITLE
wxc-tabbar无法通过style设置background-color样式

### ISSUE THREAD

**Issue by jiwenfei** [alibaba/weex#1053]
weex-components版本0.2.0, 所写代码为：
```
 <wxc-tabbar style="background-color:rgb(255, 255, 0);"  tab-items = {{tabItems}} ></wxc-tabbar>
```

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
