### ISSUE TITLE
H5:stream跨域提示Unexpected token

### ISSUE THREAD

**Issue by catliuqh** [alibaba/weex#1055]
H5页面跨域请求时报错，请问怎么解决
直接weex index.we在浏览器进行调试

**我的跨域代码是这样写的:**

![qq 20160823164836](https://cloud.githubusercontent.com/assets/17329044/17885873/b3eb2db8-6951-11e6-8047-60224a169734.png)
![qq 20160823164949](https://cloud.githubusercontent.com/assets/17329044/17885874/b4256492-6951-11e6-884c-be0710e6c1d5.png)

**运行时报如下错误，用stream跨域请求后面会默认添加callback=jsonp，但报错又提示jsonp未定义**

![qq 20160823165445](https://cloud.githubusercontent.com/assets/17329044/17886010/790e8982-6952-11e6-9e3e-109849ac6c5e.png)

**正常情况下后台返回的数据**
![qq 20160823170226](https://cloud.githubusercontent.com/assets/17329044/17886251/7b71dcbe-6953-11e6-8f5a-2b3c5c626696.png)

**Comment by MrRaindrop** [comment]
Hi,

1. h5的stream.fetch的jsonp callback返回数据有问题，没有包裹在data里面，而是直接把data做为回调参数了，当然这个问题与你说的这个问题无关（后续会修复）。
2. 目前jsonp方式没有支持自定义callback name，所以手动在url里加上`jsoncallback=jsonp`也是没用的，与之对应服务器应该从url里解析stream.fetch默认传递的`callback`这个参数，典型的参数为`callback=jsonp_1` (1是一个防止重复请求的计数，每次+1)，这时服务器应该返回jsonp_1(yourData)

**Comment by catliuqh** [comment]
那我现在的解决方法就是只有让后台改callback name为callback才能正常用吗

**Comment by MrRaindrop** [comment]
改为url里带的参数callback所指定的name，如callback=jsonp_1 则返回`jsonp_1(data)` @catliuqh

**Comment by MrRaindrop** [comment]
问题 1 已在 https://github.com/alibaba/weex/pull/1059 修复

**Comment by catliuqh** [comment]
问题2的那个callback name你们会考虑可以自定义吗，我们大部分的都是jsoncallback=jsonp

**Comment by MrRaindrop** [comment]
这个目前native没有开这个口子，原因是native也没有跨域这个需求。不够倒是可以考虑单独为h5增加一个跨域的jsoncallback参数。后续会考虑加上这个需求，你也可以给我们提pr

**Comment by SecretCastle** [comment]
请问下，stream.fetch后，报
![image](https://cloud.githubusercontent.com/assets/12498143/20616145/018f570c-b31b-11e6-9391-cc80e07d43fa.png)
这个是什么毛病

**Comment by 452MJ** [comment]
@SecretCastle +1
