### ISSUE TITLE
[bug]ios端stream.fetch的返回值与web及Android不一致

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#1063]
示例代码如下:
```
stream.fetch({
  method: 'GET',
  type: 'json',
  url: 'http://httpbin.org/get'
}, function (ret) {
  vm.rettype = typeof(ret);
},function(response){});
```
ios1.1版playground的stream.fetch均失败，经检测发现，网络通信正常，问题出在 ios端的 ret为一个字符串（rettype：string）。安卓及web端均返回正常的对象。

**Comment by SimonTal** [comment]
补充一下 stream.fetch是成功的，只是ret为字符串后，造成 ret.ok 判断失败，以及后续的数据操作失败。

**Comment by SimonTal** [comment]
ios端：
![img_0006](https://cloud.githubusercontent.com/assets/13174847/17925527/e3a1f6bc-6a1f-11e6-8806-e5745e17d021.PNG)
Android端：
![quickmemo _2016-08-24-17-28-00](https://cloud.githubusercontent.com/assets/13174847/17925604/254b4604-6a20-11e6-94a3-3f4874461d63.png)

**Comment by acton393** [comment]
hi @SimonTal  appStore 上的 playground是1.1 版本 的SDK 是0.6.1 的SDK，这个版本SDK确实存在如你上所示的一个bug，即：Android  h5 返回的type 不一致的问题， 已经在最新版本0.7里面fix掉，dev 分支也是最新的，可以尝试下

新版本的playground  集成了 0.7.0 SDK，已经在准备中，会尽快提交审核， dev 分支的playground直接跑是不会有上述问题的

**Comment by SimonTal** [comment]
谢谢 用DEV的 已经解决了 @acton393

**Comment by acton393** [comment]
OK，有问题可以继续再打开
