### ISSUE TITLE
<text>标签里面的内容无法换行，是否可以通过{% raw %}规避？

### ISSUE THREAD

**Issue by xiangbingXB** [alibaba/weex#1065]
如果写成如下：    

![image](https://cloud.githubusercontent.com/assets/11882421/17928224/50f89fd4-6a2c-11e6-9cc1-bf845a6c204b.png)

那么，Weex会把<br>直接识别为一个标签，这样会crash掉；

如果写成如下：
    
![image](https://cloud.githubusercontent.com/assets/11882421/17928241/5f8759f0-6a2c-11e6-8b31-81b5894c5a26.png)

那么，会直接在页面里面显示换行符，还是没有达到换行的目的

**Comment by IskenHuang** [comment]
Does `<br>`  breaking line on native client?
