### ISSUE TITLE
类似于DatePicker这样的控件好像并提供，未来计划提供还是从外部引入？

### ISSUE THREAD

**Issue by ustccq** [alibaba/weex#1067]
如题，
由于最近app人手严重不足，所以从后端转而研究了一下android + weex
在画产品设计图时仔细地查看了playground和英文文档，没有发现类似于DatePicker这样的控件的描述，故有此一问。

**Comment by jinyue-rdj** [comment]
目前正在开发的版本中没有规划，但可以在下个版本中引入开发

**Comment by hubinjie** [comment]
@jinyue-rdj 下个版本啥时候发布？

**Comment by alext1981** [comment]
该需求已经开发完成并将在0.9版本中引入，所以关闭此issue，如果此feature还有新的讨论，可以reopen或开新的issue。
