### ISSUE TITLE
（weex tech_list.we --qr）生成二维码错误 如何解决

### ISSUE THREAD

**Issue by Desever** [alibaba/weex#1069]
\fs-extra\node_modules\rimraf\rimraf.js:312
        throw er
        ^

**Comment by lvscar** [comment]
@Desever 请反馈多一些的错误信息和你的node版本.       建议你升级node试一下.

**Comment by lvscar** [comment]
没有发现新的例子，希望升级node后在你的环境里该问题得到解决.
