### ISSUE TITLE
关于Weex多语言支持！

### ISSUE THREAD

**Issue by HelloClouds** [alibaba/weex#1076]
希望Weex能够支持多语言！例如对字符串的抽取，类似Android里面对string字符串的处理！也可以通过引用字符串的形式！》》value-zh  ,value-en,等等！

**Comment by Jinjiang** [comment]
很好的建议，这种问题可以通过上层 JavaScript 库来解决，同时可以配合客户端提供的本地化信息

**Comment by baoti** [comment]
@Jinjiang 多语言还包括 LTR、RTL 排版方式。

**Comment by qbcbyb** [comment]
本人暂时是通过一下这种方式去支持多语言的：
将所有的文本都写在单独的json文件中，一种语言对应一个json文件。在页面加载完成后，根据local参数通过fetch从网络或者本地取回相应语言的json文件，解析并绑定到vm相应的字段上。

**Comment by myst729** [comment]
其实我一直很期待 Vue 提供一个官方的 i18n 方案。之前试过 [kazupon/vue-i18n](https://github.com/kazupon/vue-i18n)，但在跟 vue-router 和 vuex 联用的时候总是有点问题，也可能我自己没用对。

**Comment by TooBug** [comment]
https://github.com/TooBug/webpack-amdi18n-loader

**Comment by Justineo** [comment]
我比较支持用类似 gettext 的方案。以前做过基于 WordPress 的多语言，感觉还挺方便的。

**Comment by AFRE001** [comment]
@qbcbyb  你这样解决多语言问题，会不会导致所有页面都要引入全量的资源（JSON）。比如页面A只是用了A1，A2，A3，但你引入JSON文件是整个工程用的，这样编译.we的文件的时候，就会把所有JSON内容都编到这个.we翻译后的文件里。最终就是每个.we都要包含一份，加载时增加网络流量。。

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！

**Comment by junzaivip** [comment]
多语言， 大家有什么好的建议么
