### ISSUE TITLE
List和解析json的问题

### ISSUE THREAD

**Issue by HelloClouds** [alibaba/weex#1077]
我最近遇到了，我在服务器抓取数据，在weex调试扫码出来后数据能够直接json解析显示出来，集成到Android后json数据的解析又不一样，得换一个解析方式才能够显示，另外，本地写死列表项的数据和weex抓取数据扫码调试，list可以上滑动刷新，集成到Android后列表没办法自动刷新，这些不知道是我写的问题还是weex的bug，我的情况是扫码没问题，集成就出问题

**Comment by d0f** [comment]
我也有

**Comment by YorkShen** [comment]
提供一下最小代码

**Comment by misakuo** [comment]
我应该也遇到了同样的问题，通过
```
stream.fetch({
    method: 'GET',
    url: url,
    type: 'json'
}, function(response){
}, function(progress){
});
```
请求接口，在Android上，`typeof(response) -> Object`这是符合期望的，而在iOS上，`typeof(response) -> string`
更奇怪的是即使在iOS上执行了`response = JSON.parse(response)`，`typeof(response.data)`结果依旧为`string`

**Comment by breg-jjb** [comment]
@misakuo 我遇到类似的问题，同一个接口，andriod上可以正常转换为json对象，ios上则不行，通过调试发现，在ios获取的接口返回的字符串格式有问题，多加了一些双引号，比如：在大括号之前有双引号（“{）、多了正斜杠等，替换掉这些格式问题，就能正常转换成json了。
至于为什么同一个接口在ios上获取的json字符串格式有问题，这还不清楚

**Comment by misakuo** [comment]
@YorkShen 麻烦确认一下是不是因为sdk的原因导致在两个平台上出现不一致的行为 : )

**Comment by YorkShen** [comment]
@breg-jjb @HelloClouds @d0f 更新到dev分支，如果有问题，再重新打开
