### ISSUE TITLE
使用navigator-pop返回后，能否让触发一个事件。

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#1078]
某些应用环境下，待页面操作完成后，点击返回按钮期望能够触发一个事件能够对返回后的页面进行一些操作。

**Comment by vczero** [comment]
navigator.pop(params, function(e){
     //TODO: 
})；
1）回调函数可能满足你某些需求。
2）还有一个方式，可以尝试通过url传递数据，在新的页面拿到url的参数进行相关设置。

**Comment by pp1232** [comment]
我也碰到类似的情况，需要在返回后的页面做一个事件调用，触发一些页面数据的重新绑定。这个pop的回调函数应该是只能在调用返回的页面进行处理吧

**Comment by SimonTal** [comment]
不过这个回调函数是在当前页面执行的，不能操作到返回后的页面。
还有就是 返回后的页面状态 处于渲染完成状态了，也就是个死页面了，所以不会触发init created ready 事件 @vczero

**Comment by SimonTal** [comment]
是的 ，我也觉得那个 回调是在当前页面执行的，所以并没什么用处 @pp1232

**Comment by vczero** [comment]
Web页面和Native页面渲染存在差异，第2种方案不起作用了, 因此根据数据判断的方案是行不通。
@luics

**Comment by luics** [comment]
有一个临时的解决办法，后续会在 navigator 中支持。
http://alibaba.github.io/weex/doc/faq.html#transfer-data-between-pages

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！

**Comment by gracer-lyl** [comment]
这个问题最终怎么个解决方案？

**Comment by lxzliuxinzhu** [comment]
这个问题现在是怎么解决的?

**Comment by dzp181** [comment]
这个问题现在是怎么解决的?
