### ISSUE TITLE
iOS无法进行带参数的POST请求？

### ISSUE THREAD

**Issue by dongjize** [alibaba/weex#1079]
大家有没有用iOS尝试带参数的POST请求？我用Android就可以拿到weex端定义的body，并正常显示数据，但iOS端无论如何都拿不到。有和我相同的情况么？

**Comment by acton393** [comment]
可以贴一下具体的代码瞅瞅看下

**Comment by dongjize** [comment]
这个是我代码里的post请求。
```
postData: function (url, callback) {
      var self = this;
      var stream = require('@weex-module/stream');
      stream.fetch({
        method: 'POST',
        url: url,
        type: 'json',
        body: {
          'type': self.typeId + '',
          'page': self.page + '',
        }
      }, function(ret) {
        if(ret.ok) {
          var retdata = JSON.parse(JSON.stringify(ret.data));
          callback(retdata);
        } else {
          console.log('fetch POSTs error: ' + ret);
        }
      }, function(response) {
          // progress callback
      });
    },
```
一开始，我按文档传了String形式的body，`body: "type="+self.typeId+"&page="+self.page`，Android和iOS取不到数据。
后来改成dictionary，发现Android可以接收dictionary形式的body；ios接收dictionary会crash。

**Comment by osindex** [comment]
发现类似情况
请求地址如
http://localhost/api/bind?string={"id":"88","password":"weex"}&sign=209b3cd60a824b7bd597448879873b02
返回
Object {status: -1, data: "不支持的 URL(-1002)", statusText: "ERR_INVALID_REQUEST", ok: 0}

后来经过处理
**

> requrl = (encodeURI(requrl));

** 
// 不使用encodeURI ios 无法识别 返回Code=-1002 "unsupported URL" 
// 如果主机名是localhost 返回Code=-1004 "kCFURLErrorCannotConnectToHost"  切记用ip 如果本机调试。

**Comment by acton393** [comment]
hi @dongjize  

我使用的代码如下：

```
stream.fetch({
        method: 'POST',
        url: 'http://httpbin.org/post',
        body:'type=weexType&page=weexPage',
        type:'json'
      }, function(ret) {
        if(!ret.ok){
          me.postResult = "request failed";
        }else{
          console.log('get:'+JSON.stringify(ret));
          me.postResult = JSON.stringify(ret.data);
        }
      },function(response){
        console.log('get in progress:'+response.length);
        me.postResult = "bytes received:"+response.length;
      });
```

运行结果：最下面那行数据，就是post 的数据

<img width="300" alt="screen shot 2016-08-29 at 15 15 15" src="https://cloud.githubusercontent.com/assets/11631084/18043567/5880b5a2-6dfb-11e6-82d3-fc79cde060cd.png">

**Comment by dongjize** [comment]
谢谢~
我用你这种方法在playground操作了相同的数据，显示结果是一样的。但可能由于我现在项目的后台接受的是request payload，导致我把url和body改成自己的后，下面“form”仍然拿不到数据。

不知道这个和form-data、request payload的请求方法有关系吗？

**Comment by acton393** [comment]
hi  @osindex  

`http://localhost/api/bind?string={"id":"88","password":"weex"}&sign=209b3cd60a824b7bd597448879873b02`

这个url 里面 最主要 的感觉是这个  `{...}` 需要encode一下， 


你调试是在真机上还是模拟器， 我试了一下，模拟器的应该是可以访问到的

**Comment by osindex** [comment]
@acton393 
thks.

昨晚太晚，少打了一句话~
是经过encodeURI已经解决了 0_0。
后面是贴的错误的相关提示。

**Comment by acton393** [comment]
@osindex  嗯~，OK，我在模拟器上也试了一把`localhost` 好像也可以load到数据

木有看到报告这个错  Code=-1004 "kCFURLErrorCannotConnectToHost"  ，你有具体的复现的路径可以告诉我下哈~

**Comment by dongjize** [comment]
这个问题我昨天解决了~我们服务器接收的POST请求是request payload的数据形式，sdk中的WXStreamModule对此不兼容，无法拿到header和body，后来我自定义了一个StreamModule，手动传header和body进去，解决了这个问题。

以后的版本可以增加对request payload形式数据的支持~

**Comment by acton393** [comment]
@dongjize   好的，这个你可以再开一个issue 提一下  期望增加 request payload 形式数据哈

同时也欢迎你 在`WXStreamModule` 里面修改， 然后提个pr 完善下 stream module ，也方便其他开发者使用哈~~

**Comment by jieshadow** [comment]
你好我是刚开始学习这个框架，不是很知道这个请求，能否请大神给我看看你写的weex请求成功的实例。谢谢！邮箱是：2530897329@qq.com。

**Comment by acton393** [comment]
@jieshadow   可以直接参考我们的官网 playground的 例子， 
http://alibaba.github.io/weex/doc/modules/stream.html
