### ISSUE TITLE
express + weex + html5

### ISSUE THREAD

**Issue by ht616** [alibaba/weex#1089]
后端一直用express做服务，想结合weex，自己集成，总是无法生成weex里面的内容，也不报错。

weex试水，想像react+express一样，试一下weex+express。
把node_modules里的weex.min.js复制出来，使用html5的方式，weex没有初始化，就是div里的内容没有生成，是可能什么原因导致的呢，小弟初次试水，有木有大神解释下啊。

求一个express 结合weex的例子。

**Comment by Jinjiang** [comment]
请确定一下相对路径是否正确
更多使用上的疑问请移步中文聊天室讨论 https://gitter.im/weexteam/cn
想想
