### ISSUE TITLE
scroller中onclick事件和onloading不兼容

### ISSUE THREAD

**Issue by breg-jjb** [alibaba/weex#1112]
重现步骤：在官方提供的demo：scroller-demo.we中加入如下图中红色框中的测试代码（即添加了onclick事件）
结果：onloading事件不触发
测试系统：andriod和ios的playground中都是同样的问题
![qq 20160830181315](https://cloud.githubusercontent.com/assets/21171780/18085402/9b85e24a-6edd-11e6-85fd-2bf4b9145851.png)

**Comment by xkli** [comment]
@breg-jjb 按照你的写法我测试了master和dev分支，最新的playground都能够正常相应事件。麻烦你在用最新的playground试一下。http://alibaba.github.io/weex/download.html

**Comment by breg-jjb** [comment]
@xkli 仍然是不行啊！ 被加上了onclick的组件，在按住这个组件区域进行上拉的时候，不能同时响应 “点击”或者“滚动”

**Comment by breg-jjb** [comment]
@xkli 总算找到原因了，是某些机型有问题，我发现有问题的机型是H60-L01，操作系统为Android 4.4.2
