### ISSUE TITLE
Android app:直接用renderPage方法打开playground中的tabbar-demo.js，tabbar-demo.js中的this.$getConfig().bundleUrl返回值中不包含'file://assets/'

### ISSUE THREAD

**Issue by Lurkyli** [alibaba/weex#1113]
前提条件：
1. 手机: 华为 GRA-TL00[P8 移动4G] emui 4.0.1 android 6.0

复现步骤：
1. 创建测试工程，直接用renderPage方法打开playground中的tabbar-demo.js
2. 在GRA-TL00[P8 移动4G]运行上述测试程序；

结果：
1. tabbar-demo.js中的this.$getConfig().bundleUrl返回值中不包含'file://assets/'，导致从网上寻找tabbar-demo.js资源，而没有在本地assets中寻找tabbar-demo.js，从而加载资源失败；

备注：
tabbar-demo.js的相关资源都为修改，在playground中运行正常，playground是用this.$openURL(this.url)方法打开的资源。

**Comment by xkli** [comment]
@Lurkyli renderPage 中的source是用来判断是否加载本地资源，source中如果包含"your_current_IP",就会把tabbar-demo.js的host设置为file://assets. 
您是否没有把source设置对？

**Comment by Lurkyli** [comment]
这个是我的代码：
    private static final int CAMARA_PERMISSION_REQUEST_CODE = 0x1;
    private static final String TAG = "IndexActivity";
    private static final String DEFAULT_IP = "your_current_IP";
    private static String CURRENT_IP= DEFAULT_IP; // your_current_IP
    private static final String WEEX_INDEX_URL = "http://"+CURRENT_IP+":12580/examples/build/clcw_main.js";


DEFAULT_IP如上面的代码设置，没有修改就是"your_current_IP"。
tabbar-demo.js中的代码如下：
    created: function() {
	        var bundleUrl = this.$getConfig().bundleUrl;
	        console.log('hit', bundleUrl);
	        var nativeBase;
	        var isAndroidAssets = bundleUrl.indexOf('file://assets/') >= 0;
	        var isiOSAssets = bundleUrl.indexOf('file:///') >= 0 && bundleUrl.indexOf('WeexDemo.app') > 0;
	        if (isAndroidAssets) {
	          nativeBase = 'file://assets/';
	        }
	        else if (isiOSAssets) {
	          // file:///var/mobile/Containers/Bundle/Application/{id}/WeexDemo.app/
	          // file:///Users/{user}/Library/Developer/CoreSimulator/Devices/{id}/data/Containers/Bundle/Application/{id}/WeexDemo.app/
	          nativeBase = bundleUrl.substring(0, bundleUrl.lastIndexOf('/') + 1);
	        }
	        else {
	          var host = 'localhost:12580';
	          var matches = /\/\/([^\/]+?)\//.exec(this.$getConfig().bundleUrl);
	          if (matches && matches.length >= 2) {
	            host = matches[1];
	          }
	          nativeBase = 'http://' + host + '/' + this.dir + '/build/';
	        }
	        var h5Base = './' + this.dir + '/build/';
	        // in Native
	        var base = nativeBase;
	        if (typeof window === 'object') {
	          // in Browser or WebView
	          base = h5Base;
	        }

	        for(var i = 0; i < this.tabItems.length; i++) {
	            var tabItem = this.tabItems[i];
	            tabItem.src = base + tabItem.src;
	        }
	        // see log in Android Logcat
	        //if (this.items.length) console.log('hit', this.items[0].url);
	    },

**Comment by bingooo** [comment]
@Lurkyli 
可以尝试将
`var isAndroidAssets = bundleUrl.indexOf('file://assets/') >= 0;`
改为
`var isAndroidAssets = bundleUrl.indexOf('your_current_IP') >= 0 || bundleUrl.indexOf('file://assets/')>=0;`

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
