### ISSUE TITLE
安卓端webview上传图片无法调起图片浏览器

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#1117]
As title，ios端是可以调用系统图片选择界面的。

**Comment by misakuo** [comment]
Hi，麻烦提供一下出现问题的Android系统版本。
另外您是通过`<input type="file"/>`尝试调用图片浏览器的么？

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
