### ISSUE TITLE
stream.fetch请求服务器时,  修改Content-Type无效

### ISSUE THREAD

**Issue by renqishuang** [alibaba/weex#1122]
首先说下,  使用weex的平台是h5, 
使用stream.fetch请求服务器时,  默认把请求参数都放在 请求体的Request Payload 中,  我的后台服务器只从请求体的Form Data中获取参数,  那么我就想改下这个参数存放地点, API中有headers字段, 于是我就
添加headers: {'Content-Type':'application/x-www-form-urlencoded'}, 希望我的参数能出现在FormData中,  但是请求体中的Content-Type没有变化, 依然是text/plain;charset=UTF-8, 我的参数依然出现在了
Request Payload中,  求大神解释一下!!!!  
stream.fetch({
        method: 'POST',
        url: url,
        type:'json',
        headers: {'Content-Type':'application/x-www-form-urlencoded'},
        body:"{'name':'123'}"
      }

**Comment by renqishuang** [comment]
已解决, 使用 weex_temp/h5_render/xxx.js 下面的文件即可

**Comment by spiritelf** [comment]
？？？什么意思
