### ISSUE TITLE
strea.fetch()请求PHP服务器,  PHP服务器使用$_POST 接收不到参数

### ISSUE THREAD

**Issue by renqishuang** [alibaba/weex#1126]
平台是h5
代码如下:
stream.fetch({
        method: 'POST',
        url: url,
        type:'json',
        headers: {'Content-Type':'application/x-www-form-urlencoded'},
        body:'{name:'123'}'
      }, 
查看请求体时, FormData下面有 {"name":"123"}
但是PHP服务器那边使用 $_POST, 却获取不到参数,  求解!!!
RequestHeader如下:

![qq 20160901165802](https://cloud.githubusercontent.com/assets/12408084/18161636/5184f634-7065-11e6-871c-cf48573b86cb.png)

**Comment by dongjize** [comment]
https://github.com/alibaba/weex/issues/1079
这个我也遇到过，后来解决了，是request payload的问题。你可以看看上面的链接。我是本地自定义了一个网络请求module。

**Comment by renqishuang** [comment]
@dongjize  我请求的参数都放到了, FormData中, PHP服务器也只从FormData中接收参数,而不是从Request 
Payload中接收参数,  我用JQuery发送请求和Stream.fetch发送请求进行了FormData的对比, 还真是有区别,
我现在参数改为JSON对象, 放到body上, 如下: 
用JQuery请求时, 参数在FormData中的形态, 
用Stream.fetch请求时, 参数在FormData中的形态:
![1](https://cloud.githubusercontent.com/assets/12408084/18197032/b42819fc-7127-11e6-8a3c-0fca2c880059.png)
用Stream.fetch请求时, 参数在FormData中的形态:
![2](https://cloud.githubusercontent.com/assets/12408084/18197028/af23a2b4-7127-11e6-8d19-dae52b1fd713.png)

**Comment by renqishuang** [comment]
已解决, body参数使用字符串, 而且是 name='zhangsan'&age=18的形式, 而不是JSON字符串

**Comment by rundaisc** [comment]
使用 file_get_contents("php://input")
