### ISSUE TITLE
weex某些animation在native上没有效果

### ISSUE THREAD

**Issue by jiuyuegui** [alibaba/weex#1131]
***Bug***

current节点初始css设置是

```
{
    left: 750;
    transform: translateX(750px);   //ios不起作用
}
animation.transition(current, {
  styles: {
    transform: 'translateX(0px)',   //ios可以起作用，但是第一次设置的css没有作用
    left: 0                         //native上不起作用，类似的position属性均不起作用
  },
  duration: 2000,
  timingFunction: 'linear'
}, function() {
  console.log('finish');
});
```

**Comment by Jinjiang** [comment]
目前支持范围是 `color` 和 `transform` (2d语法)
具体支持animate的属性见这里：http://alibaba.github.io/weex/doc/modules/animation.html#arguments
iOS 不起作用的相关问题我们再多看一下
谢谢

**Comment by cxfeng1** [comment]
@jiuyuegui transform初始化不起作用是已知bug， 已 c36f1bfc4dab66703eba23082bc096483c5527d5 中修复， 将在0.8版本合入dev。

另外transition的接口只支持transform/backgroundColor/opacity， 还不支持left.

**Comment by jiuyuegui** [comment]
好的，知道了，多谢^_^
