### ISSUE TITLE
关于AbstractEditComponent 文本框的问题

### ISSUE THREAD

**Issue by haicuan139** [alibaba/weex#1132]
1.我在使用当前版本的Android SDK ，AbstractEditComponent 这个抽象类 并没有对 Android 中的Gravity.START 进行支持。遇到高度值很大的textarea，文字输入永远都是Gravity.CENTER。这导致我无法将光标设置到文本框的左上角。
我现在的解决方案是在AbstractEditComponent 抽象类中增加以下方法。
Android 
```java
@WXComponentProp(name = "gravity")
  public void setGravity(String gravity) {
    if ("start".equals(gravity)){
          ((EditText) mHost).setGravity(Gravity.START);
      }
  }
```
Weex 中使用:
```html
 <textarea type="text" rows="10"  gravity="start"  placeholder="在这里你可以吐槽我们,也可以描述你期待的功能(500字以内)" autofocus="true"
                      style="background-color: #0000f6;width:{{deviceW}};margin: 20;"></textarea>
```

2.我本来想通过继承TextArea这个类，但是将我的子类注册成为一个组件时，并不管用，什么都不显示,我可否能够在不修改上层代码的同时，实现这个功能？

**Comment by sospartan** [comment]
@haicuan139 贴一下注册的部分的代码,谢谢.

你这种拓展方式是支持的,由于weex的注册机制,先注册的会被后注册的'覆盖',所以如果要覆盖内置component,需要在调用SDKEngine的初始化方法之后再注册.

**Comment by haicuan139** [comment]
只有textarea才有效。我继承textarea 无效，继承AbstractEditComponent  将原有的textarea 中的代码拷贝过来也是无效的。

` //application
    private void initWeex(){
        try{
            configWx();//initialize
            WXSDKEngine.registerModule("nativemodel", WeexModel.class);
            WXSDKEngine.registerComponent("bztext", CustomAreaComt.class,false);
        }catch (Exception e){
            e.printStackTrace();
        }

    }`

`
//自定义组件
public class CustomAreaComt extends Textarea {
    public CustomAreaComt(WXSDKInstance instance, WXDomObject dom, WXVContainer parent, boolean isLazy) {
        super(instance, dom, parent, isLazy);
    }

    @WXComponentProp(name = "gravity")
    public void setGravity(String gravity) {
        if ("start".equals(gravity)){
            ((EditText) mHost).setGravity(Gravity.START);
        }
    }
}
`

`  
//weex
<div>
        <div style="flex-direction: row;align-items: center;padding: 10">
            <text style="margin-left: 20">联系邮箱</text>
            <input type="text" placeholder="请输入您的邮箱" autofocus="true"
                   style="width: {{400}};height: 80;margin-left: 20"/>
        </div>
        <smallline></smallline>
            <bztext type="text" rows="10" gravity="start"  placeholder="在这里你可以吐槽我们,也可以描述你期待的功能(500字以内)" autofocus="true"
                      style="background-color: #0000f6;width:{{deviceW}};margin: 20;"></bztext>
    </div>`

**Comment by haicuan139** [comment]
`//application
    private void initWeex(){
        try{
            configWx();//initialize
            WXSDKEngine.registerModule("nativemodel", WeexModel.class);
            WXSDKEngine.registerComponent("bztext", CustomAreaComt.class,false);
        }catch (Exception e){
            e.printStackTrace();
        }

    }

    public class CustomAreaComt extends Textarea {
    public CustomAreaComt(WXSDKInstance instance, WXDomObject dom, WXVContainer parent, boolean isLazy) {
        super(instance, dom, parent, isLazy);
    }

    @WXComponentProp(name = "gravity")
    public void setGravity(String gravity) {
        if ("start".equals(gravity)){
            ((EditText) mHost).setGravity(Gravity.START);
        }
    }
}

<template>
    <div>
        <div style="flex-direction: row;align-items: center;padding: 10">
            <text style="margin-left: 20">联系邮箱</text>
            <input type="text" placeholder="请输入您的邮箱" autofocus="true"
                   style="width: {{400}};height: 80;margin-left: 20"/>
        </div>
        <smallline></smallline>
            <bztext type="text" rows="10" gravity="start"  placeholder="在这里你可以吐槽我们,也可以描述你期待的功能(500字以内)" autofocus="true"
                      style="background-color: #0000f6;width:{{deviceW}};margin: 20;"></bztext>
    </div>
</template>`

**Comment by haicuan139** [comment]
@sospartan 代码粘贴的有点乱，主要是自定义组件 很简单的实现，通过集成 textarea 然后添加了一个setGravity 的方法 application注册的是在 WXSDKEngine.initialize之后调用的

**Comment by haicuan139** [comment]
@sospartan 是我的失误，我在自定义的时候，必须要制定一个固定的宽度和高度。

**Comment by sospartan** [comment]
@haicuan139 是的,如果需要有自我'measure'的能力,需要给component注册单独的`DomObject`,可以参考一下内置component的注册过程.
