### ISSUE TITLE
Weex Android 处理 json 对象中属性值为 null 的异常

### ISSUE THREAD

**Issue by candyili** [alibaba/weex#1133]
贴代码：

```
function getData(url, callback) {
	stream.sendHttp({
		method: ‘GET’,
		url: url
	}, function (ret) {
		var retdata = JSON.parse(ret);
	});
}
```

`retdata`为json object，其中里面有一个属性 `Time` 的值为 `null` ，怎么判断这个属性值是不是为 `null` ？ 
用了 `retdata.Time == null` 一直是 `false`（如果是用浏览器调试的话是 `true`，但是上了Android之后是 `false`），然后打印出来 `retdata.Time` 是 `[object object]`

**Comment by YorkShen** [comment]
@sospartan 看以下，stream的问题

**Comment by sospartan** [comment]
@candyili 贴一下你得json数据

**Comment by candyili** [comment]
{"Res":'',"Ret":{"Time":null,"Date":20160909}}
其中Ret里的Time的值为null

**Comment by sospartan** [comment]
你先打印ret,看看是什么内容.

btw: sendhttp接口将会启用,改用stream.fetch

**Comment by candyili** [comment]
恩，用stream.fetch发现一个新问题：
stream.fetch({
        method: ‘GET’,
        url: url
    }, function (ret) {
         // modal.alert ( "ret = " + ret +" --- " + ret.Ret  );
    });

在浏览器上调试，打印出是   “ret = [object Object] --- [object Object]”;
在Android上测试，打印出是“ret = [object Object] --- undefined”;
经过抓包看两者请求的返回结果都是 {"Res":'',"Ret":{"Time":null,"Date":20160909}}

**Comment by sospartan** [comment]
fetch的数据结构与sendhttp不同,具体请看一下 http://alibaba.github.io/weex/doc/modules/stream.html,
是在`data`字段中,而不是在第一级结构里,h5的实现有点问题,会进行修改.

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
