### ISSUE TITLE
Navigator的逻辑优化

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#1134]
假设有5个页面 ABCDE
有如下操作

A-push-B-push-C-push-E-push-B 

此时如果在B页面执行POP操作（或使用安卓返回键） 会造成B-E-C-B-A的返回

如何能提供某种方法让B页面能够直接返回到A页面

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
