### ISSUE TITLE
[bug]安卓input无光标

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#1135]
如题，安卓系统均无input的光标，经测试 小米 、LG 的机型都有此问题。

**Comment by guogailee** [comment]
确实是，感觉还是需要提供一个光标，用户体验不是很好，最好提供一个是否展示光标的属性，有的时候刚进去页面的时候不需要展示光标。

**Comment by sospartan** [comment]
光标的问题已经修复,目前在android分支可以使用,正式版本会在v0.8发布.
