### ISSUE TITLE
通过手势切换按钮页面

### ISSUE THREAD

**Issue by lanxiner123** [alibaba/weex#1139]
一行有四个按钮，怎样通过手势滑动切换四个按钮模块页面呀，通过按钮点击可以做到，但是项目中有要求滑动也能实现，淘宝中这样的例子挺多的，请提供一下思路，谢谢！

**Comment by Jinjiang** [comment]
好问题，觉得有必要更多人充分讨论一下

**Comment by guogailee** [comment]
最好能够提供一个组件，支持点击切换和滑动切换，默认滑动切换false。

**Comment by lanxiner123** [comment]
我着重看了下scroller和slider, slider支持横向滑动，但里面是list的形式，只能展示类似轮播那样的，scroller还不能支持横向滑动？我写了demo，发现不行。建议可以在slider和scroller的基础上提供一个组件，类似于原生的scrollview,每页展示的内容可以自定义，并提供change事件，不知道淘宝里这种效果是用的weex还是用的原生的呢？

**Comment by haicuan139** [comment]
<scroller id="scroll" style="flex-direction: row" scroll-direction="horizontal" append="tree" position="{{$index}}">

**Comment by haicuan139** [comment]
` <scroller id="scroll" style="flex-direction: row" scroll-direction="horizontal" append="tree" position="{{$index}}">`

**Comment by lanxiner123** [comment]
可以了呀，我试的时候<scroller style="flex-direction: row" scroll-direction="horizontal">这样没滚动，现在这样写也可以了，肯定是我上午写的有点问题，再看到文档里的这句话The scroll direction of this component is column, and it can't be changed，谢谢！

**Comment by lanxiner123** [comment]
@haicuan139  虽然可以横向滚动，但是滚动的内容不是list的该怎么处理呢，横向滚动某个宽度后让别的样式改变该在哪个方法里添加呢，文档里没有position这个属性，请问position怎么运用呀，能不能加个扣扣或微信呀

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！

**Comment by wangweiqi23** [comment]
slider 或者 scroller 嵌套list android上运行都会报空指针 0.8.0.2版本的sdk
