### ISSUE TITLE
 ios_sliderComponent在数据刷新的时,未移除老的imageView.并导致老的Imageview空白.

### ISSUE THREAD

**Issue by zlit** [alibaba/weex#1141]
如题.slider绑定的list更新后.触发了数据绑定的刷新操作.插入新数据对应的imageView.但未移除老的imageView.
demo : http://weex.alibaba-inc.com/playground/9801c96187c46c0dc386126192fba95d
和凝砺反馈过.提个issue跟踪

**Comment by HJ-StevenSun** [comment]
我这儿也有这个 情况 要重新载入界面才会显示新的image

**Comment by Jinjiang** [comment]
@zlit 你贴的地址并不是外网可以访问的，建议在公开场合回避这方面信息，我这里先 close 了，相关讨论二位可以线下继续进行
谢谢理解

**Comment by chengweipeng123** [comment]
网址是内部的，但问题是公共的。
不好意思，我也遇到这个问题。
需要新开issue么？

**Comment by Jinjiang** [comment]
可以新开一个，注意回避内部信息和资料
