### ISSUE TITLE
TimerModule-clear操作无效

### ISSUE THREAD

**Issue by zlit** [alibaba/weex#1142]
因为从weex传到native的function,每次对应的callbackID不一致.导致以callbackID做key的clear操作无效.
两个平台都有这个问题.
必现.
demo暂略.

**Comment by zlit** [comment]
备注,找不到这个module对应的负责同学.请更新内部owner文档.

**Comment by Jinjiang** [comment]
@zlit timer module 只是作为 `setTimeout` 的 polyfill 存在的，callbackID 是其中的底层实现机制的一部分，从业务使用角度，建议直接使用 HTML5 Timer APIs.
这里我先关掉了，集团内部问题可以直接找我讨论
谢谢
