### ISSUE TITLE
examples咋跑？

### ISSUE THREAD

**Issue by shevaxp** [alibaba/weex#1143]
vue小白，webpack小白，求助:
   git clone下demo后，发现通过SCRIPTS.md的方法，还是跑不起demo，查不到解决方案，特来求助！
   在根目录下运行 npm run build:examples,报错：
   截取了部分，大同小异，找不到module
```
   ERROR in ./examples/animation.we?entry=true
Module not found: Error: Cannot resolve module 'babel-loader' in /home/mike/works/weex-dev/examples
 @ ./examples/animation.we?entry=true 3:22-287

ERROR in ./examples/iconfont.we?entry=true
Module not found: Error: Cannot resolve module 'babel-loader' in /home/mike/works/weex-dev/examples
 @ ./examples/iconfont.we?entry=true 3:22-286

ERROR in ./examples/index.we?entry=true
Module not found: Error: Cannot resolve module 'babel-loader' in /home/mike/works/weex-dev/examples
 @ ./examples/index.we?entry=true 2:22-283

ERROR in ./examples/template.we?entry=true
Module not found: Error: Cannot resolve module 'babel-loader' in /home/mike/works/weex-dev/examples
 @ ./examples/template.we?entry=true 3:22-286
```

另外：
    官方文档能否来一个实例教程？毕竟vue，webpack，weex-loader之类，还是小白。
    根据某文档，大约知道项目流程：
    weex init
    npm install
    npm run serve
    但是weex init后，就开始懵逼了，比如我要添加其他的we文件，在json里应该怎么添加？
    其他系统组件引用，是否需要其他配置？
    一开始准备examples来当教程研究这些，但是发现examples的config.js文件是放在外面主目录在。
   也许大牛们觉得很简单，都一样的，但是对我这种新手来说，上手真心很吃力，所以examples能否做成现成的demo？

**Comment by shevaxp** [comment]
https://github.com/alibaba/weex/issues/257
根据这个issue的回答，尝试
npm install 然后./start
依然模块报错
```
~/works/weex-dev ~/works/weex-dev

> weex@0.4.0 build:native /home/mike/works/weex-dev
> webpack --config build/webpack.native.config.js

Hash: 0a73423906101559853e
Version: webpack 1.13.2
Time: 41ms
    + 1 hidden modules

ERROR in Cannot find module 'babel-core'

> weex@0.4.0 build:browser /home/mike/works/weex-dev
> webpack --config build/webpack.browser.config.js

Hash: b9b21f34a32f1214f9b7
Version: webpack 1.13.2
Time: 36ms
    + 1 hidden modules

ERROR in Cannot find module 'babel-core'
```

**Comment by shevaxp** [comment]
继续自己填坑，继续报错
上面错误，是用的cnpm install，有些模块没有install下来（是config文件问题么？）
npm install babel-core后解决
继续./start或者npm run build:examples
出现：
```
ERROR in ./~/.0.3.0@weex-loader/lib/script.js!./~/.6.2.5@babel-loader?presets[]=es2015&presets=es2015&plugins[]=transform-runtime&plugins=transform-runtime&comments=false!./~/.0.3.0@weex-loader/lib/extract.js?index=0&type=scripts!./examples/syntax/template-style.we
Module build failed: Error: Cannot find module 'lodash/isPlainObject'
```

**Comment by shevaxp** [comment]
ERROR in ./html5/browser/base/component/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lazyload in /home/mike/works/weex-dev/html5/browser/base/component
 @ ./html5/browser/base/component/index.js 24:16-37

**Comment by Jinjiang** [comment]
@MrRaindrop please have a check for the last problem.
Thanks

**Comment by shevaxp** [comment]
```
ERROR in ./~/node_modules/.0.3.0@weex-loader/lib/script.js!./~/node_modules/.6.2.5@babel-loader?presets[]=es2015&presets=es2015&plugins[]=transform-runtime&plugins=transform-runtime&comments=false!./~/node_modules/.0.3.0@weex-loader/lib/extract.js?index=0&type=scripts!./~/weex-components/src/wxc-tabitem.we
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/home/mike/works/weex-dev-1/node_modules/weex-components/src"

```

另外，上面那个./lazyload重新看了下，是common里面跑出来的

感觉cnpm install后，还有这么多的找不到，是我的node_modules下载出的问题么？
环境：CentOS7，node v4.5.0，npm 2.15.9， cnpm 4.3.2

**Comment by shevaxp** [comment]
终于，终于，终于TMD跑通了。。。。太激动了。。。。
心得：
1.不知道是否npm和cnpm用root装的，还是因为本身项目中需要用到root。上面的若干node_module问题，在root下不会存在
2. ./lazyload问题，在weex/html5/browser/base/component下的lazyLoad.js应该改为lazyload.js

**Comment by MrRaindrop** [comment]
hi @shevaxp lazyload文件名的问题已经修复，见 https://github.com/alibaba/weex/pull/1115

**Comment by coderyi** [comment]
请问最后是怎么通过weex init跑起来的？@shevaxp

**Comment by coderyi** [comment]
最后可以通过下面命令解决

```
npm install babel-core

```
