### ISSUE TITLE
按照字母定位list项的需求

### ISSUE THREAD

**Issue by bryantwu** [alibaba/weex#1151]
来自gitter:

Hades-li @Hades-li 9月 06 17:31
美团 APP，在选择城市列表的界面，右侧有A-Z的城市首字母，就是用手划过这些字母进行快速定位的。
当然，像这种界面几乎在任何一个电商APP上都存在
weex貌似缺的东西还真不少。感觉离公测还有很------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------的路。

**Comment by haicuan139** [comment]
用Scroller 可以实现

**Comment by haicuan139** [comment]
List 也可以实现

**Comment by breg-jjb** [comment]
@haicuan139 点击某个字母然后定位功能，我使用dom.scrollToElement(this.$el('blist'));
想定位到id为blist的元素所在位置，但发现在playground中这样写不生效，请问你是如何处理的呢？

**Comment by haicuan139** [comment]
var dom = require('@weex-module/dom');
            dom.scrollToElement(this.$el('fktitle'), {offset: 0});

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
