### ISSUE TITLE
原生页面与weex页面数据传递问题

### ISSUE THREAD

**Issue by yfldj** [alibaba/weex#1155]
iOS。例如一个原生的列表页面push到一个weex写的详情页，详情页是用weex写的，怎么把原生列表的ID传到weex页面用作请求？是否有优雅一点的实现？现在的办法是本地保存ID，然后用storage module读取。。。求更好的办法

**Comment by haicuan139** [comment]
render 的时候可以传入json数据进去

**Comment by yfldj** [comment]
@haicuan139 好，谢谢！
