### ISSUE TITLE
滚动区的ScrollChange 支持

### ISSUE THREAD

**Issue by haicuan139** [alibaba/weex#1156]
我尝试通过修改Android 中的 Scroller组件中的procAppear方法，在滚动时 fireEvent 到weex 。不知道这样做效率是否OK，将来是否支持这样的功能？

**Comment by haicuan139** [comment]
# 通过下面代码将x,y坐标在 滚动的时候 发送到weex。
`//      Map<String,Object> rc = new HashMap<>();
//      rc.put("x",x+"");
//      rc.put("y", y + "");
//      WXSDKManager.getInstance().fireEvent(mInstanceId, mDomObj.ref, "scrollchange", rc);`

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
