### ISSUE TITLE
webview与weex的交互

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#1163]
某些应用场景下，webview与weex需要交互。
比如webview中执行某种操作成功后，点击webview中的按钮能让weex页面做出反应。
另外就是按返回键能对webview界面进行响应 而不是直接操作weex页面的返回。

可以考虑的方案是在webview中引入特定的js文件 作为webview与weex联系的纽带。

**Comment by xyduane** [comment]
我也很想有这个功能，因为有些功能必须在webview上面才能做

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！

**Comment by colys** [comment]
为什么要把这个issues关掉，这个功能是硬需求啊！

**Comment by likenow** [comment]
给 WXWebComponent 加一个 webview 与 native 交互的 bridge (比如：WebViewJavascriptBridge)，其实就和Hybird 开发一样
