### ISSUE TITLE
repeat 标签复用View

### ISSUE THREAD

**Issue by q757571446** [alibaba/weex#1164]
对于Android端TabLayout+ViewPager这种实现Tab切换时，扩展组件如下
```
<tab-pager>
   <tab-indicator items="{{items}}"></tab-indicator>
   <tab-content repeat="{{items}}"></tab-content>  
</tab-pager>
```
通过repeat标签创建ViewPager中每个View的实例，但由于没办法复用，导致每次切换一个tab，内存维护了上个view的实例，导致内存暴涨。
请问官方有什么方案解决复用问题吗

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
