### ISSUE TITLE
在下列机型中出现OutOfMemoryError 错误

### ISSUE THREAD

**Issue by huobaiyu** [alibaba/weex#1165]
在下列机型中报OutOfMemoryError 
三星GALAXY S4   三星GALAXY Note 3   三星SCH-N719(Galaxy Note II)   三星GALAXY SIII   三星GALAXY Mega 5.8   三星S7568   三星GALAXY Grand DUOS   三星GALAXY S5   

错误日志片段：
09-08 12:28:19.965E10435dalvikvm-heapOut of memory on a 263528-byte allocation.
09-08 12:28:20.055E10435AndroidRuntimeFATAL EXCEPTION: pool-5-thread-1
09-08 12:28:20.055E10435AndroidRuntimejava.lang.OutOfMemoryError
09-08 12:28:20.055E10435AndroidRuntimeat java.lang.String.&lt;init&gt;(String.java:354)
09-08 12:28:20.055E10435AndroidRuntimeat java.lang.String.&lt;init&gt;(String.java:228)
09-08 12:28:20.055E10435AndroidRuntimeat com.taobao.weex.http.WXStreamModule.readAsString(WXStreamModule.java:418)
09-08 12:28:20.055E10435AndroidRuntimeat com.taobao.weex.http.WXStreamModule$2.onResponse(WXStreamModule.java:362)
09-08 12:28:20.055E10435AndroidRuntimeat com.taobao.weex.http.WXStreamModule$StreamHttpListener.onHttpFinish(WXStreamModule.java:523)
09-08 12:28:20.055E10435AndroidRuntimeat com.taobao.weex.adapter.DefaultWXHttpAdapter$1.run(DefaultWXHttpAdapter.java:258)
09-08 12:28:20.055E10435AndroidRuntimeat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
09-08 12:28:20.055E10435AndroidRuntimeat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
09-08 12:28:20.055E10435AndroidRuntimeat java.lang.Thread.run(Thread.java:841)

**Comment by zshshr** [comment]
给个复现的页面@huobaiyu

**Comment by lycool** [comment]
Hi @huobaiyu, 请给出能复现此NullPointerException的一段示例代码，谢谢

**Comment by alext1981** [comment]
因目前无法得到复现代码或者更详细的log，本issue暂时关闭，如果 @huobaiyu 能提供更详细的信息，issue可以随时打开。
