### ISSUE TITLE
下列机型中出现NullPointerException

### ISSUE THREAD

**Issue by huobaiyu** [alibaba/weex#1166]
机型：
三星GALAXY S5   三星GALAXY Note 3   三星GALAXY Mega 5.8   
---
1-20 07:57:42.450E19086AndroidRuntimejava.lang.NullPointerException
01-20 07:57:42.450E19086AndroidRuntimeat android.widget.Editor.onTouchUpEvent(Editor.java:1927)
01-20 07:57:42.450E19086AndroidRuntimeat android.widget.TextView.onTouchEvent(TextView.java:8865)
01-20 07:57:42.450E19086AndroidRuntimeat com.taobao.weex.ui.view.WXEditText.onTouchEvent(WXEditText.java:238)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.View.dispatchTouchEvent(View.java:7817)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
01-20 07:57:42.450E19086AndroidRuntimeat com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2326)
01-20 07:57:42.450E19086AndroidRuntimeat com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1612)
01-20 07:57:42.450E19086AndroidRuntimeat android.app.Activity.dispatchTouchEvent(Activity.java:2494)
01-20 07:57:42.450E19086AndroidRuntimeat android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
01-20 07:57:42.450E19086AndroidRuntimeat com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2274)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.View.dispatchPointerEvent(View.java:8025)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4668)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4556)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4207)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4176)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4261)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4184)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4318)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4207)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4176)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4184)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6302)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6240)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6211)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6382)
01-20 07:57:42.450E19086AndroidRuntimeat android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)

**Comment by zshshr** [comment]
给个复现的页面@huobaiyu

**Comment by lycool** [comment]
Hi @huobaiyu, 请给出能复现此NullPointerException的一段示例代码，谢谢

**Comment by alext1981** [comment]
因目前无法得到复现代码或者更详细的log，本issue暂时关闭，如果 @huobaiyu 能提供更详细的信息，issue可以随时打开。
