### ISSUE TITLE
布局样式position定位的问题

### ISSUE THREAD

**Issue by jiangfei891111** [alibaba/weex#1167]
我用了position定位，用的是sticky这个选项，文档里说“sticky 指的是仅当元素滚动到页面之外时，元素会固定在页面窗口的顶部。” 我测试了下，元素滚出屏幕了，没有定位在顶部啊

**Comment by luics** [comment]
请给一下代码

**Comment by jiangfei891111** [comment]
<template>
  <div style="flex-direction: column;">
  <div style="height: 300;">
      <image class="img" style="background-color: #C0C0C0; position:relative;top: 200; left: 50;"></image>
    </div>
    <div style="height: 500;">
      <image class="img" style="background-color: black; position:absolute; top: 50; left: 50;opacity:0.7"></image>
    </div>
    <div style="height: 1000;opacity:0.5">
      <image  class="img" src="" style="background-color: blue;position: sticky;top:100"></image>
    </div>
    <div style="height: 1000;">
      <image  class="img"  src="" style="background-color: red;position: fixed; top: 40; left: 200;opacity:0.5"></image>
    </div>
  </div>
</template>
<style >
  .img{width: 200;height: 200;}
</style>


重点看position为sticky的

**Comment by jiangfei891111** [comment]
`<template>
  <div style="flex-direction: column;">
  <div style="height: 300;">
      <image class="img" style="background-color: #C0C0C0; position:relative;top: 200; left: 50;"></image>
    </div>
    <div style="height: 500;">
      <image class="img" style="background-color: black; position:absolute; top: 50; left: 50;opacity:0.7"></image>
    </div>
    <div style="height: 1000;opacity:0.5">
      <image  class="img" src="" style="background-color: blue;position: sticky;top:100"></image>
    </div>
    <div style="height: 1000;">
      <image  class="img"  src="" style="background-color: red;position: fixed; top: 40; left: 200;opacity:0.5"></image>
    </div>
  </div>
</template>
<style >
  .img{width: 200;height: 200;}
</style>`

**Comment by jiangfei891111** [comment]
重点看position设置为sticky的哦

**Comment by zshshr** [comment]
@jiangfei891111 该属性只有在list或scroller上生效，你的代码直接放在div里的？如何滚动的，刚才验证套上scroller标签以后，可以吸顶的

**Comment by Jinjiang** [comment]
iOS/Android 下实测换成 scroller 标签之后也是正常的，HTML5 版本似乎有点问题 @MrRaindrop 确认一下？

**Comment by jiangfei891111** [comment]
我是把div的高度设置很大，实现的滚动效果，用position的sticky 不好使，其他的都可以

**Comment by MrRaindrop** [comment]
@jiangfei891111 这个问题不是sticky的问题，而是weex-html5的scroller组件模拟滑动机制的限制决定的。**weex的根scroller组件必须具有不大于视口的高度**。而这点必须由开发者来保证，因为weex-html5本身无法控制weex容器（'#weex' 这个元素）所处的环境，这个完全由入口的 **index.html** 来控制。weex-html5本身无法假定可以使用 `flex:1` 来固定住`#weex`容器的高度，或者直接设置height来强制设定其高度。这个高度值只能且应该由用户自己来指定，这样可以满足不同用户对weex页面渲染位置以及大小的控制。所以你有两种方法解决此问题：

1. 如果你的页面是全屏页面，在 `index.html` 里将页面的 `#weex` 容器高度设置为 `100%`
2. 或者设置scroller的高度小于或等于视口的高度。

推荐解法 1 , 也是目前 weex 官方 project 的 h5 example 的[解决方式](https://github.com/alibaba/weex/blob/dev/index.html#L11-L14) ，这样你的 weex 代码也不需要因为端的不同而做任何改动。

**Comment by MrRaindrop** [comment]
https://github.com/alibaba/weex/issues/1195 类似问题
