### ISSUE TITLE
android分支下，weex_sdk下的img标签resize属性在android设备上无效

### ISSUE THREAD

**Issue by qbcbyb** [alibaba/weex#1170]
问题出在[ImageClipDrawable](https://github.com/alibaba/weex/blob/android/android/sdk/src/main/java/com/taobao/weex/ui/view/WXImageView.java#L320)上，没有看明白`ImageClipDrawable`具体起的是什么作用。暂时将
```
    if (drawable != null) {
      super.setImageDrawable(new ImageClipDrawable(drawable));
    } else {
      super.setImageDrawable(null);
    }
```
修改为`    super.setImageDrawable(drawable);`是可以的。

**Comment by YorkShen** [comment]
ImageClipDrawable是为了实现`background-clip:border-box`属性。比如存在`border-radius`，ImageClipDrawable会把图片截断成圆角图片

**Comment by YorkShen** [comment]
@qbcbyb 贴一下可复现问题的代码

**Comment by qbcbyb** [comment]
@YorkShen 我将img的`resize`设置为`contain`，但实际出来图片还是默认的`stretch`；另外`android`分支下的playground应用，里边image的demo就能看到该问题。

**Comment by YorkShen** [comment]
Fix by commit https://github.com/sospartan/weex/commit/35a434524fcd4343727765f14bac3c311781c6c2
