### ISSUE TITLE
ios 一旦页面报错白屏, 代码改为正确, 也无法恢复. 必须杀掉 app 重新扫码才行

### ISSUE THREAD

**Issue by teamrun** [alibaba/weex#1172]
```
weex sdk: 0.7.0
jsframework: 0.15.7
```

代码:

```
<style>
    .wrapper {
        background-color: #accded;
    }
</style>

<template>
    <div class="wrapper">
        <text logo-height="{{logoHeight}}">here is demo</text>
    </div>
</template>

<script>

    module.exports = {
        data: {
            logoHeight: 80
        },
        created: function () {
            nativeLog('parent created');
        },
        methods: {
            
        }
    }
</script>
```
bug重现流程:

0. `logo-height="{{logoHeight}}"`, 页面显示正常
0. `logo-height="{{this.logoHeight}}"`, 由于多加了一个 this, 页面白屏
0. 代码恢复正常`logo-height="{{logoHeight}}"`, 重新载入, 页面仍然白屏, 无法正常显示页面. playground 杀掉之后重新扫码, 才能看到正常的页面

看上去是同一个 url 对应的代码这么反复更改才会出这样的问题, 扫码url变化之后就不会有问题

**Comment by Jinjiang** [comment]
我自己 iOS 0.7.0 没有复现，刷新页面和扫码都是可以恢复正常的，可能需要联系你收集更多的信息进行重现

**Comment by Jinjiang** [comment]
我们近期在 Weex JS 稳定性方面又做了一定的改造和优化

这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
