### ISSUE TITLE
条件渲染时是否会考虑支持像Vue的v-show

### ISSUE THREAD

**Issue by blessyezi** [alibaba/weex#1174]
目前的if会删除dom，这在有的场景下会不友好。
比如在web组件和扩展的地图组件中使用if。

**Comment by misakuo** [comment]
`style="visibility: hidden"`呢？

**Comment by Jinjiang** [comment]
恩，关键是背后的 element 是否支持 display:none，目前还是不支持的，这个 issue 可以保持讨论和评估

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！

**Comment by yuanzx** [comment]
这个功能很实用啊，赶紧加上吧
