### ISSUE TITLE
loading 控件不显示的bug

### ISSUE THREAD

**Issue by haicuan139** [alibaba/weex#1179]
``` html
<loading class="refresh-view" display="{{loading_display}}" onloading="onloading">
      <text class="refresh-arrow" style="text-align: center; color:rgb(238, 162, 54)" if="{{(refresh_display==='hide')}}">Load more</text>
      <loading-indicator style="height:60;width:60;color:#3192e1"></loading-indicator>
</loading>
```

例子中的这个上啦加载的控件不显示

**Comment by xyduane** [comment]
我的也是，ios平台

**Comment by haicuan139** [comment]
这个loading 控件只有在 Scroller 上面才会显示。在list 上面是没有效果的

**Comment by xyduane** [comment]
@haicuan139   Scroller还是有问题
![image](https://cloud.githubusercontent.com/assets/3953237/18374138/d6592778-767c-11e6-8cb3-4e068c676247.png)

**Comment by happybobo** [comment]
那list里是用`refresh`？ @haicuan139

**Comment by haicuan139** [comment]
@happybobo  如果你一定要显示的话，这么做：把loading 这个标签放在list标签里面最顶端的位置
`<list >
            <loading class="loading-view" display="show" onloading="onloading" style="background-color: #0000ed">
                <loading-indicator style="height:60;width:60" ></loading-indicator>
                <text>asdasdasd</text>
            </loading>
<cell></cell>
</list>`

**Comment by cooliean** [comment]
Android 的是号号的，就是IOS有问题。
UI友好性太差了，这个下拉

**Comment by acton393** [comment]
你的if 语句里面  loading_status 的控制检查一下~
