### ISSUE TITLE
weex-toolkit 无法找到本机的本地 ip，显示为「true」

### ISSUE THREAD

**Issue by xieguanglei** [alibaba/weex#1180]
复现方法如截图所示：

![2016-09-09 10 01 44](https://cloud.githubusercontent.com/assets/2938447/18373259/2db2829c-7675-11e6-8c34-9d05fa652306.png)

我不知道需要提供怎样的环境信息，请告知一下（如果需要的话）

**Comment by lvscar** [comment]
谢谢 @xieguanglei 的反馈。   

使用 --qr 参数时，如果不需要专门指定IP地址  ，请不要再加上 -h 参数 （weex-toolkit 会自动尝试使用你的对外IP)
