### ISSUE TITLE
list控件bug

### ISSUE THREAD

**Issue by xyduane** [alibaba/weex#1181]
如截图所示，list标签，在ISO 9.3系统下，返回桌面然后进入APP，会出现空白条
开始页面：
![image](https://cloud.githubusercontent.com/assets/3953237/18373411/682c3f0c-7676-11e6-9bf6-29494c826d07.png)
返回桌面再次进入APP：
![image](https://cloud.githubusercontent.com/assets/3953237/18373404/5b063fda-7676-11e6-841d-775fbf3e5b81.png)

**Comment by luics** [comment]
提供一个复现问题的最小 demo

**Comment by xyduane** [comment]
`<template>
  <wxc-navpage data-role="none" height={{navBarHeight}}  title={{title}} background-color="#7777EA" title-color="white" left-item-title="" left-item-color="white" right-item-src="">
  <list class="list" loadmoreoffset=2000>
    <header class="header">
        <div class="col col-first" ><text class="header-text">基金名称</text></div>
        <div class="col" ><text class="header-text">单位净值</text></div>
        <div class="col" ><text class="header-text">日涨跌幅</text></div>
        <div class="col" ><text class="header-text">操作</text></div>
    </header>
    <cell class="cell"  repeat="{{fndlist}}"  append="tree">
            <div class="col col-first" ><text class="cell-text cell-first">测试{{$index}}</text><text class="cell-date"></text><text class="cell-date">{{navdate}}</text></div>
            <div class="col" ><text class="cell-text {{getColColor(nav)}}">{{nav}}</text></div>
            <div class="col" ><text class="cell-text {{getColColor(dayinc)}}">{{dayinc}}%</text></div>
            <div class="col" if="isActive(fundstatus)">
                  <wxc-button type="default" size="small"  value="{{getButtonText(fundstatus)}}"  style="width:120px;border-color:#26a4f4;font-color:#26a4f4;border-width:2px;"></wxc-button>
            </div>
            <div class="col" if="!isActive(fundstatus)">
                <text class="button-grey" style="">--</text>
            </div>
    </cell>
  </list>

  </wxc-navpage>
</template>

<style>
.header{
  flex-direction: row;
  height: 75;
  background-color: #dddddd;
}
.col{
  lex-direction: row;
  flex:1;
  justify-content:center;
  text-align: center;
  border-left-width: 1px;
  border-color:#fff;
}
.col-first{
  flex:2;
}
.header-text{
  font-size:24px;
  text-align: center;
}

.list {
  flex-direction: column;
  overflow: hidden;
  width: 750;
  height: 1200;
}

.cell {
  flex-direction: row;
  width: 750;
  height: 115px;
  border-bottom-width: 1px;
  border-color:#dfe5eb;
  margin-left: 15px;
  margin-right: 15px;
}
.cell-text{
  font-size:24px;
  font-weight:bold;
  text-align: center;
}
.cell-date{
  font-size:16px;
  text-align:left;
}
.cell-first{
  text-align: left;
}
.cell-color-red{
    color:red;
}
.cell-color-green{
    color:green;
}
.button-grey{
    width:120px;
    border-color:#e4e4e4;
    /*border-width:0px;*/
    height:60px;
    font-size:30px;
    text-align: center;
    justify-content:center;
    padding-top: 8px;
    color:#9e9e9e;
    border-radius: 8px;
}

</style>

<script>
    require('weex-components');
    var appService = require('./service/appService');
    var modalutil = require("./common/modalutil.js");
    module.exports = {
        data: {
          navBarHeight: 88,
          title: '基金列表',
          fndlist:[{navdate:'2016-08-09',nav:'1.23',dayinc:'1.111',fundstatus:'1'}],

        },
        ready:function(){

        },
        created:function(){
            this.$getConfig(function (config) {
                var env = config.env;
                if(env.platform == 'iOS'){
                  var scale = env.scale;
                  var deviceWidth = env.deviceWidth / scale;
                  this.navBarHeight = 64.0 * 750.0 / deviceWidth;
                }
            }.bind(this));
        },
        methods:{


           getColColor:function(data){
               return data>=0?'cell-color-red':'cell-color-green';
           },
           isActive:function(status){
               if(status==0 || status==1 || status==6||status==7||status==8){
                   return true;
               }
               return false;
           },
           getButtonText:function(status){
               return status==1?'认购':'申购';
           }

        }
    }
</script>
`
真机或模拟器上面运行，
修改WXDemoViewController.m文件
`- (void)viewDidLoad
{

    [super viewDidLoad];
    
    [self setupNaviBar];
    [self setupRightBarItem];
    
    self.view.backgroundColor = [UIColor whiteColor];

    _weexHeight = self.view.frame.size.height - 0;/*从65改成0*/

    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(notificationRefreshInstance:) name:@"RefreshInstance" object:nil];
    
    [self render];
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    [self updateInstanceState:WeexInstanceAppear];
    self.navigationController.navigationBarHidden=YES;/*前端用了bar,加上这句，要不然会显示2个navigationBar*/
}`

**Comment by xyduane** [comment]
----------------
<template>
  <wxc-navpage data-role="none" height={{navBarHeight}}  title={{title}} background-color="#7777EA" title-color="white" left-item-title="" left-item-color="white" right-item-src="">
  <list class="list" loadmoreoffset=2000>
    <header class="header">
        <div class="col col-first" ><text class="header-text">基金名称</text></div>
        <div class="col" ><text class="header-text">单位净值</text></div>
        <div class="col" ><text class="header-text">日涨跌幅</text></div>
        <div class="col" ><text class="header-text">操作</text></div>
    </header>
    <cell class="cell"  repeat="{{fndlist}}"  append="tree">
            <div class="col col-first" ><text class="cell-text cell-first">测试{{$index}}</text><text class="cell-date"></text><text class="cell-date">{{navdate}}</text></div>
            <div class="col" ><text class="cell-text {{getColColor(nav)}}">{{nav}}</text></div>
            <div class="col" ><text class="cell-text {{getColColor(dayinc)}}">{{dayinc}}%</text></div>
            <div class="col" if="isActive(fundstatus)">
                  <wxc-button type="default" size="small"  value="{{getButtonText(fundstatus)}}"  style="width:120px;border-color:#26a4f4;font-color:#26a4f4;border-width:2px;"></wxc-button>
            </div>
            <div class="col" if="!isActive(fundstatus)">
                <text class="button-grey" style="">--</text>
            </div>
    </cell>


  </list>

  </wxc-navpage>
</template>

<style>
.header{
  flex-direction: row;
  height: 75;
  background-color: #dddddd;
}
.col{
  lex-direction: row;
  flex:1;
  justify-content:center;
  text-align: center;
  border-left-width: 1px;
  border-color:#fff;
}
.col-first{
  flex:2;
}
.header-text{
  font-size:24px;
  text-align: center;
}

.list {
  flex-direction: column;
  overflow: hidden;
  width: 750;
  height: 1200;
}

.cell {
  flex-direction: row;
  width: 750;
  height: 115px;
  border-bottom-width: 1px;
  border-color:#dfe5eb;
  margin-left: 15px;
  margin-right: 15px;
}
.cell-text{
  font-size:24px;
  font-weight:bold;
  text-align: center;
}
.cell-date{
  font-size:16px;
  text-align:left;
}
.cell-first{
  text-align: left;
}
.cell-color-red{
    color:red;
}
.cell-color-green{
    color:green;
}
.button-grey{
    width:120px;
    border-color:#e4e4e4;
    /*border-width:0px;*/
    height:60px;
    font-size:30px;
    text-align: center;
    justify-content:center;
    padding-top: 8px;
    color:#9e9e9e;
    border-radius: 8px;
}
</style>

<script>
    require('weex-components');
    var appService = require('./service/appService');
    var modalutil = require("./common/modalutil.js");
    module.exports = {
        data: {
          navBarHeight: 88,
          title: '基金列表',
          fndlist:[{navdate:'2016-08-09',nav:'1.23',dayinc:'1.111',fundstatus:'1'}],

        },
        ready:function(){

        },
        created:function(){
            this.$getConfig(function (config) {
                var env = config.env;
                if(env.platform == 'iOS'){
                  var scale = env.scale;
                  var deviceWidth = env.deviceWidth / scale;
                  this.navBarHeight = 64.0 * 750.0 / deviceWidth;
                }
            }.bind(this));
        },
        methods:{


           getColColor:function(data){
               return data>=0?'cell-color-red':'cell-color-green';
           },
           isActive:function(status){
               if(status==0 || status==1 || status==6||status==7||status==8){
                   return true;
               }
               return false;
           },
           getButtonText:function(status){
               return status==1?'认购':'申购';
           }

        }
    }
</script>
--------------------------------



修改WXDemoViewController.m文件
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- (void)viewDidLoad
{

    [super viewDidLoad];
    
    [self setupNaviBar];
    [self setupRightBarItem];
    
    self.view.backgroundColor = [UIColor whiteColor];

    _weexHeight = self.view.frame.size.height - 0;// 65改成0

    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(notificationRefreshInstance:) name:@"RefreshInstance" object:nil];
    
    [self render];
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    [self updateInstanceState:WeexInstanceAppear];
    self.navigationController.navigationBarHidden=YES;/*加上这句，要不然会显示2个navigationBar*/
}
~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by xyduane** [comment]
`<template>
  <wxc-navpage data-role="none" height={{navBarHeight}}  title={{title}} background-color="#7777EA" title-color="white" left-item-title="" left-item-color="white" right-item-src="">
  <list class="list" loadmoreoffset=2000>
    <header class="header">
        <div class="col col-first" ><text class="header-text">基金名称</text></div>
        <div class="col" ><text class="header-text">单位净值</text></div>
        <div class="col" ><text class="header-text">日涨跌幅</text></div>
        <div class="col" ><text class="header-text">操作</text></div>
    </header>
    <cell class="cell"  repeat="{{fndlist}}"  append="tree">
            <div class="col col-first" ><text class="cell-text cell-first">测试{{$index}}</text><text class="cell-date"></text><text class="cell-date">{{navdate}}</text></div>
            <div class="col" ><text class="cell-text {{getColColor(nav)}}">{{nav}}</text></div>
            <div class="col" ><text class="cell-text {{getColColor(dayinc)}}">{{dayinc}}%</text></div>
            <div class="col" if="isActive(fundstatus)">
                  <wxc-button type="default" size="small"  value="{{getButtonText(fundstatus)}}"  style="width:120px;border-color:#26a4f4;font-color:#26a4f4;border-width:2px;"></wxc-button>
            </div>
            <div class="col" if="!isActive(fundstatus)">
                <text class="button-grey" style="">--</text>
            </div>
    </cell>


  </list>

  </wxc-navpage>
</template>
`

**Comment by xyduane** [comment]
//<template>
//  <wxc-navpage data-role="none" height={{navBarHeight}}  title={{title}} background-color="#7777EA" title-color="white" left-item-title="" left-item-color="white" right-item-src="">
//  <list class="list" loadmoreoffset=2000>
//    <header class="header">
//        <div class="col col-first" ><text class="header-text">基金名称</text></div>
//        <div class="col" ><text class="header-text">单位净值</text></div>
//        <div class="col" ><text class="header-text">日涨跌幅</text></div>
//        <div class="col" ><text class="header-text">操作</text></div>
//    </header>
//    <cell class="cell"  repeat="{{fndlist}}"  append="tree">
//            <div class="col col-first" ><text class="cell-text cell-first">测试{{$index}}</text><text class="cell-date"></text><text class="cell-date">{{navdate}}</text></div>
//            <div class="col" ><text class="cell-text {{getColColor(nav)}}">{{nav}}</text></div>
//            <div class="col" ><text class="cell-text {{getColColor(dayinc)}}">{{dayinc}}%</text></div>
//            <div class="col" if="isActive(fundstatus)">
//                  <wxc-button type="default" size="small"  value="{{getButtonText(fundstatus)}}"  style="width:120px;border-color:#26a4f4;font-color:#26a4f4;border-width:2px;"></wxc-button>
//            </div>
//            <div class="col" if="!isActive(fundstatus)">
//                <text class="button-grey" style="">--</text>
//            </div>
//    </cell>
//  </list>

//  </wxc-navpage>
//</template>

//<style>
//.header{
//  flex-direction: row;
//  height: 75;
//  background-color: #dddddd;
//}
//.col{
//  lex-direction: row;
//  flex:1;
//  justify-content:center;
//  text-align: center;
//  border-left-width: 1px;
//  border-color:#fff;
//}
//.col-first{
//  flex:2;
//}
//.header-text{
//  font-size:24px;
//  text-align: center;
//}

//.list {
//  flex-direction: column;
//  overflow: hidden;
//  width: 750;
//  height: 1200;
//}

//.cell {
//  flex-direction: row;
//  width: 750;
//  height: 115px;
//  border-bottom-width: 1px;
//  border-color:#dfe5eb;
//  margin-left: 15px;
//  margin-right: 15px;
//}
//.cell-text{
//  font-size:24px;
//  font-weight:bold;
//  text-align: center;
//}
//.cell-date{
//  font-size:16px;
//  text-align:left;
//}
//.cell-first{
//  text-align: left;
//}
//.cell-color-red{
//    color:red;
//}
//.cell-color-green{
//    color:green;
//}
//.button-grey{
//    width:120px;
//    border-color:#e4e4e4;
//    /*border-width:0px;*/
//    height:60px;
//    font-size:30px;
//    text-align: center;
//    justify-content:center;
//    padding-top: 8px;
//    color:#9e9e9e;
//    border-radius: 8px;
//}

//</style>

//<script>
//    require('weex-components');
//    var appService = require('./service/appService');
//    var modalutil = require("./common/modalutil.js");
//    module.exports = {
//        data: {
//          navBarHeight: 88,
//          title: '基金列表',
//          fndlist:[{navdate:'2016-08-09',nav:'1.23',dayinc:'1.111',fundstatus:'1'}],

//        },
//        ready:function(){

//        },
//        created:function(){
//            this.$getConfig(function (config) {
//                var env = config.env;
//                if(env.platform == 'iOS'){
//                  var scale = env.scale;
//                  var deviceWidth = env.deviceWidth / scale;
//                  this.navBarHeight = 64.0 * 750.0 / deviceWidth;
//                }
//            }.bind(this));
//        },
//        methods:{


//           getColColor:function(data){
//               return data>=0?'cell-color-red':'cell-color-green';
//           },
//           isActive:function(status){
//               if(status==0 || status==1 || status==6||status==7||status==8){
//                   return true;
//               }
//               return false;
//           },
//           getButtonText:function(status){
//               return status==1?'认购':'申购';
//           }

//        }
//    }
//</script>

**Comment by xyduane** [comment]
代码贴上来乱了，看下截图
![image](https://cloud.githubusercontent.com/assets/3953237/18375101/8563bf78-7685-11e6-86a1-ef84d556ab5c.png)

WXDemoViewController.m 改了2个地方，以免重复显示navigationBar
![image](https://cloud.githubusercontent.com/assets/3953237/18375118/bba1daac-7685-11e6-84ec-afe296ab97a7.png)

**Comment by cxfeng1** [comment]
@xyduane 麻烦提供一下代码， 可以删减一些内部逻辑再传上来

**Comment by kfeagle** [comment]
@xyduane 我这边创建了一个类似的例子，复现了你的遇到的现象，类似的现象会在首页出现，基本上每个系统版本都会有
这个现象出现的原因是：设置navigationBarHidden=YES;表明这个viewcontroller不再采用系统自动布局，而系统布局属性 automaticallyAdjustsScrollViewInsets 默认值是YES

你需要在
 - (void)viewDidLoad这个函数添加一句
self.automaticallyAdjustsScrollViewInsets = NO;

你的代码我完整修改如下，你可以试试效果，看看是否解决你遇到的情况：

```javascript
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    
    [self setupNaviBar];
    [self setupRightBarItem];
    self.view.backgroundColor = [UIColor whiteColor];
    self.automaticallyAdjustsScrollViewInsets = NO;  //我添加的代码
    _weexHeight = self.view.frame.size.height - 0; //从65改为0
    
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(notificationRefreshInstance:) name:@"RefreshInstance" object:nil];
    
    [self render];
}
```

**Comment by alext1981** [comment]
This issue is resolved. If this solution could not solve your problem, you could add more information and reopen this issue again, @xyduane , thanks!
