### ISSUE TITLE
list控件的问题

### ISSUE THREAD

**Issue by squirrelx** [alibaba/weex#1184]
list的height要不要显示的设置？
我发现如果一个页面的比如有三个组件，上面两个组件比如占用了手机屏幕高度的1/3，此时如果你想让第三个组件可以上下滑动，加上list cell标签后，会存在有内容超过手机屏幕下方都不能拖动的情况，除非把list的内容数据给的更多，才有可能可以滑动。    

是不是list的默认height是手机整个屏幕的高度啊？（而不管的这个组件其实只占用屏幕的比如2/3的高度啊）

**Comment by jinyue-rdj** [comment]
Android还是iOS？

**Comment by squirrelx** [comment]
@jinyue-rdj   android

**Comment by Jinjiang** [comment]
list 没有默认高度，需要手动设定，或通过 flexbox 样式撑开
更多讨论来 gitter 吧 https://gitter.im/weexteam/cn
这里我先关掉了
