### ISSUE TITLE
android: 键盘收起事件

### ISSUE THREAD

**Issue by hanai** [alibaba/weex#1185]
Andorid 上收起键盘的时候不会触发 input 上的 blur 事件，我有没有办法获得android键盘收起这个事件呢？

**Comment by SimonTal** [comment]
目前临时的解决方案是 用oninput监听每一次键入 然后存入变量中，之后对这个变量做判断或者后续处理就行了。

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
