### ISSUE TITLE
[IOS] 关于playground

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1186]
ios 的 playground 使用的 sdk 好像版本很低，stream.fetch 与 html5的表现不一致，也无法使用 storage

ios 的 playground  中 stream.fetch 的 callback 返回的 res中 没有 status 等，而是直接把服务端返回的数据作为 res 了

以及，weex 中无法使用 Promise 么， 我尝试引入 es6-promise 却会报出错误`VM12590:5181 Uncaught TypeError: document.createTextNode is not a function`

**Comment by acton393** [comment]
@lmnsg  建议直接使用 dev分支的playground 编译安装，
不过按理来说 res 中没有 status  这个，应该不合理， 你用的playground的版本是多少， 是在哪获得的

**Comment by lmnsg** [comment]
@acton393 我是使用的 Appstore 里的 weex playground 扫码预览的.. 感觉 appstore 里的 sdk 版本应该很低，手头还没法弄 xcode...

关于 Promise 的这个问题何解？

**Comment by Jinjiang** [comment]
AppStore 的更新会晚一些，我们会尽快更新
另外我们已经内置了 Promise 的 polyfill，所以上层不必再加入，报错的问题我们需要一个过程逐步淘汰掉模拟的 document 全局变量，是已知问题
谢谢

**Comment by lmnsg** [comment]
@Jinjiang 关于 Promise 这个东西，是 babel 的 polyfill 的问题确实..  有没有临时解决方案呢？

**Comment by Jinjiang** [comment]
这个跟主仓库关系不大了，在 weex-loader 里这个仓库里讨论吧 https://github.com/weexteam/weex-loader
