### ISSUE TITLE
在tabbar-demo.we中，关于item中src路径的问题

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#1197]
## 准备

我是在weex正式版0.7版本中的examples直接修改的index.we文件，然后将[tabbar-demo.we](https://github.com/alibaba/weex/blob/dev/examples/component/tabbar/tabbar-demo.we)文件中的代码覆盖了index.we文件，并且注释了created函数，因为没明白（尴尬），然后发现不影响UI的效果。

## 问题
当我修改后，先用`npm run build`，然后启动 `./start`，发现所有的item中src页面都是`404 Not Found`. 并且我把第一个界面的路径换成我自己写的文件，结果也是404.

## 解决方法
经过了很多次的折腾，我达到了我要的效果，解决方法如图。
![image](https://cloud.githubusercontent.com/assets/12522809/18408722/ae449824-7769-11e6-940d-c7f23feae5d8.png)

## 疑问？？？
对比一下上面三个path， 1和2是经过修改的，能够加载成功，3源码中的，是`404 Not Found` 

### 问题1：
path1：是我自己添加的文件路径，看源码中，在启动整个项目的服务后，只要写一个相对路径就OK了，应该是`Modules/HomePage/HomePage.js`这样，但实际上这样是404，加上`examples/`后才能正常显示。
好奇为什么加`examples/`，并且加上算是一个绝对路径吗？

### 问题2：
path2中，是我修改源码的路径去达到能够显示的效果， 对比可以发现一个很奇怪的问题，它不但加了`examples/`,还需要加上build路径才能显示，`examples/build/component/tabbar/tabbar-item.js?itemId=tab2`这条路径是准确定位到js文件的。
奇怪的地方就是为什么path2需要build路径，但path1不需要？？？

### 求解哈，-_-

**Comment by luics** [comment]
这个 issue 在推进 path #497

**Comment by emptywalker** [comment]
@luics    这个算是他本身存在的问题吗？ 表示真的是找的好辛苦哈，希望可以得到比较好改善

**Comment by emptywalker** [comment]
表示尴尬了，一开始我将下面的这个created方法注释了，所以path3才会不显示的，我把这个函数打开后台，发现之前的路径是没问题的。这个方法对三端的路径做了兼容哈
```
created: function() {
        var bundleUrl = this.$getConfig().bundleUrl;
        console.log('hit', bundleUrl);
        var nativeBase;
        var isAndroidAssets = bundleUrl.indexOf('file://assets/') >= 0;
        var isiOSAssets = bundleUrl.indexOf('file:///') >= 0 && bundleUrl.indexOf('WeexDemo.app') > 0;
        if (isAndroidAssets) {
          nativeBase = 'file://assets/';
        }
        else if (isiOSAssets) {
          // file:///var/mobile/Containers/Bundle/Application/{id}/WeexDemo.app/
          // file:///Users/{user}/Library/Developer/CoreSimulator/Devices/{id}/data/Containers/Bundle/Application/{id}/WeexDemo.app/
          nativeBase = bundleUrl.substring(0, bundleUrl.lastIndexOf('/') + 1);
        }
        else {
          var host = 'localhost:12580';
          var matches = /\/\/([^\/]+?)\//.exec(this.$getConfig().bundleUrl);
          if (matches && matches.length >= 2) {
            host = matches[1];
          }
          nativeBase = 'http://' + host + '/' + this.dir + '/build/';
        }
        var h5Base = './' + this.dir + '/build/';
        // in Native
        var base = nativeBase;
        if (typeof window === 'object') {
          // in Browser or WebView
          base = h5Base;
        }

        for(var i = 0; i < this.tabItems.length; i++) {
            var tabItem = this.tabItems[i];
            tabItem.src = base + tabItem.src;
        }
        // see log in Android Logcat
        //if (this.items.length) console.log('hit', this.items[0].url);
    },
```

表示对自己没话说哈

**Comment by luics** [comment]
这个方法最初就是为了兼容 ios 打包、ios 连 server

**Comment by emptywalker** [comment]
表示从iOS转到这个，看这些还有点吃力 @luics

**Comment by luics** [comment]
@emptywalker 有道理，应该更简化逻辑， 后续关注 #497 ，这个先关了
