### ISSUE TITLE
require 没法引入模块，是我的问题，还是weex的一个bug，求大神帮我解释一下？

### ISSUE THREAD

**Issue by lisiyizu** [alibaba/weex#1206]
## **＝＝＝＝＝＝test.js 文件＝＝＝＝＝＝＝＝**
![image](https://cloud.githubusercontent.com/assets/12014252/18428119/cf55c934-78fe-11e6-8060-57a5b5482b16.png)

## **＝＝＝＝＝＝引入文件 test.js 模块＝＝＝＝**
![image](https://cloud.githubusercontent.com/assets/12014252/18428071/7ea851f0-78fe-11e6-8b74-3110c8a7905a.png)

## **＝＝＝＝＝＝test.js  ，bundle之后的代码 ＝＝＝＝**
![image](https://cloud.githubusercontent.com/assets/12014252/18428354/11c169a8-7900-11e6-9f3f-c3339d74d907.png)

## **＝＝＝＝＝＝报错了＝＝＝＝＝＝＝＝＝＝**
![image](https://cloud.githubusercontent.com/assets/12014252/18428158/f83a5586-78fe-11e6-8af3-f02ab33965bb.png)

**Comment by StanNing** [comment]
@vczero 问一下这个问题和 #1200 里面的问题是不是一个情况啊？可以合并处理吗？

**Comment by vczero** [comment]
@StanNing 不是同一个问题。 #1200  的问题可能是module 扩展问题。
