### ISSUE TITLE
项目中出现内存警告并闪退

### ISSUE THREAD

**Issue by lanxiner123** [alibaba/weex#1208]
我在iOS项目中集成了weex并扩展了拍照上传图片的module，但是拍照上传时，就会出现内存警告还闪退，提示Message from debugger: Terminated due to memory issue,
单独测试没有问题,这时候需要怎么解决内存过大的问题呀，谢谢！

**Comment by vczero** [comment]
@cxfeng1

**Comment by cxfeng1** [comment]
@lanxiner123 最好先用Instruments的allocation分析一下， 内存的增长主要来自于哪些调用，从你的描述来看， 内存泄露更有可能是出现在扩展Module本身

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
