### ISSUE TITLE
[Discuss] eventTarget and Element.getBoundingClientRect() feature support

### ISSUE THREAD

**Issue by amdgigabyte** [alibaba/weex#121]
在一些复杂的交互场景中，例如网易新闻中的「点击文章中的视频占位图，展开播放视频」的效果，需要获取到当前点击的占位图的位置，因此需要WEEX在点击eventTarget的时候通过类似DOM操作getBoundingClientRect来获取元素距离屏幕视野top和left的位置值，然后再创建动画，因此，需要weex提供类似getBoundingClientRect这样的api，返回被点击元素的top,left，width，height的值

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
