### ISSUE TITLE
数据绑定之前台界面刷新bug

### ISSUE THREAD

**Issue by squirrelx** [alibaba/weex#1211]
在created里边使用stream方法调用后台服务，在stream的回调里边修改了界面的数据绑定变量 变量值修改后 界面有时会根据新值渲染 有时不会，举例代码如下，有时候div就能正常显示，有时候就不能，但是从界面能看出留了一段高度在那。android手机

```html
<template>
   <div style="height: 500; width: 500; background-color: red" if={{xxx}}></div>
</template>
<script>
   module.exports={
      data: {
         xxx:false;
      },
      created:function() {
         var stream = require('@weex-module/stream');
         stream.fetch({***}, function(res){xxx=true;}, function(res){});
      }
   }
</script>
```

**Comment by squirrelx** [comment]
以上是示例代码，绑定的数据确实被修改了，但是界面渲染可能不正确，如果界面元素很多比较容易出现，如果很少需要频繁切换页面才能重现
感觉是回调引起，如果不在回调里边，直接在created下写this.xxx=true就没有问题

**Comment by SimonTal** [comment]
确实会有此类问题，目前我是结合promise 让所有异步请求都返回后，再使用 if 的xxx = true 来让界面渲染解决的，虽然网络延迟时会有白屏一小会，但总比不可控的渲染结果要好！

**Comment by squirrelx** [comment]
@SimonTal  这个是bug吧  后续会解决不

**Comment by Jinjiang** [comment]
把

`stream.fetch({***}, function(res){xxx=true;}, function(res){});` 改为：  
`stream.fetch({***}, function(res){this.xxx=true;}.bind(this), function(res){});`

btw: 原 issue 要想展示整段代码，需要连写三个 ` (backquote) 我已经帮你编辑过了，不要介意

**Comment by squirrelx** [comment]
@Jinjiang   这个问题和闭包没有关系 我issue举例代码不严谨，我真实的代码是在最外层var vm=this;然后在stream里边用的是vm.xxx=true;    
这个问题 我暂时通过引入timer组件，通过settimeout 延迟500ms搞定的，类似于：
stream.fetch({***}, function(res){timer.setTimeout(function(e){vm.xxx = true;}, 500)}, function(res){});
这样前台刷新基本没问题，暂时不完美的规避的

**Comment by squirrelx** [comment]
@Jinjiang 这个问题木有解决呢。。  咋关闭issue了呢 能重开不

**Comment by Jinjiang** [comment]
那你改成 `var rm = this; stream.fetch({***}, function(res){vm.xxx=true;}, function(res){});` 应该也是可以的，不需要 timer
另外 timer module 是用来给 setTimeout 做 polyfill 的，直接当 HTML5 Timer APIs 用就可以，不要这样用

**Comment by squirrelx** [comment]
@Jinjiang 这个问题的根本是绑定的数据刷新过来 但是前台界面和数据不对应啊，可能是界面渲染的时序或者别的什么bug导致， 我用timer就是为了晚一点去修改数据  这样前台就可以顺利的展示了，  应该是不完美的规避了bug。。。  您没理解我说的bug点在哪  这个和闭包没有关系呢
@SimonTal 您给帮忙解释解释。。。

**Comment by Jinjiang** [comment]
我找到另外一个问题，你不能在根元素上写 if/repeat
https://github.com/alibaba/weex/blob/dev/doc/syntax/display-logic.md

```html
<template>
  <div>
    <text>Hello</text>
    <div style="height: 500; width: 500; background-color: red" if={{xxx}}></div>
  </div>
</template>
<script>
  module.exports = {
    data: function () {
      return {
        xxx: false
      }
    },
    ready: function () {
      var stream = require('@weex-module/stream');
      var GET_URL = 'http://httpbin.org/get';
      stream.fetch({
        method: 'GET',
        url: GET_URL,
      }, function (res) {
        this.xxx = true;
      }.bind(this), function (res) {
      });
    }
  };
</script>
```

上述代码实测在 iOS / HTML5 下工作

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
