### ISSUE TITLE
'bash' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by guowang1102** [alibaba/weex#1214]
> weex@0.4.0 postinstall E:\weex-dev
> bash ./bin/install-hooks.sh

'bash' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! weex@0.4.0 postinstall: `bash ./bin/install-hooks.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weex@0.4.0 postinstall script 'bash ./bin/install-hooks.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the weex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash ./bin/install-hooks.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls weex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\weex-dev\npm-debug.log

**Comment by Jinjiang** [comment]
属于 windows 环境问题，请参考 README 里提供的 windows 下的建议 https://github.com/alibaba/weex#for-windows
谢谢
