### ISSUE TITLE
weex后续有木有全局的状态管理方案？

### ISSUE THREAD

**Issue by lisiyizu** [alibaba/weex#1215]
**## 我的问题如下图，我们目前没法去在 list.js 和 cart.js 里通过 event(dispatch 和 on) 去修改 checkGoodsCount属性，weex有没有提供一个全局的状态管理方案了？**

![image](https://cloud.githubusercontent.com/assets/12014252/18463666/5f73cfe2-79be-11e6-84b7-a0116a19659f.png)

**Comment by vczero** [comment]
@lisiyizu
暂时先使用storage吧。
后续的讨论在此：https://github.com/alibaba/weex/issues/959

**Comment by Jinjiang** [comment]
这里的“全局”有两种理解，一种是同一个页面里所有组件的全局数据，这部分可以使用 `weex-x` https://www.npmjs.com/package/weex-x
另一种理解是整个App的全局状态管理，这部分我们建议通过 storage 来做，如有希望有更多讨论，如上所述，可以在 #959 
谢谢
