### ISSUE TITLE
weex module navigator增加隐藏导航栏的方法

### ISSUE THREAD

**Issue by jiuyuegui** [alibaba/weex#1216]
***新需求***
weex module  navigator增加隐藏导航栏的方法

**Comment by jinyue-rdj** [comment]
该需求已经录入，目前0.9版本已经在开发中，我们会在下个版本的需求规划评审会上进行讨论，届时给您 答复

**Comment by jiuyuegui** [comment]
好的~

**Comment by jiuyuegui** [comment]
@jinyue-rdj 
另外提一个需求，还是导航栏相关

导航栏的透明效果，大概如下

![导航栏透明](https://gw.alicdn.com/tps/TB1TGicNpXXXXapXFXXXXXXXXXX-374-92.png)

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
