### ISSUE TITLE
iOS crash because of privacy-sensitive data access without usage description

### ISSUE THREAD

**Issue by liujianying** [alibaba/weex#1217]
This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by jinyue-rdj** [comment]
Thank you for your advice，please check this question.@cxfeng1 @gurisxie

**Comment by acton393** [comment]
如果是AppStore上的playground： 
iOS 10 适配这个已经做了~，我们会尽快提交一下， 建议先使用工程中编译安装

**Comment by kiritmodi2702** [comment]
in iOS 10, Have to added some permission of private data uses. so You have added Privacy setting code in Info.plist. See the tutorial [https://iosdevcenters.blogspot.com/2016/09/infoplist-privacy-settings-in-ios-10.html](url) permission code in info.plist
