### ISSUE TITLE
ATSDK-Weex搜索不到

### ISSUE THREAD

**Issue by gulei** [alibaba/weex#1220]
我pod install 官网的playground提示ATSDK-Weex 失败
pod --version
1.0.1
pod search ATSDK-Weex
[!] Unable to find a pod with name, author, summary, or descriptionmatching ATSDK\-Weex

**Comment by Jinjiang** [comment]
我的 pod 也是 1.0.1 可以正常安装
另外 https://cocoapods.org/?q=ATSDK-Weex 这里是可以搜到 ATSDK-Weex 的
ATSDK-Weex 主页 https://cocoapods.org/pods/ATSDK-Weex
可能还是需要您再次确认一下 cocoapods 的环境
更多使用疑问来 gitter 吧 https://gitter.im/weexteam/cn
谢谢
