### ISSUE TITLE
异步数据多层级渲染的问题

### ISSUE THREAD

**Issue by YL2014** [alibaba/weex#1224]
情景如下：
我在data里指定一个数据info，`data: {info: {}}`，然后异步获取数据赋值给这个info，异步数据格式大致如下

```
info: {
  list: [{"a":1, "b":2},{"a":1, "b":2}],
  obj: {"c":3, "d":4},
  pro: "e"
}
```

问题1：
在我上面拿到的数据里，如果直接在template里repeat数据里的info.list，compiler.js会报错：`Uncaught TypeError: Cannot read property 'slice' of undefined`
问题2：
对于上面数据里的info.obj.c，这样的数据在模板里直接使用会拿不到

暂时解决办法：
在data显示声明层级数据：`data:{info:{list:[], obj:{}}}`，然后就可以了

在使用vue的时候是不需要显示指定多层级数据的，这个以后会支持吗，还是说必须得显示指定呢

**Comment by Jinjiang** [comment]
你的暂时解决办法是对的，我们暂没有支持的计划，但欢迎大家贡献pr
p.s. 未来我们拥抱Vue2.0了，你说的Vue的这些好处也是我们拥抱他的原因
