### ISSUE TITLE
weex navigator  转场动画如何修改

### ISSUE THREAD

**Issue by liujianying** [alibaba/weex#1230]
业务场景: 现在部分模块采用原生页面采用自定义转场动画,现在部分weex  navigator 转场动画于原生styl不一致,请问navigator 的专场效果如何定制化

 url(stirng): 界面Url路径.
 animated(string): 界面跳转动画.  ture flase 
 callback(object): 跳转成功回调.

暂时没有找到可以设置

**Comment by liujianying** [comment]
作为小白,最终答案, 多看看源码,答案都在里面,发现weex 越玩越给力

**Comment by alext1981** [comment]
请参考WXNavigatorModule的实现，现在的实现只是创建了新的intent并启动，你可以写自己的navigator并注册给WXSDKEngine，这样就可以根据项目的实际需要定制打开方式和转场动画

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
