### ISSUE TITLE
发现repeat的扩展英文文档有错误

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#1233]
```
<div repeat="{% raw %}{{(k, v) in list}}{% endraw %}">
  <text>No. {{k + 1}}, {{v.nickname}}</text>
</div>
```
根据这种方式去获取repeat的索引，会报错，不能够找到`this.k`这个方法，我将`{% raw %}{{(k, v) in list}}{% endraw %}` -> `{{(k, v) in list}}`即可正常运行，希望能够修改一下文档 :)

## 建议，能否将`k`修改成`index`这样便于理解

**Comment by Jinjiang** [comment]
got 我晚些时候处理一下
Thanks

**Comment by lvscar** [comment]
fix it , thx @emptywalker
