### ISSUE TITLE
stream.fetch 错误

### ISSUE THREAD

**Issue by LiushuiXiaoxia** [alibaba/weex#1235]
[fg255,0,0; <Weex>[error]WXMonitor.m:166, Module:stream, the parameters in calling method [fetch] and registered method [fetch:callback:progressCallback:] are not consistent

下面是代码，在Android上面可以正常运行，iOS上面发生上面的错误。
```javascript
        var stream = require('@weex-module/stream');
        var url = "https://news-at.zhihu.com/api/4/start-image/1080*1776";
        stream.fetch({
            method: 'GET',
            url: url,
            type:'json'
        }, function(response) {
          var json = response.data
          me.img = json.img;
          me.text = json.text;
        });
```

**Comment by pavlos123** [comment]
iOS后边需要加上function(progress) 的回调

**Comment by LiushuiXiaoxia** [comment]
ths

**Comment by acton393** [comment]
@LiushuiXiaoxia options, callback, progresscallback,参数都必须写上, 参考  http://alibaba.github.io/weex/doc/modules/stream.html
