### ISSUE TITLE
Android 如何设置光标的颜色？

### ISSUE THREAD

**Issue by hanai** [alibaba/weex#1238]
目前用的 android 分支的代码，input 中闪动的光标是白色的，背景是白的话就看不到了，有哪里可以设置光标颜色的吗？

**Comment by Jinjiang** [comment]
我们没有提供这种定制能力，但是闪动时光标默认颜色影响识别的话，是需要改一下……

**Comment by sospartan** [comment]
目前android系统没有提供API来设置光标颜色,默认的光标颜色应该是跟Application/Activity theme中的textview/edittext相关的,建议你通过修改theme来实现.

**Comment by zzb-zzb** [comment]
光标的默认颜色是怎么来的，怎么取修改呢
