### ISSUE TITLE
[Android] WXStreamModule.fetch 优化建议

### ISSUE THREAD

**Issue by lanceliu** [alibaba/weex#1239]
开发过程中有一个http请求是使用post方法，在iOS和H5下面是OK的，在android上面请求报错，经调查Andriod平台下http method只能是大写的。

以下两种建议二选一：
1. 建议在Android中把客户端传过来的http method 做大写统一转换；
2. Stream文档中明确提出必须要大些method;

**Comment by sospartan** [comment]
好建议,欢迎你发个PR来实现这些优化 👍

**Comment by lanceliu** [comment]
# @sospartan 好的，晚上补一下

**Comment by lanceliu** [comment]
@sospartan
已经提交PR
