### ISSUE TITLE
如何刷新一个页面呢

### ISSUE THREAD

**Issue by chenhuan888** [alibaba/weex#1243]
如何刷新一个UI页面呢  在android中是一个activity  在weex中是一个weex文件，里面怎么刷新呢?
refresh是模拟的刷新页面，并没有真正刷新数据

**Comment by Jinjiang** [comment]
刷新一个页面其实就是在原地销毁旧的页面创建一个新的页面，新页面的 bundle url 和旧的页面相同，具体可以参考源代码里Playground刷新按钮的逻辑

**Comment by LiuKaiXiang** [comment]
weex自身怎么实现刷新
