### ISSUE TITLE
Android iconfont 出错

### ISSUE THREAD

**Issue by hanai** [alibaba/weex#1244]
android 上使用 iconfont 无效，使用的是 android 分支上的 playground。

![screenshot_2016-09-19-11-11-09-540_weex](https://cloud.githubusercontent.com/assets/1222115/18622226/1b149ebc-7e5f-11e6-9454-9de1113e6a6a.png)

手机型号：SM705
Android 版本：4.4.2
Smartisan OS 版本：v2.6.8

**Comment by Jinjiang** [comment]
看你 #825 里也提到了，这里我先关掉了
谢谢
