### ISSUE TITLE
项目 logo 不好看

### ISSUE THREAD

**Issue by tinyao** [alibaba/weex#1246]
希望阿里或社区的设计师帮忙设计一个好看点的 logo
现在这个 [logo](http://alibaba.github.io/weex/) 有点尴尬呀，不太优雅，比较生硬。在多种排版需求情况下，也会遇到一定问题

![image](https://cloud.githubusercontent.com/assets/1461251/18629308/51aa180c-7e97-11e6-897b-ab93f2358be0.png)

我是认真的 😂

**Comment by Jinjiang** [comment]
谢谢你的建议，logo 的问题团队会做内部讨论，这里还是先关掉了[握手]
