### ISSUE TITLE
为什么我浏览器打开we文件，却显示源代码？？

### ISSUE THREAD

**Issue by xu17** [alibaba/weex#1248]
环境配置完成如下
![filehelper_1474273262662_69](https://cloud.githubusercontent.com/assets/20675437/18626834/edf7841e-7e89-11e6-9dbf-b40e2947d670.png)
操作如下
![filehelper_1474275651405_55](https://cloud.githubusercontent.com/assets/20675437/18626947/c407d09a-7e8a-11e6-8bf2-9aee8c44678c.png)
显示如下
![filehelper_1474275685715_](https://cloud.githubusercontent.com/assets/20675437/18626955/d0359afa-7e8a-11e6-8b81-aa0e3ac89279.png)

**Comment by misakuo** [comment]
using `weex tech_list.we` to launch browser

**Comment by xu17** [comment]
@misakuo I‘m sorry that I sent a wrong picture，it should be this one
![filehelper_1474278530799_22](https://cloud.githubusercontent.com/assets/20675437/18628238/dc1b0a2e-7e91-11e6-92b5-058e644cef99.png)

but it still doesn't work

**Comment by misakuo** [comment]
![QQ20160919-0.png](http://ooo.0o0.ooo/2016/09/19/57dfbead36317.png)

**Comment by Jinjiang** [comment]
正常情况下运行整个命令会自动打开浏览器，然后打开一个localhost的网址。目测是因为整个localhost的网址没有正常打开。可以在 weex-toolkit 里开个 issue https://github.com/weexteam/weex-toolkit/issues 转述你遇到的问题，并提供尽量详尽的环境
谢谢

**Comment by xu17** [comment]
@Jinjiang 谢谢
