### ISSUE TITLE
weex windows环境下npm run build失败

### ISSUE THREAD

**Issue by esioncao** [alibaba/weex#1253]
执行步骤：
1、weex init（成功）
2、npm install （成功）
3、npm run build （失败）如下图：
![image](https://cloud.githubusercontent.com/assets/4424631/18655762/2a828aca-7f1e-11e6-9a10-8878f854bf43.png

**Comment by 280772270** [comment]
https://github.com/alibaba/weex/issues/1218

**Comment by Jinjiang** [comment]
@terrykingcha @lvscar 有劳关注一下
谢谢

**Comment by Jinjiang** [comment]
大家移步到 #1218 讨论吧，这里我先关掉了
