### ISSUE TITLE
weex **.we --qr报错

### ISSUE THREAD

**Issue by q624228096** [alibaba/weex#1254]
windows系统
1、weex init
2、 npm install
3、weex **.we --qr
在第三步的时候就包这个错了
ERR! ReferenceError: Unknown plugin "D:\Users\****\AppData\Roaming\n
pm\node_modules\weex-toolkit\node_modules\weex-loader\node_modules\babel-p
lugin-transform-runtime" specified in "base" at 0, attempted to resolve relative
to "F:\week\week\we"

一直报这个错，不知道什么原因，求帮忙啊

**Comment by 280772270** [comment]
https://github.com/alibaba/weex/issues/1218

**Comment by lvscar** [comment]
感谢 @q624228096 的反馈， 请使用 weex --version 命令看一下你的weex-toolkit版本. 并给我们反馈一下.

**Comment by esioncao** [comment]
@lvscar 我有同样的问题 windows7 下面
![image](https://cloud.githubusercontent.com/assets/4424631/18661132/e28e83a8-7f46-11e6-8928-16675b5c0a1f.png)

**Comment by jiangfei891111** [comment]
这个0.5.2版本问题挺多啊，执行weex main,we也报错

**Comment by lvscar** [comment]
谢谢反馈。 我开始看一下！

**Comment by q624228096** [comment]
这个问题，我退回0.4.0版本，就不报这个错了

**Comment by lvscar** [comment]
@q624228096  @esioncao  @jiangfei891111  请试一下最新的 weex-toolkit@0.5.3 看看这个问题在你们的场景下还会出现吗?

**Comment by lvscar** [comment]
seems latest weex-loader fix works. thx @dickeylth

**Comment by t-hong** [comment]
是不是win环境不太稳定，其他环境要好点
