### ISSUE TITLE
关于动态更新

### ISSUE THREAD

**Issue by AFRE001** [alibaba/weex#1255]
感觉一直找不到一个比较好的实践，有如下问题：
- 问题一：如果将we编译后的js直接放在服务端，则客户端每次打开页面都需要下载JS，会浪费比较多的流量。 如果缓存在本地以减少反复请求，则要考虑如何即时刷新的问题，不知这块有没有推荐的实践？
- 问题二：动态更新时服务端JS的版本管理有没有推荐做法？ 因为有时候升级不单单js升级，可能会连带升级外面的壳，还有出问题时回滚，有没有建议机制？

**Comment by Jinjiang** [comment]
JS 文件可以在上层采用一些缓存或预加载的机制，这方面和HTML5的最佳实践是完全一致的
服务器端一般分为覆盖式发布和非覆盖式发布，回滚本身就是一个新的发布，只不过版本号都是增加的但内容和旧版本一样
这个话题比较大，不产生明确的action，放在issue里不是很合适，我这里先关掉了，谢谢理解
