### ISSUE TITLE
Weex Roadmap

### ISSUE THREAD

**Issue by AFRE001** [alibaba/weex#1257]
weex 项目有具体的Roadmap吗？ 阶段计划，目标什么的。 这样的话会让跟随者更有信心，觉得是有计划在做事，不然感觉做到哪算哪给人不安全的感觉，也不专业。。纯属个人感觉。

**Comment by Jinjiang** [comment]
团队会讨论一下，通过一些合理的方式公布出来，issue 我先关掉了
谢谢
