### ISSUE TITLE
text组件text-align:center 属性在ios无效

### ISSUE THREAD

**Issue by liujianying** [alibaba/weex#1260]
================================================
代码如下扫描后在H5  Android 均能够正常居中显示,但是在ios显示不能居中
代码是git上最新的 ios10 iPhone5s

<pre>
&lt;template&gt;
       &lt;div style="background-color:red"&gt; 
            &lt;text class='textq'&gt;我 -- 的&lt;/text&gt;
       &lt;/div&gt;
&lt;/template&gt;
&lt;style&gt;
	.textq {
		font-size: 50pt;
		color: #cc0000;
		text-align: center;
		line-height: 500;
		width: 150px;
		background-color: #3e999f;
	}
&lt;/style&gt;
</pre>
================================================

![wechatimg49](https://cloud.githubusercontent.com/assets/6265414/18662486/2cb3906c-7f4d-11e6-93e2-2c38f5e177bf.jpeg)

**Comment by acton393** [comment]
hi @liujianying  我验证了一下，跟line-height 有冲突,具体原因我会查一下，你暂时可以先取消通过height来设置一下，

```
<template>
       <div style="background-color:red"> 
            <text class='textq'>我 -- 的</text>
       </div>
</template>
<style>
    .textq {
        font-size: 50;
        color: #cc0000;
        text-align: center;
        width: 300px;
        height:500px;
        background-color: #3e999f;
    }
</style>
```

**Comment by liujianying** [comment]
好的,谢谢

**Comment by lmnsg** [comment]
@acton393 这个问题解决了么， 发现在 ios 上不仅 text-align 无法使用，包括 line-height 都无法获得正确的显示。

**Comment by acton393** [comment]
@liujianying  @lmnsg  找到原因，是一个bug， 属性被冲掉了， 已经提bugfix #1285 ，应该可以修复

**Comment by acton393** [comment]
这个应该已经修复了，先关闭这个issue，有问题可以再继续打开

**Comment by lmnsg** [comment]
@acton393 好像还不行哦...  我从 dev分支 上 copy最新的 sdk，text-aligin 已经可以使用了，但是依然 line-height 无法获得正常的效果。

**Comment by acton393** [comment]
pod install 的时候显示仍然是6.0   这个主要是因为 weexSDK的 podspec里面版本号 一直没有更新

你git pull 过后， 是 以下几种哪一种：

- text-align 和 line-height 联合起来不能用，
- line-height 不能用
- line-height 显示不正常

**Comment by lmnsg** [comment]
@acton393 line-height 显示不正常

**Comment by acton393** [comment]
hi  @lmnsg  这个issue 是提到这两个style连起来使用有问题， 已经fix

line-height ios 上显示不正常可以参考下这个 [faq](http://alibaba.github.io/weex/doc/faq.html#ios-text-line-height-style-is-abnormal)

podspec  这个已经 update  #1330
