### ISSUE TITLE
点击 inspector什么东西都不出现

### ISSUE THREAD

**Issue by zhuruliang** [alibaba/weex#1261]
![image](https://cloud.githubusercontent.com/assets/14215749/18662547/66388c0c-7f4d-11e6-8eeb-266ca5fe0611.png)

**Comment by yangshengtao** [comment]
现在devtool repo迁移到https://github.com/weexteam/weex-devtool-iOS里面了，后续提issue可以到新repo，这个repo马上就删掉了

**Comment by littleseven** [comment]
@RLZHU 你好~，是你集成的调试工具版本教老引起的，尚不具备screencast功能。在较新的版本中才支持此功能和高亮~
android最新版本0.0.8.0,地址 https://github.com/weexteam/weex_devtools_android
ios最新版本0.7.0.19,地址  https://github.com/weexteam/weex-devtool-iOS

可参考其中文文档接入

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
