### ISSUE TITLE
gulp-weex支持输出语法错误等信息

### ISSUE THREAD

**Issue by moldauder** [alibaba/weex#1266]
gulp-weex在执行时，如遇到语法错误等没有提示输出，仍能正常通过。但在执行页面渲染时， 则会报错误。建议gulp-weex本身能支持此功能，方便提早定位到问题。如下面代码中的错误：

```
style="{{opacity:{{dataItem.opacity}}}}“
```

**Comment by songsiqi** [comment]
针对这条，`gulp-weex` 有报错 `WARNING: `{{opacity` is not a standard property name`。

logLevel的设置见[这里](https://github.com/weexteam/gulp-weex#loglevel)

**Comment by moldauder** [comment]
got it @songsiqi
