### ISSUE TITLE
ios10 playground push pop异常

### ISSUE THREAD

**Issue by osindex** [alibaba/weex#1269]
今天早上升级了ios10 发现编写的程序打开之后白屏(切换startSplashScreen之后)
用xcode run 提示代码如下（只有这一句）：
Error compiling builtin: Invalid private name '@capabilities'

机型：iphone6 
版本：ios10.0.1 
weexsdk:0.7

然后 继续运行了本机装着的playground 发现
More Syntax后的一系列Hello World
以及Navigator push 也是白屏.

**Comment by osindex** [comment]
remark.

**Comment by acton393** [comment]
hello， @osindex  麻烦提供一下更多的情况：
playground用的是AppStore上的还是dev分支的编译的， 
如果是dev分支的，麻烦问下SDK 你用的是cocoaPods 的版本还是dev的源码

有没有尝试在模拟器上会有问题么

**Comment by osindex** [comment]
@acton393 
用的是dev分支 dev的sdk~

看到回复后 下载了AppStore的 playground 发现里面是pop是正常 用正常playground扫码之后 仍然空白。

按道理来说 playground的扫码 就是用playground的引擎渲染么？

**Comment by acton393** [comment]
hi，@osindex  我尝试代码如下， 没有发现啥问题， 你可以试试下
```
<template>
<container>
    <text style="margin-top: 50px"onclick='onclick1'>click Me </text>
  </container>
</template>

<script>
  module.exports = {
    methods: {
      onclick1: function (e) {
        console.log('you clicked me!!!');
        var testpro = new Promise(function (resolve,reject){
          setTimeout(function(){
            console.log('jjj');
            resolve('finish');
            // reject('failed');
          },1000);
          resolve('finish')
        });
        // console.log('P:', typeof Promise);
        testpro.then(function(e){
          nativeLog('then');
          console.log(e);
        });
      },
    },
  }
</script>


```

**Comment by osindex** [comment]
@acton393 
抱歉，赶着工期，没来得及具体解决了。应该是iossdk的问题 最后决定把Promise全部删除了~
采用正常的函数方法来加载~

**Comment by Neeeo** [comment]
同有这个问题，iOS10， promise无法用。 weexSDK 0.7.0, iOS 10 .1没问题

**Comment by cxfeng1** [comment]
@Neeeo  是否还有Promise在iOS10的问题？ 我这边试了都是OK的， 是否能给一个demo

**Comment by Neeeo** [comment]
@cxfeng1 Weex SDK 更新到 0.8.0后没有问题了。

**Comment by cxfeng1** [comment]
好， 如果还有任何问题， 欢迎重新打开这个issue讨论， @Neeeo
