### ISSUE TITLE
[Android] 点击 scroller 中的 input，弹出的键盘会挡到 input

### ISSUE THREAD

**Issue by hanai** [alibaba/weex#1271]
Android 中点击 scroller 中的 input，弹出的键盘会挡到 input。

**Comment by misakuo** [comment]
在Weex容器所属的Activity（playground里是`WXPageActivity`）的`onCreate`方法里加上
```java
getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN);
```    
或在`AndroidManifest.xml`文件内Activity声明的地方加上    
```xml
android:windowSoftInputMode="adjustPan"
```    
即可。    
`SoftInputMode`还有很多取值，具体可见[Android官方文档](https://developer.android.com/guide/topics/manifest/activity-element.html#wsoft)

**Comment by hanai** [comment]
@misakuo 还是有点问题，加上之后，点击 input，弹出键盘后，scroller只能向上滚，不能向下滚了。

**Comment by misakuo** [comment]
@hanai 
还有另一个Mode`SOFT_INPUT_ADJUST_RESIZE`，不过这个Mode只在页面的根布局是一个可滚动组件的情况下才适用，系统会压缩根布局的高度，也就不会把title顶出去了。目前weex的native布局层级还比较复杂，所以暂时应该只能使用上面的方法

**Comment by misakuo** [comment]
@hanai 还有一个`SOFT_INPUT_ADJUST_RESIZE`的mode，只能在Activity根布局是可滚动组件的情况下使用，目前weex容器内的布局情况比较复杂，暂不能支持该mode

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
