### ISSUE TITLE
android x86 cpu 设备是否支持？

### ISSUE THREAD

**Issue by ShanZha** [alibaba/weex#1275]
我看官方demo里有这么几行代码：
if(!WXSoInstallMgrSdk.isCPUSupport()){
      mProgressBar.setVisibility(View.INVISIBLE);
      mTipView.setText(R.string.cpu_not_support_tip);
      return;
    }
<string name="cpu_not_support_tip">Sorry, your current device is x86 architecture.\n We only support arm architecture devices!</string>

说不支持x86的设备，请问确实如此吗？

**Comment by ShanZha** [comment]
我发现我被demo的提示语给骗了，源码里应该是不支持mips，而非x86
public static boolean isCPUSupport(){
    String cpuType = _cpuType();
    return !cpuType.equalsIgnoreCase(MIPS);
  }

 public static boolean initSo(String libName, int version, IWXUserTrackAdapter utAdapter) {
    String cpuType = _cpuType();
    if (cpuType.equalsIgnoreCase(MIPS) ) {
      return false;
    }
//非mips则继续初始化so库
}

**Comment by ShanZha** [comment]
希望有个官方的说明，谢谢
另外，gitter里的聊天模式感觉不适合问题的归档，别把我关闭了让我去那里了

**Comment by sospartan** [comment]
x86已经支持的,mips不支持.
