### ISSUE TITLE
js设置组件获取和离开焦点功能

### ISSUE THREAD

**Issue by jingxin2015** [alibaba/weex#1277]
1、场景描述：在信息录入的时候，比如登录界面，输入用户名，直接点击登录按钮，应该提示请输入密码之后焦点自动定位到密码输入框。
2、相关组件：text、textarea、dropdown。

**Comment by alext1981** [comment]
感谢  @jingxin2015 提出的需求，该feature将在0.9.x版本中实现， 本issue将被关闭。待feature上线后如果需要进一步讨论，可reopen该issue或开新的issue。
