### ISSUE TITLE
关于scroll 在ios上无法滑动

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1279]
我在 ios使用0.7.0的 sdk
scroller 在 ios 端无法滑动

**Comment by acton393** [comment]
scroller 应该是在contentSize 大于 Scroller 的高度的时候才可以滑动的

**Comment by lmnsg** [comment]
@acton393  app 大部分页面是都可以滑动的嘛， 我现在为了让它滑起来就换了 list 组件，但是从语义上觉得很别扭...

**Comment by acton393** [comment]
@lmnsg  你换成list 就可以滑动了么?  可以提供一下你的之前不能滑动的 weex code不 ， 我看一下

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
