### ISSUE TITLE
ios 如何获取渲染view的大小？

### ISSUE THREAD

**Issue by LWnoheart** [alibaba/weex#1287]
我初始化WXSDKInstance对象，并赋值了四个block：onCreate、onFailed、renderFinish、onRenderProgress。然后用renderWithURL来渲染view。但是我没有办法通过这四个block得到渲染view的大小。而且现在我也不知道通过何种方式来限制渲染大小，设置WXSDKInstance的viewController或frame都没达到想要的效果。请问我该怎么获得和限制渲染大小呢？

**Comment by LWnoheart** [comment]
经测试当展示后加个button人为手动触发打印WXSDKInstance的rootView的frame为正确的，但是在WXSDKInstance对象的所有回调中都不正确。而且WXSDKInstance对象的state永远是0，frame永远是{{0, 0}, {0, 0}}？那我应该在什么回调中第一时间知道渲染view的大小呢？

**Comment by acton393** [comment]
限制渲染 view的大小，可以通过，设置instance.frame 来设置
[example](https://github.com/alibaba/weex/blob/dev/ios/playground/WeexDemo/WXDemoViewController.m#L99)

**Comment by LWnoheart** [comment]
但是获得渲染后view的大小呢，尤其是异步的渲染？

**Comment by LWnoheart** [comment]
@acton393 什么时候有这种异步渲染完成的回调呢？我想通过获得异步渲染完成后的view大小

**Comment by acton393** [comment]
@LWnoheart  我们已经做了获得 view 的 还有view中某个组件大小的功能， 在后面版本会提供，后面可以尝试一下

**Comment by LWnoheart** [comment]
@acton393 您好，我这由于项目集成限制，不能用pod集成，我用你们自带的生成WeexSDK.framework库来集成进项目并且导入了SocketRocket。然后运行项目后打印“[fg255,0,0; <Weex>[error]WXMonitor.m:166, framework loading is failure! [;”。相应的所有渲染都不起作用也不报错。这是因为什么呢？

**Comment by acton393** [comment]
hi @LWnoheart  在WeexSDK.framework 里面有main.js 的文件，需要将它添加到copy resource里面， 
可以参考这里 https://github.com/acton393/WeexOCExample/

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
