### ISSUE TITLE
Feature or enhance advise

### ISSUE THREAD

**Issue by erguotou520** [alibaba/weex#1291]
## 建议
- 使用本地资源地址，或者可以通过类似于`this.$rootPath+'/images/abc.png'`的方式获取本地存储文件地址
- 支持`vh`单位，因为宽度总值为`750px`，但高度总值并不确定，有些场景还是需要的
- 是否有类似`vue-devtools`的调试工具？我看到的`weex`的`devtools`好像并不是这种功能，不过有个临时方案（不知道weex有没有自定义过滤器，如果有那更简单了）
  ```js
  module.exports = {
    data: {
      foo: {foo: 1}
    },
    computed: {
      bar: function () {
        return JSON.stringify(this.foo, null, 2)
      }
    }
  }
  ```
- `wxc-tabbar`组件中使用图标时只能用图片（而且还是服务器图片，好累啊。。）？是否可以用svg或者iconfont（顺便问下不支持本地资源路径的话iconfont如何在css中定义）？
- 类似于`wxc-navpage`和`wxc-tabbar`的组件是否可以自行组装？因为我看`wxc-navpage`的event好奇怪啊。。。
- 是否可以自定义页面间切换的动画？因为有的可能从下而上呢。
- 是否支持css3的动画、阴影和模糊之类的样式？因为这些在布局时还是很有用的
- 是否可以像`Vue`那样执行`Vue.use`来添加插件？
- 继续跟踪中。。。

**Comment by Jinjiang** [comment]
@erguotou520 Vue 里存在的功能我们会努力把 Vue 在 Weex 上适配好，就不基于目前的 JS Framework 了，另外几个问题我建议你作为独立的 issue 列出来，我们逐个跟进讨论
谢谢

**Comment by kfeagle** [comment]
#2709
