### ISSUE TITLE
为什么我执行内置组件的例子的时候，会报错？

### ISSUE THREAD

**Issue by xu17** [alibaba/weex#1292]
第一个实例没错，正常运行
![filehelper_1474550879084_88](https://cloud.githubusercontent.com/assets/20675437/18756342/2c7932ec-8122-11e6-8b2c-66f9e81c836d.png)
![filehelper_1474551604112_91](https://cloud.githubusercontent.com/assets/20675437/18756351/3344e85a-8122-11e6-99cb-34a3b34a352d.png)
但是第二个，也就是添加内置组件的实例，程序报错；我有检查代码，发现没有问题，错误如下
![filehelper_1474551234750_17](https://cloud.githubusercontent.com/assets/20675437/18756382/53a92af2-8122-11e6-9b66-f568f3a6b7ff.png)
请问，这是什么问题，缺少组件还是什么？

**Comment by hanai** [comment]
https://github.com/alibaba/weex/issues/1281

**Comment by xu17** [comment]
@hanai 貌似错误类型跟那个不同

**Comment by lvscar** [comment]
latest version of weex-toolkit should fix the bug
