### ISSUE TITLE
[PR]weex中怎么刷新控件

### ISSUE THREAD

**Issue by voidxin** [alibaba/weex#1298]
[PR]请教一下怎么刷新控件呢，比如有个<text class="title">字体是黑色，我想在网络请求获取到数据之后改变这个<text>的字体颜色或点击状态（是否可点击），我应该怎么做呢？在<script>获取到这个标签作修改吗，怎么获取呢，求指导一下，谢谢

**Comment by misakuo** [comment]
```vue
<template>
  <text value="{{value}}" style="color:{{textColor}};"></text>
</template>

<script>
  module.exports = {
    data: {
      textColor: '#FF0000',
    }
  }
</script>
```    
像上面这样将属性绑定到一个变量上，后面就能通过改变这个变量的值来实现相应属性的更改

**Comment by voidxin** [comment]
@misakuo 解决了，非常感谢^-^
