### ISSUE TITLE
window系统,sdk 0.7.0版本，执行start报错：Module not found: Error: Cannot resolve 'file' or 'directory' ./config in F:\weex-work-space\weex-0.7.0\weex-0.7.0\html5\runtime

### ISSUE THREAD

**Issue by yuxingfafu** [alibaba/weex#1299]
> weex@0.4.0 build:browser F:\weex-work-space\weex-0.7.0\weex-0.7.0
> webpack --config build/webpack.browser.config.js

Hash: 28a5c40b0f6db1ff67c8
Version: webpack 1.13.2
Time: 11370ms
     Asset    Size  Chunks             Chunk Names
browser.js  1.6 MB       0  [emitted]  main
    + 201 hidden modules

ERROR in ./html5/runtime/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./config in F:\weex-work-space\weex-0.7.0\weex-0.7.0\html5\runtime
 @ ./html5/runtime/index.js 8:14-33

> weex@0.4.0 serve F:\weex-work-space\weex-0.7.0\weex-0.7.0
> serve ./ -p 12580

> weex@0.4.0 dev:examples F:\weex-work-space\weex-0.7.0\weex-0.7.0
> webpack --watch --config build/webpack.examples.config.js

**Comment by xu17** [comment]
同问

**Comment by Jinjiang** [comment]
可能是中间有些步骤失败了，根据错误信息建议你手动运行一下 `npm run build:config` 再看
谢谢

@xu17 @yuxingfafu
