### ISSUE TITLE
navigator 是否可以提供 replace 方法？

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1304]
目前navigator 只有pop 和 push 控制跳转和返回，但却没有实现 replace 方法，假如在登录页面登录后，用户可以直接左划屏幕返回到登录页面，以及在首页左滑会返回到引导页。。。

会不会提供一个replace方法来完成跳转却不留记录呢?

**Comment by Jinjiang** [comment]
暂时没有支持的计划，但欢迎开发者来贡献这个feature
谢谢

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
