### ISSUE TITLE
a 标签中如何打开新的we文件

### ISSUE THREAD

**Issue by lxf1002273683** [alibaba/weex#1306]
需要打开新的页面，不想使用html文件。该怎么实现

**Comment by acton393** [comment]
可以参考下这个文档 [doc](http://alibaba.github.io/weex/doc/components/a.html)
[example](https://github.com/alibaba/weex/blob/dev/examples/component/a-demo.we)

**Comment by lxf1002273683** [comment]
案例中a标签链接的是js文件打开之后就是代码，是哪里出问题了吗？
[代码如下]
`<template>
  <scroller>
    <wxc-panel title="Hyperlink" type="primary">
      <a href="http://g.tbcdn.cn/ali-wireless-h5/res/0.0.16/hello.js">
        <wxc-tip type="info" style="margin-bottom: 20px;"
          value="Click me to see how 'A' element opens a new world."></wxc-tip>
      </a>
    </wxc-panel>
  </scroller>
</template>

<script>
  require('weex-components');
  module.exports = {
    data: {
      img: '//gw.alicdn.com/tps/i2/TB1DpsmMpXXXXabaXXX20ySQVXX-512-512.png_400x400.jpg'
    }
  }
</script>`

**Comment by lxf1002273683** [comment]
a标签点击后，直接打开链接的js文件

**Comment by acton393** [comment]
@lxf1002273683  打开之后显示的js内容么？  h5 还是Android，iOS ？
提供一下weex 的代码看一下~

**Comment by lxf1002273683** [comment]
`<template>
  <scroller>
    <wxc-panel title="Hyperlink" type="primary">
      <a href="http://g.tbcdn.cn/ali-wireless-h5/res/0.0.16/hello.js">
        <wxc-tip type="info" style="margin-bottom: 20px;"
          value="Click me to see how 'A' element opens a new world."></wxc-tip>
      </a>
    </wxc-panel>
  </scroller>
</template>

<script>
  require('weex-components');
  module.exports = {
    data: {
      img: '//gw.alicdn.com/tps/i2/TB1DpsmMpXXXXabaXXX20ySQVXX-512-512.png_400x400.jpg'
    }
  }
</script>`
是在h5中测试的

**Comment by lxf1002273683** [comment]
[就是example中的代码](https://github.com/alibaba/weex/blob/dev/examples/component/a-demo.we)

**Comment by lxf1002273683** [comment]
手机端扫码 可以打开http://g.tbcdn.cn/ali-wireless-h5/res/0.0.16/hello.js  显示正常
在pc浏览器中测试直接打开文件，有没有解决方案

**Comment by MrRaindrop** [comment]
h5的a标签只是封装了简单的页面跳转，并没有根据url去生成新的weex页面。解决方案是在url里配置一个拦截规则，然后把url设置为包含降级和拦截规则的完整url.如果在h5页面中打开则直接进入降级h5页面，如果是在你的客户端打开，可以通过拦截规则打开native的页面。

**Comment by lxf1002273683** [comment]
@MrRaindrop 有没有参考文档，或者实例呢？接触不是很久，不会设置 ....

**Comment by MrRaindrop** [comment]
如果没有做拦截规则，可以简单的根据platform判断一下环境，如果是web下，则把url稍做修改，保证url指向的是一个weex-html5入口index.html文件，而bundle文件的url只是它的page参数，实例代码：

```html
<template>
  <a href="{{url}}"><text>GO</text></a>
</template>

<script>
module.exports = {
  data: { url: '//xxx.com/your/bundle.js' },
  created: function () {
    var platform = this.$getConfig().env.platform.toLowerCase()
    if (platform === 'web') {
       this.url = '//xxx.com/a/url/to/your/weex-html5/page.html?page=' + this.url
    }
  }
}
</script>
```

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
