### ISSUE TITLE
把example全部删除掉，然后把WeexOne项目直接拷贝到example目录下，浏览器打开和android手机打开都报函数找不到

### ISSUE THREAD

**Issue by yuxingfafu** [alibaba/weex#1307]
![image](https://cloud.githubusercontent.com/assets/7764483/18830051/9acd93d6-8411-11e6-9302-a93cdf939e08.png)

**Comment by yuxingfafu** [comment]
有谁遇到过类似的问题？

**Comment by dodola** [comment]
@yuxingfafu 是最新的代码么？我这好像正常哎

**Comment by yuxingfafu** [comment]
@dodola  是最新的代码，我是window系统，你是什么系统，mac???

**Comment by yuxingfafu** [comment]
同事mac的电脑正常

**Comment by dodola** [comment]
@yuxingfafu mac

**Comment by yuxingfafu** [comment]
@dodola 能否帮忙看下？有空的时候借同事的window系统试下？谢谢：）

**Comment by dodola** [comment]
@yuxingfafu 这个可以先关了，放到weexone那边
