### ISSUE TITLE
wxc-marquee 组件滚动一次后会快速倒回第一个再继续滚动

### ISSUE THREAD

**Issue by jingxin2015** [alibaba/weex#1316]
wxc-marquee 组件目前是这样的：比如滚动的文本有3条记录，从第一条开始滚动到第3条后，会有一个快速倒回到第一条的效果，之后再从第一条开始滚动，正常应该是滚动到第3条后，继续滚动到第一条，而不应该先倒回第一条。

**Comment by Jinjiang** [comment]
暂没有既定的更新计划，是的 wxc-marquee 更多细节有很多改进和完善空间，但这里仅作为实例展示用，开发者可以根据实际情况完成更多的定制
再次感谢您的建议：）

**Comment by zhouyuexie** [comment]
@jingxin2015 今天刚写了一个,不知合不合你意.
[weex-marquee](https://github.com/zhouyuexie/weex-marquee)
