### ISSUE TITLE
希望支持js引入样式和脚本

### ISSUE THREAD

**Issue by janryWang** [alibaba/weex#1319]
虽然按照组件的划分，是样式与脚本聚合的形态，但是还是要考虑代码的易维护性

目前写模板都必须得script/style/tempalte三个标签写在一个模板文件里面，很难保证后续因为style/script的内容庞大而导致整个文件难以维护，查阅起来都是一个麻烦事情，建议支持物理分离的功能，比如

```html

<template>

.....
</template>

<script>
     export from './index.css'
     export from './index.js'
</script>

```

**Comment by coolMan2015** [comment]
+1

**Comment by Jinjiang** [comment]
简单答复一下，导入 js 文件是支持的，导入 css 不支持
更多讨论可以移步 weex-loader 仓库 https://github.com/weexteam/weex-loader/issues

谢谢
