### ISSUE TITLE
Any new developments?

### ISSUE THREAD

**Issue by zoomclub** [alibaba/weex#1323]
Looking at platform deployment today and Weex looks like a great option. What is the current status? Will Weex be launched when Vue 2.0 in released, what is the future roadmap? Is Weex complete at this point or coming soon?

While it is not native I also looked at the Quasar Framework today and is super nice together with it's Quasar Play app, which you just get at the Google Play Store. I guess Weex still requires the complete local Android or iOS setup and the Weex Playground App is not what it sounds like.

Excuse me for all my questions but I'm presently updating my platform deployment strategy. I'd love to read all your issues except I can not read Chinese :)

**Comment by Jinjiang** [comment]
Currently the latest version is [0.7.0](https://github.com/alibaba/weex/releases/tag/v0.7.0) and 0.8 is in developing. (Yes we haven't publish any roadmap yet. The team will have a discussion about this)

There is a branch `jsfm-feature-0.17` using Vue 2.0 and already has some examples and a simple webpack loader to use.

And thank you for your all great advices. btw, sorry for most Chinese issues, maybe [google translate](https://translate.googleusercontent.com/translate_c?depth=1&hl=en&ie=UTF8&prev=_t&rurl=translate.google.com&sl=auto&tl=en&u=https://github.com/alibaba/weex/issues&usg=ALkJrhjWDD3IJCj3-tBCSlXCX9Rp29LRXg) will help you a little. And we are encouraging Chinese developers using English.

**Comment by Jinjiang** [comment]
Hi, this issue will be closed and collected into #1494 which collects all new feature requests and inactive open discussions. We hope to do this to make sure the open issues represent current focus and active jobs in community and the team. If we decide to resolve this problem or make it active. It will be reopened again.
Thanks for your support :-)
