### ISSUE TITLE
[iOS] Moudle 模块中 bundleUrl  获取沙盒路径错误

### ISSUE THREAD

**Issue by HJ-StevenSun** [alibaba/weex#1325]
首先我阐述一下我的项目需求，将JS的压缩包远程下载到本地沙盒，然后通过沙盒路径进行访问

`NSString *lib = [NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES)firstObject];
Newurl = [NSString stringWithFormat:@"file://%@/yjpt/weex_jzd/login.js",lib];`

在js 中的路径映射中  var bundleUrl = this.$getConfig().bundleUrl; 通过这个方法去获取我的绝对路径，
但是js 一直无法获取到这个路径找不到文件，我在查找工程文件中 打开新的页面是使用的openURL这个方法 断点检测以后 这个url 如图所示并不是 我沙盒的路径被截取掉了

![B2FBE1DF-67E9-490B-B772-B3E07172CD7A.png](http://upload-images.jianshu.io/upload_images/1767435-1409c8d7efdc0e27.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

并不是我沙盒的路径 , 我在 openURL  这个方法中 将其路径 截取成我沙盒的路径如下图，但是还是无法获取正常的路径
![4D500A98-B723-4246-8250-992A9E2361AB.png](http://upload-images.jianshu.io/upload_images/1767435-92d39886ffde65dd.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

启动以后会报如下图的错误
![609145E4-51E4-4E16-8A8C-ADCB7D4F1B32.png](http://upload-images.jianshu.io/upload_images/1767435-c53c8427a099416a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

我查了SDK中的源文件 其中 在WXBaseViewController 这个控制器中 有如下方法
`- (void)_renderWithURL:(NSURL *)sourceURL
{
    if (!sourceURL) {
        return;
    }
    [_instance destroyInstance];
    _instance = [[WXSDKInstance alloc] init];
    _instance.frame = CGRectMake(0.0f, 0.0f, self.view.bounds.size.width, self.view.bounds.size.height);
    _instance.pageObject = self;
    _instance.pageName = [[WXUtility urlByDeletingParameters:sourceURL] absoluteString];
    _instance.viewController = self;
    NSString *newURL = nil;
    
    if ([sourceURL.absoluteString rangeOfString:@"?"].location != NSNotFound) {
        newURL = [NSString stringWithFormat:@"%@&random=%d", sourceURL.absoluteString, arc4random()];
    } else {
        newURL = [NSString stringWithFormat:@"%@?random=%d", sourceURL.absoluteString, arc4random()];
    }
    [_instance renderWithURL:[NSURL URLWithString:newURL] options:@{@"bundleUrl":sourceURL} data:nil];
        __weak typeof(self) weakSelf = self;
    _instance.onCreate = ^(UIView *view) {
        [weakSelf.weexView removeFromSuperview];
        weakSelf.weexView = view;
        [weakSelf.view addSubview:weakSelf.weexView];
    };
        _instance.onFailed = ^(NSError *error) {
        
    };
        _instance.renderFinish = ^(UIView *view) {
        [weakSelf _updateInstanceState:WeexInstanceAppear];
    };
}`

其中 ` [_instance renderWithURL:[NSURL URLWithString:newURL] options:@{@"bundleUrl":sourceURL} data:nil];` 这个方法中的sourceUrl 应该是 传给var bundleUrl = this.$getConfig().bundleUrl; 这个方法中的 路径，不知道我说的对不对 

下图是工程日志，报错。  我应该如何在哪里去修改这个bundleUrl
![609145E4-51E4-4E16-8A8C-ADCB7D4F1B32.png](http://upload-images.jianshu.io/upload_images/1767435-25582821978193e7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

如果这个问题不解决 我公司的项目无法正常开展下去了，希望尽快获得回复和解决办法

**Comment by HJ-StevenSun** [comment]
@MrRaindrop  阿里的朋友，你们有人在看这个问题吗。。。 我把版本更新之类的都已经做好了 就等你们的解决方案了，如果这条路走通了 公司可以直接想什么时候更新手机上的就更新了，都不用去远程访问服务器的了，直接可以拿本地的js 文件读取，并且这个js 文件公司可以想什么时候更新掉就给它更新掉。难道没有考虑过这种设计模式吗？

**Comment by iloveyo123u1** [comment]
你换ionic

**Comment by iloveyo123u1** [comment]
你换ionic

**Comment by acton393** [comment]
hi  @HJ-StevenSun  你可以看下这个[repo](https://github.com/acton393/WeexOCExample) ,这个上面是完全加载的本地的js ,两个之间跳转也是跳转的本地js

**Comment by acton393** [comment]
#1300 这貌似是同一个问题，一起讨论

**Comment by HJ-StevenSun** [comment]
@acton393  这个问题 暂时已经解决了，将playground 整个框架的bundleURL 的传递过程查找了一遍，不是Native 这边的问题 是 js 代码的 问题,弃用了 openURl 这个方法 使用了 navigate 这个方法以后 已经可以正常使用

**Comment by acton393** [comment]
@HJ-StevenSun  在js代码的部分可以变更路径的， 先关闭了，如果有问题再打开~
