### ISSUE TITLE
repeat{{list}}语法，无法获取以下划线开头变量的值

### ISSUE THREAD

**Issue by 00SunnyDay00** [alibaba/weex#1327]
复现步骤
（1）使用repeat进行LIst展示。
如果采用以下的语法：

```html
<div repeat="{{dataList}}">
  <div class="itemContent" if="{{_item_style==='hide'}}">
    <text class="titleCenter">{{_title}}</text>
  </div>
</div>
```

现象：
会出现以下划线开头的变量无法正常获取值。
上述例子中_item_style 和_title 都无法获取到正常值。
如果重命名去掉下划线，值获取正常。

注：如果使用

```html
<div repeat="item in dataList">
  <div class="itemContent" if="{{item._item_style==='hide'}}">
    <text class="titleCenter">{{item._title}}</text>
  </div>
</div>
```

显示正常，值正常获取。

**Comment by Hanks10100** [comment]
因为在编译 `repeat` 指令时，每条数据都会使用 `mergeContext` 以父 `vm` 为原型对象创建子 `vm`，过程中会执行 `initData(dataList[n])` 创建数据绑定。

在执行绑定过程中 `vm._data` 中的属性名会经过过滤（避免与 vm 内部属性重名），过滤掉以 `$` 和 `_` 开头的属性：
```js
// https://github.com/alibaba/weex/blob/dev/html5/default/util/index.js#L19
function isReserved (str) {
  const c = (str + '').charCodeAt(0)
  return c === 0x24 || c === 0x5F
}
```

该方法只会过滤 `vm._data` 直接子级的属性名，如果是形如 `repeat="item in dataLint"` 的绑定，`vm._data` 的直接子属性将是 `item`，不会被过滤。

**Comment by Hanks10100** [comment]
将 weex 组件 data 中以 `$` 或 `_` 开头属性视为内部属性，是 jsfm 自身特性。可以用修改属性名或使用形如 `repeat="item in list"` 的语法规避。*（此特性会加入 lint 工具的校验规则）*

Won't fix.
