### ISSUE TITLE
weex debug 参数链接问题

### ISSUE THREAD

**Issue by joebnb** [alibaba/weex#1329]
如题，在weex 下 debug 带参数
```
weex debug http://ipaddr/some.html?param1=urlencode(sdfsfs)&param2=urlencode('safasdfa')
```
时启动 weex debug 会报错，而且生成的二维码中没有第二个参数

**Comment by exolution** [comment]
由于&是 shell 里的关键字 所以请转义或者给这个url加上引号

**Comment by MaryWu** [comment]
有关debug调试的问题，可以直接提到这里哈 https://github.com/weexteam/weex-devtool/issues
