### ISSUE TITLE
一直在编译

### ISSUE THREAD

**Issue by BadWooden** [alibaba/weex#1332]
在android studio2.2下一直处于编译状态

**Comment by liujianying** [comment]
这个好像是android studio的bug,你可以cd到工程目录下 执行命令 gradle clear 就行了.

**Comment by BadWooden** [comment]
好的

**Comment by BadWooden** [comment]
C:\Users\yoush\Desktop\weex-dev\android\playground>gradle clear
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'clear' not found in root project 'playground'. Some candidates are: 'clean'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 26.811 secs

**Comment by BadWooden** [comment]
出现错误

**Comment by liujianying** [comment]
@BadWooden  应该是执行gradle clean 这个命令.之前敲错了抱歉

**Comment by BadWooden** [comment]
我试了 还是一直在编译

**Comment by sospartan** [comment]
在同个目录下执行 `./gradlew clean assemble`  看看能不能成功

**Comment by sospartan** [comment]
这是gradle工程的相关问题,已经超出了weex的支持范围,暂时关闭.
