### ISSUE TITLE
(Android)在examples的index.we添加后，运行没有显示

### ISSUE THREAD

**Issue by JakeWoki** [alibaba/weex#1334]
In index.we, add an item {name: 'newExample', title: 'New Example'} for array data.cases
添加后运行没有显示，assets下的index.js没有newExample
修改CURRENT_IP为本地ip是指手机的ip吗？改了不行呢

**Comment by JakeWoki** [comment]
修改CURRENT_IP为本地ip是指手机的ip吗？改了不行呢

**Comment by Jinjiang** [comment]
Hi 多问一下你是 iOS 客户端还是 Android 客户端还是浏览器里预览的？
在不修改 CURRENT_IP 这个参数的情况下：

1. iOS 下是直接访问本地 examples 目录 build 出来的代码的
2. Android 客户端需要在打包运行之前运行 `npm run copy:examples`
3. 浏览器端运行也是直接访问本地 examples 目录 build 出来的代码，和 iOS 相同

**Comment by panwenhua** [comment]
@Jinjiang  你说了  不修改CURRENT_IP  才会加载build里面的js文件
可是 我将CURRENT_IP 改成自己的ip    将assets里面的文件删除了， 打包安装之后就无法显示了,查了一下日志,com.alibaba.weex E/weex: java.io.FileNotFoundException: index.js。
除非再npm run copy:examples 重新打包，才会出现。(安卓)  麻烦解答一下。

**Comment by Jinjiang** [comment]
我看到你好像新开了个 issue，我联系 native 同学具体看一下
