### ISSUE TITLE
image component been translated to a `div` on web

### ISSUE THREAD

**Issue by xieguanglei** [alibaba/weex#1335]
I have the following test.we

```
<template>
  <image src="https://www.google.com.hk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"></image>
</template>
<script>
  module.exports = {
    data: {
    }
  }
</script>
```

when I run `weex test.we` I got this:

<img width="570" alt="2016-09-29 5 57 22" src="https://cloud.githubusercontent.com/assets/2938447/18949539/6507c168-866e-11e6-8f43-c90a0e680eb3.png">

**Comment by Jinjiang** [comment]
The root component type must be `<div>`, `<list>` or `<scroller>`. The others are invalid.
Thanks
