### ISSUE TITLE
 refresh，loading初始设置display=‘hide’  任然可以拉出。出现以后一直悬停（H5，Android）

### ISSUE THREAD

**Issue by 00SunnyDay00** [alibaba/weex#1336]
注： refresh 和loading表现一致
复现步骤（以refresh为例）
（1）例如 我设置了list中的刷新
 &lt;refresh class="refresh-view" display="{{refresh_display}}" onrefresh="onRefresh">
      &lt;text style="text-align: center; color:rgb(238, 162, 54)">{{refresh_display}}</text>
&lt;refresh>

（2）data中
refresh_display： ‘hide’
（3）onrefresh 函数为空
（4）预期下拉刷新应该不会显
但是实际的效果是，一直悬浮在顶部
H5 和Android 问题一致

**Comment by acton393** [comment]
hi， @00SunnyDay00  refresh 和loading就是挂在 不可见区域的， 如果设置为 refresh_display = 'show'的话， 拉完之后就会停在可见区域， 直到给它状态为 hide 的时候重新会回到最顶部或者最下部

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢

**Comment by yuxingfafu** [comment]
还是有这个问题，sdk升级到最新的0.10.0了，没升到0.11.0， android的下拉多刷新几次，然后再加载更多，refresh 一直就在那里不消失
