### ISSUE TITLE
Native与weex通信问题

### ISSUE THREAD

**Issue by mjjde** [alibaba/weex#1337]
请问下Android 下weex 和native 如何通信，比如weex的动画完成了通知activity做些工作

**Comment by misakuo** [comment]
可以通过注册module的方式来实现，参照[extend to android](http://alibaba.github.io/weex/doc/advanced/extend-to-android.html)

**Comment by mjjde** [comment]
@misakuo 没有类似通用的回调机制吗，如果使用注册module的话，是不是意味着weex每次要通知Native如activity，都要写一个module注册呢

**Comment by misakuo** [comment]
@mjjde 通过注册module可以建立一条weex和native之间双向的数据通道，可以包装一下，所有自定义的通知都走同一条通道就好了

**Comment by mjjde** [comment]
@misakuo 那weex的后续发展可以封装一个类似Eventbus的组件提供的不止是Native到js的交互同时也可以提供weex到Native的事件分发，目前好像还没有Native直接发消息给js做交互的机制吧。

**Comment by misakuo** [comment]
@mjjde Native给Weex发消息可以通过`WXBridgeManager#fireEvent`方法来实现，类似EventBus的组件我们正在进行评估

**Comment by hapiman** [comment]
@misakuo Native调用.we文件的方式有吗？或者有什么计划没有？

**Comment by hapiman** [comment]
@misakuo Native能够调用.we文件的method.exports.methods就好了，但是这样的话是不是很影响性能

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
