### ISSUE TITLE
ios 端 image 使用 rezie="contain" 的时候图片不居中

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1338]
在 ios 上使用 image 标签，设置其宽高为 view 的宽高，rezie="contain" 的时候图片考屏幕下方显示，不在中间区域。

**Comment by Hanks10100** [comment]
是不是拼错了？ `resize="contain"`

**Comment by lmnsg** [comment]
@Hanks10100 ...没错，我复制代码的方式也试了，确实是contain的效果，但是不垂直居中，你使用那种宽图片测试一下，长图片是没问题的.

**Comment by Hanks10100** [comment]
我测试在 iOS 和 Android 都正常，参考 #1381 中的回复。
