### ISSUE TITLE
ios 返回页面如何刷新页面数据呢？ 

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1340]
vue-router 可以写在 data 钩子里，但是 weex 好像返回的时候不会触发任何钩子函数？

**Comment by Jinjiang** [comment]
这部分细节 @boboning 关注一下吧
谢谢

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
