### ISSUE TITLE
navigator的setNavBarTitle在手淘中有效，在playground中无效

### ISSUE THREAD

**Issue by xiangbingXB** [alibaba/weex#1341]
http://weex.alibaba-inc.com/playground/057ce28078239e36f4c3d1db2cd18e69

**Comment by kfeagle** [comment]
@xiangbingXB 我在ios的playground 测试是可以的，你是在iOS还是android出现的bug？

**Comment by xiangbingXB** [comment]
android 上

**Comment by vczero** [comment]
@xiangbingXB 你好，涉及到集团内部信息，可以在钉钉群里提出，注意数据安全。
