### ISSUE TITLE
在playground里面发现refresh触发视图中的list下的data更新后，视图并未更新

### ISSUE THREAD

**Issue by xiangbingXB** [alibaba/weex#1348]
refreash样式：
		  	<refresh class="refresh-view" display="{{refresh_display}}" onrefresh="handleRefresh">
		      <text class="refresh-arrow" style="text-align: center; color:rgb(238, 162, 54)" if="{{(refresh_display==='hide')}}">Refreshing</text>
		      <loading-indicator style="height:60;width:60;color:#3192e1"></loading-indicator>
		    </refresh>	

事件函数：
handleRefresh:function(e){
      	this.refresh_display =  "show";
      	setTimeout( function()
      	{
      		this.refresh_display = "hide";
      		

      		while( this.shopList.length>0 )
      		{
				this.shopList.pop();
      		}
      		this.pageIndex = 1;
      		var dataArr = this._getData(this.pageIndex);
      		for(var i=0;i<dataArr.length;i++){
      			this.shopList.push(dataArr[i]);
      		};
      		this._app.updateActions()
      	}.bind(this),1000)
      },

**Comment by xiangbingXB** [comment]
找到原因了，是因为cell加了scope属性，这里请定位下，为什么scope属性会导致刷新问题，按理说不应该影响

**Comment by acton393** [comment]
@xiangbingXB  应该是不支持scope 的属性  [doc](http://alibaba.github.io/weex/doc/components/cell.html)
