### ISSUE TITLE
timer.setInterval异步循环更新页面数据，存在问题，页面直接挂掉：

### ISSUE THREAD

**Issue by xiangbingXB** [alibaba/weex#1349]
ready:function(){
                var timer = require('@weex-module/timer');
                timer.setInterval(show2,1000);
                function show()
                {
                    for(var i=0;i<this.sections.length;i++){
                        for(var j=0;j<this.sections[i].rows.length;j++){
                                  for(var k=0;k<this.sections[i].rows[j].items.length;k++){
                                              
                                              /**
                                              var dateObj=new Date();
                                              var year = dateObj.getYear();
                                              var month = dateObj.getMonth();
                                              var date = dateObj.getDate();
                                              var hour = dateObj.getHours();
                                              var minute = dateObj.getMinutes();
                                              var second = dateObj.getSeconds(); 
                                              this.sections[i].rows[j].items[k].endTime = year+'年'+month+'月'+date+'号'+hour+'时'+minute+'分'+second+'秒';
                                              **/

                                              this.sections[i].rows[j].items[k].endTime = '测试日期：2020年12月31日';
                                              
                                  }
                        }
                    }
                }
                function show2()
                {
                  this.sections[0].rows[0].items[0].endTime = '测试日期：2020年12月31日';
                  this._app.updateActions();
                  //this.sections[2].rows[1].items[1].endTime = '测试日期：2020年12月31日';
                }
          }

**Comment by Hanks10100** [comment]
timer 模块是在内部使用的，直接用 `setInterval` 就可以，不需要引入 `require('@weex-module/timer')`。

**Comment by xiangbingXB** [comment]
亲，直接setInterva也是挂掉，一样存在问题
