### ISSUE TITLE
同一排的元素无法支持vertical-align:middle/top/bottom标签，这样的话某些效果很难实现

### ISSUE THREAD

**Issue by xiangbingXB** [alibaba/weex#1350]
<div id='元素' style='vertical-align:middle/top/bottom;'>

       </div>

**Comment by xiangbingXB** [comment]
<div id='容器' style='text-align:center;'>
       内容内容内容...
       <div id='元素' style='vertical-align:middle/top/bottom;'>

       </div>
</div>

同样是使得元素在容器内居中,text-align是针对容器而言的属性(内容左右居中), 而vertical-align是针对元素而言的属性(元素上下居中

**Comment by Hanks10100** [comment]
`text-align` 一般用于 `<text>` 和 `<input>` 标签。`vertical-align` 用于 `inline-block` 的盒模型，`<div>` 组件默认是伸缩容器(flex container)，建议使用 Flex 的布局方式。

各组件支持的样式和属性可以参考：[Weex Cheat Sheet](https://github.com/alibaba/weex/blob/dev/doc/references/cheatsheet.md)。

**Comment by xiangbingXB** [comment]
如果用flex布局，我要实现得效果是，div下面的flex-direction:row的2个text在水平线上底部对齐，我采用flex-direction:row;align-items:flex-end;的style依旧无法水平底部对齐

**Comment by xiangbingXB** [comment]
http://caibaojian.com/demo/flexbox/align-items.html,请参考，我要实现的是第2个例子的效果，当前测试weex无法实现
