### ISSUE TITLE
关于MTOP请求在帮助文档中给的例子太过于简单，对实际应用没有什么参考意义

### ISSUE THREAD

**Issue by xiangbingXB** [alibaba/weex#1351]
文档过于简单：http://gitlab.alibaba-inc.com/weex/weex/wikis/group-common-api

前端人员调试mtop接口成本较高，如果没有详细的文档，自己摸索很难调通，除非调试到anroid源代码，请加入如下详细的说明到文档中去：

**Comment by DoranYun** [comment]
内部问题在内部提问吧，注意信息安全、

**Comment by xiangbingXB** [comment]
OK，谢谢，敏感信息已经去掉
