### ISSUE TITLE
下拉刷新组件增强

### ISSUE THREAD

**Issue by jingxin2015** [alibaba/weex#1352]
1、目前的下拉刷新组件refresh和onloading文档打不开；
2、list里的例子也过于简单，只是实现了下拉刷新的事件，而实际开发中，一般都会刚开始下拉显示“下拉刷新”，下拉一定距离后显示“松开后刷新”，松开后显示“正在刷新”；
3、整个下拉组件建议参考手机淘宝的下拉刷新效果实现，目前对于不会原生的开发者来说，手机淘宝的下拉刷新效果用weex是根本无法实现的。

**Comment by jinyue-rdj** [comment]
这个需求我记录一下

**Comment by jinyue-rdj** [comment]
文档近期会进行统一更新

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！

**Comment by xubodreamsky** [comment]
下拉刷新，速度过快的话，会出现吸附不住的情况， 顶部的 Search Results会跑到底部去
