### ISSUE TITLE
怎么调用一些硬件资源?比如摄像头,系统相册?

### ISSUE THREAD

**Issue by pkptzx** [alibaba/weex#1354]
详细描述
怎么调用一些硬件资源?比如摄像头,系统相册?
应用场景
我认为大部分应用都需要用户头像的设置,用户可以调用摄像头或从系统相册中选择.希望官方能提供.

**Comment by HJ-StevenSun** [comment]
使用 自定义module  调用原生的方法来 调用

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
