### ISSUE TITLE
iOS 关于如何实现获取系统相册将其显示至网页中

### ISSUE THREAD

**Issue by HJ-StevenSun** [alibaba/weex#1356]
一个类似于 微信朋友圈的界面 ，在进入相册以后选择完图片将其显示至js 页面中。 iOS 无法获取系统相册的路径，所以我的想法是 将其取出 保存到沙盒，将沙盒的路径 返回给js 界面，在上传成功以后将图片从沙盒中删除。我认为这样子过于复杂  还有更好的解决方式吗？

**Comment by kfeagle** [comment]
我想到一种方案：通过前端 获取 nodeId,也就是ref，然后在iOS 渲染imageview的值，你试试效果

前端代码片段
```javascript
this.$el("text").nodeId
```

iOS端代码片段
```javascript
WXComponent *comp = (WXComponent *)[self.weexInstance componentForRef:elemRef];
if([comp isKindOfClass:[WXImageComponent class]])
{
     UIImageView *iv =  comp.view;
      ...//然后你可以把相册中或者相机获取的图片赋值给imageview
}
```

**Comment by HJ-StevenSun** [comment]
今天 才看见 我马上 去试一下 😄 @kfeagle

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！

**Comment by HJ-StevenSun** [comment]
@kfeagle   不好意思，前段时间 在给公司另一个项目上架， 这个iOS 代码 是写在哪个地方? 写在上传图片的module 里面吗 ？还有 就是 我 刚刚测试了 一下 这个WXComponent *comp = (WXComponent *)[self.weexInstance componentForRef:elemRef]; 方法里面的 elemRef 这个参数是哪儿来的，如何 使用可以说具体一点嘛。这个 是单张相片的话还是好解决但是如果是多张图片的话就得把多张图片放在一个数组里面了 是吧！
