### ISSUE TITLE
babel-runtime/helpers/typeof.js Template block is required

### ISSUE THREAD

**Issue by JakeWoki** [alibaba/weex#1358]
ERROR in ./~/babel-runtime/helpers/typeof.js
Template block is required

ERROR in ./~/babel-runtime/helpers/defineProperty.js
Template block is required
具体如下图
![20161009095802](https://cloud.githubusercontent.com/assets/6948411/19217033/eedbbd6e-8e06-11e6-9fd6-ed1493d21a8a.png)

**Comment by Jinjiang** [comment]
可以提供一下 `package.json` 里的依赖信息吗？以及实际安装的 weex-loader 的版本号，谢谢

**Comment by JakeWoki** [comment]
@Jinjiang https://github.com/vczero/weex-yy/issues/5#issuecomment-252459233在这里
## package.json如下
{
  "name": "weex-yy",
  "version": "1.0.0",
  "description": "Weex",
  "main": "src/index.we",
  "scripts": {
    "build": "webpack",
    "dev": "webpack --watch",
    "serve": "serve -p 8080",
    "devserve": "npm run dev & npm run serve",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": ["Weex", "Native UI"],
  "author": "hugojing",
  "license": "MIT",
  "devDependencies": {
    "serve": "^1.4.0",
    "webpack": "^1.13.1",
    "weex-html5": "^0.3.0",
    "weex-loader": "^0.3.1"
  },
  "dependencies": {
    "weex-components": "^0.1.3"
  }
}

## webpack.config.js如下
require('webpack')
require('weex-loader')
var path = require('path');
var fs = require('fs');
var entry = {};
(function walk(dir) {
  dir = dir || '.'
  var directory = path.join(__dirname, 'src', dir);
  fs.readdirSync(directory)
    .forEach(function(file) {
      var fullpath = path.join(directory, file);
      var stat = fs.statSync(fullpath);
      var extname = path.extname(fullpath);
      if (stat.isFile() && extname === '.we') {
        var name = path.join('dist', dir, path.basename(file, extname));
        entry[name] = fullpath + '?entry=true';
      } else if (stat.isDirectory() && file !== 'dist' && file !== 'include') {
        var subdir = path.join(dir, file);
        walk(subdir);
      }
    });
})();
module.exports = {
  entry: entry,
  output: {
    path: '.',
    filename: '[name].js'
  },
  module: {
    loaders: [
      {
        test: /\.we(\?[^?]+)?$/,
        loader: 'weex'
      },
      {
        test: /\.js(\?[^?]+)?$/,
        loader: 'weex?type=script'
      },
      {
        test: /\.css(\?[^?]+)?$/,
        loader: 'weex?type=style'
      },
      {
        test: /\.html(\?[^?]+)?$/,
        loader: 'weex?type=tpl'
      }
    ]
  }
}
//获取当前ip地址
function getIPAddress(){
  var os = require('os');
  var ips = os.networkInterfaces();
  var address ;
  for(var item in ips){
    for(var data in ips[item]){
      var ip = ips[item][data];
      if(ip.address.indexOf('192')==0){
          address = ip.address;
          return address;
      }
    }
  }
}

**Comment by JakeWoki** [comment]
@Jinjiang 怎么看weex-loader版本号？

**Comment by Jinjiang** [comment]
`npm ls --depth=0`

**Comment by Jinjiang** [comment]
@vczero 也来看看吧

**Comment by JakeWoki** [comment]
C:\Users\Administrator>npm ls --depth=0
C:\Users\Administrator
`-- (empty)
空的呢  汗

**Comment by vczero** [comment]
@JakeWoki 关于https://github.com/vczero/weex-yy的配置文件自定义的问题已经解决，可以参考https://github.com/vczero/weex-yy/issues/5 或者直接查看：https://github.com/vczero/weex-yy-h5。关于weex-yy的问题，可以直接在https://github.com/vczero/weex-yy上留言。

**Comment by JakeWoki** [comment]
https://github.com/vczero/weex-yy/issues/5

**Comment by wengpengfeijava** [comment]
@JakeWoki  你那个问题解决了么 哥们 。

**Comment by JakeWoki** [comment]
@wengpengfeijava 最近没时间玩这个啦，不记得了
