### ISSUE TITLE
wxc-button的颜色按钮style从warning切换到default的时候，背景色没有改变

### ISSUE THREAD

**Issue by xiangbingXB** [alibaba/weex#1360]
wxc-button的颜色按钮style从warning切换到default的时候，按理说应该背景色从黄色切换到白色，但是背景色没有改变，说明样式保留

**Comment by Jinjiang** [comment]
请提供你重现的代码基于系统环境，我这里是正常的

**Comment by cokeknight** [comment]
weex 里的input 获得焦点后再点其他地方怎么不会消失的
