### ISSUE TITLE
modal 建议增加属性比如确定 取消字体颜色，按钮位置，message字体大小颜色位置等，

### ISSUE THREAD

**Issue by yuxingfafu** [alibaba/weex#1362]
var modal = require('@weex-module/modal');
            modal.confirm(
               {
                message: '是否清空历史位置',
                okTitle: '删除',
                cancelTitle: '取消'
               },
               function(result){
               }
              );

**Comment by yuxingfafu** [comment]
不然这比如对话框确认框等常用的还需要自己去定义component

**Comment by Jinjiang** [comment]
我们目前没有这方面增强的打算，尊重各自平台的特点和样式，也保持 API 的简介，如果业务场景有实际需要，可以自行定制 native module 或 component
谢谢
