### ISSUE TITLE
refresh组件中的height哪怕设置得非常小，只有20px，最后显示出来的高度还是默认高度，设置无效

### ISSUE THREAD

**Issue by xiangbingXB** [alibaba/weex#1364]
.refresh-view {
    height: 20px;
    width: 750px;
    display: -ms-flex;
    display: -webkit-flex;
    display: flex;
    -ms-flex-align: center;
    -webkit-align-items: center;
    -webkit-box-align: center;
    align-items: center;
  }

**Comment by xkli** [comment]
新版本SDK已经修复这个问题，麻烦升级一下weex SDK。
compile 'com.taobao.android:weex_sdk:0.8.0.1'
