### ISSUE TITLE
css中设置变量不生效，只有写死在style中才生效，

### ISSUE THREAD

**Issue by xiangbingXB** [alibaba/weex#1365]
css中设置变量不生效，只有写死在style中才生效，这样如果用data数据变化动态改变样式，只能将大量样式的变量都写死在style中，导致代码的可读性很差，另外对不懂这个坑得开发人员来说，可能都会踩一遍。浪费时间

**Comment by Jinjiang** [comment]
你指的 css 中是指 `<style>` 标签里吧，这部分内容本身就是抽象成 class 的通用固定样式，所以没有再设计变量在这个基础上
CSS 规范中有变量的提案，但是社区的认知程度有限，我们觉得现在不是一个合适的时机支持CSS变量
anyway，非常感谢您的建议
这个 issue 我先关掉了，将来如果有支持的计划或更好的解决办法，我们可以随时 reopen 继续讨论

**Comment by FZmz** [comment]
![image](https://user-images.githubusercontent.com/52521997/154473451-8f65a62a-955e-4acd-aaf6-77c4d28f2e5a.png)

**Comment by FZmz** [comment]
hei bro，what's problem with the code?

**Comment by jokefrelon** [comment]
> hei bro，what's problem with the code?

把scoped删掉就可以了
