### ISSUE TITLE
出现libweexcorebk1.so is 32-bit instead of 64-bit，以及代码混淆问题

### ISSUE THREAD

**Issue by HelloClouds** [alibaba/weex#1366]
集成weex Android环境编译出现libweexcorebk1.so is 32-bit instead of 64-bit  ,so文件是32位的不是64位，weex界面渲染不出来！另外weex的混淆有指导么？？测试设备型号：华为荣耀7i
![o1kiaz3lfy8 9rz900 _kp](https://cloud.githubusercontent.com/assets/19909935/19226139/b32dbd02-8ed9-11e6-8b41-5de4a5cfdc06.jpg)

**Comment by fkysly** [comment]
@YorkShen

**Comment by YorkShen** [comment]
@HelloClouds Android FAT library在android 5.0以下的loading逻辑存在[bug](https://link.zhihu.com/?target=https%3A//android-review.googlesource.com/%23/c/80810/)，为了兼容google的这个bug，目前只提供32bit架构的so，在64位的设备上将会以兼容模式运行。

如果想提升性能，避免指令转换所造成的小幅度性能损失，请参考https://zhuanlan.zhihu.com/p/21359984来兼容armv7和armv7_64,x86,x86_64等架构，以避免踩到google的坑上。

**Comment by zhoukekestar** [comment]
我也遇到了类似的问题，是引入了一个facebook的包引起的。。。
https://github.com/zhoukekestar/weex-quick-start/issues/1

**Comment by myeveryheart** [comment]
同样遇到这个问题，没有facebook的包。
并没有以兼容模式运行，依旧包楼主的错
