### ISSUE TITLE
'webpack' 不是内部或外部命令

### ISSUE THREAD

**Issue by JakeWoki** [alibaba/weex#1371]
卸载Node.js后重新安装出现的，win7系统git-bash
![20161010221518](https://cloud.githubusercontent.com/assets/6948411/19239069/0b1abbca-8f37-11e6-9c79-04938557ce68.png)
![20161010221545](https://cloud.githubusercontent.com/assets/6948411/19239070/0b1e2292-8f37-11e6-8c8e-815faefb8df7.png)
![20161010221607](https://cloud.githubusercontent.com/assets/6948411/19239072/0b45b334-8f37-11e6-96d8-cef6070412fd.png)
![20161010221626](https://cloud.githubusercontent.com/assets/6948411/19239071/0b35b560-8f37-11e6-8b13-037e10156dde.png)
卸载Node.js后重新安装出现的，win7系统git-bash

**Comment by fkysly** [comment]
make sure you have npm install

**Comment by JakeWoki** [comment]
@fkysly npm已经安装

**Comment by fkysly** [comment]
What I mean is that you should run "npm install" command in the weex directory.

**Comment by JakeWoki** [comment]
@fkysly 有的，先npm install才./start的

**Comment by fkysly** [comment]
You can try to install the webpack globally, using the "npm install -g webpack" command. And if you still have problems, please make sure that the npm local package lookup path is correct.

[fixing-npm-path-in-windows-8](http://stackoverflow.com/questions/27864040/fixing-npm-path-in-windows-8)

[Windows Installer didn't add Node PATH](https://github.com/nodejs/node-v0.x-archive/issues/4356)

**Comment by alext1981** [comment]
该问题已经超过两周没有反馈，从目前的讨论看应该可以解决作者的问题，所以先关闭该问题，如果有进一步的讨论，可以再reopen。

**Comment by ThinkingInGIS** [comment]
请问您解决这个问题了吗？我也遇到了这个问题，path 已经指明了npm 和 nodejs的路径
