### ISSUE TITLE
UI适配问题，weex页面和原生页面不一致。

### ISSUE THREAD

**Issue by yfldj** [alibaba/weex#1379]
在少于750宽度的屏幕下，字体、间距、宽度、高度变小这种问题怎么解决？在5s看到页面是变小的，在6plus又是变大的，导致app的weex页面跟原生其他页面不一致。。。
var height = 88 * 750 / env.deviceWidth 这样写可以适配，但是，这样的话每个样式都需要定义一个变量，然后计算一次，这样很麻烦。有没有统一的处理？.we文件还是按正常的写多少px，然后有个预处理的公式进行统一转换？css的预处理？求助啊！

**Comment by fkysly** [comment]
@acton393

**Comment by alext1981** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
