### ISSUE TITLE
Image 的 resize="contain" 在 Android 没有效果

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1381]
IOS 中是 ok的。

**Comment by jinyue-rdj** [comment]
请 @gurisxie 看一下，是否是三端不一致的问题

**Comment by gurisxie** [comment]
给下脚本，以及描述下你使用的工具版本 @lmnsg ，我这边查看Android是可以的。

**Comment by lmnsg** [comment]
这是效果   
![wechatimg45](https://cloud.githubusercontent.com/assets/10400425/19295689/dde1a0c8-9068-11e6-93b1-d87a1567ea8a.jpeg)

```html
.slider-img {
        width: 750px;
        height: 294px;
    }
<image class="slider-img" src="{{pictureUrl}}" resize="contain"></image>
```
ios sdk 版本是7.0  android 是8.0

**Comment by lmnsg** [comment]
cover 也一样哦 ， ios OK  Android 始终是拉伸的效果

**Comment by lmnsg** [comment]
@gurisxie @acton393 麻烦关注一下。。。

**Comment by lmnsg** [comment]
还有个关联 issue [https://github.com/alibaba/weex/issues/1338](url)

**Comment by xkli** [comment]
@lmnsg 使用新版本playground 集成SDK版本为0.8.0.测试效果正常。playground下载地址:https://alibaba.github.io/weex/download.html

测试js代码
```
<template>
    <img src="http://i2.s1.dpfile.com/pc/21c287e0760b710dd1bf6c605f2e4804%28740x2048%29/thumb.jpg" style="width: 750px;
        height: 294px;" resize="contain"></image>
</template>
```

麻烦确认是否是用最新版本的weex sdk.
`compile 'com.taobao.android:weex_sdk:0.8.0'`
