### ISSUE TITLE
js文件里面如何获取getConfig()？

### ISSUE THREAD

**Issue by yfldj** [alibaba/weex#1383]
var env = this.$getConfig().env; 这个API怎么用在js文件里面？

就是在js文件里面如何获取getConfig()？？？

**Comment by jinyue-rdj** [comment]
可以看一下文档，@Jinjiang 答复一下

**Comment by fkysly** [comment]
![image](https://cloud.githubusercontent.com/assets/3274605/19265026/fc5e9616-8fd5-11e6-9769-c6d1f7e2b35c.png)

**Comment by Jinjiang** [comment]
抱歉我们目前没有这样的设计，想多了解一下您的实际需求场景，如果希望在 JS 文件里获取页面的配置信息，也可以暴露一个接口，然后从 `*.we` 文件里 `getConfig()` 然后传递到 JS 文件中。

**Comment by yfldj** [comment]
@Jinjiang 现在我的做法就是像你这样说的去做。我的场景是这样的，因为要做UI适配，要用到scale和屏幕宽度，我现在是.we调用js的一个公共方法获得经过转换的像素值，不想每次都传Config到js里面。还有，顺便问一下有没有什么方便的方法做UI适配？现在我的做法是在.we定义一个样式变量，绑定到style中，然后动态计算出这个样式变量去做适配，感觉这样有点麻烦。

**Comment by yfldj** [comment]
@Jinjiang 在.we如何调用自定义组件的方法？需要在自定义组件注册？请问具体怎么做？

**Comment by Jinjiang** [comment]
UI 适配我们已经有规划并且在实践了，issues 里有 viewpoint 相关的话题，可以简单搜索关注一下
如果你希望在 js 文件里获取 `getConfig()` 的信息，我建议你这样：

```javascript
var config = {}
exports.setConfig = function (cfg) {
  config = cfg
}

// do something else with `config`
```

然后在 `*.we` 文件里：

```vue
...
<script>
  var lib = require('./3rd-lib.js')
  module.exports = {
    methods: {
      foo: function () {
        var cfg = this.$getConfig()
        lib.setConfig(cfg)
        // use the lib
      }
    }
  }
</script>
```

**Comment by Jinjiang** [comment]
在.we如何调用自定义组件的方法，可以先查阅 https://github.com/weexteam/article/issues/16
如果还有问题可以另开 issue，js 获取 config 的问题可以在这里继续讨论

**Comment by Jam1zhu** [comment]
怎么在父级组件调用子级组件的函数？

**Comment by yfldj** [comment]
@Jinjiang 我说的在.we如何调用自定义组件是指we调用原生写的自定义组件。

**Comment by Jinjiang** [comment]
没有完全明白你说的“调用”是什么意思？可否解释一下或举个例子
