### ISSUE TITLE
[bug] text控件的内容超过宽度没有以三个点显示

### ISSUE THREAD

**Issue by squirrelx** [alibaba/weex#1385]
1.采用text-overflow 配置成ellipsis  超过宽度的字符没有以"..."的样式展示
2.如果不采用text-overflow  使用lines的话 在H5上是以"..."显示的，在android上没有效果

**Comment by liujianying** [comment]
text-overflow: ellipsis;   lines:1; 要一起使用才行

**Comment by squirrelx** [comment]
@liujianying  一起使用在android上可以了 多谢
