### ISSUE TITLE
使用官方stream-demod的代码解析json接口,可是出现富文本（含有html标签）时候，直接强退出去，

### ISSUE THREAD

**Issue by Yumengjing** [alibaba/weex#1388]
- 例如下面的接口内容：
![o frrh 3zpa va mie gll](https://cloud.githubusercontent.com/assets/12806513/19341844/cf0c08dc-9161-11e6-96a2-11056db183fe.png)

**Comment by acton393** [comment]
@Yumengjing  是Android还是iOS的， 如果可以的话，提供一下复现的demo~

**Comment by Yumengjing** [comment]
@acton393 是写在.we文件里面的，用的是stream-demo.we的源码，只是换了一个富文本json接口

**Comment by Yumengjing** [comment]
@acton393 需要我把接口给你吗？

**Comment by cooliean** [comment]
safe-html一下，我觉得应该就好了。

**Comment by acton393** [comment]
@Yumengjing  android 还是iOS  ,iOS 现在确实是直接去做parse的， 但是强退应该不大会，有做try catch ， 方便的话，可以把你的case，包括接口贴一下

**Comment by Jinjiang** [comment]
截图中的代码破坏了 JSON 的结构，本身就是有问题的，但是如果没有更细节和精确的信息，我们也无法定位这个问题，鉴于这个 issue 一直没有后续回应，暂时做关闭处理。
有必要继续讨论的话还是可以在这里留言的。
谢谢
