### ISSUE TITLE
component 之间数据传递，数据命名必须用小写，或者用-连接单词。建议改成更加直观的正常命名

### ISSUE THREAD

**Issue by 00SunnyDay00** [alibaba/weex#1389]
注：foo 是一个新的组件
 &lt;foo title="..." image="..."></foo>
是OK
但是  &lt;foo Title="..." Image="..."></foo>
不行

主要原因是父view和子view的变量对应需要采用小写。单词之间用-连接，会自动转换成驼峰。

强烈建议改成直接普通变量命名对应的方式。这对于原先非H5开发基本都是一个坑。
而且react的命名就是直接命名方式，并没有这么复杂。建议可以采用更直观的方式。

**Comment by liujianying** [comment]
将Title在父类view的表现形式是  _title

**Comment by Jinjiang** [comment]
因为 html 语法的 attribute name 是大小写的，所以 `abc-def-ghi` 在生成码中会自动转换成 `abcDefGhi` 我们沿用了这一约定，也是对标准的尊重
未来我们会支持 Vue 2.0 的语法，相关问题可以在将来移步 vue 的相关仓库和社区继续讨论

谢谢
