### ISSUE TITLE
iOS 的JSContext的exception[@"sourceURL"]获取不了

### ISSUE THREAD

**Issue by yfldj** [alibaba/weex#1390]
![0d494ace-1d34-4d63-b0d6-eba8440d52bd](https://cloud.githubusercontent.com/assets/6778148/19375115/7f6235fc-9203-11e6-8245-9459b2c047b7.png)
请问这个sourceURL在哪定义的？现在打印都是undefine。

**Comment by cxfeng1** [comment]
@yfldj 目前所有bundle JS都是通过new Function执行的， 所以暂时无法配置具体的sourceURL。

**Comment by alext1981** [comment]
Close this issue. If there's further discussion or information, we can reopen it.
