### ISSUE TITLE
坑！WXAppMonitorProtocol协议的pageName参数是写死的！

### ISSUE THREAD

**Issue by yfldj** [alibaba/weex#1391]
![3b3eb8af-df2d-4996-b3ac-fff407ce3b20](https://cloud.githubusercontent.com/assets/6778148/19377818/a791c818-921b-11e6-9ac6-46021cd49821.png)
![cb5de896-f6ae-415a-a237-2deb5d735881](https://cloud.githubusercontent.com/assets/6778148/19377819/a9808560-921b-11e6-8eed-36eb6f5fc86f.png)
这里为什么这样传參？对不上号，开发者实现这个协议，看到可以获取pageName,结果看sdk源码发现这里是写死weex，真正的pageName又是传到arg里面。。。。

**Comment by cxfeng1** [comment]
@yfldj  这个和一些老的实现逻辑有关系， 后面会调整到合适的接口，请暂时使用arg来取pageName

**Comment by alext1981** [comment]
Close this issue. If there's further discussion, we can reopen it.
