### ISSUE TITLE
Weex支持摄像头吗？

### ISSUE THREAD

**Issue by lifubang** [alibaba/weex#1392]
在社区提问回答速度太慢。
Weex支持摄像头吗？相关摄像头的文档链接在什么地方。多谢。

**Comment by lifubang** [comment]
另外，这个download的源代码能否开源？
http://alibaba.github.io/weex/download.html
这里有摄像头，但是找不到相关文档。

**Comment by DoranYun** [comment]
playground 的源码就在[项目仓库](https://github.com/alibaba/weex)中， iOS 和 Android 两个文件夹

**Comment by Jinjiang** [comment]
暂不支持摄像头功能，未来有支持的打算
