### ISSUE TITLE
notsup Not compatible with your operating system or architecture: fsevents@1.0.14

### ISSUE THREAD

**Issue by sunxiaoyang** [alibaba/weex#1394]
`$ npm install -g weex-devtool`

提示：

```
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
…………

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/weex-devtool/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

这个weex开发还限制平台是吗？

**Comment by Jinjiang** [comment]
请问你的操作系统和Node版本分别是多少，方便我们定位这个提示信息
另外warning信息一般不会影响程序正常工作，想多问一下安装之后运行是否正常？
谢谢

**Comment by sunxiaoyang** [comment]
操作系统是ubuntu-desktop-14.04，Node版本是v5.4.0。
我重新安装了一下，还是会出现如上警告，但可以运行简单we文件。
thank u

**Comment by Jinjiang** [comment]
了解了，我帮你记录到 devtool 仓库，这里先关掉了
谢谢

**Comment by clarkyu** [comment]
也遇到类似问题，简单的 template 和 style 可以运行，加了 scripts 后，运行结果不正常。

**Comment by clarkyu** [comment]
用的  MAC

**Comment by diydyq** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/weex-toolkit/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
