### ISSUE TITLE
同一个Activity如何加载本地不同的js文件？

### ISSUE THREAD

**Issue by scau-beyondboy** [alibaba/weex#1396]
在android平台上，怎么样用一个Activity加载本地多个不同s文件。

**Comment by scau-beyondboy** [comment]
按照官方提供的android demo加载方式看，每加载一个js文件就创建一个新的Activity。

**Comment by sospartan** [comment]
这几个js之间是什么关系? 是相互依赖么 还是说,你只是要加载一个新页面来替换已有的,如果是这样的话,直接render就行.

**Comment by sospartan** [comment]
@scau-beyondboy 要先把老的SDKInstance destory,让后创建新的来render
