### ISSUE TITLE
请问除了数据绑定刷新某个组件外，还有什么办法刷新组件视图呢

### ISSUE THREAD

**Issue by cooliean** [alibaba/weex#1397]
IOS 端
`
[self fireEvent:@"pagefinish" params:data domChanges:@{
                                                               @"attrs": @{@"src":@"cooliean"},
                                                               @"style" : @{@"height":@(heightV)}
                                                               }];
`
比如这样的方法，通过回调修改了组件的样式，或者属性，怎么自动刷新呢。
谢谢了

**Comment by Hanks10100** [comment]
能否再介绍一些这种需求的应用场景？如果数据没有更新，为什么还要更新视图呢？

如果是想更改组件的样式和属性，可以在样式和属性中添加数据绑定：

```html
<template>
  <div class="{{rootClass}}">
    <image src="{{imageSource}}"></image>
  </div>
</template>

<style>
  .rootA {
    background-color: #F0F0F0;
  }
  .rootB {
    background-color: #666;
  }
</style>

<script>
  module.exports = {
    data: {
      rootClass: 'rootA',
      imageSource: 'image.png'
    }
  }
</script>
```

**Comment by cooliean** [comment]
是这样的，我自己写了一个html显示的组件，我想这个组件可以根据我html的内容来动态的高度，显示已经实现了，但是高度算出来了以后，是在OC里面获取的。然后我在oc也已经更新了frame了。但是we中高度更新了,这样我一个视图是没有问题的。如果连续两个，下面的那个就会覆盖在上面那个上面，我如果通过finishload中的this.htmlHeight = e.height; 修改一下高度，视图刷新了，界面就OK了，但是我现在就是不想要手动区调用this.htmlHeight = e.height;我想这个组件更加的只能，方便点使用，我想这个刷新能不能用其它方式来弄，还是我哪里没有做好。谢谢了，不知道我描述的清楚不

```
<template>
  <div class="{{rootClass}}">
    <htmlview style="height:{{htmlHeight}}"></image>
  </div>
</template>
module.exports = {
		data: {
	      htmlHeight: 32,
	      color: '#ff0000'
	    },
		methods: {
	        finishload: function(e) {
	        	this.htmlHeight = e.height;
	        }
    	}
    }
```

**Comment by cooliean** [comment]
看了一下源码，照到一个更新属性的方法：
```javascript
        [self performBlockOnComponentMananger:^(WXComponentManager *manager) {
            [manager updateStyles:@{@"height" : @(heightV)} forComponent:weakSelf.ref];
        }];

```
这样就可以手动的促发视图的样式变化，就可以动态高度了。

**Comment by tonyyls** [comment]
android 端该如何实现?

**Comment by misakuo** [comment]
@tonyyls 我们在WXComponent中提供了一个`notifyNativeSizeChanged`方法，用于重设Native View的尺寸，调用该方法会导致native端与js端的dom object产生差异，请慎重使用。

**Comment by tonyyls** [comment]
thanks，在0.11.0 版本中没有notifyNativeSizeChanged。我的场景是：Componet的高度是不固定的，想动态修改。 现在尝试用 setHostLayoutParams 来控制，但发现 不会 撑开，其他view 位置变不了

**Comment by misakuo** [comment]
请查看这个变更：https://github.com/apache/incubator-weex/pull/337

**Comment by tonyyls** [comment]
@cooliean 在0.12.x上没有找到performBlockOnComponentMananger， 只有updateStyles ,但不生效，请问您是如何实现的？
