### ISSUE TITLE
[discuss]weex目前的现状问题和发展方向的讨论

### ISSUE THREAD

**Issue by mansonchor** [alibaba/weex#1399]
weex概念上的三端统一和"write once, run anywhere"感觉目前只适用在一些比较简单的界面场景，但是感觉离大部分替代native还有很多工程实现问题要解决，我提2个问题：

1. weex提供的官方组件我理解也是和RN一样逐个对接native的组件，现在都是一些好抽象的能三端实现的组件。那么如果是一些平台特殊的，但是又是很常用的组件（如 Android的 PageViewer），怎么实现三端统一？ 如果不考虑实现这种差异化的组件，是否意味着限制了开发者能力，牺牲了用户体验？
2. 只是css的子集，如果真的去深入浏览器，我们发现最复杂的其实是css和渲染引擎，不过其实目前所有的框架（RN、weex、微信小程序）都没去突破这块，虽然表面都是使用css语法，但真正实践的时候，会发现用CSS3很容易实现的一些效果，在这种方案下需要曲线救国去实现，有点回到IE6时代的感觉。
3. 接着上一个问题，我的理解这种方案根本不可能实现完整的CSS，否则相当于重新定义了一个渲染引擎。那么目前样式上的三端统一，是建立在这种css子集的基础上的，假如将来这种方案就到这种程度了，请问真的能够大规模替换native和直接代替普通的web开发吗？

以上问题纯属个人想法，或许weex的团队已经思考过和有解法，期望能回复交流

**Comment by liujianying** [comment]
Android的 PageViewer 我觉得也是,这个控件基本每个app基本都会用到,不懂官方为什么这个都没封装

**Comment by Jinjiang** [comment]
第一个问题，Weex 看待三端一致是基于业务需求一致或绝大部分一致的前提和假设，是提供一次性描述业务的DSL，各端展现结果可以一致，也可以基于各端的特点有差异的体现，但是上层描述是一致的
针对2和3，CSS 中的效果我们会逐步完善，部分细节需要进一步探索，但可以肯定的是这些探索或移植一定是建立在对开发者需求和业务场景的理解，而不是为了CSS而鲁莽的支持所有的CSS，同时无法完整实现的地方，我们一定是基于需求本身拿出更好更合适的方案出来
另外这些想法和工作从提出到实现确实有个过程，必要的话题我们可以单开 issue 继续讨论
这里我先关掉了
再次感谢二位的建议
