### ISSUE TITLE
weex init的问题

### ISSUE THREAD

**Issue by coderyi** [alibaba/weex#1401]
weex init 

之后会提示

```
npm WARN babel-loader@6.2.5 requires a peer of babel-core@^6.0.0 but none was installed.

```

没有安装babel-core，需要自己手动再安装。

**Comment by Hanks10100** [comment]
你好，在 weex-toolkit 项目有 `babel-core` 的依赖 （[package.json](https://github.com/weexteam/weex-toolkit/blob/dev/package.json#L16)），请明确下当前工具的版本，建议保持更新。

P.S. 关于工具的问题，可以在 [weex-toolkit](https://github.com/weexteam/weex-toolkit) 项目中提 issue.

**Comment by coderyi** [comment]
好的
