### ISSUE TITLE
在xcode中运行时遇到的一些问题

### ISSUE THREAD

**Issue by carly1987** [alibaba/weex#1403]
请问，在xcode中运行时报：
/Users/xianyun/weex/piece/ios/playground/WeexDemo/UIViewController+WXDemoNaviBar.m:74:28: 'UIBarButtonItemStyleBordered' is deprecated: first deprecated in iOS 8.0 - Use UIBarButtonItemStylePlain when minimum deployment target is iOS7 or later

这样的情况该如何解呢？

我是先下载https://github.com/alibaba/weex， 把example中的weex代码全部覆盖，然后在xcode运行。第一次运行的时候，模拟器是ok的，只是手机端报错。现在是两者都报以上的错误。
我也不知是不是我流程走的不对。但是我不是想要在weex playground中调试自己写的页面。我是要最终生成一个ios安装包，或者是手机上调试生成的一个本地app，然后可以使用。
但是现在卡在xcode的build过程上，求指导。

**Comment by HJ-StevenSun** [comment]
你 pod 过没有

**Comment by cooliean** [comment]
把target 版本设置高点。比如这里说的8.0

**Comment by acton393** [comment]
hi @carly1987  如 @cooliean  所提到的，你的target  version应该是有问题， 现在WeexSDK iOS SDK 的 minimum deployment target  是 iOS 7.0

在podfile 中请添加
```
 platform :ios, '7.0'
```
xcode的 setting中 如下图，请设置到7.0
![image](https://cloud.githubusercontent.com/assets/11631084/19471329/437d4e96-9555-11e6-87f6-94cd48645430.png)

**Comment by carly1987** [comment]
Podfile 里已改成8.0
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK', :path=>'../sdk/'
    pod 'WXDevtool', '0.8.0'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1'
end

target 'WeexDemo' do
    common
end

target 'WeexUITestDemo' do
    common
end
```

target 已改成8.0  ，然后运行报错：
UIBarButtonItemStyleBordered is deprecated: first deprecated in iOS 8.0 - Use UIBarButtonItemStylePlain when minimum deployment target iOS7 or later
