### ISSUE TITLE
iOS 中切换界面 除了Push 和 Pop 可以再 添加一个 presentViewcontroller 

### ISSUE THREAD

**Issue by HJ-StevenSun** [alibaba/weex#1410]
在登录成功以后 push 到了 主页， 这样的逻辑是行不通的，因为是push 过去的  在登录后的主页 侧滑以后会回到 login 页面。这是不符合app 的设计常理的，目前的app 中能够返回到登录页面都是需要去设置中心点击退出登录才能退出的。 我现在的解决方案是 自己写了一个module 的present 方法。希望能够在新版本加入此模块方法。

**Comment by HJ-StevenSun** [comment]
下午测试了以后 加了自己的present 方法以后 是可以从登陆页面 跳转过去了  但是 Push 方法 没有用了
点击主页面的时候 没有反应了。 不知道是 什么情况，这个 js文件是不是 都是依赖在 navigator 导航控制器下面的

**Comment by alext1981** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
