### ISSUE TITLE
请问在html5扩展module中handler components module的区别，分别在什么情况下使用。

### ISSUE THREAD

**Issue by psychokiller666** [alibaba/weex#1412]
我现在要扩展html5的module，大概是一个上传模块。

先创建一个dom，<input type='file' />（多选单选，blablablablabla）

得到选中值触发上传。

是都在module下创建一个文件来写，

还是创建dom的代码在components里，然后负责上传的代码在module里面写。

小白提问希望大神指教，如果你不愿意回答这很白痴的问题，直接丢关键词我自己搜索去学习。

谢谢！

**Comment by Jinjiang** [comment]
目前 component 只支持用户定义 attribute、style、event，方法暂不支持，但未来有这个计划
另外根据你需求的描述，这个“触发上传”可以是一个 event，方法本身不一定要暴露给用户
