### ISSUE TITLE
weex/ios/playground/Podfile中代码有误

### ISSUE THREAD

**Issue by walkerzhou** [alibaba/weex#1424]
需要删除多余的'字符
pod 'WXDevtool', '0.8.0''

**Comment by liujianying** [comment]
![a1edee08-0dbe-43e7-9a72-05b4fdc34689](https://cloud.githubusercontent.com/assets/6265414/19460934/fd09bba8-9512-11e6-8fda-bcb57de806a7.png)

**Comment by liujianying** [comment]
貌似0.8.0 默认demo 运行起来空白一片.之前版本没这个问题,麻烦也看下

**Comment by acton393** [comment]
@walkerzhou  @liujianying    thx,
这个确实是我们提交的时候失误，已经通过提pr  #1431   更新到dev ，麻烦更新一下尝试
