### ISSUE TITLE
Attributes and Styles 

### ISSUE THREAD

**Issue by wqd1994** [alibaba/weex#1425]
在封装组件中，我注意到这样一个问题，对于控件的属性，weex将属性分为Attributes和Styles两种,而且在Attributes中只能全部小写，Stylens中要通过“-”分隔开，我有点疑惑，为什么都是控件属性，还要区分两种呢？weex 在Attributes和Styles有什么特殊的定义吗？

**Comment by Jinjiang** [comment]
更多的是为了和 Web 标准中的定义对齐，确实 attr/style 从技术上没有本质差别，也没有那么严格的界限，之所以 attr 全部小写、style 是横线连接，也都是未来尊重 Web 标准

谢谢

**Comment by wqd1994** [comment]
像输入框的placeholder和placeholderColor在android 都是属性，但是在Weex中将两个属性拆分成Attributes和Styles，我绝对这样很别扭，而且应该和Web标准应该没有关系吧。 @Jinjiang

**Comment by Jinjiang** [comment]
语义上，attr 偏特性和行为描述一些，style 偏展示和效果描述一些，在 web 里，placeholder 是 attr，placeholder color 是通过 CSS 里的 :placeholder 伪类 + color 描述的。在有多重标准的情况下，我们希望更尊重 web 标准一些
