### ISSUE TITLE
下拉刷新与上来加载功能体验性建议

### ISSUE THREAD

**Issue by liujianying** [alibaba/weex#1427]
weex 0.8.0 版本 android 下拉刷新与上来加载更多在加载过程,list scroller 无法上下滚动,这种体验不好,建议改进

**Comment by alext1981** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
