### ISSUE TITLE
建议使用vue 2.0的语法规则

### ISSUE THREAD

**Issue by qq524007127** [alibaba/weex#1428]
建议使用vue2.0的语法规则

**Comment by Hanks10100** [comment]
本身我们的语法就和 Vue 比较接近，现在已经和 Vue 官方有合作，下一步会把内核切换成 Vue 2.0，支持所有 Vue 2.0 的语法。

目前是 Inspired by Vue ，下一步将是 Powered by Vue 。

**Comment by CrazyRocks** [comment]
下一个版本什么是发@Hanks10100 我们想上正式项目

**Comment by Hanks10100** [comment]
@CrazyRocks 还没有明确的时间。可以关注一下 [weex-vue-framework](https://github.com/weexteam/weex-vue-framework) 这个仓库，其中的 [Roadmap](https://github.com/weexteam/weex-vue-framework/issues/9) 是我们打算要做的事。

**Comment by spacemeowx2** [comment]
从 Roadmap 上看进度还差很多啊, 加油

**Comment by alext1981** [comment]
Close this issue. If there's further discussion, we can reopen it.
