### ISSUE TITLE
iOS pod报错（Unable to find a specification for `ATSDK-Weex (= 0.0.1)`）

### ISSUE THREAD

**Issue by Toorealistic** [alibaba/weex#1438]
Update all pods
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-WeexDemo`: (``)

Fetching external sources
-> Fetching podspec for `WXDevtool` from `../WXDevtool/`
-> Fetching podspec for `WeexSDK` from `../sdk/`

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `ATSDK-Weex (= 0.0.1)`

**Comment by acton393** [comment]
执行： pod update

如果上述 完成依然有问题 尝试：
pod repo remove master
pod repo add master https://github.com/CocoaPods/Specs.git
重新执行pod install

**Comment by yfldj** [comment]
Podfile貌似有问题

**Comment by acton393** [comment]
@yfldj  podfile 之前确实是有多了一个 '  ，已经提pr #1431 fix掉了， 可以尝试拉取一下dev的新的commit 应该ok的~

**Comment by evernoteHW** [comment]
pod 'ATSDK-Weex', '0.0.1'   改成 'ATSDK', '0.0.1'就行
