### ISSUE TITLE
更新weex toolkit之后，weex debug app list不能加载我的app 

### ISSUE THREAD

**Issue by yfldj** [alibaba/weex#1439]
为了使用这个最新的weex-devtool-extension，我更新weex toolkit之后，weex debug app list不能加载我的app了。之前（weex toolkit 0.4.10）是可以的。
weex版本是0.5.8
weex debug 版本是0.2.48
原生的weex sdk已更新至0.8.0

![e3e0afc3-9c1e-4a6a-ae8b-87908e1df71d](https://cloud.githubusercontent.com/assets/6778148/19470598/b6f87f4c-9552-11e6-927f-ee48d5360953.png)
![image](https://cloud.githubusercontent.com/assets/6778148/19470631/d172b284-9552-11e6-8b2a-dc2e89ae04d8.png)

**Comment by yfldj** [comment]
本地pod了最新的0.8.0的WXDevtool就可以显示了，但是weex的tab是空的。
![5241f27c-d8da-4dba-9f99-2ce376fefb50](https://cloud.githubusercontent.com/assets/6778148/19503753/4a5a1cce-95e8-11e6-845a-0542b0287173.png)

**Comment by alext1981** [comment]
已将该issue转至dev-tool项目讨论区， weexteam/weex-devtool#31 ， 请移步至新的issue继续讨论，谢谢。
