### ISSUE TITLE
slider组件增加throttle和非循环属性

### ISSUE THREAD

**Issue by yuanzhaohao** [alibaba/weex#1444]
1、slider在滑动过程中，经常会触发多次onChange事件。
目前我已经在js层加了一个throttle去控制频率，但是最好的方式还是在客户端代码去做这个throttle，因为虽然js能控制住，但是native->js的通信量还是没有减少，会消耗性能。
2、希望支持非循环滚动的属性来控制是否循环，因为我最近的业务场景就必须是非循环滚动的。

**Comment by alext1981** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
