### ISSUE TITLE
Andriod端如何获取we生成的界面元素

### ISSUE THREAD

**Issue by chengweipeng123** [alibaba/weex#1446]
在 "iOS 关于如何实现获取系统相册将其显示至网页中" #1356 有人提到了一种解决方案：
WXComponent *comp = (WXComponent *)[self.weexInstance componentForRef:elemRef];
UIImageView *iv =  comp.view;
通过这种方法，Native可以获取到we生成的界面元素，直接进行原生操作。非常不错。
但安卓端没有发现这样的函数，请问Andriod是否有这种途径？

**Comment by misakuo** [comment]
```java
WXSDKManager.getInstance().getWXRenderManager().getWXComponent(${instanceId}, ${ref}).getHostView()
```

**Comment by chengweipeng123** [comment]
@misakuo 多谢
