### ISSUE TITLE
storage在iPhone上无效，在模拟器上有效

### ISSUE THREAD

**Issue by allentofight** [alibaba/weex#1453]
代码如下
```
var me = this;
var storage = require('@weex-module/storage'); 
storage.getItem('ads', function(e) {
if (e.data) {
    var ads = JSON.parse(e.data);
    me.rows = ads;
}
});
```
请求网络数据时ads作了缓存，然后运行simulator能很快地显示ads,真机上却不行

**Comment by allentofight** [comment]
在iphone 6s Plus, iOS10上测的

**Comment by acton393** [comment]
@allentofight  真机上缓存前，能console.log 打出来么

**Comment by allentofight** [comment]
对，用真机调试没有任何log，需要做一些操作吧，正纳闷呢，我是这样操作的，进入页面，将拿到的数据缓存住，退出，关掉网络，再进入，然后模拟器能展示缓存数据，而真机这么操作没有缓存数据展示

**Comment by acton393** [comment]
@allentofight   在真机上调试可以使用[devtool](https://github.com/weexteam/weex-devtool)， 卸载掉app ，然后重新 请求网络，调试看下在缓存前，有没有数据

**Comment by allentofight** [comment]
@acton393 我知道咋回事了，在真机调试测试无网时，我直接打开了飞行模式，导致与本地的server断连，当然是没有请求到的，如果直接加载的js文件就可以了，麻烦了!
