### ISSUE TITLE
Android Memory问题

### ISSUE THREAD

**Issue by YanyeZhang** [alibaba/weex#1457]
在工程中接入Weex后，发现打开页面后内存占用抖增。增幅特别大。发现和图片加载（图片为webp）有关系。因此有如下几个问题：
1,造成内存常驻是否和weex自带的桥接有关？
2.结构冗余的js文件是否会造成类似问题？
3. 有没有提供一离开weex页面就就手动释放相关内存的方法
（附：加载的图片都不是特别大）

**Comment by alext1981** [comment]
@YanyeZhang   导致这个问题的可能性比较多，你能否提供一些可复现的页面代码，或者你在调试中的内存占用、log等信息， 这样可以帮助我们较快定位问题。
