### ISSUE TITLE
Android 由0.7升级为0.8报wx_create_instance_error

### ISSUE THREAD

**Issue by wqd1994** [alibaba/weex#1460]
今天我在升级Android Weex 版本时，出现wx_create_instance_error问题，方法还是用的以前0.7的方法，请问在升级0.8之后有较大的改动吗？

**Comment by YorkShen** [comment]
提供一些源代码和复现路径 @wqd1994

**Comment by wqd1994** [comment]
//    compile 'com.taobao.android:weex_sdk:0.7.0@aar'
    compile 'com.taobao.android:weex_sdk:0.8.0.2'
    compile 'com.taobao.android:weex_inspector:0.0.2.7'

我在之前的开发中用的上一个版本，现在我将weex Android 版本升级为0.8 ,这时候页面加载不出来，我打印了erroCode 和erroMsg 分别为 wx_create_instance_error 和createInstance fail!

**Comment by wqd1994** [comment]
// compile 'com.taobao.android:weex_sdk:0.7.0@aar'
compile 'com.taobao.android:weex_sdk:0.8.0.2'
compile 'com.taobao.android:weex_inspector:0.0.2.7'

我在之前的开发中用的上一个版本，现在我将weex Android 版本升级为0.8 ,这时候页面加载不出来，我打印了erroCode 和erroMsg 分别为 wx_create_instance_error 和createInstance fail! @YorkShen

**Comment by YorkShen** [comment]
需要更详细的日志或者源代码 @wqd1994

**Comment by wqd1994** [comment]
import android.content.Context;
import android.graphics.Rect;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import com.taobao.weex.IWXRenderListener;
import com.taobao.weex.WXSDKInstance;
import com.taobao.weex.common.WXRenderStrategy;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by wqd on 16-9-26.
 */

public abstract class IWXBaseActivity extends BaseActivity implements IWXRenderListener{
    public WXSDKInstance mWXSDKInstance;
    public ViewGroup mContainer;


    private static final String TAG = "IWXBaseActivity";


    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContainer((ViewGroup) findViewById(bindContainerId()));
        createWeexInstance();
        mWXSDKInstance.onActivityCreate();
        initWidget();
        setListener();
        loadData();

    }
    public void onWxActivityResume(){
        if(mWXSDKInstance!=null){
            mWXSDKInstance.onActivityResume();
        }
    }
    public void onWxActivityPause(){
        if(mWXSDKInstance!=null){
            mWXSDKInstance.onActivityPause();
        }
    }
    public void onWxActivityStop(){
        if(mWXSDKInstance!=null){
            mWXSDKInstance.onActivityStop();
        }
    }
    public void onWxActivityDestory(){
        if(mWXSDKInstance!=null){
            mWXSDKInstance.onActivityDestroy();
        }
    }
    public void onWxActivityStart(){
        if(mWXSDKInstance!=null){
            mWXSDKInstance.onActivityStart();
        }
    }
    protected final void setContainer(ViewGroup container){
        mContainer = container;
    }

    protected final ViewGroup getContainer(){
        return mContainer;
    }

    protected void createWeexInstance(){
        destoryWeexInstance();

        Rect outRect = new Rect();
        getWindow().getDecorView().getWindowVisibleDisplayFrame(outRect);

        mWXSDKInstance = new WXSDKInstance(this);
        mWXSDKInstance.registerRenderListener(this);
    }


    protected void destoryWeexInstance(){
        if(mWXSDKInstance != null){
            mWXSDKInstance.registerRenderListener(null);
            mWXSDKInstance.destroy();
            mWXSDKInstance = null;
        }
    }

    public void renderPage(String template,String source){
        renderPage(template,source,null);
    }

    protected String getPageName(){
        return TAG;
    }

    protected void renderPage(String template,String source,String jsonInitData){
        Map<String, Object> options = new HashMap<>();
        options.put(WXSDKInstance.BUNDLE_URL, source);
        mWXSDKInstance.render(
                getPageName(),
                template,
                options,
                jsonInitData,
                ScreenUtil.getDisplayWidth(this),
                ScreenUtil.getDisplayHeight(this),
                WXRenderStrategy.APPEND_ASYNC);
    }
    public void renderPageByURL(String url){
        renderPageByURL(url,null);
    }

    protected void renderPageByURL(String url,String jsonInitData){
        Map<String, Object> options = new HashMap<>();
        options.put(WXSDKInstance.BUNDLE_URL, url);
        mWXSDKInstance.renderByUrl(
                getPageName(),
                url,
                options,
                jsonInitData,
                ScreenUtil.getDisplayWidth(this),
                ScreenUtil.getDisplayHeight(this),
                WXRenderStrategy.APPEND_ASYNC);
    }

    @Override
    public void onViewCreated(WXSDKInstance instance, View view) {
        if (mContainer != null) {
            mContainer.removeAllViews();
            mContainer.addView(view);
        }
    }

    @Override
    protected void onStart() {
        super.onStart();
        onWxActivityStart();

    }

    @Override
    protected void onResume() {
        super.onResume();
        onWxActivityResume();

    }

    @Override
    protected void onPause() {
        super.onPause();
        onWxActivityPause();
    }

    @Override
    protected void onStop() {
        super.onStop();
        onWxActivityStop();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        onWxActivityDestory();
    }
    public abstract int bindContainerId();
    public abstract void initWidget();

    public abstract void loadData();

    public abstract void setListener();
}
加载Weex的基类，
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.view.Gravity;
import com.jzxiang.pickerview.TimePickerDialog;
import com.jzxiang.pickerview.listener.OnDateSetListener;
import com.taobao.weex.WXSDKInstance;
import com.taobao.weex.utils.WXFileUtils;


public class IndexActivcity extends IWXTitleBarActivity implements OnDateSetListener {
    public ServiceTimePopup popup;
    public ProvincePopup provincePopup;

    @Override
    public int bindLayout() {
        return R.layout.activity_index;
    }

    @Override
    public int bindContainerId() {
        return R.id.index_container;
    }

    @Override
    public void initWidget() {
        setTitleBarText("测试");
    }

    @Override
    public void loadData() {
        renderPage(WXFileUtils.loadAsset("tech_list.js", mContext), "");
    }

    @Override
    public void setListener() {

    }

    @Override
    public void onRenderSuccess(WXSDKInstance instance, int width, int height) {

    }

    @Override
    public void onRefreshSuccess(WXSDKInstance instance, int width, int height) {

    }

    @Override
    public void onException(WXSDKInstance instance, String errCode, String msg) {
        if (!TextUtils.isEmpty(errCode)) {
            Log.i("adolph", errCode);
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
    }


    @Override
    public void onDateSet(TimePickerDialog timePickerView, long millseconds) {

    }
}
这是加载Weex 的界面，我在使用0.0.7的SDK的时候没有问题，升级0.8之后出现的异常，之前正常使用。
谢谢了。
@YorkShen

**Comment by YorkShen** [comment]
@wqd1994 
* 代码不完整，无法复现问题
* 代码麻烦格式化下

**Comment by wqd1994** [comment]
解决了，是我在android中引用了jack，导致weex出问题，我把jack去掉就好了 @YorkShen 谢谢了。

**Comment by YorkShen** [comment]
@wqd1994 我试了一下，目前weex playground是支持jack编译链没有发生问题，你是用了jack的特性导致了问题
