### ISSUE TITLE
slider组件新需求及bug

### ISSUE THREAD

**Issue by jingxin2015** [alibaba/weex#1462]
1、建议slider组件增加是否循环播放属性，当为是时可循环播放，当为否时播放到最后一张结束，再向左滑动时不能继续滑动。
场景：使用slider做了一个引导页，一般app的引导页都是第一张不能向右滑动，最后一张不能向左滑动。

2、在安卓playground下，把slider的 auto-play 属性设置为false，页面初始化的时候是正确的，不会自动播放，但是手动滑动两下后，就自己又变成自动播放了。

**Comment by misakuo** [comment]
您好，请提供你集成的weex sdk的版本信息

**Comment by jingxin2015** [comment]
0.8.0.1

**Comment by misakuo** [comment]
playground集成的是比较旧的sdk，auto-play属性设置无效的问题在0.8.0上已经修复，您可以从dev分支上重新编译playground查看效果；循环播放属性的需求我们会进行评估。

**Comment by jingxin2015** [comment]
嗯，好的，谢谢

**Comment by Jinjiang** [comment]
不可循环的播放属性我们暂时没有支持的计划，也觉得没有特别的必要，另外听你描述的场景更像是一个横向的 scroller
建议如果业务上有此类需求，可以自行扩展
谢谢
