### ISSUE TITLE
iconfont支持动态icon切换

### ISSUE THREAD

**Issue by 00SunnyDay00** [alibaba/weex#1465]
如果icon使用iconfont，那么数据绑定传递的&#xe601全部会当成字符串显示。
Android，H5，ios 三端一致。都是字符串显示。
可否增加iconfont的动态替换icon的功能

**Comment by alext1981** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
