### ISSUE TITLE
[js]examples 里面的tabbar-demo在浏览器运行不起来，但在iOS却正常

### ISSUE THREAD

**Issue by coderyi** [alibaba/weex#1466]

**Comment by liujianying** [comment]
这个确实是bug,现在很多人反馈这个问题
weex 0.7.0  是正常的,升级到weex0.8.0  浏览器tabbar组件就不能正常显示页面内容,
在app端则没有这个问题

**Comment by MrRaindrop** [comment]
weex-html5 由于历史原因没有默认设置位于顶层的 div 节点的高度（只有 list/scroller 做了设置），导致这个页面高度缺失

https://github.com/alibaba/weex/pull/1484 可以 fix 这个问题

**Comment by esmeetu** [comment]
那这个demo该怎么修改呢？在哪里指定高度呢？谢谢。希望更新weex-html5

**Comment by Hanks10100** [comment]
#1484 Already merged.

**Comment by yolynn-bird** [comment]
![image](https://cloud.githubusercontent.com/assets/5186573/22812369/3f59476e-ef7f-11e6-8013-7cf298f8d35e.png)
同样有此问题，页面中有div类型也有scroller类型，在iOS设备上正常显示，在浏览器都无法显示
