### ISSUE TITLE
Android 里没有  dom.scrollToElement(top) ，文档里也没说明，但是需要这样的滚动到某个位置的API

### ISSUE THREAD

**Issue by jiangfei891111** [alibaba/weex#1467]

**Comment by cooliean** [comment]
你是不是没有加第二个参数，
>dom.scrollToElement(this.$el('someId'), {offset: 10});

**Comment by jiangfei891111** [comment]
那为什么浏览器里可以

**Comment by jiangfei891111** [comment]
我使用的Android 的weex的sdk版本是com.taobao.android:weex_sdk:0.8.0

**Comment by jiangfei891111** [comment]
如果界面没超出屏幕高度，没有滚动，是不是这个方法就不会滚动到指定的id的元素啊
