### ISSUE TITLE
WXTimerModule 如何清除事件

### ISSUE THREAD

**Issue by haicuan139** [alibaba/weex#1469]
WXTimerModule 这个类是通过clearTimeout 来清除消息的,接收的funcId 如何获得？每次funcId都是变化的。
`  @WXModuleAnno(runOnUIThread = false)
  public void clearTimeout(int funcId) {
    if(funcId <= 0){
      return;
    }
    WXBridgeManager.getInstance().removeMessage(WXJSBridgeMsgType.MODULE_TIMEOUT, funcId);
  }`

**Comment by Jinjiang** [comment]
timer module 是 HTML5 Timer APIs 底层实现的一部分，不建议直接使用。funcId 是框架层自行生成的
谢谢
