### ISSUE TITLE
[BUG]IOS10 Promise Error

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#1472]
There is an error occurred when using Promise.
Crash log here. [IOS10]
![5gw3b 534aag dv25n0 cx](https://cloud.githubusercontent.com/assets/13174847/19563772/d21e7e3a-9713-11e6-98e6-8a06f62a723f.jpg)

**Comment by fkysly** [comment]
Can you provide index.js ?

**Comment by fkysly** [comment]
More than two weeks without reply, manually closed.
