### ISSUE TITLE
建议为WXLoadingIndicator添加一个start属性

### ISSUE THREAD

**Issue by allentofight** [alibaba/weex#1474]
发现使用WXLoadingIndicator不太方便，由于默认是不start的,导致使用起来很不方便，建议加个属性start,这样可以很方便控制这个指示条是否开启，更灵活,类似如下

```
<loading-indicator start="true"></loading-indicator>
```

**Comment by cooliean** [comment]
自己加了。但是总是不敢PR，害怕我的代码质量玷污了他们框架，哈哈

**Comment by alext1981** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
