### ISSUE TITLE
最新版本错误 感觉是把packer.js 里面的斜杠去掉了

### ISSUE THREAD

**Issue by 1459416736** [alibaba/weex#1477]
最新版本运行./start 的错误如下：
browser.js  1.27 MB       0  [emitted]  main
    + 151 hidden modules

ERROR in ./html5/browser/extend/packer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./componentsimage in E:\APPWeex\weex\weex\html5\browser\extend
 @ ./html5/browser/extend/packer.js 3:23-51

ERROR in ./html5/browser/extend/packer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./components      ext in E:\APPWeex\weex\weex\html5\browser\extend
 @ ./html5/browser/extend/packer.js 7:21-49

ERROR in ./html5/browser/extend/packer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./componentsscrollable in E:\APPWeex\weex\weex\html5\browser\extend
 @ ./html5/browser/extend/packer.js 11:28-61

ERROR in ./html5/browser/extend/packer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./componentsslider in E:\APPWeex\weex\weex\html5\browser\extend
 @ ./html5/browser/extend/packer.js 15:24-53

ERROR in ./html5/browser/extend/packer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./componentsindicator in E:\APPWeex\weex\weex\html5\browser\extend
 @ ./html5/browser/extend/packer.js 19:27-59

ERROR in ./html5/browser/extend/packer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./components      abheader in E:\APPWeex\weex\weex\html5\browser\extend
 @ ./html5/browser/extend/packer.js 23:26-59

ERROR in ./html5/browser/extend/packer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./componentsinput in E:\APPWeex\weex\weex\html5\browser\extend
 @ ./html5/browser/extend/packer.js 27:23-51

ERROR in ./html5/browser/extend/packer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./components      extarea in E:\APPWeex\weex\weex\html5\browser\extend
 @ ./html5/browser/extend/packer.js 31:25-57

ERROR in ./html5/browser/extend/packer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./components
                                                                          ideo in E:\APPWeex\weex\weex\html5\browser\extend
 @ ./html5/browser/extend/packer.js 35:22-53

**Comment by gindepper** [comment]
也有这个问题，解决了么？

**Comment by MrRaindrop** [comment]
可以把 `packer.js` 的内容贴一下我看一下么？这个文件内容是构建生成的

**Comment by 1459416736** [comment]
`// import components.
import Image from './components\image'
import Text from './components\text'
import Scrollable from './components\scrollable'
import Slider from './components\slider'
import Indicator from './components\indicator'
import Tabheader from './components\tabheader'
import Input from './components\input'
import Textarea from './components\textarea'
import Video from './components\video'
import Switch from './components\switch'
import A from './components\a'
import Embed from './components\embed'
import Spinner from './components\spinner'
import Web from './components\web'

// import apis.
import Dom from './api\dom'
import Event from './api\event'
import PageInfo from './api\pageInfo'
import Stream from './api\stream'
import Modal from './api\modal'
import Animation from './api\animation'
import Webview from './api\webview'
import Navigator from './api\navigator'
import Storage from './api\storage'
import Clipboard from './api\clipboard'
import Geolocation from './api\geolocation'

module.exports = [Image, Text, Scrollable, Slider, Indicator, Tabheader, Input, Textarea, Video, Switch, A, Embed, Spinner, Web, Dom, Event, PageInfo, Stream, Modal, Animation, Webview, Navigator, Storage, Clipboard, Geolocation]

**Comment by tianlang724** [comment]
同求解决

**Comment by 1459416736** [comment]
@MrRaindrop  已经传上了packer.js文件内容，好多人都有这个问题，我的是win平台

**Comment by CodeFalling** [comment]
Send a PR here: https://github.com/MrRaindrop/wwp/pull/1 @MrRaindrop

**Comment by 1459416736** [comment]
@CodeFalling  你好，还是没有解决问题，我更新了你修改的文件后，页面显示空白，感觉组件都没有加载进去

**Comment by CodeFalling** [comment]
@1459416736 感谢测试，可以提供更新后的 `packer.js` 么

**Comment by 1459416736** [comment]
@CodeFalling 代码如下
// import components.
import Image from './components/image'
import Text from './components/text'
import Scrollable from './components/scrollable'
import Slider from './components/slider'
import Indicator from './components/indicator'
import Tabheader from './components/tabheader'
import Input from './components/input'
import Textarea from './components/textarea'
import Video from './components/video'
import Switch from './components/switch'
import A from './components/a'
import Embed from './components/embed'
import Spinner from './components/spinner'
import Web from './components/web'

// import apis.
import Dom from './api/dom'
import Event from './api/event'
import PageInfo from './api/pageInfo'
import Stream from './api/stream'
import Modal from './api/modal'
import Animation from './api/animation'
import Webview from './api/webview'
import Navigator from './api/navigator'
import Storage from './api/storage'
import Clipboard from './api/clipboard'
import Geolocation from './api/geolocation'

export default { Image, Text, Scrollable, Slider, Indicator, Tabheader, Input, Textarea, Video, Switch, A, Embed, Spinner, Web, Dom, Event, PageInfo, Stream, Modal, Animation, Webview, Navigator, Storage, Clipboard, Geolocation }

**Comment by CodeFalling** [comment]
@1459416736 抱歉装 Windows 虚拟机耗费了很长时间 =。=，确实存在这个问题，但是似乎和 `packer.js` 无关了

**Comment by CodeFalling** [comment]
组件具体的内容没有渲染出来，console 没有异常

![image](https://cloud.githubusercontent.com/assets/5436704/19798795/c0d2f3be-9d25-11e6-9e1f-2ae94b95427f.png)
![image](https://cloud.githubusercontent.com/assets/5436704/19798806/cba4b3e0-9d25-11e6-8305-d7f544a0a334.png)

**Comment by MrRaindrop** [comment]
@CodeFalling 看你这个图片的现象应该是组件没有注册上。你的pr已经merge了，生成的packer应该没有问题，没渲染出来的问题我继续跟进一下。在 virtualbox 下搞 win 的环境搞了半天没搞完...

**Comment by CodeFalling** [comment]
@MrRaindrop 找到问题了，wwp 生成的 `packer.js` 从导出一个数组改成了导出一个对象，而 `weex` 这边没有做出相应的改变

PR: https://github.com/alibaba/weex/pull/1534

// 虚拟机 win 开发太痛苦了...

**Comment by MrRaindrop** [comment]
这个问题是 wwp ^0.3.0 版本作出的改变，对应到 https://github.com/alibaba/weex/tree/html5-feature-0.5 分支的，目前 `dev` 分支的版本对应 wwp ^0.2.0 版本，可以从 `package.json` 的版本依赖里看出来。这个 pr 暂时就不 merge 了，对应代码可以看这里 https://github.com/alibaba/weex/blob/html5-feature-0.5/html5/render/browser/extend/index.js#L6-L12

**Comment by Jinjiang** [comment]
我这边实测，html5-feature-0.5 分支，在更新 wwp 依赖版本之后，Windows 下也正常工作了，并可以正常展示，有劳确认

**Comment by tianlang724** [comment]
@1459416736 请问你是如何修改的packer.js的，这个东西都是每次自动生成的，感谢

**Comment by maulshh** [comment]
has this bug/issue solved already? sorry I can't really follow the discussions
