### ISSUE TITLE
Failed at the weex@0.4.0 serve script 'serve ./ -p 12580'  

### ISSUE THREAD

**Issue by unsignedlinux** [alibaba/weex#1481]
17 error Linux 3.13.0-32-generic
18 error argv "/opt/node/bin/node" "/opt/node/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/root/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "serve"
19 error node v6.0.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error weex@0.4.0 serve: `serve ./ -p 12580`
22 error Exit status 1
23 error Failed at the weex@0.4.0 serve script 'serve ./ -p 12580'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the weex package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     serve ./ -p 12580
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs weex
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls weex
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

在./start 后报错，显示Failed at the weex@0.4.0 serve script 'serve ./ -p 12580'. 有遇到这种问题的小伙伴么，或者知道这个 'serve ./ -p 12580'在哪  
（when i was running ./start ,there was a err in my console，anyone konw what hapend? i think  'serve ./ -p 12580' something wrong ,but i dont konw how to fix it）

**Comment by 1459416736** [comment]
端口好被占用，解决方法有2种
1.修改端口好，在package文件里
2.删除本机本占用的端口号12580的进程

**Comment by unsignedlinux** [comment]
确实是端口得占用了，我用的是ubuntu14.04  （the port 12580 already used）
解决办法：netstat -ap | grep 12580   ,查看pid号 ，然后 kill pid
再次运行 ./start

**Comment by alext1981** [comment]
It seems that the issue has been resolved. It can be reopened if the author finds some new problems about this issue.
