### ISSUE TITLE
安卓或者苹果手机调试main.we文件，页面显示不出来

### ISSUE THREAD

**Issue by jingxin2015** [alibaba/weex#1485]
如题，我的执行步骤是这样的：
1、在cmd上执行 weex debug src/main.we -h 192.168.2.108 弹出来调试页面
2、扫描左边的二维码，上面识别出来手机信息，再扫描第2个二维码，手机上会出来页面，但是页面如下图所示，不知道什么原因？

![](https://cloud.githubusercontent.com/assets/16143766/19604461/ec998f14-97e7-11e6-813d-1fc740ae6bbb.png)

**Comment by alext1981** [comment]
@jingxin2015  你是不是用了tabbar组件？  tabbar组件的内容显示区实际是用embed加载了新的weex页面实例，也就是说内容展示区是新的weex页面，你用的weex debug xxxx.we 命令仅是编译了main.we文件，但是每个tab里的.we文件并未编译，所以无法找到。

**Comment by jingxin2015** [comment]
@alext1981 是的，是这个原因。

**Comment by Jinjiang** [comment]
weex 有两种开发用法，一种是调试单个 JS Bundle，比较轻便快捷但有较大局限性，适合入门；另一种是创建一个完整的工程，有完整的构建脚本和工具，可以批量生成多份 JS Bundle 且可以相互配合

如果是多个文件需要同时调试，建议建一个完整的工程来做，比如 weex init 一个工程在里面
