### ISSUE TITLE
用git for windows 还是无法解决正斜杠，反斜杠的问题，请问除了用虚拟机，还有什么办法么

### ISSUE THREAD

**Issue by gindepper** [alibaba/weex#1486]
ERROR in ./html5/browser/extend/packer.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./componentsimage in E:\weex-dev\html5\browser\extend
 @ ./html5/browser/extend/packer.js 3:23-51

**Comment by MrRaindrop** [comment]
可以把 `./html5/browser/extend/packer.js` 这个文件的内容贴一下么？

**Comment by Jinjiang** [comment]
这个问题放 #1477 一起讨论吧，这里先关掉了
谢谢
