### ISSUE TITLE
[android] textarea与scroller滚动事件冲突

### ISSUE THREAD

**Issue by jiangfei891111** [alibaba/weex#1488]
使用textarea多行输入，外层使用scroller的时候，滚动输入的多行文字，会出现滚动冲突，没办法滚动textarea里的文字了

**Comment by sospartan** [comment]
你是不是添加了什么事件监听,我这边一个简单的例子不能重现你说的问题:
```
<template>
  <scroller>
    <textarea rows=3 placeholder="2332432"></textarea>
  </scroller>
</template>
```

要不贴一下你的代码

**Comment by jiangfei891111** [comment]
这个需要吧scroller制造出滚动才会出现冲突，我改了下你的代码，用一个text设置高度来制造了scroller键盘弹出时的滚动，代码如下：
`<template>
  <scroller style="height: 5000;" append="tree">
    <textarea rows="10" placeholder="2332432" autofocus="true"></textarea>
    <div>
     	<text style="height:200;"></text>
	</div>
  </scroller>
</template>`

**Comment by sospartan** [comment]
恩 重现了 我先分析一下

**Comment by sospartan** [comment]
fixed by 88b0176486b7e0577bb888101731f9e0a18c29e9

你可以使用android分支的代码进行依赖.

**Comment by jiangfei891111** [comment]
大神，这个是不是得很久之后release下个版本了啊

**Comment by jiangfei891111** [comment]
大神，这个是不是得很久之后release下个版本了啊

**Comment by sospartan** [comment]
v0.9 大致在大半个月后发布,如果你着急的话建议你用代码依赖

**Comment by jiangfei891111** [comment]
好的大神，另外两个问题，还得麻烦了
