### ISSUE TITLE
CLI how to make it to specified platform

### ISSUE THREAD

**Issue by johnzhu12** [alibaba/weex#1491]
可以说中文吧，我直接提问了，之前做过ionic开发，原生接触过一点，这个是不是应该写好h5上的逻辑，然后一句命令，自动生成ios平台，没看明白怎么弄得，先跑了那个demo。不知道ios部分的代码自己写么
  
![5](https://cloud.githubusercontent.com/assets/11485619/19635206/3b443d32-99f3-11e6-8559-62e7776d124a.png)

**Comment by johnzhu12** [comment]
我有init一个项目，然后改改东西，生成二维码，然后用这个playground应用扫一下，应用里出现页面。但是我要做一个类似原生的app,步骤能稍微说明下么，不太懂，是不是一样做完h5开发，比如
`
 <listView repeat="item in list"><listView> 
 `
然后怎么就到ios原生的UItableVIew去了，是不是都封装好了,怎么弄得

**Comment by johnzhu12** [comment]
看明白一点就是在examples文件夹下，都是进行vue开发，然后打包的js文件在build下面，原生启动的时候会去调
     
![6](https://cloud.githubusercontent.com/assets/11485619/19640582/f4327d6a-9a0f-11e6-81de-b99a2f2f28d2.jpg)

那就是不管，直接进行前端开发，然后在原生里面去调用，但这个和用webView的cordova是不一样的，不是应该和RN一样，是原生控件吗，所以后面得具体看看是怎么封装的原生UI,js和OC怎么交互，走jscore,现在还很多不明白

**Comment by alext1981** [comment]
@johnzhu12  请参考weex相关文档，再阅读demo并试运行一下，应该可以对理解weex原理有很大帮助。
