### ISSUE TITLE
Android list 嵌套 scroller 不能滑动问题 IOS

### ISSUE THREAD

**Issue by YanyeZhang** [alibaba/weex#1492]
list标签中嵌套横向的scroller

**Comment by beghujam** [comment]
不允许相同方向的 <list> 或者 <scroller> 互相嵌套，换句话说就是嵌套的 <list>/<scroller> 必须是不同的方向。

举个例子，不允许一个垂直方向的 <list> 嵌套的一个垂直方向的 <scroller> 中，但是一个垂直方向的 <list> 是可以嵌套的一个水平方向的 <list> 或者 <scroller> 中的。
