### ISSUE TITLE
Collections of new feature requests and open discussions

### ISSUE THREAD

**Issue by Jinjiang** [alibaba/weex#1494]
This issue is just for recording all new feature requests and inactive open discussions. The origin issues will be closed in order to make the community more focus on active and key points. In the future we will reopen some of them if we decide to do that job or make it active. Also it's welcome to continue the related discussions here.

Thanks.

这则 issue 是为了记录所有的新需求和不活跃的开放式讨论。原本的 issue 会统一做关闭处理以让整个社区更专注在正在解决和活跃的事情。如果这些被关闭的 issue 在未来会被支持或重启讨论，我们会适时 reopen 它们。当然大家也可以在这里继续畅所欲言。

谢谢。

---

下面按 issue 号排列：
- #62 Make app accessible with weex
- #74 img doesn't support data url
- #117 Data querying and manipulation with a server
- #121 [Discuss] eventTarget and Element.getBoundingClientRect() feature support
- #155 need feature：more custom styles of slider indicator，or support set image
- #222 一个小案例
- #241 dbClick event handler needs to be supported.
- #282 请问有没有拍照和二维码的组件
- #331 [Discuss] The lifecycle of weex.
- #395 [discuss] component `web` may receive messages for calling apis
- #424 Android AnimationDrawable support
- #425 background-color支持gradients
- #478 box-shadow not work
- #498 visibility:hidden need enhancement
- #553 建议支持图片加载事件
- #705 什么时候支持可以直接打包 什么时候可以直接调用系统API???
- #782 [Discuss] 点击效果
- #864 页面加载显示能否优化？
- #967 [Feature Request] list增加下拉进度动画
- #990 WXScrollerProtocol缺少监听偏移量的接口
- #1003 Weex对于styles非法值(NaN/Infinity)的处理
- #1016 如何实现客户端主动调起JS端的函数
- #1039 slider 组件在android playground只有两个页面的时候无法循环
- #1045 对weex性能优化的一个设想
- #1051 关于 script type="data"
- #1053 wxc-tabbar无法通过style设置background-color样式
- #1070 设置一个属性，用来禁止点击
- #1076 关于Weex多语言支持！
- #1078 使用navigator-pop返回后，能否让触发一个事件。
- #1134 Navigator的逻辑优化
- #1139 通过手势切换按钮页面
- #1151 按照字母定位list项的需求
- #1156 滚动区的ScrollChange 支持
- #1163 webview与weex的交互
- #1164 repeat 标签复用View
- #1174 条件渲染时是否会考虑支持像Vue的v-show
- #1185 android: 键盘收起事件
- #1216 weex module navigator增加隐藏导航栏的方法
- #1230 weex navigator 转场动画如何修改
- #1287 ios 如何获取渲染view的大小？
- #1304 navigator 是否可以提供 replace 方法？
- #1317 建议增加仿微信或支付宝的选择头像并上传组件
- #1323 Any new developments?
- #1337 Native与weex通信问题
- #1352 下拉刷新组件增强
- #1353 选项卡组件增强
- #1354 怎么调用一些硬件资源?比如摄像头,系统相册?
- #1355 Video标签支持全屏
- #1356 iOS 关于如何实现获取系统相册将其显示至网页中
- #1340 ios 返回页面如何刷新页面数据呢？
- #1379 UI适配问题，weex页面和原生页面不一致
- #1410 iOS 中切换界面 除了Push 和 Pop 可以再 添加一个 presentViewcontroller
- #1427 下拉刷新与上来加载功能体验性建议
- #1444 slider组件增加throttle和非循环属性
- #1465 iconfont支持动态icon切换
- #1474 建议为WXLoadingIndicator添加一个start属性
- #1487 要是`<style></style>`里面能设置变量就方便多了
- #1494 用 border 绘制三角形
- #1631 iOS中如何实现一个cell两个同样的view的效果
- #1621 weex input有单选框吗，为什么type="radio"会变成type="text"
- #1743 select什么时候可以支持
- #1783 Canvas

**Comment by wang111588** [comment]
需求 UICollectionView 集成

**Comment by miyalee** [comment]
关于本地图片，作为一个第一次接触android的渣前端，我暂时选择将图片发在res/drawable里(新建了文件夹drawable)，如logo.png，在<image>组件如此引用：`<image src="local:///logo"></image>`，不要加后缀，亲测有效，在base64和custom android代码不好使又不想用http的情况下是个方法。虽然感觉有些别扭，不过我们可以自己写个脚本在build时把图片cp过去这样会好一点？

官方文档这里：http://weex.apache.org/cn/references/path.html
by the way 其实这段研究了很久后来还是结合网上看到别人的做法才明白，其实感觉这样说让人有些难懂，如果改为：
* 在 Android 中，image 组件将从 drawable 资源文件夹加载，例如，image 组件的 src 属性为 local:///app_icon'， Weex 会加载 res/drawable 中名为 app_icon 的图像资源......
 这样会不会更一目了然

**Comment by junzaivip** [comment]
test

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
