### ISSUE TITLE
有没有滑动事件类型

### ISSUE THREAD

**Issue by whoiam2007s** [alibaba/weex#1499]
touch事件中获取不到触发的坐标位置，所以无法自己写。
weex中有没有滑动触发事件，比如左右滑动，swipeLeft和swipeRight等,

**Comment by MrRaindrop** [comment]
有 swipe 和 pan 事件，判断方向可以访问 `e.direction`

**Comment by whoiam2007s** [comment]
swipe可以了，不过不知道这个pan是什么事件，onpan监听不到触发动作

**Comment by jiangfei891111** [comment]
在哪里讲到这个了啊，文档里没找到，我是Android端，在哪里看具体使用方法

**Comment by Jinjiang** [comment]
@vczero 关注一下这块的文档状况吧
谢谢

**Comment by MrRaindrop** [comment]
@whoiam2007s 可以试一下 `panstart`, `panmove` 以及 `panend`

**Comment by whoiam2007s** [comment]
ok，正确了
