### ISSUE TITLE
demo中同样的会场页面在app里和在浏览器里不一样

### ISSUE THREAD

**Issue by johnzhu12** [alibaba/weex#1506]
![1](https://cloud.githubusercontent.com/assets/11485619/19679192/79ca3846-9ad3-11e6-8ce7-3f765d34f62d.png)

**Comment by cooliean** [comment]
你这个应该是路径不对导致的

**Comment by MrRaindrop** [comment]
和页面高度有关，这个 pr https://github.com/alibaba/weex/pull/1484 可以 fix 此问题.
