### ISSUE TITLE
HTML5 textarea 问题

### ISSUE THREAD

**Issue by DemoPan** [alibaba/weex#1507]
template
`<textarea autofocus="true" placeholder="给卖家留言" value="给卖家留言" row="20"></textarea>`

转成html:
`<div value="给卖家留言" placeholder="给卖家留言" autofocus="true" class="weex-container" data-ref="19"></div>`

**Comment by MrRaindrop** [comment]
你可能笔误了.. 把 `row` 改成 `rows` 

```
<textarea autofocus="true" placeholder="给卖家留言" value="给卖家留言" rows="20"></textarea>
```

**Comment by DemoPan** [comment]
weex-toolkit 版本问题，我以为自己的版本够新的，竟然忽略了这个问题。
