### ISSUE TITLE
android 怎么在当前页面加载了weex之后，js更改了，怎么更新这个页面的weex呢？

### ISSUE THREAD

**Issue by zxc120301945** [alibaba/weex#1510]
js已经更改，我怎么在当前页面刷新weex呢？现在是刷新后并没有改变，只有重新开启这个页面才会更改

**Comment by Jinjiang** [comment]
Playground App 里应该是有刷新按钮的，如果不是 Playground App 而是把 WeexSDK 集成在自己的 App 里，可以参考一下 Playground App 里刷新按钮的实现 (本质上是 destroyInstance 然后 createInstance，两个 instance 的 bundle url 相同)
谢谢

**Comment by zxc120301945** [comment]
能不能具体说明下？我暂时没在demo里面发现刷新的操作

**Comment by Jinjiang** [comment]
![image](https://cloud.githubusercontent.com/assets/206848/19725789/2cfcf26e-9bba-11e6-99d2-22a240d33d61.png)

右上角

**Comment by zxc120301945** [comment]
你这是哪里的demo  我下的官网的demo没有刷新这个按钮，左边的扫描是在右边！
