### ISSUE TITLE
png透明位图显示黑色

### ISSUE THREAD

**Issue by HelloClouds** [alibaba/weex#1513]
weex页面中有部分的带有透明区域的png图片会显示成黑色，而在电脑端透明部分显示没问题。
<img width="500" alt="2e5d7403-5db6-4747-9e71-5776398dc0c3" src="https://cloud.githubusercontent.com/assets/19909935/19717403/ff94be82-9b92-11e6-814e-c1867c128738.png">

**Comment by Jinjiang** [comment]
请提供一下你的客户端信息，我这里经过测试没有发现png不透明的问题
谢谢

**Comment by Jinjiang** [comment]
这样吧，因为没有得到您更多的回复，这个 issue 我先关掉，如果你能提供更详细的信息并且我们可以确认重现，再 reopen 这个 issue
谢谢支持！
