### ISSUE TITLE
[proposal] execute javascript to inject pre-load content(library)

### ISSUE THREAD

**Issue by sospartan** [alibaba/weex#1514]
# 提供执行javascript的接口

提供native接口供app在页面(bundle)加载/执行前,做一些准备工作(注入基础库,预加载数据).
一个app的基础库是不需要跟随页面一起执行的,如果在'打包'工具能实现的前提下,完全可以预加载,能有限减少加载页面的影响.坏处是在加载页面前的内存消耗会增加.
## 修改内容

在SDKEngine和Instance添加接口执行javascript,便于在全局以及Instance范围内注入内容

1.

```
SDKEngine#executeJS(String javascriptContent)
```

2.

```
SDKInstance#executeJs(String javascriptContent)
```

**Comment by cairuiquan** [comment]
execute javascript without bootstrap 是否合适一些，instance是已经创建了，只是没bootstrap。如果连instance都没创建，后续相关操作也没办法关联起来

**Comment by seajean** [comment]
- 做JS预加载能减少JS的体积，执行bundle时的会有比较大的提升，支持这个方案支持。
- 弊端是，预加载的模块可能会在执行时受到污染，所以需要考虑执行时的封闭性，或者执行重新初始化。
- 可以考虑出个预加载模块的设计规范。

**Comment by weejulius** [comment]
想到一块了。。支持啊

**Comment by Jinjiang** [comment]
#1938 may be another way to do this job

**Comment by Jinjiang** [comment]
`jsfm-feature-0.19` branch has implemented JS service #1938 to solve this problem.
Thanks.
