### ISSUE TITLE
关于web端扩展上传，有些地方不太懂。

### ISSUE THREAD

**Issue by psychokiller666** [alibaba/weex#1516]
大概是这样。

扩展web端，我用webuploader，http://fex.baidu.com/webuploader/doc/index.html

里面有很多监听的事件（例如：当有文件选中进入文件列表，把图片转换成Base64提供预览，触发上传，上传成功后返回数据等等）

这样的一个扩展大概如何来写。

我的设想首先扩展一个<input type="file">的组建，浏览文件，用webuploader上传。相应的代码https://github.com/psychokiller666/heishi-weex/blob/master/html5/module/upload/button.js

控制上传的Module https://github.com/psychokiller666/heishi-weex/blob/master/html5/module/upload/upload.js 

那么问题来了，在控制上传的Module中，一些事件，如何渲染到页面的dom上。例如（webuploader中的fileQueued，uploadProgress，uploadSuccess等等）

请求指教

**Comment by Jinjiang** [comment]
你的问题是图片如何转换成base64然后展示在界面上吗？

**Comment by psychokiller666** [comment]
已经可以转换base64，上传过程中有一个事件xxx，这个事件是返回进度条事件，如何渲染到界面上

**Comment by psychokiller666** [comment]
例如，webuploadeer.on('uploadProgress', function(file, percentage){
xxx
})
如何渲染到界面上啊

**Comment by Jinjiang** [comment]
图片渲染到界面只能传普通 URL 到 src attribute
如果你能拿到上传成功后的 url，可以把 url 赋值给 image 的 src attribute
直接赋值 base64 给 src 我不确定目前是否完整支持，先用第一个方法
