### ISSUE TITLE
发布周期时间

### ISSUE THREAD

**Issue by elover** [alibaba/weex#1518]
目前weex的发布周期大概为2个月发一个版本，从一个互联网公司的角度来看，并且weex还可能处于初期发展阶段，整个发布时间间隔感觉有些长，感觉可以稍微短一点（一个月左右），不知道未来的发布周期是如何规定的？

如果有roadmap就更好的了

**Comment by Jinjiang** [comment]
Roadmap 会在未来公布出来，迭代时间本身是一个月，最近双十一团队负担会重一些所以不太规律请见谅
谢谢
