### ISSUE TITLE
请问weex中如何实现js间页面跳转或者网站访问

### ISSUE THREAD

**Issue by guyikun** [alibaba/weex#1520]
请问we中如何去访问一个网页，必需要用webview直接加载嚒？
有没有类似href的参数设定，点击后可以直接跳转？
两个js间的页面跳转呢以及两者间数值如何传递？

**Comment by Hanks10100** [comment]
有 `<web>` 标签可以渲染一个页面，内部就是使用 webview 实现的，具体用法可以参考[官方文档](http://alibaba.github.io/weex/doc/components/web.html)。

另外还有 [`<a>`](http://alibaba.github.io/weex/doc/components/a.html) 标签可以定义超链接，能够实现点击跳转。

**Comment by guyikun** [comment]
@Hanks10100 webview的话说实话并没有实现跳转，应该只是加载所制定的页面显示。
<a>的话我有一个问题:
<template>
	<div>
		<a href="https://www.163.com" style="width:100;">
			<text class="text" style="width:80;"> 163 </text>
		</a>
	</div>
</template>

<style>
	.text{
		margin-left: 20;
		/*line-height: 63;*/
		text-align: center;
		font-size: 24;
		/*line-height: 24;*/
		margin-bottom: 5;
	}
</style>

<script>
	module.exports = {
		data:{
			width: 20,
			height: 20,
			textdata:{
				text: '',
				link: ''
			}
		},
	}
</script>
简单的一个demo，我PC上可以跳转到163网页，但是weex XX.we --qr后，用playground扫描生成的二维码，点击后确实有跳转，地址栏上也显示的www.163.com，但却无法显示页面内容(android 手机)，
请问是我的demo有问题嚒？

**Comment by guyikun** [comment]
@Hanks10100 webview我试过了，应该只是加载了所指的网页内容，并没有实现跳转。
<a>的话
**<div>
		<a href="http://www.163.com" style="width:100;">
			<text class="text" style="width:80;"> 163 </text>
		</a>
	</div>**

我测试后发现PC上没问题，可以跳转到163页面，但是加上--qr手机(android)扫描二维码后，点击跳转，地址栏上确实是www.163.com，但是内容却是空白，请问这样写有问题么？
感谢～

**Comment by guyikun** [comment]
@Hanks10100 
 webview我试过了，应该只是加载了所指的网页内容，并没有实现跳转。
<a>的话
`<div>
		<a href="http://www.163.com" style="width:100;">
			<text class="text" style="width:80;"> 163 </text>
		</a>
	</div>`

我测试后发现PC上没问题，可以跳转到163页面，但是加上--qr手机(android)扫描二维码后，点击跳转，地址栏上确实是www.163.com，但是内容却是空白，请问这样写有问题么？
感谢～

**Comment by Hanks10100** [comment]
你这种情况的话应该用 `<web>` 标签，通过改变 `src` 的方式更新 URL。

代码例子如下：

```html
<template>
    <div class="wrapper">
      <text class="button" onclick="go">Go to 163</text>
      <web class="content" src="{{url}}"></web>
    </div>
</template>

<script>
  module.exports = {
    data: {
      url: 'https://m.taobao.com'
    },
    methods: {
      go: function() {
        this.url = 'http://www.163.com'
      }
    }
  }
</script>

<style>
  .wrapper {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
  }
  .button {
    width: 350;
    height: 60;
    line-height: 60;
    margin-left: 200;
    margin-right: 200;
    margin-top: 10;
    margin-bottom: 10;
    text-align: center;
    border-color: #666666;
    border-width: 1;
    color: #666666;
  }
  .content {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    margin-top: 80;
  }
</style>
```
