### ISSUE TITLE
我想让express和weex结合使用啊，请问能不能做一个helloworld出来

### ISSUE THREAD

**Issue by SteveCruise** [alibaba/weex#1533]
github上有一个express-weex-html5，但是运行不起来啊

**Comment by Jinjiang** [comment]
帮你搬砖到仓库作者了 https://github.com/ht616/express-weex-html5/issues/1
后续在那边追踪吧
谢谢了

**Comment by Jinjiang** [comment]
多说一下，和 Weex 配合使用的服务端方案确实值得搞一个，但暂时不在我们的计划内，如果你提到的仓库可以正常工作，或未来我们有这方面打算，我们会重新 reopen 这个 issue
