### ISSUE TITLE
安装weex-toolkit之后，写好文件却无法弹出默认浏览器

### ISSUE THREAD

**Issue by CYZstudy** [alibaba/weex#1535]
首先描述我已经试过的情况：
1 在命令行已经试过start www.baidu.com 显示可以打开默认浏览器，证明命令行是没有任何问题的。
2 下载的为0.5.8版本，所以在命令行输入weex显示
![image](https://cloud.githubusercontent.com/assets/22089819/19826871/f5ceeb42-9dc8-11e6-9204-8198bd88455f.png)也是没有问题的，不存在weex-toolkit 安装不对的问题。
3 写好一个we文件之后，在命令行运行之后会显示
![image](https://cloud.githubusercontent.com/assets/22089819/19826880/420360f6-9dc9-11e6-87bf-329b31aa8855.png)也是没有问题，就是不弹出浏览器。
4 在playground中是可以跑we文件的，也是证明此文件是没有任何问题的。但是不知道为什么就是不弹出默认浏览器，已经换了几个浏览器，都不行。电脑为win10 32位的

**Comment by Jinjiang** [comment]
我在自己的windows上测试没有发现异常，想确认几个细节：
* 您的默认浏览器配置是否正确
* 您所在的目录是否有正常的读写权限

**Comment by Jinjiang** [comment]
如果有条件的话，再到 weex-toolkit 的源代码里追踪一下 https://github.com/weexteam/weex-toolkit/blob/dev/bin/weex.js#L219 这行代码的执行是否有效

谢谢

**Comment by yangzhou2** [comment]
请问问题解决了吗，我现在也遇到这样的问题了

**Comment by JackPu** [comment]
@yangzhou2  你也是windows么？

**Comment by yangzhou2** [comment]
@JackPu 是的 win10
