### ISSUE TITLE
Inter-instance communications

### ISSUE THREAD

**Issue by Jinjiang** [alibaba/weex#1536]
See WHATWG HTML Spec:
https://html.spec.whatwg.org/multipage/comms.html

There are three types of web messaging solution:
1. Cross-document messaging: just normal `postMessage`. Fit for messages between parent instance and `<embed>` instance
2. Channel messaging: need to send a channel object through `postMessage` from an instance to another. Potentially it may lead to memory leaks and is complicated to use. So not recommended.
3. Broadcast to other browser-contexts: **new** `BroadcastChannel` APIs. Fit for communications between Weex instances which have no strong relationships.

Article: BroadcastChannel API: A Message Bus for the Web https://developers.google.com/web/updates/2016/09/broadcastchannel

Also there are some existed polyfill to see:
- https://gist.github.com/alexis89x/041a8e20a9193f3c47fb
- https://gist.github.com/inexorabletash/52f437d1451d12145264

I think we can implement BroadcastChannel API to solve inter-instance communication problems first.

**Comment by cxfeng1** [comment]
If the new `BroadcastChannel` API support sending messages with Objects or Arrays， is there any mechanism to prevent it from memory leak?

**Comment by Jinjiang** [comment]
Just send the value by force, not the reference.

**Comment by Hanks10100** [comment]
I support to use `BroadcastChannel` API, it was born to fix this problem.

According to the [specification](https://html.spec.whatwg.org/multipage/comms.html#broadcasting-to-other-browsing-contexts), I have already implemented a simple [ployfill](https://github.com/Hanks10100/weex/blob/jsfm-feature-broadcast-channel/html5/shared/BroadcastChannel.js) of it, and add some [test cases](https://github.com/Hanks10100/weex/blob/jsfm-feature-broadcast-channel/html5/test/unit/shared/BroadcastChannel.js). 

### APIs

+ `postMessage`: Sends the given message to other BroadcastChannel objects set up for this channel.
+ `close`: Closes the BroadcastChannel object, opening it up to garbage collection.

### Usage

```js
const Stack = new BroadcastChannel('Avengers')
Stack.onmessage = function (event) {
  console.log(event.data) // in this case, it's "Hulk Smash !!!"
}

// in another instance
const Hulk = new BroadcastChannel('Avengers')
Hulk.postMessage("Hulk Smash !!!")
```

Run the code above, Stack can receive the message from Hulk.

Welcome to review the code and discuss with me. :)

**Comment by Jinjiang** [comment]
Great job! Btw, can we avoid memory leaks here?

**Comment by Hanks10100** [comment]
In the spec, the `message` should [*StructuredClone*](https://html.spec.whatwg.org/multipage/infrastructure.html#structuredclone) to the `event.data`. In order to achieve *window* and *web worker* communication, they have to do so, but we don't have this restriction.

However, in order to avoid memory leaks and respect for the spec, we can also deep clone the `message` to the `event.data`.

**Comment by Jinjiang** [comment]
If we just send the data without deep clone, does it cause memory leaks or some problem else?I think we could have a discuss about what's the point and details of that danger? Maybe deep clone is not necessary.

**Comment by totzcc** [comment]
iOS Weex 0.8 运行的时候 
在 ready 里面写
` 
var Stack = new BroadcastChannel('changeSearchOptions')
				Stack.onmessage = function (event) {
					console.log("received message");
					console.log(event.data) // in this case, it's "Hulk Smash !!!"
				}
`
出现错误
`ReferenceError: Can't find variable: BroadcastChannel`

现在这个还没被支持吗?

**Comment by Hanks10100** [comment]
@totzcc 我们还在讨论中，还不支持。

**Comment by wfc1870** [comment]
mark

**Comment by Jinjiang** [comment]
supported

**Comment by jiaowoxiaoming** [comment]
在我们的安卓应用中，new BroadcastChannel('xxx')不能使用 但是在playground中可以使用
