### ISSUE TITLE
 iOS list列表中下拉刷新时会有闪烁的效果，体验很差

### ISSUE THREAD

**Issue by allentofight** [alibaba/weex#1537]
![bad](http://i.imgur.com/SJOJjjr.gif)
如图所示，在已有数据源的基本下再下拉刷新(请求完网络数据更新数据源)会有很明显的闪烁效果，体验很差，下拉刷新时的相关代码如下

```
 var vm = this;
 if (page === 1) {
        vm.lists = [];
 }
var dataSource = vm.lists;
dataSource.push({'promotionItems': model.promotion_items});
```

list是数据源，数据其实是一样，只不过是数据地址不一样，结果就造成了这种效果，应该是WXListComponent实现的刷新机制问题导致这种下拉刷新后的闪烁

正常的下拉刷新效果可以看淘宝首页的下拉刷新，很顺畅，没有闪烁效果

**Comment by Jinjiang** [comment]
你好，想先确认一下，template 源代码里的 repeat 写法是 `repeat="list"` 还是 `repeat="item in list"`，前者的更新逻辑设计得不够好，而且已经不推荐使用了，后者可以保持相同的内容不会被重复创建和更新

**Comment by allentofight** [comment]
Hi,用`repeat="item in list"`果然就好了，cool!多谢!

**Comment by allentofight** [comment]
实测现在发现另一个问题，下拉刷新后由于数据源变化，cell里如果有图片，图片有时会先显示本应是其他cell的图片，再显示第一个cell的图片，会有一种闪烁效果

同时在第一个cell中的text有时下拉刷新后就没掉了

**Comment by allentofight** [comment]
经排查，发现还有一个地方未未使用`repeat="item in list"`这种形式，使用了就OK了，sorry
