### ISSUE TITLE
在AS运行项目后，点击主界面列表报Network Error

### ISSUE THREAD

**Issue by fozero** [alibaba/weex#1538]
按照文档我已经将ip设置成我本地ip地址，运行后点击主界面列表无法查看显示示例界面，报网络错误

**Comment by Jinjiang** [comment]
请提供一下更具体的错误信息和系统/平台信息，方便我们排查问题
谢谢

**Comment by Jinjiang** [comment]
不好意思，由于长期没有得到更多反馈，这个 issue 做关闭处理
再开 issue 的时候有劳按照模板里的描述尽量完整详细的描述您的问题
谢谢
