### ISSUE TITLE
请问如何判断scroller下拉的距离？

### ISSUE THREAD

**Issue by jingxin2015** [alibaba/weex#1539]
场景：想实现下拉刷新的三个状态效果
状态1显示：下拉刷新
状态2显示：松开刷新
状态3显示：正在刷新

由状态1变为状态2时，是根据下拉距离判断的。

**Comment by cooliean** [comment]
估计的修改代码来回传事件

**Comment by ydream** [comment]
<list><header onrefreshStart="{{ 下拉刷新激活 }}" onRefreshActivate="{{ 下拉刷新触发 }}"  onRefreshDeactivate="{{ 下拉刷新取消 }}" pullHeight="{{ 下拉高度值 }}">  </header>  。。。

能不能在header组件加几个这种状态的回调事件，这样方便定制复杂的交互行为。

loadmore同上。

**Comment by ydream** [comment]
另外header组件里包含子组件的情况，一旦创建后没法去动态变更里面的内容，定制复杂的下拉刷新效果没发实现了。
`<refresh><text style="display:show;color:red" if="{{ pullHeaderOffset > 100 }}">release to reload</text><text style="display:show;color:red" if="{{ pullHeaderOffset <= 100 }}">pull to reload</text></refresh>`

**Comment by acton393** [comment]
透出下拉距离这个有计划， 但出于性能方面还需要再考虑一下

**Comment by Jinjiang** [comment]
我现汇总到 #1494 了
