### ISSUE TITLE
［Android］a链接跳转报错

### ISSUE THREAD

**Issue by lanceliu** [alibaba/weex#1540]
我用的 0.8.0.2版本，上面的问题解决了，但是报新的错。
如果是a 链接则会报错，
bundle源码：

``` javascript
{
                  "type": "a",
                  "attr": {
                    "href": function () {return this.pages['i-bio-desc']}
                  },
                  "children": [
                    {
                      "type": "text",
                      "attr": {
                        "value": "个人简介"
                      }
                    }
                  ]
                },
```

报错信息
10-25 13:57:42.462 2424-2453/org.yuntu.app E/weex: [WXBridgeManager] invokeInitFramework java.lang.UnsatisfiedLinkError: No implementation found for int com.taobao.weex.bridge.WXBridge.initFramework(java.lang.String, com.taobao.weex.bridge.WXParams) (tried Java_com_taobao_weex_bridge_WXBridge_initFramework and Java_com_taobao_weex_bridge_WXBridge_initFramework__Ljava_lang_String_2Lcom_taobao_weex_bridge_WXParams_2) at com.taobao.weex.bridge.WXBridge.initFramework(Native Method) at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:1027) at com.taobao.weex.bridge.WXBridgeManager.invokeCreateInstance(WXBridgeManager.java:826) at com.taobao.weex.bridge.WXBridgeManager.access$200(WXBridgeManager.java:273) at com.taobao.weex.bridge.WXBridgeManager$5.run(WXBridgeManager.java:807) at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:234) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:148) at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by YorkShen** [comment]
.so文件加载失败，处理器架构是什么，arm v7? x86? x86_64?

**Comment by lanceliu** [comment]
x86的，API 23 的模拟器  @YorkShen

**Comment by lanceliu** [comment]
@YorkShen 我把代码上传了，帮我看一下吧， https://github.com/lanceliu/weex-demo.git

**Comment by YorkShen** [comment]
@lanceliu clean & rebuild project 之前x86架构的so被删除了，现在已经重新发布，此问题应该已解决了。

**Comment by lanceliu** [comment]
@YorkShen 重新build还是一样的，感觉sdkjar包没有改变的呢，sample代码已经上传。https://github.com/lanceliu/weex-demo/invitations

**Comment by YorkShen** [comment]
@lanceliu 需要clean工程，或者点击sync project with gradle files，否则已经下载的依赖项不会更新
