### ISSUE TITLE
请问，参数传递值是否可以支持dom结构，或者是回调函数呢？

### ISSUE THREAD

**Issue by carly1987** [alibaba/weex#1541]

**Comment by Jinjiang** [comment]
可以，Element 和 function 类型的变量会自动被转换成 ref 字符串或 callbackId 字符串再传递给 native，native 触发回调的时候，会通过底层接口回传 callbackId，JavaScript 会自动识别其对应的 function 并执行回调
谢谢

**Comment by carly1987** [comment]
如您所说，也就是：
<test hd="<text>hhhhhhhhh</text>" bd="renderBd"></test>
....
   renderBd: function(){
      return '<text>bbbbbb</text>'
   }
....
//组件定义...
<div>
    <div class=hd">{{hd}}</div>
    <div class=bd">{{bd}}</div>
</div>

但是并没有得到我想要的呢？  是我使用方式不对么？

**Comment by Jinjiang** [comment]
哦，我理解错你的意思了，请无视我前面的回答，针对你列出的这种情况，我们不支持参数中带 DOM 结构或回调函数，DOM 结构还是要在 template 里写清楚才可以
谢谢

**Comment by carly1987** [comment]
但是  我目前在做一个split controller 这样的组件，里面包含：
```
<div>
     <div class="side">
          //side content
           ....

     </div>
     <div class="page">
         <div class="nav"></div>
         <div class="content">
              {{content}}
         </div>
     </div>
</div>
```


然后 调用时：
```
<weex-split>
   <div>
        <text>content</text>
    </div>
</weex-split>
```


那么  side content 的dom 要如何传呢？   如果  把side的结构固定死的话，不是我写这个组件的初衷。  因为现在h5不是被降级么，所以页面的过渡效果也没有，也不是真正意义上的单页面。  所以我想写这个容器去快速构建一个带侧边栏的页面。
