### ISSUE TITLE
IOS版本的下拉和上拉的体验（UI）很差呢，Android 版本的效果都很正常的，希望能修正一下

### ISSUE THREAD

**Issue by cooliean** [alibaba/weex#1542]
如题，
这个gif的效果可能不是很好的，但是基本是看不到轮子的
不要说我demo回弹太快，官方demo那个轮子也是被挡住了的。
![untitled](https://cloud.githubusercontent.com/assets/4754617/19843445/6e42c1f8-9f5d-11e6-913f-33020b12f873.gif)

**Comment by acton393** [comment]
@cooliean   麻烦你的refresh的代码的部分可以附一下，看一下

**Comment by jingxin2015** [comment]
这个选项卡是原生的还是weex搞的啊？看起来不错

**Comment by acton393** [comment]
hi @cooliean  #1550  这个pr 已经修掉， 麻烦看一下

**Comment by cooliean** [comment]
#1550  我在你github中拿下来的版本是对的了。什么时候能发布出来呢。 ：）

**Comment by cooliean** [comment]
@jingxin2015
自己定义的组件。借鉴的Tabbar

**Comment by acton393** [comment]
@cooliean 麻烦先暂时使用一下cocoaPods 源码依赖，如果是添加framework的话，可以参照我github 中教程编译生成
