### ISSUE TITLE
weex如何固定死元素大小

### ISSUE THREAD

**Issue by chengweipeng123** [alibaba/weex#1543]
weex中的说明：
In order to simplify the page design and the complete underlying implementation, the width of our default screen is unified to 750 pixels, different screens should be scaled with corresponding ratio.

也就是说weex的元素在所有的屏幕中使用的放大缩小来进行屏幕适配的，源码中也有大量的同WXScreenResizeRadio的计算，所以我们现在开发的app包括官方的weex playground，在iphone5s中看起来比较精致，但一到iphone 6plus上，界面一拉大，扑面而来一股粗糙之感，。。。。。不能忍啊。。

我们想对我们的元素在不同的屏幕上限定死大小，请问有什么好的办法？

比如在ios原生开发里，如无适配设置，font size为11，在各个屏幕上都为11；高度为300，各个屏幕都为300。

**Comment by Hanks10100** [comment]
750 是我们默认设定的 viewport 宽度，是个相对值，绘制时会根据机型转成实际物理像素。

目前我们也在讨论如何支持自定义 viewport 和实现绝对宽度，欢迎来 #421 贡献思路 ~
