### ISSUE TITLE
dom.addRule is not a function

### ISSUE THREAD

**Issue by xl602** [alibaba/weex#1545]
***Bug***

H5页面报错

**Comment by Jinjiang** [comment]
Could you please supply a reproduce demo or code snippets and the platform/version you use?
Thanks

**Comment by Jinjiang** [comment]
由于长期没有得到反馈，该问题做关闭处理
如果有后续讨论仍可再次继续
谢谢

**Comment by MrRaindrop** [comment]
可能是 h5-render 版本问题, `dom.addRule` 的 h5 端实现比其他端要迟一些。目前 `dev` 分支已支持该特性 https://github.com/alibaba/weex/blob/dev/html5/render/browser/extend/api/dom.js#L40
