### ISSUE TITLE
请问这个效果目前weex能实现吗？

### ISSUE THREAD

**Issue by jingxin2015** [alibaba/weex#1546]
先上图，闲鱼app的首页选项卡效果：
![qq 20161101131230](https://cloud.githubusercontent.com/assets/16143766/19880113/1ae494d6-a035-11e6-8f4d-b3d714a96f75.jpg)

上图中 “新鲜的” 和  “附近的” 是个选项卡
1、可以左右滑动切换选项卡，当显示“新鲜的”页时，向右滑动不会切换，向左滑动切换到“附近的”，再向左滑动不会变化。
2、切换选项卡时，“新鲜的”下面的黄色横线，会有个平移动画，平移到“附近的”下面，滑动的时候这个黄色横线会跟着动。
3、在“新鲜的”页面，向上拉拉到底的时候会有加载更多的动作，但是向下拉选项卡标签会跟着动，也就是选项卡标签和内容之间不会有下拉刷新的效果。

不知道weex能否实现？这个效果算不算个性？

**Comment by Jinjiang** [comment]
目测都是没问题的，滑动切换选项卡这个功能可能需要基于 slider组件定制或扩展一下，使用答疑可以到 gitter，这里希望 issues 用来追踪 bug 或新功能实现
谢谢

**Comment by jingxin2015** [comment]
老大，你的回答是不是过于草率了，如果按你的思路来考虑的话，那所有的问题都不是问题了，都可以通过扩展来解决不是吗？
但是对于我们不会原生的同学来说，这个扩展真的很难的，如果是这样的话，不会原生的人就不用考虑用weex了？

**Comment by Jinjiang** [comment]
可以到 gitter 继续讨论
