### ISSUE TITLE
Android component 中动态修改大小Bug

### ISSUE THREAD

**Issue by YanyeZhang** [alibaba/weex#1555]
代码比较多，先以口头描述。
场景：在桥接component（ <carousel> 继承自**WXVContainer**）的过程中，希望动态的改变component中子view的大小,以实现类似画廊滑动放大缩小效果。

子view 定义在文件中。
```javascript
  <carousel class="slider">
       <div repeat="{{promotionItem in item.promotionItems}}" >
             // and so on
       </div>    
   </carousel>
```

执行代码后，ui不变化，通过ddms发现子view的容器本身的大小变化了，展示出来的大小却没有变化。

![image](https://cloud.githubusercontent.com/assets/8480050/19888629/daeb4790-a06a-11e6-813e-dac0a8f537cc.png)

**Comment by allentofight** [comment]
+1,如何实现carousel效果，iOS很简单，android貌似有些复杂啊

**Comment by YorkShen** [comment]
* weex内置的slider的是否可以实现这个效果？
* 如果不能，提供weex版本号or依赖的分支，可复现问题的代码
@YanyeZhang

**Comment by YanyeZhang** [comment]
@YorkShen  使用 slider-neighbor  解决了 ，不过 slider-neighbor 还有很多问题 详细#1709
