### ISSUE TITLE
[bug]自定义component组件，重写了IWXActivityStateListener的相关生命周期方法却没有被调用

### ISSUE THREAD

**Issue by squirrelx** [alibaba/weex#1557]
由于自定义的component的组件需要涉及到activity的生命周期的几个方法，重写了此接口的方法，但是在实际执行的时候并没有进入到我的方法
android    0.7.0版本

**Comment by misakuo** [comment]
你需要手动调用组件的`registerActivityStateListener()`方法

**Comment by squirrelx** [comment]
@misakuo 你的意思是在我的自定义组件里边重写registerActivityStateListener()方法吗？
我看WXComponent已经写了啊    我要怎么复写呢：
```
  public void registerActivityStateListener() {
    if (mInstance != null) {
      mInstance.registerActivityStateListener(this);
    }
  }
```

**Comment by squirrelx** [comment]
@misakuo   你的意思是在init方法里调用这个方法 是吧？

**Comment by squirrelx** [comment]
@misakuo 你好  我在initCompnentHostView里边手动调用了this.registerActivityStateListener()   复写的onActivityStart等生命周期方法，还是都没有调用。。。  请指教。。

**Comment by squirrelx** [comment]
@misakuo  通过手动调用的方式，重写了onActivityStart onActivityCreate onActivityResume onActivityStop onActivityPause onActivityDestroy，发现在页面启动的时候只会调用initCompnentHostView方法，start和resume没调用，切换到别的activity的时候会调用destroy方法，如果不切换只是按home键然后再打开app的时候会调用resume方法。   这些调用怎么和原生activity的不一致啊，比如启动的时候 start,resume create等都没有调用呢

**Comment by misakuo** [comment]
在你component的构造函数或其他初始化的位置，简单调用`registerActivityStateListener()`即可，不需要做额外操作。on开头的回调函数由sdk调用，不需要你手动触发。

**Comment by squirrelx** [comment]
@misakuo  关键用来承载we（或者说js）的activity是必须要实现IWXRenderListener接口的，实现此接口需要复写onViewCreated，同时要registerRenderListener；我怎么来保证本activity在oncreate或者onstart等执行的时候我自定义的组件registerActivityStateListener先执行了呢，否则activity启动的时候  还没有注册好activitystatelistener呢。。

**Comment by squirrelx** [comment]
我是参照playground代码来写的，activity启动的时候（onstart onresume等），onViewCreated还没被全部回调呢，也就是说我在自定义component的构造函数里边的registerActivityStateListener还没有被执行呢，所以activity在启动的时候调不到我在component里边复写的生命周期方法。。。

**Comment by misakuo** [comment]
参考WXPageActivity，在Activity生命周期的各个回调里会调用WXSDKInStance里相应的回调函数，如果在调用的时候component还没有registerActivityStateListener或者是还没有初始化的话，是接受不到相应状态的回调的

**Comment by squirrelx** [comment]
我是参照的WXPageActivity的做法啊，我无法控制activity启动的时候就能使component注册上啊，weex 的playground当前肯定也做不到，我就参照搞的。想问下你们的建议是什么，怎么才能控制时序

**Comment by misakuo** [comment]
由于weex页面是在onCreate之后才开始异步渲染的，所以监听页面可见生命周期`onCreate`/`onStart`/`onResume`确实是不可靠的做法。你的时序控制是否可以转移到View的`onAttachToWindow`和`onDetachToWindow`来控制？

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
