### ISSUE TITLE
自定义Native组件，二维码扫描

### ISSUE THREAD

**Issue by blacksunset** [alibaba/weex#1565]
Hi,我想自定义个组件放到一个模块里面，用到二维码扫描，但是看到playground里面的直接把zxing的源码复制进来了，导致在我的模块里面应用zxing会跟playground里面的冲突，怎么破

**Comment by HJ-StevenSun** [comment]
你 吧playground 里面的模块 的注册 注释掉 就是 的 或者 你重现建一个模块 你调用你自己的模块就是的。WXSDKEngine.m  官方提供的 模块组件 都是在这个 类文件里面注册的

**Comment by acton393** [comment]
@blacksunset  zxing 在iOS 目前 playground版本中应该没有使用的，
