### ISSUE TITLE
slider的需求

### ISSUE THREAD

**Issue by ChrisWuAnHui** [alibaba/weex#1568]
如何禁止slider的手势滑动，而且只有点击slider的内容才可以滑动 。

例如轮播图，既不让它自动切换，也不让他滑动切换。只有点击内容（图片）的时候才切换下一张

**Comment by alext1981** [comment]
一般点击的时候会触发事件打开新的页面，你的场景除了翻看图片外没有打开新页面的需求吗？  如果只是点击切换图片，是不是不需要用slider来做呢

**Comment by ChrisWuAnHui** [comment]
@alext1981 例如做题的，必须点击了答案以后才能自动切到下一题。

**Comment by ChrisWuAnHui** [comment]
![image](https://cloud.githubusercontent.com/assets/17464713/20050331/af8d5244-a503-11e6-93c9-104e8246d865.png)

**Comment by Jinjiang** [comment]
同意 alext1981 支持手动横滑是 slider 的默认特性，这个场景选择 slider 感觉不是特别合适
建议直接用导航栏实现横滑效果，这里不再展开了
谢谢
