### ISSUE TITLE
Promise 在 html5 端的问题

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1569]
WEEX HTML5: 0.4.0 从 仓库的 dev 分支 dist 出来的。
在任意 js 文件及 we 文件内 new Promise()报错
报错内容如图：

猜测是 weex 修改了内置 document 对象导致 babel 内置的 Promise 的 polyfill 调用 document.createTextNode 时报错
![73348f7f-684e-4bcf-9abf-74cbfe60dbe1](https://cloud.githubusercontent.com/assets/10400425/19958457/4a7ce81e-a1da-11e6-8b14-acda920a9b2f.png)

**Comment by lmnsg** [comment]
我目前的解决方案是显示的调用 window.Promise ,  new window.Promise()

**Comment by MrRaindrop** [comment]
你是不是引入了 promise polyfill ? 其实不需要这个一步，因为 jsfm 已经加了这个。相反你应该去掉这个 polyfill 因为部分 polyfill 里用到了 document 但是在 weex 的运行环境里 document 并不是浏览器里的那个 document.

**Comment by lmnsg** [comment]
@MrRaindrop  因为 webpack 使用 babel-runtime 编译的时候会自动引入 这个 polyfill, 有什么方法可以解决么

**Comment by MrRaindrop** [comment]
不要太依赖 babel-runtime，如果需要 es6 的某些 polyfill 建议可以单独引入一些类似 [core-js](https://github.com/zloirock/core-js) 或者 [regenerator](https://github.com/facebook/regenerator) 这样的库。

**Comment by lmnsg** [comment]
恩，我删除掉了 runtime , 不过还是建议 weex 不要去篡改 浏览器的 document 对象...

**Comment by lmnsg** [comment]
删除掉 runtiem 后之前很多代码都爆掉了，可以把标签改一下么..  建议再考虑考虑这个问题

**Comment by MrRaindrop** [comment]
@lmnsg 这边是有计划做改动的，目前最新版本应该已经做了，不确定是否已经合并到 dev 分支。 @Jinjiang @fkysly

**Comment by Jinjiang** [comment]
@lmnsg #1637 已经修复了这个问题，再新的 JS Framework 版本应该不会有这个问题了
谢谢

**Comment by lmnsg** [comment]
什么时候会更新到 dev 分支呢，或者我怎样可以使用呢

**Comment by Jinjiang** [comment]
暂时的话，可以在 jsfm-feature-0.17 分支重新 build 一个 js framework 代码在 native 的 sdk resource 里替换掉
