### ISSUE TITLE
navigator的用法问题

### ISSUE THREAD

**Issue by guyikun** [alibaba/weex#1570]
Hi，请问navigator具体要怎么用？
我看了weex-dev 的examples\component下的navigator-demo.we代码，
结果Log显示
[JS Framework] Vm#$call is deprecated, please use "require('@weex-module/moduleName')" instead
而且weex examples\component\navigator-demo.we后点击push，跳转到
http://127.0.0.1:8081/weex_tmp/h5_render/index.html?page=./examples/build/component/navigator-demo.js?test=1
后界面一片空白？
是因为这个call的方式deprecated的问题还是源码的url的问题？
为什么手机上playground的navigator的那个案例是好的呢？
感谢~

**Comment by bluebird78999** [comment]
如果你不是最新代码，请先拉下最新代码，再运行试下。
weex-dev目前代码里开的本地服务端口已经变成12580，将你的地址改为：http://127.0.0.1:12580/weex_tmp/h5_render/index.html?page=./examples/build/component/navigator-demo.js?test=1  应该是能访问的。
你运行起playground应该能看到如下日志：`<Weex>[log]WXMonitor.m:148, Performance:
    pageName: http://127.0.0.1:12580/examples/build/component/navigator-demo.js`, 这是playground运行环境的navigator-demo地址。

Vm#$call 方式确实已经废弃，使用`var navigator = require('@weex-module/navigator');`即可取到当前VM的navigator，然后调用push/pop方法即可。
文档参考：https://alibaba.github.io/weex/doc/modules/navigator.html

**Comment by nisang** [comment]
如何需要实现两步pop？这样实现怎样：navigator.pop({'animated' : 'false','step':'2'},function(){});

**Comment by bluebird78999** [comment]
目前不支持两步pop。
