### ISSUE TITLE
slider组件里的indicator是圆形的，需要可定制，比如三角形

### ISSUE THREAD

**Issue by cokeknight** [alibaba/weex#1571]
slider组件里的indicator是圆形的，需要可定制，比如三角形

**Comment by cokeknight** [comment]
官方能不能给个例子，如何继承扩展SDK里的UI组件，不敢改SDK里的代码

**Comment by jingxin2015** [comment]
帮顶，最好是可以随意定义样式

**Comment by Hanks10100** [comment]
@cokeknight 官方文档里有 [Extend to Android](http://alibaba.github.io/weex/doc/advanced/extend-to-android.html#component-extend) 和 [Extend to iOS](http://alibaba.github.io/weex/doc/advanced/extend-to-ios.html#custom-native-components-for-ios)。 更详细的文档我们也在整理，等新版网站上线了会有的。

**Comment by Jinjiang** [comment]
@jingxin2015 开发的时候确实可以考虑不展示 indicator，然后用前端组件模拟，slider 本身是非标准组件，这里的设计很难让所有人满意，如果有照顾不到的场景，我们推荐大家自行在 native 层扩展，或者通过前端组件模拟
希望理解

**Comment by cokeknight** [comment]
@Jinjiang 在 native 层扩展的话，indicator代码是在SDK里，我是直接改SDK吗？还是自定义组件的方式？因为我只是改下render方法，要是自定义组件又太累赘了，

**Comment by alext1981** [comment]
@cokeknight  不同的使用者对UI有不同的需求，weex sdk很难满足所有人的口味，建议你在自己的项目里对组件进行自定义扩展，如果改动比较小，可以通过继承官方组件并修改对应部分的方式实现。现在weex团队正在建立插件机制以及对应的市场，以后你完全可以把自己的组件发布出来，让更多的人使用。面对不同的需求有不同的解决方案，可能会比单一的实现有更好的适应性，也可以让大家更方便地参与到weex的发展中来，期待大家能开发出比官方实现更好的组件。
