### ISSUE TITLE
stream.fetch错误

### ISSUE THREAD

**Issue by tuzi8080808080** [alibaba/weex#1576]
返回状态吗都是-1,只有http://alibaba.github.io/weex/doc/modules/stream.html这个例子里面的是200，这个是怎么回事？

**Comment by pp1232** [comment]
fetch应该是可以正常使用的，
返回状态码可能和服务器接受参数的格式等有关系，可能需要加入heasers{}，
建议后台服务端打断点调试下

**Comment by tuzi8080808080** [comment]
web端返回值和android端返回不一样，写.we文件使用weex命令在命令行调试打开时web返回值一直是-1，在android上是没问题的  这个是怎么回事？

**Comment by MrRaindrop** [comment]
是不是跨域了？`fetch` 的实现是 `xmlHttpRequest`，只有 xhr 抛异常了才会返回 -1。比较常见的错误大概就是跨域了，大概是你的服务器没有设置 CORS.
