### ISSUE TITLE
Android weex原理问题

### ISSUE THREAD

**Issue by YanyeZhang** [alibaba/weex#1577]
根据这段时间对weex的研究，想请问一下weex的原理是不是这样的：
**通过v8引擎解码js文件，然后渲染canvas，而不是真正的桥接view。Native View只相当于一个尺子的作用。**

**Comment by Hanks10100** [comment]
可以参考[这篇文档](http://alibaba.github.io/weex/doc/advanced/how-it-works.html)，和下边这张图。

![Weex Architecture](http://gtms02.alicdn.com/tps/i2/TB1ootBMpXXXXXrXXXXwi60UVXX-596-397.png)

在 issue 里讨论这个问题，只言片语容易被断章取义。希望你能够关注我们对外的推广活动和文章。

**Comment by sospartan** [comment]
现在都是实实在在的view,以后可能不是
