### ISSUE TITLE
如何计算展示一段长文本所需要的大小

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#1581]
我有一段长文本，默认展示的时候是显示一部分内容，需要用户点击后才能全部显示。实现的时候有几个问题：

1. 在给定宽度、字体样式下，这段文本全部展示需要多少高度？
2. 如何获取指定元素当前的位置、大小？

**Comment by hch2187821** [comment]
同问

**Comment by Hanks10100** [comment]
我们在 dom module 中已经实现了 `getComponentRect` 接口，可以获取页面元素的大小和位置。目前还没 release ，在下一个版本中可用。

```js
{
  result: true,
  size: {
    bottom: 60, // 组件下边界相对屏幕视口上边界的距离
    height: 15,
    left: 0, // 组件左边界相对屏幕视口左边界的距离
    right: 353, // 组件右边界相对屏幕视口左边界的距离
    top: 45, // 组件上边界相对屏幕视口上边界的距离
    width: 353
  }
}
```

**Comment by bsed** [comment]
good ~

**Comment by Hanks10100** [comment]
See the details in #1455 .

**Comment by Neeeo** [comment]
请教一下，在给定宽度、字体样式下，这段文本全部展示需要多少高度？

**Comment by Hanks10100** [comment]
@Neeeo 如果只有一行的话，和 line-height 相同；如果多行那就不确定了，可以通过 getComponentRect 获取文字高度。

**Comment by Neeeo** [comment]
@Hanks10100 是多行。我的需求主要是想在js里能计算出文字高度，这样我就能决定是否限制文本区域高度，并显示展开按钮

**Comment by Hanks10100** [comment]
@Neeeo 可以用 getComponentRect 获取文字高度啊，这个版本里还没有。另外，`<text>` 标签支持 `lines` 这个样式（[文档](http://alibaba.github.io/weex/doc/components/text.html#styles)），可以指定文字和行数。

针对这个需求的话，你暂时可以根据文字个数做判断。

**Comment by Neeeo** [comment]
@Hanks10100 我知道这个方法之后有，只是只有这个方法还不够吧。我写个伪代码说明一下：
```html
<text id="hello">{{content}}</text>

<script>
data = {
  content:''
}

ready:function(){
  asyncGetData(function(ret){
    this.content(ret);
 })
},
setupFold:function(){
 
//根据 getComponentRect 设置是否显示展开文本按钮
}
</script>
```
在异步获取数据，设置给text后，什么时候知道`text`组件绘制完成？才能调用`setupFold`方法，通过 `getComponentRect` 来知道文本多大。
如果是根据 `text` 组件的 appear事件，那界面上会有抖动，用户体验很差。
不知道我表达清楚没。

**Comment by Hanks10100** [comment]
在更新值之后就会触发 UI 更新，直接在后边调用 `setupFold` 就可以。（另外 content 不是个属性么，怎么当函数调了…）

```js
ready: function() {
  var self = this
  asyncGetData(function(ret){
    self.content = ret;
    self.setupFold();
 })
```

**Comment by Neeeo** [comment]
写错了。已改
