### ISSUE TITLE
weex跑程序时中文出现乱码，怎么做好？

### ISSUE THREAD

**Issue by MARCUSW10** [alibaba/weex#1585]

**Comment by Jinjiang** [comment]
可以提供一下你的操作系统信息、Node 版本、文件编码格式吗？文件编码格式最好是 utf-8 的

**Comment by MARCUSW10** [comment]
操作系统是windows8.1
node版本是v.6.9.1
文件编码格式有ANSI  UTF-8 UNICODE

还有就是我刚刚在script里加入 charset="UTF-8"，结果中文没有乱码了......

**Comment by MARCUSW10** [comment]
求高手帮我解决一下#1586

**Comment by Hanks10100** [comment]
可能你的文件格式不是 UTF-8 的，检查下编辑器的配置，改成 UTF-8 就能正常显示了。

**Comment by MARCUSW10** [comment]
是的，谢谢
看一下#1586，求帮助！！急急急！！！
