### ISSUE TITLE
IOS的SDK中WXImageComponent组件不能正常读取placeholder属性

### ISSUE THREAD

**Issue by zzyhappyzzy** [alibaba/weex#1587]
img的placeholder属性不应采用驼峰式命名，而WXImageComponent读取的却是placeHolder，导致无法设置placeholder

**Comment by acton393** [comment]
@zzyhappyzzy   设置的时候 是 用 的place-holder 这个属性，  transform会自动转换成驼峰 placeHolder， 建议你在pr对placeholder 这个属性做一下兼容

**Comment by zzyhappyzzy** [comment]
@acton393 嗯，<img place-holder ="xxxx">确实会被转为placeHolder
我自己写成了<img placeholder ="xxxx">才导致转换后无法识别
谢谢！
