### ISSUE TITLE
centos7服务器下 weex 移动web项目部署问题

### ISSUE THREAD

**Issue by 1459416736** [alibaba/weex#1588]
我们公司只是部署一个测试版本在服务器上，请问centos7服务器下 weex 移动web项目怎么部署，还是通过npm run serve 进行项目的启动么

**Comment by Jinjiang** [comment]
可以像部署任意 web 项目一样部署，Weex 在服务端提供的就是一个 JS 文件资源，npm run serve 背后其实就是一个 Node Web Server。
