### ISSUE TITLE
hlist  list-demo-horizon.we . 这个demo是不是不能用的啊。

### ISSUE THREAD

**Issue by cooliean** [alibaba/weex#1591]
我试了一下，不能工作呢，看不到要的效果

**Comment by Eric-ss** [comment]
例子没问题，能横滑啊
![0w92vzxqb1 s6oz5okqdlga](https://cloud.githubusercontent.com/assets/22341907/20084269/282c80a6-a59c-11e6-9b8b-e5959484aee0.png)

**Comment by Jam1zhu** [comment]
能横滑，安卓机上要设置内层容器的宽度

**Comment by sospartan** [comment]
@cooliean hlist功能没有开发完成，这个demo并没有对外公布，没有加到索引页面，所以这个issue先关闭了
