### ISSUE TITLE
weex ios transform rotate 内容变形

### ISSUE THREAD

**Issue by fattydevelop** [alibaba/weex#1596]
- 描述：使用`transform:rotate(30deg)`,在初始化style的时候，两端表现一致。当通过手势重新设置transform:rotate(90deg)的时候，IOS会发生内容变形的情况，android的表现没有问题。见下图：

- **android**

<img src="https://img.alicdn.com/tps/TB1akWDOXXXXXbNapXXXXXXXXXX-1080-1920.png" alt="android" width="200px"/>

- **IOS**

<img src="https://img.alicdn.com/tps/TB1gDPXOXXXXXcxXXXXXXXXXXXX-720-1280.jpg" alt="ios"  width="200px"/>

**Comment by alext1981** [comment]
@fattydevelop   你能贴一下能够复现问题的代码吗？

**Comment by namedlock** [comment]
你好，信息越多越能帮助我们定位问题。麻烦提供一下你相关的信息，包括或者不限于以下内容，如：

* 能够复现此问题的代码
* 复现此问题的步骤
* 使用的weex的版本
* iOS的版本
* 模拟器上出现的问题还是真机上产生的问题
* 其他信息

**Comment by cxfeng1** [comment]
@fattydevelop  #1830 应该可以修复你的问题
