### ISSUE TITLE
能提供coffeescript支持嗎？

### ISSUE THREAD

**Issue by red010182** [alibaba/weex#1598]
weex新手，請多包涵
我看到vue.js[官方文件](https://github.com/vuejs/vue-loader/blob/123f4e2089cd91f7ed6b06f7875b05547d5c7e55/docs/en/configurations/pre-processors.md)有提供coffeescript支持

不知道基於vuejs之上的weex是否也能提供？

我按vuejs的教學去做，似乎不可行

請問有什麼辦法嗎？

謝謝

**Comment by Jinjiang** [comment]
可以在 weex-loader 的基础上自行配制，另外相比 coffeescript，我们更推荐使用 ES6 语法
weex-loader: https://github.com/weexteam/weex-loader
谢谢
