### ISSUE TITLE
Native在通过程序修改相关属性时，也触发对应的事件，h5不会

### ISSUE THREAD

**Issue by sospartan** [alibaba/weex#1599]
有一个被忽略的平台差异，就是h5上的事件都是由UI交互触发，但native只要是属性被修改，不管是来自UI交互还是程序的修改，都会触发事件。以input为例：   
```html
<template>
<div>
  <input value={{value}} oninput="oninput"></input> 
  <text onclick="clicktext">click</text>
</div>
</template>
<script>
module.exports = {
  data:{"value":""},
  methods:{
    oninput:function(e){
      
      this.value = e.value;
      console.log("input",e.value)
    },
    clicktext:function(){
      this.value = "some thing new "
   }
  }
}
</script>
```
点击文本对`value`进行修改，在native会触发oninput，在h5上不会。并且我了解到前端开发者对这一状况都已经比较接受。
所以，如果真有这样的差异，需要明确定义一下。 @Jinjiang 
随后我会整理哪些native控件的实现需要求改，来与h5进行统一。

**Comment by MrRaindrop** [comment]
建议 native 端按照 web 标准修改一下。感觉这个问题没有普遍性，也就表单事件 `input` 和 `change` 有这个问题，标准里貌似也没说明不能通过程序修改值来触发，但是各浏览器的实现都是这样的，算是事实标准吧。另一方面两种方式都触发可能导致数据更新上的混乱，需要做额外的工作来避免，这就搞复杂了。

**Comment by Jinjiang** [comment]
> 标准里貌似也没说明不能通过程序修改值来触发

https://www.w3.org/TR/html5/forms.html#event-input-input
这里的事件代表的是用户交互引起的变化，是通过事件模型对用户行为的一种抽象和反应
程序修改数据和用户交互是有严格区分的

**Comment by Jinjiang** [comment]
我们现在整体上更多的是基于 web 的标准在设计接口和开发体验，所以文档里说明这个事情的必要性其实不大……
如果未来社区有比较大量的咨询和服务，我们也可以在文档里更多体现一下
如果没有更多疑问这个 issue 我先关掉了：）
