### ISSUE TITLE
Weex 的   Hot-Reload 貌似无效？

### ISSUE THREAD

**Issue by noman798** [alibaba/weex#160]
文档上说

『after changes saved the Weex playground App will immediately display these changes. this called Hot-Reload』

但是

我用最新版的 weex playground 和 weex，然后修改了代码，貌似没有自动刷新。

我需要 ctrl+c 杀掉 mac 上weex 进程，然后手工重启，然后 playground 手工刷新，才能看到改动

很麻烦

**Comment by macoscoder** [comment]
有时候可以auto reload，有时候又不行，是怎么回事？
