### ISSUE TITLE
weex 使用本地图片时应该怎么写路径，图片应该放在哪个位置好

### ISSUE THREAD

**Issue by MARCUSW10** [alibaba/weex#1601]

**Comment by zzyhappyzzy** [comment]
个人感觉有两种思路：
1、图片转为base64字符串，赋值给`<img>`的`src`
2、实现WXImgLoaderProtocol协议(IOS端为例，安卓类似)
```
(id<WXImageOperationProtocol>)downloadImageWithURL:(NSString *)url imageFrame:(CGRect)imageFrame userInfo:(NSDictionary *)userInfo completed:(void(^)(UIImage *image,  NSError *error, BOOL finished))completedBlock
```
约定`<img>`中src的本地图片表现形式（eg：file://xxx）,当url的值符合自己约定的本地图片方式时(eg：以file://开头)，读取本地图片后completedBlock回传img即可

**Comment by MARCUSW10** [comment]
我发现playground里面的image-demo.js例子里的Base64是没有图片的，这个怎么破解？
而且我自己写的时候发现图片装换成Base64也是显示不了图片。
对于你说的第二种思路，我觉得有点难理解，所以希望用第一种思路，可是好像不行啊，求高手帮助！！

**Comment by HJ-StevenSun** [comment]
第二种思路  在他的SDK 中改增加一个队URL 的判断 官方的只支持网络路径的图片，第一种 使用base64应该是 可以的，你在检查试试。

**Comment by MARCUSW10** [comment]
第一种使用Base64在浏览器跑是可以的，但是用playground扫二维码跑程序时Base64没出现图片啊，求救！！！

**Comment by HJ-StevenSun** [comment]
你加我QQ吧335297434

发自我的 iPhone

**Comment by Jinjiang** [comment]
HTML5 版本是因为浏览器天生支持的，所以各端表现现在并不一致
#74 这里是 data url 的讨论 (并且汇总到了 #1494 )
为了让 issues 更聚焦，建议大家在 #74 继续讨论，这里我先关掉了
谢谢理解
