### ISSUE TITLE
全局通知监听

### ISSUE THREAD

**Issue by Mryong** [alibaba/weex#1605]
在iOS中看到WXGlobalEventModule,但是这个module只能监听当前页面的通知,并不能监听全局的通知.比如有三个页面,两个是Weex实现,一个是Native实现,现在在Native页面发生一个通知,但是希望所有的Weex的界面都能监听.是不是要自定义module,还是有现成的module.

**Comment by Hanks10100** [comment]
关于 weex 页面间的通信，我们讨论了一些方案在 #1536 ，简而言之是打算实现 [`BroadcastChannel`](https://html.spec.whatwg.org/multipage/comms.html#broadcasting-to-other-browsing-contexts) API 。

**Comment by Hanks10100** [comment]
这个 issue 先关掉了，请关注 #1536 的进度。
