### ISSUE TITLE
请问如何创建 websocket 连接？（我需要做一些聊天的应用）

### ISSUE THREAD

**Issue by noman798** [alibaba/weex#161]
请问如何创建 websocket 连接？

如题。
另外，写小游戏也会经常需要websocket。

**Comment by Jinjiang** [comment]
https://gitter.im/weexteam/cn 更多讨论欢迎移步至中文聊天室
这个问题没有后续讨论了，这里做关闭处理
谢谢

**Comment by Micjoyce** [comment]
对于websocket支持有什么新的进展吗？

**Comment by kfeagle** [comment]
#https://github.com/alibaba/weex/pull/2080 @Micjoyce 已经实现了
