### ISSUE TITLE
iOS经常会时不时的 异常奔溃抛这个异常WXUtility.m:319, Unknown fontFamily:'Open Sans', sans-serif

### ISSUE THREAD

**Issue by liujianying** [alibaba/weex#1611]
#iOS. 经常会时不时的 异常奔溃抛这个异常
```
WXUtility.m:319, Unknown fontFamily:'Open Sans', sans-serif
```
##代码在android 和h5上正常, 在ios 上经常奔溃

![0061dc63-9103-460c-9f42-d4220d43892d](https://cloud.githubusercontent.com/assets/6265414/20163199/8532f61e-a735-11e6-9356-cb39d5b65068.png)

**Comment by acton393** [comment]
@liujianying  这个crash的case有木有，麻烦提供给我一个~~

**Comment by liujianying** [comment]
@acton393   能加下我qq把925279861   我传给你,由于涉及很多页面逻辑,这上面不好上传给你

**Comment by george-luofz** [comment]
@liujianying  这个问题有方案了吗？我这边跟你的问题一样

**Comment by cxfeng1** [comment]
Log里的警告不会导致crash， 看上去是定义了同名的C函数或是其他命名冲突了？

**Comment by liujianying** [comment]
@cxfeng1 代码片段已经发给 acton393  目测跟c函数冲突的可能性不大
@george-luofz  修改下实现方式目前不会出现类似情况,具体原因还不清楚

**Comment by cxfeng1** [comment]
@liujianying 能分享一下是如何修改实现绕过的么

**Comment by Jinjiang** [comment]
由于长时间没有讨论，该 issue 做关闭处理
不过还是希望 @liujianying 愿意的话可以分享一下自己的实现心得：）
