### ISSUE TITLE
border绘制三角形失败

### ISSUE THREAD

**Issue by WangXiZhu** [alibaba/weex#1613]
如下：
border-top-width: 12;
border-right: 0;
border-bottom-width: 12;
border-left-width: 20;
border-top-color: transparent;
border-right-color: transparent;
border-bottom-color: transparent;
border-left-color: #ffffff;

在web中ok,但是在原生中显示的还是矩形

**Comment by yuanzx** [comment]
同样遇到这种问题

**Comment by WangXiZhu** [comment]
几天前在gitter.im上 勾股说看  然后就没有然后了。。。现在只有用图片代替吧。  但 color:transparent是OK的，这就很坑了

**Comment by Jinjiang** [comment]
@cxfeng1 几天前跟你留言问过的那个问题……

**Comment by cxfeng1** [comment]
@WangXiZhu 麻烦给一下完整的demo， 目前border这一块考虑到性能和复杂度， 并没有完全实现 Web 的标准

**Comment by Jinjiang** [comment]
```html
<template>
  <div>
    <div class="triangle"></div>
  </div>
</template>

<style>
  .triangle {
    border-top-width: 10;
    border-right: 0;
    border-bottom-width: 10;
    border-left-width: 20;
    border-top-color: transparent;
    border-right-color: transparent;
    border-bottom-color: transparent;
    border-left-color: #000000;
  }
</style>
```

**Comment by cxfeng1** [comment]
这个属于W3C border标准中的"Corner Shaping"， iOS和Android确实都还没实现(主要考虑到实现的成本和性能影响)，可以考虑先用图片代替。

**Comment by Jinjiang** [comment]
如果短期没有好的解决办法，这个问题我先汇总到 #1494 吧
谢谢
