### ISSUE TITLE
将图片转换成Base64字符串来上传图片，可是我发现playground里面的image-demo.js例子里的Base64并没有显示图片，但是我用浏览器跑image-demo时，Base64出现图片，求解

### ISSUE THREAD

**Issue by MARCUSW10** [alibaba/weex#1614]
demo将图片转为base64字符串是显示不了图片的，这个怎么破解？ 而且我自己写的时候发现图片装换成Base64也是显示不了图片。 至于上传图片通过实现WXImgLoaderProtocol协议思路，我觉得有点难理解，所以希望用base64字符串的思路，可是好像不行啊，求帮助！！急急急！！！

**Comment by Jinjiang** [comment]
HTML5 版本是因为浏览器天生支持的，所以各端表现现在并不一致
#74 这里是 data url 的讨论 (并且汇总到了 #1494 )
为了让 issues 更聚焦，建议大家在 #74 继续讨论，这里我先关掉了
谢谢理解
