### ISSUE TITLE
android globalEvent 问题

### ISSUE THREAD

**Issue by YanyeZhang** [alibaba/weex#1619]
```javacript
var globalEvent = require('@weex-module/globalEvent');
```
看到其实现方法被Deprecated，是打算用jscallback来取代么

**Comment by Hanks10100** [comment]
全局事件将要废弃，在 #1536 里讨论了相关解决方案，简而言之是打算实现 [`BroadcastChannel`](https://html.spec.whatwg.org/multipage/comms.html#broadcasting-to-other-browsing-contexts) API 。

**Comment by YanyeZhang** [comment]
大致在什么时候上这个功能呢

**Comment by Hanks10100** [comment]
@YanyeZhang 还在讨论，还没有确定的时间。

**Comment by Hanks10100** [comment]
这个 issue 先关掉了，请关注 #1536 的进度。
