### ISSUE TITLE
支持font-family吗（文档上没写）？如何使用自定义字体（尤其是图标字体）？

### ISSUE THREAD

**Issue by noman798** [alibaba/weex#162]
最好可以支持远程的字体
我比较喜欢用阿里的 http://iconfont.cn/ 来实现用字体当图标用

比如
@font-face {
  font-family: 'ico';
  src: url('//at.alicdn.com/t/font_1462340970_857406.eot'); /\* IE9_/
  src: url('//at.alicdn.com/t/font_1462340970_857406.eot?#iefix') format('embedded-opentype'), /_ IE6-IE8 _/
  url('//at.alicdn.com/t/font_1462340970_857406.woff') format('woff'), /_ chrome、firefox _/
  url('//at.alicdn.com/t/font_1462340970_857406.ttf') format('truetype'), /_ chrome、firefox、opera、Safari, Android, iOS 4.2+_/
  url('//at.alicdn.com/t/font_1462340970_857406.svg#ico') format('svg'); /_ iOS 4.1- */
}

**Comment by spiritelf** [comment]
<template>
  <div>
   
    <text class="title2">http ttf: &#xe606;&#xe605;&#xe604;&#xe603;&#xe602;&#xe601;&#xe600;</text>
    <text class="title3">http woff: &#xe606;&#xe605;&#xe604;&#xe603;&#xe602;&#xe601;&#xe600;</text>
  </div>

</template>
<style>
 

  .title2 {
    color: red;
    font-size: 36;
    font-family: iconfont2;
  }

  .title3 {
    color: red;
    font-size: 36;
    font-family: iconfont3;
  }


</style>

<script>   
  module.exports = {
    created: function() {
      var domModule = require('@weex-module/dom');     
      domModule.addRule('fontFace', {
        'fontFamily': "iconfont2",
        'src': 'url("http://at.alicdn.com/t/font_1469606063_76593.ttf")'
      });
      domModule.addRule('fontFace', {
        'fontFamily': "iconfont3",
        'src': 'url("http://at.alicdn.com/t/font_1469606522_9417143.woff")'
      });
      
    }
  }
</script>


显示不了图标？

**Comment by YorkShen** [comment]
playground中有iconfont的[demo](https://github.com/alibaba/weex/blob/dev/examples/iconfont.we)，请看playground。 @spiritelf

**Comment by spiritelf** [comment]
@YorkShen  我用的就是那个demo

**Comment by YorkShen** [comment]
@spiritelf 复现步骤（推荐有截图）、设备型号、OS 版本、App 版本（playground 版本或自己的 app）。

**Comment by spiritelf** [comment]
weex-pack生成项目，只是把weex里的iconfont.we demo拷进去测试。没效果 （Android4.4手机） @YorkShen

**Comment by YorkShen** [comment]
@spiritelf 问题粘贴到 https://github.com/alibaba/weex/issues/825 中，在该issue中统一讨论。
