### ISSUE TITLE
slider组件嵌套list问题

### ISSUE THREAD

**Issue by yuanzx** [alibaba/weex#1620]
android weex版本0.6.2 , playgournd版本0.8.04
slider下面放一个text和一个list， h5预览可以，使用playground 扫码会直接闪退，单独把list移出来和slider平级，把slider和list用div包起来，扫码就可以成功预览，是否是slider里不能放list？

**Comment by Hanks10100** [comment]
帮你加个代码：

```html
<template>
  <slider>
    <list>
      <cell><text>list cell</text></cell>
    </list>
  </slider>
</template>
```
实测 iOS 和 H5 都能正常显示，旧版本 Android 没有内容。

**Comment by xkli** [comment]
已知问题，是因为懒加载状态不统一导致。新版已经修复，待发布。
