### ISSUE TITLE
在自定义组件上无法调用 inline handler

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#1624]
下面这样形式的调用无法触发，ar-button是在另一个we文件里定义的。
```html
<ar-button style="margin-right: 20;" value="下载" onclick="tap($index, $event)"></ar-button>
```
只能触发这样的形式：
```html
<ar-button style="margin-right: 20;" value="下载" onclick="tap"></ar-button>
```

**Comment by MrRaindrop** [comment]
Hi, 你看下在你的环境里以下代码是否正常运行:

```html
<template>
  <div>
    <text onclick="test('MSG!!!', $event)">TEST</text>
  </div>
</template>

<script>
  var modal = require('@weex-module/modal')
  module.exports = {
    methods: {
      test: function (msg, evt) {
        modal.toast({
          message: 'msg:' + msg     // msg:MSG!!!
        })
      }
    }
  }
</script>
```

这段代码在最新 dev 分支下应该是正常运行的，而且这个写法在比较早期就已经支持了。如果不行，可以把你的运行环境，包括运行设备，操作系统，weex 版本号等信息提供一下。

**Comment by Neeeo** [comment]
在系统自带组件上没问题，我说的是在自定义子组件上（we文件定义的，不是native提供的）。

**Comment by MrRaindrop** [comment]
确实有问题，这里补充一下出错用例：

```html
<element name="foo">
  <template>
    <div><text>TEST</text></div>
  </template>
</element>

<template>
  <div>
    <foo onclick="test('MSG!!!', $event)"></foo>
  </div>
</template>

<script>
  var modal = require('@weex-module/modal')
  module.exports = {
    methods: {
      test: function (msg, evt) {
        modal.toast({
          message: 'msg:' + msg     // msg:MSG!!!
        })
      }
    }
  }
</script>
```

**Comment by Jinjiang** [comment]
和 #1502 问题重复了，我们继续保留这边跟进

**Comment by Hanks10100** [comment]
我本地测试了一下，下边这个例子是可以正常工作的：
```
<template>
  <div>
  <div repeat="{{v in viewData}}" onclick="clicked($index)">
    <text>{{v}}</text>
  </div>
  </div>
</template>

<script>
  module.exports = {
    data: {
      viewData: ['a', 'b', 'c']
    },
    methods: {
      clicked: function(position) {
        console.log("被点到了:" + position)
      },
    }
  }
</script>
```

线上网站  http://dotwe.org/  中的 js framework 和 weex-html5 版本都较低，最近会升级。

**Comment by Neeeo** [comment]
请看清问题再说，问题说的是在一个自定义组件上有问题，下面也有人回复测试用例。你发的这完全不是一件事

**Comment by Hanks10100** [comment]
Sorry, 是我理解错了，之前遇到过同类问题是由于线上版本太低导致的。@fkysly 看一下具体怎么回事。

**Comment by luoyang125024608** [comment]
`<template>
    <div class="wrapper">
        <wxbutton class="button" title="jump" @click="jump" ></wxbutton>
        <text class="button" @click="jump">Jump</text>
    </div>
</template>`

自定义components上的@click没有响应哦 在ios代码里没有addTarget监听，@click还是不起作用

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
