### ISSUE TITLE
在自定义组件上无法设置额外的属性

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#1625]
在 div这类默认组件上可以添加额外的属性，以便之后访问：
```
<div custom="hello"></div>
```
但在自定义组件上（另外的we文件），添加的额外属性，在之后无法在事件里通过 `e.target.attr.custom` 获取到。

**Comment by Jinjiang** [comment]
`e.target` 一定是真实的 native element，自定义组件的 attribute 只是用来从父组件向子组件传递数据用的，如果你希望可以在子组件的脚本中访问到这个 `custom` “特性”，可以试试 `this.custom`
谢谢

**Comment by Neeeo** [comment]
我是想在父组件上访问这个 `custom` 自定义 “特性”，主要需求是记录 index 这类信息，方便之后事件响应的时候找到对应的数据

**Comment by Jinjiang** [comment]
把你想要记录的东西放在子组件的 data 里即可，一样可以在事件响应的时候通过访问 this.custom 找到
