### ISSUE TITLE
overflow和radius兼容性问题

### ISSUE THREAD

**Issue by goldenlandfool** [alibaba/weex#1629]
在ios和android上验证发现如下两个兼容性问题。不知道现在解决了没，或者有没有解决的计划
1.  overflow: hidden;在android的div中不起作用
2.  image控件ios版本border-top-left-radius的作用和border-radius一样，border-top-right-radius、border-bottom-left-radius和border-bottom-right-radius不起作用，在android下起作用，这四个样式在text下也能两端一致

**Comment by YorkShen** [comment]
@goldenlandfool 
## iOS
* 目前不支持border-x-y-radius，只支持border-radius
## Android
* 对于image组件，可以认为其存在`background-clip:border-box`, `overflow:hidden`两个属性，border-radius会影响canvas的clip，canvas可以clip到圆角矩形区域或矩形区域。
* 对于非image组件，只有`overflow:hidden`，border-radius不会影响canvas的clip，canvas只能clip到矩形区域。
* android上述实现是基于性能和最常见的user-case两个角度考虑，暂时不会修改实现。
