### ISSUE TITLE
list的bug

### ISSUE THREAD

**Issue by zhangdefu3** [alibaba/weex#1630]
**bug: list的bug.** 
描述：我把list放在上面(flex:6)，把提示文本放在下面(flex:1)。页面刚加载时，onappear的cell数，比展示出来的多。

源代码如下：

><template>
    <div style="flex:1;">
        <list class="main">
            <cell repeat="{{rows}}" index="{{$index}}" onappear="onappear" ondisappear="ondisappear">
                <div class="cell-in">
                    <text class="cell-text">row - {{id}}</text>
                </div>
            </cell>
        </list>
        <div class="footer">
            <text class="count">{{minAppearId}} ---- {{maxAppearId}}</text>
        </div>
    </div>
</template>

><style>
    .main{
        flex:7;
    }
    .footer{
        flex:1;
        background-color: yellow;
    }
    .count{
        font-size:24px;
        margin:20px;
        text-align: center;
    }
    .cell-in{
        border-bottom-width:2px;
        border-bottom-color: silver;
    }
    .cell-text{
        font-size:40px;
        padding:16px;
    }
</style>

><script>
    var debugMode = true;
    module.exports = {
        data:{
            appearIds:[],
            minAppearId:1,
            maxAppearId:1,
            rows:[
                {id:1},
                {id:2},
                {id:3},
                {id:4},
                {id:5},
                {id:6},
                {id:7},
                {id:8},
                {id:9},
                {id:10},
                {id:11},
                {id:12},
                {id:13},
                {id:14},
                {id:15},
                {id:16},
                {id:17},
                {id:18},
                {id:19},
                {id:20}
            ]
        },
        computed:{

        },
        methods:{
            refreshAppearData:function(){
                this.appearIds.sort(function(a, b){
                    return a - b;
                });
                this.minAppearId = this.appearIds[0];
                this.maxAppearId = this.appearIds[this.appearIds.length - 1];
            },
            onappear:function(e){
                var appearId = this.rows[e.target.attr.index].id;
                if(debugMode){
                    console.log("+++++++++++++项目：" + appearId);
                }
                var index1 = this.appearIds.indexOf(appearId);
                if(index1 < 0){
                    this.appearIds.push(appearId);
                    this.refreshAppearData();
                }
            },
            ondisappear:function(e){
                var disappearId = this.rows[e.target.attr.index].id;
                if(debugMode){
                    console.log("------------项目：" + disappearId);
                }
                var index1 = this.appearIds.indexOf(disappearId);
                if(index1 > -1){
                    this.appearIds.splice(index1, 1);
                    this.refreshAppearData();
                }
            }

        },
        created:function(){

        }
    }
</script>

**Comment by Hanks10100** [comment]
在含 `repeat` 的标签里边绑定的事件，如果想取下标值，可以用 `this.$index` 不要用 `e.target.attr.index`。

```js
onappear: function (e) {
    var appearId = this.rows[this.$index].id;
}
```

因为在 HTML 标准中，attribute 和 property 是不一样的，参考 [Properties and Attributes in HTML](http://stackoverflow.com/questions/6003819/properties-and-attributes-in-html)。attribute 就是 DOM 上的初始值，更新 DOM 才能更新 attribute，更新数据时 attribute 不变。`attr` 属性中的值不一定是最新的。

 > 另外提示一点： `repeat="rows"` 这种写法我们已经废弃了，建议使用 `repeat="row in rows"` 这种方式。

**Comment by yuanzx** [comment]
@Hanks10100 另外提示一点： repeat="rows" 这种写法我们已经废弃了，建议使用 repeat="row in rows" 这种方式。

为何要废弃这种写法，两种写法都支持不更好么？

**Comment by Hanks10100** [comment]
@yuanzx 这种写法在性能优化和数据更新完备性上存在比较大的局限性，而且作用域也容易存在歧义。

考虑如下情况：

```
<template>
  <div>
    <text>{{title}}</text>
    <div>
      <text repeat="lists" onclick="handleClick">{{title}}</text>
    </div>
  </div>
</template>

<script>
  module.exports = {
    data: {
      title: 'Banner',
      lists: [
        { title: 'A' },
        { title: 'B' },
        { title: 'C' }
      ]
    },
    methods: {
      handleClick: function () {
        this.title = 'X'
      }
    }
  }
</script>
```

其中 `this.title` 修改的值是数组里的还是数组外的？

此外，使用 `repeat="row in rows"` 这种写法便于以后切换成 Vue 2.0 的 `v-for`，Vue 2.0 里也没有了 `v-repeat` 这种指令了。

**Comment by WangXiZhu** [comment]
为什么我获取 $index为 undefined

`<div class="tabbar"  onclick="switchPage($index)" repeat="{{item in tabItems}}">
</div>


data: {
  tabItems: [{},{},{}]
},
methods: {
  switchPage: function(index){     
      console.info(index);  //undefined
    }
}
`

**Comment by Hanks10100** [comment]
@WangXiZhu 我测了是有的，帮你把代码补全：

```html
<template>
  <div>
    <div class="tabbar"  onclick="switchPage($index)" repeat="{{item in tabItems}}">
      <text>{{$index}}</text>
    </div>
  </div>
</template>
<script>
  module.exports = {
    data: {
      tabItems: [{},{},{}]
    },
    methods: {
      switchPage: function(index){     
        console.info(index);
      }
    }
  }
</script>
```

**Comment by WangXiZhu** [comment]
谢谢你的回答。
我的代码也是这么写的。然后很奇怪，我把你的代码复制到我本地打印的结果也是undefined，
我不知道什么原因，不知道和我的环境有没有关系，也是最近才开始用weex,
版本上应该没什么问题的。。 

![weex-bug](https://cloud.githubusercontent.com/assets/8960318/20307511/c17bccc4-ab7a-11e6-9a5c-e2c538c33ca4.png)

**Comment by WangXiZhu** [comment]
sorry,就是weex-toolit版本的问题，之前版本是0.6.2，现在回退到 0.5.8就可以了。
这个确实有点烦，还有小伙伴谈到，node_module有时候没有成功安装，导致解析出问题。

**Comment by Hanks10100** [comment]
@WangXiZhu 👌 工具我们也会不断完善，如果发现问题了可以在 [weex-toolkit](https://github.com/weexteam/weex-toolkit) 这里提 issue。
