### ISSUE TITLE
iOS中如何实现一个cell两个同样的view的效果

### ISSUE THREAD

**Issue by allentofight** [alibaba/weex#1631]
如图，要实现以下效果
![collectionView](https://i.imgsafe.org/6c73bacf56.png)

`<cell repeat="{{item in lists}}" index="{{$index}}" onclick="oncellclick" append="tree">`

一个item只能对应一个cell，而在上图中是两个item对应一个cell,如果有collectionView实现的就好办了，
但现在只有tableView实现的 list，何解

**Comment by allentofight** [comment]
WXListComponent的底层我建议使用UICollectionView而非UITableView来实现，这样可拓展性会更好

**Comment by allentofight** [comment]
@huacnlee

**Comment by Jinjiang** [comment]
目前我们确实有这方面的打算，我暂时把你的建议汇总到 #1494 并关掉了。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
谢谢
