### ISSUE TITLE
weex 怎么将一个we文件里的数据传到另一个we文件里

### ISSUE THREAD

**Issue by MARCUSW10** [alibaba/weex#1632]

**Comment by Jinjiang** [comment]
不存在数据从一个文件传到另外一个文件的说法
我猜测你可能想问组件之间如何传递数据，目前我们有 `$emit` `$on` `$off` 这样的方法可以使用，可以具体参考一些相关的文档和例子
Weex 页面直接的通信我们正在讨论 #1536
谢谢
