### ISSUE TITLE
sticky在andriod的效果不正常

### ISSUE THREAD

**Issue by jiuyuegui** [alibaba/weex#1634]
sticky在andriod上向上滑动的时候，能看到sticky区域是"复制了一份节点"让其sticky，具体显示如下：
<img style="width: 460px; height: 702px" src="https://cloud.githubusercontent.com/assets/7759642/20259081/fb667da0-aa8d-11e6-8460-f29ecda96faa.png" />
代码如下
<pre>
<style>
	.common {
		flex-direction: row;	
		align-items: center;
		justify-content: center;	
		height: 100;
		width: 750;
		position: sticky; 
		margin-top: 80;
		margin-bottom: 80;
		opacity: 0.6;
	}
	.common-txt {
		background-color: #999999;
		opacity: 0.6;
	}
	.txt {
		font-size: 28;
		margin-top: 20;
		margin-bottom: 20;
	}
	.content {
		height: 1600;
		width: 750;
		background-color: #999999;
	}
</style>
<template>
	<scroller style="position: relative">
		<div class="common">
			<text class="common-txt">header ----- sticky</text>
		</div>
		<div class="content">
			<text>test</text>
		</div>
	</scroller>
</template>
</pre>
<a href="http://weex.alibaba-inc.com/playground/6a32d11056bae922ace5e14e22fb26d7">测试二维码</a>
<img style="width: 50px; height: 50px" src="https://cloud.githubusercontent.com/assets/7759642/20258055/a0f99d34-aa88-11e6-86ba-52286e100151.png" />

**Comment by Hanks10100** [comment]
提醒下，不要在 github 放关于手淘的东西，也不要放二维码。
