### ISSUE TITLE
Android原生Tab界面嵌套的页面切换为为Weex界面，当包含list组件显示时，list最下面数据被遮挡，怎么处理这种兼容问题？

### ISSUE THREAD

**Issue by samyzhang** [alibaba/weex#1639]
1:可否直接等list显示完后在动态更新list?
2:也是直接在native拿到weex组件的id,再次更新，有没有这样的api?
![image](https://cloud.githubusercontent.com/assets/10821317/20291076/06d7a89e-ab1f-11e6-8ab2-7f44ad86547c.png)

**Comment by xkli** [comment]
这个应该是weex render的时候传入的宽高不对，你可以用WXSDKInstance.setSize()重新设置宽高

**Comment by vczero** [comment]
@xkli 正解。render之后，WXSDKInstance.setSize()重新设置宽高即可。

**Comment by vczero** [comment]
@samyzhang 后续的版本【研发中】会增强这块，可以做到自适应。

**Comment by samyzhang** [comment]
恩，用Weex做Tab 当包含list组件是没有问题的；

**Comment by sospartan** [comment]
android的后续新版会自适应容器尺寸，可以在android分支上体验，这个issue先关了

**Comment by yuxingfafu** [comment]
请问这个问题，在最新版本的里面是否解决了呀？

**Comment by samyzhang** [comment]
用自带的TabBar，有点问题，建议你自己重新写个；
