### ISSUE TITLE
关于list控件的分组

### ISSUE THREAD

**Issue by WHChaw** [alibaba/weex#1642]
目前list中只支持header，cell，refresh等，后续有没有可能支持类似section或者group这种群组概念的标签，section和group中可以包含cell和header等标签

**Comment by Hanks10100** [comment]
嗯，好建议，可以讨论下这个需求。

如果添加了 `<section>` 或者 `<group>` 这种标签，实际上在渲染时是否和 `<div>` 或者 `<cell>` 是一样的，不一样的话会增加 `<list>` 标签的复杂度；仅仅是别名的话，可以视为语义化的标签扩展，是否支持在任意位置写这些标签。

另外，增加分组会导致多了一层标签嵌套，这很影响 Native 上的渲染性能，是否可以考虑仅在逻辑上分组。

**Comment by WHChaw** [comment]
而且现在0.8的iOS SDK存在一个问题，就是refresh和loader同时写的话，会导致loader无法显示，我看了下，是sdk中lits加载subcomponent的逻辑处理上有点问题

**Comment by acton393** [comment]
@WHChaw  可以给一下你的同时使用无法显示的case，我这边看一下

**Comment by WangXiZhu** [comment]
我有点不明白header的使用， 文档中这样写道
> header 0.6.1 header which will stick to the top when it reaches the top of the screen.

这里的 0.6.1是指 weex-toolkit的版本吗？（PS:目前weex-toolkit已经是0.6.1），其中 weex npm版本也才0.4好像，所以我猜测是指 weex-toolkit的版本 。

这里的demo是 

```
<template>
  <list>
    <header><text>我是标题</text></header>
    <cell class="tabbar" repeat="{{item in tabItems}}">
      <text>{{$index}}</text>
    </cell>
  </list>
</template>
<script>
  module.exports = {
    data: {
      tabItems: [{},{},{},{},{},{},{},{},{},{}]
    }
  }
</script>
<style media="screen">
    .tabbar{
        height: 200;
    }
</style>

```

然后拖动的时候还出现  scroller.js的 bug

>  scroll.js:180 Unable to preventDefault inside passive event listener due to target being treated as passive

请问我应该如何使用header? 谢谢

**Comment by fromIRIS** [comment]
@WangXiZhu 我这边出现的提示是
![image](https://cloud.githubusercontent.com/assets/8492963/20552631/dbacb26c-b187-11e6-8729-b6ddebb5de9f.png)

**Comment by WangXiZhu** [comment]
是的，所以文档有错。在源码中  https://github.com/alibaba/weex/blob/dev/html5/render/browser/extend/components/scrollable/list/list.js   支持的类型只有3中

```
'use strict'

import scrollableModule from '../scrollable'

const availableChildrenTypes = ['cell', 'loading', 'refresh']
```

所以其他类型好像不可以吧，警告也是这里提示的，可以看一下源码。

不知道 header什么时候支持呢？

**Comment by Jinjiang** [comment]
文档中的 0.6.1 是主仓库的 tag，不是 toolkit 的版本号
标题中的提议我先整理汇总到 #1494 了
额外引申出来的问题建议再开一个 issue 分开讨论
谢谢理解

**Comment by MrRaindrop** [comment]
header 组件在 h5-render 里目前还没有实现，所以 h5-render 提示 invalid type. android/ios 端目前实现了这个组件，可以在对应客户端查看效果.
