### ISSUE TITLE
集成到Android时出现more than one library with package name com.taobao.weappplus_sdk，这个怎么破

### ISSUE THREAD

**Issue by MARCUSW10** [alibaba/weex#1646]

**Comment by zshshr** [comment]
能描述一下你是怎么集成的？最简单的方式，就是直接同步代码，用android studio 打开sdk中的 build.gradle文件, 你可以试试

**Comment by Jinjiang** [comment]
由于长时间没有得到反馈且缺乏细节描述，这个 issue 我关掉了
今后开 issue 请遵循模板的建议
谢谢
