### ISSUE TITLE
weex-html5 0.4.1 导致tabbar在浏览器不显示内容

### ISSUE THREAD

**Issue by findabox** [alibaba/weex#1648]
在使用weex-html5 的0.4.1版本后，tabbar在浏览器不显示内容，并且样式非常奇怪
替换回0.3.2一切正常，example里的tabbar例子也能重现

0.3.2显示tabbar页面内容
![html5-0 3 2](https://cloud.githubusercontent.com/assets/17056882/20333973/79c392fa-abf1-11e6-9802-1bed199e5356.PNG)

0.4.1不显示tabbar页面内容
![html5-0 4 1](https://cloud.githubusercontent.com/assets/17056882/20333993/99fdf6b4-abf1-11e6-8077-2e253d37ee00.PNG)

**Comment by esmeetu** [comment]
==> #1484 may be helpful.

**Comment by findabox** [comment]
设置高度后解决

**Comment by Jinjiang** [comment]
请确认一下最新的 dev 的版本 (0.5.0) 我这边是正常的
谢谢

**Comment by MrRaindrop** [comment]
@findabox 最新版本不设置高度也是可以的 (最新的 `html5-feature-0.5` 分支和 `dev` 分支)

**Comment by findabox** [comment]
html5-feature-0.5 分支下的examples\component\tabbar\tabbar-demo.we
的确能在不设置高度的情况下显示内容

**Comment by yaochenfeng** [comment]
dev分支的index.html?page=./examples/build/component/tabbar/tabbar-demo.js 在 网页不显示内容
