### ISSUE TITLE
集成到android,生成apk,安装在手机，发现图片全都显示不了，怎么破解

### ISSUE THREAD

**Issue by MARCUSW10** [alibaba/weex#1652]

**Comment by jixiangxiang** [comment]
确切的说是weex的android sdk更新到0.8.0.2，出现了所有图片都不显示的问题，0.7.0.1版本是没有问题的，希望有人能够帮忙解决一下

**Comment by jixiangxiang** [comment]
后来我仔细查看了一下WXImageView的代码，重写了setImageDrawable方法，导致调用setImageBitmap方法的时候不会再调用ImageView的setImageDrawable方法，所以不会重绘显示不图片，如果想让图片显示，直接用WXImageView的setImageDrawable来显示图片，而不要使用setImageBitmap来显示图片

**Comment by Jinjiang** [comment]
@xkli 有劳确认一下这里的细节吧

**Comment by YorkShen** [comment]
@jixiangxiang 请你们是否修改了图片库，
如果没有使用weex的默认图片库，需要确保
* 图片库实现不依赖Drawable.Callback
* 图片库在调用Image.setDrawable（Drawable a）的时候，a.getBitmap返回值不是null

**Comment by spiritelf** [comment]
怎么解决的？

**Comment by YorkShen** [comment]
@spiritelf 见讨论，自行更换图片库，需要自行适配图片库。

**Comment by spiritelf** [comment]
有没有例子可以参考？ @YorkShen

**Comment by YorkShen** [comment]
@spiritelf 参考对Piacasso图片库(即内置图片库)的封装

**Comment by spiritelf** [comment]
@YorkShen 在哪个项目里？

**Comment by spiritelf** [comment]
ImageAdapter？？

**Comment by YorkShen** [comment]
参考https://github.com/alibaba/weex/blob/dev/android/commons/src/main/java/com/alibaba/weex/commons/adapter/ImageAdapter.java 接入自己的图片库。 @spiritelf
