### ISSUE TITLE
按照教程完成了android 的集成和图片的扩展，但是只能显示网上的图片，如果将图片转为Base64,仍然无法显示，求助

### ISSUE THREAD

**Issue by MARCUSW10** [alibaba/weex#1653]

**Comment by Jinjiang** [comment]
@MARCUSW10 Hi 确认一下这个问题是不是和 #1614 重复了？之前的 issue 也是你提问的

**Comment by Jinjiang** [comment]
不介意的话我们把这个问题放在 #1652 一起讨论吧，这个 issue 我先关掉了
谢谢理解和支持：）

**Comment by zshshr** [comment]
playground 里的图片库不支持 base64 和gif 这个需要开发者在自己的app的里图片库里做实现
