### ISSUE TITLE
报wx_create_instance_error

### ISSUE THREAD

**Issue by yahooyee** [alibaba/weex#1659]
我现在没有用jack，还是报这个错误

**Comment by Hanks10100** [comment]
能否再详细描述下报错的场景？例如平台（Web、iOS、Android）、系统、Weex 版本、出错代码、报错信息等。

**Comment by Jinjiang** [comment]
由于长时间没有得到更细节的信息，这个 issue 我关掉了
今后开 issue 请遵循 issue 模板的格式，并尽量描述完整可复现的信息
谢谢理解
