### ISSUE TITLE
在项目中其他SDK使用arm64-v8a so库后，导致weex不能使用armeabi so 库

### ISSUE THREAD

**Issue by paranoiaaa** [alibaba/weex#1662]
我们在开发过程中遇到这样的问题，我们在引入其他三方sdk后，由于三方中使用了arm-v8a 的so 库，导致项目不能使用weex 提供的armeabi so 库，出现项目不兼容的情况，请问 weex 可以帮忙打一个arm-v8a的so 包吗？

**Comment by zshshr** [comment]
@wqd1994 你们的filter 是怎么写的？

**Comment by wqd1994** [comment]
我们现在在项目中使用了 “armeabi” 和 “arm64-v8a” @zshshr @Jinjiang

**Comment by zshshr** [comment]
@wqd1994 是so不兼容的问题，还是so找不到，目前sdk中针对非armeabi 的so，做了兼容加载的 armeabi的应该是可以支持arm64-v8a 的

**Comment by zshshr** [comment]
@wqd1994  armeabi可以 兼容arm64-v8a的，你把so加载失败的log 发出来看看

**Comment by wqd1994** [comment]
你们的armeabi的是可以支持arm64-v8a 的，但是在项目使用arm64-v8a后，项目不在使用armeabi so 库了，我们这边三方在更改兼容方式，你们如果能提供arm64-v8a的so 库就更好了　Ｏ（∩＿∩）Ｏ谢谢

**Comment by zshshr** [comment]
@wqd1994 你们用的sdk版本是多少，我们下个release版本计划加入arm64-v8a的so好了

**Comment by myeveryheart** [comment]
@zshshr 真的是跪求加入其他so包。我被这个困扰很久了。公司正在做技术预演，weex只有armeabi和x86让我泪崩了。因为很多其他第三方库不支持armeabi了，我没办法打armeabi的包。

**Comment by myeveryheart** [comment]
@zshshr 如果通过引入weex源码然后修改build，可以自己弄出其他so吗？

**Comment by smoothdvd** [comment]
这么久都没解决

**Comment by myeveryheart** [comment]
@smoothdvd 真要解决很简单。可能是阿里没遇到，就不积极吧。
