### ISSUE TITLE
Scroller/List的loadmoreretry由属性修改为方法，方法名字为resetloadmore

### ISSUE THREAD

**Issue by namedlock** [alibaba/weex#1664]
* 目前由一个属性来控制行为不合适，应由方法来控制
* loadmoreretry的行为是设置loadmore是否被触发，所以应把方法名字改为resetloadmore
* h5/iOS/Android三端行为应一致

**Comment by MrRaindrop** [comment]
补充一下背景：

当 `list` 组件滑动到 `loadmoreoffset` 的范围内的时候，触发 `loadmore` 事件。这时 `loadmore` 已经触发过一次了，所以后续再滚动的话，不会再触发该事件，这显然不科学。所以设计了这个 `resetloadmore` 方法，调用该方法可以开启该事件的触发机制，恢复 `loadmore` 的正常触发。一个使用 `resetLoadmore` 方法的例子（建议使用 CamelCase 书写 `resetloadmore` -> `resetLoadmore`）。

```html
<list id="list" onloadmore="handleLoadmore" loadmoreoffset="{{offset}}">
  ...
</list>

<script>
module.exports = {
  data: { offset: 1000 },
  methods: {
    handleLoadmore: function () {
      fetchMoreData().then(function() {
        // 获取数据成功
        ... （绑定新数据等）
        this.$el('list').resetLoadmore()
      }).catch(function(err) { ... })
    }
  }
}
</script>

```

**Comment by sospartan** [comment]
@MrRaindrop @misakuo 这个讨论已经有结论了么？

**Comment by misakuo** [comment]
@namedlock

**Comment by namedlock** [comment]
@sospartan 增加一个方法resetLoadmore
