### ISSUE TITLE
将weex生成的js放到android后生成apk，可是发现只要用了<wxc-tabbar></wxc-tabbar>，里面的内容就全无，求解

### ISSUE THREAD

**Issue by MARCUSW10** [alibaba/weex#1666]

**Comment by vczero** [comment]
你好，可以确保下tabbar里面引入的js文件路径正确吗？

**Comment by MARCUSW10** [comment]
就算里面没有js文件的路径，只要在we文件一加入<wxc-tabbar></wxc-tabbar>,即使在playground能正常显示，但是只要用android studio生成apk，就只见到一片空白

**Comment by Jinjiang** [comment]
@MARCUSW10 `<wxc-tabbar>` 在使用的时候是需要依赖 `weex-components` 这个 npm 包的，请先确认一下是否正确引入，如果还不能正常工作，有劳提供一下您的 Android 版本和 Weex 源代码的版本或分支名

谢谢

**Comment by acton393** [comment]
hi @MARCUSW10    

如果引入 wxc-开头的一些自定义的组件，得在你的.we 文件里面写上
```
require('weex-components')
```

并且执行 
```
npm install weex-components
``` 
或者 
```
cnpm install weex-components
```

这些自定义的组件源码 [weex-components](https://github.com/weexteam/weex-components)
