### ISSUE TITLE
Animated GIF doesn't work well in Android

### ISSUE THREAD

**Issue by Jinjiang** [alibaba/weex#1673]
For example:

```html
<template>
  <div>
    <image
      src="http://ww3.sinaimg.cn/mw690/005BUxg5gw1f9xltfd6ctg307305f1kz.gif"
      style="width: 300; height: 200;"></image>
  </div>
</template>
```

Just work well in HTML5 Render & iOS. Android doesn't render anything or a static picture.

Weex playground app 0.8.0.4 from weex homepage
SmartisanOS

**Comment by zshshr** [comment]
这个是图片库的需要支持，palyground的图片库是不支持的gif的，手淘的图片库的可以支持的，这个功能偏适配层，需要开发自己在自己的图片库实现 @Jinjiang
