### ISSUE TITLE
【新需求】如何实现类似Vue.filter的功能

### ISSUE THREAD

**Issue by Hello2015** [alibaba/weex#1676]
在Vue中可以使用以下方法：
```
Vue.filter("statusLabel" , function(value){
  switch(value)
  {
   case 0:return "未开始";
  case 1:return "正在进行";
  case 2:return "已结束";
 default:return "未开始";
}
});
```
在使用的时候只要`v-text="list.status | statusLabel"
`
即可将状态转换为文本。
请问在weex是否有这样的功能，如果有，如何使用？

谢谢大神们！

**Comment by Hanks10100** [comment]
我们和 Vue 有合作，正在将内核切换成 Vue 2.0，完成后将支持所有 Vue 2.0 的语法。可以在这个 [Roadmap](https://github.com/weexteam/weex-vue-framework/issues/9) 里看到进度。
