### ISSUE TITLE
iOS关于targetExecuteThread方法的疑惑

### ISSUE THREAD

**Issue by george-luofz** [alibaba/weex#1678]
在一个download module中，我需要在子线程上做一个download的任务，如果不在targetExecuteThread方法中创建子线程，而是直接在调用方法中创建子线程，下载完毕callback是否能得到执行?
例如：
WX_EXPORT_METHOD(@selector(downloadImgs:sucCallback:failCallback:))
-(void) downloadImgs:(NSDictionary) options sucCallBack:(WXModuleCallback)sucCallback failCallBack:(WXModuleCallback)failCallback{
...
[downloadService downloadImages:imgUrls sucCallBack:^(id result){ // 子线程操作
...
sucCallback(@{@"success":result});// 主线程操作，sucCallback是否能得到执行?
}failBlock:^(NSError *)error{
failCallback(@{@"error":error});
}];
}

**Comment by cxfeng1** [comment]
可以执行， targetExecuteThread只是用来指定让SDK在哪个线程调用你的 `downloadImgs: sucCallBack: failCallBack`方法， 跟这个方法里面的实现无关。

**Comment by george-luofz** [comment]
@cxfeng1 感谢！我测试了一下确实可行。另外，由于callback是从JS间接传入oc，那么oc函数中callback生命周期与JS中的对应的fuc生命周期是否一致？拿上边例子来说：当在子线程执行downloadImgs:sucCallback:failCallback操作，假设执行了很长时间，执行完毕需要sucCallback(在主线程执行)时，JS中对应的func是否会出现已经被释放，造成callback无法回调。对weex的内存管理疑惑较大

**Comment by cxfeng1** [comment]
@george-luofz  JS对应的func回调默认会在被调用一次后才被释放， 所以不用担心你的callback不会被执行， 除非回调时页面已经被销毁。

另外如果你想让JS的func一直保留，比如需要回调多次的场景， 那么可以使用 keep alive callback:

```
typedef void (^WXModuleKeepAliveCallback)(id result, BOOL keepAlive);
```

将keepAlive置为YES， 那JS的func会一直保存直到页面销毁。

**Comment by george-luofz** [comment]
@cxfeng1 ok，感谢
