### ISSUE TITLE
weex增量升级方案

### ISSUE THREAD

**Issue by liujianying** [alibaba/weex#1679]
weex已经开源几个月了,相信陆续有团队已经使用weex开发出对应的demo
既然是动态更新方案,weex为何没有提及任何增量更新的相关信息.
所以希望weex团队能够分享些这方面的解决方案

以下是参考RN的更新方案,但是更想听听weex是如何去实现的.
https://github.com/cnsnake11/blog/blob/master/ReactNative开发指导/ReactNative增量升级方案.md

https://github.com/cnsnake11/react-native-pushy

**Comment by Jinjiang** [comment]
好问题
我对上述文章的理解是，JS Bundle 代码是默认离线的，而且整个 App 的内容是固定的，每次都做完整离线同步或局部离线同步
Weex 的 JS Bundle 目前是以页面为单位的，相互之间独立，有各自的线上 URL。只要 App 作者部署新的 URL，就可以通过页面跳转的方式让 App 产生一个新的界面。这样的模型和传统的浏览器模型是非常接近的，所以所谓的“增量更新”在 Weex 的角度看是一个浏览器页面离线缓存的问题
我们可以用类似浏览器的 HTTP 缓存或 AppCache 的策略来做到相同的效果，也可以增加一些通过服务器把缓存主动 push 给客户端的附加功能
目前 Weex 本身并没有提供这样的能力，但是可以和目前主流 App 针对 webview 的缓存策略做一个简单的对应，就可以很好的配合起来
以上

**Comment by haicuan139** [comment]
我的做法是
1：使用renderbyurl
2：通过download jsbundle 的方式实现。

**Comment by likenow** [comment]
@haicuan139 您好，我也在学习weex，在增量更新这块遇到了问题，“通过download jsbundle 的方式实现”希望能够描述的再具体点，谢谢！

**Comment by sunzhongliangde** [comment]
@likenow 
可以做一个简单版的缓存方案
重写renderbyurl，在这个方法里面判断本地是否存在缓存以及缓存版本号是否一致，若一致则从缓存加载，否则加载远端地址
weex提供onjsdownloadfinish方法，在这个方法里面可以将js文件写入本地缓存

以上，仅供参考
