### ISSUE TITLE
WXSDKInstance.render的options参数不支持传bundleUrl作为key

### ISSUE THREAD

**Issue by sascsy** [alibaba/weex#1682]
我发现android SDK下如果在WXSDKInstance.render方法的options传入bundleUrl参数就会渲染失败。

手动跟踪代码发现是WXBridgeManager.invokeCreateInstance(String,String,Map,String)调用WXJsonUtils.fromObjectToJSONString(options)序列化方法发生无限递归调用导致堆栈溢出。
但如果在上级方法调用相同的序列化方法则没有问题。

**Comment by sascsy** [comment]
我找到原因了 Url我传的是Uri类型

**Comment by Hanks10100** [comment]
OK, closed.
