### ISSUE TITLE
cnpm run serve后打开localhost:8080只有一片空白，应该如何做

### ISSUE THREAD

**Issue by MARCUSW10** [alibaba/weex#1693]

**Comment by MARCUSW10** [comment]
我是将想自己的we文件集成到web上，we文件是有内容的，可以在playground中显示，但卡在这里了，希望各位高手指点

**Comment by fkysly** [comment]
weex default port is 12580, please check your port mapper.

**Comment by Jinjiang** [comment]
主仓库的端口是 12580
如果通过 weex-toolkit init 出来的空白仓库端口是 8080
一般情况下如果也没空白，首先确认你的网络请求包括路径、端口号是否正确 (可以通过服务器日志先做确认)；然后看有没有 we 文件编译的报错，以及 运行时 JS 的报错；如果还没有发现问题，请比对一下官方可工作的例子，有哪些出入。
谢谢
