### ISSUE TITLE
textarea控件的bug

### ISSUE THREAD

**Issue by liujianying** [alibaba/weex#1701]
### iOS:
1. 设置padding 属性设置无效
2.  placeholder采用label实现,字体大小没有和UITextField统一,同时placeholder比较长时候,无法自动换行

### android:
 1. 默认text 文本属性是垂直居中,如果需要多行显示的时候就有问题,无法通过设置TOP属性让他在显示在顶部
2.当前控件必须设置lines 属性才能显示多行,否则默认只能显示2行.  

```
<template>
	<wxc-navpage data-role="none" height={{navBarHeight}} background-color="#1b1d29" title={{title}} title-color="white" left-item-src="http://7xocov.com2.z0.glb.qiniucdn.com/return.png" left-item-color="white">
		<div class= "root">
		    <textarea id ="textarea-id" class="feedback"    lines="10000" autofocus="true" placeholder="给您带来不便深表歉意，您的意见能帮助我们更好的完善产品." >
			</textarea>

            <wxc-button class="btn" value="提交" onclick="commit" type="normal"></wxc-button>
		</div>
	</wxc-navpage>
</template>


<style>
    .root {background-color: #eeeeee; flex: 1; flex-direction:column; align-content: center; }
    .feedback {width:750;height:300; padding: 10; background: red; color:blue; placeholder-color:red;font-size:30;}
    .btn { width:720; height: 100; background-color: orange; margin-left: 15; margin-top: 15; }
</style>
<script>

    // 使用的组件
    require('weex-components');
    module.exports = {
        data: {  //数据绑定
            navBarHeight : 88,
            title: '意见反馈',
            scheight:1000,
        }
   }
</script>
```

![a190ce54-bcc6-44be-8628-cf77adec9dc7](https://cloud.githubusercontent.com/assets/6265414/20584799/13b0a16a-b231-11e6-8d80-a903c951360a.png)
![b545d597-b592-4528-a860-abfd599985f5](https://cloud.githubusercontent.com/assets/6265414/20584978/74b117a0-b232-11e6-84ac-425ff39bf6aa.png)

**Comment by acton393** [comment]
hi @liujianying 
textarea 组件是参照[w3c](https://dev.w3.org/html5/spec-preview/the-textarea-element.html) 上的组件的标准来实现的,如果不写的话,默认的rows 是2 行，它不是通过高度来控制的 

iOS : 
         1. 问题确实存在，待修复
         2. 问题 **已经** 在ios-feature-1208 修复掉，后面会发布，


Android  居中这个问题我记得也已经修复掉了， @sospartan

**Comment by liujianying** [comment]
@acton393  我这边在梳理下
ios :
1.设置padding 属性设置无效       
2.默认键盘弹出时候placeholder无法显示

还有个问题看代码发现 
ios          设置行的属性是row  
android  设置行的属性是lines  两端这个未做统一.

**Comment by sospartan** [comment]
行数两边都支持rows；
android上竖向居中的问题也已经修复过了，暂时可以使用android分支的最新代码

**Comment by liujianying** [comment]
@sospartan  Thank you
