### ISSUE TITLE
关于this.$getConfig().env.deviceWidth

### ISSUE THREAD

**Issue by fromIRIS** [alibaba/weex#1704]
在H5环境打印`self.$getConfig().env.deviceWidth`都是统一的750，查看源码确实是写死了750.
那这个还有什么意义呢？

另外在安卓H5端编写1边框问题，由于安卓H5不支持小于1的值，所以安卓H5显示不了1边框。

在FQA中查看这个方法，原理上是行通的，因为在安卓下这样处理就会显示真正的1px，但是这个`deviceWidth`永远都是750呀。。。。在weex中定义 1 /750 \*750还是 1，在安卓H5下就会被转换为 360/750\*1 < 1px

![image](https://cloud.githubusercontent.com/assets/8492963/20585815/1ddfd266-b239-11e6-9b9f-eb127b23ecae.png)

**Comment by Jinjiang** [comment]
该问题已经通过引入 viewport 配置的方式尝试解决 #421
更多讨论可以在那边继续，为了讨论更聚焦这个 issue 我关掉了
谢谢理解
