### ISSUE TITLE
[新需求]获取某个元素的具体大小

### ISSUE THREAD

**Issue by Hello2015** [alibaba/weex#1714]
目前好像没有获取某个元素具体大小的方法。例如我想要获取一个text的宽度和高度，怎么获取呢？

**Comment by Hanks10100** [comment]
`getComponentRect` 可以，参考 #1581 和 #1455

**Comment by Hello2015** [comment]
我在Playground环境里面运行调试的时候没有找的这个方法，是这个方法只支持在HTML5中运行吗？
