### ISSUE TITLE
ios：list下拉回弹后uitableview的bounds变为-0.5

### ISSUE THREAD

**Issue by voicewitness** [alibaba/weex#1716]
出现的代码结构是:
```
<list>
<refresh>
<item></item>
</refresh>
<cell><slider><div repeat="item in array"></div></slider></cell>
<cell repeat="item in array"></cell>
<cell repeat="item in array"></cell>
</list>
```
下拉小段距离后回弹发现uitableview的bounds变为-0.5（效果是视图顶端出现白线条）；
下拉刷新回弹或者slider在自滚动的过程中恢复正常

**Comment by cxfeng1** [comment]
@voicewitness  麻烦给一下更详细一些能run的例子，以及出现的机型、系统， 我在playground试了几个机型，list都是能正常回弹的。

**Comment by voicewitness** [comment]
我这边在5se，6，6p，7p等机型都出现过，是一个很普通的list，往下拉一点点10个单位左右，放手、回弹，就出现了@cxfeng1

**Comment by cxfeng1** [comment]
@voicewitness 是使用的 playground 还是自己的客户端， 具体的Weex接入方式有么？

**Comment by cxfeng1** [comment]
已修复 #1984
