### ISSUE TITLE
navigtor 怎么pop到指定页面

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#1717]
###  问题一

在使用navigator组件时，我在 A -> B -> C, 现在想从C pop A, 我在pop方法的param中加url：A的path，发现pop还是只回到了上一界面， 求解怎么回到A？

###  问题二
 有没有native与weex相互调用的参考
因为项目中都是局部套用weex，有很多关于数据的相互调用，以及相互跳转，求资料？？？？？

**Comment by YorkShen** [comment]
1. pop不支持参数，pop和push的能力以文档为准，文档中没有就是没有实现或者内部不稳定实现，不保证后续兼容性。
1. https://github.com/alibaba/weex/blob/doc/doc/advanced/integrate-to-android.md
