### ISSUE TITLE
Tutorial too much recursion

### ISSUE THREAD

**Issue by paolodina** [alibaba/weex#1721]
I'm trying to [follow the tutorial](https://alibaba.github.io/weex/doc/tutorial.html). With the slider I get a recursion error and nothing is shown on the page. Any idea why? weex 0.6.2, node 4.5.0

```
START WEEX HTML5: 0.4.0 Build 20161019 weex.js (line 1)
GET http://127.0.0.1:8081/weex_tmp/h5_render/tech_list.js 200 OK 3ms weex.js (line 10373)
transformerVersion: undefined, available transformerVersion: >=0.1.5 <0.4 weex.js (line 6182)
[h5-render] createBody Node { nodeType=1,  nodeId="4",  ref="_root",  more...} weex.js (line 9491)

too much recursion weex.js (line 11138, col 6)
Received: 'ws server ok' weex.js (line 333)
```

**Comment by MrRaindrop** [comment]
Is this running on the browser's device simulator ? I assume you are using the weex-toolkit and the `weex xx.we` command. Which version of weex-toolkit are you using ?

**Comment by MrRaindrop** [comment]
I see, toolkit's version is `0.6.2`. It works fine on my chrome device simulator. Which platform is the blank page showing on, ios, android or browser (and webview) ?

**Comment by paolodina** [comment]
```
$ weex slider.we 
info Wed Nov 30 2016 21:26:11 GMT+0100 (CET)WebSocket  is listening on port 8082 
info Wed Nov 30 2016 21:26:11 GMT+0100 (CET)http  is listening on port 8081 
```

I tested on Firefox 50 and Chrome 54 / Ubuntu and got the same error.

weex-toolkit 0.6.2

I suspect something is wrong with my code, sorry in this case. [slider.txt](https://github.com/alibaba/weex/files/622903/slider.txt)

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
