### ISSUE TITLE
onTouch事件在iphone Retina （plus,7）上的坐标兼容问题

### ISSUE THREAD

**Issue by haicuan139** [alibaba/weex#1723]
iphone 7 touch 事件产生的  screenY，screenX 和pageY，pageX 坐标与非Retina屏是有很大差别的。
这个问题会导致 在使用ontouchstart move 去处理滑动事件的时候会不兼容。

**Comment by acton393** [comment]
hi @haicuan139 

麻烦给一个例子我这边验证下

**Comment by Jinjiang** [comment]
由于长期没有回复，这个 issue 我先关掉了，如果仍有问题可以再开 issue
谢谢
