### ISSUE TITLE
Would WEEX separate the  js framework core part as npm module

### ISSUE THREAD

**Issue by seajean** [alibaba/weex#1724]
## What the situation is now
if someone want to use another framework as WEEX  js framework, he will want to modify the source code and run build:native again
## What to expect 
Separating the  js framework core part, and developers can use npm install it, and using another framework can be  something  easy as the codes shown below

```
import Core from 'weex-core';
import FW from './myframework';
import BuiltIn from './myBuiltIn';

Core.addFrameWork(FW);
Core.addBuiltIn(BuiltIn);
module.exports Core;
``` 

## why doing this
WEEX js framework is changing all the time, including it building tool and  framework it used, custom framework's developing jsfm and building tools are not the same, and building them together  cause some problems.

**Comment by yuanyan** [comment]
Good idea, jsfm could be split into some node packages.

**Comment by Hanks10100** [comment]
Agree. Split js framework into small parts will very convenient for developers.

Currently we already have:

+ [weex-js-framework](https://www.npmjs.com/package/weex-js-framework): The js framework of Weex.
+ [weex-js-runtime](https://www.npmjs.com/package/weex-js-runtime) The runtime of Weex, which is shared with all "cores".
+ [weex-vue-framework](https://www.npmjs.com/package/weex-vue-framework): The Vue ^2.0 "core" of Weex. (The source code of it is in [Vue repo](https://github.com/vuejs/vue).)
+ [weex-html5](https://www.npmjs.com/package/weex-html5): Weex HTML5 renderer.
+ [weex-components](https://www.npmjs.com/package/weex-components): A group of simple and useful weex components.

But they may not be suitable for use alone, some of them is hard to use (`weex-js-framework` contains ES6 modules, which couldn't running on node platform recently). I will continue decoupling the internal modules of Weex and publish more packages.
