### ISSUE TITLE
Android 不能重新render js 加载页面

### ISSUE THREAD

**Issue by wqd1994** [alibaba/weex#1725]
在页面中已经加载了JS 文件，我想通过重新加载JS的方式刷新页面，发现android端重新render不起作用。

**Comment by zshshr** [comment]
目前还不支持重新加载的方式刷新，只能针对通过js 的数据进行刷新，不能对整个页面进行刷新

**Comment by wqd1994** [comment]
Ok  那我还是通过Global的方式吧
