### ISSUE TITLE
事件冲突怎么怎么解决

### ISSUE THREAD

**Issue by Jam1zhu** [alibaba/weex#1726]
在同一个标签绑定了两个事件，click 和 longpress，触发longpress的时候，也会触发click事件，请问有什么好的解决方案吗？

**Comment by haicuan139** [comment]
在event的携带json 里面有 eventtype 这样的字段 可以进行判断

**Comment by hebby** [comment]
@Jinjiang 请问这个问题最后是怎么解决的呢，longpress结束都会触发click事件
