### ISSUE TITLE
页面之间如何进行数据交互

### ISSUE THREAD

**Issue by Hello2015** [alibaba/weex#1727]
A打开B，B处理完数据之后需要通知A，此时该如何去做？

**Comment by haicuan139** [comment]
哪个naticve?

**Comment by Hello2015** [comment]
例如我在A.we中使用openURL方法打开了B.we，B中处理了一些数据，我想在B页面关闭的时候通知A数据处理的结果，这个功能该如何实现？

**Comment by Hanks10100** [comment]
组件之间的通信可以用 `$on` 和 `$dispatch`，文档里有。http://alibaba.github.io/weex/doc/syntax/comm.html

想让 B 页面关闭时发送通知，可以使用 `destroyed` 生命周期。

```js
module.exports = {
  destroyed: function () {
    this.$dispatch('B:destroyed', {})
  }
}
```

**Comment by Hello2015** [comment]
我这里说的并不是组件之间的通信，而是两个页面(Activity)之间的通信。
`module.exports = {
  destroyed: function () {
    this.$dispatch('B:destroyed', {})
  }
}`
这个地方派发的事件A页面应该是收不到的吧？

**Comment by haicuan139** [comment]
@Hello2015 两种方法1.处理Activity的 onResum 2.处理WEEX 的onResum 3.用全局通知

**Comment by Hello2015** [comment]
@haicuan139 看来没有捷径了，我这边想到的是拓展了globalEvent,目前是在Weex中可以fireGlobalEvent,这样可以跨页面进行数据通知。在`WXGlobalEventModule`中添加了
```
@WXModuleAnno
  public void fireGlobalEvent(String eventName, String jsonData) {
    try {
      JSONObject json = new JSONObject(jsonData);
      Iterator<String> nameItr = json.keys();
      Map<String, Object> outMap = new HashMap<String, Object>();
      while(nameItr.hasNext()) {
        String name = nameItr.next();
        outMap.put(name, json.get(name));
      }
      mWXSDKInstance.fireSuperGlobalEventCallback(eventName , outMap);
    } catch (JSONException e) {
      e.printStackTrace();
    }
  } 
```
在`WXSDKInstance`中增加了
```
public void fireSuperGlobalEventCallback(String eventName, Map<String,Object> params){
    List<WXSDKInstance> instances = WXSDKManager.getInstance().getWXRenderManager().getAllInstances();
    for(WXSDKInstance instance : instances)
    {
      instance.fireGlobalEventCallback(eventName , params);
    }
  }
```
目前消息可以跨页面进行通知，但是还不知道会不会产生别的bug，目前还在测试中。

**Comment by Hanks10100** [comment]
@Hello2015 页面间通信的话可以参考 #1536，简而言之是打算实现 [`BroadcastChannel`](https://html.spec.whatwg.org/multipage/comms.html#broadcasting-to-other-browsing-contexts) API 。全局事件可能会被废弃，不建议hack。#1619 #1605

**Comment by zk0301** [comment]
我按你的方法也实现了。楼上Hanks10100发的BroadcastChannel不知道是什么我看不懂，链接过去一堆鬼佬文。看官网文档关于BroadcastChannel没有介绍。我的版本是0.10.x。

**Comment by zhushangwei** [comment]
@Hanks10100 这个问题到底该怎么解决？

**Comment by zk0301** [comment]
看到官网迁移了，BroadcastChannel的文档出来了，https://weex.apache.org/cn/references/jsfm-apis.html。实际支持了吗，怎么使用？

**Comment by zk0301** [comment]
broadcastchannel 测试可用。

**Comment by jasonhe88** [comment]
@zk0301 请问你用的是Vue 还是 We? 我用Vue在iOS下不行

**Comment by zk0301** [comment]
@jasonhe88   we，在安卓和ios都可以。 vue还不知道

**Comment by Labmem003** [comment]
报告，vue亲测已可用。
