### ISSUE TITLE
H5:stream跨域提示Unexpected token

### ISSUE THREAD

**Issue by 1459416736** [alibaba/weex#1732]
首先，参考了https://github.com/alibaba/weex/issues/1055 这个问题的解决方法，已经更新到0.4.0
START WEEX HTML5: 0.4.0 Build 20161019
但是我使用跨域还是会报错，请问是怎么回事

**Comment by Jinjiang** [comment]
跨域问题请在 #1686 下继续讨论吧，这里就不产生更多 issue 了
谢谢理解
