### ISSUE TITLE
[Proposal] Managing class styles in native renderer

### ISSUE THREAD

**Issue by Hanks10100** [alibaba/weex#1733]
In short:

 > JS framework send all static class styles to native before rendering, and the native renderer is responsible for managing those static styles by class name.

## Current situation

For the styles written in the `<style>` tag, js framework will merge them into vdom's `style` property including the class name, and those styles will send to native renderer by `callNative`.

## Known problems

If developer use a same class name in many places, even if they have only one definition in `<style>`, the styles would still be copied into multiple vdom elements.

This behavior greatly increases the memory usage and the communication burden.

## Proposal

JS framework (even transformer) can extract all the class styles into an immutable object, and it can be send to native before rendering. The vdom element no longer need to have `classStyle` property,  it only needs to care about the `className`.

While rendering, js framework send the inline styles and the class name to the native. Native parse the class name and calculate the real style of the element.

### Advantages

+ **Less memory usage.** No need to store multiple copies of class style.
+ **Faster render speed.** Less messages would be send between js and native.
+ **No breaking change.** The DSL and the behavior doesn't change. Developer will not be aware of this modification.
+ It's much easier to handler the pseudo-class. (#942)
+ Components can have a default style, and it could be configurable.

### Disadvantages

+ How to manage the scope of all the class styles.
+ Both js framework and native renderer should have a lot of modifications.

**Comment by Jinjiang** [comment]
This proposal needs iOS/Android render, js framework, transformer, devtool all changed. And it needs to be scoped manually (with some prefix etc.) for each custom component.
And the "faster render speed" need to be approved with more experiment and details.

**Comment by Hanks10100** [comment]
On hold, temporarily move to #1494 . It will be reopen when we actually doing this.
