### ISSUE TITLE
[Proposal] Support CSS property Inheritance

### ISSUE THREAD

**Issue by Hanks10100** [alibaba/weex#1735]
See the example below:

```html
<template>
  <div style="color:blue">
    <text>blue</text>
  </div>
</template>
```
The text color should be blue, but it shows black on the phone. ([demo](http://dotwe.org/8216e8160b41b588dcf26dafdf6346bc))

I think we should support the inheritance, which is a useful and powerful technique in writing styles.

## Properties we should support

The full list of inherited properties could be found in [W3C's spec](https://www.w3.org/TR/CSS21/propidx.html). Here is a summary on stackoverflow: [Which CSS properties are inherited?](http://stackoverflow.com/questions/5612302).

But we do not need to support all Inheritable properties (many properties are not support originally 😂 ).

Here is a candidate list I organized:

+ color
+ font-family
+ font-size
+ font-style
+ font-weight
+ line-height
+ text-align

Quite a short list 😄.

The most important property we should support at first is **`color`** and **`font-size`**.

**Comment by Hanks10100** [comment]
On hold, temporarily move to #1494 . It will be reopen when we actually doing this.

**Comment by Gaohaoyang** [comment]
After two years, when should this issue reopen?
