### ISSUE TITLE
Weex Android扩展自定义控件 无法显示

### ISSUE THREAD

**Issue by jiantao88** [alibaba/weex#1746]
## Weex 中使用WXComponent 扩展自定义控件，在.wx中使用后android端无法显示，请帮忙查看是否我这写的有问题；
![image](https://cloud.githubusercontent.com/assets/7411102/20658304/bac9887a-b576-11e6-8d5a-03157184e7b4.png)
![image](https://cloud.githubusercontent.com/assets/7411102/20658311/c570241e-b576-11e6-9b07-8bd694d181ac.png)
.wx 里调用的方法
```html
<richtext style="background-color:red;margin-top: 30" tel="18600000000"></richtext>
<text style="background-color:red;">123</text>
```

实际应该显示两个textview ，结果只显示了下面正常的text，自定义的richtext不显示
![image](https://cloud.githubusercontent.com/assets/7411102/20658344/05a6bb7e-b577-11e6-928c-d5ecd064850b.png)

![image](https://cloud.githubusercontent.com/assets/7411102/20658516/8072d97c-b578-11e6-83b4-2a5c719a7e91.png)
Android7.0系统

**Comment by YorkShen** [comment]
自行定制的text，需要自行编写dom和component的measure方法，参见WXTextDomObject。同时需要把dom和component关联起来，见https://github.com/alibaba/weex/blob/dev/android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java#L345

**Comment by jiantao88** [comment]
http://alibaba.github.io/weex/doc/advanced/extend-to-android.html
按照文档缩写的，我已经在application中调用了注册方法，请看图2 
也就是这个方法，但是还没没有显示
```WXSDKEngine.registerComponent("richtext", RichText.class);```

**Comment by YorkShen** [comment]
@jiantao88 需要注册dom，请看上一条回答。

**Comment by jiantao88** [comment]
![image](https://cloud.githubusercontent.com/assets/7411102/20704395/129403d0-b65a-11e6-9292-28ac730161b4.png)
是这样注册么？这样注册还是无法显示

**Comment by YorkShen** [comment]
@jiantao88 是的，dom和compoent要配对，WXTextDomObject需要和WXText配对，和其他的component配对，可能渲染不出来。

**Comment by jiantao88** [comment]
那如何自定义dom呢？我看官方文档和官方demo里都没有相关的代码，RichText也是官方demo里的。

**Comment by YorkShen** [comment]
所有的dom都需要继承WXDomObject，看下WXSwitchDomObject的代码，那个是最简单的dom.
