### ISSUE TITLE
Native 与weex交互的一点疑问

### ISSUE THREAD

**Issue by myyeshang** [alibaba/weex#1756]
因为业务需要，要在原生里实现一些功能，反馈数据给weex页面，本来绑定的data直接refreshInstance是没有问题的，结果刚好今天碰到了一个页面用的tab bar，refresh的结果是只能更新tabbar的页面数据，不能更新tabitem的子页面数据，求教有没有相关的说明。或者关于本地数据与weex通讯有无更好的实现方法。

**Comment by bluebird78999** [comment]
如果只更新某个item里数据可以自定义相关module或组件，weex文件里添加js方法调用，使用callback回调获取本地数据。比如：`
refreshXXData: function() {
                var xxPicker = require('@weex-module/xxPicker');
                var self = this;
                xxPicker.refresh({
                    'value':'aa',//传入参数
                },function (ret) {
                    var result = ret;//返回结果
                });
            },
`

**Comment by myyeshang** [comment]
@bluebird78999  刚好所需的业务还要复杂一点，一个是websocket之类的即时推送，一个是二维码扫描，这两个返回的消息都需要主动推过来，所以用weex的js回调显得麻烦而且不够及时。暂时用的方法是开了不含tabbar的新页面。希望开发组后面能考虑一下这个问题。
