### ISSUE TITLE
建议支持文本格式嵌套

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#1759]
比如:
```html
<text>hello,<text>world!</text></text>
```

用途很简单，一段文本可以多样格式，不同的加粗，字体，大小。
可以用webview代替实现，只是如果页面多处需要，webview多了影响性能。

**Comment by Hanks10100** [comment]
See #1740 , use webview is not suitable.

**Comment by liwenyou** [comment]
可以以写在一个div里，然后几个text样式一起用

**Comment by Neeeo** [comment]
试过，如果文字里有 emoji，则会对不齐，应该是行高的问题

**Comment by liwenyou** [comment]
设置行高后，就不居中了

**Comment by Neeeo** [comment]
设置固定行高会让没有 emoji 的样式不好看

**Comment by Hanks10100** [comment]
如果你想在文字里边加上图片（emoji）的话，可以用富文本 #835 ，正在开发了。

**Comment by Jinjiang** [comment]
相关讨论汇总到 #835 吧，这里先关掉了
谢谢
