### ISSUE TITLE
list里面嵌套scroller问题

### ISSUE THREAD

**Issue by liwenyou** [alibaba/weex#1765]
# 1.滑动方向不同：
嵌套有scroller的cell会跑到第一行。
![simulator screen shot 2016 11 29 15 56 29](https://cloud.githubusercontent.com/assets/8529588/20701496/64442266-b64e-11e6-8833-15eb1c9a66f1.png)
正常应该是这样的：
![simulator screen shot 2016 11 29 16 10 06](https://cloud.githubusercontent.com/assets/8529588/20701510/71fc8b32-b64e-11e6-8684-ee4edfd34f82.png)

## 环境：
weex 0.8.0有这个问题，0.7没有。iOS 10；调用render位置：viewDidLoad
# 2.滑动方向相同：
高度计算不准。包括marquee。

**Comment by cxfeng1** [comment]
```
<template>
  <list>
    <cell>
      <text>
        cell 1
      </text>
    </cell>
    <cell>
      <text>
        cell 2
      </text>
    </cell>
    <cell>
      <scroller scroll-direction="horizontal" style="height:50;">
        <div style="background-color:red;width:500"></div>
        <div style="background-color:green;width:500"></div>
      </scroller>
    </cell>
  </list>
</template>
```
@liwenyou  我试了一个最简单的例子， 带scroller的cell是可以放到指定位置的， 另外第2个问题是否能再描述详细一点，最好能带上你精简过后的代码例子，谢谢！

**Comment by liwenyou** [comment]
例子怎么给你？

**Comment by cxfeng1** [comment]
精简之后直接贴到回复里就可以了

**Comment by Jinjiang** [comment]
也可以写在 dotwe.org 里写，写好之后把链接贴出来

**Comment by Jinjiang** [comment]
由于长时间没有收到反馈，该 issue 暂时关闭，如果有新的情况可以再开 issue 讨论
感谢理解
