### ISSUE TITLE
刷新数据，list里的slider数据会成倍增长

### ISSUE THREAD

**Issue by liwenyou** [alibaba/weex#1766]
刷新数据，list里的slider数据会成倍增长，但是上下滚动，消失后再现就正常了，是不是底层cell可重用的时候没处理好？
![simulator screen shot 2016 11 29 16 12 37](https://cloud.githubusercontent.com/assets/8529588/20701686/5b223bae-b64f-11e6-9ab7-bf4b5d840e91.png)
![simulator screen shot 2016 11 29 16 12 42](https://cloud.githubusercontent.com/assets/8529588/20701688/5c019934-b64f-11e6-823b-6c568722972d.png)
![simulator screen shot 2016 11 29 16 13 23](https://cloud.githubusercontent.com/assets/8529588/20701687/5bf6e890-b64f-11e6-9ee7-78fa20a97c5f.png)

**Comment by Jam1zhu** [comment]
很多人遇到。andriod没问题，ios有问题

**Comment by boboning** [comment]
@liwenyou , slider的数据是通过更新取得的，你可以参考下面几步再试一下：
1. 更新完slider数据，将原数据清空；
2. 通过setTimeout的方式，使用set方法重设数组项；
例如：
```
this.sliderArray = [];
var self = this;
setTimeout(function(){
     var l = temp.length; // temp为刷新后的数据
      for(var i = 0;i<l;i++){
            self.sliderArray.$set(i,temp[i]);
       }
 },0)
```

**Comment by liwenyou** [comment]
还是不好使，直接没有数据了

**Comment by liwenyou** [comment]
//                    self.data1_0 = [];
//                    self.data1_0 = data[2];
                    var temp = data[2];
                    this.data1_0 = [];
                    setTimeout(function(){
                        var l = temp.length; // temp为刷新后的数据
                        for(var i = 0;i<l;i++){
                            self.data1_0.$set(i,temp[i]);
                        }
                    },0)

![simulator screen shot 2016 12 12 19 16 03](https://cloud.githubusercontent.com/assets/8529588/21097483/98c4b16c-c09f-11e6-8d9d-13989a43f917.png)

**Comment by boboning** [comment]
@liwenyou ,  建议先把数据打印一下，看下js中拿到的结果是否正确，如果还是有问题的话，麻烦再把代码片段提供地详细一些，方便我们排查。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
