### ISSUE TITLE
[Android]关于 customize native APIs 中参数问题

### ISSUE THREAD

**Issue by Mhina007** [alibaba/weex#1768]
public class URLHelperModule extends WXModule{

    @WXModuleAnno
    public void openURL(String url,String callbackId){
        //...
        //callback to javascript 
        Map<String, Object> result = new HashMap<String, Object>();
        result.put("ts", System.currentTimeMillis());
        WXBridgeManager.getInstance().callback(mWXSDKInstance.getInstanceId(), callbackId, result);
    }
}
WXBridgeManager.getInstance().callback(mWXSDKInstance.getInstanceId(), callbackId, result);
中callbackId在we中是怎么定义的

**Comment by misakuo** [comment]
`callbackId`对应we文件里写的某个function，通常也可以在native代码里使用`JSCallback`对象替代`callbackId`，它事实上是对`callbackId`及`WXBridgeManager#callback()`的一个包装

**Comment by Mhina007** [comment]
@misakuo 有没有具体的demo

**Comment by misakuo** [comment]
比如如你上面的例子，写成下面这样：
```java
public class URLHelperModule extends WXModule{

@WXModuleAnno
public void openURL(String url, JSCallback callback){
    //...
    //callback to javascript 
    Map<String, Object> result = new HashMap<String, Object>();
    result.put("ts", System.currentTimeMillis());
    callback.invoke(result)
}
}
```
效果也是一样的

**Comment by Mhina007** [comment]
@misakuo 那这个JScallback 能够通知页面刷新吗 ？页面上是怎么写的

**Comment by misakuo** [comment]
请查看文档 https://alibaba.github.io/weex/doc/advanced/extend-to-android.html

**Comment by Mhina007** [comment]
看到了 ，一开始没看到
