### ISSUE TITLE
页面之间跳转，在跳转过程白屏期间是否有方法可以加入loading的图标状态

### ISSUE THREAD

**Issue by cyan24** [alibaba/weex#1776]
使用navigator push方法跳转页面期间，由于网络等其他原因，会出现短暂的白屏，是否有方法可以在白屏期间显示loading的图标？

**Comment by liujianying** [comment]
为什么现在做好的页面放到本地assets目录下面,第一次加载还要2s左右才能展示页面内容,第二次在进入用时在200ms~500ms 后才展示页面.这个在ios 上基本没问题,android上效果欠缺, 这个是否有优化空间
@Hanks10100

**Comment by liujianying** [comment]
今天把部分日志关闭,打成正式包发现页面跳转快很多,但是还是会出现白屏

**Comment by Jinjiang** [comment]
建议多分析一下，2s 时间在 JS 运行和 native 渲染中分别有多大开销，然后针对性的分析，哪块开销比较大就对哪个部分进行具体优化……
这个可能问题比较综合了

**Comment by 501956430** [comment]
@cyan24 遇到相同的问题，需要解决方案，请问你的问题解决了嘛？
