### ISSUE TITLE
SVG组件

### ISSUE THREAD

**Issue by cairuiquan** [alibaba/weex#1780]
# 一组纯Native SVG组件，类似于RN的ART SVG库 #
支持以下组件
## svg-surface ##
    <svg-surface width="" height="">
## svg-group ##
    <svg-group scale="" x="" y="" rotation="" originX="" originY="" transform="">
            
**scale**：float，相当于同时设置了scaleX与scaleY
**rotation**：float，旋转角度
**x**: float，x坐标
**y**: float，y坐标
**transform**：支持3种变换，可同时使用多种变换
**translate** 
transform="translate(x,y)"，即新坐标系的原点在原坐标系的（x,y）处。坐标轴的方向不变。
**rotate**
transform="rotate(angle cx,cy)"。angle代表旋转角度，缺省单位是“度”，瞬时针为正，逆时针为负。（cx,cy）是旋转中心所在的坐标。若省略旋转中心坐标，则缺省值是（0,0）。
**scale**
transform="scale(sx,sy)"，sx,sy分别代表x轴方向和y方向拉伸或缩小的比例因子。拉伸：大于1；缩小：小于1。若省略sy，即sy=sx，作等比例缩放。
## svg-rectangle ##
    <svg-rectangle scale="" x="" y="" rotation="" originX="" originY="" transform="" width="" height="">
## svg-shape ##
    <svg-shape scale="" x="" y="" rotation="" originX="" originY="" transform="" fill="" stroke="" strokeWidth="" strokeLinecap="" strokeLinejoin="" d="">
**fill**：填充颜色
**stroke**：描边颜色
**strokeWidth**：float，描边宽度
**strokeLinecap**：控制边框终点的形状，有三种可能值：
butt
square
round
**strokeLinejoin**：控制描边线段如何连接，有三种可能值：
miter 
bevel  
round 
            d：路径，支持以下指令m,l,c,s,q,t,a,h,v,M,L,C,S,Q,T,A,H,V,Z,z
## svg-circle ##
    <svg-circle scale="" x="" y="" rotation="" originX="" originY="" transform="" fill="" stroke="" strokeWidth="" strokeLinecap="" strokeLinejoin="" cx="" cy="" r="">
**cx**：float，圆心x坐标
**cy**：float，圆心y坐标
**r**：float，半径

## 例子 ##
    <svg-surface width="22" height="22">
        <svg-rectangle>
            <svg-shape transform={{SCALE_HALF}} fill={{themeIconColor}} d="M28.2,33.7h3v10h-3V33.7z M34.2,27.7h3v16h-3V27.7z M40.2,35.7h3v8h-3V35.7z"></svg-shape>
            <svg-shape transform={{SCALE_HALF}} stroke={{themeIconColor}} strokeWidth="3" strokeLinecap="round" d="M2.2,41.7c0,0,2.4-6,7-6s6.7-3,7-5 c0,0-3.9-3.5-5-6c-1.3-3.2-2-6.6-2-10C9.4,8.4,14.7,3.4,21,3.6c0.1,0,0.2,0,0.3,0c6.8,0.2,11.3,3.5,12,11c0.5,4.6-0.2,8.4-3,11"></svg-shape>
        </svg-rectangle>
    </svg-surface>

## 效果 ##
![image](https://cloud.githubusercontent.com/assets/16644713/20741000/61945fc2-b702-11e6-826f-16ae9ebf158b.png)

目前该组件已经在项目中使用。

**Comment by sospartan** [comment]
@cairuiquan 可以说一下具体的spec，或者使用的规范。

**Comment by cairuiquan** [comment]
晚上补充一下，下午比较忙，使用跟RN的 ART svg是一样的。

**Comment by sospartan** [comment]
@cairuiquan 我们不建议参考‘RN’，而是直接参考web规范。包括代码也是。

**Comment by cairuiquan** [comment]
由于我们项目前期是RN版本的，所以相关规范也跟RN一样，但如果放到weex里面可以按web规范来

**Comment by Jinjiang** [comment]
由于长时间没有更多讨论，这个提议先汇总到 #1494 了，非常感谢楼主的建议，我们也会对 SVG 相关的技术保持关注

**Comment by weepy** [comment]
I don't quite follow (sorry english here). #1494 only references the fact that this ticket is closed. Are you planning on supporting Native SVG in weex ?

**Comment by Jinjiang** [comment]
@weepy You are welcome.
Currently no more idea for SVG. Maybe we will do more research about this later and then make a decision. If we decide to support SVG, we will reopen this issue.
Thanks.
