### ISSUE TITLE
Navigator组件

### ISSUE THREAD

**Issue by cairuiquan** [alibaba/weex#1781]
# View级别的Navigator组件，用于实现bundle内的路由 #

由两个组件：nav、scene，和一个module：nav组成。scene的is-default属性为true是默认显示的场景，其他场景通过nav module的pop 与 push操作来实现路由
## nav组件 ##
navigator根组件，没有特殊属性
## scene组件 ##
定义一个场景

    <scene scene-name="" is-default="">

**scene-name**：场景名称，push或popTo时通过该名称来操作
**is-default**：默认场景
## nav module ##
**push(String sceneName)**：压入一个场景
**pop()**：弹出栈顶场景
**popTo(String sceneName)**：弹出指定场景

## 例子 ##
    <template>
        <nav class="nav">
	    <scene scene-name="scene0" is-default="true">
                <div>
                    <text style="font-size: 30">测试default</text>
                    <text style="font-size: 20" onclick="pushScene3">push scene3</text>
                    <text style="font-size: 20" onclick="pushScene4">push scene4 view pager</text>
                </div>
            </scene>
            <scene scene-name="scene1" >
                <div>
		    <text style="font-size: 30">测试scene1</text>
		    <text style="font-size: 20" onclick="pushScene2" >push scene2</text>
		    <text style="font-size: 20" onclick="pushScene4">push scene4 view pager</text>
		    <text style="font-size: 20; padding-top:30;" onclick="pop" >pop</text>
		</div>
            </scene>
            <scene scene-name="scene2" >
                <div>
		    <text style="font-size: 30">测试scene2</text>
		    <text style="font-size: 20" onclick="pushScene4">push scene4 view pager</text>
		    <text style="font-size: 20" onclick="removeScene1">remove scene1</text>
		    <text style="font-size: 20; padding-top:30;" onclick="pop" >pop</text>
		    <text style="font-size: 20; padding-top:30;" onclick="popTo3" >pop to scene3</text>
		</div>
            </scene>
            <scene scene-name="scene3" >
                <div>
		    <text style="font-size: 30">测试scene3</text>
		    <text style="font-size: 20" onclick="pushScene1">push scene1</text>
		    <text style="font-size: 20" onclick="pushScene4">push scene4 view pager</text>
		    <text style="font-size: 20; padding-top:30;" onclick="pop" >pop</text>
		</div>
            </scene>
        </nav>
    </template>

    <script>
        module.exports = {
	    init:function() {
	    },
	    created:function() {
	    },
	    ready:function() {
	    },
	    methods:{
	        pushScene1: function(){
		    var ucNav = require("@weex-module/nav");
		    ucNav.push("scene1");
                },
		pushScene2: function(){
		    var ucNav = require("@weex-module/nav");
		    ucNav.push("scene2");
		},
		pushScene3: function(){
		    var ucNav = require("@weex-module/nav");
		    ucNav.push("scene3");
		},
		pop: function(){
		    var ucNav = require("@weex-module/nav");
		    ucNav.pop();
		},
		popTo3: function(){
		    var ucNav = require("@weex-module/nav");
		    ucNav.popTo('scene3');
		}
            }
        };
    </script>
    <style>
        .nav {
	    flex: 1;
        }
    </style>

**该组件目前已经在项目中使用**

**Comment by emptywalker** [comment]
@cairuiquan  能否提供全部的代码，你这个组件内部的实现都没有展现出来，表示不知道具体是怎么实现的  谢谢哈

**Comment by Jinjiang** [comment]
由于长时间没有更多讨论，这个提议先汇总到 #1494 了，非常感谢楼主的建议
