### ISSUE TITLE
weex中统计图表的解决方法

### ISSUE THREAD

**Issue by 375575413** [alibaba/weex#1783]
在网上找了些关于weex中处理统计图表的方法，但是都没有很好的解决方案，看到有人建议用weex-canvas，不过好像weex中还没有canvas标签的支持，希望各位大神帮忙给一些建议或意见。

下面是weex-canvas的测试代码：
<template>
    <container>
        <canvas style="width:750;height:750;" id="canvas"></canvas>
    </container>
</template>
<script>
    var Canvas = require('weex-canvas');
    module.exports = {
        ready: function () {
            var ctx = Canvas.getContext(this.$el('canvas'));
            ctx.fillStyle = 'red';
            ctx.fillRect(100, 100, 100, 100);
            ctx.draw();
        }
    }
</script>

**Comment by Hanks10100** [comment]
暂时没有 `<canvas>` 组件，可以自己扩展。

**Comment by Jinjiang** [comment]
已汇总到 #1494 这里先关掉了
谢谢
