### ISSUE TITLE
[IOS] Input 在 ios 中，当设置 opacity 为0的时候无法唤起键盘

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1790]
要做一个输入 code 的控件，我把 input opacity:0后放到一堆方框上面，发现当 input 透明后就无法唤起键盘了

**Comment by acton393** [comment]
你是native的逻辑设置的opacity：0  还是we 脚本，
可以提供下不

**Comment by lmnsg** [comment]
@acton393  是 we 脚本
 .input-code {
        position: absolute;
        left: 0;
        top: 0;
        width: 580px;
        height: 100px;
        opacity: 0;
    }

                        <input class="input-code" oninput="inputCode" type="tel" autofocus="true" placeholder="请输入验证码">

**Comment by acton393** [comment]
@lmnsg  你设置了 opacity 为0 ， debug 看了一下， 它的视图的alpha 就变成了0， 根据[iOS开发文档](https://developer.apple.com/reference/uikit/uiview/1622469-hittest?language=objc)的描述， 当alpha 值小于0.01 的时候就不响应任何点击事件
