### ISSUE TITLE
如何获取input中输入的值？

### ISSUE THREAD

**Issue by myth2loki** [alibaba/weex#1792]
如何获取input中输入的值？

**Comment by misakuo** [comment]
可以监听input的`onchange`和`oninput`事件

**Comment by myth2loki** [comment]
@misakuo 试过了，oninput有用，但不知为何onchange没有反应。
我的代码如下：
<template>
    <scroller>
        <text style="font-size:60px; color:red" onclick="login">{{text}}</text>
	    <input id="username" type="text" autofocus="true" style="color: #666666;" 
                onchange="onChange oninput="onInput"/>
    </scroller>
</template>

<script>
    module.exports = {
        data: {
          text: 'login!!!!!',
	      username: 'hello '
        },
        methods: {
            login: function() {
               //login是我自定义的module，确定能正常运行
                var tm = require('@weex-module/login');
                tm.login(this.username, function(ret){
                    modal.toast({'message':ret, duration: 0.7});
                });
            },
            onChange: function(e) {
                this.username = e.value;
                var modal = require('@weex-module/modal');
                modal.toast({'message': e.value, duration: 1});
            },
            onInput: function(e) {
                this.username = e.value;
            }
        }
    }
</script>

**Comment by misakuo** [comment]
`onchange`事件目前依赖控件的焦点切换来触发，有一些小问题，下一个版本会提供稳定的实现，可以暂时用`oninput`替代一下

**Comment by myth2loki** [comment]
@misakuo 好的，多谢了！
