### ISSUE TITLE
weex 能否支持类似ES6的可变参数和默认参数

### ISSUE THREAD

**Issue by kfeagle** [alibaba/weex#1797]
weex 能否支持类似ES6的可变参数和默认参数

可变参数例子：
```js
function containsAll(haystack, ...needles) {
  for (var needle of needles) {
    if (haystack.indexOf(needle) === -1) {
      return false;
    }
  }
  return true;
}
```
我们来看一下调用containsAll("banana", "b", "nan")之后的函数调用过程，与之前一样，传递进来的第一个参数"banana"赋值给参数haystack，needles前的省略号表明它是一个不定参数，所有传递进来的其它参数都被放到一个数组中，赋值给变量needles。对于我们的调用示例而言，needles被赋值为["b", "nan"]

默认参数例子
```js
function animalSentence(animals2="tigers", animals3="bears") {
    return `Lions and ${animals2} and ${animals3}! Oh my!`;
}
```

默认参数的定义形式为[param1[ = defaultValue1 ][, ..., paramN[ = defaultValueN ]]]，对于每个参数而言，定义默认值时=后的部分是一个表达式，如果调用者没有传递相应参数，将使用该表达式的值作为参数默认值。相关示例如下：
```js
animalSentence();                       // Lions and tigers and bears! Oh my!
animalSentence("elephants");            // Lions and elephants and bears! Oh my!
animalSentence("elephants", "whales");  // Lions and elephants and whales! Oh my!
```

参考：http://www.infoq.com/cn/articles/es6-in-depth-rest-parameters-and-defaults

**Comment by cxfeng1** [comment]
把Native的实现思路也写一下， 以及考虑下三端一致性， 不一定要达到ES6的标准

**Comment by Jinjiang** [comment]
@kfeagle 目前主要是 iOS 里的 JavaScriptCore、Android 里的 v8 以及各主流手机浏览器对 ES6 的支持情况良莠不齐，所以没有办法直接在 runtime 下支持，不过 JavaScript 社区已经有工具 (比如 babel 或 buble) 可以把 ES6 的源代码转成 ES5 的生成码，然后就可以在 Weex JS Runtime 下运行了

**Comment by survivol** [comment]
testtest

**Comment by kfeagle** [comment]
可以js采用argments传参到native
native做支持
