### ISSUE TITLE
关于weex和原生交互 

### ISSUE THREAD

**Issue by Mhina007** [alibaba/weex#1799]
weex交互，除了JSCallBack，原生的能够主动调we的方法吗 ？

**Comment by misakuo** [comment]
see `WXSDKManager#fireEvent`

**Comment by acton393** [comment]
[globalEvent](http://alibaba.github.io/weex/doc/modules/globalevent.html)
可以在 js端增加事件， native直接fireGlobalEvent触发

**Comment by Mioke** [comment]
@misakuo fireEvent 怎么在weex端捕获？没有看见相关文档和用法

**Comment by SeongBrave** [comment]
@acton393 您好，我现在是用的vue，但是现在vue 还不支持 fireGlobalEvent吧？哪个版本回得到支持呢？

**Comment by alitong** [comment]
有没有实际列子可以参考啊？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
