### ISSUE TITLE
android上自定义view的渲染使用什么方法？

### ISSUE THREAD

**Issue by hello-li** [alibaba/weex#1801]
先用we文件实现一个简单页面，转换成js文件。然后在一个acitivity中，自定义一个view，在此view中使用WXSDKInstance.render()来渲染js文件。
实验一：在自定义view的初始化中调用render，发现并没有执行到onRenderSuccess；
实验二：在activity中new一下自定义view之后，强制调用render，执行到onRenderSuccess，但是js页面并没有显示；
实验三：在“实验二”结束后，强制刷新activity，js页面依然没有显示。
请问：能用什么方法和步骤，让自定义的view中能成功渲染js的页面？

**Comment by misakuo** [comment]
在js被render结束后，`IWXRenderListener#onViewCreated`会被回调，你只需要将回调参数中的View放到某个容器里就可以了（这个View就是js的渲染结果）

**Comment by hello-li** [comment]
感谢楼上解答！

**Comment by hello-li** [comment]
@misakuo 再请教一个问题，weex能直接渲染we文件吗，还是说只能渲染js文件？

**Comment by misakuo** [comment]
we文件最终是会被转换成js文件的，渲染的是js文件
