### ISSUE TITLE
Navigator 功能在 ios10.1.1 上不能使用,push a nwe page 显示空白界面

### ISSUE THREAD

**Issue by hf20** [alibaba/weex#1805]
Weex Playground 更新日期: 2016年10月31日 版本: 1.2

演示代码中【wxc-navpage，navigator】也不在能 ios10.1.1上使用，跳转后都显示：空白界面； 但在安卓端是正常的
wxc-navpage
http://alibaba.github.io/weex/cn/doc/components/wxc-navpage.html
navigator
http://alibaba.github.io/weex/cn/doc/modules/navigator.html

**Comment by Jinjiang** [comment]
@DoranYun 也一起看一下，包括新的文档描述是否准确
谢谢

**Comment by diytz** [comment]
同样遇到这个问题

**Comment by boboning** [comment]
这个问题在即将发布playground中修复，到时候请更新下。
