### ISSUE TITLE
是否可以为View添加backgroundImage以及渐变色

### ISSUE THREAD

**Issue by nc-theone** [alibaba/weex#1806]
* 现在有场景需要背景添加图片或者渐变的方式进行处理，请问如何才能实现？

**Comment by Hanks10100** [comment]
使用 `<image>` 标签可以实现背景图，用绝对定位控制好位置。渐变色目前还不支持，属于 CSS 较高级的属性了，现在也在讨论了，我们明确了解决方案后会实现的。

**Comment by Jinjiang** [comment]
渐变色我们先汇总到 #1494 了，谢谢
