### ISSUE TITLE
weex是否支持横屏

### ISSUE THREAD

**Issue by zmhuahua** [alibaba/weex#1807]
1.rt，横屏应用怎么办
2.是否可以考虑安卓使用dp，html中使用rem来解决适配问题

**Comment by Hanks10100** [comment]
横屏目前还不支持，不过我有个关于可配置 viewport 的 issue #421 ，已经着手实现了。 另外 `dp` 的话，参考 #1641 ，有计划支持多种 CSS 单位。

**Comment by Jinjiang** [comment]
横屏的问题我们先汇总到 #1494 了，谢谢
