### ISSUE TITLE
[Android]适配4.0.4系统用到globalEvent 初始化失败

### ISSUE THREAD

**Issue by samyzh** [alibaba/weex#1809]
12-03 19:24:49.621 28268-28330/      W/weex: app AvailMemory ---->>>58
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
 [WXBridgeManager] invokeCallJSBatch: framework.js uninitialized.
                                                             
                                                             [ 12-03 19:24:49.761   444:0xf09 E/         ]
                                                             notify_perfman failed, call init_perfman first!
                                                             
                                                             [ 12-03 19:24:49.761   444:0xf09 E/         ]
                                                             fopen failed: /dev/cpuctl/ux/tasks, No such file or directory
12-03 19:24:49.781 28268-28268/      W/dalvikvm: VFY: unable to resolve instance field 21320
12-03 19:24:50.021 28268-28330/      D/weex: weex JS framework from assets
12-03 19:24:50.061 28268-28330/      W/dalvikvm: VFY: unable to resolve virtual method 14789: Landroid/view/View;.setBackground (Landroid/graphics/drawable/Drawable;)V
12-03 19:24:50.421 28268-28268/      W/dalvikvm: VFY: unable to resolve virtual method 320: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
12-03 19:24:50.501 28268-28268/      W/dalvikvm: VFY: unable to resolve static method 14556: Landroid/view/Choreographer;.getInstance ()Landroid/view/Choreographer;
12-03 19:24:50.501 28268-28268/      W/dalvikvm: Link of class 'Lcom/oneapm/agent/android/core/background/ApplicationStateMonitor$4;' failed
12-03 19:24:50.501 28268-28268/      E/dalvikvm: Could not find class 'com.oneapm.agent.android.core.background.ApplicationStateMonitor$4', referenced from method com.oneapm.agent.android.core.background.ApplicationStateMonitor.e
12-03 19:24:50.501 28268-28268/      W/dalvikvm: VFY: unable to resolve new-instance 3904 (Lcom/oneapm/agent/android/core/background/ApplicationStateMonitor$4;) in Lcom/oneapm/agent/android/core/background/ApplicationStateMonitor;
12-03 19:24:50.501 28268-28268/      W/dalvikvm: VFY: unable to resolve virtual method 14557: Landroid/view/Choreographer;.postFrameCallback (Landroid/view/Choreographer$FrameCallback;)V
12-03 19:24:50.501 28268-28268/      W/dalvikvm: VFY: unable to resolve virtual method 14557: Landroid/view/Choreographer;.postFrameCallback (Landroid/view/Choreographer$FrameCallback;)V
12-03 19:24:50.501 28268-28268/      W/dalvikvm: Link of class 'Lcom/oneapm/agent/android/core/background/ApplicationStateMonitor$4;' failed
12-03 19:24:50.631 28268-28268/      W/dalvikvm: VFY: unable to resolve virtual method 1468: Landroid/os/StatFs;.getAvailableBlocksLong ()J
12-03 19:24:50.761 28268-28330/      D/jsengine: jsLog>>>>:START JS FRAMEWORK: 0.15.8 Build 20160909
12-03 19:24:50.761 28268-28330/      D/jsLog: START JS FRAMEWORK: 0.15.8 Build 20160909
12-03 19:24:51.051 28268-28269/      D/dalvikvm: GC_CONCURRENT freed 3453K, 34% free 8209K/12355K, paused 2ms+3ms
12-03 19:24:51.341 28268-28330/      D/jsengine: init JSFrm version 0.15.8
12-03 19:24:51.341 28268-28330/      D/weex_perf: [render time]initFramework:1291
12-03 19:24:51.341 28268-28330/      D/weex_perf: [render time]SDKInitTime:2099
12-03 19:24:51.341 28268-28330/      E/weex: [WXBridgeManager] execRegisterFailTask register module fail
12-03 19:24:51.341 28268-28330/     ###  E/weex: [WXBridgeManager] execRegisterFailTask register component fail

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
