### ISSUE TITLE
ios端依然尚未解决的上拉下拉问题

### ISSUE THREAD

**Issue by seascheng** [alibaba/weex#1810]
对于ios端长时间以来的上拉下拉问题，我测试了下>0.9.1的几个版本，已经优化很多。

不知道发版计划是什么，希望能尽快发布的dev branch和pod。。。这些问题的fix都望眼欲穿。

当**首次记录数少于一屏**时，还是有错误。
下图`ios-feature-20161208`分支playground 修改`list-basic.we`文件的rows为：
```
rows:[
        {id: 1},
        {id: 2},
      ],
```
明显看出，页面为了配合上拉，完全**下滑到底部**了。
![ios端上拉下拉问题](http://7xitzh.com1.z0.glb.clouddn.com/WechatIMG2.jpeg)

**Comment by chengweipeng123** [comment]
转到主分支issue

**Comment by cijianzy** [comment]
同

**Comment by cyan24** [comment]
同遇到这个问题，希望早日发版

**Comment by acton393** [comment]
这个问题是在1208 的分支还是dev 
麻烦提供一下  .we 的case，我试下

**Comment by chengweipeng123** [comment]
@acton393 1208分支和dev是都有的。

**Comment by acton393** [comment]
@chengweipeng123 

麻烦提供一下 .we 的case，我试下

**Comment by chengweipeng123** [comment]
@acton393 
不好意思，除了上面之前已经写的，我不是很理解.we的case还需要补充什么。
现具体描述如下：
1. 修改文件为：list-basic.we。即文件：[https://github.com/alibaba/weex/blob/dev/examples/component/list/list-basic.we](https://github.com/alibaba/weex/blob/dev/examples/component/list/list-basic.we)
2. 修改内容为：把rows变量有多个改为
```
rows:[
        {id: 1},
        {id: 2},
      ],
```
3. 修改完成后，使用ios playground查看，点击"list-basic"项。
4. 上拉界面或下拉界面。

case的reproduce很简单，并且应该是所有版本都有的。

如需其他信息，请详细告知。多谢。

**Comment by acton393** [comment]
#1896
