### ISSUE TITLE
weex集成到h5里面，部分图片会自动加.webp后缀，导致图片不显示。

### ISSUE THREAD

**Issue by hyqinloveslife** [alibaba/weex#1817]
集成的h5用谷歌浏览器打开的时候，会自动加上.webp后缀，然后图片就报404错误。
有时候审查元素，图片链接是正确的，但依然不显示。而且不报错。

**Comment by MrRaindrop** [comment]
能不能贴个出错的demo，另外你使用的是哪个版本的weex-html5？

**Comment by hyqinloveslife** [comment]
1.集成后的html文件。
### 
<!DOCTYPE html>
<html>

	<head>
		<meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" charset="utf-8" />
		<meta charset="UTF-8">
		<title>weex ceshi</title>
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black" />
		<meta name="apple-touch-fullscreen" content="yes" />
		<meta name="format-detection" content="telephone=no, email=no" />
		<style>
			html body #weex {
				width: 100%;
				/*height: 100%;*/
				background: #EEEEEE;
				margin: 0;
				padding: 0;
			}
		</style>
		<script src="//g.alicdn.com/mtb/lib-flexible/0.3.4/??flexible_css.js,flexible.js"></script>
		<script src="//g.alicdn.com/weex/weex-html5/0.3.2/weex.min.js"></script>
	</head>

	<body>
		<div>
			<p>hello world</p>
		</div>
		<div id="weex"> </div>
	
		
		<script>
			(function() {
				function getUrlParam(key) {
					var reg = new RegExp('[?|&]' + key + '=([^&]+)');
					var match = location.search.match(reg);
					return match && match[1];
				}
				var loader = getUrlParam('loader') || 'xhr';
				var page = getUrlParam('_wx_tpl') || 'js/weex/test.js';
				
				window.weex.init({
					appId: location.href,
					loader: loader,
					source: page,
					rootId: 'weex'
				});
				
		
			})();
			
			
		</script>
	</body>

</html>
### 

2.这是我集成的weex，贴.we文件
**
<template>
	<container>
		<image src="{{img}}" class="img"></image>
		<img src="http://aglhzmall.image.alimmdn.com/files/gouwuche.png?t=1481698951516" class="img"></container>
	</container>
</template>
<style>
	.img{width: 400;height: 400;}
</style>
<script>
	module.exports={
		data:{
			img:'http://aglhzmall.image.alimmdn.com/files/gouwuche.png?t=1481698951516'
		}
	}
</script>
**

**Comment by hyqinloveslife** [comment]
上面的标签怎么直接变成图片了？
原来的代码应该是这样的：

> <template>
	<container>
		<image src="{{img}}" class="img"></image>
		<img src="http://aglhzmall.image.alimmdn.com/files/gouwuche.png?t=1481698951516" class="img"></container>
	</container>


> </template>
<style>
	.img{width: 400;height: 400;}
</style>
<script>
	module.exports={
		data:{
			img:'http://aglhzmall.image.alimmdn.com/files/gouwuche.png?t=1481698951516'
		}
	}
</script>

**Comment by MrRaindrop** [comment]
看你的入口页面，引用的是 alicdn 的版本，仅适用于阿里内部开发，目前对图片都统一做了处理，在支持 webp 的平台上都会使用 cdn 的 webp 后缀。
