### ISSUE TITLE
如何自定义音频组件

### ISSUE THREAD

**Issue by echoyoung46** [alibaba/weex#1823]
因为没有 audio 标签，所以想自定义一个音频组件，用 video 来加载资源，自定义样式。
想要可以拖拽进度条来控制播放进度，但是 video 标签只提供了 play-status 来控制播放/暂停，没有类似 duration/currentTime 的属性来获取播放时间。
那么应该如何实现这个需求？

**Comment by Jinjiang** [comment]
支持一下这个建议，我觉得我们可以再多讨论一下

**Comment by echoyoung46** [comment]
@Jinjiang 好的，比如说？

**Comment by Jinjiang** [comment]
本质上 audio 是个非视图的东西，也许做成 module 更合适而不是 component
