### ISSUE TITLE
content 不能是cell的子节点吗

### ISSUE THREAD

**Issue by sliu1126** [alibaba/weex#1827]
<cell repeat="{{lists}}">
            <content>
            </content>
  </cell>

这种写法不支持吗

**Comment by Jinjiang** [comment]
应该是因为 cell 只支持 append="tree" 导致的吧？ @cxfeng1 确认一下吧，另外这块文档可能需要加上必要的提示 @DoranYun

**Comment by cxfeng1** [comment]
@sliu1126  content是指什么， 麻烦给个demo
