### ISSUE TITLE
在iOS 设备上，突然所有的动画都没了

### ISSUE THREAD

**Issue by totzcc** [alibaba/weex#1831]
在iOS 设备上，突然所有的动画都没了，有人遇到过这个问题吗？

比如。Navigator 的过渡动画
UIAlertController的弹出动画

![](http://p1.bpimg.com/567571/beea4acadd05e29a.gif)

**Comment by cxfeng1** [comment]
@totzcc 重启模拟器试一下， 感觉更像是系统和设备的问题

**Comment by totzcc** [comment]
@cxfeng1 我在真机上也会出现这样的问题

**Comment by acton393** [comment]
@totzcc 未知失败是哪弹的..

**Comment by totzcc** [comment]
@acton393 不好意思。这个未知失败不是这个问题出现的，让你费解了。这是我自己请求接口的错误

**Comment by totzcc** [comment]
这个问题影响到的不止Weex 的动画没有了。
我自己写的UIAlertController 弹出的过渡动画也没了

**Comment by acton393** [comment]
@totzcc  你试重新写一个简单的demo看下系统的那那些动画， 还在不， 在模拟器选项中打开showanimation

**Comment by totzcc** [comment]
这个问题太难重现了；我在Gitter.im 上也听说有一个人遇到了我这样的情况
@sliu1126

我尝试找到重现的规律。弄一个demo来复现这个问题

**Comment by george-luofz** [comment]
同样遇到这个问题，暂未找到复现办法

**Comment by liujianying** [comment]
表示官方demo 有时候也会遇到这个问题,动画全部消失,不过这个现象很少看见

**Comment by WildDylan** [comment]
系统版本是多少？ iOS 9.3 ？

**Comment by totzcc** [comment]
iOS 10.2。10.1


发自网易邮箱大师
在2016年12月23日 18:57，Dylan 写道:

系统版本是多少？ iOS 9.3 ？

**Comment by totzcc** [comment]
我发现当动画消失后。modal 的toast也不见了

**Comment by totzcc** [comment]
在最新的 iOS SDK 0.9.4 依然存在这个问题

**Comment by totzcc** [comment]
我成功100%复现了这个问题
复现步骤： 
反复的push pop

[复现Demo下载地址](https://share.weiyun.com/b69719fa1ee6efdd2d745203e3f75b05)

![](http://p1.bqimg.com/567571/b566dc787794c48e.gif)

**Comment by funnyN7** [comment]
```
[UIView setAnimationsEnabled:YES]
```
设置这个，亲测可以解决问题，出现这个情况是系统把应用的动画给强行关闭了，原因不知

**Comment by acton393** [comment]
hi @totzcc 我会用你的demo 检查一下，做后续回复

**Comment by acton393** [comment]
@totzcc  试了一下，应该是由于在有些非主线程中操作UI导致， 已经修复了， 下个新版本会发布， 也可以尝试 iOS-feature-20170118 分支

**Comment by totzcc** [comment]
好的。感谢


发自网易邮箱大师
在2017年01月11日 14:35，acton393 写道:

@totzcc 试了一下，应该是由于在有些非主线程中操作UI导致， 已经修复了， 下个新版本会发布， 也可以尝试 iOS-feature-20170118 分支
