### ISSUE TITLE
flex布局不支持justify-content:space-around;

### ISSUE THREAD

**Issue by dongnaebi** [alibaba/weex#1832]
感觉这个也是很常用很重要的，希望得到支持。另外文档的可选值没有space-around，图片上却有。。。

**Comment by Jinjiang** [comment]
目前三端比较难统一展示这个效果，我们暂时汇总到 #1494 吧
谢谢

**Comment by Jinjiang** [comment]
cc @DoranYun 留意一下文档的描述
谢谢
