### ISSUE TITLE
列表中loading样式问题

### ISSUE THREAD

**Issue by Jam1zhu** [alibaba/weex#1835]
![wechatimg1](https://cloud.githubusercontent.com/assets/21252750/20999776/f9310a88-bd51-11e6-9668-8d03cef11f26.jpeg)
当内容不能撑满一屏的时候，触发loading标签的onloading事件，会把内容强行推拽到底边，如上图。有谁遇到相似的问题吗？还是我的代码有问题。

**Comment by sospartan** [comment]
能贴一下你相关的代码么
