### ISSUE TITLE
[ios 依然没有提供 presentViewcontroller]

### ISSUE THREAD

**Issue by HJ-StevenSun** [alibaba/weex#1836]
A - B 
界面如下

A 朋友圈界面
![33238a58-7389-46b9-9547-1de6a60a32c1](https://cloud.githubusercontent.com/assets/20534672/21001516/adeb8418-bd5b-11e6-85c3-a2aee4b91d1b.png)

B 上传朋友圈界面
![77bacafe-326e-4fa2-8327-045c50390725](https://cloud.githubusercontent.com/assets/20534672/21001537/e1013f46-bd5b-11e6-820f-66edb01ad59e.png)

A 已经上传成功以后的朋友圈界面
![7ef93cb7-742f-4624-a486-2e3278e06203](https://cloud.githubusercontent.com/assets/20534672/21001569/156e4b3e-bd5c-11e6-8011-22303244a331.png)

由于是 Push 过来的页面 当我左滑返回时会再次出现  B 上传朋友圈的界面 ， 然后左滑 返回到 A 没有上传新的朋友圈的界面。

我不知道我是否表达清楚，意思就是 B 发表朋友圈界面只是一个功能业 只需要出现一次，然后刷新 A 界面就可以了。这个需要PresentViewController 方法来实现。 刚刚查看了0.9.0 的版本也没有考虑到这个功能，所以我来提个需求。这个需求我很久以前就提到过得。使用 push 一个方法照顾不到所有的界面逻辑。

**Comment by acton393** [comment]
hi 这个暂时先关掉了， 如果业务需要的话，可以做一下native的扩展， 同时也欢迎提pr，谢谢~
