### ISSUE TITLE
dom.scrollToElement在h5下没有效果

### ISSUE THREAD

**Issue by hezhirong** [alibaba/weex#1838]
dom.scrollToElement(el, {
        offset: 0
})
在h5上没效果
官方文档示例：http://dotwe.org/3c05750fb1af58764dc9d54d4b51637f

**Comment by Jinjiang** [comment]
感觉是 list 作为根节点的时候才可以
http://dotwe.org/02c8dc3212f8401bbb0801f8ad457bca 这个 demo 是工作的
我们想办法处理一下
谢谢反馈

**Comment by MrRaindrop** [comment]
这里的滚动没有生效，原因是 list 没有设置高度。weex-h5 里 list 只有作为根元素且没有设置高度时才会添加 100% 的高度，如果是作为子元素则需要添加一个高度才能滚动。主要原因是在 web 的文档模型里，块元素的高度在不指定的情况下默认是由内容决定的，而不是其父元素的可容纳高度决定的。这个后续需要进一步讨论，以保证三端一致的体验，目前可以绕过的办法就是设置一个高度。

**Comment by 452MJ** [comment]
H5的话直接调用window.scrollTo(x, y);就可以自由滑动。xy的值可以用dom来计算
