### ISSUE TITLE
dom module使用疑问

### ISSUE THREAD

**Issue by pp1232** [alibaba/weex#1844]
看到dom module里有关dom操作的方法，但是没有在任何地方找到使用的示例，有没有谁用过相关功能的，请求提供下使用示例，
相关函数中，特别是createBody，addElement，moveElement
其中的element对象应该如何创建，index如何设置

**Comment by ctyytc** [comment]
确实需要示例，目前的例子实在看不太懂。

**Comment by Jinjiang** [comment]
DOM module 中的 API 不是提供给开发者直接使用的，是底层 JS bridge 通信原理的一部分，文档里知会做一些简单的说明，想了解底层实现原理可以多看看我们的源代码
接下来我们在文档上会弱化这些描述，避免给开发者带来困扰
请谅解

cc @DoranYun
