### ISSUE TITLE
<text> 标签中去除了左右空格，导致了不能首行空格

### ISSUE THREAD

**Issue by totzcc** [alibaba/weex#1849]
text 标签是不是替我们做了去除左右空格啊？
我遇到了这么一个问题。。我想首行空格，结果做不到了

![](http://p1.bqimg.com/567571/8bdc6e9a20e8a31e.png)

![](http://i1.piimg.com/567571/b8cd04cd21e1f5d3.png)

**Comment by Jinjiang** [comment]
感谢，我们记录一下这个问题，针对这种使用场景我们想想更好的设计

**Comment by totzcc** [comment]
感谢给出的idea 现在使用这样的方案来解决这个问题
![临时解决方案](http://i1.piimg.com/567571/5dccf3c814d4e902.png)

**Comment by Jinjiang** [comment]
恩，但这种解法并不优雅，我们再想想看更好的设计

**Comment by sunzhongliangde** [comment]
如果有text-indent 这样的css属性支持就好了

**Comment by Jinjiang** [comment]
恩，我先汇总到 #1494 然后认真考虑一下
谢谢
