### ISSUE TITLE
[Android]bug APP升级部分手机渲染错误,callAddElement is not defined

### ISSUE THREAD

**Issue by samyzhang** [alibaba/weex#1851]
Andriod APP从没有用Weex的升级到用Weex项目的apk，在部分手机（Vivo Y51A和魅蓝5）上渲染.weex界面报错；等清理掉数据库缓存后，又好了；
![image](https://cloud.githubusercontent.com/assets/10821317/21041855/cada4d66-be28-11e6-842b-8ceaa6484dce.png)
跟踪信息是，exeJs调用jni渲染template错误；不知道是怎么导致的？

**Comment by Jinjiang** [comment]
callAddElement 是一个比较新的 JS 接口，想确定一下你的 WeexSDK 版本是多少？

**Comment by samyzhang** [comment]
发现，之前我描述的有点问题。是之前APP用的低版本weex0.7多的版本,升级后APP用的是0.8.0.2版本。我这边是直接用的官方的SDK,没有做编译处理；初步分析是在部分手机（Vivo Y51A和魅蓝5），升级后libweexv8.so没有被替换掉，还是用的原来的低版本的，没有callAddElement方法，要清理数据库和缓存后，再次启动APP,新的libweexv8.so才会写入进去；
问题：现在有没有什么什么方式去清理更新指定的.so文件？也还是weex会提供相关的方法？

**Comment by sospartan** [comment]
@samyzhang 你说的问题与weex没有直接联系，是一个android领域的问题，可能与你们的升级、安装方式的有关。由于没有更多反馈这个问题的issue，在这里不做继续讨论了。
