### ISSUE TITLE
Android手机上面发现微信和百度浏览器、UC浏览器内核不支持weex生成的h5页面显示，很奇怪的bug。

### ISSUE THREAD

**Issue by alex1226** [alibaba/weex#1855]
使用weex helloworld.we 生成h5web页面，按照地址http://172.17.6.139:8081/weex_tmp/h5_render/?page=helloworld.js生成二维码。用Android手机上面的微信（版本号6.3.31）扫描二维码发现只能显示标题，不能显示内容。用手机百度（版本号7.4）也是一样，UC浏览器也试试也不行。  用Android手机上的360浏览器、Chrome浏览器都是可以的。难道Android手机上面的微信和百度浏览器内核都不支持weex生成的h5页面吗？跟踪不到h5代码运行，没办法知道故障到底在哪，用的是中兴天机和三星galaxy note3。  对比测试了一下，在iphone上面微信和百度都是可以的，可能是iOS平台上强制统一浏览器内核所致。 在PC Window平台上面浏览器都是可以的。盼请验证并尽快修复这个bug。

**Comment by alex1226** [comment]
最简单的helloworld we代码：
<template>
  <div>
    <text style="font-size:100px;"> hello world </text>
    <input >
  </div>
</template>

<script>
  module.exports = {
    data: {
      Title: 'hello word from weex',
    },
  }
</script>

**Comment by MrRaindrop** [comment]
这个还需要具体定位一下问题，可能是内核渲染兼容问题，也可能是报错。你可以试着用 `window.onerror ` 把错误 alert 出来，如果有报错的话。另外，你的 weex-toolkit 版本是多少？

**Comment by fkysly** [comment]
麻烦提供一下以下信息：
1. weex-toolkit 的版本是多少，可以通过运行 weex --version 获取版本信息。
2. .we 文件 以及对应编译出来的 .js 文件源码，建议粘贴到 gist.github.com ，我们可以运行分析一下。
3. 可以使用 window.onerror 方法定位出错信息；也可以使用 chrome 自带的远程调试安卓手机浏览器的功能看一下报错信息，然后贴给我们。

**Comment by alex1226** [comment]
看了一下 装的是两三个月前的版本0.4.9 更新到最新的0.6.3就好了 谢谢！

**Comment by alex1226** [comment]
node4.4版本 weex-toolkit 0.4.9版本 可能是weex-toolkit版本太旧了
