### ISSUE TITLE
关于计时器countdown

### ISSUE THREAD

**Issue by Eric-ss** [alibaba/weex#1856]
![1](https://cloud.githubusercontent.com/assets/22341907/21044132/512deb14-be35-11e6-9b82-8e74be6bd598.png)
![2](https://cloud.githubusercontent.com/assets/22341907/21044135/51d65c86-be35-11e6-8a0a-02d176a397fa.png)
想完成一个类似验证码倒计时的功能，获取后例如60s后还可以获取，参考了一下countdown-demo  
1.发现如果隔几秒手动触发倒计时的话，它依然是在页面加载进去就开始倒计时。
2.找不到有关countdown的文档。比如在它计时结束后，想再给它赋值再让它重新倒计时，不知道如何重置时间再执行。
3.如果用setInterval一秒执行一次自减1的话，视图不会更新

**Comment by fkysly** [comment]
这个 countdown-demo 仅仅是实现了一个非常基础的，页面加载倒计时的功能，你可以不基于这个，重新写自己的倒计时组件的。

**Comment by Jinjiang** [comment]
@Eric-ss 解释一下：现在有了 HTML5 Timer APIs 的支持，可以自由定制倒计时的效果了，之前我们做 countdown 的时候一方面是作为示例展示能力，另一方面是 Weex 再早的版本时没有 HTML5 Timer APIs，只能通过一个 native 的 `<countdown>` 组件来做倒计时，所以这个文件可以做到向下兼容。

**Comment by Jinjiang** [comment]
http://dotwe.org/2561fcc8d75321b410f43db8eec0ba2b
直接参考这个吧

**Comment by Eric-ss** [comment]
@Jinjiang 好的，谢谢
