### ISSUE TITLE
[html5] onviewappear事件

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1857]
onviewappear事件 在 ios 端是好用的，在浏览器端无法触发，

http://dotwe.org/450205a8f8612381422220ce88a562ff
这个是官方中文文档上的对于这个事件的试一试链接，发现也是无效的。

**Comment by DoranYun** [comment]
目前 H5 暂时不支持 viewappear 和 viewdisappear 这两个事件，我在文档中补充说明一下。
