### ISSUE TITLE
一个非官方的国际化解决方案

### ISSUE THREAD

**Issue by totzcc** [alibaba/weex#1858]
近期在弄Weex 的国际化。官方没有提供国际化的方案
我自己是用这样的方式来实现的。可以临时解决我的问题。希望官方能够提供一个推荐的解决方案

解决思路
1.定义一个全局的变量global，每个we都引入他
2.将global 放进 we 文件的data
3.利用data中值变回会触发渲染的原理，在延迟100ms 后改变global的lang方法
4.done, 页面重新渲染，实现国际化

demo 的文件
[Weex i18n.zip](https://files.gitter.im/weexteam/cn/0CFO/weex---i18n.zip)

global.js
```javascript
var environment = {
	language:"en" //改变这里的值。来切换中英文
}
var langFiles = {
	en:require("./i18n/en.js").lang
}
exports.lang = function(key) {
	return "";
}
setTimeout(function(){
	exports.lang = function(key) {
		if (environment.language == "en") {
			return langFiles.en[key] || "not find";
		}
		return key;
	}
},100);
```

i18n/en.js
```javascript
var lang = {
	"首页":"Home",
	"经纪人":"Agent",
	"指标":"Target",
	"我的":"My",
}
exports.lang = lang;


```
i18n.we

```html

<template>
	<div style="justify-content: center;align-items: center;">
		<text>{{global.lang('首页')}}</text>
	</div>
</template>
<script>
	var global = require("./global.js");
	module.exports = {
		data:{
			global:global
		}
	}
</script>
```

**Comment by Jinjiang** [comment]
也许未来可以通过 JS Service #1938 建立一层这样的机制

**Comment by Jinjiang** [comment]
国际化的问题我先汇总到 #1494 这段时间没有更多讨论，这里我先关掉了
感谢

**Comment by zkluna** [comment]
老哥，这个方法确实可以，但是要怎么动态的切换语言？ 还有老哥有没试过vue-i18n，iOS模拟器运行的时候会报错啊？是不是我用的姿势不对？

**Comment by 354018894** [comment]
哥，这个方法确实可以，但是要怎么动态的切换语言？

**Comment by 354018894** [comment]
我然后改了：
exports.language=function(es){
	var environment = {
		language:es 
	}
	return environment
};

var langFiles = {
	en:require("./en.js").lang,
	// zh:require("./zh.js").lang
}
exports.lang = function(key) {
	return "";
}
setTimeout(function(){
	exports.lang = function(key) {
		if (exports.language == "en") {
			return langFiles.en[key] || "not find";
		}
		return key;
	}
},100);
