### ISSUE TITLE
用weex写页面时前端后台遇到的小问题

### ISSUE THREAD

**Issue by VeritasDada** [alibaba/weex#1862]
写前端时：
<style>中文字等元素的改变不支持；css中的百分比无法使用；
<br/>
写后台时：<br/>
不支持引入外源库jquery；

**Comment by Hanks10100** [comment]
关于 `<style>`

目前 Weex 的布局是由 Native 计算出来的，并非 Web 端，支持的 CSS 样式属性有限。我们会不断扩充支持的属性，百分比我们也会尽量支持。

关于 jQuery

DOM 是 web 中的概念，Weex 的运行环境不止 web ，在手机中都是原生视图，没有所谓的 DOM ，不支持 DOM 操作，当然也不支持用 jQuery。
