### ISSUE TITLE
单独定义一个activity 页面跳转就有问题？ 用weexpack生成的可以正常跳转，什么回事？

### ISSUE THREAD

**Issue by spiritelf** [alibaba/weex#1864]
package com.github.zhoukekestar.weexquickstart;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Toast;

import com.taobao.weex.IWXRenderListener;
import com.taobao.weex.WXSDKInstance;
import com.taobao.weex.common.WXRenderStrategy;
import com.taobao.weex.utils.WXFileUtils;

public class MainActivity extends Activity implements IWXRenderListener  {

    private static final String TAG = "MainActivity";
    private static WXSDKInstance mInstance;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mInstance = new WXSDKInstance(this);
        mInstance.registerRenderListener(this);

        // WeexSDK 0.5.1
//        mInstance.render("WeexQuickStart", WXFileUtils.loadFileContent("weex/index.js", this), null, null, -1, -1, WXRenderStrategy.APPEND_ASYNC);

        // WeexSDK 0.8.0.1
        mInstance.render("WeexQuickStart", WXFileUtils.loadAsset("dist/login.js", this), null, null, -1, -1, WXRenderStrategy.APPEND_ASYNC);
       // mInstance.render("WeexQuickStart", WXFileUtils.loadAsset("weex/index.html", this), null, null, -1, -1, WXRenderStrategy.APPEND_ASYNC);
    }

    @Override
    public void onViewCreated(WXSDKInstance wxsdkInstance, View view) {
        Log.v(TAG, "onViewCreated");
        setContentView(view);
        Toast.makeText(MainActivity.this, "onViewCreated", Toast.LENGTH_LONG).show();
    }

    @Override
    public void onRenderSuccess(WXSDKInstance instance, int width, int height) {
        Log.v(TAG, "onRenderSuccess");
        Toast.makeText(MainActivity.this, "onRenderSuccess", Toast.LENGTH_LONG).show();
    }

    @Override
    public void onRefreshSuccess(WXSDKInstance wxsdkInstance, int i, int i1) {
        Log.v(TAG, "onRefreshSuccess");
        Toast.makeText(MainActivity.this, "onRefreshSuccess", Toast.LENGTH_LONG).show();
    }

    @Override
    public void onException(WXSDKInstance instance, String errCode, String msg) {

        Log.v(TAG, "onException errCode:" + errCode + " msg:" + msg);
        Toast.makeText(MainActivity.this, "ERROR  errCode:" + errCode + " msg:" + msg, Toast.LENGTH_LONG).show();
    }
}

**Comment by spiritelf** [comment]
NetWork Error!
1.make sure you use the comman npm run serve launched local service
2.make sure you modify you_current_ip to you local IP in WXMainActivity

**Comment by ambitionJz** [comment]
当时我也遇到了  看下wxpage这个类

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
