### ISSUE TITLE
dpr=3的分辨率下，env.deviceWidth的问题。

### ISSUE THREAD

**Issue by dongnaebi** [alibaba/weex#1866]
`var height = 88 * 750 / env.deviceWidth`
在iPhone 7 plus或者其他3倍像素比的安卓机子下，`env.deviceWidth`获取到的值有点乱。
比如按照以上代码，要布局一个实际高88的导航栏，在7plus下deviceWidth的值按理应该是828才对，可是实际得到的是1000多。导致`88 * 750 / env.deviceWidth`在3倍像素比的机器显示不正常。
看了其他issues，应该是iphone 4等1倍像素下也有问题。
建议：①把3倍和1倍屏幕下的deviceWidth也改成和2倍的一样？②env里再加一个`pixelRadio`用以计算？

**Comment by cxfeng1** [comment]
`env.deviceWidth` 和 `env.deviceHeight` 给的是真实物理像素(px)， iPhone 7 plus 是 `1242x2208`， 如果想要得到PT值， 只需  `env.deviceWidth/env.scale`.

**Comment by dongnaebi** [comment]
env.scale只有iOS有啊

**Comment by YorkShen** [comment]
* android的导航栏（actionbar）的高度是由theme指定的，不同theme下高度不一样，一个activity对应于个theme，同一个theme可能对应多个activity。
* 导航条的高度单位是dp，dp与真实像素（px）的换算关系是由dpi决定的，不同手机不一样。
* weex android这里只返回了屏幕的像素宽度。
@dongnaebi

**Comment by YorkShen** [comment]
Fix by https://github.com/sospartan/weex/pull/98
