### ISSUE TITLE
【android tag-0.8】  <silder-neighbor> index属性不起作用 

### ISSUE THREAD

**Issue by YanyeZhang** [alibaba/weex#1867]
WXSilderNeighbor继承自WXSilder但是其index 属性却不起效果，虽然代码走进去了。但是没有生效

**Comment by YanyeZhang** [comment]
[test.we.zip](https://github.com/alibaba/weex/files/645319/test.we.zip)
以上文件为改自官方demo的

**Comment by YanyeZhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8480050/21092552/11c8ff5e-c088-11e6-8dd6-82e21b845157.png)
去掉以上的标记行数，则功能正常

**Comment by acton393** [comment]
hi @YanyeZhang  thx 反馈~，这个是已知bug，我们Android的同学会fix掉

**Comment by YanyeZhang** [comment]
已经找内部的人fix了
