### ISSUE TITLE
IOS 上 animation 设置元素的 width 和 height 都无效

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1871]
亲测，同样的代码在 html 上是 ok 的

**Comment by cxfeng1** [comment]
@lmnsg 示例代码有么？

**Comment by Jinjiang** [comment]
http://alibaba.github.io/weex/cn/doc/modules/animation.html
@lmnsg 参考这里 width/height 的例子
如果仍有问题可以再开 issue 并附上可重现的 demo
谢谢

**Comment by pinguo-liangyunzhu** [comment]
给dom上加width或者height初始样式至少要是1px，动画就能生效了，不能给0
