### ISSUE TITLE
[html5] 扩展globalEvent，回调只执行一次

### ISSUE THREAD

**Issue by dongnaebi** [alibaba/weex#1872]
文档看的不太懂，自己试着写，不知道写法对不对。
index.html
```javascript
var scrollEvent = new Event('iscroll');
document.addEventListener("touchmove",function(e){
    var scroller=document.querySelector(".scroller-element");
    var distance=scroller.style.transform;
    scrollEvent.distance = distance;
    document.dispatchEvent(scrollEvent);
});
```
main.we
```javascript
globalEvent.addEventListener("iscroll", function (e) {
   console.log(e);
});
```
如上代码，touchmove滚动的时候只打印了一次。

看了globalEvent.js，好像也只是把事件转移到document，于是自己在console里写
```javascript
document.addEventListener("iscroll",function(e){
    console.log(e)
});
```
滚动的时候能正常打印。

看了很多代码，也只能想到这样来实现滚动的监听，还出了问题。不知道有没有更好的办法？

**Comment by MrRaindrop** [comment]
h5 的 globalEvent 的回调，调用的时候没有开启 keepAlive，所以监听是一次性的。后续我们这边需要考虑一下监听的时候是否需要设置这个参数. 另外 list 的 scroll 事件目前没有透出出来，这个是组件设计上的问题，下个版本三端会考虑加上这个事件.

**Comment by MrRaindrop** [comment]
https://github.com/alibaba/weex/pull/1944 添加了 keepAlive 参数，可以持续监听这个事件了.
