### ISSUE TITLE
deviceHeight 不准确

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1873]
deviceHeight 不准确，在 ios 和 html5上， 在6plus 得到的值大概是真实屏幕高度是2倍

sdk: 0.8.0

**Comment by cxfeng1** [comment]
@lmnsg  这里给的是真实物理像素数， 如6plus为736*3

**Comment by lmnsg** [comment]
@cxfeng1 但是这就带来一个问题， 这里的真实物理数据和 weex 的布局所用的宽高不一致，需要换算，这样就需要额外的计算代码去做同一件事情，这里可否优化一下呢，   不然如何三端通用呢。。
而且也没有返回 每个设备对应的 倍数...  好难搞

**Comment by cxfeng1** [comment]
@lmnsg  换算公式可以参照 [FAQ](http://alibaba.github.io/weex/doc/faq.html#how-to-get-rid-of-750-adaption-and-calculate-widthheight-in-real-pixels？) ， 目前三端都是给的真实物理像素， 这里给真实像素也是为了让用户能够通过deviceWidth和deviceHeight脱离750PX适配的限制。

另外我们目前已经在支持 viewport  属性了， 可以自由地定制用于适配的屏幕宽度。

**Comment by lmnsg** [comment]
@cxfeng1 比如我要设置一个高度为整个屏幕的高。  怎么计算得出这个值呢？

**Comment by cxfeng1** [comment]
参照 FAQ 文档计算方式:  `env.deviceheight * 750 / env.deviceWidth`
