### ISSUE TITLE
希望weex支持一个css扩展，可以使用加减法计算

### ISSUE THREAD

**Issue by MatthewChen** [alibaba/weex#1875]

**Comment by Hanks10100** [comment]
在标准 CSS 中只有 `calc()` 中支持加减运算，但是 `calc()` 是实时计算布局，可能会存在性能问题。如果想更灵活的写样式，可以用 CSS 预处理器来写（Sass、Stylus 等）。

`weex-loader` 支持引入外部 css 文件，用法如下：

```html
<style src=".path/to/your.css"></style>
```

你可以用任意预处理器编译生成 `.css` 文件，然后通过上述方法引入。
