### ISSUE TITLE
Weex 组件高度计算的 BUG

### ISSUE THREAD

**Issue by jerrybendy** [alibaba/weex#1878]
你好，

最近发现一个 weex 在组件高度计算上的 BUG，具体如下：

Weex 要求将元素的所有尺寸使用 750px 来计算，例如高度 375px 实际渲染的结果将是实际设备宽度的 50%。这样就有可能会在宽度不等于 750px 的设备上计算出现小数。

例如：

```html
<div style="width: 750; height: 100;"></div>
```

在宽度为 750 的设备上（如 iPhone 6）实际计算的高度是 100px，但在 iPhone 5S 上实际计算的高度为 85.33px，即非整数。如果页面上有多个这样的被计算为高度非整数的元素相加，最终将会在某个不确切的位置出现 0.5px 到 1px 的缝隙。这条缝隙在背景色为深色时显得尤为明显。

不过这个 BUG 目前只在 iOS 设备上遇到，在 iPhone 5S 及 iPhone 6/7 Plus 上更为频繁。

附上一段问题重现的代码，代码中设置 `scroller` 的背景色为蓝色，每行一个高 100 的白色色块。在 iOS 设备上每隔几行就会看到一条明显的蓝色线条。

```html
<template>
    <scroller style="background-color: blue;">
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
    </scroller>
</template>

<style>
    .row {
        background-color: #FFFFFF;
        width: 750;
        height: 100;
    }
</style>
```

**Comment by cxfeng1** [comment]
@jerrybendy  这个是已知问题， 750px适配后像素四舍五入带来的精度丢失。 目前没有太好的办法， 一般是在背景色上做处理。

后面会加入viewport的概念， 允许自定义用于适配的宽度，而非固定750， 如可以设置"device-width"，这样适配后的像素小数会相应减少， 这个问题会有所好转。

**Comment by jerrybendy** [comment]
是否可以把四舍五入的计算统一为向下取整或向上取整，不知这样能否避免一些计算上的误差

**Comment by cxfeng1** [comment]
@jerrybendy  都会有类似的问题， 举个例子:

一个div容器的高度是4px， 里面有三个元素 `flex:1` 均分这个高度， 即都为 1.33333px。
 如果向下取整， 容器会空1px出来， 如果向上取整， 容器会超出2px。

**Comment by jerrybendy** [comment]
嗯，是的，抱歉没有考虑到这种固定容器高度的情况。这样说来也确实没有什么太好的解决办法呀。

我现在的处理方式是在背景区域额外再加一个白色的底，这样就可以隐藏掉多出来的线条，但仅在页面底色是白色是有效。如果页面底色并非白色的话仍然会看到白色的线条（好在背景非白色的情况在我们的应用中并不多见）

**Comment by cxfeng1** [comment]
@jerrybendy  暂时先这样处理吧， 后面我们也在考虑更深层次的解决方案。

**Comment by jerrybendy** [comment]
嗯，好的，感谢你们的付出 😊
