### ISSUE TITLE
who use weex?

### ISSUE THREAD

**Issue by edouard-lopez** [alibaba/weex#1881]
Hi,
Your project look promising, thanks for the work.

I see no information on **who is using weex in production environment?** React Native has a [dedicated page for that](https://facebook.github.io/react-native/showcase.html).

This would provide additional credibility to your project.

**Comment by Hanks10100** [comment]
Sorry about that, we are also collating those informations. At least TaoBao and Tmall are using Weex in production.

Our new website would have a showcase page, please look forward : ）

**Comment by lee134134134** [comment]
![a0dbaed216293c012f92232765f81ac6](https://cloud.githubusercontent.com/assets/4250254/21922999/9a77cff0-d9ac-11e6-94cd-c6a65f9685ad.jpg)


中青旅遨游   应用与app融合页面

**Comment by qddegtya** [comment]
![2017-01-16 11 10 39](https://cloud.githubusercontent.com/assets/773248/21969857/93fde146-dbdc-11e6-8c45-2e56af863879.png)

** Alibaba.com with PWA / Weex&Rax**
