### ISSUE TITLE
android ScrollView 嵌套EditTextView 滑动问题

### ISSUE THREAD

**Issue by aosting** [alibaba/weex#1883]
我们使用Textarea 被嵌套了ScrollView中，有滑动冲突。
我在Textarea 中appleStyleAfterCreated 后面添加 editText.setOnTouchListener(new View.OnTouchListener() {
          @Override
          public boolean onTouch(View v, MotionEvent event) {
              v.getParent().requestDisallowInterceptTouchEvent(true);
              if (event.getAction() == MotionEvent.ACTION_UP) {
                  v.getParent().requestDisallowInterceptTouchEvent(false);
              }
              return false;
          }
      });来支持滑动。

这个地方有新发布和编辑功能。当文章内容超出输入框高度的时候。
新发布的到没问题，编辑功能失败。
查看是因为在WXEditText
 @Override
  protected void onSizeChanged(int w, int h, int oldw, int oldh) {
    super.onSizeChanged(w, h, oldw, oldh);
    int contentH = getLayout().getHeight();
    //TODO: known issue,set movement to null will make cursor disappear.
    if(h < contentH){
      setMovementMethod(null);
    }else{
      setMovementMethod(getDefaultMovementMethod());
    }
  }

中   setMovementMethod(null); 

请问，问什么要设置这个 setMovementMethod(null);

**Comment by sospartan** [comment]
最新的0.9版本已经解决这个冲突问题。

**Comment by aosting** [comment]
我这边的issues 有两个问题。
1 Textarea嵌套的滑动冲突问题。（0.9 已经修复）
2 Textarea 初始化的时候内容高度>控件高度的时候不能滑动问题。场景如截图中评论被拒绝后，再次编辑！（0.9 未修复）

我是在textarea中添加这块代码来解决的。
    editText.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
      @Override
      public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
        if (v.canScrollVertically(-1) || v.canScrollVertically(0)) {
          EditText view = (EditText) v;
          if (view.getMovementMethod() == null) {
            view.setMovementMethod(ArrowKeyMovementMethod.getInstance());
          }
        }
      }
    });

对WXEditText 中
if(h < contentH){
setMovementMethod(null);
}不清楚为什么要这样设置？？


![Uploading Screenshot_20161228-112058.jpg…]()
![Uploading Screenshot_20161228-112355.jpg…]()
