### ISSUE TITLE
scroller 在 ios 上的问题 

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1884]
当 scroller 内部元素的高度低于 scroller 的高度的时候, scroller 无法滑动，也就无法触发下拉刷新操作。
html5 端测试发现是可以下拉的

List（IOS 端） 在同样情况下可以下拉，但是很诡异..  无论是上拉还是下拉都触发了下拉

**Comment by acton393** [comment]
scroller 在contentSize 小于 scroller 本身高度时候是不能触发滑动的

**Comment by lmnsg** [comment]
@acton393 那为什么 list 可以？  但是 list 滚的有问题

**Comment by acton393** [comment]
hi @lmnsg  list 滚动有啥问题嘞， list 实现是用的tableView

**Comment by lmnsg** [comment]
list 的问题是 无论是上拉还是下拉都触发了下拉 当子元素未填满一屏的时候

**Comment by acton393** [comment]
hi @lmnsg  #1896 这个情况我在这回复一下

**Comment by acton393** [comment]
@lmnsg  scroll contentSize 小于本身高度不能滑的问题排查到，下个版本修复一下， 这个也同时会影响到refresh loading 等相关组件~~

**Comment by lmnsg** [comment]
@acton393  感谢

**Comment by zhshijie** [comment]
设置一下scroll 的alwaysScrollableVertical 的属性为true ，就可以然scroll在铺不满屏幕的时候能够下拉

**Comment by pigheartCN** [comment]
@zhshijie 这个我试了不行啊

**Comment by JackLiu0001** [comment]
alwaysScrollableVertical方法我也试了，不行，急求解决办法

**Comment by JakeRed** [comment]
android 上也有同样的问题。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
