### ISSUE TITLE
IOS 键盘问题

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1885]
移动端网页上一般键盘弹出的时候会把 view 往上推， 而 weex 在 ios 端的时候，键盘弹出却没有把 view 推上去，比如悬浮的输入框被键盘盖住。

**Comment by acton393** [comment]
@kfeagle  我记得应该是整个weexView 都往上移动的

**Comment by lmnsg** [comment]
是的。。但是并没有..  
weex sdk: 0.8.0

**Comment by acton393** [comment]
可以试下 ios-feature-1208 分支的input组件看下

**Comment by acton393** [comment]
暂时先关闭了，如果有问题可以继续打开
