### ISSUE TITLE
注意:在iOS中 循环调用 renderWithURL 会产生内存不断叠加的情况,Leak工具检测不到.

### ISSUE THREAD

**Issue by haicuan139** [alibaba/weex#1890]
场景:使用UITableView cellForRowAtIndexPath 中通renderWithURL 动态加载脚本渲染UITableViewCell的subview.动态添加View时 renderWithURL 会不断累加内存.注释掉renderWithURL一行代码.内存叠加情况消失.

**Comment by cxfeng1** [comment]
@haicuan139  在不可见的时候是否使用了destroyInstance去销毁实例？

**Comment by haicuan139** [comment]
@cxfeng1 已经解决 
如下:
- (void)prepareForReuse
{
    [super prepareForReuse];
    [_instance destroyInstance];
}

**Comment by cxfeng1** [comment]
@haicuan139  赞， 那我先关掉这个issue了
