### ISSUE TITLE
Can't get input value if there is no input event listener

### ISSUE THREAD

**Issue by zhoukekestar** [alibaba/weex#1895]
I have a component named [`wxc-form`](https://github.com/zhoukekestar/wxc-form) which should get input value without `oninput` OR `onchange`. 

Here is an online demo:  [input-bug](https://zhoukekestar.github.io/wxc-form/public/index.html?page=./input-bug.js), [demo code](https://github.com/zhoukekestar/wxc-form/blob/master/src/input-bug.we)

When you input `1111` to first input control, `2222` to second input control. Get current input value. The result is: input-1 equal to `1111` which is i want, input-2 is equal to an empty string which i think is a bug.

The same issue is occurred on android too.
![738177998040603469](https://cloud.githubusercontent.com/assets/7157346/21173055/bdc9cc5a-c210-11e6-9a28-d192c9e9638c.png)

Relative issues: [#1000](https://github.com/alibaba/weex/issues/1000)

**Comment by Jinjiang** [comment]
This is an known issue. Yes you have to add event listener for it. Sorry about that...
Maybe we will find some way to solve it in the future.

Thanks.
