### ISSUE TITLE
怎么优化下拉刷新和上拉加载的体验

### ISSUE THREAD

**Issue by QFangMobile** [alibaba/weex#1896]
用weex做单页确实比RN要方便，但是下拉刷新和上拉加载体验怎么优化，做的完全没法和原生比啊，下拉中间有一段空白，如果把空白设置少点轻轻一碰就出发下拉，下拉也是一样，如果是这样这下拉刷新完全没法用啊

**Comment by acton393** [comment]
hi @QFangMobile  这种情况是在iOS 还是在Android上的，方便贴一下case，讨论一下不

iOS 现在处理下拉： 当refreshview 完全出现在当前可视区域之后触发onrefresh 事件，

**Comment by QFangMobile** [comment]
下面是我临时写的一个demo,只要下拉显示refreshview下边一点点松开就会触发onrefresh
而且refresh设置height后会导致refreshview和list下面有height高度的空白
我是在IOS平台测试的
具体可以看下面的截图，只要顶端的颜色露出一点松开就会触发，实际这是refreshview的底部
[http://mobile.qfang.com/download/IMG_0996.jpg](url)
<template>
  <div>
    <list class="list">
      <refresh class="dropdownrefresh" onrefresh="refreshData">
      <img src="http://192.168.0.42:8088/test/upload/ftp/arrow.png"></img>
        <text class="text"> ↓ Pull to refresh a </text>
        <loading-indicator class="indicator"></loading-indicator>
      </refresh>
      <cell class="row" repeat="item in items" id="item-{{$index}}" rownumber={{$index}} onclick="cellclick">
          <img class="item-img" src="{{item.path}}" alt="" />

          <div class="item-info">
              <div class="item-info-detail">
                <text class="title">{{item.gardenName}}</text>
                <text class="price">{{item.price}}万</text>
              </div>
              <div class="detail-info">
                <text class="desc">{{item.gardenAddress}}</text>
              </div>

              <div class="tips-panel">
                 <div if="{{item.hasdate}}" class="tip-empty"><text class="txt">12-12放盘</text> </div>
                 <div if="{{item.haskey}}"  class="tip-green tip-base"><text class="txt">有钥匙</text></div>
                 <div if="{{item.year5}}"  class="tip-blue tip-base"><text class="txt">满五唯一</text></div>
                 <div if="{{item.red}}"  class="tip-red tip-base"><text class="txt">红本在手</text></div>
                 <div if="{{item.uniqueEstate}}"  class="tip-red tip-base"><text class="txt">唯一房产</text></div>
                 <div if="{{item.hasred}}" class="tip-yellow tip-base"><text class="txt">业主委托</text></div>
              </div>
              <div class="ext-panel" if="{{item.showextpanel}}" onclick="quickclick" enable={{item.enableextpanel}}>
                    <img class="ext-tip-icon" src="{{item.exttipicon}}"/>
                    <text class="ext-tip-message">{{item.exttipmessage}}</text>
                    <img if="{{item.hasextarrow}}" class="ext-tip-arrow" src="http://192.168.0.42:8088/test/upload/ftp/arrow.png"></img>
                    <div if="{{!item.hasextarrow}}" class="ext-tip-arrow"></div>
              </div>
          </div>
      </cell>
      <loading onloading="loadingData" style="width: 750; padding: 30;" display="{{loadingDisplay}}">
        <text class="text">asdfad{{loadingText}}</text>
      </loading>
    </list>
    <div class="up" onclick="goToTop">
      <img class="img" src="https://img.alicdn.com/tps/TB1ZVOEOpXXXXcQaXXXXXXXXXXX-200-200.png"></img>
    </div>
  </div>
</template>

<style>
.dropdownrefresh{
  width: 750;
  height:60;
  background-color:#cfc;
}
.header {
  padding: 25;
  background-color: #efefef;
  border-bottom-color: #eeeeee;
  border-bottom-width: 2;
  border-bottom-style: solid;
}

.ext-panel{
  padding:5;
  height:48;
  background-color:#efefef;
  flex-direction: row;
  align-items:center;
  justify-content:flex-end;
}

.tips-panel{
  margin-top:10;
  #background-color: #efefef;
  padding-top:5;
  padding-bottom:5;
  width:512;
  text-algin:center;
  flex-direction: row;
  align-items:center;
  justify-content:flex-start;
}

.ext-tip-icon{
   width:32;
   height:32;
   margin-right:10;
}
.ext-tip-message{
width:430;
lines:1;
  font-size:24;
}
.ext-tip-arrow{
  width:16;
  height:22;
  margin-right:10;
}

.txt
{
  font-size:24;
}
.tip-empty{
  #padding:5;
  #margin-left:5;
  margin-right:5;
}
.tip-base{
    padding:5;
  border-radius:5;
    border-style:solid;
  border-width:1;
  #margin-left:5;
  margin-right:5;
}

.tip-green{
  border-color:green;
  color:green;
}

.tip-blue{
  border-color:blue;
  color:blue;
}

.tip-yellow{
  border-color:yellow;
  color:yellow;
}

.tip-red{
  border-color:red;
  color:red;
}

.title {
  lines:1;
  text-overflow: ellipsis;
  font-size: 28;
  color: #2D2D2D;
  line-height: 40;
  background-color:white;
  width:392;
}

.item-content {
  flex-direction: row;
  background-color: #ffffff;
}

.item-img {
  width: 208;
  height: 160;
  margin-right: 10;
}

.item-info {
  margin-right:20;
  width:512;
  #background-color:gray;
}


.desc {
  lines: 4;
  text-overflow: ellipsis;
  font-size: 26;
  line-height: 30;
  color: #A2A2A2;
  background-color:#fff;
}

.price{
  width:120;
  lines: 1;
  text-align:right;
  font-size:32;
  color:#FF8102;
  font-weight:bold;
  background-color:white;
}

.detail-info{
  margin-top:12;
  height:40;
  justify-content:center;
  #background-color:#cff;
}

.item-info-detail {
  position: relative;
  color: #A2A2A2;
  width:512;
  margin-top:5;
  background:#acacac;
  flex-direction: row;
  text-overflow: ellipsis;
  align-items:stretch;
  background-color:#fcf;
}

.text {
  text-align: center;
}
.list {
  background-color: #ffffff;
}
.row {
  padding: 8;
  border-bottom-color: #eeeeee;
  border-bottom-width: 2;
  border-bottom-style: solid;
  flex-direction: row;
  box-align:stretch;
}

.up {
  width: 70;
  height: 70;
  position: fixed;
  right: 20;
  bottom: 20;
}
.img {
  width: 70;
  height: 70;
}
</style>

<script>
var dom = require('@weex-module/dom') || {}

var modal = require('@weex-module/modal') || {}
var apis = require('./common/api');

module.exports = {
  data: {
    page: 1,
    extstatus:[],
    loadingDisplay: 'Show',
    loadingText: 'Loading...',
    items:[]
  },
  created: function () {
    this.requestData(1);

    var item={}, item1={}, item2={};
    item.exttipicon = 'http://192.168.0.42:8088/test/upload/ftp/send.png';
    item.exttipmessage = '发布可得黄金展位';
    item.hasextarrow = true;


    item1.exttipicon = 'http://192.168.0.42:8088/test/upload/ftp/qiang.png';
    item1.exttipmessage = '抢推荐展位';
    item1.hasextarrow = true;

    item2.exttipicon = 'http://192.168.0.42:8088/test/upload/ftp/get.png';
    item2.exttipmessage = '已获得黄金展位';
    item2.hasextarrow = false;

    this.extstatus[0] = item;
    this.extstatus[1] = item1;
    this.extstatus[2] = item2;

    this.page++
  },
  methods: {
    requestData: function (cpage) {
      var self = this

      apis.getListData(cpage, function (ret) {
          for (var i = 0; i < ret.data.items.length; i++) {
              var item = ret.data.items[i];
              if(!item.path || !item.path.length)
                item.path = 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg';
              if(!item.keyNumber)
                item.haskey = false;
              else
                item.haskey = true;

                if(!item.year5 || item.year5 == "NO")
                  item.year5 = false;
                else
                  item.year5 = true;

                  if(i & 2 > 0){
                     item.hasdate = false;
                     item.showextpanel = true;
                     item.enableextpanel = true;
                     if(i & 3 > 0)
                       item.enableextpanel = false;

                      var style = 0;
                       if(i == 1)
                       {
                          style = 0;
                       }
                       else if(i == 3)
                       {
                         style = 1;
                       }
                       else
                       {
                         style = 2;
                       }

                       item.exttipicon = self.extstatus[style].exttipicon;
                       item.exttipmessage = self.extstatus[style].exttipmessage;
                       item.hasextarrow = self.extstatus[style].hasextarrow;
                  }
                  else{
                     item.showextpanel = false;
                     item.hasdate = true;
                     item.enableextpanel = false;
                  }


              self.items.push(item);
          }
      });
    },
    loadingData: function (e) {
      var self = this

      if (self.page <=10 ) {
        self.requestData(this.page)
        self.page++
      } else {
        self.loadingDisplay = 'hide'
        self.loadingText = 'NO MORE!'
      }
    },
    goToTop: function (e) {
      dom.scrollToElement(this.$el('item-0'), {
        offset: -100
      })
    },
    refreshData: function (e) {

      modal.toast({
        'message': 'Refreshing...',
        'duration': 1
      })

      this.items = []
      this.page = 1
      this.requestData(this.page)
    },
    quickclick:function(e){

      if(e.target.attr.enable)
          modal.toast({
            'message': 'ext panel clicked!',
            'duration': 1
          });
        else
        {
        modal.toast({
          'message': 'disable ext panel clicked!',
          'duration': 1
        });
        }
    },
    cellclick: function(e){
      modal.toast({
        'message': 'row ' + e.target.attr.rownumber + ' clicked',
        'duration': 1
      });
    }
  }
}
</script>

**Comment by QFangMobile** [comment]
下面是我临时写的一个demo,只要下拉显示refreshview下边一点点松开就会触发onrefresh
而且refresh设置height后会导致refreshview和list下面有height高度的空白
我是在IOS平台测试的
具体可以看下面的截图，只要顶端的颜色露出一点松开就会触发，实际这是refreshview的底部
[http://mobile.qfang.com/download/IMG_0996.jpg](url)

`<template>
  <div>
    <list class="list">
      <refresh class="dropdownrefresh" onrefresh="refreshData">
      <img src="http://192.168.0.42:8088/test/upload/ftp/arrow.png"></img>
        <text class="text"> ↓ Pull to refresh a </text>
        <loading-indicator class="indicator"></loading-indicator>
      </refresh>
      <cell class="row" repeat="item in items" id="item-{{$index}}" rownumber={{$index}} onclick="cellclick">
          <img class="item-img" src="{{item.path}}" alt="" />

          <div class="item-info">
              <div class="item-info-detail">
                <text class="title">{{item.gardenName}}</text>
                <text class="price">{{item.price}}万</text>
              </div>
              <div class="detail-info">
                <text class="desc">{{item.gardenAddress}}</text>
              </div>

              <div class="tips-panel">
                 <div if="{{item.hasdate}}" class="tip-empty"><text class="txt">12-12放盘</text> </div>
                 <div if="{{item.haskey}}"  class="tip-green tip-base"><text class="txt">有钥匙</text></div>
                 <div if="{{item.year5}}"  class="tip-blue tip-base"><text class="txt">满五唯一</text></div>
                 <div if="{{item.red}}"  class="tip-red tip-base"><text class="txt">红本在手</text></div>
                 <div if="{{item.uniqueEstate}}"  class="tip-red tip-base"><text class="txt">唯一房产</text></div>
                 <div if="{{item.hasred}}" class="tip-yellow tip-base"><text class="txt">业主委托</text></div>
              </div>
              <div class="ext-panel" if="{{item.showextpanel}}" onclick="quickclick" enable={{item.enableextpanel}}>
                    <img class="ext-tip-icon" src="{{item.exttipicon}}"/>
                    <text class="ext-tip-message">{{item.exttipmessage}}</text>
                    <img if="{{item.hasextarrow}}" class="ext-tip-arrow" src="http://192.168.0.42:8088/test/upload/ftp/arrow.png"></img>
                    <div if="{{!item.hasextarrow}}" class="ext-tip-arrow"></div>
              </div>
          </div>
      </cell>
      <loading onloading="loadingData" style="width: 750; padding: 30;" display="{{loadingDisplay}}">
        <text class="text">asdfad{{loadingText}}</text>
      </loading>
    </list>
    <div class="up" onclick="goToTop">
      <img class="img" src="https://img.alicdn.com/tps/TB1ZVOEOpXXXXcQaXXXXXXXXXXX-200-200.png"></img>
    </div>
  </div>
</template>

<style>
.dropdownrefresh{
  width: 750;
  height:60;
  background-color:#cfc;
}
.header {
  padding: 25;
  background-color: #efefef;
  border-bottom-color: #eeeeee;
  border-bottom-width: 2;
  border-bottom-style: solid;
}

.ext-panel{
  padding:5;
  height:48;
  background-color:#efefef;
  flex-direction: row;
  align-items:center;
  justify-content:flex-end;
}

.tips-panel{
  margin-top:10;
  #background-color: #efefef;
  padding-top:5;
  padding-bottom:5;
  width:512;
  text-algin:center;
  flex-direction: row;
  align-items:center;
  justify-content:flex-start;
}

.ext-tip-icon{
   width:32;
   height:32;
   margin-right:10;
}
.ext-tip-message{
width:430;
lines:1;
  font-size:24;
}
.ext-tip-arrow{
  width:16;
  height:22;
  margin-right:10;
}

.txt
{
  font-size:24;
}
.tip-empty{
  #padding:5;
  #margin-left:5;
  margin-right:5;
}
.tip-base{
    padding:5;
  border-radius:5;
    border-style:solid;
  border-width:1;
  #margin-left:5;
  margin-right:5;
}

.tip-green{
  border-color:green;
  color:green;
}

.tip-blue{
  border-color:blue;
  color:blue;
}

.tip-yellow{
  border-color:yellow;
  color:yellow;
}

.tip-red{
  border-color:red;
  color:red;
}

.title {
  lines:1;
  text-overflow: ellipsis;
  font-size: 28;
  color: #2D2D2D;
  line-height: 40;
  background-color:white;
  width:392;
}

.item-content {
  flex-direction: row;
  background-color: #ffffff;
}

.item-img {
  width: 208;
  height: 160;
  margin-right: 10;
}

.item-info {
  margin-right:20;
  width:512;
  #background-color:gray;
}


.desc {
  lines: 4;
  text-overflow: ellipsis;
  font-size: 26;
  line-height: 30;
  color: #A2A2A2;
  background-color:#fff;
}

.price{
  width:120;
  lines: 1;
  text-align:right;
  font-size:32;
  color:#FF8102;
  font-weight:bold;
  background-color:white;
}

.detail-info{
  margin-top:12;
  height:40;
  justify-content:center;
  #background-color:#cff;
}

.item-info-detail {
  position: relative;
  color: #A2A2A2;
  width:512;
  margin-top:5;
  background:#acacac;
  flex-direction: row;
  text-overflow: ellipsis;
  align-items:stretch;
  background-color:#fcf;
}

.text {
  text-align: center;
}
.list {
  background-color: #ffffff;
}
.row {
  padding: 8;
  border-bottom-color: #eeeeee;
  border-bottom-width: 2;
  border-bottom-style: solid;
  flex-direction: row;
  box-align:stretch;
}

.up {
  width: 70;
  height: 70;
  position: fixed;
  right: 20;
  bottom: 20;
}
.img {
  width: 70;
  height: 70;
}
</style>

<script>
var dom = require('@weex-module/dom') || {}

var modal = require('@weex-module/modal') || {}
var apis = require('./common/api');

module.exports = {
  data: {
    page: 1,
    extstatus:[],
    loadingDisplay: 'Show',
    loadingText: 'Loading...',
    items:[]
  },
  created: function () {
    this.requestData(1);

    var item={}, item1={}, item2={};
    item.exttipicon = 'http://192.168.0.42:8088/test/upload/ftp/send.png';
    item.exttipmessage = '发布可得黄金展位';
    item.hasextarrow = true;


    item1.exttipicon = 'http://192.168.0.42:8088/test/upload/ftp/qiang.png';
    item1.exttipmessage = '抢推荐展位';
    item1.hasextarrow = true;

    item2.exttipicon = 'http://192.168.0.42:8088/test/upload/ftp/get.png';
    item2.exttipmessage = '已获得黄金展位';
    item2.hasextarrow = false;

    this.extstatus[0] = item;
    this.extstatus[1] = item1;
    this.extstatus[2] = item2;

    this.page++
  },
  methods: {
    requestData: function (cpage) {
      var self = this

      apis.getListData(cpage, function (ret) {
          for (var i = 0; i < ret.data.items.length; i++) {
              var item = ret.data.items[i];
              if(!item.path || !item.path.length)
                item.path = 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg';
              if(!item.keyNumber)
                item.haskey = false;
              else
                item.haskey = true;

                if(!item.year5 || item.year5 == "NO")
                  item.year5 = false;
                else
                  item.year5 = true;

                  if(i & 2 > 0){
                     item.hasdate = false;
                     item.showextpanel = true;
                     item.enableextpanel = true;
                     if(i & 3 > 0)
                       item.enableextpanel = false;

                      var style = 0;
                       if(i == 1)
                       {
                          style = 0;
                       }
                       else if(i == 3)
                       {
                         style = 1;
                       }
                       else
                       {
                         style = 2;
                       }

                       item.exttipicon = self.extstatus[style].exttipicon;
                       item.exttipmessage = self.extstatus[style].exttipmessage;
                       item.hasextarrow = self.extstatus[style].hasextarrow;
                  }
                  else{
                     item.showextpanel = false;
                     item.hasdate = true;
                     item.enableextpanel = false;
                  }


              self.items.push(item);
          }
      });
    },
    loadingData: function (e) {
      var self = this

      if (self.page <=10 ) {
        self.requestData(this.page)
        self.page++
      } else {
        self.loadingDisplay = 'hide'
        self.loadingText = 'NO MORE!'
      }
    },
    goToTop: function (e) {
      dom.scrollToElement(this.$el('item-0'), {
        offset: -100
      })
    },
    refreshData: function (e) {

      modal.toast({
        'message': 'Refreshing...',
        'duration': 1
      })

      this.items = []
      this.page = 1
      this.requestData(this.page)
    },
    quickclick:function(e){

      if(e.target.attr.enable)
          modal.toast({
            'message': 'ext panel clicked!',
            'duration': 1
          });
        else
        {
        modal.toast({
          'message': 'disable ext panel clicked!',
          'duration': 1
        });
        }
    },
    cellclick: function(e){
      modal.toast({
        'message': 'row ' + e.target.attr.rownumber + ' clicked',
        'duration': 1
      });
    }
  }
}
</script>`

**Comment by QFangMobile** [comment]
代码粘贴显示有问题你直接去下面链接下吧
http://mobile.qfang.com/download/testlist.we

**Comment by liujianying** [comment]
android 如果在下拉刷新 或者是 在上拉加载更多的时候, 整个列表是无法上下滚动,看android 代码发现是底层做了屏蔽.如果去除会带来新的问题,希望改进 @ acton393
![c7c0bea25ad46811704244992e6f0377](https://cloud.githubusercontent.com/assets/6265414/21178009/88114166-c228-11e6-9622-1c9d0b055136.png)

**Comment by acton393** [comment]
@sospartan   麻烦帮瞅一下@liujianying  的问题

**Comment by acton393** [comment]
hi  @QFangMobile 我看了一下， refresh其实是正常的， 你下拉一点点的时候主要是触发了loading， 然后调用了loading 的requestData，我看到你code里面refresh 和loading 都有request data 的


hi @lmnsg 
下面解释下在iOS 为啥会在下拉一点的时候调用到loading 方法：
    [此处](https://github.com/alibaba/weex/blob/dev/ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m#L135) 会在cell load 的时候去重新计算一次 scroller view 的contenSize 的高度
 [下拉处理](https://github.com/alibaba/weex/blob/dev/ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m#L447) 由于刚开的刚开始的时候 contentSize 高度太小(只有一条数据)，所以你在下拉的时候触发到loading 方法

**Comment by QFangMobile** [comment]
@acton393 
不是的，loading是在上拉加载更多的时候触发，你可以屏蔽这里的加载代码，而且我第一次加载的数据可以显示两屏，我下拉的时候怎么又去触发loading的加载呢? 我跟代码是先触发的onrefresh，正常我还没超过refreshView怎么就出发onrefresh这不是有问题的吗？

你可以把requestData的函数换成下面的就可以在本地调试了
`requestData: function (cpage) {
      var self = this

      self.items = items:[{
          path: 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg',
          gardenName: 'Who is Alan Mathison Turing?',
          gardenAddress: 'Alan Mathison Turing ( 23 June 1912 – 7 June 1954) was an English computer scientist, mathematician, logician, cryptanalyst and theoretical biologist. He was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general purpose computer.Turing is widely considered to be the father of theoretical computer science and artificial intelligence.'
        },{
          path: 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg',
          gardenName: 'Who is Alan Mathison Turing?',
          gardenAddress: 'Alan Mathison Turing ( 23 June 1912 – 7 June 1954) was an English computer scientist, mathematician, logician, cryptanalyst and theoretical biologist. He was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general purpose computer.Turing is widely considered to be the father of theoretical computer science and artificial intelligence.'
        },{
          path: 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg',
          gardenName: 'Who is Alan Mathison Turing?',
          gardenAddress: 'Alan Mathison Turing ( 23 June 1912 – 7 June 1954) was an English computer scientist, mathematician, logician, cryptanalyst and theoretical biologist. He was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general purpose computer.Turing is widely considered to be the father of theoretical computer science and artificial intelligence.'
        },{
          path: 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg',
          gardenName: 'Who is Alan Mathison Turing?',
          gardenAddress: 'Alan Mathison Turing ( 23 June 1912 – 7 June 1954) was an English computer scientist, mathematician, logician, cryptanalyst and theoretical biologist. He was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general purpose computer.Turing is widely considered to be the father of theoretical computer science and artificial intelligence.'
        },{
          path: 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg',
          gardenName: 'Who is Alan Mathison Turing?',
          gardenAddress: 'Alan Mathison Turing ( 23 June 1912 – 7 June 1954) was an English computer scientist, mathematician, logician, cryptanalyst and theoretical biologist. He was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general purpose computer.Turing is widely considered to be the father of theoretical computer science and artificial intelligence.'
        },{
          path: 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg',
          gardenName: 'Who is Alan Mathison Turing?',
          gardenAddress: 'Alan Mathison Turing ( 23 June 1912 – 7 June 1954) was an English computer scientist, mathematician, logician, cryptanalyst and theoretical biologist. He was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general purpose computer.Turing is widely considered to be the father of theoretical computer science and artificial intelligence.'
        },{
          path: 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg',
          gardenName: 'Who is Alan Mathison Turing?',
          gardenAddress: 'Alan Mathison Turing ( 23 June 1912 – 7 June 1954) was an English computer scientist, mathematician, logician, cryptanalyst and theoretical biologist. He was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general purpose computer.Turing is widely considered to be the father of theoretical computer science and artificial intelligence.'
        },{
          path: 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg',
          gardenName: 'Who is Alan Mathison Turing?',
          gardenAddress: 'Alan Mathison Turing ( 23 June 1912 – 7 June 1954) was an English computer scientist, mathematician, logician, cryptanalyst and theoretical biologist. He was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general purpose computer.Turing is widely considered to be the father of theoretical computer science and artificial intelligence.'
        },{
          path: 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg',
          gardenName: 'Who is Alan Mathison Turing?',
          gardenAddress: 'Alan Mathison Turing ( 23 June 1912 – 7 June 1954) was an English computer scientist, mathematician, logician, cryptanalyst and theoretical biologist. He was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general purpose computer.Turing is widely considered to be the father of theoretical computer science and artificial intelligence.'
        }];

        for (var i = 0; i < self.items.length; i++) {
            var item = self.items.items[i];
            if(!item.path || !item.path.length)
              item.path = 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg';
            if(!item.keyNumber)
              item.haskey = false;
            else
              item.haskey = true;

              if(!item.year5 || item.year5 == "NO")
                item.year5 = false;
              else
                item.year5 = true;

                if(i & 2 > 0){
                   item.hasdate = false;
                   item.showextpanel = true;
                   item.enableextpanel = true;
                   if(i & 3 > 0)
                     item.enableextpanel = false;

                    var style = 0;
                     if(i == 1)
                     {
                        style = 0;
                     }
                     else if(i == 3)
                     {
                       style = 1;
                     }
                     else
                     {
                       style = 2;
                     }

                     item.exttipicon = self.extstatus[style].exttipicon;
                     item.exttipmessage = self.extstatus[style].exttipmessage;
                     item.hasextarrow = self.extstatus[style].hasextarrow;
                }
                else{
                   item.showextpanel = false;
                   item.hasdate = true;
                   item.enableextpanel = false;
                }
        }`

**Comment by QFangMobile** [comment]
@acton393 你可以试试，下拉只要露出绿色区域(refreshView)一点松开就会触发onrefresh，确定了几次是没有触发loading事件的，只要把清空items=[]放到加载数据判断是否要清空就不会触发loading，但是onrefresh触发时机肯定不是你们说的全部refreshview显示才会触发

**Comment by acton393** [comment]
@QFangMobile  嗯，关于push 的数据，我之前是把request data 手动改成了push 1 条数据的， 

你发的case，我试了一下，没有出现稍微往下一拉就会触发onrefresh 的逻辑，

你是在哪个分支的，也可以源码调试一下

**Comment by weixinbing** [comment]
@acton393 
![2017-01-10 11 39 53](https://cloud.githubusercontent.com/assets/13991159/21793115/8a430c7e-d729-11e6-91f8-c5f4196edb6a.png)
请问这个问题, iOS现在是如何解决的.

**Comment by CFKit** [comment]
#2370 

1. iOS列表不满一屏时上拉回同时触发上下拉刷新，此时需要在WXScrollerComponent.m总修改
![default](https://cloud.githubusercontent.com/assets/20106110/22766030/3d61c5e8-eeae-11e6-94f8-5fa3fa3549f1.png)
在两个if中都添加一个return，保证一次上拉只触发一次操作。
2. 还有一个问题是，当不满一屏时做上拉操作，iOS页面列表会下对其，有一个解决方案是修改WXLoadingComponent.m
![default](https://cloud.githubusercontent.com/assets/20106110/22766127/b2e95b50-eeae-11e6-9398-928dbcaa55fc.png)
@acton393

**Comment by acton393** [comment]
@CFKit  这个在最新版本 应该已经修复掉了~~

**Comment by yuxingfafu** [comment]
@acton393 最新的版本，list在下拉刷新的时候，同时向下滚动列表，刷新的logo会一直留在那里不消失，官网的playground 就会
![gl57f i605klh45_ o9rv7q](https://cloud.githubusercontent.com/assets/7764483/26340005/8253fbc4-3fbe-11e7-86d9-ffdf7384c016.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
