### ISSUE TITLE
请问，如何设置font-weight:light的思源黑体中文字体（现在设置了无效，思源黑体支持这个字重）

### ISSUE THREAD

**Issue by noman798** [alibaba/weex#190]
参见这个 pull requests
https://github.com/alibaba/weex/pull/188
最好可以引用网络或本地的字体
请给出方案之后再 close 这个 issue 吧（不要写 coming soon  @就关了）

**Comment by YorkShen** [comment]
@noman798 This issue has been fixed, see https://github.com/alibaba/weex/pull/868 . If anything goes wrong, you can reopen it anytime.
