### ISSUE TITLE
<image>component 懒加载的图片在H5环境下无法触发问题

### ISSUE THREAD

**Issue by fromIRIS** [alibaba/weex#1901]
## 环境

- h5
- START WEEX HTML5: ^0.4.1 Build 20161209

## bug描述

在list中列有大量图片，在`ready`周期函数中调用

```
dom.scrollToElement(self.$el(history.state.itemId), {
            offset: 0
          })
```

页面滚到到相应位置，但是图片无法触发

![image](https://cloud.githubusercontent.com/assets/8492963/21182146/8a990bee-c23c-11e6-9df2-cd26922f3881.png)
![image](https://cloud.githubusercontent.com/assets/8492963/21182152/976dd6e2-c23c-11e6-91e4-7488358ac464.png)

**Comment by Jinjiang** [comment]
可以在 http://dotwe.org/ 写个例子吗？@fromIRIS

**Comment by fromIRIS** [comment]
@Jinjiang http://dotwe.org/d754256626e7dba0b7ab3c0b04fa9373

**Comment by Jinjiang** [comment]
稍微往上划一下就看到了 @MrRaindrop 这是不是个已知问题？

**Comment by MrRaindrop** [comment]
在 scrollToElement 之前需要确认这个节点已经挂载到页面里去了. ready 并不是一个正确的时机做这件事，因为 ready 只是绑定了数据和 vm,  节点还没有挂载完. h5 这个 0.4.1 这个版本还没有把 `weex:createfinish` 这个事件暴露出来，所以暂时建议只能把 setTimeout 的时间加长一点了.
