### ISSUE TITLE
注意:module/stream body 不兼容的问题

### ISSUE THREAD

**Issue by haicuan139** [alibaba/weex#1905]
例子代码:
xxx.fetch({
        url:'xxx',
        body:{params:'age'},
        // body:JSON.stringify({params:'age'}),
        
    })

body 存在两个平台不兼容的问题,在ios 平台上 必须要将{}转换为string,Android平台上不必如此.
问题产生的原因是由于 ios 平台使用body转为NSData时发生了错误.因为此时的body为NSDIC类型.
//ios stream 中的异常代码. 
[request setHTTPBody:[body dataUsingEncoding:NSUTF8StringEncoding]];//如果此时的body的类型为NSDicotary的话就会报错

**Comment by acton393** [comment]
@haicuan139  如你看到的， iOS 目前接受 的入参， Body确实是string类型
[code](https://github.com/alibaba/weex/blob/dev/ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m#L77)

**Comment by acton393** [comment]
#1945  pr 应该可以支持

**Comment by acton393** [comment]
暂时先关闭了，如果有问题可以继续打开，或者在 #1936 讨论
