### ISSUE TITLE
weex 安全性以及体验方面问题

### ISSUE THREAD

**Issue by liujianying** [alibaba/weex#1907]

**Comment by yuanzx** [comment]
数据包本来就很小，只请求数据。所有的js都是存在app中的吧，js+云更新。个人觉得js暴露出来没什么，走http或者https都可以抓包

**Comment by icepy** [comment]
@liujianying 能不能说一下，什么简单的功能页面怎么会有上百k？你引了很多其他的库吧？然后构建一个bundle.js文件。

**Comment by liujianying** [comment]
@icepy   部分页面确实引用了很多库, 但是这也是问题吧,无用的一些东西,其实没必要打包进来,熟悉jsbundle的话,这个可以有优化空间

**Comment by icepy** [comment]
@liujianying webpack构建的时候遇到require管你有没有引用都会打包的，而且weex-components只是几个很常见的组件，你看看源码都非常简单，构建出来绝对不可能有136kb，像@weex-module/apimodel 这种，是运行时动态挂的，构建之后只是换成了__weex_define 和 __weex_require__也不会有很多代码量。

个人觉得，你查一下require('./api.js'); 这个文件里是不是require很多其他的库。

**Comment by liujianying** [comment]
@icepy  导入require('weex-components');  js文件会大49kb 你可以测试下. 
所以关于js包较大的问题,我这边建议:
webpack 在打包时候,应该过滤无用的代码,不打入js文件中才是解决这个问题的关键.

**Comment by Jinjiang** [comment]
1. 本地可以采用一些加密的技术，不一定要在本地直接使用文件系统，这部分内容可以和 native 的技术强相关，理论上是可行的，网络传输可以使用 https 同样可以保障安全
2. 包大小确实需要很好的控制，未来我们会比较谨慎的考虑如何减少 JS Bundle 的负担
3. 首屏渲染优化一方面是要在运行时快速解析，这方面我们的 JS Framework 一直在不断挑战极致，另外一方面也需要把 JS Bundle 提前从网络加载下来，可以复用 ApplicationCache 的设计理念

最后感谢对 Weex 的肯定和支持！

**Comment by liujianying** [comment]
@Jinjiang  Thanks    第一点我们团队内部最终讨论的结果也是这样, 第三个目前我们还在探索当中
