### ISSUE TITLE
a链接在 浏览器中无法跳转？

### ISSUE THREAD

**Issue by WangXiZhu** [alibaba/weex#1909]
在原生上时可以的，但是在浏览器中打开不能跳转。

目前下面的方式实现的跳转，不知道这个什么原因。源码中虽然有监听事件，但是并没有处理跳转的代码。

虽然这种方式能够实现，但是在每个跳转的地方都要添加 5-6行代码还是有点麻烦。谢谢
```
<template>
    <div>
        <a href="http://www.baidu.com" onclick="click"><text>click me</text></a>
    </div>
</template>
<script>
    module.exports = {
        methods:{
            click: function(e){
                this.$openURL(e.target.attr.href)
            }
        }
    }
</script>

```

**Comment by Jinjiang** [comment]
似乎确实没打开 http://dotwe.org/041b1921ca8915777d4ba485394f0c40 提供一个 demo

**Comment by fromIRIS** [comment]
@WangXiZhu 你如果是用的weex-html5，你需要手动注册一个a组件。0.4.1版本的weex-html5并没有实现a组件

**Comment by WangXiZhu** [comment]
@fromIRIS  weex-html5后面的版本有没有考虑实现呢？   我手动注册的组件只会与html5相关吧？不会影响到其他部分吗？

**Comment by Jinjiang** [comment]
会的，我们稍后会在 dotwe.org 升级版本
谢谢
