### ISSUE TITLE
[FEATURE] Are u going to support css  transform property?

### ISSUE THREAD

**Issue by JackPu** [alibaba/weex#1914]
![image](https://cloud.githubusercontent.com/assets/4744967/21248836/c467c7be-c374-11e6-8c4f-e8cfda07e484.png)

I am devloping an weex component but it dosn't support use transform property like below:

``` html
<div style="transform:rotateX({{rightTransformerDegree}})"></div>
```
Myabe I can use animation to solve this porblem. So are u going to support it? 😄💐

**Comment by fkysly** [comment]
Sorry, this feature may not be supported in the near future. However, you can use the animation module instead.

**Comment by JackPu** [comment]
@fkysly  Thanks~ Have finished it. https://github.com/JackPu/weex-percentage-circle

![image](https://cloud.githubusercontent.com/assets/4744967/21263417/9da14d1e-c3d1-11e6-800d-df20d4ce0807.png)
