### ISSUE TITLE
info Thu Dec 15 2016 19:50:57 GMT+0800 (中国标准时间)http  is listening on port 8081

### ISSUE THREAD

**Issue by zhairui** [alibaba/weex#1915]
请问下，我编译hello.we文件的时候， 我端口被占用了，然后，我kill掉了，但是，当我再次运行命令的时候，那个端口又被占用了，结果看了下，是node.js占用的，我想问下，这个该怎么解决呢？

**Comment by Jinjiang** [comment]
可能和 toolkit 的逻辑有关，有劳多提供一些运行时和你本地开发环境的信息
另外整个操作过程中是否有报错信息，如果有的话也可以贴一下
谢谢

**Comment by exolution** [comment]
如果您用的是weex-toolkit的话   
可以增加参数 --port 8888 更换端口
如果不行再增加一个参数 --wsport 8889  （要不同于上个端口）

**Comment by zhairui** [comment]
您好，我是根据weex的官方文档来操作的，用的是weex-tookit，当我执行weex hello.we的时候，就说端口被监听，然后我看了下，监听的程序是node.exe，就算把这个kill掉之后，再次执行weex hello.we还是，同样的问题，然后，我是在windows 环境下运行的，安装的过程中并没有出现报错。

**Comment by exolution** [comment]
你尝试我说的加参数换端口了么

**Comment by exolution** [comment]
另外从你的标题来看 只有运行成功之后才会出现这个info。你所说的被占用是什么意思 node报错了么 报的错可以截下图看一下么（这个info是正常log）
如果没报错 表现上跟你预期不一样的地方 你也可以说一下

**Comment by Hanks10100** [comment]
长时间未回复，weex-toolkit 已经多次更新了
