### ISSUE TITLE
Android SDK IWXUserTrackAdapter 中的 perf.errMsg

### ISSUE THREAD

**Issue by NLMartian** [alibaba/weex#1916]
Android SDK 中 IWXUserTrackAdapter 回调方法收到的 errMsg 是同一类型的错误 append 起来的，用来上报的话不是很清晰，这样设计有什么用意吗？或者还有没有其他的可以在 native 接收 js 报错的接口

**Comment by xkli** [comment]
这样是为了把相关错误的信息都上报，比如错误类型、错误消息等。中间使用#进行分割，这样上报的信息更详细。
