### ISSUE TITLE
Flex 布局在Android上表现异常

### ISSUE THREAD

**Issue by totzcc** [alibaba/weex#1917]
如下是我的代码
[dotwe 预览](http://dotwe.org/6de2384327e09c5bcd14f4f2dce9ae19)
```html
<template>
  <list>
    <cell repeat="v in {[1,2,3,4,54,5,6,7,78]}">
      <div style="flex-direction: row;">
		<div style="flex: 1; justify-content: center;align-items: center;border-width:1;">
			<text>11111</text>
			<text>11111</text>
			<text>11111</text>
			<text>11111</text>
			<text>11111</text>
			<text>11111</text>
		</div>
		<div style="justify-content: center;align-items: center;border-width:1;">
			<text>11111</text>
		</div>
	</div>
    </cell>
  </list>
</template>

```
它在Android上右侧的div 不能居中， 在其他平台上是好的

Android
![Android](http://p1.bqimg.com/567571/840121a119ecb383.png)
iOS 
![iOS](http://p1.bqimg.com/567571/f9041265ad6fd91d.png)
H5
![H5](http://i1.piimg.com/567571/437bca8602afee91.png)

**Comment by WangXiZhu** [comment]
在外层设置个高度就可以了

```
<cell repeat="v in {[1,2,3,4,54,5,6,7,78]}">
      <div style="flex-direction: row;height:200;">
```

这里的text应该是直接被撑开的，不知道android怎么设计的

**Comment by sospartan** [comment]
@totzcc @WangXiZhu 这个是老版本csslayout的bug，flex的默认值不对，是已知问题，会在0.11版本修复。

**Comment by totzcc** [comment]
@WangXiZhu 
我试着用了另外一中解决方案。在右侧的这个我不加 div 了
因为如果左侧的内容是不固定高度的。这个在右侧的div上写一个高度不好办。
```html
<template>
  <list>
    <cell repeat="v in {[1,2,3,4,54,5,6,7,78]}" style="flex:1">
      <div style="flex-direction: row;justify-content: center;align-items: center;border-width:1;">
		<div style="flex: 1; justify-content: center;align-items: center;border-width:1;">
			<text>11111</text>
			<text>11111</text>
			<text>11111</text>
			<text>11111</text>
			<text>11111</text>
			<text>11111</text>
		</div>
		<text>11111</text>
	</div>
    </cell>
  </list>
</template>

```
http://dotwe.org/d4c50431d294856c3f8e78a12affd83d

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
