### ISSUE TITLE
点击事件无法传值了。

### ISSUE THREAD

**Issue by hyqinloveslife** [alibaba/weex#1922]
我的weex当前版本是0.5.8，一直都没问题的一个js文件，今天更新了一下，就发现onclick函数里面不能传值。尝试了两种方法，分别是
` <text class="hello" style="txt-color:#fff;bg-color:green"onclick="handleClick({{id}})">hello weex</text>`
另一种方法
`<text class="hello" style="txt-color:#fff;bg-color:green"onclick="handleClick(id)">hello weex</text>`

第一种方法报错，信息：uncaught TypeError: Cannot read property 'call' of undefined
第二种方法倒是不报错，但是传过来的值永远是undefined

请问一下还有别的解决办法吗？

**Comment by Jinjiang** [comment]
http://dotwe.org/fc0a66e8890ae1096d6d9281202ea580

我提供一个可工作的版本供你参考先，(没有发现你描述的问题)，看看可不可以参考一下

**Comment by icepy** [comment]
@hyqinloveslife 你这个是不是写在循环repeat里的？

**Comment by DangDangHellen** [comment]
好像是传data里面设的变量就可以，但是自己定义的好像不行
