### ISSUE TITLE
关于对带有底部虚拟导航栏的android机型适配问题

### ISSUE THREAD

**Issue by fqlgaryth** [alibaba/weex#1924]
因为weex在加载的时候是要传入显示的view大小，这样导致对一个带有底部虚拟导航栏的手机在加载进去后隐藏和显示虚拟导航栏上底部有遮蔽或空白问题。
mInstance.renderByUrl(
        getPageName(),
        url,
        options,
        jsonInitData,
        ScreenUtil.getDisplayWidth(this),
        ScreenUtil.getDisplayHeight(this),
        WXRenderStrategy.APPEND_ASYNC);

**Comment by sospartan** [comment]
@这个问题在android分支修复了，新增了`RenderContainer`的容器，会自适应。现阶段的话可以通过`SDKInstance#setSize`方法来调整容器大小。
