### ISSUE TITLE
animation的动画是否有暂停或者还原的方法？

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#1925]
animation的动画是否有暂停或者还原的方法？同时还想问的是，react native里面动画支持的sequence，在weex里面目前有支持吗？还是必须要自己计算每个动画的时间，设置delay？

**Comment by Jinjiang** [comment]
目前是没有的，我们先记录一下这个问题，汇总到 #1494 将来会选择合适的时机对这一块进行增强
谢谢您的反馈
