### ISSUE TITLE
一个奇怪的问题, 在安卓浏览器上

### ISSUE THREAD

**Issue by lmnsg** [alibaba/weex#1926]
我使用的 jssdk 版本是0.5.0 从 dev 分支上 build 下来的。
然后在安卓浏览器上有个奇怪的表现，weex.js 中不能使用 "use strict"; 
只有删除掉这句，才能正常使用， 只要加上这个，就无法使用，不知道是什么情况。

**Comment by Jinjiang** [comment]
`"use strict"` 放在什么地方了？如果放到最外层确实是有问题的，因为我们在实例管理的代码中用到了 `new Function`

**Comment by lmnsg** [comment]
看着是在 factory 函数的第一句...

**Comment by Jinjiang** [comment]
0.5 版本有点老了……最新的 dev 分支我们在 https://github.com/alibaba/weex/blob/dev/html5/frameworks/legacy/app/ctrl/init.js#L66 这里加入了严格模式，这样每个 JS Bundle 在运行的时候是在严格模式下的
