### ISSUE TITLE
[ios] fireGlobalEvent无响应！写法是否有问题？

### ISSUE THREAD

**Issue by flyer012** [alibaba/weex#1927]
ios代码：

我在UIViewController （里面有WXSDKInstance）里调用fireGlobalEvent：
//_instance 是在加载完成weex页面后调用的下面的方法，所以_instance是有值的！
 [_instance fireGlobalEvent:@"OpenTranslate" params:@{@"result":@"success",@"value":@"value"}];

js代码：

 created: function () {
       #可以正常执行到这
        var modal = require('@weex-module/modal');
        modal.toast({'message': "enter created function", 'duration': 1});

        var globalEvent = require('@weex-module/globalEvent');
        globalEvent.addEventListener("OpenTranslate", function (e) {
          #我在iOS端fireGlobalEvent无响应
          var modal = require('@weex-module/modal');
          modal.toast({'message': "globalListenerOfOpenTranslate", 'duration': 1});
        });
    },

function是放在vc对应的weex页面！
但是在js里面未收到响应？？？是否我写法有问题呢！

**Comment by acton393** [comment]
hi @flyer012  麻烦咨询下 你使用的SDK的版本 是哪个分支上的

**Comment by flyer012** [comment]
主分支上的！最新的SDK

**Comment by icepy** [comment]
@flyer012 是写在renderFinish这个block里来调用fireGlobalEvent的么？

**Comment by flyer012** [comment]
@icepy 不是的，在vc里面直接写的！

**Comment by acton393** [comment]
hi @flyer012
你试试写在renderFinish 内， 
最主要的原因是有可能你在调用的globalEvent 的时候js的instance还没有创建好，尽管你做了延时调用，

我看到你在qq群里面调用的地方是在 module里面，你也可以试试在module 里面发一下

**Comment by flyer012** [comment]
已经找到问题了，引用的framework包的问题，用最新下载的weex源码就没有问题！

**Comment by ZhangHJ1002** [comment]
@flyer012  你好 你后来是引用的那个架包的呢 我现在也出现这个问题 
在 module里 使用无法触发事件

@acton393  @icepy  大佬 你们看看呢
