### ISSUE TITLE
Simple Android Wrapper

### ISSUE THREAD

**Issue by rizkyramadhan** [alibaba/weex#1929]
Is there any pre-made android wrapper apk?, so that I just need to put some configuration file to load .we from my server, change the icon and app name, and then ship it. 

Current playground apk is great for showcasing weex, but it cannot start with my .we. 

I think it will greatly simplify weex development / deployment.

**Comment by Jinjiang** [comment]
We have a Weex Playground App in our download web page.

http://alibaba.github.io/weex/download.html

You can write some code through http://dotwe.org/ just like codepen. And then you can easily preview the render effect by scan the qrcode with Weex Playground App.

And of cource you can also make a server by your own using `weex-loader`

Thanks.

**Comment by Jinjiang** [comment]
btw the source code of Weex Playground App is in `./android/playground` and `./ios/playground`
