### ISSUE TITLE
weex如何调用界面里的原生控件啊

### ISSUE THREAD

**Issue by hodgevk** [alibaba/weex#1931]
比如weexpack生成的android 项目，PageActivity里有个mProgressBar，我想在weex中控制其显示和隐藏，有办法不？

**Comment by littleseven** [comment]
@hodgevk 控制逻辑全都在WXPageActivity中，如果要控制mProgressBar，则需要重载其控制逻辑并封装接口暴露给前端。主要是以下几个接口preRenderPage，onRenderSuccess，onException

**Comment by MaryWu** [comment]
further questions on weexpack please go to this place https://github.com/weexteam/weex-pack/issues. thanks

**Comment by hodgevk** [comment]
我只是举例，并不特指weexpack项目。@littleseven 具体怎么实现呢？
