### ISSUE TITLE
调用接口使用body传参就被浏览器挡住了！！！什么跨域访问问题！！！

### ISSUE THREAD

**Issue by lmh0921** [alibaba/weex#1933]
created:function () {
            var self = this
            stream.fetch({
                method: 'GET',
                headers:{
                    'apikey':'deaa5742c4fa6856c33309d63aefba4c'
                },
                url: 'http://apis.baidu.com/tngou/cook/show',
                body:{
                    'id':29643
                },
                type: 'json'
            }, function (ret) {。。。。。。
这种就不行
浏览器显示XMLHttpRequest cannot load http://apis.baidu.com/tngou/cook/show. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

然后status是-1，不使用body传参就没问题，这是怎么回事？？？？

**Comment by Jinjiang** [comment]
http://dotwe.org/559143bddeafb53b865c19974dbb1e13

**Comment by Jinjiang** [comment]
我简单写了个完整的例子，我们再确认一下 @lmh0921

**Comment by lmh0921** [comment]
@Jinjiang ，status是-1代表出错了，请你尝试一下把body的参数改为url?传参就会返回正确结果,而且我估计这个例子使用weex 。。。--qr扫码那个ios官方app会闪退，使用body传参时候。。

**Comment by DoranYun** [comment]
"GET" 请求不能添加 body，应该以 url 的方式传递参数，body 是 "POST" 方式的请求，你将 body 删除，url 改为 http://apis.baidu.com/tngou/cook/show?id=29643 即可。提供一个正确的例子： 
http://dotwe.org/2ada4056935c918b2a9030f6e8acd8b6

![image](https://cloud.githubusercontent.com/assets/16359169/21300634/93bb6f4e-c5e0-11e6-8281-46abeabc4102.png)

**Comment by MrRaindrop** [comment]
https://github.com/alibaba/weex/pull/1939 添加了对 `GET`  的识别并自动添加 body 的内容到 url 的 queryString

**Comment by zhugexiansheng** [comment]
我不传参也会报错，但是数据是返回了的，就是会报错 #2346

**Comment by 1021727984** [comment]
@DoranYun 你的例子有时请求成功，有时请求失败，很不稳，如果把没设置headers头就一直正常，一旦设置就很不稳，请帮忙看下问题#1933,同样遇到了这个问题，
