### ISSUE TITLE
安卓weex使用navigator跳转时，如果安装了weexplayground，会弹出打开应用选择

### ISSUE THREAD

**Issue by hodgevk** [alibaba/weex#1934]
安卓weex使用navigator跳转时，如果安装了weexplayground或者其他weex开发的软件，都会弹出打开应用选择，这种情况，可以避免吗？

**Comment by lmh0921** [comment]
你跳转是怎样传参的呢？想在前一个页面把分类id传给后一个页面，但是不能传啊

**Comment by hodgevk** [comment]
那传参正确的方法是怎么弄？我是参考weexone弄的

**Comment by hodgevk** [comment]
我把参数去掉了，也是一样，都弹出打开应用选择

**Comment by hodgevk** [comment]
看了安卓源码
`
    public class WXNavigatorModule extends WXModule {
       ...
       private final static String WEEX = "com.taobao.android.intent.category.WEEX";
       ...
       @WXModuleAnno
       public void push(String param, final String callbackId) {
           ...
           Intent intent = new Intent(Intent.ACTION_VIEW, builder.build());
           intent.addCategory(WEEX);
           ...
`
在这里使用了固定的分组，所以会弹出所有用weex开发的应用选择对话框，我能想到的就是新建自己的navigator Module,修改分组。不知道有没有其他的好办法。

**Comment by samyzhang** [comment]
一直很纳闷，为什么这个不做成public final static 【private final static String WEEX = "com.taobao.android.intent.category.WEEX";】
这样我们APP就可以通过反射修改；现在搞得跳转有点麻烦，得自定义自己的WXNavigatorModule
@sospartan

**Comment by xkli** [comment]
@samyzhang Android 对外提供了接口IActivityNavBarSetter可以自己实现navigator的跳转

**Comment by samyzhang** [comment]
哦，好的；
没有用过这个接口，以后试下
@xkli

**Comment by linda8167** [comment]
完美解决方案有么。。。
