### ISSUE TITLE
touch 事件相关问题

### ISSUE THREAD

**Issue by haicuan139** [alibaba/weex#1936]
针对0.8版本存在的平台兼容问题以及bug,下个版本在哪个时间段发布?

**Comment by cxfeng1** [comment]
@haicuan139  能否告知具体的问题以及bug， 0.9版本很快发布了， 我们看一下是否已经修复。

**Comment by haicuan139** [comment]
我目前能想到的问题:
1.touch 坐标在iOS plus 的真机上 产生的坐标不兼容
2.ios 的下拉上拉刷新,刷新控件高度计算存在问题 复现方式(正常集成下拉刷新控件,频繁开启当前页面,偶尔会发现下拉刷新或者上拉控件高度计算存在问题)
3.iOS 平台的stream 模块 存在一个 平台兼容问题:在为stream的body 传值时iOS平台 要使用JSON.strf 将{}转义为字符串,否则会报错,原因是因为 body为NSString,运行时类型为NSDic 在转换为NSData时报错,NSDic并不存在dataUsingEncoding方法
4.touch 事件,在Android,html5 平台上的性能堪忧.
5.在嵌套使用weex页面(设计通用模块),如果嵌套层次过多会导致 在使用 xx={{dataModel}} 传值时 经常会出现 undefine (这个问题我当时的测试环境比较复杂) 
6.ios的平台还不支持 onpulling事件.导致 不能进行三端统一扩展下拉刷新控件.
后面遇到问题我会持续进行反馈,有些问题也可能是使用weex方式不对.
@cxfeng1

**Comment by acton393** [comment]
hi @haicuan139  
麻烦  问题1 2可以再具体提供一下截图，或者期望值和目前提供值的差异，
        问题3 我有在 #1905  中提到的，目前接受的入参是String， [doc](http://alibaba.github.io/weex/doc/modules/stream.html) 上也是String ， 接受Object 类型会尝试兼容一下

**Comment by YorkShen** [comment]
@haicuan139 android手势性能请先看[文档](https://github.com/alibaba/weex/blob/doc/doc/references/gesture.md )，文档中已经列举了原因，方案，以及优缺点。

**Comment by haicuan139** [comment]
![img_0281](https://cloud.githubusercontent.com/assets/5266044/21306187/b5b8ba46-c60a-11e6-9ef9-330c6e5fa33a.PNG)
![img_0283](https://cloud.githubusercontent.com/assets/5266044/21306188/b6135ffa-c60a-11e6-9fca-1cf25bbae1b1.PNG)
![img_0284](https://cloud.githubusercontent.com/assets/5266044/21306190/b6223a8e-c60a-11e6-8cfe-ca9e743bbefc.PNG)
![img_0376](https://cloud.githubusercontent.com/assets/5266044/21306189/b620ea3a-c60a-11e6-95e3-a3e370a4b423.PNG)

**Comment by haicuan139** [comment]
@acton393 截图看下,其中坐标的问题 提现在 H5的render 上面.下拉刷新在ONREFRE 时 控件的高度和坐标明显是有问题的

**Comment by Jinjiang** [comment]
@haicuan139 建议不同的问题分不同的 issue 讨论。我把标题做了调整，手势的问题继续在这里讨论，其它问题可以另开 issue，这样比较方便追踪和解答
谢谢理解

**Comment by acton393** [comment]
hi  @haicuan139   这个issue 暂时先关闭了，0.10 版本SDK 可以做下尝试， 如果仍然有上述问题，欢迎 继续提issue,方便的话，单个问题尽量开一个issue, 谢谢~~
