### ISSUE TITLE
[proposal] Support rem/vw/vh CSS length values

### ISSUE THREAD

**Issue by Jinjiang** [alibaba/weex#1937]
## background

Currently we can just describe length through a number which are the pixels of the length. In many situation, for example when we want to set a length to 50% of the screen's width or height, it need to make a calc.

## Purpose

This proposal is for writing CSS length with more popular and standard values more easily.

## Details

Developers can use `100vw`, `2rem` in `<style>` and inline style. At the same time in JavaScript runtime. `weex.unit.vw(100)`, `weex.unit.rem(2)` are both OK.

refs: [Distance Units in W3C CSS Values and Units Module](https://www.w3.org/TR/css-values-3/#lengths)

### Changes for Render Layer

(nothing to change)

### Changes for JS Runtime

* Pass through these CSS values in Weex transformer: `vw`, `vh`, `rem`, `cm`, `mm`, `q`, `in`, `pt`, `pc`, `px`
* Calculate each CSS units and set them into `weex.unit` instance object.

### Changes for Tools

(nothing to change)

### Changes for Dev Experiences

* Developers can use `100vw`, `3rem`... in `<style>` and inline style.
* Developers can use `weex.unit.vw(100)` ... in `<script>` and JavaScript lib files.

## Notes

(none)

**Comment by Jinjiang** [comment]
update: recommend `rem` & `vw` only, and change `100 * weex.unit.rem` to `weex.unit.rem(100)`

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
