### ISSUE TITLE
weex onclick参数中有{{}}变量，js中获取不到变量值

### ISSUE THREAD

**Issue by ming1014** [alibaba/weex#1946]
template:

      <slider class="slider" interval="{{intervalValue}}" auto-play="{{isAutoPlay}}" >
        <indicator class="indicator"></indicator>
        <div class="slider-pages" repeat="{{itemList}}">
          <image class="thumb" src="{{picUrl}}" onclick="goPage('{{linkUrl}}', $event)"></image>
          <text class="img-title">{{title}}</text>
        </div>
      </slider>

js:

      goPage:function(linkUrl,e){
        log.error("logError:...."+linkUrl);//这里打印出来的是undefined 获取不到linkUrl的值
        windVane.open(linkUrl);
      }

**Comment by samyzhang** [comment]
参数格式写错了；
如：
<cell class="list_cell" repeat="{{itemList}}">
              <div class="desc_arrow" onclick="jumpPage(src,name)">
                  <text class="item_desc">{{name}}</text> 
              </div>
          </cell>

**Comment by Jinjiang** [comment]
cc @songsiqi

**Comment by Jinjiang** [comment]
@songsiqi 我简单写了个例子 http://dotwe.org/1c7da7020df1b8e5ae34e18205b620db
`onclick="goPage('{{linkUrl}}', $event)"` 会被转换成 `"events": { "click": "Page('{{linkUrl}}', $even" }` 感觉比较诡异……
生成码链接：http://dotwe.org/raw/dist/1c7da7020df1b8e5ae34e18205b620db.js

**Comment by songsiqi** [comment]
@Jinjiang 具体逻辑是这样的：

https://github.com/weexteam/weex-templater/blob/master/lib/validator.js#L375

`weex-templater` 发现 `goPage('{{linkUrl}}', $event)` 里面有 `{{...}}` ，认为是个表达式，所以把前面和后面各去掉了两个字符，所以会变成 `Page('{{linkUrl}}', $even`

**Comment by Jinjiang** [comment]
但即便这样，`{{}}` 如果在字符串里的话就不应该再转了，而是应该保留原本的字符串值

**Comment by Jinjiang** [comment]
经过讨论，这个细节的处理代价比较高，并且属于误操作，所以暂不做更多的改进和修复了
p.s. 我们已经开始支持 Vue 2.0 了，在 Vue 的语法中是没有这个问题的，可以更多关注一下
谢谢理解和支持
