### ISSUE TITLE
微信，QQ登录分享，微信支付，地图应用。没有这些插件吗？

### ISSUE THREAD

**Issue by ztools** [alibaba/weex#1947]
我现在正在react-native和weeb之间徘徊，喜欢vue.js。但是找不到如标题的这些插件。根本没有办法做一个应用来。

**Comment by Hanks10100** [comment]
这些组件、模块和具体的应用或者业务关系比较大，Weex 框架本身不包含这些功能，从能力上讲是支持的，未来在社区中可能会有。

 > 注： 是 Weex 不是 weeb

**Comment by ztools** [comment]
bye, weex

**Comment by iloveyo123u1** [comment]
@ztools  welcome to ionic  http://ionic.io/
