### ISSUE TITLE
Android 的okhttp 依赖冲突

### ISSUE THREAD

**Issue by fatcatdown** [alibaba/weex#1948]
我在扩展WEEX android源码时遇到一个依赖兼容性问题。
1、在原生端加入野狗实时的AndroidSDK
    compile 'com.wilddog.client:wilddog-sync-android:2.0.3'
   该SDK使用okhttp2.7,导致依赖变化
com.squareup.okhttp:okhttp-ws:2.7.0
com.squareup.okhttp:okhttp:2.7.0
com.squareup.okio:okio:1.6.0
WEEX原本的依赖是：
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.okhttp:okhttp-ws:2.3.0'
    compile 'com.squareup.okio:okio:1.0.1'
部分接口变化，导致Andoid的playground和debug功能报错

Error:(74, 60) 错误: 找不到符号
符号:   类 PayloadType
位置: 接口 WebSocket
Error:(60, 3) 错误: HotRefreshManager.WXWebSocketListener不是抽象的, 并且未覆盖WebSocketListener中的抽象方法onMessage(ResponseBody)
Error:(68, 5) 错误: 方法不会覆盖或实现超类型的方法
Error:(73, 5) 错误: 方法不会覆盖或实现超类型的方法
。。。。。

尝试按照新接口修改代码，可以启动，但调试无法使用，怀疑是
    compile 'com.taobao.android:weex_inspector:0.0.8.1'
中引用的weex_inspector也使用了okhttp引起的问题。

若使用
compile ('com.wilddog.client:wilddog-sync-android:2.0.3'){
        exclude group: 'com.squareup.okhttp'
        exclude group: 'com.squareup.okio'
}则强制使用2.3版则野狗异常。

请问是否有办法可以解决。

**Comment by fatcatdown** [comment]
后来试了一下，统一将okhttp升级到2.7.0，然后修改playground,sdk,debug的对应接口，程序可浏览页面，但若开启devtools进行debug，则引起崩溃。问题很可能还是在compile 'com.taobao.android:weex_inspector:0.0.8.1'，在git上找不到该版本的源码，所以无法进行修改

**Comment by littleseven** [comment]
@fatcatdown 感谢反馈，okhttp自身的兼容性问题在这里确实是个麻烦，devtools在这方面做了些努力，分别适配了两个版本的okhttp库分别是
```
dependencies {
   compile 'com.squareup.okhttp:okhttp:2.3.0'
   compile 'com.squareup.okhttp:okhttp-ws:2.3.0'
    ...
}
```
和

```
dependencies {
  compile 'com.squareup.okhttp3:okhttp:3.4.1'
  compile 'com.squareup.okhttp3:okhttp-ws:3.4.1'
   ...
}
```

确保所引用的版本与上述两个版本其一兼容即可

**Comment by xujinyang** [comment]
![image](https://cloud.githubusercontent.com/assets/4199903/22821102/9a4efd00-efb4-11e6-88e3-6eb3f770aa7d.png)

官方文档给的链接有问题，如果项目中又使用okhttp3有使用okhttp会出现兼容问题，导致debug 连接不上，都换成okhttp3就好

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
