### ISSUE TITLE
Integrate to Android : more than one library with package name com.taobao.weappplus_sdk

### ISSUE THREAD

**Issue by ahtohlcy** [alibaba/weex#1951]
My Platform is Mac 
<img width="586" alt="wx20161220-013724 2x" src="https://cloud.githubusercontent.com/assets/4382827/21322614/edcd6b26-c654-11e6-8ee7-054c0c1a5dd4.png">

Android Studio version infomation:
<img width="400" alt="wx20161220-013350 2x" src="https://cloud.githubusercontent.com/assets/4382827/21322652/116661aa-c655-11e6-8e56-74285842fe9b.png">

When I created a new  Android Project ,By default, Android Studio(2.2.3) will integrate 
the Compile Sdk Version : API 25 Android 7.1.1(Nougat)
and 
the Build Tools Version 25.0.2

# And than......
**# Official Chinese documents recommended for the following operation**：

             app 的build.gradle 中添加如下依赖:compile project(':weex_sdk')
But throw an error: **_more than one library with package name com.taobao.weappplus_sdk_**

I solved the issue when  commented on this line of code

# My Solution.......
**COMMENT "compile project(':weex_sdk')"**

`
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'
    defaultConfig {
        applicationId "com.xdcoder.eyurose"
        minSdkVersion 19
        **targetSdkVersion 23 //25 -> 23**
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    **compile 'com.android.support:appcompat-v7:23.1.0'  //25.1.0 -> 23.1.0**
    testCompile 'junit:junit:4.12'

    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.alibaba:fastjson:1.1.46.android'
    compile 'com.taobao.android:weex_sdk:0.5.1@aar'

    compile 'com.squareup.picasso:picasso:2.5.2'

    //compile project(':weex_sdk')
}

`
<img width="656" alt="wx20161220-012536 2x" src="https://cloud.githubusercontent.com/assets/4382827/21322453/0e605016-c654-11e6-8117-26245c6913cf.png">

<img width="1231" alt="wx20161220-014823 2x" src="https://cloud.githubusercontent.com/assets/4382827/21322986/75809952-c656-11e6-8feb-334f8873fca6.png">

**Comment by sospartan** [comment]
Chinese document is out of date. We suggest you use remote dependency instead.
And  you can comment under chinese doc to notice author to fix that.
