### ISSUE TITLE
同一局域网下 playground 扫码总是报“network error”

### ISSUE THREAD

**Issue by Lx15** [alibaba/weex#1957]
确保了手机和电脑 运行在同一个局域网，并且同一个项目在电脑浏览器可以运行正常，但是 用android 的 playground 扫码就是 会出现“network error”.

 为了解决这个问题我尝试过 1: 电脑 开wifi 给手机连 2. 手机开热点给电脑连 3. 手机和电脑通连一个wifi ,并保证没有进程占用8082端口，但是这三种情况都是 不可以。另外我尝试 更换了电脑、手机、重装playground 还是不可以，为什么感觉只有我不可以？

另外 运行的项目就是 weex init 的简单demo。

这个问题真的让我很困扰，感觉都说只要保证 在同一个局域网就好了。可能会是什么原因呢？

**Comment by DangDangHellen** [comment]
你试着ping一下手机和电脑，看能不能Ping通？

**Comment by Lx15** [comment]
![image](https://cloud.githubusercontent.com/assets/14272220/21352626/525fe660-c6fd-11e6-80c4-6d3fa5afc780.png)
我测试的情况是这样的，是在 电脑和手机同时连同一个wifi 的情况下。

**Comment by TJHVigour** [comment]
有可能你安装了虚拟机,这样的话weex在运行的时候把主机的IP地址弄成了虚拟机的虚拟网卡的地址了,虽然你和电脑连接的是同一个WiFi 但是你们的ip地址不一样,只要去网络设置中禁用虚拟网卡,重新运行即可

**Comment by Jinjiang** [comment]
翻墙代理、防火墙 的 因素也排除一下吧，我自己也在这几个地方栽过……

**Comment by Lx15** [comment]
多谢大家。但是我在关掉翻墙、防火墙下，并且 没有装虚拟机的情况下 去扫码还是这个错误。我用 ipconfig 看到也只有一个无线网络连接，  并且ping 手机 也是可以。

**Comment by Lx15** [comment]
目前的情况是 同一份代码 在同学电脑上扫码是可以的， 但是在我自己电脑上扫码是 ‘network error’,所以应该是我电脑的问题，我在重启电脑，关闭 虚拟机、翻墙、防火墙的前提下 打开运行环境，在浏览器中运行是好的 但结果在 手机扫码'network error'

**Comment by Jinjiang** [comment]
确实比较难定位了，印象中 windows 系统里还有类似“局域网可访问”、“公共网络可访问”、“家庭可访问”之类的选项
我个人的建议是
1. 你先测试一下 npm 里的 serve 看看启动一个本地服务器，然后手机是否可以正常访问
2. 用别的扫码软件扫一下之前出错的那个二维码，看看二维码代表的那个 url 是否有问题，能不能在手机的浏览器里正常访问
谢谢

**Comment by Lx15** [comment]
---------------可以扫码了--------------
原因还是防火墙的问题，之前是我并没有真的关上防火墙，我只是把360之类的关掉了，并且使用的工作网络，这样扫不出来。若是在工作网络下，并且关闭防火墙是可以扫码成功的。若是在公用网络下不用关闭防火墙也是可以扫码的。实测是这样，但是我总觉得是反的，因为我查家庭网络、工作网络、公用网络觉得应该是公用网络防火墙应该关掉才是。
找到这个问题的办法是在本地启动服务器，同局域网下用浏览器去访问服务器下的url,这时是不可以访问的，这应该就是局域网有限制，并且@Jinjang 设置一下网络设置，所以去试了一下，果然可以了。。
----好开心。 多谢大家----
