### ISSUE TITLE
header 吸附顶部怎么不起作用？

### ISSUE THREAD

**Issue by chenyunecjtu** [alibaba/weex#1959]
0.6.1 header which will stick to the top when it reaches the top of the screen ，文档上说有这个功能，如果不用list，直接div 设置position 为sticky的话可以做到，但是list 就不行，不用list的话，上拉刷新和小拉刷新在有些机子里会不起作用。有解决方法吗？

**Comment by and80506** [comment]
目前文档里已写0.6以上版本支持header,实际测试不放refresh时header可以支持悬浮效果。
```html
<template>
  <div>
    <list class="list">
      <header><text>header</text></header>
      <cell onappear="onappear" ondisappear="ondisappear" class="row" repeat="{{rows}}" index="{{$index}}">
        <div class="item">
          <text class="item-title">row {{id}}</text>
        </div>
      </cell>
    </list>
  </div>
</template>
```

但是同时放置refresh标签和header标签是，header悬浮不起作用。
```html
<template>
  <div>
    <list class="list">
      <refresh  class = "refresh-view" display="{{refresh_display}}" onrefresh="onrefresh">
        <text if="{{(refresh_display==='hide')}}"> ↓ pull to refresh </text>
        <loading-indicator class="indicator"></loading-indicator>
      </refresh>
      <header><text>header</text></header>
      <cell onappear="onappear" ondisappear="ondisappear" class="row" repeat="{{rows}}" index="{{$index}}">
        <div class="item">
          <text class="item-title">row {{id}}</text>
        </div>
      </cell>
    </list>
  </div>
</template>
```

**Comment by liujianying** [comment]
header 吸附顶部怎么不起作用
+1

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
