### ISSUE TITLE
input组件使用position:fixed时失去焦点

### ISSUE THREAD

**Issue by goodyorkye** [alibaba/weex#1960]
input组件使用position:fixed时，或者input外层使用position:fixed时，android手机playground上每输入一个字母后就会失去焦点

**Comment by lmnsg** [comment]
同样遇到这个问题

**Comment by cuanhanshansi** [comment]
https://github.com/weexteam/article/issues/112 你把这里面的<text></text>改成<input type='text' />,好像没出现你说的问题啊。

**Comment by ljuns** [comment]
我用了 input 事件就会出现这种情况，改成 change 事件就不会

**Comment by goodyorkye** [comment]
@ljuns  @lmnsg 已测试，去掉oninput事件使用onchange确实好了。
@cuanhanshansi 这个我倒没试，有空试试

**Comment by ljuns** [comment]
@goodyorkye 用 android 分支的最新版本，发现 oninput 事件可以正常使用，不会出现输入一个字符就失去焦点的问题

**Comment by goodyorkye** [comment]
@ljuns 好的
