### ISSUE TITLE
repeat 的{{$index}}不能作为参数传到函数里面吗？

### ISSUE THREAD

**Issue by DangDangHellen** [alibaba/weex#1964]
` <div class="selectnum" repeat="( index, v) in arr">
              <text value="{{v.id}}" onclick="selectfunc(arr[{{index}}].id)" class="select_player1">{{v.id}}</text>
            </div>`

`<script>
  module.exports = {
    data: {
      arr: [
      {id: 10},
      {id: 11},
      {id: 12},
      {id: 13},
      {id: 14}
      ],
      select_player:"谁会中奖呢？"
    },
    methods: {
      selectfunc: function(index){
        this.select_player = '玩家'+index;
      }
    }
  }
</script>`

点击之后没有反应

**Comment by 0326** [comment]
你的写法有问题`onclick="selectfunc(arr[{{index}}].id)"` 改成 `onclick="selectfunc(arr[index].id)"`
