### ISSUE TITLE
H5 下懒加载图片无法被动态加载

### ISSUE THREAD

**Issue by oMaten** [alibaba/weex#1965]
**环境：** Chrome@55.0
**依赖：** Weex-toolkit@0.6.4
**问题：** 在横向布局下利用 animation.transition.transform 进行横向位移动画，当移动至图片所在区域时图片不会被动态载入。

> image elements which have attribute 'i-lazy-src' were elements
   that had been preprocessed by lib-img-core, but not loaded yet, and
   must be loaded when 'appear' events were fired. It turns out the
   'appear' event was not fired correctly in the css-translate-transition
   situation, so 'i-lazy-src' must be checked and lazyload must be
   fired manually.

在 global lib 中找到这样一段注释，请问在 weex 中应该如何手动 fire 图片加载。

另外，在 `<scroller>` 组件中由于无法解决该问题 ，直接对图片进行了 preload。[注释](https://github.com/alibaba/weex/blob/6f58f89c9ec9a6962bfea0b1008b5bb1ddc3f64a/html5/render/browser/extend/components/slider/index.js#L191)

如果可以对 `<image>` 添加 `data-lazy='false'` 的属性在 `lazyimg` 中强制加载图片避免懒加载的问题，但是 hyphenated 语法会自动将该属性转成 `datalazy='false'`。

**Comment by MrRaindrop** [comment]
后续会监听 transitionend 事件并自动加载图片。在此之前可以通过以下方式手动hack:（不推荐，建议等 bugfix 的 pr）:

1. 判断环境：`this.getConfig().env.platform === 'Web'`
2. 在 web 环境下，手动在你需要触发图片加载的地方调用 `lib.img.fire()`

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
