### ISSUE TITLE
移动端如何实现点击号码拨打电话

### ISSUE THREAD

**Issue by Eric-ss** [alibaba/weex#1971]
看了一下微信端一个页面拨打电话的方式是直接一个 `<a href="tel:10086">马上拨打电话10086</a>`完成，
weex我这么写的话，a标签编译出来的是div标签，不起作用。如何实现这个功能。

**Comment by and80506** [comment]
个人理解，根据文档描述，实现一个打电话的module扩展，比如callTel。
```javascript
var event = require('@weex-module/event');
event.callTel('13175881111', function () {});
```
http://alibaba.github.io/weex/cn/doc/advanced/extend-to-android.html

**Comment by yaochenfeng** [comment]
实现自定义scheme打开操作，tel打开电话操作，类似
NSString *phoneCallNum = [NSString stringWithFormat:@"tel://%@",listingPhoneNumber ];

 [[UIApplication sharedApplication] openURL:[NSURL URLWithString:phoneCallNum]];

**Comment by Hanks10100** [comment]
@and80506 和 @yaochenfeng 说的有有道理，这个功能应该是个 module，应该由 native 提供。

不建议在 `<a>` 标签里写电话号码…… `<a>` 只是个描述界面的 DSL ，在浏览器上渲染成 `<div>` 标签，在手机上渲染成原生视图。

**Comment by WildDylan** [comment]
如果是正常开发中的，假设UIWebView作为容器中加载一个HTML

```html
<html>
<body>
<a href="tel://13888888888">Call me</a>
<body>
</html>
```

会弹出一个Alert询问是否拨打。

**Comment by Jinjiang** [comment]
`tel:` 是一种协议，就像 `mailto:` 一样，是个通用的描述方式，也是一种前端开发的习惯，确实应该支持。我们会先汇总到 #1494 然后选择一个适当的时机进行支持
谢谢
