### ISSUE TITLE
[html5] scroller和list组件是否会考虑使用浏览器自己的滚动条？

### ISSUE THREAD

**Issue by dongnaebi** [alibaba/weex#1974]
weex的以改变div的`translateY`来实现滚动的方式在很多浏览器都体验太差。

具体表现在：

1. 移动端浏览器，大多都是滚动时才把头部和底部收起，浏览器的头和底把可见范围缩小了很多，比如Safari。

2. 一些浏览器，比如chrome和流量大头微信浏览器，都实现了酷似原生的滚动，用改变`translateY`的方式在这些浏览器上享受不到很好的滚动体验。

3.有时候会滚不动？ 而且横向滚动有一定概率会和浏览器的右滑返回冲突。

weex在注重三端统一的前提下，能否也考虑各端的体验？毕竟是拿来做应用的，**使用体验还是第一**。

**Comment by Hanks10100** [comment]
如果保持了行为一致的话，可以考虑。

**Comment by MrRaindrop** [comment]
h5渲染器目前的 list/scroller 是一个重度使用的组件，但是模拟滚动的性能和体验在某些环境下确实存在问题。如果是根元素为 list/scroller，可以通过在 `weex.init` 里加上参数

 ```javascript
weex.init({
  ...
  downgrade:['root']
})
```

来使得根 list/scroller 变成浏览器原生的滚动。但是目前还不支持子元素这么做。

如果你需要使用原生滚动的非根节点 list/scroller，建议你参考主仓库里**内置组件定义的方法**[示例代码](https://github.com/alibaba/weex/blob/dev/html5/render/browser/extend/components/input.js) 自己定义一个原生滚动的 list/scroller 组件，然后通过这个仓库的打包方式自己打包一个 `browser.min.js` 出来。扩展内置组件的文档见这里：[扩展web](http://alibaba.github.io/weex/cn/doc/advanced/extend-to-html5.html)

**Comment by dongnaebi** [comment]
一用`downgrade:['root']`，slider和所有的子组件滚动都挂了。。。

**Comment by MrRaindrop** [comment]
目前降级的滚动其实就是把 list / scroller 当作普通的 div 来对待，只不过它的高度完全取决于子元素的高度，这样滚动的话就是 body 的滚动了，一般子组件的滚动应该和它没有直接关系，倒是 loading  和 refresh 的组件会受到影响...

**Comment by beghujam** [comment]
scroller的滚动条在html5中不能隐藏啊，用了scroller 在html5上右侧出现滚动条好难看，用show-scrollbar这个属性，IOS 和安卓就隐藏掉了，但是在html5上还是存在 这个如何隐藏啊

**Comment by Bob-huang-gdut** [comment]
@beghujam 请问你的问题解决了没？
