### ISSUE TITLE
wxc-tabbar

### ISSUE THREAD

**Issue by frankxiongsir** [alibaba/weex#1977]
按照官方文档配置了tabbar的item，如下
`module.exports = {
        data: {
            tabItems: [
                {
                    index: 0,
                    title: "任务大厅",
                    titleColor: 0x0,
                    icon: "",
                    image: "http://gtms01.alicdn.com/tps/i1/TB1qw.hMpXXXXagXXXX9t7RGVXX-46-46.png",
                    selectedImage: "http://gtms04.alicdn.com/tps/i4/TB16jjPMpXXXXazXVXX9t7RGVXX-46-46.png",
                    src: "modules/test.js",
                    visibility: "visible"
                },
                {
                    index: 1,
                    title: "我的任务",
                    titleColor: 0x0,
                    icon: "",
                    image: "http://gtms03.alicdn.com/tps/i3/TB1LEn9MpXXXXaUXpXX9t7RGVXX-46-46.png",
                    selectedImage: "http://gtms02.alicdn.com/tps/i2/TB1qysbMpXXXXcnXXXX9t7RGVXX-46-46.png",
                    src: "modules/test.js",
                    visibility: "hidden"
                },
                {
                    index: 2,
                    title: "个人中心",
                    titleColor: 0x0,
                    icon: "",
                    image: "http://gtms01.alicdn.com/tps/i1/TB1B0v5MpXXXXcvXpXX9t7RGVXX-46-46.png",
                    selectedImage: "http://gtms04.alicdn.com/tps/i4/TB1NxY5MpXXXXcrXpXX9t7RGVXX-46-46.png",
                    src: "modules/test.js",
                    visibility: "hidden"
                }
            ]
        }
`
可是npm run serve 显示出来的页面每个item页面都不显示
![1e2b8e42-64c2-411c-9fd0-3c968fb27762](https://cloud.githubusercontent.com/assets/11530882/21386198/b00844f6-c7ac-11e6-9ecf-bf8dd6f73535.png)

**Comment by ljuns** [comment]
@frankxiongsir 我用了最新的 android 分支，解决了 tabbar 显示的问题，结果 list 却不显示了
