### ISSUE TITLE
希望支持引入公共样式文件以及样式简写

### ISSUE THREAD

**Issue by dongnaebi** [alibaba/weex#1983]
.we文件能以`<style src="../style/main.css"></style>`引入样式，但再写<style>标签就无效了。不能引入公共样式文件，很多代码都是无用的重复的代码，对代码洁癖的人简直是折磨。
然后样式又不能简写，经常不自觉的写错，很痛苦。

用weex写业务层的几乎都是前端出身的吧。

**Comment by Hanks10100** [comment]
可以考虑支持多个 `<style>` 标签，如此设计本意是想限制全局样式的使用。

样式不支持简写的话，是考虑到包含了数据绑定的情况：

```html
<template>
  <div style="border-color: 1px solid {{color}}"></div>
</template>

<script>
  module.exports = {
    data: {
      color: 'red'
    }
  }
</script>
```
允许给样式中某一部分添加数据绑定的话，将很难实现样式简写。不过后期也会考虑实现这个特性。

**Comment by and80506** [comment]
支持引入公共样式文件可以减少很多冗余代码，另外提升可维护性；目前我的项目中，不得以而为之，只能先把公共样式每个页面都复制一份。

目前的情况本来就不是所有css特性都能直接直接使用，我的使用习惯是用这个样式之前先查文档。在很多样式比如line-height都没有支持得很好的情况下，没有必要花精力去做css样式简写的支持，既然不使用简写可以达到目的，无非是改变使用习惯的问题。

**Comment by Jinjiang** [comment]
全局样式的弊端非常多，我们对这部分功能持相对谨慎和观望的态度，但将来可以通过 `<style src="xxx.css">` 多份组件共享一部分样式

**Comment by Jinjiang** [comment]
更多讨论可以移步 weexteam/weex-loader 仓库，这里我先关掉了
感谢理解和支持：）
