### ISSUE TITLE
js获取值问题

### ISSUE THREAD

**Issue by tinylpc** [alibaba/weex#1986]
mWXSDKInstance.render("WXSample", WXFileUtils.loadFileContent("hello.js", this), map, "123", -1, -1, WXRenderStrategy.APPEND_ASYNC);

参数中的options（代码中的map）、jsonInitData（代码中的"123"）,这两个值可以在hello.js文件中获取到吗，若可以，怎么获取？

**Comment by icepy** [comment]
this.$getConfig()

**Comment by tinylpc** [comment]
具体怎么获取啊，config里面有好多参数，试了很多都没获取到 @icepy
