### ISSUE TITLE
关于input的问题

### ISSUE THREAD

**Issue by Demon-liao** [alibaba/weex#199]
当我插入input框的时候遇到以下几个问题：
1.input获取光标的时候，弹出键盘，然后点击任何其他区域，键盘都无法缩回去。
2.点击手机键盘的回车键的时候，竟然是换行而不是失去焦点让键盘缩回去。input按照是不应该出现换行才对。能换行的应该是textarea。
3. 如果是因为原生的限制问题，把输入框都统一为input了，那是不是在内上面添加属性，可以控制它是否执行换行。

**Comment by ustccq** [comment]
同时android下没有光标闪烁，而h5和ios下都有

**Comment by sospartan** [comment]
@ustccq 你使用的是什么版本的SDK,并且最好能贴一下你得相关代码

**Comment by ustccq** [comment]
大概三四周前安装的。windows下npm安装的。同时二维扫码安装了playgroud生成的weex应用
cmd中weex --verison显示
info 0.4.5

weex --qr xxx.we显示二维码，后android手机上扫码打开，无光标。
android手机是小米note pro，版本为5.1.1 LMY47V。
又用酷派大神F2手机打开一样无光标，版本为4.4.2，其上安装的是用AS编译playgroud生成的weex

**Comment by sospartan** [comment]
@ustccq 光标的问题已经修复,请使用android分支的代码进行编译

**Comment by Jinjiang** [comment]
这个问题长期没有讨论，这里先做关闭处理了，如果仍有问题可以随时继续留言讨论
谢谢

**Comment by cokeknight** [comment]
1.input获取光标的时候，弹出键盘，然后点击任何其他区域，键盘都无法缩回去。  这个问题解决了吗

**Comment by sospartan** [comment]
@cokeknight 这个无论是h5,还是iOS都是一样的,因为input一直持有焦点,所以不会关闭键盘,这个行为本身是一致的.
另外,主动获取/移除焦点的方法正在开发中.

可以参考这个例子:
```
<template>
  <div>
    <input></input>
    <text>text</text>
  </div>
</template>
```

**Comment by liuzhiyi1992** [comment]
input在输入完成后
1.无法通过Return键提交内容（重点）
2.无法点击空白区域取消第一响应者
