### ISSUE TITLE
playground app download link is broken

### ISSUE THREAD

**Issue by lhorie** [alibaba/weex#1991]
Reproduction steps:

- using an Android phone (HTC One), go to https://alibaba.github.io/weex/download.html as recommended on the tutorial page
- click on "weex playground app android apk"

expected:

- download an APK

actual:

- nothing happens

---

QR code also leads to a github 404 link. Reproduction steps:

- use a qr scanner on the qr code on the page above

expected:

- navigate to a page

actual:

- github 404 error

**Comment by DoranYun** [comment]
Try this URL instead. http://alibaba.github.io/weex/playground_download.html

The result of the QR code is this url.

**Comment by Jinjiang** [comment]
This url will detect the OS platform and jump to iOS App Store or Android APK file.
And currently this APK file is: http://appdownload.alicdn.com/publish/weex_playgroud/latest/weex_playgroud_10006024.apk

If both the link or QRCode still doesn't work, please go here directly.

Thanks.
