### ISSUE TITLE
0.9.4 tabbar 直接没有效果

### ISSUE THREAD

**Issue by ljuns** [alibaba/weex#1993]
集成到android平台，之前版本都可以运行正常，试了0.9.4直接白了，什么都不见了

**Comment by boboning** [comment]
@ljuns , 麻烦给一个android上的截图，便于我们排查问题，我们使用0.9.4是正常的。

**Comment by ljuns** [comment]
@boboning 如果用 0.8.0版本就是这样的，显示了一半
![wechatimg1](https://cloud.githubusercontent.com/assets/13607918/21515889/5a944d8c-cd0e-11e6-92b9-c793b33283e2.jpeg)
用 0.9.4 就直接整个页面空白。
我是这样引的 compile 'com.taobao.android:weex_sdk:0.9.4@aar'

**Comment by sunny66666666** [comment]
我添加的是 这些  compile 'com.taobao.android:weex_sdk:0.5.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.alibaba:fastjson:1.1.46.android' 也是 进去什么都不显示。。在Android studio中集成 没有东西

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
