### ISSUE TITLE
webstorm集成的terminal里生成的二维码太大太大了，希望能小一点。

### ISSUE THREAD

**Issue by mqhe2007** [alibaba/weex#1998]
不仅太大，而且变形，导致手机的playground一直扫描不成功。
[预览图](http://qingjin.me/wp-content/uploads/2016/12/QQ%E6%88%AA%E5%9B%BE20161223111146.png)

**Comment by oMaten** [comment]
有个 `weex /src/index.we --smallqr` 参数可以解决

**Comment by exolution** [comment]
webstorm是指那个ide插件里的二维码么

**Comment by Jinjiang** [comment]
确实有点大，不过在命令行里显示二维码本身有一定的局限性，这个可能需要重新想别的办法
建议更多讨论在 `weex-toolkit` 仓库的 issues 里继续展开吧 https://github.com/weexteam/weex-toolkit/issues
这里我先关掉了，谢谢理解和支持
