### ISSUE TITLE
如果对input的数据进行双向绑定操作？

### ISSUE THREAD

**Issue by Demon-liao** [alibaba/weex#200]
需求是这样的，当我在input里面输入内容的时候，于data里面的某个值可以直接绑定一起，不用通过事件再次赋值。改如何操作，vue.js里面有类似的 v-model , 不知道weex里面可否有这样的？

**Comment by djyde** [comment]
+1

**Comment by 13032519955** [comment]
> 是的我们正在尝试设计解决中，比较可能的做法是对于特殊的传统“双向绑定”的场景，当表单被用户修改时，可以直接更新虚拟dom里的值，避免重复判断。请留意我们未来的更新
马上2019年了 还是这个样子  我踩了一通宵的坑 mmp
