### ISSUE TITLE
weex中的手势提供的changedTouches怎么使用？

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2006]
我设置了touch事件，但是在回调里不知道怎么使用changedTouches，官方文档的实例不够清晰啊。

      handleTouchstart: function(e) {
        console.log("d:"+e.changedTouches);
        console.log("d:"+changedTouches);
        console.log("eventProperties:"+e.screenX);
      }

我这样试的几种都不行啊

**Comment by DoranYun** [comment]
`changedTouches` 是一个数组，其子元素是对象，包含这些属性identifier,pageX,pageY,screenX,screenY。

使用方式类似这样

` e.changedTouches[0].identifier`

**Comment by shangcongrong** [comment]
@DoranYun ，你这种方法似乎也并不行。错误是，
Uncaught TypeError: Cannot read property '0' of undefined(…)
你那边可以吗？

**Comment by DoranYun** [comment]
@shangcongrong 刚才确认了一下，H5 touch 手势没有 changedTouches 属性。

**Comment by DoranYun** [comment]
我稍后在文档里补充一下

**Comment by shangcongrong** [comment]
@DoranYun ，手机上试了下可以了，这个issue可以关掉了。
