### ISSUE TITLE
如何配合现有的APP？

### ISSUE THREAD

**Issue by Demon-liao** [alibaba/weex#201]
我们公司目前有一个app了。目前想用weex扩展APP里面的应用模块。那问题出来了：
app已经引用了weex的SDK，原来就有登录，目前需要用weex做一个小应用类似抽奖的模块插入app内部，抽奖操作需要用户登录才可以。那需要怎么操作才能结合一起？
因为跟APP之间的数据交互不仅仅只有登录这一个，还有各种操作，请问如果扩展呢？

之前做H5页面的时候，我们用WebViewJavascriptBridge来实现原生和H5的交互，现在weex因为是最终是编译成原生控件的，WebViewJavascriptBridge肯定行不通了，那是否有其他方法可以扩展和对接呢？

**Comment by Mhina007** [comment]
WXBridgeManager.getInstance().callback(instanceId,callbackId,paramMap);
callbackId是在那里定义的
