### ISSUE TITLE
Android Studio 的Weex插件不能用

### ISSUE THREAD

**Issue by AndyFightting** [alibaba/weex#2010]
<img width="484" alt="2016-12-24 1 16 59" src="https://cloud.githubusercontent.com/assets/12689782/21465367/8cf87860-c9db-11e6-8c70-26f5a02ff8a4.png">

Weex插件版本0.5.4，Android Studio 的版本2.2.2，Mac OS 10.11.5

**Comment by Darin726** [comment]
@AndyFightting 这个错误的原因是javafx 组建找不到, 能否升级到 java8再次尝试一下

**Comment by AndyFightting** [comment]
我的 JDK Location 是 `/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`,这已经是java8 了吧？

**Comment by Darin726** [comment]
@AndyFightting 昨天升级了一个新的版本修复了依赖问题, https://plugins.jetbrains.com/idea/plugin/8460-weex, 可以直接在 Android studio 里升级

**Comment by AndyFightting** [comment]
嗯，1.0版本可以用了，辛苦了
