### ISSUE TITLE
weexpack build android 无法生成apk

### ISSUE THREAD

**Issue by kyjo2014** [alibaba/weex#2011]
weexpack run android 能够在AS的模拟器上运行apk，但是用build进行打包的时候会出现
`ts@1.0.15
npm WARN helloworld@1.0.0 No repository field.

> helloworld@1.0.0 build H:\github\weex-demo\helloworld
> webpack

Hash: d16d92df9b8179ff6941
Version: webpack 1.14.0
Time: 1602ms
   Asset     Size  Chunks             Chunk Names
index.js  8.85 kB       0  [emitted]  index
    + 4 hidden modules

 => Will start Android app
============build config============
AppId=>com.alibaba.weex
AppName=>WeexApp
SplashText=>Hello
Weex
WeexBundle=>index.js
if you want to change build config.please modify android.config.json
 => Building app ...
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。`
无法完成打包

**Comment by exolution** [comment]
weexpack run 正常是么？那你先用run吧 run也是会打出apk包的（位置文档里有提到）run包含build的逻辑。
我看下build有啥问题～

**Comment by exolution** [comment]
build的问题已经修复了 请更新到0.2.5

**Comment by MaryWu** [comment]
if you had further questions on weexpack, pls go to this place https://github.com/weexteam/weex-pack/issues.  thanks
