### ISSUE TITLE
element 红通通问题

### ISSUE THREAD

**Issue by AndyFightting** [alibaba/weex#2012]
用webstorm开发的时候，用 element 标签包装自定义组件的时候红通通的一片啊...虽然不影响运行。有人知道咋回事吗？
<img width="554" alt="2016-12-25 5 03 56" src="https://cloud.githubusercontent.com/assets/12689782/21470449/ef2bfce8-cac4-11e6-8b24-3d2d497f80ba.png">

**Comment by Jinjiang** [comment]
你用了什么编辑器插件或语法高亮的工具吗？
这个问题先忽略吧，可能插件没做好，没有支持 element 标签识别

**Comment by AndyFightting** [comment]
没用什么插件，好吧，我先忽略了。

**Comment by misakuo** [comment]
我的锅，找时间更新下插件
