### ISSUE TITLE
js更新后加载不及时问题

### ISSUE THREAD

**Issue by AndyFightting** [alibaba/weex#2019]
问题是这样的：比如我自定义了一个组件 A，然后我在 main 组件里引用了A, 当修改A的时候必须要在main里也修改些东西，然后运行才会显示A修改后的效果。(我已经开启监听和服务的了，无论单独修改A,还是main 都会自动更新转成js，问题就是如果不修改main的话，再运行不会自动加载更新后的A 的js) 所以结果就是每当修改A后，也要在mian里随便改点什么然后再运行 (iOS集成Weex真机运行)

**Comment by Jinjiang** [comment]
weex-toolkit 本身的 watch 功能比较简陋，确实存在你说的问题
weex-loader 在 webpack watch 的情况下应该是没有问题的

**Comment by AndyFightting** [comment]
好吧，我就先这样用了
