### ISSUE TITLE
error koa-serve-static@0.0.1: The engine "node" is incompatible with this module. Expected version "1.x.x".

### ISSUE THREAD

**Issue by aguegu** [alibaba/weex#2020]
<img width="1171" alt="screen shot 2016-12-26 at 15 56 21" src="https://cloud.githubusercontent.com/assets/1559791/21478194/f232c42a-cb83-11e6-8830-03c6970e6859.png">

是 node 7.3 还是 yarn 0.18.1，更新步子迈太大扯到蛋了么？

系统依赖着一块，能不能更具体一些？

**Comment by exolution** [comment]
我试了下 node 7.3（npm3.10.10）安装是可以成功的~
建议用npm安装~

**Comment by Jinjiang** [comment]
@aguegu 问题是否已经解决？

**Comment by aguegu** [comment]
![image](https://cloud.githubusercontent.com/assets/1559791/21792682/6a11a0d0-d726-11e6-8955-d6d41e615be8.png)

感觉并没有，淘宝源感觉也不是很稳定的感觉。有别的朋友帮忙验证么？

**Comment by zxm9988** [comment]
我也出现这个问题

**Comment by limichange** [comment]
![image](https://cloud.githubusercontent.com/assets/1947344/21962073/95a5e84e-db56-11e6-94d0-fbb9822f4c07.png)
也出现了这个问题

**Comment by limichange** [comment]
似乎最新版的脚手架`weex init project-name`不管用yarn和npm安装都会出现问题。
希望你们能测试一下，谢谢。

**Comment by JackPu** [comment]
@exolution @Jinjiang  用yarn确实安装有问题，用 npm 安装 没有问题。
node : 6.0.0
npm : 3.8.6

**Comment by JackPu** [comment]
@limichange yarn的问题我们会及时排查的，建议你先使用npm安装

**Comment by limichange** [comment]
@JackPu THX.

**Comment by cooliean** [comment]
我也遇到这个报错了。没有办法安装
yarn global add weex-toolkit

**Comment by limichange** [comment]
@cooliean 
```bash
$ yarn global add weex-toolkit@beta
```

**Comment by YangFan789** [comment]
我也遇到了这个错误，用npm安装成功了
```
PS E:\Repository\Workspace\Helloweex\awesome-project> yarn
yarn install v0.20.3
info No lockfile found.
[1/4] Resolving packages...
warning serve > jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning serve > jade > transformers@2.1.0: Deprecated, use jstransformer
warning weex-devtool > koa-serve > koa-send > mz > native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
[2/4] Fetching packages...
error koa-serve-static@0.0.1: The engine "node" is incompatible with this module. Expected version "1.x.x".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by allentong** [comment]
I'm using ` yarn install --ignore-engines ` to use yarn to install for the time being.

**Comment by mymmoonoa** [comment]
真的是可以的， 时间过去这么久还没解决。
我也遇到了这个问题，还卸载了nodejs重新下了个低版本的

**Comment by swan488** [comment]
yarn install --ignore-engine 可以install 但是Playground app扫过QR code之后出来network error, 这是因为 ignore-engine吗 还是我需要做些别的东西？

**Comment by swan488** [comment]
也试过了 npm install -g  weex-toolkit@beta 但是还出现之前的error, npm 5.3.0, yarn 0.24.6, nodev8.4.0

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
