### ISSUE TITLE
关于跳转和关闭页面的一些问题

### ISSUE THREAD

**Issue by myyeshang** [alibaba/weex#2023]
一个基本的需求，登录之后结束掉当前页面，到下一个页面。如果是普通的跳转，那么安卓上按返回键就跳回到登陆页面了，这样很不友好，是否有方法finish掉上一个，或者以识别的方式，阻断当前页面的返回事件呢？

**Comment by Jinjiang** [comment]
先汇总到 #1961 讨论吧，谢谢理解：）
