### ISSUE TITLE
Android Weex push 后怎么隐藏 ActionBar ？

### ISSUE THREAD

**Issue by AndyFightting** [alibaba/weex#2026]
Android Weex push 后怎么隐藏 ActionBar ?  wxc-navpage height 我设置为0了，在iOS上是没有问题的。Android 的App Theme 我也设置成 NoActionBar 的了，就是通过Weex push 一下又出来了，请问这个怎么隐藏呢？
<img width="300" alt="aa" src="https://cloud.githubusercontent.com/assets/12689782/21482781/5bf99936-cbb3-11e6-8af4-8812c411cc3e.png">

**Comment by AndyFightting** [comment]
Hi, @acton393 , @Jinjiang  这个问题能看一下吗？我看论坛里也有人问这问题，但没人回答。当Android 的 app  theme 设置成 NoActionBar 了， weex push 的时候能不能不显示ActionBar呢？

**Comment by boboning** [comment]
@AndyFightting ，Android暂时还不支持隐藏导航栏，隐藏导航栏我们以后的设计方案是：在你加载的url中拼接相应的参数（例如：navbar_hidden=true），进入容器自动隐藏导航栏，这样的话，您拿到的应该是整个屏幕的渲染区域。

**Comment by AndyFightting** [comment]
哦，好的👌

**Comment by caijingpeng** [comment]
@AndyFightting 现在解决了吗

**Comment by AndyFightting** [comment]
@caijingpeng  没有继续看了

**Comment by Pumpe** [comment]
这个问题现在解决了吗

**Comment by w11p3333** [comment]
@boboning   请问下iOS下怎么自定义或者隐藏导航栏

**Comment by zhaoji223** [comment]
@AndyFightting  老哥，问题解决了吗？
