### ISSUE TITLE
framework-main.js 是依赖哪些文件产生的?

### ISSUE THREAD

**Issue by zjuwjf** [alibaba/weex#2030]
在实际开发中, 遇到一些问题, 想了解main.js的设计流程, 但是可读性不高, 请问是否有原始的framework的 包可供阅读?

**Comment by icepy** [comment]
@zjuwjf 看https://github.com/alibaba/weex/tree/dev/html5/frameworks

**Comment by zjuwjf** [comment]
@icepy 感谢!
