### ISSUE TITLE
怎么同步调用和返回JSObject对象

### ISSUE THREAD

**Issue by myth2loki** [alibaba/weex#2036]
第一个问题：如何可以写成这样的方式？ 就像var username= module.getUsername();其中moudle是自定义模块。
第二个问题：如何在回调函数中直接返回一个Object对象。moudle.getInfo(function(obj){});其中obj是一个{a:a,b:b,c:c,...}的对象。

**Comment by Jinjiang** [comment]
第一个问题见 #1677 我们正在开发中
第二个问题是个纯 Objective-C 的问题，查阅一下相关资料就可以了
我随意 Google 了两个
http://stackoverflow.com/questions/18728228/generate-js-object-literal-in-objective-c
http://nshipster.com/javascriptcore/

**Comment by myth2loki** [comment]
@Jinjiang 第二个问题，不好意思，我使用的是android，试了以下代码：
WXJSObject obj = new WXJSObject(WXJSObject.JSON, "{a:1, b:2}");
jsCallback.invoke(obj);
返回的任然是一个包含"{a:1, b:2}"字符串的object

**Comment by Jinjiang** [comment]
Android 源代码里已经有很多例子了，自己搜一下参考吧，比如 https://github.com/alibaba/weex/blob/dev/android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java#L759
