### ISSUE TITLE
weex sdk导入报错

### ISSUE THREAD

**Issue by sunzhongliangde** [alibaba/weex#2037]
我使用了生成SDK的方式导入到项目当中，按照步骤，导入了依赖环境，但是编译出错
开发工具：xcode7.3
weexsdk版本：0.9.4

但是，我之前使用的是0.7.x的weex sdk版本就没有报错，今天给sdk升级了一下就报错了，然后我重新新建了一个项目，也是编译报错了，这是什么原因

```
Undefined symbols for architecture x86_64:
  "_GLKMatrix4Identity", referenced from:
      -[WXCanvasComponent viewDidLoad] in WeexSDK(WXCanvasComponent.o)
  "_GLKTextureLoaderApplyPremultiplication", referenced from:
      -[WXCanvasComponent getTexture:] in WeexSDK(WXCanvasComponent.o)
  "_OBJC_CLASS_$_GLKBaseEffect", referenced from:
      objc-class-ref in WeexSDK(WXCanvasComponent.o)
  "_OBJC_CLASS_$_GLKTextureLoader", referenced from:
      objc-class-ref in WeexSDK(WXCanvasComponent.o)
  "_OBJC_CLASS_$_GLKView", referenced from:
      objc-class-ref in WeexSDK(WXCanvasComponent.o)
  "___gxx_personality_v0", referenced from:
      -[WXRoundedRect initWithRect:topLeft:topRight:bottomLeft:bottomRight:] in WeexSDK(WXRoundedRect.o)
      Dwarf Exception Unwind Info (__eh_frame) in WeexSDK(WXRoundedRect.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cxfeng1** [comment]
@sunzhongliangde 先手动链接一下GLKit让编译通过， 我看到podspec里是有写依赖的， 我们再检查一下。

**Comment by sunzhongliangde** [comment]
@cxfeng1  引入了GLKit也还是编译错误

`Undefined symbols for architecture x86_64:
  "___gxx_personality_v0", referenced from:
      -[WXRoundedRect initWithRect:topLeft:topRight:bottomLeft:bottomRight:] in WeexSDK(WXRoundedRect.o)
      Dwarf Exception Unwind Info (__eh_frame) in WeexSDK(WXRoundedRect.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

我是按照 [https://open.taobao.com/doc2/detail?spm=a219a.7629140.0.0.tFddsV&&docType=1&articleId=104829](url)  部署说明来的。是不是有哪些依赖这篇文章没说清楚

**Comment by sunzhongliangde** [comment]
@cxfeng1   问题已解决，引入GLKit.framework 和 libc++.tbd后编译通过，
期待weex的文档也能更好的完善起来
