### ISSUE TITLE
pod install 的时候提示[!] Unable to find a specification for `WXDevtool (= 0.8.2)`

### ISSUE THREAD

**Issue by solaronke** [alibaba/weex#2041]
pod install 的时候提示[!] Unable to find a specification for `WXDevtool (= 0.8.2)`  是什么原因？网上都找不到解决办法，急！

**Comment by solaronke** [comment]
找到解决办法 了，pod setup执行结束之后再试pod install就可以了，pod setup真特么久，网上说的du -sh *出来是100多M，我的du -sh * 出来是926M！！

**Comment by acton393** [comment]
1.执行pod  repo update
2.Podfile  里面 改为 和dev 分支的podfile 内容一样（注意source）
