### ISSUE TITLE
利用Weex 在安卓上不支持CSS3的渐变颜色？

### ISSUE THREAD

**Issue by DangDangHellen** [alibaba/weex#2046]
利用CSS3中的径向渐变radial-gradient(rgba(255,255,255,0.3),rgba(255,255,255,1))在浏览器中可以很好的显示，但在安卓端背景无颜色，iPhone也没有试。
有遇到这种情况的吗？

**Comment by Jinjiang** [comment]
Weex 暂不支持渐变色，我先汇总到 #1494 了
