### ISSUE TITLE
android Textarea 内容高度>控件高度 不能滑动问题

### ISSUE THREAD

**Issue by aosting** [alibaba/weex#2050]
issues  1883 有两个问题。
1 Textarea嵌套的滑动冲突问题。（0.9 已经修复）
2 Textarea 初始化的时候内容高度>控件高度的时候不能滑动问题。场景如截图中评论被拒绝后，再次编辑！（0.9 未修复）

我是在textarea中添加这块代码来解决的。
```
editText.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
@Override
public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
if (v.canScrollVertically(-1) || v.canScrollVertically(0)) {
EditText view = (EditText) v;
if (view.getMovementMethod() == null) {
view.setMovementMethod(ArrowKeyMovementMethod.getInstance());
}
}
}
});

```

对WXEditText 中
```
if(h < contentH){
setMovementMethod(null);
}
```
不清楚为什么要这样设置？？

![Uploading Screenshot_20161228-111757.jpg…]()
![Uploading Screenshot_20161228-112058.jpg…]()
![Uploading Screenshot_20161228-112355.jpg…]()

**Comment by sospartan** [comment]
首先要区分两个东西，一个是文本内容的高度，一个是native view的高度，不能滚动的是native view的高度大于weex尺寸时的情况，这个是为了与各端保持统一。当文本内容的高度，因为输入内容增加，换行后，这个滚动情况是正常的。
