### ISSUE TITLE
AndroidManifest.xml 这个文件里面那个地方是去掉app的Activity的

### ISSUE THREAD

**Issue by itzj86** [alibaba/weex#2057]
android打包的时候，AndroidManifest.xml 这个文件里面那个地方是去掉app的Activity的，发布包的时候，不可能还带个调试的Activity，太难看了

**Comment by sospartan** [comment]
你说的具体是哪个activity？

**Comment by itzj86** [comment]
就是在打包完后，运行app后，显示在顶部的蓝色bar，对于我们非原生开发的人员来说，的确不会取消或者设置那个顶部bar
![qq 20161229111427](https://cloud.githubusercontent.com/assets/5669477/21536013/04d9f9a0-cdb8-11e6-98fc-431b5ae28eb4.jpg)

**Comment by sospartan** [comment]
是直接基于playground打的包？这个不适合作为正式应用去分发的，我们正在开发响应的打包工具。

**Comment by itzj86** [comment]
好的。感谢，期待新的打包工具
