### ISSUE TITLE
url中含有中文的话且没有encodeURI的话ios调用会报错然而安卓与web都好着

### ISSUE THREAD

**Issue by lmh0921** [alibaba/weex#2061]
比如这个url:
stream.fetch({
                    method: 'GET',
                    headers:{
                        'apikey':'deaa5742c4fa6856c33309d63aefba4c'
                    },
                    url: 'http://apis.baidu.com/tngou/cook/name?name=鸡',
                    type: 'json'
                }, function (ret) {。。。。。

这个没有encodeURI的话在ios端会出问题，很难调试问题也不好找，在安卓端与web都好着，估计是安卓端sdk阿里巴巴团队对url进行的转码而ios端的sdk的程序员没有进行转码。
虽然可以使用者使用encodeURI进行转码，但是很多时候那些参数是变量而且会忽略，然后出问题了又不好调试可以卡住程序员很久，觉得不如官方sdk里面帮忙encode一下比较好。

**Comment by iChenLei** [comment]
@exolution 大神帮忙看看这个

**Comment by acton393** [comment]
@lmh0921  native的SDK是没有做urlEncode这个的，建议前端同学做一下encode

**Comment by lmh0921** [comment]
@acton393 但是安卓手机的weexplayground扫二维码就不会出错，而ios的会，所以想问一下是不是可以在下一个版本native的sdk中做一下帮忙转码的事情，因为许多粗心的程序员或者新手们会在这块可能卡很久，像我就卡了一下午，很灰心。。。

**Comment by fengmingye** [comment]
同意lmh0921同学的观点，如果sdk能在ios端做个转码，同android端保持一致。这样weex端代码也能保持一致，使用起来简单。谢谢

**Comment by cuanhanshansi** [comment]
encodeURI('string')

**Comment by acton393** [comment]
hi , @fengmingye  @lmh0921     @sospartan 是Android stream 开发， 有咨询过 Android也没有做encode 操作， js做encode 也比较简单，控制权交给js，native尽量只做最小集合操作, thx~~
