### ISSUE TITLE
Picker 在浏览器上不支持啊

### ISSUE THREAD

**Issue by DangDangHellen** [alibaba/weex#2065]
利用Picker模块实现一个单选按钮，在安卓端可以很好得显示，但在浏览器上会报错，有人能解释下这个吗？

**Comment by zhangquan** [comment]
浏览器上的picker实现由于引入了第三库， 并没有做成内置的组件， 你可以到这里 https://github.com/weexteam/weex-picker 自行安装

**Comment by Jinjiang** [comment]
#2079
