### ISSUE TITLE
Input 标签 的问题

### ISSUE THREAD

**Issue by funnyN7** [alibaba/weex#2084]
在ios上一个页面有多个input的时候，一个input聚焦，再点击别的input使其聚焦，再点击 done，这时候rootView的frame将会错误，导航条也下不来了。
![simulator screen shot 2016 12 29 7 47 29](https://cloud.githubusercontent.com/assets/9295525/21543282/a6167482-cdff-11e6-939d-84b5f92ac4dd.png)

**Comment by acton393** [comment]
@funnyN7  SDK 使用的版本号是多少，或者使用的是哪个分支的

**Comment by funnyN7** [comment]
@acton393 0.9.4 最新版本，cocoapods集成的

**Comment by acton393** [comment]
hi @funnyN7  
麻烦方便的话，贴一下你的case， 我试试,谢谢~~

**Comment by emptywalker** [comment]
我这边，出现frame不对的时候，可以点击一个高于键盘上方的input，然后收起，即可恢复

**Comment by acton393** [comment]
@emptywalker 有没有固定的复现路径

**Comment by emptywalker** [comment]
就是当出现frame错误的时候，点击一个键盘上方的input，然后在收起键盘，frame就可以恢复   @acton393

**Comment by acton393** [comment]
#2164   @emptywalker  这个应该可以fixed，尝试一下

**Comment by acton393** [comment]
新版本发布会修复，也可以直接使用源码 
暂时先关闭了， 如果有问题可以再打开， thx~
