### ISSUE TITLE
内联事件处理参数问题，onclick=update(1, 2)

### ISSUE THREAD

**Issue by Hillkinsh** [alibaba/weex#2086]
现在，weex的内敛事件处理参数，直接写明确定，那么运行运行正常。如果参数是绑定的，则就会报错。
以下是详细描述：
1，这种情况是好的，
   <div>
     <text onclick="update(1, 2)">Result: {{result}}</text>    
  </div>

update: function (x, y) {
    this.result = x + y
      }
  }
运行结果是：Result:3。
2，但是，以下3种情况则全部报错。
2（1）参数来自绑定：
<div>
    <text onclick="update({{listVariable}}, 2)">Result of Variable: {{result}}</text>  
  </div>

data:{
    listVariable:2
}
2（2）参数来自绑定的数组：
<div>
    <text onclick="update({{listArray[0]}}, 2)">Result of Variable: {{result}}</text>  
  </div>

data:{
    listArray:[1,2,3]
}
2（3）参数来自对象数组：
<div>
    <text onclick="update({{ObjectArray[0].age}}, 2)">Result of Variable: {{result}}</text>  
  </div>

data:{
    ObjectArray: [
      { gender: 'male', nickname: 'Li Lei',age:1 },
      { gender: 'female', nickname: 'Han Meimei',age:2 },
      { gender: 'male', nickname: 'Jim Green',age:3 }
    ]
}
他们错误的反馈是： Uncaught TypeError: Cannot read property 'call' of undefined(…)。
应用上说，如果能把绑定的数据通过内连事件作出一定的处理，那么就会很方便的解决很多问题。

2016阿里weex校园开发者大赛 参赛组: Daily Delicacy

**Comment by Hanks10100** [comment]
不太明白问题的描述，`Result of Variable: {{result}}` 是写在模板里的吗？ 方便的话，可以在 http://dotwe.org/ 中写个 demo 描述问题。

通常来讲，报 `Uncaught TypeError: Cannot read property 'call' of undefined` 这种错误，都是因为绑定了不存在数据处理函数。可以确认下 `methods` 属性里是否定义了 `update` 方法。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
