### ISSUE TITLE
[安卓]scroller使用append="tree"后，顶部会有留白

### ISSUE THREAD

**Issue by hodgevk** [alibaba/weex#2088]
```javascript
        <scroller append="tree">
            <refresh class="refresh-view" display="{{refresh_display}}" onrefresh="onrefresh">
                <loading-indicator class="indicator"></loading-indicator>
            </refresh>
            <header>
                <input type="text" value="" placeholder="查询" />
            </header>
            <div repeat="{{data}}" track-by="{{name_pinyin_first}}" id="letter-{{name_pinyin_first.toUpperCase()}}">
                <div class="header">
                    <text class="header-title">{{name_pinyin_first.toUpperCase()}}</text>
                </div>
                <div class="item" repeat="{{data}}" track-by="{{id}}">
                    <text class="item-title">{{name}}</text>
                </div>
            </div>
        </scroller>
```
![图片](http://www.xwxq.gov.cn/upload/2016/1230/1483065907323.jpg)
去掉scroller的append属性，就能在顶部显示了

**Comment by Jinjiang** [comment]
我这里没毛病呀…… http://dotwe.org/weex/e15839e2c3bf0ffe89909a3b9074487e
你可以提供个重现的在线例子吗？方便我们排查问题
谢谢

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
