### ISSUE TITLE
stream模块fetch方法callback的ok参数，在安卓和IOS不一致

### ISSUE THREAD

**Issue by hodgevk** [alibaba/weex#2103]
stream模块fetch方法callback的ok参数在安卓是返回boolean类型的值，如下代码可以执行，而IOS里返回的是Int类型，成功为1，这就需要前端js进行类型转换。虽然是个小问题，但是框架本身的返回结果应该是要统一的，不然违背了weex的“多端接口设计一致”。
```javascript
     stream.fetch(params, function (response) {
            if (response.ok === true) {

            }
     }
```

**Comment by zzyhappyzzy** [comment]
不是应该判断response的status么？
```
stream.fetch(params, function (response) {
    if (response.status === 200) {
    }
}
```

**Comment by hodgevk** [comment]
官方说明里：ok {boolean}：如果状态码在 200~299 之间就为真。有时会有返回码是204的情况，所以判断status不如直接用ok来的方便。

**Comment by acton393** [comment]
hi @hodgevk 
stream.fetch 的ok 字段是返回的iOS native 的 boolean 类型 [here](https://github.com/alibaba/weex/blob/dev/ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m#L75), 应该是在native 回给jscore 的时候需要处理一下， 确实是个小的细节处理问题，后面版本处理掉，thx~~~~
