### ISSUE TITLE
动画执行结束后的属性更改效果会卡顿1秒

### ISSUE THREAD

**Issue by luoei** [alibaba/weex#2114]
ready:function(){

    var self=this;
    setTimeout(function(){
      self.animationLight();
    },1000);

  },
方法：
animationLight:function(){
      var self=this;
   //animationLightIndexDisplay和animationLightIndexId是在同一个组件上的属性
      this.animationLightIndexDisplay=true; //if属性
     var obj=this.$el('animationLightIndexId''); //组件id 但这里obj是null，获取不到对象
      setTimeout(function(){
        var obj=self.$el('animationLightIndexId');//这里可以获取到
        if(!obj)return;
        self.animationLightObj(obj);
        setTimeout(function(){
            self.animationLightIndexDisplay=false;
        },5000);
      });
    },
animationLightObj:function(obj){
      if (!obj.attr.dataShow)return; //dataShow是组件上面自定义属性，跟if是同一个变量，如果组件隐藏，则停止动画
      var self=this;
      animation.transition(obj, {
            styles: {
              transform: 'scale(2.5)',
              opacity:0.1
            },
            duration: 1000,
            timingFunction:'ease-in-out',
          }, function () {
              obj.setStyle('transform','none'); //效果上面会卡顿1秒
              obj.setStyle('opacity',1);//效果上面会卡顿1秒
              self. animationLightObj(obj);//卡顿1秒后会有效果
        });
    },

如果同时在多个组件上面进行动画操作，效果不是很理想，可能与我编写有关。平台是iOS,系统10.2，weex版本:0.9.4

**Comment by xispower** [comment]
有没有什么好的办法，动画的那部分用原生去做，其余的布局都用weex？

**Comment by xispower** [comment]
@Jinjiang 希望关注一下

**Comment by cxfeng1** [comment]
@xispower  麻烦在 http://dotwe.org/ 编写你的例子并分享一下链接， 谢谢

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
