### ISSUE TITLE
tab组件父子不能通信

### ISSUE THREAD

**Issue by colys** [alibaba/weex#2118]
看了源码，每个选项卡是单独的实例，就算用全局事件，也无法通信。目前我是修改的全局事件，让他跨实例，有更好的方式么？

**Comment by Hanks10100** [comment]
如果想实现跨页面通信的话，可以使用 `BroadcastChannel` 。参考 #1536 ，代码实现和用法参考 #1644 。

**Comment by colys** [comment]
建议将BroadcastChannel添加到教程中。

**Comment by Jinjiang** [comment]
@DoranYun 留意一下：）

**Comment by colys** [comment]
看了一下，BroadcastChannel 是浏览器的新功能，跟weex没啥关系啊，逗我么？

**Comment by DoranYun** [comment]
已更新到文档。

https://weex-project.io/references/jsfm-apis.html

**Comment by DoranYun** [comment]
@colys Weex 中的 `BroadcastChannel `API 根据现有的 BroadcastChannel 规范实现的。各浏览器也有自己的实现。

**Comment by jasonhe88** [comment]
@DoranYun 为什么我用Vue的语法说出现这个错误？谢谢！

Can't find variable: BroadcastChannel
