### ISSUE TITLE
背景图片不支持

### ISSUE THREAD

**Issue by colys** [alibaba/weex#2119]
想设置整个页面的背景图，无法生效，background-image: url()的方式
<template>
<div  style="background-image: url(http://www.qqzi.com/theme01/images/carousel01_sm.jpg)">
</div>
</template>

**Comment by xispower** [comment]
用image标签加position: absolute;可以实现

**Comment by Jinjiang** [comment]
楼上正解，目前 background-image 的 CSS 属性 Weex 还没有支持，背景图片可以通过底层的绝对布局图片来实现
感谢理解

**Comment by Jinjiang** [comment]
我们先把 background-image 汇总到 #1494 了
谢谢
