### ISSUE TITLE
关于input的一个bug

### ISSUE THREAD

**Issue by myyeshang** [alibaba/weex#2123]
android上遇到的一个问题，比较特殊，最新sdk，在测试机努比亚z11mini上发现，其他品牌手机有不同程度的类似状况(测试了三星小米一加)，在对表单进行修改的时候，点击input有几率出现键盘弹出立刻收起，有几率出现input光标停留在上一个input框，input框会触发菜单(类似长按操作)。
上个截图：
![image](https://cloud.githubusercontent.com/assets/23429274/21611451/d8ef4ab2-d207-11e6-94c6-4135ce4513cb.png)
代码片段如下：
```
<div class="mitem">
          <input class="item-id" aid="{{id}}" oninput="oninput" placeholder="{{hint}}" value="{{content}}"></input>
</div>
```
data为服务器获取的列表数据循环
```
items: [
        {id: '0',src: '>',title:'姓名:',content:'',hint:'姓名(必填)',shown:true},
]
```
希望可以给予一些指点

**Comment by myyeshang** [comment]
再补充一点，大部分手机状况好像都是，点一下，焦点过去，再点一下会键盘才会弹出，个别手机也会出现键盘先弹出再收起的情况

**Comment by myyeshang** [comment]
@Jinjiang

**Comment by misakuo** [comment]
已经重现了，我来解决

**Comment by myyeshang** [comment]
@misakuo 测试过焦点问题解决了，但是触发长按的菜单在我的手机上还是会出现(努比亚)

**Comment by myyeshang** [comment]
![515b7ec8fd8443630af9a83e9f2546b3](https://cloud.githubusercontent.com/assets/23429274/21633836/9595ba36-d28d-11e6-9c0c-7eb3f0adf2e3.jpg)
例如上图这样，在连续点击input框的时候，有概率出现这样的问题

**Comment by misakuo** [comment]
@myyeshang 在我的测试设备（三星gt-i9500和索尼 e6883）上暂时未能复现触发长按的问题，我会继续跟踪

**Comment by misakuo** [comment]
空data导致显示null的问题已解决
https://github.com/sospartan/weex/pull/106/commits/114863a09c6121aca221689caab84a42ec6da06b

**Comment by myyeshang** [comment]
@misakuo 我在其他手机上(红米3s)也发现类似情况，在scroller 里拖动的时候按到input拖动好像是一定会触发，可能识别的是拖动也识别为长按了吧，其他情况如果多次点击也有可能触发。关键是触发之后菜单会黏在input上，会出现好几个菜单。

**Comment by yardfarmer** [comment]
🔨  坚果上也要这个问题，点击输入框立即弹出长按选中菜单

**Comment by myyeshang** [comment]
截止最新sdk0.10的时候，这问题还是存在的，尤其是在scroller中点击到input滑动的时候，触发的多。
![image](https://cloud.githubusercontent.com/assets/23429274/23194000/981cf556-f8e6-11e6-9e1b-f5a1a2bccb91.png)

**Comment by chenyunecjtu** [comment]
input 这个问题，很影响用户的输入

**Comment by misakuo** [comment]
合并到#2750 讨论和跟踪，这里先close掉了
