### ISSUE TITLE
[BUG]安卓端，圆角按钮点击动画后，圆角失效变直角

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#2125]
给圆角按钮添加background-color变换动画后，会造成触发动画时圆角失效。
此BUG经测试 仅安卓平台会有
playground版本0.9.4

[在线示例代码](http://dotwe.org/acea9bfd57bff36f43ac79edea0cd3e7)

![quickmemo _2017-01-04-10-15-43](https://cloud.githubusercontent.com/assets/13174847/21629979/c4f6248a-d267-11e6-98c4-66b847ebd6d6.png)

**Comment by yuanzx** [comment]
貌似对任何有border-radius的做动画都会有这个问题，比如width，而且如果过渡时长设置长一点，会发现圆角立即消失，透明会渐变，ios也会圆角消失

**Comment by YorkShen** [comment]
background-color动画与border属性冲突，对background-color做动画，会导致border-radius, border-width, border-color, border-style失效。

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (109/100 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:47064 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWmiM-0032Ym-LW
	for greg@biomassiv.es; Thu, 26 Jan 2017 10:15:58 -0600
Date: Wed, 25 Jan 2017 01:46:31 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485337591;
	bh=DRpXSQlUlIgMTpI/Kh7BAgio49z/i5gBeK5VL3S1w8c=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=A4PW7rJQHtQ89H6eZkc3DTE76LAays3kQjZMs+LUL0Cxr4lprOWEAApYLR70baOr1
	 vbvMfwAw2kIBW0IgSd79AmTqFHe/KkV+335GAIbK1numcQ6bidcdiK479878GuJAAU
	 q72QZKt/MKKCtlNxFqt0L5bthH+PIVexDCcEYg3I=

**Comment by YorkShen** [comment]
Fixed by https://github.com/alibaba/weex/issues/2125
