### ISSUE TITLE
stream.sendHttp()存在跨域问题该怎么解决？

### ISSUE THREAD

**Issue by Hillkinsh** [alibaba/weex#2126]
我的代码如下：
` renderData: function (url) {
        var self = this
        stream.fetch({
          method: 'GET',
          url: url
          type:'json'
        }, function(res) {
            var results = res.data.result.data || []

            if (Array.isArray(results)) {
                self.items.push(results[0])
                console.log("results is ok!")
                console.log(results[0].albums[0])

            }
        },function(res){

        })
      },
`
当在url里输入聚合数据的api时，就会报错
![image](https://cloud.githubusercontent.com/assets/16912205/21630280/ab0bbda2-d26a-11e6-81a1-08c8131e540c.png)

**Comment by acton393** [comment]
hi @Hillkinsh 
#1933   可以看一下这个地方

暂时先关闭了，有问题可以再打开
