### ISSUE TITLE
stream.fetch()在iOS中发送post请求，body被拼接成url参数了

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#2128]
我在weex中使用stream.fetch()发送一个post请求，代码如下
```
                         getSmsCode: function (e) {
				var path = util.serverPath() + "/1.1/requestMerchantSmsCode"
				var self = this
				if (!regMobile.test(this.mobilePhoneNumber)) {
					modal.toast({
			                        'message': '请填写正确的手机号码',
			                        'duration': 1.5
			                });
					return
				}
				var param = {
					'mobilePhoneNumber': this.mobilePhoneNumber
				}
				stream.fetch({
					url: path,
					method: 'POST',
					type: 'json',
					body: param,
				}, function (response) {
					console.log(response)
					if(response.status == 200){
						timer = setInterval(self.start.bind(self), 1000)
					} else {
						modal.toast({
				          'message': '获取验证码失败',
				          'duration': 1.5
				        });
						return
					}
				}, function (res) {
					console.log(res)
				});
			}
```
但是在iOS中返回的是400，我用的SDK是0.9.4版本，修复了body中Dic转Data的错误，但是我查看后台日志，显示我传的body Prama被放在了url参数中，结果如下
![image](https://cloud.githubusercontent.com/assets/12522809/21630446/2ba92a5c-d26c-11e6-914b-ed5da945b809.png)

**Comment by emptywalker** [comment]
我看了WXStreamModule中的`- (void)fetch:(NSDictionary *)options callback:(WXModuleCallback)callback progressCallback:(WXModuleKeepAliveCallback)progressCallback`方法的实现，但是没有发现为什么`[request setHTTPBody:body];`，最终没有设置成功，在后台获取的body是空的，并且这个参数又被拼接到了URL参数上去，我在web端测试，这个请求是可以成功的，但是iOS这边就一直不行，很烦心哈

**Comment by acton393** [comment]
hi @emptywalker  
1. 你截图中URL才参数 这个部分的值是在请求中哪个地方获取到的
2. 用你的case，我自己写的服务端的demo，试了一下 `[request setHTTPBody:body];` 这个是设置成功的

charles 抓包
![image](https://cloud.githubusercontent.com/assets/11631084/21643817/59d21408-d2c5-11e6-83af-24ef4784eed3.png)

**Comment by emptywalker** [comment]
@acton393    表示我这边还是不行，   麻烦你测试一下 https://api.toomao.com/1.1/requestMerchantSmsCode，这个接口，然后body中按照
`
var param = {
			'mobilePhoneNumber': 你正确的手机号
}
`
发送一个post请求，我这边的post请求，一直都是将body的参数放在url后面，而不是post的body中

**Comment by emptywalker** [comment]
表示我这边所有的POST请求都是同样的问题，将body当作URL参数进行处理，导致POST无法获取参数，我用官方的palyground扫描后，也是同样的错误，你确定你的post请求能够成功吗  @acton393

**Comment by acton393** [comment]
@emptywalker  跟playground  还有客户端没有关系， 我给你截图中的是Charles的请求， post 的参数，是按照http 协议的请求带到body 里面的，不是拼在url 后面， 问题在服务端如何去拿并且展示这个参数，咨询下你们服务端同学， 查一下客户端post 参数是带到哪个地方的

**Comment by emptywalker** [comment]
#### 同样的接口，同样的代码，我在网页端请求就OK的，但是在iOS端请求就是失败的
并且request的数据格式也不一致，在客户端中这个request的body就被拼在url后面


### 网页端
![image](https://cloud.githubusercontent.com/assets/12522809/21667140/79f56034-d331-11e6-9d62-5067e5d2e246.png)
### iOS客户端
![image](https://cloud.githubusercontent.com/assets/12522809/21667153/896e4df0-d331-11e6-9923-82ffaea68264.png)

**Comment by emptywalker** [comment]
@acton393  我们这边找到了问题所在了，

```
    var header = {'Content-Type': 'application/json'};
    stream.fetch({
        method: 'POST',
        url: "https://dev-api2.toomao.com/1.1/requestMerchantSmsCode",
        type:'json',
        body: JSON.stringify({'mobilePhoneNumber': '18226987649'}),
        headers: header
      }, function(response) {
        console.log(response);
        
        var status = response.status
          modal.toast({
                  'message': status,
                  'duration': 1.5
                });
      },function(response){
        console.log('get in progress:'+response.length);
      });
```

### 因为我在request的type中设置了`json`，但是在iOS SDK中request的header没有设置content-type为json，只有在we文件中自己设置headers，SDK才会设置header，   希望后面可以修改一下，   保持request的header的content-type与  type一致

**Comment by zhoukekestar** [comment]
@acton393 ![img](https://cloud.githubusercontent.com/assets/11631084/21643817/59d21408-d2c5-11e6-83af-24ef4784eed3.png)
The request type is `json`, but the `content-type` is `application/x-www-form-urlencoded` (should be `application/json`).

**Comment by acton393** [comment]
@zhoukekestar  You are right, But this module haven't supported to set request type.
 Contribution welcome!!

**Comment by zhoukekestar** [comment]
What the code `type: "json"` actually do if the `content-type` is `application/x-www-form-urlencoded` & the body is a json string.

**Comment by acton393** [comment]
@emptywalker  看了一下文档，文档可能有点问题， type 字段对应的是 response 的type，不是 request的Type，会修正一下， 开放了header字段，就是允许header字段可以设置的。

application/x-www-form-urlencoded  在 [w3c](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1) 文档上 表示form 提交默认content-type， 也就是说参数是body参数没有被拼接到url后面
