### ISSUE TITLE
iOS 中多个输入框，多次触发键盘隐藏收起，会导致整个View页面上调，不能恢复

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#2130]
#### 描述
我使用的是0.9.4版本，貌似这个功能才加上去的，就是键盘弹出的时候input会上移到键盘的上方，但是多次切换键盘，发现整个View上移了一个高度，并且下不来了。

### 结果
结果如图：
![image](https://cloud.githubusercontent.com/assets/12522809/21630587/b9a79900-d26d-11e6-91dd-452d98d116e1.png)

如果将空白处收起，需要触发一个比键盘高度更搞的input，然后收起键盘的时候，View能够恢复

**Comment by acton393** [comment]
#2123  可以在这边统一讨论一下，这个我暂时先关掉了~~
