### ISSUE TITLE
weex-toolkit 安装失败

### ISSUE THREAD

**Issue by XiaoChenYung** [alibaba/weex#2131]
![qq20170104-1](https://cloud.githubusercontent.com/assets/14293093/21631242/0623184e-d274-11e6-8850-df0458276c8a.png)

**Comment by Hanks10100** [comment]
从报错信息来看，是 shasum 值校验失败，可能会是版本或者缓存的问题。

建议换个 npm 的安装源，或者使用 cnpm 。

**Comment by Jinjiang** [comment]
楼上正解，国内推荐 cnpm，或重新用 npm 安装试试看

**Comment by XiaoChenYung** [comment]
可以了  谢谢
