### ISSUE TITLE
JS调用自定义组件的成员方法

### ISSUE THREAD

**Issue by fightKen** [alibaba/weex#2135]
Hi，我现在有一个需求：需要将一个第三方公司提供的密码输入框控件封装成Weex自定义组件，其实需要一个方法去调用控件一个C++ 本地方法来获取加密密文，但目前我没有找到适当的方式来让Weex端能直接调用自定义组件的成员方法，是Weex不支持吗？求赐教！

**Comment by misakuo** [comment]
请看 https://github.com/alibaba/weex/blob/dev/examples/component/input-demo.we#L132 这个例子，对应到java代码里，给需要export到weex端的方法加上`@JSMethod`注解就可以，iOS怎么导出方法麻烦@kfeagle 解答下

**Comment by kfeagle** [comment]
https://github.com/alibaba/weex/blob/ios-feature-20161208/ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m#L90
iOS实现方式

**Comment by fightKen** [comment]
感谢两位的回答！
