### ISSUE TITLE
用dev编译的framework集成到工程里面，5c，Xcode联机调试时，mapview？释放后主线卡死

### ISSUE THREAD

**Issue by iamqk** [alibaba/weex#2136]
设备：5C OS:10.11.6 weex本：b5b600d
连接xcode debug调试的时候，含有地图的页面在退出的时候，主线程卡死，界面无响应
移除framework程序恢复正常

点击暂停，主界面的bt如下：
(lldb) bt
* thread #1: tid = 0x15d4a, 0x1dd2b89c libsystem_kernel.dylib`semaphore_wait_trap + 8, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x1dd2b89c libsystem_kernel.dylib`semaphore_wait_trap + 8
    frame #1: 0x0213a34a libdispatch.dylib`_dispatch_semaphore_wait_slow + 168
    frame #2: 0x0201cc84 libglInterpose.dylib`ContextInfo::~ContextInfo() + 116
    frame #3: 0x01fd3eda libglInterpose.dylib`EAGLContext_dealloc(EAGLContext*, objc_selector*) + 266
    frame #4: 0x1d815194 libobjc.A.dylib`objc_object::sidetable_release(bool) + 238
    frame #5: 0x2901b9b8 VectorKit`ggl::OESContext::~OESContext() + 164
    frame #6: 0x2901182e VectorKit`-[GGLOpenGLESLayer .cxx_destruct] + 54
    frame #7: 0x1d7fa046 libobjc.A.dylib`object_cxxDestructFromClass(objc_object*, objc_class*) + 116
    frame #8: 0x1d804ec4 libobjc.A.dylib`objc_destructInstance + 34
    frame #9: 0x1d804ee4 libobjc.A.dylib`object_dispose + 14
    frame #10: 0x21448b26 QuartzCore`-[CALayer dealloc] + 114
    frame #11: 0x213fb3fa QuartzCore`-[CAEAGLLayer dealloc] + 114
    frame #12: 0x01fd64b6 libglInterpose.dylib`CAEAGLLayer_dealloc(CAEAGLLayer*, objc_selector*) + 450
    frame #13: 0x2901130e VectorKit`-[GGLOpenGLESLayer dealloc] + 110
    frame #14: 0x28f2c30c VectorKit`-[MDDisplayLayer dealloc] + 260
    frame #15: 0x1d815194 libobjc.A.dylib`objc_object::sidetable_release(bool) + 238
    frame #16: 0x28cb4e5e VectorKit`-[VKMapView dealloc] + 864
    frame #17: 0x21447730 QuartzCore`CA::Layer::free_transaction(CA::Transaction*) + 136
    frame #18: 0x213f8c32 QuartzCore`CA::Transaction::commit() + 690
    frame #19: 0x213f9652 QuartzCore`CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 162
    frame #20: 0x1e553f14 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
    frame #21: 0x1e552190 CoreFoundation`__CFRunLoopDoObservers + 282
    frame #22: 0x1e5525a6 CoreFoundation`__CFRunLoopRun + 934
    frame #23: 0x1e4a1532 CoreFoundation`CFRunLoopRunSpecific + 486
    frame #24: 0x1e4a1340 CoreFoundation`CFRunLoopRunInMode + 104
    frame #25: 0x1fc78bfc GraphicsServices`GSEventRunModal + 156
    frame #26: 0x236afe26 UIKit`-[UIApplication _run] + 574
    frame #27: 0x236aa550 UIKit`UIApplicationMain + 150
    frame #28: 0x003d34ac DEV`main(argc=1, argv=0x01da89e4) + 100 at main.m:16
    frame #29: 0x1dc6b50a libdyld.dylib`start + 2
(lldb)

**Comment by acton393** [comment]
有复现的路径吗？

**Comment by iamqk** [comment]
补充一下：xcode版本是 8.2 8.2.1都一样
6s设备没有此类问题，模拟器也没有此类问题

**Comment by iamqk** [comment]
补充一下：xcode版本是 8.2 8.2.1都一样
6s设备没有此类问题，模拟器也没有此类问题

**Comment by iamqk** [comment]
连接xcode debug调试的时候，含有地图的页面在退出的时候，主线程卡死，界面无响应
复现路径：
xcode连接5c进行debug调试，在切换没有内嵌mapview地图的页面时没没有问题
切换进入含有mapview地图的页面时也没有问题
但是从含有mapview的页面退出，页面释放后就会产生此类问题
主线程卡死，但是不会超时退出，用户交互无响应（不能点击）

**Comment by xispower** [comment]
你这个问题跟我们当初遇到uiwebview情况一致，在5c上，开启debug，会卡死，不开启就没事。其它没事，一直没有找到这个原因，也就没有解决这个问题，不影响正常使用。 可能是因为5c使用armv7编译库的原因，5s及其之后都是使用的是arm64。如果有解决方法提出来，兄弟们记得@我一下，多谢。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
