### ISSUE TITLE
Invalid activity declaration for WXPageActivity in playground app

### ISSUE THREAD

**Issue by tahnok** [alibaba/weex#2139]
I noticed that the declaration for https://github.com/alibaba/weex/blob/4abcd6cf0070c6301ed64d6bbcdef727365f347e/android/playground/app/src/main/AndroidManifest.xml#L49 contains a bug.

The activity has an intent filter that will match any URI starting with http/https and launch WXPageActivity but this activity is NOT exported. [the activity tag](https://developer.android.com/guide/topics/manifest/activity-element.html) specifies that if `android:exported` is missing it defaults to `android:export=false`

If any other app on the phone tries to launch an intent with an http/https uri (eg: `Intent browserIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("http://www.google.com"));`) that app will crash with a security exception as it is trying to launch an activity that is not exported.

This issue also occurs with the [Alibaba.com app](https://play.google.com/store/apps/details?id=com.alibaba.intl.android.apps.poseidon)

```
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://tools.usps.com/... cmp=com.alibaba.intl.android.apps.poseidon/com.alibaba.android.intl.weex.activity.WeexPageActivity (has extras) } from ProcessRecord{e23a770 21945:com.shopify.mobile/u0a82} (pid=21945, uid=10082) not exported from uid 10442
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3131)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1540)
	at android.app.Activity.startActivityForResult(Activity.java:4283)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
	at android.app.Activity.startActivity(Activity.java:4563)
	at android.support.v4.app.ActivityCompatJB.startActivity(ActivityCompatJB.java:27)
	at android.support.v4.app.ActivityCompat.startActivity(ActivityCompat.java:140)
	at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:262)
	at com.shopify.mobile.lib.app.Router.launchWithChrome(Router.java:126)
```

**Comment by Hanks10100** [comment]
@sospartan please have a look. @tahnok you could send a PR to fix it.

**Comment by tahnok** [comment]
I don't have enough knowledge of how weex is supposed to work to fix I'm afraid. Is a new wxActivity supposed to be launched whenever any link is clicked within the app? Can those intent filters be deleted?

**Comment by sospartan** [comment]
@tahnok the purpose of 'playground' app is testing weex page, not for production using. So I think this `export` problem is acceptable. As the 'Alibaba.com app', I will contact the dev team to fix that if they are not going to open url send by another app.
Thanks for reporting.

**Comment by maxme** [comment]
FYI, I've also contacted the team via developer.android@aliexpress.com since we get a lot of crashes in our app due to this issue. 

Ref: https://github.com/wordpress-mobile/WordPress-Android/issues/4991

**Comment by kypeli** [comment]
When will the next version be released? Are there any devs from AliBaba reading this - quite critical - bug?

**Comment by Jesbus** [comment]
Also getting these crashes... This is quite ridiculous, please fix ASAP.

**Comment by DapengAtGradientx** [comment]
I uninstalled alibaba app because of this bug. Whoever could fix the problem but chose not to do it promptly hurt alibaba badly.

**Comment by FrankNT** [comment]
You can avoid crash in your application using try catch

`try {
                context.startActivity(browserIntent);
            } catch (Exception ex) {
                Toast.makeText("Error").show();
            }`

Even if Alibaba eventually fix this some other apps could make the same mistake again.

**Comment by Praeterii** [comment]
Oh, come on guys, this is ridiculous, FIX IT.

**Comment by PattaFeuFeu** [comment]
I’m also seeing this issue in an app which is crashing if Ali Baba B2B app is installed and when trying to open a link even remotely connected to one of AliBaba’s sites.

It seems like the bug only occurs for devices with Android 6 or higher (see attached screenshot)

![screen shot 2017-01-09 at 10 46 47](https://cloud.githubusercontent.com/assets/9012887/21762459/00e9f526-d659-11e6-817a-6ff3ae08bf44.png)

**Comment by zunjae** [comment]
@FrankNT 

Should I also use try catch when defining a String?

```
try {
    String message = "Hello World";
} (Exception e) {
    throw new RuntimeException("Unable to create String object\n"+ e);
}
```

**Comment by Praeterii** [comment]
@FrankNT 
This wont make the browser open, so this is not really a fix. Better workaround would be to catch SecurityException and open the page in webview.

**Comment by lynenzhang** [comment]
@maxme I'm sorry for this. Our team has released a new version to fix this issue. You can download the latest version from Play to check.

**Comment by lynenzhang** [comment]
@PattaFeuFeu This issue doesn't occur for all devices. It mostly occurs for devices with Android 6 or higher. We checked this issue with Android 4.4.4, Android 5.1.1, Android 6.0, Android 7.1 devices. We have released a new version to fix this bug. Thank you for your screenshot.

**Comment by lynenzhang** [comment]
@tahnok We have fixed it. You can check it with the newest version from play. Thank you for your feedback.

**Comment by tahnok** [comment]
I can confirm that the latest release (4.15.2) fixes the issue.

I still think that the sample app should be changed to remove this bug as I can see inexperienced developers copying the manifest and re-introducing this bug. I'd do that myself, but I don't understand this codebase enough to know if removing the intent-filter would cause other issues

**Comment by sospartan** [comment]
@tahnok this `export` flag will affect if other apps have the permission to open app by that url-intent.  I'll consider your suggestion. But this is a normal 'android-feature', not always a bug. Thanks anyway.
I will close this issue since the alibaba app fixed this problem.

**Comment by jeelanibasha12** [comment]
@maxme - i have downloaded the Alibaba.com B2B Trade App. I am not seeing view site and my site option any where.
