### ISSUE TITLE
Weex集成至Xcode时遇见的问题

### ISSUE THREAD

**Issue by tmxdyf** [alibaba/weex#2140]
Weex集成至iOS时，发生如下错误。查找网上多种相似情况解决方式，依然无法解决。请问应该怎么处理？

![image](https://cloud.githubusercontent.com/assets/6415080/21667822/08a916d6-d337-11e6-9aa8-c2190841f284.png)

**Comment by acton393** [comment]
@tmxdyf   cocoaPods 集成还是 添加framework集成

**Comment by iamqk** [comment]
framework依赖的SRWebSocket是独立的开源包
要单独加到工程里面

**Comment by xispower** [comment]
@tmxdyf  你这个问题是少了SocketRocket库，项目地址：https://github.com/square/SocketRocket，不过建议用第三方工具(例如：CocoaPods)去管理第三方库，在开发环境建议集成WXDevtool，在生产环境集成WeexSDK，两者都会自动下载所需要的第三方库。

**Comment by acton393** [comment]
暂时先关闭了，如果有问题可以再打开, thx~
