### ISSUE TITLE
Weex Android SDK 显示不全

### ISSUE THREAD

**Issue by CCC2016** [alibaba/weex#2149]
设备型号：Samsung SM-G5308W
OS 版本：Android 4.4
App 版本：0.9.4

通过 playground 应用扫描二维码，界面显示正常；但通过 Weex SDK 集成时，界面显示不全；

`mWXSDKInstance.render("more-lists", WXFileUtils.loadAsset("more-lists.js", this), null, null, -1, -1, WXRenderStrategy.APPEND_ASYNC);`

![weex sdk](https://github.com/CCC2016/Cache/blob/master/Weex%20SDK%20show%20error.png "error")

**Comment by 1149863953** [comment]
我也遇到同样的问题，我发现在官方demo中直接修改js文件是可以显示全屏的，但是通过.we生成的js文件同样的代码会出现显示不全。

**Comment by 1903514970** [comment]
应该是0.9.4sdk有问题吧，我改成0.8.0就可以显示全了。

**Comment by CCC2016** [comment]
@1903514970 多谢，使用 0.8.0 版本显示正常了。😂

**Comment by CCC2016** [comment]
```Java
mInstance.renderByUrl(
      getPageName(),
      url,
      options,
      jsonInitData,
      **ScreenUtil.getDisplayWidth(this),**
      **ScreenUtil.getDisplayHeight(this),**
WXRenderStrategy.APPEND_ASYNC);
```

@1149863953 试试不使用 -1 ，采用 `ScreenUtil`，目前0.9.4也显示正常了😄；
https://github.com/alibaba/weex/blob/dev/android/commons/src/main/java/com/alibaba/weex/commons/AbstractWeexActivity.java#L300
