### ISSUE TITLE
请问如何监听鼠标移入和移出?

### ISSUE THREAD

**Issue by ymzuiku** [alibaba/weex#2152]
***新需求***
web端一个非常常用的是鼠标移入和移出的监听, 不知道有没有实现呢?我把文档看了一圈好像没有发现...求指点.

**Comment by alex-zhang** [comment]
同问

**Comment by myyeshang** [comment]
weex明明是为移动端三端统一做的，尤其是为原生ios和android更方便有效，为啥PC端的会用到weex呢？

**Comment by ymzuiku** [comment]
既然是"开发一次,处处运行",就得考虑PC端的Web呀
如果不考虑Web端的功能, 同样只是iOS和Android, 为什么不用ReactNative呢?

**Comment by myyeshang** [comment]
这位兄弟对一个口号太极端了吧

**Comment by xispower** [comment]
@ymzuiku 说的是，如果项目中不考虑H5，我们当时是准备使用ReactNative的，目前项目iOS和Android的问题都还有很多不完善，一切慢慢来。如果你需要的那部分没有，可以考虑自己去填充这部分，毕竟开源要成功要靠大家的努力。

**Comment by Jinjiang** [comment]
@ymzuiku 抱歉我们的设计和侧重点可能未如您所愿。
如果非要咬文嚼字的话，我们是一个跨平台的**移动**开发框架，今天移动平台上几乎见不到鼠标了，所以我们并没有做针对性的支持，也不太会打算在未来支持，希望得到您的理解和支持。
再次感谢
