### ISSUE TITLE
WXJsonUtils.fromObjectToJSONString()方法传递内部类，无法序列化json字符串

### ISSUE THREAD

**Issue by zcl0001** [alibaba/weex#2163]
代码如下：jsoninit 的数据就会为{}
public class TMFerlizerUseInfoActivity extends TMBaseActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_tmfui);

        setContainer((ViewGroup) findViewById(R.id.frameLayout_tmfui));
        SharedPreferences sp = this.getSharedPreferences("TMSharedPreferences", Context.MODE_PRIVATE);
        final String userName=sp.getString("UserName","tmnull");
        RenderJson j =new RenderJson();
        j.src= TMConstant.WebServer+TMConstant.fertilizerUseInfo+"?UserAID="+userName;
        String appData= WXJsonUtils.fromObjectToJSONString(j);
        renderPage(WXFileUtils.loadAsset("tmWeb.js", TMFerlizerUseInfoActivity.this),null,appData);
    }
    class RenderJson{
        String src="";
    }
}

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
