### ISSUE TITLE
if指令的性能问题

### ISSUE THREAD

**Issue by wangying3426** [alibaba/weex#2165]
用if来控制组件的显示/隐藏时，目前weex实现方式是直接创建/删除节点的，如果页面比较复杂或者状态变化比较频繁，性能会不会不太好？可不可以用类似android的GONE和VISIBLE来控制节点的显示和隐藏？iOS也是类似的。

**Comment by Jinjiang** [comment]
是的你说的没错，显示隐藏其实就是 CSS 里的 `display: none`，#1494 已经对这一需求做了汇总，团队会考虑在一个适当的时机进行讨论并实现，这里就不重复讨论了
希望理解
