### ISSUE TITLE
android startActivityForResult调用疑问.谢谢。

### ISSUE THREAD

**Issue by easybenefit** [alibaba/weex#2167]
android 通过WXSDKEngine.registerModule注册的module，怎么调用startActivityForResult，以及以何种方式回调onActivityResult方法

**Comment by misakuo** [comment]
0.9.4版本中可以覆盖WXModule中的`onActivityForResult`方法接收到回调，startActivityForResult可通过WXSDKInstance实例持有的Context实现，下一个版本将会重构Activity生命周期回调部分，敬请期待。

**Comment by easybenefit** [comment]
还是有疑问，能写的详细点吗？我的操作流程:
1.在WXModule中调用  ((Activity) context).startActivityForResult();
2.在WXBaseActivity中，override
  protected void onActivityResult (int requestCode, int resultCode, Intent data) {
         if (mInstance != null) {
               mInstance.onActivityResult(requestCode, resultCode, data);
          }
  }
3.覆盖WXModule中的onActivityForResult();方法.

4.疑问一:如果不在WXBaseActivity的onActivityResult中调用mInstance.onActivityResult，WXModule中的onActivityResult何时会调用？
5.疑问二:如上调用程序， 在 WXModuleManager.onActivityResult方法中，HashMap<String, WXModule> modules =sInstanceModuleMap.get(instanceId);
因为modules＝＝null，会crash。

**Comment by misakuo** [comment]
1. 必须在WXBaseActivity#onActivityResult中调用WXSDKInstance#onActivityResult，WXModule的onActivityResult才有机会被调用
2. 为什么上面说的是有机会被调用呢，因为只有一个WXModule是和WXSDKInstance绑定而非全局注册的时候，它才会存在于`sInstanceModuleMap`中

**Comment by easybenefit** [comment]
方法调用与你相同，但遇到了空指针报异常，
上图所示sInstanceModuleMap持有定义的photoModule，但对应的instanceId为”4“，但调用WXSDKInstance#onActivityResult时，instanceId为"2"，sInstanceModuleMap.get(instanceId) 会为null，导致空指针。

<img width="682" alt="1" src="https://cloud.githubusercontent.com/assets/16224454/21797872/90fcdcfc-d74c-11e6-8ef1-526b870a5fb2.png">
<img width="859" alt="2" src="https://cloud.githubusercontent.com/assets/16224454/21797874/923da7c2-d74c-11e6-946b-17965c367243.png">

**Comment by misakuo** [comment]
出现该情况的原因可能是调用startActivityForResult时所处的WXSDKInstance和onActivityResult时操作的WXSDKInstance不是同一个

**Comment by easybenefit** [comment]
1.一个是Module的WXSDKInstance, 一个是Activity的WXSDKInstance.其instanceId不一样。
2.临时解决方法是缓存Module的InstanceId。在onActivityResult中调用WXModuleManager.onActivityResult(instanceId, requestCode, resultCode, data);
是否会有其它问题。
3.在modules = sInstanceModuleMap.get(instanceId)，是否需要添加modules空指针判断。

**Comment by misakuo** [comment]
你看下两个WXSDKInstance关联的Context是否是同一个

**Comment by easybenefit** [comment]
Context是同一个

**Comment by misakuo** [comment]
现在可以暂时用缓存instanceId的方式规避一下，我查一下具体原因，下个版本一并做优化

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
