### ISSUE TITLE
weex h5页面在安卓版微信、QQ中打不开

### ISSUE THREAD

**Issue by goldmantis** [alibaba/weex#2168]
我搭建了个weex项目，h5的地址为pay2018.com:12580
经测试，该页面在安卓版的qq、安卓版的微信、mac上的safari上显示为一片空白
在mac的chrome、iPad的safari下显示正常。

安卓手机：小米5（安卓版本为6.0）,坚果YQ601(安卓版本为5.1.1)

提示错误（mac safari）为：TypeError: window.weex.init is not a function. (In 'window.weex.init', 'window.weex.init' is undefined)

**Comment by goldmantis** [comment]
请问，官方是否有类似的搭建好的demo地址，供测试下

**Comment by Jinjiang** [comment]
感觉不是环境配置问题，和微信、QQ、Android 没有太大关系
你的 demo 是怎么搭建的？

**Comment by Jinjiang** [comment]
pay2018.com:12580 我没有访问成功，提示“找不到 pay2018.com 的服务器 DNS 地址”

**Comment by goldmantis** [comment]
sorry,昨天调试时把服务停掉了。现在可以了，请大牛帮看看，谢谢。

**Comment by fkysly** [comment]
好像又停掉了，你要不然保持常开？或者给个源码？

**Comment by Jinjiang** [comment]
@goldmantis 由于长时间得不到回应，这个 issue 我先关掉了，建议再报 bug 的时候可以提供稳定可访问的地址或源码。如果仍有问题可以重开 issue。
感谢支持
