### ISSUE TITLE
怎么实现像bootstrap的栅格系统一样的布局

### ISSUE THREAD

**Issue by solaronke** [alibaba/weex#2170]
列表里每一行有三列,怎么样才能实现像bootstrap的col-md-4这样的布局排列

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4"></div>
  <div class="col-md-4"></div>
</div>

**Comment by Jinjiang** [comment]
参考 flexbox，写三个 div，然后都设置为 flex: 1

**Comment by BoringDays** [comment]
父元素设置display: flex，子元素均设置为flex: 1可破，注意flex direction
