### ISSUE TITLE
在js文件中调用Weex的require('@weex-module/stream')的Module无法调用,有什么解决方法?

### ISSUE THREAD

**Issue by Mryong** [alibaba/weex#2175]
由于需求需要,要将所有的网络请求写在各个模块的js中,而在js文件中调用Weex的require('@weex-module/stream')的Module无法调用,有什么解决方法?

**Comment by xispower** [comment]
```
var stream
__weex_define__('@weex-temp/api', function(__weex_require__) {
  stream = __weex_require__('@weex-module/stream')
});
```
你这样试试？

**Comment by Jinjiang** [comment]
这是我们早期 API 设计上的缺陷，JS 文件里无法使用 require 方法获得 native module
未来我们的 API 会是 `weex.requireModule('stream')`，下个版本就可以这样使用了，当然老的用法我们还会继续支持
谢谢

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (121/100 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:47880 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWmiX-0032eU-Le
	for greg@biomassiv.es; Thu, 26 Jan 2017 10:16:09 -0600
Date: Wed, 25 Jan 2017 01:44:11 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485337451;
	bh=LxwVGZyFZZVumkQfc/CkRAAAICVXNyYyNyu3V2F+Vm0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=cHHFWRnC90v93UwZJ+N9gMZaGfrS0dKyzV1qd9dDn554bkfY7VLe8UU1Oy26YFS6+
	 s4O9iZ7fBaBCq5ff18Rb571fY3R8g71SL96EpCZ3ioPGuFNyBskrzfWqmCv+GR1Iy+
	 hsG1jjKGQ1290sBVPCbeT06OHIMMhs/xUrZ0tX70=

**Comment by MrFuFuFu** [comment]
@Jinjiang 能把这个`weex.requireModule('stream')` 文档更新一下吗，这几天正在集成，需要 native 的方法...用的就是0.9.5的版本...
