### ISSUE TITLE
weex更新问题

### ISSUE THREAD

**Issue by caozhiyong** [alibaba/weex#2176]
当我输入weex --version时，显示的版本是0.6.4 。目前发布的版本是0.9.4了，我应该怎么做去升级软件的版本呢？

**Comment by xispower** [comment]
只要你的项目中是最新就行，weex只是你命令行使用的版本，跟项目没有多大关系。比如在iOS项目中直接用pod  'WeexSDK' 就行。

**Comment by Hanks10100** [comment]
@xispower 说得对，`weex --version` 看到的是 [weex-toolkit](https://github.com/weexteam/weex-toolkit) 这个工具的版本，不是 WeexSDK 的版本。 升级 WeexSDK 一般都是在 native 项目中配置的。

**Comment by yolynn-bird** [comment]
浏览器里运行时，很多语法不支持，比如v-for

**Comment by Hanks10100** [comment]
@yolynn-bird 支持 v-for 的，参考 http://dotwe.org/vue/28340bcaf6a1272d6b03810e0d7b1aec

记得在左上角选择 vue 语法（默认）。
