### ISSUE TITLE
iOS: modal.toast无法显示浮层提示

### ISSUE THREAD

**Issue by Lurkyli** [alibaba/weex#2183]
问题描述：
我在一个we文件中增加了如下代码：
this.modal.toast({'message':'test', 'duration': 2});

结果：
1. this.modal.toast在Android端显示正常;
2. this.modal.toast在iOS端不会显示浮层提示，但换成weex playground运行，可以显示浮层提示。

分析过程：
1. 将iOS SDK从0.8.0升级到0.9.4，问题依然复现；
2. 跟踪WXModalUIModule中的如下代码，没有异常，但浮层提示不能显示：
- (void)showToast:(UIView *)toastView superView:(UIView *)superView duration:(double)duration
{
    if (!toastView || !superView) {
        return;
    }
    
    [WXToastManager sharedManager].toastingView = toastView;
    [superView addSubview:toastView];
    
    [UIView animateWithDuration:0.2 delay:duration options:UIViewAnimationOptionCurveEaseInOut animations:^{
        toastView.transform = CGAffineTransformConcat(toastView.transform, CGAffineTransformMakeScale(0.8, 0.8)) ;
    } completion:^(BOOL finished) {
        [UIView animateWithDuration:0.2 delay:0.2 options:UIViewAnimationOptionCurveEaseInOut animations:^{
            toastView.alpha = 0;
        } completion:^(BOOL finished){
            [toastView removeFromSuperview];
            [WXToastManager sharedManager].toastingView = nil;
            
            NSMutableArray *queue = [WXToastManager sharedManager].toastQueue;
            if (queue.count > 0) {
                [queue removeObjectAtIndex:0];
                if (queue.count > 0) {
                    WXToastInfo *info = [queue firstObject];
                    [self showToast:info.toastView superView:info.superView duration:info.duration];
                }
            }
        }];
    }];
}

3. 比较APP中的WXViewController与weex playground的代码，没有遗漏代码。

问题：
1. iOS APP的集成过程完全遵循demo程序；
2.我的APP中集成了一些第三方组件：百度地图SDK、友盟统计、极光推送等；
3.现在的现象是依赖组件兼容性的问题么？

谢谢！

**Comment by Lurkyli** [comment]
另外，同样的下列代码在iOS上显示正常：
this.modal.alert
this.modal.confirm
this.modal.prompt

**Comment by xispower** [comment]
如果要做到包含导航栏的全屏，可以使用position: fixed;定位。

**Comment by Lurkyli** [comment]
如果要做到包含导航栏的全屏，可以使用position: fixed;定位。
现在的问题是根本看不到toast浮层，不是toast显示的位置不对。另外，演示代码modal.we中并没有任何关于toast位置的设置。

**Comment by xispower** [comment]
我是自定义的一个div去做的浮层，你这个情况可能是一个bug， @Jinjiang

**Comment by Lurkyli** [comment]
WXViewController.m
- (void)toast:(NSString *)message duration:(double)duration
{
    WXAssertMainThread();
 //   UIView *superView =  [[[UIApplication sharedApplication] windows] objectAtIndex:0];
// 将上行的代码该为下行就好了。
    UIView *superView = [[[UIApplication sharedApplication] windows] lastObject];
    if (!superView) {
        superView =  self.weexInstance.rootView;
    }
    UIView *toastView = [self toastViewForMessage:message superView:superView];
    WXToastInfo *info = [WXToastInfo new];
    info.toastView = toastView;
    info.superView = superView;
    info.duration = duration;
    [[WXToastManager sharedManager].toastQueue addObject:info];

    if (![WXToastManager sharedManager].toastingView) {
        [self showToast:toastView superView:superView duration:duration];
    }
}
