### ISSUE TITLE
关于wxc-navpage 和 wxc-navbar 的问题

### ISSUE THREAD

**Issue by yuhaolove** [alibaba/weex#2186]
按照官方的用法,使用了wxc-navpage  但是为何在h5下正常 在ios和安卓下 会出现两个 导航条

如图:

![](http://images.kaistart.com/error-weex.png)

代码:

```

<wxc-navpage data-role="none" background-color="#ff5898" title="今日2节目" title-color="white" left-item-title="返回" left-item-color="white">
  <div class="wrapper">
   <text>message</text>
  </div>
  </wxc-navpage>

```

**Comment by AlenGao** [comment]
@yuhaolove weex很恶心最外部容器有个navbar， navpage又有一个navbar其实是两个，我的不会出现你这种情况我的navbar会在最外部容器的navbar下，被遮住，看起来好像是一个。

**Comment by AlenGao** [comment]
@yuhaolove 你也可以尝试用下wxc-navbar 这个没问题的 但是你可能要设置navbar 下面内容的margin-top

**Comment by yuhaolove** [comment]
@AlenGao 谢谢哦  wxc-navbar  是没问题 但是好像 没法动态改变 title  按理说 wxc-navbar 应该作为 根部的 一个 组件来用的,  其他的页面来设置 wxc-navbar的title 和其他属性来实现交互,  现在 没法动态改变titile  我也是醉了

**Comment by emptywalker** [comment]
借助这个问题，我想问一下，在wxc-navpage中，设置多个按钮怎么做 ！！！！！

@yuhaolove  改变title貌似只能在当前页面，动态修改

**Comment by yuhaolove** [comment]
@emptywalker 我现在是 每个页面都有一个 wxc-navbar  然后在nav-bar上 设置按钮 现在好像只能设计左右按钮吧 想要自定义的话 试试  自己写个navbar  把data-role="none" 设置为 data-role="navbar" 试试 只是猜测

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
