### ISSUE TITLE
iOS导航bug

### ISSUE THREAD

**Issue by WHChaw** [alibaba/weex#2187]
在使用weex playground时，偶尔会出现push和pop动画失效，我自己集成weexSDK的App也同样会出现push和pop动画失效问题，用我自定义的UIViewController替代WeexSDK中的ViewController问题依旧存在

**Comment by acton393** [comment]
这个bug已经有开发者提到，跟进中...  新版本会解决..   #1831 

统一讨论， 这个暂时先关闭了，
