### ISSUE TITLE
求助：wxc-navpage&list结合使用的一个怪异的问题

### ISSUE THREAD

**Issue by AlenGao** [alibaba/weex#2189]
.header {
    padding-top:25;
    padding-right:25;
    padding-bottom:25;
    padding-left:25;
    background-color: #efefef;
    border-bottom-color: #eeeeee;
    border-bottom-width: 2;
    border-bottom-style: solid;
  }
//***********************
![image](https://cloud.githubusercontent.com/assets/17421721/21792657/415c7dc2-d726-11e6-98f3-6a672666e937.png)

//***********************
created: function() {
      var env = this.$getConfig().env;
      if(env.platform == 'iOS'){
          var scale = env.scale;
          var deviceWidth = env.deviceWidth / scale;
          this.navBarHeight = 64.0 * 750.0 / deviceWidth;
      }
    }
页面刚进入的效果图（正常）：
![image](https://cloud.githubusercontent.com/assets/17421721/21792456/e37dd314-d724-11e6-91a7-80f506b97bcd.png)
随意点击某人进入聊天页面，再返回到消息列表页面，list的header往下移动了一个navbar的高度，如图所示：
![image](https://cloud.githubusercontent.com/assets/17421721/21792502/332dadf8-d725-11e6-8a87-54e883db71b8.png)
![image](https://cloud.githubusercontent.com/assets/17421721/21792510/42636a7e-d725-11e6-8c9a-82a24f30d68d.png)
但是在list前面加个空的div，代码如下
![image](https://cloud.githubusercontent.com/assets/17421721/21792667/54ff417a-d726-11e6-9ebe-a10a19a64a42.png)

前面提到的list header的位置问题就解决了，这是不是weex的bug还是说我程序有问题，如果我程序问题，麻烦指点下，谢谢

**Comment by yuhaolove** [comment]
@AlenGao 你的 wx-navpage 不会出现  我的情况么 #2186

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
