### ISSUE TITLE
WXSlider一直持有ViewPager中的View

### ISSUE THREAD

**Issue by bigconvience** [alibaba/weex#2192]
### 原因
WXSlider会持有ViewPager中所有的View，在数据项多的情况下容易OOM。扫描[demo](http://weex.alibaba-inc.com/playground/b1f86aecebd1fea5aeeef38f2ffcfb67), 期页面层次如下所示：
![snip20170110_13](https://cloud.githubusercontent.com/assets/1308834/21794994/0f144ade-d73a-11e6-8b1d-6f71fec07a04.png)

### 解决方案
在WXCirclePageAdapter中修改如下代码：

![snip20170110_12](https://cloud.githubusercontent.com/assets/1308834/21795042/599488f8-d73a-11e6-8c31-0088e846d294.png)

修改之后的页面层次如下所示：

![snip20170110_14](https://cloud.githubusercontent.com/assets/1308834/21795032/4ed4fc04-d73a-11e6-9f98-8c41d0e342db.png)

**Comment by misakuo** [comment]
您好，为了支持循环滚动，slider中可能出现一个View被多个position对应的情况，烦请确认这个变更会不会在item数量小于或等于3个时导致空白页面出现

**Comment by bigconvience** [comment]
@misakuo  我验证了一下，确实会有这个问题。我重新修改了一下，不对第一个和最后一个View进行删除。这种修改方式会缓存5个，而不是三个：
![snip20170110_16](https://cloud.githubusercontent.com/assets/1308834/21801856/63dd17f2-d75e-11e6-934b-cedad8c43d46.png)

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
