### ISSUE TITLE
对list设置了横向滑动属性scroll-direction，浏览器显示没问题，在手机上显示有问题

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2194]
对list设置了横向滑动属性，在浏览器中调试是正常，装到手机上就显示有错位了。具体的显示效果如下：

	a
		b
			c

代码如下：

    <template>
      <div>
    <list class = "elevator_tab_list_style" scroll-direction="horizontal">
      <cell class = "elevator_tab_item_style" repeat = "item in tabData" index = "{{$index}}" id = "item-{{$index}}" onclick = "tabClicked">
    <text>{{item.title}}</text>
    <div if = "{{item.clicked}}" class = "selected_tab_style"> </div>
      </cell>
    </list>
      <div>
    </template>
    
    <style>
    .elevator_tab_list_style {
      flex-direction: row;
    }
    .elevator_tab_item_style {
      padding: 20px;
    }
    .selected_tab_style {
      width: auto;
      height: 5px;
      margin-top: 10px;
      background-color: red;
    }
    .elevator_goods_item_style {
      flex-direction: row;
    }
    </style>
    
    <script>
    var dom = require('@weex-module/dom')
    module.exports = {
      data: {
    tabData:[{title:"母婴",clicked:true},
      {title:"全球直买",clicked:false},
      {title:"测试一下",clicked:false},
      {title:"美容彩妆",clicked:false},
      {title:"服饰鞋包",clicked:false},
      {title:"哈哈哈哈",clicked:false},
      {title:"家具各户",clicked:false},
      {title:"海外直勾",clicked:false},
      {title:"数码检点",clicked:false},
      {title:"营养保健",clicked:false}],
    clickedTabPosition: 0,
    clickedTabShown: false,
      },
      methods: {
    tabClicked: function(e) {
      this.clickedTabPosition = e.target.attr.index;
      for (var i=0; i<this.tabData.length; i++) {
    this.tabData[i].clicked = false;
      }
      this.tabData[this.clickedTabPosition].clicked = true;
      var el = this.$el('item-'+this.clickedTabPosition)
    console.log("el:"+el);
      dom.scrollToElement(el, {
    offset: -240
      })
    },
      }
    }
    </script>

**Comment by shangcongrong** [comment]
看了源码要用 hlist。。文档里却没说，感觉可以补充一下

**Comment by Jinjiang** [comment]
是的文档里没提，因为还没有完全做好，建议先不要在生产环境使用
谢谢

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
