### ISSUE TITLE
stream 文档修改建议

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#2214]
在 [stream](https://weex-project.io/doc/modules/stream.html)中关于response中ok属性的数据类型为
`ok(boolean): true if status code is bewteen 200～299.`,经测试，在iOS中返回的整形`1`,在Android中返回的`true`,在实际用的时候只能使用
```
        if(response.ok){//这里不能用response.ok === true 作为判断，否则iOS中，即使请求成功也会当作错误处理
            //success todo
          }
```

**Comment by kfeagle** [comment]
已经修复，会在后续版本发布
https://github.com/alibaba/weex/issues/2214
