### ISSUE TITLE
【BUG】【iOS】text 控件文字超长后在 list 中设置 lines 属性无法正常显示

### ISSUE THREAD

**Issue by YongX** [alibaba/weex#2216]
问题描述：
给一个 `list` 组件通过 `flex` 属性设定宽度后，在 `list` 组件中的 `text` 组件设置 `lines` 属性无效。但在安卓中和网页中均能正常显示。但是若用 `width` 属性设定宽度，或者将 `list` 组件换成 `scroller` 组件均能正常显示。

weex sdk 版本：0.9.4

代码如下：
```
<template>
  <div class="list-wrap">
    <div class="left">
      <list class="menu-left">
        <cell class="menu-item" repeat="menu">
          <text class="menu-name">{{ name }}</text>
        </cell>
      </list>
    </div>
    <div class="right">
      <list class="menu-right">
        <cell class="menu-item" repeat="menu">
          <text class="menu-name">{{ name }}</text>
        </cell>
      </list>
    </div>
  </div>
</template>
<script>
  module.exports = {
    data: {
      menu: [
        { name: 8.2, },
        { name: 8.8, },
        { name: 6.2, },
        { name: 9.8, },
        { name: 6.8, },
        { name: '用了一段很长的文字描述测试文字换行的时候显示', },
      ],
    },
  };
</script>
<style>
  .list-wrap {
    margin-top: 30px;
    flex-direction: row;
    flex: 1;
    background-color: #fff;
  }
  
  .left {
    flex: 3;
  }
  
  .right {
    flex: 9;
  }
  
  .menu-left {
    background-color: #f8f8f8;
  }
  
  .menu-right {
  }
  
  .menu-name {
    padding-left: 20px;
    padding-right: 20px;
    padding-top: 36px;
    padding-bottom: 36px;
    lines: 3;
    text-overflow: ellipsis;
    color: #666;
    font-size: 24px;
  }
  
  .menu-item {
    border-top-width: 1px;
    border-top-style: solid;
    border-top-color: #ededed;
  }
</style>

```
![qq20170111-0](https://cloud.githubusercontent.com/assets/7367678/21839814/c4131ae8-d814-11e6-8091-bd5ea3445126.png)

安卓中的效果如下：
![wechatimg22](https://cloud.githubusercontent.com/assets/7367678/21839933/7d360530-d815-11e6-9317-c402680461ee.jpeg)

将左边的 `list` 改为 `scroller` 后的效果如下：
![f2facc55-cd63-47dc-a73e-66fa6140a903](https://cloud.githubusercontent.com/assets/7367678/21839922/70306d76-d815-11e6-9c39-2b2c94e89fd7.png)

**Comment by YongX** [comment]
补充说明下，将上面的style中 
```
  .left {
    flex: 3;
  }
  
  .right {
    flex: 9;
  }
```
改为
```
  .left {
    width: 200px;
  }
  
  .right {
    flex: 1;
  }
```
也能正常显示。

**Comment by acton393** [comment]
@YongX flex layout 在 text这边还有点问题，建议暂时先写 width

**Comment by bmcciscoding** [comment]
![Uploading image.png…]()
lines 写在 css 里试试

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
