### ISSUE TITLE
navigator.pop() 中animated的值要设成'true' 或者 'false'， 否则iOS端会crash

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#2217]
在使用navigator组件的pop方法代码如下：
```
              var navigator = require('@weex-module/navigator');
              navigator.pop({'animated': true}, function (argument) {});
```
但是运行在iOS中执行这个方法会crash，确定错误如下，因为我传入animated的值为`true`,在OC中变成了一个 `NSNumber`类型的1，所以执行字符串`lowercaseString`方法会crash，
![image](https://cloud.githubusercontent.com/assets/12522809/21840295/adaa9b5c-d817-11e6-8e68-b1ba391bb62f.png)

后将`true` -> `'true'`，就能修复问题

我使用的weexSDK是0.9.4版本，这个问题也希望官方可以改正

**Comment by acton393** [comment]
#2225   thx ,这个确实是个bug， 已经fixed，下个版本会发布，也可以直接尝试ios-feature-20170118, 同时欢迎直接提pr~~~
