### ISSUE TITLE
一个小案例

### ISSUE THREAD

**Issue by Demon-liao** [alibaba/weex#222]
弄了一个简单的例子 `https://github.com/Demon-liao/Weex/tree/master/examples`
顺便总结下感受：
1. 整个布局几乎都是div+text这两个标签搭建的，感觉看着特别别扭，不知道像p标签，span标签这类支持不支持。
2. 按钮元素都是用div+text模拟出来的，希望能出一个类似butoon的标签，weex-ui里面的模拟button不能在外部去重置字体颜色，已经宽度自适应问题
3. line-height的不支持感觉太致命了，如果文本内容太长自动换行，文字与文字之间贴的太紧了
4. input的光标问题，只要获取到光标了，点击其他任何地方光标都无法失去，键盘无法收缩，而且安卓里面点击回车键时候还会出现换行符
5. ajax的数据通信还未支持跨域
6. checkbox，radio未支持
7. 表单的双向绑定未实现
8. 全局性的JS方法引入感觉有bug，无法引入值为function的变量。
9. 考虑性能问题CSS不支持父级继承，造成一些困扰。
10. 因为之前一直是用vue来开发，习惯了vue开发，某些语法的改变加上目前文档说明还没有健全感觉到很多逻辑性的内容缺少。
11. 文档最好也顺便提供下中文的。
12. 最后提一下，很多的书写习惯需要改变适应，跟平时写H5页面有一定的差异，尤其是tpl部分和css部分，没了解过native的人去接触，可能会造成不少困惑。

当然还有其他问题暂时没发现或者被我漏了，因为还在内测阶段，总体上来说，整个架构思路不错。希望在6月底的时候，能发布一个完善的项目出来，期待中..

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！

**Comment by passioncsu** [comment]
请问第四条
```
input的光标问题，只要获取到光标了，点击其他任何地方光标都无法失去，键盘无法收缩，而且安卓里面点击回车键时候还会出现换行符
```
有没有解决方案呢
