### ISSUE TITLE
安装weex-toolkit后运行weex --verion出错

### ISSUE THREAD

**Issue by iusn** [alibaba/weex#2234]
/usr/local/lib/node_modules/weex-toolkit/node_modules/vue-template-compiler/index.js:8
  throw new Error(
  ^

Error:

Vue packages version mismatch:

- vue@2.0.8
- vue-template-compiler@2.1.8

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-vue-loader/lib/parser.js:1:78)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)

**Comment by xl602** [comment]
遇到同样的问题

**Comment by iusn** [comment]
提示说
vue@2.0.8
vue-template-compiler@2.1.8
他俩版本不匹配 
但是我vue都是都是2.7.0版本 并木有 2.0.8版本

**Comment by exolution** [comment]
引起这个问题的关键是 你们曾经不小心npm install -g vue过 这样全局目录下就会有个旧版本的vue 
更新下weex-toolkit@beta 吧 我们现在会强制依赖一个最新的vue 以解决你们的这些问题

**Comment by iusn** [comment]
你好 还是有问题

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit@beta"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! weex-toolkit@1.0.1-beta.4 postinstall: `xtoolkit install weex-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weex-toolkit@1.0.1-beta.4 postinstall script 'xtoolkit install weex-builder'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the weex-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     xtoolkit install weex-builder
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex-toolkit

**Comment by JackPu** [comment]
@iusn Hello，你能再尝试下嘛？我们今天发布了新的版本。期待你的进一步反馈，也可以直接加我 760341479 具体排查

**Comment by iusn** [comment]
@JackPu 你好 还是一样的问题
sudo npm install -g weex-toolkit@beta
Password:
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/weex -> /usr/local/lib/node_modules/weex-toolkit/bin/weex

> fsevents@1.0.17 install /usr/local/lib/node_modules/weex-toolkit/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/lib/node_modules/weex-toolkit/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/spawn-sync
> node postinstall


> weex-previewer@1.2.3 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer
> node ./src/hook/post-install.js

Error:permission denied.Please apply the write premission to the directory: "/Users/nero"

> weex-toolkit@1.0.1-beta.5 postinstall /usr/local/lib/node_modules/weex-toolkit
> xtoolkit install weex-builder

fs.js:846
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/Users/nero/.xtoolkit'
    at Object.fs.mkdirSync (fs.js:846:18)
    at Object.exports.init (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/index.js:29:12)
    at Command.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/bin/xtoolkit.js:10:10)
    at Command.listener (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/bin/xtoolkit.js:17:9)
    at Module._compile (module.js:573:32)
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit@beta"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! weex-toolkit@1.0.1-beta.5 postinstall: `xtoolkit install weex-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weex-toolkit@1.0.1-beta.5 postinstall script 'xtoolkit install weex-builder'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the weex-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     xtoolkit install weex-builder
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex-toolkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls weex-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nero/Desktop/npm-debug.log
npm ERR! code 1

**Comment by JackPu** [comment]
@exolution  帮忙看下这个问题吧？

**Comment by exolution** [comment]
@iusn 
请不要使用sudo 安装weex-toolkit
如果提示权限不够 请更改/usr/local/lib/node_modules/的权限 sudo chmod 777 /usr/local/lib/node_modules

个人建议 不建议用sudo 装npm包 因为很多带有目录操作的cli工具 这样都会引起权限问题，sudo装了使用估计就要带一辈子sudo了，而且有时即使加sudo都没用（如果这个工具起了子进程）

如果 你不加sudo 都提示无法npm 安装 这说明 你的node是用root用户安装的（目测官网下安装包就是这样） 这时候只需要 sudo chmod 777 /usr/local/lib/node_modules 应该就能解决问题

**Comment by JackPu** [comment]
@isun 可以看下这里 [消除mac下npm全局安装使用sudo命令](http://www.jackpu.com/xiao-chu-macxia-npmquan-ju-an-zhuang-shi-yong-sudoming-ling/)

**Comment by youmu178** [comment]
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/nvm/0.29.0/versions/node/v5.3.0/bin/node" "/usr/local/Cellar/nvm/0.29.0/versions/node/v5.3.0/bin/npm" "install" "-g" "weex-toolkit@beta"
npm ERR! node v5.3.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! weex-toolkit@1.0.1-beta.5 postinstall: `xtoolkit install weex-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weex-toolkit@1.0.1-beta.5 postinstall script 'xtoolkit install weex-builder'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the weex-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     xtoolkit install weex-builder
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex-toolkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls weex-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/youzehong/npm-debug.log
npm ERR! code 1

**Comment by redye** [comment]
全局应该安装过 vue, vue 的版本 跟vue-template-compiler 不匹配，可以删掉全局环境下的 vue，目录在
/usr/local/lib/node_modules

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
