### ISSUE TITLE
WeexSDK for ios v0.9.5 中main.js版本滞后

### ISSUE THREAD

**Issue by jaylinwang** [alibaba/weex#2237]
CocoaPods  WeexSDK 0.9.5 中的 main.js 还是20161103版本，导致ios集成运行出错：

```
[undefined:63:37] ReferenceError: Can't find variable: Vue
```
拷入最新的main.js后运行正常

麻烦确认一下 😄

**Comment by Bijiabo** [comment]
感谢，怪不得今天用 0.9.5 有些组件显示不出来。

**Comment by acton393** [comment]
thx @jaylinwang     在发布的时候source 字段的url 没有填写最新的，会尽快发一个 0.9.5.1 fix

**Comment by acton393** [comment]
hi @jaylinwang 

麻烦尝试一下 0.9.5.1 这个版本， 已经[提交](https://github.com/CocoaPods/Specs/blob/6322e44bb486d9f6ecacf66892472e4790f0cf27/Specs/7/2/9/WeexSDK/0.9.5.1/WeexSDK.podspec.json)fix

暂时先关闭了，如果有问题可以再打开~， thx~

**Comment by jaylinwang** [comment]
OK啦，thx
