### ISSUE TITLE
bug 使用weex devtool报错 “unhandled 'error” event.

### ISSUE THREAD

**Issue by fengmingye** [alibaba/weex#2244]
您好，windows系统 使用weex debug命令来调试则报错，“unhandled 'error” event.
我们工程下面并没有event.js这个文件。
很奇怪呢，求解
![image](https://cloud.githubusercontent.com/assets/16618626/21915099/98244c5e-d972-11e6-8fcd-15308d2ee09a.png)

**Comment by exolution** [comment]
请查看一下weex-toolkit的版本 weex --version

**Comment by exolution** [comment]
看起来是node版本也太低 请更新node至6.0以上（现在6.0一下官方都不维护了 长效稳定版都6.9.x了）

**Comment by fengmingye** [comment]
![image](https://cloud.githubusercontent.com/assets/16618626/22179009/e37c93da-e081-11e6-83e9-2baf6c2e00e6.png)



![image](https://cloud.githubusercontent.com/assets/16618626/22179010/e79f02e0-e081-11e6-9260-2a77763a87d9.png)


恩恩，按照您说的试了下。如图，node版本确实低了，v4.3.1。

**Comment by fengmingye** [comment]
但是升级node版本至6.9.4后，也更新了npm，重新安装了weex-tookit
![image](https://cloud.githubusercontent.com/assets/16618626/22189089/591568c8-e155-11e6-85d4-63cbc834b85f.png)

然后使用weex debug命令的时候，报错weex “不是内部命令"’。如下图
![image](https://cloud.githubusercontent.com/assets/16618626/22189107/7a2e2522-e155-11e6-85e4-20ce67d495c8.png)

**Comment by fengmingye** [comment]
请问上诉问题可有遇到？有何对策?谢谢

**Comment by fengmingye** [comment]
![image](https://cloud.githubusercontent.com/assets/16618626/22876319/2043a4d0-f20b-11e6-9e2b-425016398b63.png)

现在遇到了这个问题，请问是怎么回事？谢谢
