### ISSUE TITLE
Install weex-toolkit@beta error

### ISSUE THREAD

**Issue by oMaten** [alibaba/weex#2245]
**OS:** darwin 15.6.0
**Nodejs:** 4.4.2
**tnpm:** 4.9.2
**npm:** 3.10.5

1. 执行 `$ tnpm i -g weex-toolkit@beta`
2. 错误提示
```
/Users/aaron.wf/.nvm/versions/node/v4.4.2/lib/node_modules/.weex-toolkit_npminstall/node_modules/.weex-previewer@1.1.3/src/libs/fs-utils.js:24
  let exists = fs.existsSync(src);
  ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

官网上似乎未写明 node 的版本要求

**Comment by BrickCarvingArtist** [comment]
![image](https://cloud.githubusercontent.com/assets/10768423/21951686/59729942-da45-11e6-9404-06e02b6ef120.png)

**Comment by Jinjiang** [comment]
@JackPu 有劳看看？看报错是 weex-previewer 的部分

**Comment by JackPu** [comment]
@Jinjiang  这个是ES6的部分，这个weex-previewer 新版已经将hook执行的地址修改到babel build后的文件了。

**Comment by dickeylth** [comment]
遇到 `tnpm install -g weex-toolkit@beta` 安装报错

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/typeof'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/build/hook/post-install.js:7:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by JackPu** [comment]
@dickeylth  您能再试下么？我刚刚用你的方式

`tnpm install -g weex-toolkit@beta` 没有报安装错误，您能发下你的环境么？

**Comment by dickeylth** [comment]
@JackPu https://github.com/weexteam/weex-toolkit/issues/45

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
