### ISSUE TITLE
"Weex Inside" Logo – Unfortunate misinterpretation

### ISSUE THREAD

**Issue by timoxley** [alibaba/weex#2253]
Concerning this "Weex Inside" logo I saw on the [rax readme](https://github.com/alibaba/rax/blob/07e20908e4e17b182873db0997729cb6c03ab690/README.md):

![image](https://cloud.githubusercontent.com/assets/43438/21920445/131d1dd6-d99c-11e6-96d3-f44ce36fbd65.png)

At first glance, the brain skips over the stylised "X". The logo initially reads as "**wee** inside".

You may or may not be aware that ["wee" is a commonly used slang term for "urinate" or "penis"](http://onlineslangdictionary.com/meaning-definition-of/wee).

Unfortunately this means the logo initially appears rather sexually suggestive. Mildly amusing, but probably not the intention.

Just letting you know.

**Comment by imsobear** [comment]
Rax will update to weex's new logo. Thanks for your advice.

![](https://img.alicdn.com/tps/TB1zBLaPXXXXXXeXXXXXXXXXXXX-121-59.svg)

**Comment by timoxley** [comment]
Great.
