### ISSUE TITLE
今天新init一个项目，playground扫描二维码没显示界面

### ISSUE THREAD

**Issue by w530385371** [alibaba/weex#2258]
今天新init一个项目，playground扫描二维码没显示界面，而在http://localhost:8080/index.html，界面是有的

**Comment by xxiiaass** [comment]
我也是一样的情况，看了下log, "Vue is not a constructor", 应该是官方bug吧。等人解决

**Comment by xxiiaass** [comment]
不知道是playground的错误，还是初始化代码的问题

**Comment by xxiiaass** [comment]
官方说，playground版本还没更新

**Comment by Jinjiang** [comment]
是的。Playground 还没有更新，暂时可以自己 build 一个 App 扫码预览
谢谢
