### ISSUE TITLE
repeat doesn't support object?

### ISSUE THREAD

**Issue by Gcaufy** [alibaba/weex#2259]
repeat doesn't support object? like this:

```
<div repeat="(k, v) in obj"></div>

data: {
    obj: {a:1,b:2}
}
```

**Comment by Hanks10100** [comment]
Yes, not supported in `.we`. 

We are now support to use Vue 2.x syntax, the directive `v-for` support objects.

**Comment by Gcaufy** [comment]
when it will be done?

**Comment by Jinjiang** [comment]
We have already have supported Vue 2.0 in tag v0.9.5

**Comment by tianlinzx** [comment]
@Jinjiang suppose this issue can be closed ?
