### ISSUE TITLE
[WXDebugger registerCallNativeModule:] unrecognized selector

### ISSUE THREAD

**Issue by xiaohuapunk** [alibaba/weex#2262]
debug时，扫一扫后 app crash掉了，报错 [WXDebugger registerCallNativeModule:] unrecognized selector，请查看一下

**Comment by hodgevk** [comment]
使用0.9.5版，安卓也是这样，换回0.9.4版就ok

**Comment by Neeeo** [comment]
希望能早点解决，调试不能……

**Comment by yangshengtao** [comment]
最新devtool链接已经迁移至[这里](https://github.com/weexteam/weex-devtool-iOS)，dev分支是最新开发分支

**Comment by Neeeo** [comment]
能否更新一下 pod 呢？能否让工具之间同步进度？

**Comment by xiaohuapunk** [comment]
新进展：终端升级一下weex-devtool `npm install -g weex-devtool`，就不报 ` [WXDebugger registerCallNativeModule:] unrecognized selector`这个错误了，但是调试的时候点击debug后app页面会触发刷新页面的方法`render`,然后页面加载失败，调试的错误：`Uncaught ReferenceError: weex is not defined`，其他issues有提到，所以现将此issues关闭了！
