### ISSUE TITLE
Already support Vue 2?

### ISSUE THREAD

**Issue by gabrielbuzziv** [alibaba/weex#2264]
Question in the title.

**Comment by envomer** [comment]
Also wondering. +1

**Comment by BrickCarvingArtist** [comment]
yes

**Comment by envomer** [comment]
@BrickCarvingArtist thanks a bunch. Is there any guide for using weex with vuejs 2.0?

**Comment by JackPu** [comment]
@envomer  现在文档里就是vue2.0的写法 演示 https://weex-project.io/cn/guide/index.html

**Comment by Jinjiang** [comment]
Yes that's a small guide in Chinese. The English docs will be finished soon.
And we have some examples in https://github.com/alibaba/weex/tree/dev/examples/vue
Thanks.
