### ISSUE TITLE
错别字:https://weex-project.io/cn/faq.html

### ISSUE THREAD

**Issue by babyking** [alibaba/weex#2265]
https://weex-project.io/cn/faq.html

![snip20170114_27](https://cloud.githubusercontent.com/assets/478250/21942345/a9474410-da07-11e6-849f-6782afe6ac45.png)

**Comment by Jinjiang** [comment]
@DoranYun 留意一下
谢谢

**Comment by DoranYun** [comment]
感谢反馈，已修复。
