### ISSUE TITLE
更新vue

### ISSUE THREAD

**Issue by uxiya** [alibaba/weex#2266]
更新到vue看文档说weex实例变量有config属性，可是打印出来是undefined，之前的this.getconfig（）也没有了，怎么获取配置呢？或者我的本地图片怎么加载，

**Comment by Jinjiang** [comment]
之前的 `this.getConfig()` 我们在 Vue 里改成了 `weex.config`，具体文档在这里 https://weex-project.io/cn/references/weex-variable.html

**Comment by uxiya** [comment]
这个文档看了，可是weex..config是undefined，weex的属性只有这些
```
![111](https://cloud.githubusercontent.com/assets/16519044/21968580/fade8eda-dbd0-11e6-9ea8-7cdd9fc22a93.png)

```

**Comment by uxiya** [comment]
![weex](https://cloud.githubusercontent.com/assets/16519044/21968653/e7794ffa-dbd1-11e6-92f5-99c74cf84810.png) weex只有这些属性 @Jinjiang

**Comment by jiyinyiyong** [comment]
版本的对应有点晕, 这边的 `0.9.5` 没有 changelog https://github.com/alibaba/weex/releases `weex.config` 是在这个版本里加入的吗?

**Comment by Hanks10100** [comment]
@jiyinyiyong `weex.config` 0.9.5 里已经有了，被 freeze 了，只读不可写。 0.9.5 是个小版本，等发 0.10.x 的时候会提供详细 change log。

**Comment by uxiya** [comment]
@Hanks10100 浏览器内怎么更新

**Comment by Hanks10100** [comment]
@uxiya 参考 #2282 ，web 端有些功能未同步更新，最近应该也会再发版的。
