### ISSUE TITLE
npm install weex-toolkit@beta -g安装执行到node ./src/hook/post-install.js时Error: EACCES: permission denied, mkdir '/var/root/.weex_tmp'

### ISSUE THREAD

**Issue by BrickCarvingArtist** [alibaba/weex#2267]
![image](https://cloud.githubusercontent.com/assets/10768423/21951931/7a5c531e-da4a-11e6-8d90-b2d9cc6d35e7.png)
我就只是想安装一下`weex-toolkit@beta`
系统：`MacOS 10.12.2`
`node`版本： `V6.0.0`，`V6.9.2`，`V7.4.0`全都试过
都是报同样的这个没有权限的错，我用`sudo`以及登录到`root`上安装都不行
`chmod 777`了`/usr/local/lib/node_modules`也一样是没权限

而cnpm安装可以装上
而创建好项目模板后，`npm install`或`cnpm install`安装依赖的时候，`qrcode V0.5.0`安装报错，去掉这个依赖可以装好，但是二维码就无法生成了，`node`打印出来的log上二维码的请求404
`node`版本`V6.9.2`时npm install报![image](https://cloud.githubusercontent.com/assets/10768423/21952141/9a7b5366-da4f-11e6-89cc-eda68a9305c9.png)
最终通过`vue-cli`创建的模版在`node`版本`V7.4.0`并且一定要`su root`进到root的权限，`sudo`都不行，终于`npm install`安装成功

**Comment by JackPu** [comment]
@BrickCarvingArtist 应该是用户home目录没有写的权限问题。这个问题已经mark，是我们考虑不到，你可以修改下 /var/root 的权限。

**Comment by wikieswan** [comment]
+1

**Comment by BusyHe** [comment]
这个问题怎么操作？我的也是同样的问题

**Comment by JackPu** [comment]
@BusyHe  你那边是报什么错误？

**Comment by BusyHe** [comment]
@JackPu  
![image](https://cloud.githubusercontent.com/assets/17348825/22920769/a54b3bf4-f2d1-11e6-9040-82ab6fd86c24.png)

**Comment by JackPu** [comment]
你把你用户目录设置下权限吧，
```
chmod -R 777  /usr/bushye
```
默认情况下目录归属用户都具备写权限，你修改下再试下，如果有问题直接qq我 760341479，也需要足够多的案例复现。

**Comment by b1g3rr0r** [comment]
这个问题貌似依然存在，Mac平台下。我首先chmod我的/var/root，然后又报我的个人目录的权限问题，我又chmod了我的个人目录，然后解决，不知道是不是跟我的node或者npm环境有关。

**Comment by BusyHe** [comment]
@b1g3rr0r 去掉mac的sudo权限
