### ISSUE TITLE
webpack --watch & serve -p 8080不管用

### ISSUE THREAD

**Issue by gitshuang** [alibaba/weex#2268]
# 热重载和服务不能同时启动，为什么呀
webpack --watch & serve -p 8080

**Comment by yangzhou2** [comment]
"dev": "webpack & serve -p 8080"
    要这样写才行

**Comment by Jinjiang** [comment]
如上所述。如有更多问题，请提供多一些你的开发环境信息和项目配置信息。谢谢

**Comment by gitshuang** [comment]
weex和react怎么整合？？？？
