### ISSUE TITLE
在weex-toolkit@beta版本用weex编译文件报错，0.6.4版本编译正常

### ISSUE THREAD

**Issue by worldsoon** [alibaba/weex#2274]
# 在weex-toolkit@beta版本用weex编译文件报错，0.6.4版本编译正常
![qq 20170116112053](https://cloud.githubusercontent.com/assets/10103820/21970048/ed1a39e0-dbdd-11e6-9af6-c69647796fc9.png)
![qq 20170116112605](https://cloud.githubusercontent.com/assets/10103820/21970109/954e4386-dbde-11e6-8ff7-30045ba52923.png)

运行环境：Windows
we文件0.6.4版本编译正常，但是升级到beta版本 后编译报错，详情看图

**Comment by exolution** [comment]
请尝试更新最新版本weex-toolkit 
1.0正式版已发布
