### ISSUE TITLE
picker在手机上为啥不能用啊

### ISSUE THREAD

**Issue by The-Pursuit-of-Happyness** [alibaba/weex#2275]
本来说，想试试这个全新的框架，可是引入picker后，界面压根不能正常渲染
![image](https://cloud.githubusercontent.com/assets/17919630/21970368/7db9917e-dbe0-11e6-8c12-fe1694532d26.png)

能够出来的是这个项目的例子，但是数据选择器，时间选择器，都不能正常的渲染出来，那几个按钮点了也是渲染错误，android手机上测试的
求大神指点迷津！！！！！

**Comment by alext1981** [comment]
@The-Pursuit-of-Happyness  运行这个例子的log你能贴出来么，这样可以加快我们排查的进度

**Comment by The-Pursuit-of-Happyness** [comment]
这个是chrome浏览器上运行时的结果，文档上有说h5目前不支持，但是手机端运行的也没法查看log啊，
![image](https://cloud.githubusercontent.com/assets/17919630/21971804/044fc0a6-dbef-11e6-80d0-5ceeefa98198.png)

**Comment by The-Pursuit-of-Happyness** [comment]
![image](https://cloud.githubusercontent.com/assets/17919630/21972118/13c0309a-dbf2-11e6-91d8-bb5fbb8b03ca.png)
连上android Studio后log里面一直这么刷

**Comment by misakuo** [comment]
你好，麻烦提供你的Android机型信息和操作系统版本信息。另外点击各个按钮后Logcat的输出内容可以的话也麻烦提供一下

**Comment by The-Pursuit-of-Happyness** [comment]
手机版本信息：
![image](https://cloud.githubusercontent.com/assets/17919630/21972602/90f672a6-dbf5-11e6-91d4-805047c1f0fb.png)

**Comment by The-Pursuit-of-Happyness** [comment]
三个选择按钮分别点击报的错误
![image](https://cloud.githubusercontent.com/assets/17919630/21972638/dbd22d7e-dbf5-11e6-9b74-735e696210b7.png)

**Comment by The-Pursuit-of-Happyness** [comment]
界面顶部都会显示：
render error :null

**Comment by misakuo** [comment]
android studio的log能提供一下么

**Comment by The-Pursuit-of-Happyness** [comment]
额，上面不显示的，一直刷那个上面的log
![image](https://cloud.githubusercontent.com/assets/17919630/21973472/dca13816-dbfb-11e6-8f79-ae5e60dab51f.png)

**Comment by misakuo** [comment]
请提供一下dialog.we文件的内容

**Comment by The-Pursuit-of-Happyness** [comment]
这个是源码中picker-demo.we中的代码，稍微改动了一点点
<template>
    <scroller>
        <wxc-panel title="picker module" type="primary">
            <text style="margin-bottom: 20px;">pick value: {{value}}</text>
            <wxc-button type="primary" onclick="{{pick}}" value="single pick" style="margin-bottom: 20px;"></wxc-button>
            <wxc-button type="primary" onclick="{{pickDate}}" value="pickDate" style="margin-bottom: 20px;"></wxc-button>
            <wxc-button type="primary" onclick="{{pickTime}}" value="pickTime"></wxc-button>
        </wxc-panel>

        <wxc-panel title="input component" type="primary">
            <text>onchange: {{txtChange}}</text>
            <input
                    type="date"
                    placeholder="select date"
                    class="input"
                    autofocus="false"
                    value=""
                    onchange="onchange"
                    max = "2029-11-28"
                    min = "2015-11-28"
            />
            <input
                    type="time"
                    placeholder="select time"
                    class="input"
                    autofocus="false"
                    value=""
                    onchange="onchange"
            />
        </wxc-panel>
    </scroller>
</template>

<style>
    .input {
        font-size: 60px;
        height: 80px;
        width: 400px;
    }
</style>

<script>
    require('weex-components');
    var picker
__weex_define__('@weex-temp/api', function(__weex_require__) {
  picker = __weex_require__('@weex-module/picker')
});
    module.exports = {
        data: {
            value: '',
            index: 0,
            txtChange: ''
        },
        methods: {
            pick: function() {
                //var picker = require('@weex-module/picker');
                var items = new Array("Saab","Volvo","BMW");
                var self = this;
                picker.pick({
                    'items':items,
                    'index':self.index
                },function (ret) {
                    var result = ret.result;
                    if(result == 'success')
                    {
                        self.value = items[ret.data];
                        self.index = ret.data;
                    }
                });

            },
            pickDate: function() {
                //var picker = require('@weex-module/picker');
                var self = this;
                picker.pickDate({
                    'value':'2016-11-28',
                    'max':'2029-11-28',
                    'min':'2015-11-28'
                },function (ret) {
                    var result = ret.result;
                    if(result == 'success')
                    {
                        self.value = ret.data;
                    }
                });
            },
            pickTime: function() {
                //var picker = require('@weex-module/picker');
                var self = this;
                picker.pickTime({
                    'value':'19:24'
                },function (ret) {
                    var result = ret.result;
                    if(result == 'success')
                    {
                        self.value = ret.data;
                    }
                });
            },
            onchange: function(event) {
                this.txtChange = event.value;
                console.log('onchange', event.value);
            }
        }
    }
</script>

**Comment by The-Pursuit-of-Happyness** [comment]
<template>
    <scroller>
        <wxc-panel title="picker module" type="primary">
            <text style="margin-bottom: 20px;">pick value: {{value}}</text>
            <wxc-button type="primary" onclick="{{pick}}" value="single pick" style="margin-bottom: 20px;"></wxc-button>
            <wxc-button type="primary" onclick="{{pickDate}}" value="pickDate" style="margin-bottom: 20px;"></wxc-button>
            <wxc-button type="primary" onclick="{{pickTime}}" value="pickTime"></wxc-button>
        </wxc-panel>

        <wxc-panel title="input component" type="primary">
            <text>onchange: {{txtChange}}</text>
            <input
                    type="date"
                    placeholder="select date"
                    class="input"
                    autofocus="false"
                    value=""
                    onchange="onchange"
                    max = "2029-11-28"
                    min = "2015-11-28"
            />
            <input
                    type="time"
                    placeholder="select time"
                    class="input"
                    autofocus="false"
                    value=""
                    onchange="onchange"
            />
        </wxc-panel>
    </scroller>
</template>

<style>
    .input {
        font-size: 60px;
        height: 80px;
        width: 400px;
    }
</style>

<script>
    require('weex-components');
    var picker
__weex_define__('@weex-temp/api', function(__weex_require__) {
  picker = __weex_require__('@weex-module/picker')
});
    module.exports = {
        data: {
            value: '',
            index: 0,
            txtChange: ''
        },
        methods: {
            pick: function() {
                //var picker = require('@weex-module/picker');
                var items = new Array("Saab","Volvo","BMW");
                var self = this;
                picker.pick({
                    'items':items,
                    'index':self.index
                },function (ret) {
                    var result = ret.result;
                    if(result == 'success')
                    {
                        self.value = items[ret.data];
                        self.index = ret.data;
                    }
                });

            },
            pickDate: function() {
                //var picker = require('@weex-module/picker');
                var self = this;
                picker.pickDate({
                    'value':'2016-11-28',
                    'max':'2029-11-28',
                    'min':'2015-11-28'
                },function (ret) {
                    var result = ret.result;
                    if(result == 'success')
                    {
                        self.value = ret.data;
                    }
                });
            },
            pickTime: function() {
                //var picker = require('@weex-module/picker');
                var self = this;
                picker.pickTime({
                    'value':'19:24'
                },function (ret) {
                    var result = ret.result;
                    if(result == 'success')
                    {
                        self.value = ret.data;
                    }
                });
            },
            onchange: function(event) {
                this.txtChange = event.value;
                console.log('onchange', event.value);
            }
        }
    }
</script>

**Comment by The-Pursuit-of-Happyness** [comment]
代码直接放进去会被转码：
我添加一个注释，你去掉就行了

**Comment by The-Pursuit-of-Happyness** [comment]
代码放进去不行，会被浏览器解析一部分，会变成下面这个样子，其实代码就是picker-demo.we的源码，只是稍稍改动了一点点

<template>
    <scroller>
        <wxc-panel title="picker module" type="primary">
            <text style="margin-bottom: 20px;">pick value: {{value}}</text>
            <wxc-button type="primary" onclick="{{pick}}" value="single pick" style="margin-bottom: 20px;"></wxc-button>
            <wxc-button type="primary" onclick="{{pickDate}}" value="pickDate" style="margin-bottom: 20px;"></wxc-button>
            <wxc-button type="primary" onclick="{{pickTime}}" value="pickTime"></wxc-button>
        </wxc-panel>

        <wxc-panel title="input component" type="primary">
            <text>onchange: {{txtChange}}</text>
            <input
                    type="date"
                    placeholder="select date"
                    class="input"
                    autofocus="false"
                    value=""
                    onchange="onchange"
                    max = "2029-11-28"
                    min = "2015-11-28"
            />
            <input
                    type="time"
                    placeholder="select time"
                    class="input"
                    autofocus="false"
                    value=""
                    onchange="onchange"
            />
        </wxc-panel>
    </scroller>
</template>

<style>
    .input {
        font-size: 60px;
        height: 80px;
        width: 400px;
    }
</style>

<script>
    require('weex-components');
    var picker
__weex_define__('@weex-temp/api', function(__weex_require__) {
  picker = __weex_require__('@weex-module/picker')
});
    module.exports = {
        data: {
            value: '',
            index: 0,
            txtChange: ''
        },
        methods: {
            pick: function() {
                //var picker = require('@weex-module/picker');
                var items = new Array("Saab","Volvo","BMW");
                var self = this;
                picker.pick({
                    'items':items,
                    'index':self.index
                },function (ret) {
                    var result = ret.result;
                    if(result == 'success')
                    {
                        self.value = items[ret.data];
                        self.index = ret.data;
                    }
                });

            },
            pickDate: function() {
                //var picker = require('@weex-module/picker');
                var self = this;
                picker.pickDate({
                    'value':'2016-11-28',
                    'max':'2029-11-28',
                    'min':'2015-11-28'
                },function (ret) {
                    var result = ret.result;
                    if(result == 'success')
                    {
                        self.value = ret.data;
                    }
                });
            },
            pickTime: function() {
                //var picker = require('@weex-module/picker');
                var self = this;
                picker.pickTime({
                    'value':'19:24'
                },function (ret) {
                    var result = ret.result;
                    if(result == 'success')
                    {
                        self.value = ret.data;
                    }
                });
            },
            onchange: function(event) {
                this.txtChange = event.value;
                console.log('onchange', event.value);
            }
        }
    }
</script>

**Comment by misakuo** [comment]
我编辑了一下，是上面这样的内容么？

**Comment by The-Pursuit-of-Happyness** [comment]
其实就是picker-demo.we的源码，就把@click改成了onclick ,其他好像几乎没有改变

**Comment by misakuo** [comment]
playground里的picker-demo可否正确运行？

**Comment by The-Pursuit-of-Happyness** [comment]
不能，只有input选择日期的能正确，其他都不行

**Comment by kfeagle** [comment]
@misakuo @The-Pursuit-of-Happyness ios上The-Pursuit-of-Happyness提供的demo是可以运行的

**Comment by The-Pursuit-of-Happyness** [comment]
那为啥Android上不能运行?  ;) ;)

**Comment by misakuo** [comment]
需要确认几个问题：
1. we文件逻辑是否有问题，上面js报的错误是`picker.pick is not a function`，表明picker模块是存在的，不过调用的函数未被定义，你可以先把picker和picker.pick在console里输出一下看看具体指向什么对象，或者使用DevTools断点调试。
2. 如果可以在Android端 Weex SDK 内断点，确认`@WXModuleAnno`修饰的几个方法是否有被调用到，如果调用异常，麻烦提供Logcat内的异常信息

**Comment by The-Pursuit-of-Happyness** [comment]
1、picker.pick 这个函数不是我定义的，picker输出是一个对象，picker.pick输出是undefined 
2、@WXModule的其他几个模块是可以用的，比如说动画，toast等都是可用的
3、playground内的Picker示例中， 在谷歌浏览器中 select data 和select time 是可以正常运行的，但是android端就会被渲染成普通文本输入框。
4、非常想请教一下，如果要实现点击输入框上传图片或文件，该如何实现

非常感谢你的耐心解答，祝愿你们的weex框架越来越好用！！！！

**Comment by misakuo** [comment]
Picker的Android实现在`WXPickersModule`这个类，你可以在这里面断点试一下，点击输入框之后的逻辑处理在`AbstractEditComponent`，目前是根据`type`参数来区分的，点击输入框上传文件我之前写过一个简单的实现在https://github.com/misakuo/weex/blob/android-feature-filechooser/android/sdk/src/main/java/com/taobao/weex/appfram/filechooser/WXFileChooserModule.java

**Comment by lovederh** [comment]
我在ios中不能用，有没有人遇到，ios 10.3 版本，单个pick是好使的，但是pick成功后在调用一个pick就不好使了
`//选择开始日期
      pickDate: function() {
        var arr = this.currentdate.split('-');  
        var year = arr[0]; //获取当前日期的年份  
        var month = arr[1]; //获取当前日期的月份  
        var day = arr[2]; //获取当前日期的日
        var year1 = parseInt(year) + 1;  
        var t2 = year1 + '-' + month + '-' + day;  
        picker.pickDate({
        value: this.currentdate,
        max: t2,
        min: '2017-01-01'
        }, event => {
          if (event.result === 'success') {
            this.date = this.formatDate(event.data);
            this.pickTime();
          }
        })

      },`
` //选择开始时间
      pickTime: function() {
        picker.pickTime({
            'value':this.currenttime
        },event => {
          if (event.result === 'success') {
            this.icontrue02=false;
            this.time = event.data;
            this.qj.datetime=this.date+" "+this.time;
            if(this.qj.datetime<this.qj.datetime1){
              this.qj.datetime=this.date+" "+this.time;
              return this.duraTion();
            }else{
              this.qj.datetime="请选择(必填)";
              modal.alert({
                message: '请假开始时间要小于请假结束时间，请重新选择',
                duration: 0.3
              })
            }
          }
        });
      },`

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
