### ISSUE TITLE
Debug报seesion为null的错误

### ISSUE THREAD

**Issue by answerPUNK** [alibaba/weex#2277]
debug 一个we文件时报，toolkit已经重新更新过一次无效

`Launching Dev Tools...
New version[0.2.72
] of Weex debugger detected! Please update.(npm install -g weex-toolkit)
 can not join session,unknown sessionId[null]
@(C:\Users\JoeDennis\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\
weex-devtool\lib\components\P2PSession.js:218:24)`

页面则显示
Debugee App: WeexPlayground
Press F12 to open Developer Tools. Please select Sources tag to start!
Log Level  
**Warning:The session with native was closed,please restart your native app!**

**Comment by Hanks10100** [comment]
你的版本是多少呢？除了更新 weex-toolkit 还有更新一下 weex-devtool 。@exolution 关注一下。

关于工具的问题也可以在这里提 issue https://github.com/weexteam/weex-toolkit

**Comment by answerPUNK** [comment]
weex-toolkit@1.0.1-alpha 我用的淘宝镜像装的

**Comment by zcl0001** [comment]
同样的错误，weex-toolkit v2.7，playground是svn下载源码编译 自己手机的 
![image](https://cloud.githubusercontent.com/assets/24770276/22047942/0c0d2884-dd65-11e6-84a3-01ef3eb25cc4.png)

**Comment by exolution** [comment]
这个问题 已在 weex-toolkit issue里回复

**Comment by lisongyu** [comment]
这个问题已经解决了吗，用什么方案解决的我也遇到一样的问题ios系统

**Comment by lisongyu** [comment]
更新最新谷歌浏览器解决
