### ISSUE TITLE
weex.config与文档所说不符合

### ISSUE THREAD

**Issue by emmanuelwang** [alibaba/weex#2280]
在文档中说移除了this.getconfig换成了weex.config,可是在调试过程中却并没有这个，config为undefined
![image](https://cloud.githubusercontent.com/assets/13744738/21978747/e3cfcc72-dc16-11e6-9926-f0517c622b03.png)

**Comment by Hanks10100** [comment]
`weex.config` 在 WeexSDK >= 0.9.5 中才会有，目前 web 版本中还未更新。

**Comment by emmanuelwang** [comment]
@Hanks10100 那现在web版要么降版本，要么用不了吗？是否有其他解决途径

**Comment by Ghost-Ge** [comment]
文档是硬伤，乱七八糟的，

**Comment by jiyinyiyong** [comment]
@Ghost-Ge 我也听到几次了... 个人感觉倒不是文档, 现在急缺 FAQ 啊...

**Comment by Hanks10100** [comment]
@emmanuelwang 最近 web 端也会发版的，重点关注 0.10.x 版本吧，0.9.5 是个小版本，web 上有些功能和 sdk 里未同步。

**Comment by dongnaebi** [comment]
请坚定三端一致的初衷。

**Comment by Hanks10100** [comment]
@dongnaebi 👌 会一直坚持的。
