### ISSUE TITLE
Android 更新之后 weex undefined，原来扩展的 module 失效

### ISSUE THREAD

**Issue by karynsong** [alibaba/weex#2282]
花了一整天的时间，将`app`升级到最新版，并把前端的框架换成了`vue`，`IOS`能完美运行，`Android`一直报错，`web`上的页面渲染表现和原生完全不一样，已放弃`web`调试。

> * debug 看了之后发现，控制台不报错 weex is undefined。
> * 使用 weex.requireModule 原有的 Android 扩展都 undefined 了。
> * web 上的渲染表现非常不一致。
> * 新版目前调试非常困难，基本属于盲人摸象，写的`标签`渲染出来的结果不对。
> * 求官方大神来个指导群，最近官方文档更新略着急，完全不知道怎么做，孤独且毫无指导的摸索太辛苦，非常希望能在前期基础问题解决完成之后，以后能为 weex 贡献一些组件

**Comment by karynsong** [comment]
安卓`debug`控制台报错`weex is undefined`还没有解决
`Android module`是因为之前扩展注解写的都是 `WXModuleAnno` 
注解改成`JSMethod`就好了

**Comment by karynsong** [comment]
现在除了`Android`和`iOS`再`debug`的时候都会报 `weex is undefined` 都`OK`了
尝试在`webpack plugins BannerPlugin`中加入`framework Weex`，`devtools`还是没有解析，目前已经放弃尝试解决了
由于现在`web`和客户端表现差异比较大，所以只能看客户端，但是没有调试工具，简直要崩溃，希望官方能早日更新

**Comment by Jinjiang** [comment]
@exolution 留意一下调试工具方便的问题吧
谢谢

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
