### ISSUE TITLE
文档此处错误 " vue init weex awesome-project "

### ISSUE THREAD

**Issue by charmingzuo** [alibaba/weex#2283]
https://weex-project.io/cn/guide/index.html

![image](https://cloud.githubusercontent.com/assets/2429983/21983058/36360e5a-dc2a-11e6-9f82-63687f0e3719.png)

`vue init weex awesome-project`

实际应为

`vue init Jinjiang/weex-template awesome-project`

**Comment by Hanks10100** [comment]
多谢提醒，目前在 [vuejs-templates](https://github.com/vuejs-templates) 仓库中暂时把 weex 的模板项目去掉了，等模板准备好后会再加上。现在会先把文档改掉，删除这一句。

**Comment by Hanks10100** [comment]
@charmingzuo 现在文档已经更新了。
