### ISSUE TITLE
Why setNeedsLayout also invalid the supercomponent in iOS SDK?

### ISSUE THREAD

**Issue by CodeLife2012** [alibaba/weex#2284]
Any doc or blog about the layout and draw pass in SDK side should be better.

**Comment by acton393** [comment]
hi  @CodeLife2012  
Because current component layout may have affect on its supercomponent,  so adjust it.

we are concerning  about the doc for layout, as so much thing to do, so it is delayed.

**Comment by CodeLife2012** [comment]
I think it's because changing of cell's size will need to relayout the whole table, a bit different from iOS layout system.
