### ISSUE TITLE
Cloning spec repo `alibaba-inc-specs` from `git@gitlab.alibaba-inc.com:alipods/specs.git`

### ISSUE THREAD

**Issue by forrest23** [alibaba/weex#2286]
执行weexpack run ios命令后

=> Will start iOS app
 => pod update
Update all pods
Cloning spec repo `alibaba-inc-specs` from `git@gitlab.alibaba-inc.com:alipods/specs.git`
[!] Unable to add a source with url `git@gitlab.alibaba-inc.com:alipods/specs.git` named `alibaba-inc-specs`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
? Choose one of the following devices iPhone 6 ios: 10.0
project is building ...
** BUILD FAILED **

    cd /Users/fgmh/Project/weex/weextest/platforms/ios
    /bin/sh -c /Users/fgmh/Project/weex/weextest/platforms/ios/build/Build/Intermediates/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Script-359BEE13DD78032A2CB791E8.sh
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Script-359BEE13DD78032A2CB791E8.sh
(1 failure)

这个是 cocoapods没安装好，造成的吗？

**Comment by yangshengtao** [comment]
升级一下weexpack版本试试

**Comment by Jinjiang** [comment]
明显的内网问题，集团内部沟通解决吧
谢谢

**Comment by lilin666** [comment]
@forrest23 我遇到的问题跟你一样的，你后来怎么解决的？
