### ISSUE TITLE
weex使用全局事件globalEvent无法正确触发

### ISSUE THREAD

**Issue by facetome** [alibaba/weex#2301]
我在使用全局事件的时候，在ready方法中注册了一个事件，但是这个事件在页面渲染完成之后里面就回调了（listener中执行了后续代码），而在native中调用mInstance.fireGlobalEventCallback没能触发listener中的回调
//native中调用代码
mConfirm.setOnClickListener(new OnClickListener() {
          @Override
           public void onClick(View v) {
                Map<String, Object> param = new HashMap<>();
                param.put("key", "native invoke weex");
                mInstance.fireGlobalEventCallback("globalevent", param);
            }
        });

// js中调用代码
var globalEvent = require('@weex-module/globalEvent');
ready:function() {
             globalEvent.addEventListener("globalevent", new function(event) {
                  model.toast({"message":"native call js", "duration":1});
              });
        }

看了文档，使用方式应该没有什么问题，如果有我未发现的地方，请指出，谢谢

**Comment by xkli** [comment]
@facetome 你的JS有点问题，请参考下面的写法。
```
<template>
    <div>
       <text>这是一个测试页面!</text>
    </div>
</template>
<script>
    module.exports = {
        data: {},
        ready: function () {
            var globalEvent = require('@weex-module/globalEvent');
            globalEvent.addEventListener("globalevent", function (event) {
                console.log("into--[addEventListener]");
                var modal = require('@weex-module/modal');
                modal.toast({
                    'message': "native call js",
                    'duration': 1
                });
            });
        },
        methods: {}
    }
</script>
```
