### ISSUE TITLE
swift WXImgLoaderDefault use SDWebImage error

### ISSUE THREAD

**Issue by snice** [alibaba/weex#2302]
`

    class WXImgLoaderDefault:NSObject, WXImgLoaderProtocol{
    func downloadImage(withURL url: String!, imageFrame: CGRect, userInfo options: [AnyHashable : Any]! = [:], completed completedBlock: ((UIImage?, Error?, Bool) -> Void)!) -> WXImageOperationProtocol! {
        var temp:String;
        if(url.hasPrefix("//")){
            temp = "http:" + url;
        }else{
            temp = url;
        }
        let operation = SDWebImageManager.shared().downloadImage(with: URL(string: temp), options: SDWebImageOptions.retryFailed, progress: { (receivedSize:Int, expectedSize:Int) in
            
        }) { (image:UIImage?, error:Error?, cacheType:SDImageCacheType, finished:Bool, imageURL:URL?) in
            if ((completedBlock) != nil) {
                completedBlock(image, error, finished);
            }
        };
        return operation as! WXImageOperationProtocol;
    }
    }
`

运行报错：
Could not cast value of type 'SDWebImageCombinedOperation' (0x1006aa858) to 'WXImageOperationProtocol' (0x100130db8).

**Comment by acton393** [comment]
try   `return operation as? WXImageOperationProtocol;` 

[more detail](https://github.com/acton393/WeexSwiftSample/blob/master/SwiftWeexSample/WXImageLoaderDefaultImplement.swift#L29)

**Comment by ikpower** [comment]
有人解决了吗
