### ISSUE TITLE
class 语法支持不全

### ISSUE THREAD

**Issue by sunorry** [alibaba/weex#2303]
这种不支持
`:class="{'border-active' : active === 'guide', 'border-default': active !== 'guide' }"` 

写成数组的方式就好了
`:class="[ active === 'guide' ? 'border-active' : 'border-default' ]"`

之前版本是支持的。
好闹心啊。

**Comment by Hanks10100** [comment]
这是已知特性，在 Weex 中 classList 只能是数组，参考 [comment in class](https://github.com/vuejs/vue/blob/994aee4f869d68a00c3b9d87daa9c8d84623ac42/src/platforms/weex/runtime/modules/class.js#L17) 。由于 Weex 在 native 上的渲染机制，从类名中取样式会是一个高频操作，简化这部分逻辑是出于性能考虑的。
