### ISSUE TITLE
failed to execute weexpack run ios command

### ISSUE THREAD

**Issue by hwysjj** [alibaba/weex#2304]
On my mac, 

1. Run `weexpack create xxx` to init a weex project.
2. cd xxx, run `weexpack run ios`, display the following error:

> Cloning spec repo `alibaba-inc-specs` from `git@gitlab.alibaba-inc.com:alipods/specs.git`
> [!] Unable to add a source with url `git@gitlab.alibaba-inc.com:alipods/specs.git` named `alibaba-inc-specs`.
> You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

I'm pretty sure I installed **_cocoapods_** successfully, is that issue about `git@gitlab.alibaba-inc.com:alipods/specs.git`, this impacts me to use **_weexpack_**, could anyone help me on this?

**Comment by YongX** [comment]
Got the same issue on weexpack 0.3.2.  My workaround is downgrading to 0.2.5.
FYI: [https://github.com/weexteam/weex-pack/issues/56](https://github.com/weexteam/weex-pack/issues/56)

**Comment by hwysjj** [comment]
Upgraded weexpax to 0.3.3, works fine.
