### ISSUE TITLE
导入内置的module出现问题：Module not found: Error: Cannot resolve module '@week-module/event'

### ISSUE THREAD

**Issue by programer001** [alibaba/weex#2307]
ios ，自定义module，但是在.we文件中 var eventModule = require('@week-module/event');然后执行命令weex xxx.we就会出现这种问题，不知道怎么解决，有人遇到过么

**Comment by acton393** [comment]
有注册么

**Comment by programer001** [comment]
<img width="748" alt="4e16053f-02ab-413b-9445-2bef91a724aa" src="https://cloud.githubusercontent.com/assets/8346968/22051981/0ede7fe6-dd82-11e6-9447-75a9544a2588.png">
是有注册的,然而这个注册不是在native的代码里的么。by the way。项目运行时还有另一个问题就是WXDevTool注释的那一行，如果打开，渲染的页面就成了空白页，回调render fail

**Comment by yangshengtao** [comment]
WXDevtool最新代码仓库在[这里](https://github.com/weexteam/weex-devtool-iOS/tree/master/Devtools/WXDevtool)，启动devtool需要先运行weex debug命令，另外''host''这个字段如果真机调试需要换成你本地的ip地址

**Comment by programer001** [comment]
一样的，最终页面还是会被渲染成空白页

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
