### ISSUE TITLE
[ios] sdk 0.9.5， *.vue 下，引用内部模块时 weex undeifned

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#2314]
pod上的0.9.5有这个问题，如果自己拿工程编译js framework，就没有这个问题。
开启 debugger 也会提示 weex not found

**Comment by fnbone** [comment]
pod 使用0.9.5.1，0.9.5少了main.js

**Comment by Neeeo** [comment]
说的就是0.9.5.1

**Comment by acton393** [comment]
0.9.5.1 应该是ok的， 0.9.5 可能因为本地缓存的问题，是老版本，但是不应该少 jsfm(main.js)的

**Comment by Neeeo** [comment]
更新weex-devtool 到 0.2.74 后问题解决
