### ISSUE TITLE
【bug】scroller组件 refresh 中的 text 文字不可以修改

### ISSUE THREAD

**Issue by karynsong** [alibaba/weex#2330]
```
<scroller>
       <refresh class="refresh" @refresh="onrefresh" :display="refreshing ? 'show' : 'hide'">
            <text class="indicator">{{ freshMessage }}</text>
        </refresh>
</scroller>
```
freshMessage: 视图上直接就消失了

**Comment by Jinjiang** [comment]
Hi，方便在 http://dotwe.org/ 写一个例子吗？我这边没有重现你描述的问题
谢谢

**Comment by karynsong** [comment]
<template>
  <div >
    <scroller>
      <refresh class="refresh" @refresh="onrefresh" :display="refreshing ? 'show' : 'hide'">
        <text class="indicator">下拉刷新</text>
      </refresh>
      <text class="home">hahaha</text>
    </scroller>
  </div>
</template>
<style>
    .home {
        background-color: blue;
        height: 3000px;
    }
    .indicator {
        color: #888888;
        font-size: 42px;
        text-align: center;
    }
</style>
<script>
    module.exports = {
        data(){
            return {
                freshText: '下拉刷新',
                refreshing: false,
            }
        },
        methods: {
            onrefresh(){
                this.freshText = '加载中';
                this.refreshing = true;
                setTimtout(() => {
                  this.freshText = '下拉刷新';
                  this.refreshing = false;
                }, 3000);
            }
        }
    }
</script>

**Comment by karynsong** [comment]
http://dotwe.org/vue/3f5d6bd191eef0c18939761323b4eba7

**Comment by Hanks10100** [comment]
这个问题统一记录在 #2421 .
