### ISSUE TITLE
[ios] vue模式下，无法修改类的 toString 方法

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#2334]
在iOS 设备上，修改类的 toString 方法会提示：

> Cannot assign to read only property 'toString' of object

在游览器里没这个问题。用的sdk是从 `dev` 分支下自己编译的最新版。

复现代码:
```vue
<template>
  <div class="wrapper" @click="update">
    <image :src="logoUrl" class="logo"></image>
    <text class="title" v-if="!show">Good!! {{target}}</text>
    <text class="title" v-else-if="show">Bad!! {{target}}</text>
  </div>
</template>

<style>
  .wrapper { align-items: center; margin-top: 120px; }
  .title { font-size: 48px; }
  .logo { width: 360px; height: 82px; }
</style>

<script>
  export default {
    data: {
      logoUrl: 'https://alibaba.github.io/weex/img/weex_logo_blue@3x.png',
      target: 'World',
      show: true,
    },
    mounted: function() {
      debugger;
      var a = function() {

      };
      a.prototype.toString = function(){return 'hhhhhh';};
    },
    methods: {
      update: function (e) {
        this.target = 'Weex'
        console.log('target:', this.target)
      }
    }
  }
</script>
```

**Comment by Hanks10100** [comment]
与 Vue 无关，因为我们将 `Object.prototype` freeze 了，所以无法覆盖原型中的 `toString` 。参考 #1529

**Comment by Neeeo** [comment]
有个问题是，我用到的一个第三方库 [url-parse](https://www.npmjs.com/package/url-parse) 里重写了自己的 `toString`，导致现在用到它的地方都崩溃。
另外，为什么在 web 环境下没问题？

**Comment by Hanks10100** [comment]
（如果你写的是 Vue 项目的话）在 Web 环境上是直接用 Vue.js 渲染的，不依赖于 Weex ，不含 Weex runtime 的代码，也就没 freeze 原型链。

**Comment by Hanks10100** [comment]
将来很可能也会在 `weex-vue-render` 里把原生对象的原型 freeze 起来的。

**Comment by Neeeo** [comment]
顺便问一下，开 debugger 的时候，weex 对象找不到这个问题有解决办法吗？
https://github.com/alibaba/weex/issues/2314

**Comment by Hanks10100** [comment]
@Neeeo 是 weex-toolkit 工具的问题，工具执行的时候会包上一层函数，没有把 weex 变量传进去，现在应该已经修掉了。

**Comment by dickeylth** [comment]
@Neeeo url-parse 可以跟踪这个 pr: https://github.com/unshiftio/url-parse/pull/54
