### ISSUE TITLE
【win7集成android】font-face自定义图标使用问题

### ISSUE THREAD

**Issue by chinafootballyu** [alibaba/weex#2336]
1、sdk-->0.9.4
2、自定义字体直接赋值给text标签在真机（android4.4.2）可以显示出想要的效果，以插值方式赋值显示的是unicode。

代码：
![1](https://cloud.githubusercontent.com/assets/15266646/22100073/e518d020-de68-11e6-81d1-b079cba74dfb.png)
![2](https://cloud.githubusercontent.com/assets/15266646/22100075/e623c70e-de68-11e6-9f47-fa2f1c21646b.png)

**Comment by misakuo** [comment]
```js
cart: \uxe698;
```
这样试一下

**Comment by misakuo** [comment]
```js
cart: '\ue698'
```
这样试试

**Comment by chinafootballyu** [comment]
@misakuo 这样修改就可以了，后续会解决这个问题吗？还是建议写成这种格式？

**Comment by misakuo** [comment]
`&#xe698`是html entity number，在js里需要转成unicode即`\ue698`的形式，这不是一个bug

**Comment by chinafootballyu** [comment]
好的，thanks
