### ISSUE TITLE
header 在IOS中渲染效果与安卓和H5都不一致，甚至叫错误

### ISSUE THREAD

**Issue by hodgevk** [alibaba/weex#2341]
[测试代码](http://dotwe.org/62da004fa0604af0985a6bef9e80e5cd)
这个代码在IOS中显示content浮在header上面并且顶在最顶端，而且header没有与窗口宽度保持一致。相同代码在安卓、H5上都是相同效果，header宽度100%，content在header下面。

**Comment by cxfeng1** [comment]
@hodgevk  麻烦给一下demo谢谢， http://dotwe.org/weex/

**Comment by cxfeng1** [comment]
@hodgevk  header只在list组件下生效，  其他场景下无法保证功能可用性

**Comment by hodgevk** [comment]
明白了。谢谢
