### ISSUE TITLE
stream.fetch在浏览器预览时，会出现跨域问题，但是在weex playground中预览正常的

### ISSUE THREAD

**Issue by zhugexiansheng** [alibaba/weex#2346]
```
stream.fetch({
          method: 'GET',
          url: 'http://liuguangli.mock.uctest.local/weex/goodsList',
          type: 'json',
          body: body
        }, function (res) {
           if ( res.ok ) {
             callback(res.data.data);
           }
        });
```
使用这个模块获取数据，在浏览器上面预览的时候会出现跨域错误
![image](https://cloud.githubusercontent.com/assets/13861291/22137850/7e0851f2-df18-11e6-8ab6-b3776ea3a028.png)
但是在weex playground下预览却没有问题，是在浏览器下需要特殊处理吗？

**Comment by acton393** [comment]
hi @zhugexiansheng  尝试查看下这个issue  #1933

**Comment by zhugexiansheng** [comment]
hi @acton393 我试过里面的方法了，但是好像没用，而且在浏览器上面数据是已经是返回了的
![image](https://cloud.githubusercontent.com/assets/13861291/22139570/da11bc0a-df21-11e6-8495-256d0f16017e.png)
但是还是报-1的错误，是不是返回的数据需要特殊格式？
![image](https://cloud.githubusercontent.com/assets/13861291/22139601/0b5ce320-df22-11e6-8363-b884eec7d74c.png)

**Comment by abczdefg** [comment]
防止跨域不是浏览器中的安全机制吗？playground中已经不是webview了？

**Comment by jaylinwang** [comment]
首先在服务器端允许跨越 @zhugexiansheng

**Comment by zhugexiansheng** [comment]
@jaylinwang @abczdefg 好像是这个问题，之前可能看错了，以为数据已经返回了
@acton393 可以close了

**Comment by zhe-he** [comment]
服务器添加一个返回头就可以了。
close  提问的人就可以close
