### ISSUE TITLE
weex-vue-render的slider组件bug

### ISSUE THREAD

**Issue by dongnaebi** [alibaba/weex#2350]
首次rander方法没有获取到this._cells，然后就执行了updateLayout。导致frameCount没有计算就给`inner.style.width`赋值，渲染出来的ul的宽为0，slider组件不显示。

slider子组件indicator的私有样式没有做处理。

还想问一下，0.10版本大概什么时候发？

**Comment by dongnaebi** [comment]
.weex-scroller-horizontal .weex-scroller-inner{width:100%}怕是不会自动撑开。。。

**Comment by MrRaindrop** [comment]
0.10 版本目前还有一些问题，richtext 和 伪类 暂不支持，所以暂时还没有发，另外从 0.10 以后会逐步切换到 vue-render，0.10 的功能会逐渐迁移到 vue-render 上，目前也有一些问题需要处理和修复. 

slider 的问题 @Hanks10100 麻烦看一下.

**Comment by Hanks10100** [comment]
slider 和 #2365 说的是同一个问题吧。如果第一次渲染的时候没有子节点（数组中没数据），的确会把 `weex-slider-inner` 宽度置为 0 ，这个问题最近发个小版本修复一下。 另外 Weex 不支持 CSS 里的关系选择器（不支持两个类名写一起），那种写法只在 Web 中有效。

**Comment by dongnaebi** [comment]
@Hanks10100 抱歉样式的问题没有描述清楚。
[https://github.com/Hanks10100/weex/blob/html5-feature-vue-render/html5/render/vue/styles/components.css#L199](https://github.com/Hanks10100/weex/blob/html5-feature-vue-render/html5/render/vue/styles/components.css#L199)
这个以及L205导致了横向滚动不能滚。

如果要发小版本，建议在weex-vue-render 0.1.7修复/支持以下：

1. 处理slider子组件indicator的私有样式。
2. 修复横向滚动
3. 处理lines:1
4. 添加weex.config

目前只发现这些

**Comment by Hanks10100** [comment]
@dongnaebi 多谢提醒。由于在 weex-vue-render 中 CSS 纯粹是由浏览器解析，indicator 上的私有样式属性、lines 属性不是合法的 CSS ，暂不支持（会支持写在标签属性里）。scroller 横滚问题正在修复。

**Comment by Hanks10100** [comment]
@dongnaebi weex-vue-render@0.1.7 已经更新，添加了 `weex.config` 修复了 scroller 横滚样式，其他 feature 还待讨论。

**Comment by dongnaebi** [comment]
scroller横滚还有问题啊，weex-scroller-inner的样式`width:auto`撑不开，建议加上absolute让其脱离文档流，就能撑开了
