### ISSUE TITLE
导入内置的module出现问题:@week-module/event undefined

### ISSUE THREAD

**Issue by zdpdsy** [alibaba/weex#2353]
ios vue模式下,vue文件下导入event module，报一下错误。
![image](https://cloud.githubusercontent.com/assets/7123339/22141439/09368492-df2d-11e6-8740-2aa79db3ca8c.png)

vue代码如下
![image](https://cloud.githubusercontent.com/assets/7123339/22141475/36b816c4-df2d-11e6-9026-6ea614d71c96.png)

ios工程已注册对应的Module
![image](https://cloud.githubusercontent.com/assets/7123339/22141506/52a5c520-df2d-11e6-8143-76f636dd5cb7.png)

**Comment by kfeagle** [comment]
vue中应该通过requireModule 引入，你有相关demo吗
这儿有例子https://weex-project.io/references/modules/clipboard.html

**Comment by Hanks10100** [comment]
@zdpdsy 另外提醒一下，Vue 2.0 里没有 `ready` 生命周期，可以使用 `mounted`。

**Comment by zdpdsy** [comment]
@kfeagle  用的就是官方的weexDemo。但是我使用weex.requireModule('@weex-module/event')会报错，然后导致界面渲染空白
![image](https://cloud.githubusercontent.com/assets/7123339/22142779/87694fa2-df32-11e6-9cde-1cf9482fb80e.png)

**Comment by Hanks10100** [comment]
@zdpdsy 你用的是 vue 的语法吧，你写的例子是基于 `.we` 语法的。

使用 Vue 的话参考下官方文档[《使用 Vue 开发 Weex 页面》](https://weex-project.io/cn/guide/intro/using-vue.html)，从 WeexSDK 0.9.5 开始才支持使用 Vue。引入模块的写法可以参考 [stream 模块的文档](https://weex-project.io/cn/references/modules/stream.html) ，`weex.requireModule('stream')` 不需要加 `@weex-module/`。

**Comment by zdpdsy** [comment]
@Hanks10100 我用这种方式就可以了。weex.require('event') 
![image](https://cloud.githubusercontent.com/assets/7123339/22179159/5e33888c-e086-11e6-8b14-9f66417f2973.png)
但是weex.requireModule('event')就是不行,而且我SDK版本是0.9.5版本的

**Comment by Hanks10100** [comment]
我这里验证了 0.9.5 里是只包含了 `weex.requireModule` 方法，请再次确认一下 weex sdk 版本吧。

用 手机扫这个二维码可以看到 Weex SDK 的版本号： http://dotwe.org/weex/5bfd4b3c774b85cf103d7916474a523b

**Comment by zdpdsy** [comment]
@Hanks10100  扫出来是0.9.5版本,demo工程发你gmail邮箱了，麻烦看一下问题，谢谢

**Comment by Hanks10100** [comment]
你可以在 http://dotwe.org/vue 里写 vue 的例子，测试一下是否能正常工作。这里还有我写的一个使用模块的例子 http://dotwe.org/vue/b8b943c5c5dd66fb61f2d78ca2d9eeae ，可以参考一下。

**Comment by SeongBrave** [comment]
@zdpdsy  您好，你的问题解决了吗？ 我也遇到类似的问题了，使用weex.requireModule('event') 导入自定义的module 始终不行,我的weexsdk是使用的0.9.5.3 ，vue 的语法

**Comment by zdpdsy** [comment]
@SeongBrave 您好，还没有解决

**Comment by Hanks10100** [comment]
0. 先扫码确认一下环境，SDK 版本要在 0.9.5 或以上 http://dotwe.org/weex/8c2fb817f19d9837a4f773e163d9cc45 
0. 再确认一下这个例子能不能工作  http://dotwe.org/vue/b8b943c5c5dd66fb61f2d78ca2d9eeae 
0. 如果还报错，希望能在 http://dotwe.org/vue 上提供一个能复现问题的例子。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
