### ISSUE TITLE
图片渲染不一致的问题

### ISSUE THREAD

**Issue by yuanzx** [alibaba/weex#2356]
```
<div style="width:690;align-items:center;padding:30">
    <img src="{{c.image.url}}" style="width:1000;height:310;" />
</div>
```

在Android上，图片宽度大于容易宽度会截断，类似于cover，但是在ios上，宽度会无视padding，即充满750

**Comment by Jinjiang** [comment]
重现了 http://dotwe.org/weex/25af7e1841d5d34e6ebf124ca0e82d0e
@YorkShen

**Comment by YorkShen** [comment]
* android 不支持`overflow:visible`，只支持`overflow:hidden`，故图片会被裁剪。
* iOS既支持`overflow:visible`，又支持`overflow:hidden`，且默认值是`overflow:visible`，故图片不会被裁剪。

为div添加`overflow:hidden`，可以使iOS和android渲染效果一致。

**Comment by yuanzx** [comment]
@YorkShen  我就是加了overflow hidden保持一致的
