### ISSUE TITLE
[ios] <text :class="className" /> 不工作

### ISSUE THREAD

**Issue by vfasky** [alibaba/weex#2358]
```js
let className = 'n1 n2' // 不工作
let className = 'n1' // 工作
```
`<text>` 使用动态 class 会导致界面所有 `<text>` 不显示
使用 :style 正常

SDK 0.9.5 && vue

**Comment by Jinjiang** [comment]
动态 class 建议写成数组，试一下这种写法：

```vue
<template>
  <div>
    <text :class="classList">Hello World</text>
  </div>
</template>

<style>
  .foo { color: red; }
  .bar { font-size: 64px; }
</style>

<script>
  module.exports = {
    data: { classList: ['foo', 'bar'] }
  }
</script>
```

http://dotwe.org/vue/1dce726c51b1f7dae55fe21dcb524e1f

导致所有 `<text>` 不显示可以在 http://dotwe.org/ 给个重现的例子吗？

**Comment by vfasky** [comment]
换成数组就工作了，谢谢

and 重现地址 http://dotwe.org/vue/d7ca5d880f37d3ea77eeda45dfa2b0a2

**Comment by Jinjiang** [comment]
我通过你提供的例子再次确认了一些，因为 classList 必须是数组，不是数组无法被正常处理所以就报错了。只要把这个地方语法写对就没问题了。
谢谢

**Comment by Jinjiang** [comment]
补充一下，这个地方的健壮性我们会考虑加强，避免因为写错 class 语法导致整个页面不展示的问题
