### ISSUE TITLE
请问下，何时可以完善文档？点击“构建全新应用”，显示：Work in process.

### ISSUE THREAD

**Issue by wenqibo** [alibaba/weex#2360]
如题。

**Comment by wenqibo** [comment]
另外，按照文档中的快速上手构建的应用，npm run serve运行起来后，用手机端的weex app扫码，是空白页面

**Comment by wenqibo** [comment]
看了文档都不知道怎么下手开发，谁有最佳实践吗

**Comment by MrLiHong** [comment]
同问！

**Comment by wenqibo** [comment]
@MrLiHong  握爪。以前没弄过app开发，现在想全新开始。

**Comment by shmy** [comment]
请耐心等待

**Comment by daizheng521** [comment]
现在支持vue之后，感觉东西更乱，没法下手了，阿里的大牛们，能不能弄一套完整的。tabbar 用vue图片久显示不出来，不知道咋搞了。。。。。

**Comment by chinafootballyu** [comment]
@wenqibo 手机和电脑要在同一个网段的。

**Comment by AugHua** [comment]
而且按照指导文档建了一个项目，页面就没渲染

**Comment by Dpuer** [comment]
@wenqibo @AugHua 直接运行npm run serve是只有空白页面，因为对于渲染的是dist目录下生成的js bundle，你需要先执行npm run dev或者npm run build生成js bundle以后才能看到对应渲染的内容

**Comment by DoranYun** [comment]
@wenqibo Hi，首先回答你第一个问题，构建全新应用需要周边工具配套支持，这部分我们还需要一点时间，等工具完成我们会马上发布相关文档。

第二个问题，关于快速上手显示空白页，确认你是否执行了 `npm run serve` 和 `npm run dev` 这两个命令。`npm run serve` 只开启静态服务器，如果你没有编译 js bundle ，打开页面是会报 404 error 的，你可以打开 chrome devtool 查看一下。
而 ` npm run dev` 的作用是开启 watch 服务实时编译 js bundle。
所以，你需要同时运行 `npm run serve` 和 `npm run dev` 。

**Comment by Dpuer** [comment]
@DoranYun 借楼问一下，weex不支持v-html的话，如何渲染富文本维护的模板内容，比如商品图文详情之类

**Comment by wenqibo** [comment]
@DoranYun 好的，谢谢了。问题已经解决，原因是我的Weex Playground是老版本的，可能还不支持vue，重新下载安装后搞定。另外，期待文档，辛苦了！
