### ISSUE TITLE
weex.require is deprecated but some document is not updated

### ISSUE THREAD

**Issue by markzhai** [alibaba/weex#2361]
Such as 
- https://weex-project.io/cn/references/weex-variable.html

**Comment by DoranYun** [comment]
Thanks for your reminder, I'll fix it right away.

**Comment by markzhai** [comment]
@DoranYun and this:

`registerModule` is typed as `registerModules`

- https://weex-project.io/cn/v-0.10/references/specs/js-framework-apis.html
- https://weex-project.io/v-0.10/references/specs/js-framework-apis.html
- https://weex-project.io/cn/references/advanced/extend-jsfm.html

**Comment by DoranYun** [comment]
I am sure these are right. You can register multiple modules with  `registerModules` in JS Framework.  But for iOS or Android, you need use `registerModule` to register module,  only one can be registered at a time.

**Comment by DoranYun** [comment]
Fixed.https://github.com/alibaba/weex/pull/2373
