### ISSUE TITLE
[bug]项目中的example下的a-demo通过weex-toolkit build出的页面没有跳转效果

### ISSUE THREAD

**Issue by LeonDWong** [alibaba/weex#2364]
**复现步骤**： 在项目根目录下使用cli`weex example/component/a-demo.we`打开web页面，渲染出的html为带有`href`属性的div，并不支持链接跳转。
<img width="1191" alt="2017-01-22 10 14 09" src="https://cloud.githubusercontent.com/assets/17465046/22179339/903a36be-e08b-11e6-8930-52e44269b11d.png">

**toolkit版本**：<img width="278" alt="2017-01-19 10 43 11" src="https://cloud.githubusercontent.com/assets/17465046/22179305/79f1bc20-e08a-11e6-8713-c67432cc7e7c.png">

**browser版本**：<img width="350" alt="2017-01-22 10 16 39" src="https://cloud.githubusercontent.com/assets/17465046/22179347/e5141c22-e08b-11e6-9cdd-e64d34875def.png">

**OS版本**：<img width="219" alt="2017-01-22 10 18 35" src="https://cloud.githubusercontent.com/assets/17465046/22179352/2702730e-e08c-11e6-8367-5756d7814c96.png">

**Comment by DoranYun** [comment]
这个问题应该是 weex-toolkit 使用的 weex h5 render 版本较老，没有打入 `<a>` 组件导致的。

@exolution 确认下是否这个问题。

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
