### ISSUE TITLE
vue内如何获得bundleUrl

### ISSUE THREAD

**Issue by tongtongbuxudong** [alibaba/weex#2368]
代码：var bundleUrl = this.$getConfig().bundleUrl;
显示错误：this.$getConfig is not a function
请问vue后缀名下如何获取bundleUrl

**Comment by Hanks10100** [comment]
直接使用 `this.$getConfig` 是可以获取的 http://dotwe.org/vue/5f77d2989ee8a314ea3c8d534d96ff39

目前在手机端可以正常获取，在 web 上暂时还不能获取到。

**Comment by tongtongbuxudong** [comment]
谢谢

**Comment by Hanks10100** [comment]
现在在 web 上也有 `weex.config` 变量和 `this.$getConfig` 了，weex-vue-render@0.1.8
