### ISSUE TITLE
Support constant extension for android and iOS

### ISSUE THREAD

**Issue by markzhai** [alibaba/weex#2369]
#In react-native, we have `getConstants` to expose a map to js: 

```java
  @Override
  public Map<String, Object> getConstants() {
    final Map<String, Object> constants = new HashMap<>();
    constants.put(DURATION_SHORT_KEY, Toast.LENGTH_SHORT);
    constants.put(DURATION_LONG_KEY, Toast.LENGTH_LONG);
    return constants;
  }
```

So that js can access those constants directly without a promise. However in weex, registerModule can only do this with a callback. This is really useful if the common configs are on native side.

For more details, please refer: http://facebook.github.io/react-native/docs/native-modules-android.html

**Comment by Jinjiang** [comment]
The next release of WeexSDK will support return value from a native module method call, also without Promise or callbacks.
Thanks.

**Comment by markzhai** [comment]
@Jinjiang Thank you, looking forward to the next release
