### ISSUE TITLE
iOS上拉刷新Bug(当list的cell不满整屏幕是)

### ISSUE THREAD

**Issue by frankxiongsir** [alibaba/weex#2370]
iOS的SDK中list控件，当cell数量不满整屏幕时，下拉是没有问题的，当上拉时最后一个cell会吸附到屏幕底部，要手动点一下才上弹。测试手机iphone6s，iOS10。
[http://i.niupic.com/images/2017/01/22/AVXL0j.png](url)

**Comment by frankxiongsir** [comment]
上面的图片地址![](https://i.niupic.com/images/2017/01/22/AVXL0j.png

**Comment by acton393** [comment]
hi @frankxiongsir  这个问题已知，正在解决， #1896  这个集中地方讨论，这个issue 暂时先关了
