### ISSUE TITLE
iOS Apis 降级使用文档错误

### ISSUE THREAD

**Issue by markzhai** [alibaba/weex#2372]
https://weex-project.io/cn/references/ios-apis.html

> 降级使用
> Weex 处于发展阶段会增加一些新的特性和功能，但是这些新的特性和功能都必须升级 SDK 才能实现，对于没有升级的应用应该怎么处理呢？可以使用降级功能。
> 
> 所谓降级功能就是 Weex 无法运行的版本或者手机，可以用 Weex h5 来代替。
> 
> Native 端可以通过接口 IWXRenderListener 中的 onException 方法进行处理，如果是主动降级 errCode 是以“|”分割的字符。“|”前面的字符为1表示主动降级，Native 端可以跳转到对应的 H5 页面。或者用其他的方式提示用户当前环境不支持 Weex。

这个是Android的才对吧

**Comment by acton393** [comment]
hi @markzhai , thx 这个地方确实是没有改，会尽快改掉

可以暂时先查看[这里](https://github.com/weexteam/article/issues/126)

**Comment by DoranYun** [comment]
Fixed. https://github.com/alibaba/weex/pull/2383
