### ISSUE TITLE
fireEvent in android & iOS has no corresponding document on JS

### ISSUE THREAD

**Issue by markzhai** [alibaba/weex#2376]
In Android Apis (https://weex-project.io/cn/references/android-apis.html)

> 自定义事件通知
> 
> 多用于某个自定义控件进行事件通知，例如自定义点击事件，响应下拉事件等。
> 
> WXSDKInstance.java
> 
> public void fireEvent(String elementRef,final String type, final Map<String, Object> data,final Map<String, Object> domChanges){  }
> public void fireEvent(String elementRef,final String type, final Map<String, Object> data){
>   fireEvent(elementRef,type,data,null);
> }
> public void fireEvent(String elementRef, String type){
>   fireEvent(ref,type,new HashMap<String, Object>());
> }

However, there is no corresponding document on how to deal with event on JS side.

**Comment by Hanks10100** [comment]
This API is used for the communication between js framework and native. The receiver is js framework, not js bundle (or DSL). If you want to fire an event in js, just use the API offered by specific front-end frameworks, such as `$emit` in Vue.

**Comment by markzhai** [comment]
But the document shows nothing about it, I think neither frontend developer nor native developer know how to deal with each side, at least the document should give some clue (like if using Vue.js, use @event）

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
