### ISSUE TITLE
<Text>标签希望支持 text-indent 和 内嵌span

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#2378]
某些应用场景下，文段需要首行缩进。
以及部分文本需要加粗或者彩色显示，用于强调。

**Comment by karynsong** [comment]
同求，非常有需求。而且我们有动态改变字体的需求，自己做标签，源码上的很多方法都没有暴露。进退两难
由于没有继承，很难实现字体缩放，能不能有一个地方可以统一给字体 size * 缩放

**Comment by karynsong** [comment]
http://dotwe.org/vue/3f5d6bd191eef0c18939761323b4eba7

**Comment by Hanks10100** [comment]
参考 #1740
