### ISSUE TITLE
 indicator組件 设置颜色无效，代码如下

### ISSUE THREAD

**Issue by daizheng521** [alibaba/weex#2379]
如官网的例子：
https://weex-project.io/examples/indicator.html

**Comment by SimonTal** [comment]
item-color:rgba(255,255,255,0.4);
item-selectedColor:#ffffff;

使用rgb 或者 16进制是可以的

**Comment by daizheng521** [comment]
@SimonTal  你好，我按照这样的格式，也不行哦。麻烦看看具体什么问题？

**Comment by DoranYun** [comment]
@daizheng521 vue 版本的 h5 render 暂时不支持 `item-color`、`item-selectedColor` 等自定义样式，只有 native 支持

**Comment by daizheng521** [comment]
@DoranYun  谢谢，只能暂时这样了，
