### ISSUE TITLE
希望保留之前的文档

### ISSUE THREAD

**Issue by lforme** [alibaba/weex#2384]
现在和文档对应的新的方式会给新的开发者带来不少困扰:
由于看过之前的文档, 一直都是: var stream = require('@weex-module/stream'); 这么写的, 现在在新的文档的指导下更新成这样:   var stream = weex.requireModule('stream')
导致的界面无法正常显示, 估计是我开发环境没有升级, 可能对长期从事web开发的同学不是什么大问题, 但是对于刚接触weex的我, 这个问题, 找了一上午...

**Comment by DoranYun** [comment]
Hi，旧文档一直有保留，进入方式：

左侧目录最后一项就是历史文档。或者 FAQ 首条回答。

![image](https://cloud.githubusercontent.com/assets/16359169/22194417/4bf0310a-e17d-11e6-8787-c4d9faa3e2e9.png)

这里再链一下：


- [Guide](https://weex-project.io/cn/v-0.10/guide/index.html)
- [手册](https://weex-project.io/cn/v-0.10/references/index.html)
- [高阶知识](https://weex-project.io/cn/v-0.10/advanced/index.html)
- [工具](https://weex-project.io/cn/v-0.10/tools/index.html)

**Comment by lforme** [comment]
谢谢
