### ISSUE TITLE
weex 和 realm-android 冲突

### ISSUE THREAD

**Issue by sdaduanbilei** [alibaba/weex#2385]
weex 按照配置app 的build.gradle
` 
ndk{ 
            abiFilters "x86"
            abiFilters "armeabi"
        }
`

之后 realm-android 编译

`java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: com.getkeepsafe.relinker.MissingLibraryException: lib/armeabi/librealm-jni.so`

这个要怎么过滤？

**Comment by markzhai** [comment]
因为 realm 不支持 armeabi，改成armeabi-v8就行了

**Comment by sdaduanbilei** [comment]
`ndk{ // weex 兼容64bit
            abiFilters "x86"
            abiFilters "armeabi-v7a"
            abiFilters "armeabi-v8a"
        }`
单独设置一个 我也测试过。
我已经改了  realm 没有问题，但是 weex 报错了  
`[WXBridgeManager] invokeCreateInstance: framework.js uninitialized.`

**Comment by myeveryheart** [comment]
@markzhai 改成armeabi-v8a 或者 armeabi-v7a 之后，realm是没问题，但weex就挂了。归根结底还是weex的so太少了。

**Comment by JuniperPhoton** [comment]
Approve. Weex should support armeabi-v7a. I try compile weex sdk by moving armeabi so file to armeabi-v7a and it works on my device so far. Still hoping the weex team can fix this.

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
