### ISSUE TITLE
选择we或者vue?

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#2387]
知道最近weex支持vue语法， 那我们准备入坑的到底选用用那种语法， 未来是不是要抛弃we语法？渐渐变为vue语法？尽管两者很类似， 还有react，谢谢。

**Comment by Hanks10100** [comment]
`.we` 语法的设计和 Vue 1.0 比较相似，现在 Vue 推出了 2.0 ，我们也有官方合作，从 1.0 过渡到 2.0 也是理所当然，以后会逐步推进大家使用 [Vue 2.0](https://vuejs.org/) 或者 [Rax](http://rax.taobaofed.org/) 的语法。从 `.we` 到 `.vue` 的过渡可以参考这篇文档：[《将原有 Weex 项目改造成 Vue 版本》](https://weex-project.io/cn/references/migration/migration-from-weex.html)

> 另外建议在 [gitter](https://gitter.im/weexteam/cn) 中讨论这类问题。
