### ISSUE TITLE
[ios] vue模式下， 自定义事件的对象格式不对

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#2394]
根据文档：https://weex-project.io/cn/v-0.10/guide/syntax/comm.html
如果这么发送事件：
```javascript
this.$parent.$emit('notify', {a:1});
```
收到的应该是：
```javascript
this.$on('notify', function(e){
    // e = {
    //   type:'string',
    //   target:Element,
    //   timestamp:number,
    //   detail:{a:1},
    // }
});
```
但实际收到的是
```javascript
this.$on('notify', function(e){
    // e = { a: 1 }
});
```

iOS sdk为 0.9.5.1

**Comment by Jinjiang** [comment]
Sorry，这部分文档是反向整理的，应该以实际效果为准。我们重新核对一下文档吧
谢谢

**Comment by Jinjiang** [comment]
我又重新看了一下，文档里的描述是对的，这份旧文档是针对之前老版本的 `*.we` 匹配的，Vue 模式 (Vue 2.0) 的行为以 Vue 的官网文档为准 https://vuejs.org/v2/guide/components.html#Custom-Events
谢谢
