### ISSUE TITLE
-[WXBridgeManager _runLoopThread] crash

### ISSUE THREAD

**Issue by willice9527** [alibaba/weex#2397]
hi,各位
问题描述：我们这边iOS应用接入weex大约有两个月左右时间。接入以来，我们陆续收到了一些+[WXSDKEngine initSDKEnviroment]过程中产生的crash。大约累计产生了7000余次，对稳定性还是产生了一些影响。查了crash stacktrace，发现崩溃发生在-[WXBridgeManager _runLoopThread]。具体的stacktrace，我附了两个典型的作为附件，如果你们需要查看更多，也可以联系我这边(jinlin.liu@ele.me)。目前我们在iOS9/10两个系统环境下启用weex，崩溃的发生也是分布在两个系统上 。整体上来说，这个bug的崩溃率比较低，难以人为复现。相似的崩溃在-[WXComponentManager _runLoopThread]也有发生，stacktrace也非常类似。这个累计约1500余次。
另外还有一些使用上的疑问，想要向这边咨询一下：
1.WXBridgeManager WXComponentManager都使用了常驻线程的做法，相较于dispatch_queue，当时如何取舍的？出于何种考虑使用常驻thread的方式 ？
2.thread的入口方法没有使用autoreleasepool?可能是我们理解粗浅，不过可能会有一些leak？
3.出于不影响主业务流程的考虑，我们将[WXSDKEngine initSDKEnviroment]时机放的比较靠后。在第一次进入weex页面的控制器的viewdidload方法中调用，随后才进行WXSDKInstance 的renderWithURL。上面的问题与这个较迟的初始化时机是否有关联。
[WXBridgeManager_crash_stacktrace01.txt](https://github.com/alibaba/weex/files/725763/WXBridgeManager_crash_stacktrace01.txt)
[WXBridgeManager_crash_stacktrace02.txt](https://github.com/alibaba/weex/files/725764/WXBridgeManager_crash_stacktrace02.txt)
[WXComponentManager_crash_stacktrace01.txt](https://github.com/alibaba/weex/files/725765/WXComponentManager_crash_stacktrace01.txt)
[WXComponentManager_crash_stacktrace02.txt](https://github.com/alibaba/weex/files/725766/WXComponentManager_crash_stacktrace02.txt)

期待回复

**Comment by CodeLife2012** [comment]
观察了下貌似是`CFRunLoopSourceSignal`时source里面的lock为空

**Comment by cxfeng1** [comment]
@willice9527 

1. 采用创建NSThread并绑定runloop的方式，主要用于Native和JS的频发通信以及component线程16ms一次的layout计算，Weex的整个渲染机制基于三线程的架构， 采用NSThread可以对线程有更直接的控制。
2. 这个是好建议， 已提PR #2401
3. 目前也有接入的App是在controller的viewdidload中进行初始化的， 没有发现类似的crash， 是否能提供和 [WXSDKEngine initSDKEnviroment] 同时触发的其他Weex相关操作， 怀疑是runloop内部死锁了。 另外也可以尝试一下将初始化方法往前移， 初始化方法在主线程的耗时不高， 大部分App都是放到启动的时候进行初始化。

如有任何问题， 欢迎直接回复issue。

**Comment by willice9527** [comment]
@cxfeng1   [WXSDKEngine initSDKEnviroment]的同时应该是没有其它weex相关操作的，在init完成后，才进行当前viewcontroller所持有的WXSDKInstance的创建及调用renderWithURL:方法

**Comment by acton393** [comment]
hi @willice9527  可以尝试一下 `0.9.5.2` [这里](https://cocoapods.org/pods/WeexSDK) 版本，这个版本是要发布的 0.10 的版本feature，有修复上面 @cxfeng1  提到的一些问题， 如果还有其他问题，可以继续在下面回复， thx~~~

**Comment by willice9527** [comment]
我们计划在这个版本升级至0.10.0 到时候再看看是否还有这个问题。
@acton393

**Comment by acton393** [comment]
hi @willice9527  ok， issue 暂时先关闭了， 如果后续有问题，可以再打开回复

**Comment by ChenMengqi** [comment]
0.18.0 SDK上依然存在这两个crash
