### ISSUE TITLE
vue 使用对象渲染 class 不生效，样式无法继承真的是好痛苦，toolkit 报错，ios 方法没有暴露

### ISSUE THREAD

**Issue by karynsong** [alibaba/weex#2403]
vue 官方写法 class 渲染不生效
:class="{'item-on' :  true}" 
需要写成下面这种才生效，是因为必须要传入一个空的 class 么？
[true ? 'item-on' : '']

样式无法继承，使得 active 状态的 class 可能会加非常多的才能使一个复杂的 list 显示 active 的状态。比如：list 背景和内部的字体都有 active 的状态，都需要些一个 active 的样式

现在 toolkit 还是有问题，weex is undefined，无法调试，找问题都靠猜

很多原生标签方法没有暴露，没法调用到，很难做扩展。比如 iOS 的：#import "WXComponent_internal.h"

**Comment by DoranYun** [comment]
动态 class 建议写成数组。

@Hanks10100 ，确认一下。

**Comment by karynsong** [comment]
麻烦官方看是不是优先解决，更新 vue 的写法，升级最新的 SDK() 和 最新的 toolkit(0.2.74) 之后，toolkit 报错 weex is undefined 的问题，无法调试真的很难开发。

输入框调用键盘的时候能不能自适应一下输入框的高度，让输入框放到视野中。这个体验挺重要的

**Comment by Hanks10100** [comment]
目前在 weex 中，class list 只能是数组，参考 #2303 。

样式继承有利有弊，不支持样式继承可以简化样式的复杂度，提高样式的计算效率，只不过在写法上有些繁琐（其实支持继承的样式属性也不多，参考 #1735 ）。

weex-toolkit 已经修复了 weex is undefined 的问题， 升级版本即可，目前已经有 1.x-alpha 版本，可以通过 `weex --version` 查看。最近工具可能会频繁更新，建议安装最新版。
