### ISSUE TITLE
weex debug启动，扫码，app list不显示设备，注：安卓有这问题，苹果正常。

### ISSUE THREAD

**Issue by chenkezhao** [alibaba/weex#2405]
- playground版本：weex_playgroud_10006024.apk

- weex版本：
C:\Users\aaron>weex -v
v1.0.1-beta.5
weex-devtool : v0.2.76

- 安卓--------------------->>>>
扫码,app list中不会出现设备。
设备：荣耀8、红米note 4、红米1s
注：没有报错误，app list列表就是不显示我的设备

- 苹果--------------------->>>>
设备：ipad pro
扫码，app list正常显示设备。

**Comment by hodgevk** [comment]
只有0.9.5版本有这个问题，我的小米5扫描后直接崩溃。

**Comment by chenkezhao** [comment]
是apk版本问题。自己build个版本吧。
https://github.com/alibaba/weex

**Comment by dufangyu1990** [comment]
@chenkezhao  你好，你说重新build个版本，是说弄个debug版本的apk吗？我现在这里发现release包无法使用weex 的devtool,相反debug包可以，你也是这个问题吗？
