### ISSUE TITLE
页面修改不实时更新，报如下错误

### ISSUE THREAD

**Issue by jl6278462** [alibaba/weex#2406]
D:\workspace\weex\src>weex hello.vue
info weex JS bundle saved at C:\Users\qian\.weex_tmp
info Wed Jan 25 2017 14:46:21 GMT+0800 (中国标准时间)WebSocket  is listening on port 8082
info Wed Jan 25 2017 14:46:21 GMT+0800 (中国标准时间)http  is listening on port 8081
file refresh!
file refresh!
Error: not opened
    at WebSocket.send (C:\Users\qian\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\.1.1.1@ws\lib\WebSocket.js:219:16)
    at C:\Users\qian\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\.1.2.6@weex-previewer\build\index.js:270:29
(node:7080) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: not opened
(node:7080) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Jinjiang** [comment]
@exolution @jackpu 有劳关注一下
谢谢

**Comment by JackPu** [comment]
@jl6278462  嗯，收到，你能提供下weex-toolkit 的版本号么

**Comment by jl6278462** [comment]
@JackPu   v1.0.1-beta.5 我查到是这个版本，麻烦看下

**Comment by JackPu** [comment]
@jl6278462  Hello，最新版本的weex-toolkit 已经修复了热刷新的问题。可以先卸载再重新安装就好。

``` bash
npm uninstall weex-toolkit -g
npm install weex-toolkit -g
```

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
