### ISSUE TITLE
border-[bottom|left|right|top]-[style|color|width] 在ios上失效

### ISSUE THREAD

**Issue by hwysjj** [alibaba/weex#2408]
border-[bottom|left|right|top]-[style|color|width]的样式不能在手机上work, 可以尽快帮修复下吗？或者有没有workaround?

**Comment by Hanks10100** [comment]
我写了个例子是可以正常使用的 http://dotwe.org/vue/324ac4b172fc6b869a73edc12bfb8023 。

能否在提供一些详细的信息，例如 .we 还是 .vue ，sdk 版本等。扫下边这个二维码可以获取 Weex 执行环境的信息：

![weex-env](https://cloud.githubusercontent.com/assets/8401776/22457643/8c3e8cb4-e7d3-11e6-9624-5174b55d2713.png)

**Comment by lanmerry** [comment]
@hwysjj border相关的属性尽量作用在div上，text、image等标签上使用是会出现无效的情况

**Comment by hwysjj** [comment]
@laijiandong 我是加在了input上面，现在在外面套了一层div解决了。谢谢！
