### ISSUE TITLE
如何直接构建APP，以及不能使用v-html的疑问

### ISSUE THREAD

**Issue by Dpuer** [alibaba/weex#2409]
之前用的是ionic开发Hybrid APP，在看了多方介绍之后准备入坑WEEX，看了2天的官方文档后有2个问题想问一下。

1、如何直接构建APP，官方文档中构建新应用的地方暂时还是一片空白，集成到现有应用要求掌握一定原生开发能力，请问WEEX是否能提供类似ionic的ionic build android之类的命令行生成应用的功能，或者其他不需要原生开发能力的解决方案
2、文档介绍说WEEX不支持v-html标签，如果我有一个需求，类似于一个传统的电商平台，需要开放给商户入驻并提供富文本编辑商品图文详情的功能，既然WEEX不支持v-html，我该如何实现该需求

**Comment by hwysjj** [comment]
1. weexpack

**Comment by Hanks10100** [comment]
直接构建 app 可以使用 [weexpack](https://github.com/weexteam/weex-pack) ，支持 weexpack build android 这种命令。

v-html 是用于直接插入 html 字符串的，这个操作具有一定危险性，Weex 渲染生成的是原生组件，不支持 html 标签，参考[《Weex 和 Web 平台的差异》](https://weex-project.io/cn/references/platform-difference.html) 。

对于富文本编辑功能，如果想沿用 web 上的编辑器插件，可以将可定制的区域使用 `<web>`(webview) 组件渲染。另外也可以自行实现一个富文本编译器，能够直接生成 weex 平台支持的组件。

**Comment by Dpuer** [comment]
@Hanks10100 由于春节长假抱歉这么久才给与回复，关于问题1，我表示已经没有问题；关于问题2，如果如你所说使用web组件来渲染是没有什么问题，但是这是否意味着每一个商品详情的内容部分都需要有一个对应的url地址进行访问才可以？当然我不是说这样做会有什么问题，只是感觉上有些别扭。另外你所说的自行失效一个可以直接生产weex平台支持组件的富文本是需要结合原生来实现吗？是否可以提供相关的例子作为参考

**Comment by Hanks10100** [comment]
用 web 组件的话，每个详情内容的部分都要有个链接地址。如果想用原生实现，也应该将可自定义的内容区域单独视为一个 weex instance ，编辑器生成 Weex 支持的 js bundle ，需要写原生代码，还是有些难度的。

另外 Weex 有富文本组件（参考 #835 #2367 ），但是不是富文本组件**编辑器**，功能和你描述的不同。

**Comment by Dpuer** [comment]
感谢解答，我会关闭这个问题
