### ISSUE TITLE
iOS 0.95 SDK  组件 >特性 缺少一步由连字符式转换为驼峰式

### ISSUE THREAD

**Issue by wj2061** [alibaba/weex#2411]
使用 连字符式命名的 特性如： `<slider>auto-play`  及 `<scroller>show-scrollbar`，
在js 的回调：`- (void)registerCallAddElement:(WXJSCallAddElement)callAddElement
`中，仍为连字符式，如一个`scroller`初始化时的`componentData`：

> {
    attr =     {
        "show-scrollbar" = false;
    };
    ref = 584;
    style =     {
        borderColor = "rgb(162,217,192)";
        borderStyle = solid;
        borderWidth = 3;
        height = 700;
        marginLeft = 25;
        width = 700;
    };
    type = scroller;
}    
    
而在Componet初始化时仍按照驼峰式来检查属性，如：
`        _showScrollBar = attributes[@"showScrollbar"] ? [WXConvert BOOL:attributes[@"showScrollbar"]] : YES;`    
    
导致这些使用连字符式命名的特性无法使用。   
最好能在js回调之前使用js转换一次。

**Comment by Hanks10100** [comment]
嗯，是个已知问题，参考 https://github.com/weexteam/weex-vue-framework/issues/21 。可能会通过修改编译工具来修复，原生代码不用修改。
