### ISSUE TITLE
textarea的高度不能自动适应字体大小

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#2413]
textarea的高度不能随字体大小调整， 设置大字体时，不能显示完整指定行数的文字

**Comment by jasonhe88** [comment]
不能继承也不能扩展WXTextAreaComponent, 最后，
我把自带的WXTextAreaComponent拷贝出来，改写成一个新的component，
而且可以自己加上很多功能了，问题解决

**Comment by acton393** [comment]
hi @jasonhe88  如果可以的话，提一个pr 改进一下现有的一些问题， 让大家都可以用起来~
