### ISSUE TITLE
请问weex能调用本地c/c++的库吗？

### ISSUE THREAD

**Issue by ytmoye** [alibaba/weex#2420]
我们的app用了一些本地的c/c++的库，之前是用原生代码调用的，请问如果使用了weex以后，能调用吗？

**Comment by acton393** [comment]
hi @ytmoye 可以尝试通过开发自定义的module 、handler 或者component ， 在这些自定义的native组件中调用c/c++库

**Comment by ytmoye** [comment]
thanks!
