### ISSUE TITLE
[html5] weex-vue-render 需要改进的地方，大家在这里集中反馈及讨论吧。

### ISSUE THREAD

**Issue by dongnaebi** [alibaba/weex#2421]
除了@Hanks10100 已记录的 [TODO](https://github.com/Hanks10100/weex/projects/7)

使用中我还发现以下问题（v0.2.0）：

 1. slider组件change回调没有返回index。
 2. slider子组件indicator没有支持flexbox
 3. scroller横向滚动撑不开，建议`.weex-scroller-horizontal .weex-scroller-inner{...position:absolute;top:0;left:0}`
 4. 建议scroller、list组件加上样式`-webkit-overflow-scrolling:touch;`
 5. scroller竖向滚动长按并向上滑时weex-scroller-inner的translate3d变化导致滚动不流畅。并且很快向下滚，再回滚到顶部时translate3d没有来得及变化，导致顶部一部分内容不显示。建议touchmove时判断scrollTop为0或到底部时再改变translate3d
 6. fresh组件`display="hide"`不隐藏，重现：文档里的例子[https://weex-project.io/examples/refresh.html](https://weex-project.io/examples/refresh.html)
 7. `weex.config`获取的`deviceWidth`和`deviceHeight`会偶发错误，多发生在页面切换时
 8. example中的[marquee.vue](https://github.com/Hanks10100/weex/blob/html5-feature-vue-render/examples/vue/include/marquee.vue)运行报错，原因是`this.$refs.anim.ref`，这个.ref是写错了还是工具转换错的？
 9. slider组件的循环项click事件不执行，点击时执行了左滑事件。
 10. refresh组件下拉刷新时，没有触发refresh事件。
 11. modal字体过小
 12. 建议去掉蜜汁样式`.weex-list-inner, .weex-scroller-inner{background-color: #FFFFFF;}`
 13. input组件输入时会报警告

**Comment by Hanks10100** [comment]
Good job!

**Comment by Hanks10100** [comment]
refs #2399 #2414

**Comment by huixisheng** [comment]
`loading组件`上拉加载时，没有触发`loading`事件   
![wechatimg212](https://cloud.githubusercontent.com/assets/1518967/22722444/ff378440-edf1-11e6-8a96-5fa048a302ca.jpeg)
示例:http://dotwe.org/vue/bd5a458c6aff3e7fa9173a0e5378891d

**Comment by huixisheng** [comment]
html5:stream 使用 jsonp 报`ReferenceError: Can't find variable: global`  demo: http://dotwe.org/vue/74dfe8a47895e4581963a9b6b2e0a46e

week版本:
```
   v1.0.1-beta.5
 - weex-builder : v0.1.16
```

**Comment by xl602** [comment]
9.slider组件的循环项click事件不执行，点击时执行了左滑事件。

这个问题有修复吗？

**Comment by dongnaebi** [comment]
@xl602 没有，web端是干儿子

**Comment by MrRaindrop** [comment]
@huixisheng 确实有问题，global 没有指向 window. https://github.com/alibaba/weex/pull/2657 这个 pr 修复了此问题。后续等重要 bug 修完会发布新的 weex-vue-render npm 包。

**Comment by fromIRIS** [comment]
![image](https://cloud.githubusercontent.com/assets/8492963/23114507/657e607a-f77a-11e6-8fab-a6323b5e459e.png)
H5端的loading组件配合list在手机上滑动会抖动，而且loading事件不会触发

**Comment by MrRaindrop** [comment]
@fromIRIS list 的修复在最新的 html5-feature-0.10 分支，可以 checkout build 看一下效果，目前 loading 组件还没有修复.

**Comment by stardew516** [comment]
weex-vue-render stream get获取数据的时候   参数用body拼接的，如果不传body，url默认会拼上undefined
2937行这个代码：url += (config.url.indexOf('?') <= -1 ? '?' : '&') + body + hash;
但是body传数据时，weex-playground一直报错“ Runtime.js:222 [Native Error] Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}”

**Comment by stoneqq11** [comment]
使用weex-vue-render后，存在循环引用的vue组件丢失定义在<style></style>标签里面的样式。例如
TreeList    beforeCreate() {this.$option.components.TreeItem = TreeItem}
TreeItem   beforeCreate() {this.$option.components.TreeList = TreeList}
在使用weex-vue-render后，TreeList/TreeItem以及其父组件的样式丢失了。

**Comment by stoneqq11** [comment]
@dongnaebi 帮忙看看这个问题吧，谢谢！

**Comment by stoneqq11** [comment]
<style scoped></style>里面添加了scoped属性才丢失

**Comment by dingly** [comment]
关于scroller 中loading 的问题求解：
   1： loading display 默认hide 首次加载数据之后， display还是变为show
   2： 下拉刷新 触发一次loading ， 添加滚动条数， display还是保持show，  此时在H5端正常运行， 但是在android上出现一个问题 loading一直悬浮在屏幕上， 并没有在滚动内容的底部

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
