### ISSUE TITLE
ios 上weexplayground 扫码崩溃的问题

### ISSUE THREAD

**Issue by monyee** [alibaba/weex#2422]
系统版本 10.2.1

扫码要崩溃，要不就白屏

**Comment by xiaohuapunk** [comment]
升级weex-devtool然后在试试看

**Comment by kfeagle** [comment]
https://github.com/alibaba/weex/pull/2436   改下podfile 更新试试

**Comment by monyee** [comment]
@xiaohuapunk   weex-devtool 和 weex-playground 都已经是最新版本

**Comment by monyee** [comment]
@kfeagle playground是从appstore中下载的，怎样修改podfile呢，不是很明白 能详细说下吗

**Comment by acton393** [comment]
@monyee  可以给一些具体的复现路径和信息么~~，appStore 包 扫什么样内容的码crash  thx ~

**Comment by monyee** [comment]
Hello @acton393 之前扫描0.5版本出现过crash，现在改成weex的最新0.9是白屏状态, weex-toolkit初始化的demo(默认foo.vue)的 项目就有这个问题， appStore中有好几个人反馈过这个问题  ：）

**Comment by acton393** [comment]
hi @monyee  猜测应该是相机权限的问题，在 设置里面找到weex playground app 然后允许它的相机权限， 或者卸载掉重新安装，应该会有相机权限请求提示， 允许就可以

**Comment by monyee** [comment]
Hi @acton393 相机权限给的，尝试过卸载安装过多次无效。

**Comment by wslyy99** [comment]
@acton393 确实有这个问题，我是bate版的.vue的代码，用了2台IOS手机扫码都是白屏，没有任何反应，Android扫码就没事，难道非要让我改成.we的代码。求解决

**Comment by acton393** [comment]
hi @monyee  @wslyy99  我看了appStore 的评论，有尝试过提到的几个版本的机器，没有发现这个问题，你们扫码固定crash或者白屏的内容可以贴下不~

**Comment by CoderSunnyLau** [comment]
@acton393 我也遇到了同樣的問題，.vue文件在iOS系統上無法正常顯示，而.we文件可以。
我的版本是：
_v1.0.1-beta.5
weex-builder : v0.1.18
weex-devtool : v0.2.76_
iPhone手機用在App Store裡下載的最新版playground掃碼，頁面一片空白，我的系統是iOS 9.3.2；
但是，Android手機用最新版的playground掃碼，頁面可以正常顯示。

**Comment by acton393** [comment]
hi @CoderSunnyLau  支持Vue版本的 playground 还没有发布到appStore， 可以编译安装到iOS 设备，最近会发布

**Comment by wslyy99** [comment]
v1.0.1-beta.5 这个 tookit有问题，用npm install -g weex-toolkit@beta

然后去git下载最新playground自己编译在扫码



在 2017-02-15 11:07:14，"Sunny Lau" <notifications@github.com> 写道：


@acton393 我也遇到了同樣的問題，.vue文件在iOS系統上無法正常顯示，而.we文件可以。
我的版本是：
v1.0.1-beta.5
weex-builder : v0.1.18
weex-devtool : v0.2.76
iPhone手機用在App Store裡下載的最新版playground掃碼，頁面一片空白，我的系統是iOS 9.3.2；
但是，Android手機用最新版的playground掃碼，頁面可以正常顯示。

**Comment by CoderSunnyLau** [comment]
@acton393 好的，謝謝你，期待iOS的新版本發佈~

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
