### ISSUE TITLE
weex界面跳转到weex界面，有默认导航栏，怎么自定义或者去掉

### ISSUE THREAD

**Issue by 13754327232** [alibaba/weex#2428]
weex界面跳转到weex界面，有默认导航栏，怎么自定义或者去掉

**Comment by HJ-StevenSun** [comment]
你是在iOS 端吗，如果是的话你可以尝试一下在界面出现之前在生命周期里将它hide 看能成功吗？ good luck

**Comment by 13754327232** [comment]
不，是android端

**Comment by 13754327232** [comment]
不，是android端

**Comment by 1903514970** [comment]
@13754327232 WXNavigatorModule 有一个setNavBarHidden方法，用这个可以控制显示，隐藏。

**Comment by Neeeo** [comment]
在 component 的属性里设置 `data-role="none"`
类似这样：
```html
<div  data-role="none"></div>
````

**Comment by 13754327232** [comment]
@1903514970 setNavBarHidden方法在源码中获取到的((Activity)mWXSDKInstance.getContext()).getActionBar()为null，就无法继续判断是否隐藏还是显示了

**Comment by 13754327232** [comment]
@Neeeo 你所说的组件是指导航栏组件么，我那没写导航栏组件，就一push进去，它的导航栏就出现了

**Comment by Neeeo** [comment]
@13754327232 你要写自己的导航栏的话，就在自己导航栏加上这个

**Comment by analcy** [comment]
android的是在platform/android/app/main/src/AndroidMainfest.xml文件下android:theme="@style/AppTheme"改成android:theme="@style/AppTheme.NoActionBar"

**Comment by YNameUndefined** [comment]
you can try it
this.$navigator.setNavigationInfo({
                    title: '',
                    navShow: false,//导航栏显示与否
                    statusBarStyle: 'Default'
                },
                () => {}
            );

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
