### ISSUE TITLE
BasicListComponent.java 出现 NullPointerException

### ISSUE THREAD

**Issue by or0fun** [alibaba/weex#2429]
在onBeforeScroll里 bounceRecyclerView为null

错误栈信息如下：

java.lang.NullPointerException
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at com.taobao.weex.ui.component.list.BasicListComponent.onBeforeScroll(BasicListComponent.java:650)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at com.taobao.weex.ui.view.listview.adapter.WXRecyclerViewOnScrollListener.onScrolled(WXRecyclerViewOnScrollListener.java:268)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4250)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3348)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3080)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.View.layout(View.java:14852)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:4642)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1990)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1747)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5713)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:544)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:733)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:136)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5120)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:515)
02-05 10:32:42.418 29335 29335 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run

**Comment by sospartan** [comment]
请问你使用的是哪个版本？

**Comment by or0fun** [comment]
0.9.5

**Comment by sospartan** [comment]
在最新的开发分支上已经修复了 https://github.com/alibaba/weex/blob/0.11-dev/android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java#L605  谢谢反馈。
