### ISSUE TITLE
[*] Can i use $renderThen to call my function on next render only once?

### ISSUE THREAD

**Issue by zhoukekestar** [alibaba/weex#2435]
Can i use `$renderThen` to call  my function on the next render only once?

Will this function be removed in the future?

I have this code:
```html
<template>
  <div>
    <input id='input' name='name' value='{{value}}'/>
  </div>
</template>

<script>
  module.exports = {
    data: {
      value: 'value'
    },
    ready: function() {
      var input = this.$el('input')
      console.log('ready:' + input.attr.value) // ready:value
      
      this.value = 'value2'
      console.log('change:' + input.attr.value) // change:value
      
      setTimeout((function() {
        console.log('timeout:' + input.attr.value) // timeout:value2
      }).bind(this), 1000)

      // var input = this.$el('input')
      // console.log('ready:' + input.attr.value)
      // input.attr.value = 'value2'
      // console.log('change:' + input.attr.value)
      //
      // setTimeout((function() {
      //   console.log('timeout:' + input.attr.value)
      // }).bind(this), 1000)


      // var input = this.$el('input')
      // console.log('ready:' + input.attr.value)
      // this.value = 'value2'
      // console.log('change:' + input.attr.value)
      // 
      // this.$renderThen(function() {
      //   console.log('renderThen:' + input.attr.value)
      // })
    }
  }
</script>

```
What i expect the output is `value2` in the second `console.log` . 

I know weex will render asynchronously after changing data. 

So, in the second block, i just change the `input.attr.value` directly, i got what i wanted. 

Finally, in the third block,  i got a function named `$renderThen` on `this` object which is not displayed on document. So, i just confused...

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
