### ISSUE TITLE
weex.config 为何app下存在env 但是web下不存在

### ISSUE THREAD

**Issue by Roxyhuang** [alibaba/weex#2437]
根据https://weex-project.io/cn/references/weex-variable.html

尝试获取platform,但是发现web端与移动端不一致

web端：weex.config.platform
移动端： weex.config.env.platform

劳烦解答

**Comment by vfasky** [comment]
同被坑， 最后发现 `WXEnvironment` 这个变量，三端结构是一致的

**Comment by alex-zhang** [comment]
@vfasky  WXEnvironment 这个变量怎么来的

**Comment by vfasky** [comment]
@alex-zhang 看源码。。。

**Comment by markzhai** [comment]
@MrRaindrop 有没有修复的排期

**Comment by Hanks10100** [comment]
fixed in weex-vue-render@0.2.0
