### ISSUE TITLE
希望可以把容器 WXEmbedComponent src属性增加和image的src一样的转换机制。

### ISSUE THREAD

**Issue by xoxhk** [alibaba/weex#2440]
- (instancetype)initWithRef:(NSString *)ref type:(NSString *)type styles:(NSDictionary *)styles attributes:(NSDictionary *)attributes events:(NSArray *)events weexInstance:(WXSDKInstance *)weexInstance
{
    if (self = [super initWithRef:ref type:type styles:styles attributes:attributes events:events weexInstance:weexInstance]) {
        
        _createFinished = NO;
        _renderFinished = NO;
        
        NSMutableString * newURL = [attributes[@"src"] mutableCopy];
        WX_REWRITE_URL(attributes[@"src"], WXResourceTypeLink, self.weexInstance, &newURL)
        
        _sourceURL = [NSURL URLWithString:newURL];
        _visible =  [WXConvert WXVisibility:styles[@"visibility"]];
        
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(observeInstanceState:) name:WX_INSTANCE_NOTIFICATION_UPDATE_STATE object:nil];
    }
    
    return self;
}

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
