### ISSUE TITLE
weex发展好慢啊，到现在连一个weex与后端框架express结合的demo都没有

### ISSUE THREAD

**Issue by SteveCruise** [alibaba/weex#2443]
不跟一个后端框架结合，让我们怎么用啊，光有weex怎么搭有功能的网站

**Comment by dongfanghu** [comment]
你确定你懂weex

**Comment by dongfanghu** [comment]
你确定你懂weex？

**Comment by hodgevk** [comment]
你确定你懂weex?

**Comment by HomHomLin** [comment]
A framework for building Mobile cross-platform UI

**Comment by AlphaDu** [comment]
我可能学了假的weex

**Comment by dongnaebi** [comment]
我可能用了假的weex

**Comment by daizheng521** [comment]
不过说实话，确实坑挺多，很多东西都不完善，想在公司推weex，都不敢推啊。

**Comment by daizheng521** [comment]
阿里大牛们，雄起啊

**Comment by HJ-StevenSun** [comment]
阿里大牛们，雄起啊

**Comment by bobsam813** [comment]
我可能是学了假的express

**Comment by SteveCruise** [comment]
楼上的那些人，看上去个个大神，一句有营养的都没有

**Comment by sopaco** [comment]
题主是学了真·weex的才提出如此问题，就是和后端无关的，纯前端渲染方案

**Comment by SteveCruise** [comment]
@dongfanghu 你流弊，请问用weex怎么路由？

**Comment by SteveCruise** [comment]
@sopaco 但是怎么和后端框架结合啊，别的框架都不用光用weex就搭了网站？

**Comment by jiyinyiyong** [comment]
楼主问的真是外行... Weex 是用在界面前端的, 具体说浏览器端, Android 和 iOS, 用来写客户端的界面, 其实就是个 JavaScript 运行加上一个 DOM 抽象, 最多加其他一些 API. 现在即便普通前端单页面应用也是可以跟后端解耦, 做前后端分离的.

而后端结合的问题看下 restful API 相关的内容.

**Comment by dongfanghu** [comment]
@SteveCruise vue-router 是为了解决什么的? weex是为什么解决什么的?搭网站?多看 @jiyinyiyong 的答案在看看API和教程别一上来就说什么什么不行

**Comment by SteveCruise** [comment]
@jiyinyiyong 有个demo就好了，去年有了一个https://github.com/ht616/express-weex-html5，跑不起来，而且还结合了别的用不着的东西

**Comment by jiyinyiyong** [comment]
下载这个客户端, 里边有 demo https://weex-project.io/cn/playground.html demo 只是纯客户端的演示, 有点像个离线的 app, 没有跟服务端相关的部分.

大一点的 demo 也是有, https://github.com/weexteam/weex-hackernews 但我也没运行过, 这个比我自己玩的复杂太多了.

现在应该是文档不够全面吧. 熟悉相关领域开发的人很多能自己猜出来没说的地方... 新手就不晓得了.

**Comment by SteveCruise** [comment]
@dongfanghu 但是我不会组合啊，weex+express不会，weex + vue-router也不会。express不是最流行的后端框架吗，weex+express的结合连一个demo没有

**Comment by SteveCruise** [comment]
@jiyinyiyong 看了package.json，这个例子是weex跟vue系列组合起来用了，不想学vue。
express不是最流行的后端框架吗，weex+express的结合连一个demo没有

**Comment by jiyinyiyong** [comment]
新手问题不适合在 GitHub 刷啊...

* https://gitter.im/weexteam/cn/~chat
* http://weex.help/topic/58847503c491b3f542a1b667

目前 Weex 是跟 Vue 语法绑定的, 如果不想学 Vue 的话, 短期不建议挖 Weex 了. Express 等以后有人写再说吧, 再说 Weex 也不关心后端是不是 Express.

**Comment by SteveCruise** [comment]
@jiyinyiyong 
我在weexteam上问过，妥妥被淹没。
Weex 不关心Express，Express也不关心Weex ，然后想前端用weex、后端用express的人就悲剧了。我一前试过，真不好结合。
总之，还是谢谢你的回答
