### ISSUE TITLE
weex-toolkit安装时报错

### ISSUE THREAD

**Issue by YongMaple** [alibaba/weex#2444]
JSONResponseFormatError: [weex-previewer@1.2.6 › weex-builder@0.1.18 › babel-core@6.22.1 › private@^0.1.6] Unexpected end of JSON input (data json format: "{\"author\":{\"name\":\"Ben Newman\",\"email\":\"bn@cs.stanford.edu\"},\"name\":\"private\",\"description\":\"Utility for associating truly private state with any JavaScript object\",\"keywords\":[\"private\",\"access control\",\"access modifiers\",\"encapsulation\",\"secret\",\"state\",\"privilege\",\"scope\",\"es5\"],\"version\":\"0.1.7\",\"homepage\":\"http://github.com/benjamn/private\",\"repository\":{\"type\":\"git\",\"url\":\"git://github.com/benjamn/private.git\"},\"license\":\"MIT\",\"main\":\"private.js\",\"files\":[\"private.js\"],\"scripts\":{\"test\":\"mocha --repor" ...skip... "value, because it is completely inaccessible except through\\nthe `.increment` method. And if the `.increment` method were not\\navailable, it would be as if no `secret` variable had ever been declared,\\nas far as you could tell.\\n\\nThis style breaks down as soon as you want to inherit methods from the\\nprototype of a class:\\n```js\\nfunction MyClass(secret) {\\n    this.secret = secret;\\n}\\n\\nMyClass.prototype.increment = function() {\\n    return ++this.secret;\\n};\\n```\\nThe only way to communicate between the"), GET https://registry.npm.taobao.org/private/%3E%3D0.1.6%20%3C0.2.0 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":28,"closeSocketCount":8,"errorSocketCount":0,"timeoutSocketCount":2,"requestCount":1310,"freeSockets":{"cdn.npm.taobao.org:443:::::::true:":6},"sockets":{"registry.npm.taobao.org:443:::::::true:":10,"cdn.npm.taobao.org:443:::::::true:":4},"requests":{"registry.npm.taobao.org:443:::::::true:":71}})
headers: {"date":"Tue, 07 Feb 2017 01:56:23 GMT","content-type":"application/json; charset=utf-8","content-length":"9642","connection":"keep-alive","x-current-requests":"1","etag":"\"25aa-zv6zeQGE1Gj6P62WnRRrbQ\"","x-readtime":"14"}
    at Object.parse (native)
    at parseJSON (/usr/local/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:875:24)
    at /usr/local/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:658:23
    at decodeContent (/usr/local/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:512:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:639:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by exolution** [comment]
不建议使用cnpm安装 最近貌似cnpm有问题 
使用npm安装吧 如果嫌慢 可以加上--registry=http://registry.npm.taobao.org 效果是跟cnpm一样的
