### ISSUE TITLE
list 组件在weex 下面横向滑动在移动端不起作用,在web端可以

### ISSUE THREAD

**Issue by dongfanghu** [alibaba/weex#2447]
http://dotwe.org/weex/0248953eac2c109842f33ebfe08fa5bd
很是尴尬

**Comment by dongfanghu** [comment]
http://dotwe.org/weex/35647ece0a3cf7898b256a90267a3644 地址贴错了

**Comment by Neeeo** [comment]
相关问题：https://github.com/alibaba/weex/issues/2438

**Comment by Hanks10100** [comment]
Fixed in weex-loader@0.4.3
