### ISSUE TITLE
关于WXComponentFactory类中+ (void)registerComponents:(NSArray *)components;

### ISSUE THREAD

**Issue by jizhidejingmo** [alibaba/weex#2452]
该方法并未对Component导出的method进行存储。
![image](https://cloud.githubusercontent.com/assets/13342825/22680449/0883b546-ed43-11e6-9aa8-dfe739f39e3b.png)
该config缺少了对方法的存储
![image](https://cloud.githubusercontent.com/assets/13342825/22680487/33aefadc-ed43-11e6-9410-61f8c1a4c4a8.png)

**Comment by acton393** [comment]
hi @jizhidejingmo  谢谢查找bug，可以提一个pr 修复一下不~

**Comment by jizhidejingmo** [comment]
好的，已经提了pr。
