### ISSUE TITLE
 // { "framework": "Vue" }， // { "framework": "Weex" } 的作用？

### ISSUE THREAD

**Issue by alex-zhang** [alibaba/weex#2463]
new webpack.BannerPlugin(
        {
          raw: true ,
          banner: '// { "framework": "Vue" }'
          // banner: '// { "framework": "Weex" }'
        }
      ),

// { "framework": "Vue" }， 
// { "framework": "Weex" }，

weexNativeRuntime  对这两个的注释的有 意识么？ 我这里感觉好像结果有点不一样啊

**Comment by Neeeo** [comment]
指明用的是 vuejs framework 还是 weex 本身的  framework。
Ref: https://weex-project.io/cn/guide/intro/using-vue.html
