### ISSUE TITLE
weex-toolket,weexpack,webpack到底是什么关系 

### ISSUE THREAD

**Issue by segatecm** [alibaba/weex#2464]
github，https://weex-project.io/cn/guide/，各个地方都不一样啊。
到底是用npm run build 还是用weexpack，完全蒙了，你们官方到底是以什么为主？

**Comment by alex-zhang** [comment]
webpack: 用于打包 js 和 weex 本身关系不大
weex-toolkit 是个工具箱，主要 用于快速调试
weexpack 主要用于 移动端app的打包

**Comment by segatecm** [comment]
weexpack用we的语法，weex-toolkit用的是vue。两个完全不能用于同一个项目。

**Comment by Hanks10100** [comment]
webpack 是一个前端的打包工具，看其[官方文档](http://webpack.github.io/docs/)。

weex-toolkit 和 weex-pack 的关系和差别可以参考[这篇文章](https://segmentfault.com/a/1190000008344148)。
