### ISSUE TITLE
WEEX 是否会支持动态组件？

### ISSUE THREAD

**Issue by jaylinwang** [alibaba/weex#2467]
咨询一下，weex是否会支持动态组件呢 😄  ，如同 [vue.js 动态组件](https://cn.vuejs.org/v2/guide/components.html#动态组件)

**Comment by jaylinwang** [comment]
sorry,sorry,是自己使用错误

**Comment by Acathur** [comment]
@jaylinwang 支持吗？

**Comment by jaylinwang** [comment]
@Acathur 是支持的

**Comment by Acathur** [comment]
@jaylinwang 我这试了试渲染不出来，用的`<component :is="comp">`，求指教
