### ISSUE TITLE
npm run build:browser 报错

### ISSUE THREAD

**Issue by stonewen** [alibaba/weex#2469]
weex git:(dev) ✗ npm run build:browser

> weex@0.4.0 build:browser /Users/wenshuo/projects/weex
> wwp && node build/build.js browser

pack components:
     name		path
     image   (./html5/render/browser/extend/components/image)
     text   (./html5/render/browser/extend/components/text)
     scrollable   (./html5/render/browser/extend/components/scrollable)
     slider   (./html5/render/browser/extend/components/slider)
     indicator   (./html5/render/browser/extend/components/indicator)
     tabheader   (./html5/render/browser/extend/components/tabheader)
     input   (./html5/render/browser/extend/components/input)
     textarea   (./html5/render/browser/extend/components/textarea)
     video   (./html5/render/browser/extend/components/video)
     switch   (./html5/render/browser/extend/components/switch)
     a   (./html5/render/browser/extend/components/a)
     embed   (./html5/render/browser/extend/components/embed)
     spinner   (./html5/render/browser/extend/components/spinner)
     web   (./html5/render/browser/extend/components/web)
     neighbor   (./html5/render/browser/extend/components/neighbor)
pack apis:
     name		path
     animation   (./html5/render/browser/extend/api/animation)
     clipboard   (./html5/render/browser/extend/api/clipboard)
     dom   (./html5/render/browser/extend/api/dom)
     event   (./html5/render/browser/extend/api/event)
     geolocation   (./html5/render/browser/extend/api/geolocation)
     globalEvent   (./html5/render/browser/extend/api/globalEvent)
     meta   (./html5/render/browser/extend/api/meta)
     modal   (./html5/render/browser/extend/api/modal)
     navigator   (./html5/render/browser/extend/api/navigator)
     pageInfo   (./html5/render/browser/extend/api/pageInfo)
     storage   (./html5/render/browser/extend/api/storage)
     stream   (./html5/render/browser/extend/api/stream)
     webview   (./html5/render/browser/extend/api/webview)
     webSocket   (./html5/render/browser/extend/api/webSocket)
pack npm:
     name		path
     WeexPicker   ()

 => start to build browser (weex-web-render)

(node:9229) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error transforming /Users/wenshuo/projects/weex/html5/render/browser/index.js with 'eslint' plugin: Failed to load plugin react: Cannot find module 'eslint-plugin-react'

**Comment by Hanks10100** [comment]
重新安装 npm 依赖。 `rm -rf node_modules && npm install`

**Comment by qiongshusheng** [comment]
![image](https://cloud.githubusercontent.com/assets/13391396/25438694/e39a75fe-2acc-11e7-8de1-4712e1cd7580.png)
请问这个是什么原因呢？

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
