### ISSUE TITLE
问个jsbundle访问文件的问题

### ISSUE THREAD

**Issue by segatecm** [alibaba/weex#2471]
用 $weex compile path/to/*.vue,*.js . 命令编译，会把所有的js文件都编成了一个。
那我如果要用其中一个文件的js，该怎么写啊：
比如
<embed v-for="item in tabItems" :src="item.src" type="weex" :style="{ visibility: item.visibility }" class="content" > </embed>

这里的:src需要写一个js文件，如果写 src: 'tabcontent.js?itemId=tab1'

这个tabcontent.js已经被编译到一个文件里面了，在ios平台上访问不到了，该怎么办。

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
