### ISSUE TITLE
[ios] sdk 0.9.5.2 包含 private apple api 导致审核被拒

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#2479]
提交 app 的时候 Apple 反馈这个：

> The app references non-public selectors in (My_APP): _isKeyDown, _modifiedInput, _modifierFlags, _unmodifiedInput

搜了下，是 `WXSimulatorShortcutMananger` 这个的原因。

**Comment by acton393** [comment]
hi @Neeeo  问题出在[这里](https://github.com/alibaba/weex/blob/dev/ios/sdk/WeexSDK/Sources/Utility/WXSimulatorShortcutManager.m#L13)

这个主要是在模拟器上才起作用的，在一次merge pr 的过程，这个地方的宏被注释掉了，我修复一下，之后在下面回复

**Comment by acton393** [comment]
hi @Neeeo   可以尝试一下 [0.9.5.3](https://cocoapods.org/pods/WeexSDK)

相关 pr #2481 

如果有发现问题，欢迎继续回复~~

**Comment by acton393** [comment]
暂时先关闭掉了，如果有发现问题，可以再打开
