### ISSUE TITLE
[Android]Build Playground Failed: Conflict with dependency 'com.android.support:recyclerview-v7'.

### ISSUE THREAD

**Issue by csvwolf** [alibaba/weex#2485]
系统 macOS 10.12.2
Android Studio 2.2.3

git clone 下了 dev 分支：

在最新版的 Android Studio 中进行编译， `gradle build` 失败：

提示：
> WARNING: Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.2.1) and test app (23.1.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
> ...
> Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.2.1) and test app (23.1.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
> 
> FAILED
> :commons:mergeDebugAndroidTestResources UP-TO-DATE
>
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:prepareDebugAndroidTestDependencies'.
> Dependency Error. See console for details.

不是很懂 Gradle 配置，只找到了：
```
    provided 'com.android.support:recyclerview-v7:23.1.1'
```

尝试了：<https://github.com/JakeWharton/u2020/blob/05a57bf43b9b61f16d32cbe8717af77cd608b0fb/build.gradle#L136-L140> 这里的方法

并没有用。

**Comment by csvwolf** [comment]
试了一下最新的 Release 版本，问题相同。

**Comment by csvwolf** [comment]
修改了 `compile 'com.android.support:design:23.2.1'` 到 `compile 'com.android.support:design:23.1.1'`，感觉是所需的 23.1.1 和这个包提供的 23.2.1 的冲突，但又不太确定。

**Comment by luckyjay09** [comment]
和up主同样的问题  反正照你说的做了  可以运行 也不知道有没有什么隐患

**Comment by YorkShen** [comment]
问题先关闭，如还有问题，提新的issue
