### ISSUE TITLE
debug问题

### ISSUE THREAD

**Issue by hwysjj** [alibaba/weex#2488]
index.we文件中使用了wxc-button，
运行`weex debug index.we`, 报了如下错误, 可有解决方法？
weex version: 1.0.1

> building...
> 
> /usr/local/lib/node_modules/weex-toolkit/node_modules/.0.4.4@source-map/lib/source-map/source-map-consumer.js:697
>         throw new Error('"' + aSource + '" is not in the SourceMap.');
>               ^
> Error: "/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.2.0@weex-components/src/wxc-button.we?c89d7814" is not in the SourceMap.
>     at BasicSourceMapConsumer.SourceMapConsumer_sourceContentFor [as sourceContentFor] (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.4.4@source-map/lib/source-map/source-map-consumer.js:697:15)
>     at /usr/local/lib/node_modules/weex-toolkit/node_modules/.0.4.4@source-map/lib/source-map/source-node.js:138:42
>     at Array.forEach (native)
>     at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.4.4@source-map/lib/source-map/source-node.js:137:34)
>     at SourceMapSource.node (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.6.9@webpack-core/lib/SourceMapSource.js:41:20)
>     at ReplaceSource.node (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.6.9@webpack-core/lib/ReplaceSource.js:64:29)
>     at CachedSource.node (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.6.9@webpack-core/lib/CachedSource.js:41:22)
>     at PrefixSource.node (/usr/local/lib/node_modules/weex-toolkit/node_modules/.0.6.9@webpack-core/lib/PrefixSource.js:27:26)
>     at /usr/local/lib/node_modules/weex-toolkit/node_modules/.0.6.9@webpack-core/lib/ConcatSource.js:38:49
>     at Array.map (native)
>

**Comment by zhoukekestar** [comment]
我同事在mac上也出现了这种情况，我给他的解决方案是：
```sh
$ npm show weex-toolkit versions // 查看weex-toolkit的所有版本
$ sudo npm install -g weex-toolkit@0.6.0 // 安装了旧的版本就可以了或选一个比这个稍微高一点的
```
可能是`weex-toolkit`的新版本没测试充分

**Comment by HikingMan** [comment]
我也是遇到这个问题，按照@zhoukekestar 的方法也没有成功

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
