### ISSUE TITLE
请问怎么生成二维码？我需要做一个微信支付扫描二维码的功能。

### ISSUE THREAD

**Issue by solaronke** [alibaba/weex#2489]
我们项目需要生成微信付款二维码，weex到底是怎么来实现生成二维码的呢？

**Comment by acton393** [comment]
hi @solaronke  需要你在native 端做扩展， 生成二维码， js 传入一些信息到native，native根据这些信息生成

**Comment by Hanks10100** [comment]
无论是 js 还是 native 上都有生成二维码的库的，这些功能不在 weex sdk 里。

这类问题可以去 [getter](https://gitter.im/weexteam/cn) 和 [segmentFault](https://segmentfault.com/t/weex) 上提问 ~
