### ISSUE TITLE
android captureActivity 竖屏扫不了  改为横屏可以扫码

### ISSUE THREAD

**Issue by Shamao** [alibaba/weex#2490]
<activity
                android:name="com.google.zxing.client.android.CaptureActivity"
                android:clearTaskOnLaunch="true"
               ***android:screenOrientation="landscape"***
                android:stateNotNeeded="true"
                android:theme="@style/CaptureTheme"
                android:windowSoftInputMode="stateAlwaysHidden">
            <intent-filter>
                <action android:name="com.google.zxing.client.android.SCAN"/>

                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>

                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>

                <data android:host="zxing.appspot.com" android:path="/scan" android:scheme="http"/>
            </intent-filter>
        </activity>

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
