### ISSUE TITLE
android 上 slider子控件高度问题

### ISSUE THREAD

**Issue by gxmdboy** [alibaba/weex#2493]
使用sdk 0.9.5
代码：
```
<template>
    <div style="flex:1">
        <slider style="flex:1">
           <div style="flex:1;background-color:yellow">
                <div style="flex:1;background-color:green;">
                </div>
           </div>
           <div style="flex:1;background-color:red">
                <div style="flex:1;background-color:blue;">
                </div>
           </div>
        </slider>
    </div>
</template>
```
里面第一层的黄色，红色div，高度是撑满整个空间的，但是其子控件就不能撑满了，只能撑一半，因为高度不一定不能写死，只能用flex:1来撑开
![screenshot_2017-02-09-13-40-39-887](https://cloud.githubusercontent.com/assets/13041525/22770829/311a80a2-eece-11e6-8c34-c2bc6b1bdb17.png)
这个是bug还是应该用其他方法布满整个布局？

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
