### ISSUE TITLE
Wee官方文档中的input实例，使用vue解析报错

### ISSUE THREAD

**Issue by xl602** [alibaba/weex#2497]
***Bug***

[http://dotwe.org/vue/849c5bc407f9c091619bc7504fb8876c](http://dotwe.org/vue/849c5bc407f9c091619bc7504fb8876c)

当输入时报错：
VM2106 vue.runtime.js:525 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value" 
(found in component <input>)

**Comment by Hanks10100** [comment]
你用的例子是 Weex 旧版框架的语法，不是 vue 语法。

试一下这个 http://dotwe.org/weex/ccf22bec1766abca6a81fd4b658c8827

Weex Playground 网站左上方有个下拉选框可以选语法版本。

**Comment by CodingForMoney** [comment]
@Hanks10100  你给的新页面里面， 选择 vue 语法， 然后进行输入，还是会有这个报错啊 。

**Comment by Hanks10100** [comment]
@CodingForMoney 要用 vue 的语法写才可以，只切换标签是不行的，目前还没有自动语法转换的功能。

**Comment by meakchen** [comment]
现在好像还是有这个问题 @Hanks10100
