### ISSUE TITLE
cocoapods集成引用不到WXSDKInstance问题

### ISSUE THREAD

**Issue by slidoooor** [alibaba/weex#2498]
之前用的是源码集成,现在复制了一份工程出来用cocoapods集成了一下,但是在使用的控制器里边就提示引用不到WXSDKInstance,,,不知道为什么,有人遇到过这种情况吗?从头开始只编辑了podfile和podinstall,还需要其他的吗

**Comment by slidoooor** [comment]
还有个小问题,weex服务端原来根视图就是一个滚动视图,现在改成滚动视图被根视图包着,也就是滚动视图不是根视图了,,然后监听滚动就没反应了,这个问题有人遇到过吗,,多谢了

**Comment by acton393** [comment]
@slidoooor  哪个版本SDK

**Comment by slidoooor** [comment]
@acton393 0.9.4

**Comment by slidoooor** [comment]
@acton393  麻烦问下程序里哪里可以看版本吗,我担心我更新出错```

**Comment by acton393** [comment]
hi @slidoooor  cocoaPods 可以在工程目录下 Podfile.lock 中看 WeexSDK的依赖版本， 

[0.9.4](https://github.com/CocoaPods/Specs/blob/e207e31fc7bbd7d371943151fa93446f7e7c9b37/Specs/7/2/9/WeexSDK/0.9.4/WeexSDK.podspec.json) 看了一下， `WXSDKInstance.h` 是public的， 你有引哪个头文件提示找不到



你监听滚动是在啥地方监听的

**Comment by slidoooor** [comment]
@acton393  我用的是源码集成,,然后引用不到是另一个工程用cocoapod集成的问题,
我有一个视图控制器里边直接创建一个weex的实例,然后整个页面就是weex,在创建之后写了onscroll的回调,但是滚动的时候不会进入这个方法,因为服务端原来根视图就是个滚动视图,现在在外面套了两个dev,,不知道和这个有没有原因,麻烦你啦

**Comment by acton393** [comment]
hi  @slidoooor  只有当 scroller 是root 标签 (也就是template 的直接子节点)时候 onScroll 才可以回调到

WXSDKInstanceI 是public 的， 可以找到工程中framework 看下，是否在header里面有这个头文件.

**Comment by slidoooor** [comment]
@acton393  但是安卓端就能监听到滚动呀....为什么呢

**Comment by acton393** [comment]
@slidoooor  native实现可能有点差异， 会尽快统一掉，这个可能需要点时间，需要验证在iOS上取消这个限制之后会不会有其他的问题

建议可以尝试：

1. 去掉根标签 div
2. 拿到rootView里面的subView 中的scrollerView 设置它的delegate为你自己的delegate， 然后回调数据， 之后在还原之前的delegate

**Comment by slidoooor** [comment]
@acton393  多谢多谢,还有一点不明白的是ios端有可以拿到weex子控件的方法吗,因为公司催的太紧,还没好好看看源码,所以很多还是自己都比较模糊,也麻烦你们啦

**Comment by acton393** [comment]
hi @slidoooor  可以查看这边 [WXComponent](https://github.com/alibaba/weex/blob/dev/ios/sdk/WeexSDK/Sources/Model/WXComponent.h#L91)
