### ISSUE TITLE
问一下beta版vue打包jsbundle的问题

### ISSUE THREAD

**Issue by hanjin39** [alibaba/weex#2501]
1. 老版we文档说可以将所有 .we 文件转换到一个目录中，我试图用同样的命令来打包vue:`weex src/components -o dist`,报错了：`Not a ".vue" or ".we" file
`
2.看到demo有一段配置[https://github.com/alibaba/weex/blob/dev/build/webpack.examples.config.js](url)，对照修改后搬过来，还是没成功，build报错。

问下vue版有什么方法可以把所有vue文件分别打包成js？

**Comment by Hanks10100** [comment]
就用 `webpack.examples.config.js` 这个文件里的配置就可以，里边的 `walk` 方法就是用来找到目录中所有 vue 文件的。

**Comment by hanjin39** [comment]
@Hanks10100 ，光改下配置还不行，问题还是蛮多的

**Comment by wslyy99** [comment]
bulid后，在dist下有个*.week.js就是，但是我在IOS下用playground扫完白屏，正在解决，哎(Android 正常)

**Comment by Hanks10100** [comment]
这类问题可以去 [getter](https://gitter.im/weexteam/cn) 和 [segmentFault](https://segmentfault.com/t/weex) 上提问 ~
