### ISSUE TITLE
关于vue生成页面时候的bug

### ISSUE THREAD

**Issue by emmanuelwang** [alibaba/weex#2503]
在同一个页面，有2个用v-for循环创建cell的list，2组的数据是通过在created方法中分别请求来的，然后在加载过程反复用navigator.push和pop，可能会出现<Weex>[error]WXJSCoreBridge.m:86, jsLog: RangeError: Maximum call stack size exceeded.  [;报错，有时候也会出现数组越界，但是在请求完a以后，再去请求b就没问题了。

请问在2个异步请求完成后，同时更新页面，是否会造成混乱?

**Comment by Hanks10100** [comment]
能否在 http://dotwe.org/vue 上提供一个例子，如果还错误可以再提供一些执行环境的信息。

![weex-env](https://cloud.githubusercontent.com/assets/8401776/22822558/e5480af8-efba-11e6-99c3-bfb384c18355.png)

**Comment by Hanks10100** [comment]
长时间未回复，我先关闭了。提 issue 时希望能提供详细的信息。
