### ISSUE TITLE
ios build 0.9.5的 playground 扫描后显示空白 报错: vue is not constructor

### ISSUE THREAD

**Issue by jiawei5** [alibaba/weex#2506]
ios build 0.9.5的 playground 扫描后显示空白 报错: vue is not constructor

**Comment by Hanks10100** [comment]
提 issue 时建议认真写一下描述，明确一下问题。可以先扫描这里的二维码看一下自己的环境 http://dotwe.org/weex/8c2fb817f19d9837a4f773e163d9cc45

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
