### ISSUE TITLE
webview与weex的交互

### ISSUE THREAD

**Issue by colys** [alibaba/weex#2508]
之前有人提了这个，后面又被关闭了，我们通常在app中都会集成有webview，如果充值，缴费等，成功后点确认按钮要关闭窗体，不能说页面一个大大的按钮，不让用户点，而去用返回图标。
另外还有其它的web页面，在完成某些动作的时候，需要通知app去做点什么，比如刷新一下什么数据的。
所在这些都是硬需要。

**Comment by zhe-he** [comment]
weex里面可以集成webview。

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
