### ISSUE TITLE
android上 将带refresh和或loading的list嵌套在slider的第三页出现的bug

### ISSUE THREAD

**Issue by gxmdboy** [alibaba/weex#2517]
android上，weex的slider是由Viewpager扩展而来。
但由于viewpager的特性，当页面初始化时，只有第一第二页会AttachedToWindow
如果第三页有带refresh和或loading的list的话，refresh和loading会生成，但无法加入list的headview和footview中，因为这页还未AttachedToWindow，setRefreshView方法未执行，headview和footview都为null

希望官方有好的解决方案

**Comment by fengmingye** [comment]
同问

**Comment by 1903514970** [comment]
同问

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
