### ISSUE TITLE
`id`, `options`, `data` variables polluted the scope in vanilla js framwork

### ISSUE THREAD

**Issue by jiyinyiyong** [alibaba/weex#2519]
In the demo of [vanilla js as a framework](https://github.com/alibaba/weex/blob/6f58f89c9ec9a6962bfea0b1008b5bb1ddc3f64a/examples/vanilla/index.js#L25) I see code:

```js
sendTasks(id, [{ module: 'dom', method: 'createFinish', args: []}])
```

Which is [defined in source](https://github.com/alibaba/weex/blob/1db33988b17601c78d3a53a6701fb7064c015a73/html5/frameworks/vanilla/index.js#L44):

```js
  const globalObjects = Object.assign({
    Document: config.Document,
    Element: config.Element,
    Comment: config.Comment,
    sendTasks: config.sendTasks,
    id, options, data, document
  }, serviceObjects)
```

`id` `options` `data` are frequent used variable names that we normally do use at globals. Can you change it to new names, maybe prefix them with `weex`?

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
