### ISSUE TITLE
如果我使用weex，但我不想打包成apk或ipa的话，是不是很多的内置组件都无法使用？

### ISSUE THREAD

**Issue by tangjion** [alibaba/weex#2522]
问一下，如果我使用weex，但不打包成apk或ipa的话，那么原生的一些特性是不是就无法实现，内置的组件是不是就有一些无法使用？这个问题怎么解决呢？我需要自己些自定义组件吗？但内置的组件根本就无法满足常见的HTML5的需求，局限很大，有什么好的方案吗？

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
