### ISSUE TITLE
[BUG]安卓端 scroller 里的 input，键盘弹出后会遮住输入框

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#2523]
input外层为普通div标签时，键盘弹出后 会将视图挤上去：

![11](https://cloud.githubusercontent.com/assets/13174847/22862046/e678f9b6-f161-11e6-9f5d-d9e68168f2fc.jpg)

input外层为scroller 或者 list时，键盘弹出则会遮挡输入框：

![22](https://cloud.githubusercontent.com/assets/13174847/22862048/e9d6699a-f161-11e6-911d-c2abd7dd390e.jpg)

**Comment by fantasybei** [comment]
也遇到了同样的问题  +1

**Comment by anrananran** [comment]
也遇到了同样的问题 +2

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
