### ISSUE TITLE
请问项目组老师，如何使用weex进行全新开发app

### ISSUE THREAD

**Issue by wenqibo** [alibaba/weex#2531]
https://weex-project.io/cn/
中的“构建全新应用”打开并没有任何内容，大概何时会更新该文档呢？

**Comment by DoranYun** [comment]
你好，构建全新应用需要 [weexpack](https://github.com/weexteam/weex-pack) 支持，目前 weexpack 对 vue 2.0 的支持还在完善中，相关进度可以在该项目仓库查看 https://github.com/weexteam/weex-pack

**Comment by Hanks10100** [comment]
这类问题，建议去社区提问（中文可以去 [SegmentFault](https://segmentfault.com/t/weex)）。另外，了解从头构建全新应用，可以参考 [weex-hackernews](https://github.com/weexteam/weex-hackernews) 项目，以及社区里[相关的文章](https://segmentfault.com/a/1190000008342533)。

**Comment by wenqibo** [comment]
@Hanks10100 好的，谢谢您的指点。

**Comment by wenqibo** [comment]
@DoranYun 哦，明白了。我关注一下。
