### ISSUE TITLE
indicator: Can't use style in css scoped

### ISSUE THREAD

**Issue by QingWei-Li** [alibaba/weex#2535]
设置  scoped 后 .indicator 的样式没有生效。

```html
<template>
  <div>
    <slider class="slider">
      <image class="image" v-for="img in imageList" resize="cover" :src="img.src"></image>
      <indicator class="indicator"></indicator>
    </slider>
  </div>
</template>

<style scoped>
  /* 设置 scoped 后 .indicator 的样式没有生效 */
  .indicator {
    width: 700px;
    height: 700px;
    item-color: green;
    item-selected-color: red;
    item-size: 50px;
    top: 200px;
    left: 200px;
  }

  .image {
    width: 700px;
    height: 700px;
  }
  .slider {
    width: 700px;
    height: 700px;
  }
</style>

<script>
  export default {
    data () {
      return {
        imageList: [
          { title: 'item A', src: 'https://gd2.alicdn.com/bao/uploaded/i2/T14H1LFwBcXXXXXXXX_!!0-item_pic.jpg'},
          { title: 'item B', src: 'https://gd1.alicdn.com/bao/uploaded/i1/TB1PXJCJFXXXXciXFXXXXXXXXXX_!!0-item_pic.jpg'},
          { title: 'item C', src: 'https://gd3.alicdn.com/bao/uploaded/i3/TB1x6hYLXXXXXazXVXXXXXXXXXX_!!0-item_pic.jpg'}
        ]
      }
    }
  }
</script>
```

## 期待的效果

demo: http://dotwe.org/vue/ea747c9d6f0a0c6de0032181d32e8bc7

指示器应该在中间位置

## 实际效果

demo: http://dotwe.org/vue/d75ac76944da1a02186722053c3ffd64

指示器在右下角

**Comment by xxxxxMiss** [comment]
我按照官网的示例跑了一遍，indicator中的样式确实没生效。加了`scoped`与不加`scoped`，指示器的位置不一样。而且`item-color`,`item-selected-color`根本就没有生效

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
