### ISSUE TITLE
[iOS]关于导航栏的问题

### ISSUE THREAD

**Issue by jizhidejingmo** [alibaba/weex#2536]
js端实现的导航栏，iOS端使用WXRootViewController初始化的NavigationController。在加载时会闪现黑灰色的导航栏，然后显示js端的实现的导航栏。
个人感觉应该是本身导航栏先于js端实现的导航栏显示，这个情况不知道有没有办法解决？

weex.version : 0.9.5.1
iPhone.version : simulators/iPhone 6p 10.2

**Comment by acton393** [comment]
hi @jizhidejingmo  native有做定制么，  如果没有的话，方便贴一个简单复现问题的case，我这边试试

**Comment by jizhidejingmo** [comment]
没有任何定制啊，js端那边实现了导航栏，引用的navibar就是你们封装的。iOS这边就是正常的初始化一个WXRootViewController的实例。
![image](https://cloud.githubusercontent.com/assets/13342825/22874662/514b307e-f202-11e6-98d9-0b39db821228.png)
![image](https://cloud.githubusercontent.com/assets/13342825/22874687/76b74334-f202-11e6-8d89-389814c60612.png)

**Comment by jizhidejingmo** [comment]
![image](https://cloud.githubusercontent.com/assets/13342825/22874755/d11ee8f4-f202-11e6-9d08-7ac8a04dd518.png)

**Comment by jizhidejingmo** [comment]
并且js端的dateRole属性如果使用了None，我这边即使隐藏了导航栏，js端的导航栏也会下移一段像素，y并不是从0开始。

**Comment by acton393** [comment]
@jizhidejingmo  方便提供一下相对完整的文本的demo不~~

**Comment by jizhidejingmo** [comment]
手动摊手，没有demo了，小问题。我们js端换了种写法，项目写完，我提个pr好了。
