### ISSUE TITLE
移植到新项目后 网络请求不执行 在demo中没问题 IOS

### ISSUE THREAD

**Issue by dongfanghu** [alibaba/weex#2539]
IOS还需要做些什么吗

**Comment by acton393** [comment]
@dongfanghu  有没有js报错信息

**Comment by dongfanghu** [comment]
@acton393 TypeError: stream.fetch is not a function. (In 'stream.fetch', 'stream.fetch' is undefined)

**Comment by acton393** [comment]
hi @dongfanghu 
看js错误是 stream 没注册成功导致的， 没注册成功的原因可能有以下几种：

1. SDK 初始化位置(时机)比较晚， 建议检查初始化位置
2. 检查是否被多次调用SDK初始化，多次初始化造成jsfm 环境被覆盖（目前多次初始化时候有bug，已经修复下个版本发），测试方法：尝试require 以下其他的内置module ,是否存在

**Comment by dongfanghu** [comment]
@acton393 谢谢解决了 sdk初始化两次了

**Comment by acton393** [comment]
#2542

**Comment by rainbowzx** [comment]
@dongfanghu 是在APP启动的时候就初始化两次吗
