### ISSUE TITLE
（iOS）网络数据加载不出来，重定义的图片加载可以，注册的event模块也没有问题

### ISSUE THREAD

**Issue by ZeroJson** [alibaba/weex#2542]
报的错误：
WXMonitor.m:190, [undefined:458:20] TypeError: stream.fetch is not a function. (In 'stream.fetch', 'stream.fetch' is undefined)
requestData
ready

**Comment by acton393** [comment]
hi @ZeroJson  按照#2542 中描述的先定位一下

**Comment by ZeroJson** [comment]
谢谢 已解决
