### ISSUE TITLE
loading view cannot display when scroller scrollDirection is horizontal

### ISSUE THREAD

**Issue by KevinOfNeu** [alibaba/weex#2546]
Here is the code.
```
<template>
  <scroller class="scroll"
            scrollDirection="horizontal"
            :style="{height: layoutHeight}">
    <slot
      v-for="item in items"
      :item="item"
      :width="layoutWidth"
      :height="layoutHeight - 2*layoutMargin"
      :margin="layoutMargin">
    </slot>
    <loading style="width:200; height: 200;flex-direction: row;justify-content: center;" :display="show">
      <loading-indicator style="height:160;width:160;color:#3192e1"></loading-indicator>
    </loading>
  </scroller>
</template>
<style scoped>
  .scroll {
    background-color: #f5f5f5;
    flex-direction: row;
  }
</style>
```

But, when scrollDirection is vertical, loading view works!

**Comment by sunorry** [comment]
SDK version?

**Comment by KevinOfNeu** [comment]
@sunorry 我用playground预览的，0.9.5 版本

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
