### ISSUE TITLE
引入scss stylus 后web端没问题，客户端报错 ：ReferenceError: Can't find variable: window

### ISSUE THREAD

**Issue by Roxyhuang** [alibaba/weex#2554]
引入scss stylus 后web端没问题，客户端报错 ：ReferenceError: Can't find variable: window

  引入方式如下

` import './navbar.styl';`

webpack loader配置如下
```
        {
          test: /\.styl$/,
          loader: 'style-loader!css-loader!stylus-loader'
        },
```

**Comment by dongfanghu** [comment]
weex 客户端中没有window .好像weex 不支持 父子关系的样式吧

**Comment by Roxyhuang** [comment]
@dongfanghu  但是我具体样式中并没有写为父子关系样式仅定义了一个class的样式？请问您具体项目中样式怎么进行处理的，谢谢

**Comment by Hanks10100** [comment]
@Roxyhuang 移动端上没有 window 变量，不要用 window ，也尽量别用全局变量。

**Comment by Hanks10100** [comment]
@Roxyhuang 移动端上没有 window 变量，不要用 window ，也尽量别用全局变量。

**Comment by markzhai** [comment]
@Hanks10100 但是他没有用window啊，只是引入了stylus而已....

**Comment by zfha** [comment]
请问现在支持less， stylus预处理器么？
