### ISSUE TITLE
ios端cocoapods集成之后main.js报错

### ISSUE THREAD

**Issue by slidoooor** [alibaba/weex#2558]
SyntaxError: Unexpected token '<'

完整的:
2017-02-14 13:18:45.538657 CH999[4136:1247068] 创建完毕
2017-02-14 13:18:45.563064 CH999[4136:1247203] [fg255,0,0; <Weex>[error]WXMonitor.m:196, [main.js:2:10996] SyntaxError: Unexpected token '<'
Function@[native code]
main.js:4:10996
init@main.js:4:11484
createInstance@main.js:4:4693
main.js:1:1775 [;

求助啊```

**Comment by Hanks10100** [comment]
报的是语法错误，是不是没编译 js bundle 代码。

**Comment by slidoooor** [comment]
@Hanks10100 您好,因为不太会前端,所以不清楚您说的是预计的哪一步有问题呢,,我从cocoadpods导入之后还需要引用main.js吗,好像不用..麻烦你啦

**Comment by acton393** [comment]
hi @slidoooor   你应该是直接 把  xxx.we  交给 weex SDK 引擎去渲染了，所以会报错

[需要将 .we 转到bundlejs](https://weex-project.io/cn/v-0.10/guide/how-to/transform-code-into-js-bundle.html) ， 把bundlejs 给weexSDK 渲染

如果cocoapods 导入，不需要手动引 main.js,

**Comment by slidoooor** [comment]
@acton393 没有啊,,之前是好好好的,这次用了cocoapod就main.js报错了,远程的文件都是相同的

**Comment by acton393** [comment]
@slidoooor  jsfm 确实检查到了 非法的字符，一般出现在大家使用.we 文件渲染，

你可以检查下你的 weex 文件里面格式有没有问题，是不是有其他误敲的字符
