### ISSUE TITLE
0.10有没有一个排期，项目中目前无法根据自适应，有没有比较好的方案

### ISSUE THREAD

**Issue by Roxyhuang** [alibaba/weex#2566]
0.10有没有一个排期，项目中目前无法根据自适应，有没有比较好的方案

**Comment by hodgevk** [comment]
是的呢，项目组最好能有个排期，什么时候出什么版本，这样我们项目更新也有底气。

**Comment by Hanks10100** [comment]
这周五。

这类问题可以去社区（[gitter](https://gitter.im/weexteam/cn) 或 [SegmentFault](https://segmentfault.com/t/weex)）里问，不建议在 issue 里问这些问题。
