### ISSUE TITLE
QRCode can't recognise by WeexPlayground and WeChat.

### ISSUE THREAD

**Issue by CodeLife2012** [alibaba/weex#2567]
Use weex tool `1.0.1-alpha`.

**Comment by CodeLife2012** [comment]
If need any further info please let me know. I tried to scan with a local build playground and the Apple Store one, both can't recognise the QR. Seems the QR scan is never callback. Then tried to scan with WeChat, also can't recognise the QR

**Comment by CodeLife2012** [comment]
A sample list below:
[<img width="502" alt="screen shot 2017-02-14 at 5 46 59 pm" src="https://cloud.githubusercontent.com/assets/4277861/22923753/ae2e47aa-f2dd-11e6-9a79-177f028b3313.png">
](url)

**Comment by Hanks10100** [comment]
The problem is obvious, this QR code is not standard. You may have to regenerate it.

If this is generated by weex-toolkit, you should change the font in your console.

**Comment by CodeLife2012** [comment]
It is generated by weex-toolkit. Any  doc about how to change the font?

**Comment by Hanks10100** [comment]
It's according to your OS and command line tools. You can search it on the web, like "How to change the font in the console".

**Comment by CodeLife2012** [comment]
I mean the doc for why `qrcode` is broken.
