### ISSUE TITLE
vue2.0 和 weex 语法的差异，vue2.0里auto-play无效，autoPlay有效

### ISSUE THREAD

**Issue by chenkezhao** [alibaba/weex#2568]
**# bug:**
vue2.0 和 weex 语法的差异，vue2.0没有支持auto-play这样中划线的写法。
template里面的，写成auto-play无效，autoPlay有效。

**Comment by Hanks10100** [comment]
是个已知问题，参考 https://github.com/weexteam/weex-vue-framework/issues/21 ，同样的问题只保留一个吧，记录在 #2438
