### ISSUE TITLE
（iOS）加载列表的时候怎么给他图片的占位符？

### ISSUE THREAD

**Issue by ZeroJson** [alibaba/weex#2570]

**Comment by ZeroJson** [comment]
已经解决了，就是在没有加载出来前给一张默认图片

**Comment by zk0301** [comment]
解决了你还不把解决方法写下来 = =！

**Comment by ZeroJson** [comment]
以下是我的做法，在重写图片加载器的类中  使用sdwebimage的方法-(id <SDWebImageOperation>)downloadImageWithURL:(NSURL *)url
                                         options:(SDWebImageOptions)options
                                        progress:(SDWebImageDownloaderProgressBlock)progressBlock
                                       completed:(SDWebImageCompletionWithFinishedBlock)completedBlock；
在progressBlock回调中加载占位图片，下面是实现源码

**Comment by ZeroJson** [comment]
以下是我的做法，在重写图片加载器的类中使用sdwebimage的方法- (id <SDWebImageOperation>)downloadImageWithURL:(NSURL *)url
                                         options:(SDWebImageOptions)options
                                        progress:(SDWebImageDownloaderProgressBlock)progressBlock
                                       completed:(SDWebImageCompletionWithFinishedBlock)completedBlock；
在progressBlock回调中加载占位图片，下面是实现源码  IMAGE_NAME 宏是： [UIImage imageNamed:name]

- (id<WXImageOperationProtocol>)downloadImageWithURL:(NSString *)url imageFrame:(CGRect)imageFrame userInfo:(NSDictionary *)userInfo completed:(void(^)(UIImage *image,  NSError *error, BOOL finished))completedBlock
{
    NSString *placeholderName;
    float imageRatio = imageFrame.size.width / imageFrame.size.height;
    if (imageRatio > 3) {
        placeholderName = @"place_holder_wide";
    }else {
        placeholderName = @"place_holder";
    }
    
    __block BOOL startDownload;
    return (id<WXImageOperationProtocol>)[[SDWebImageManager sharedManager] downloadImageWithURL:[NSURL URLWithString:url] options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) {
        if (!startDownload && completedBlock) {
            completedBlock(IMAGE_NAME(placeholderName), nil, NO);
            startDownload = YES;
        }
    } completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
        if (completedBlock) {
            if (error) {
                completedBlock(IMAGE_NAME(placeholderName), error, finished);
            }else {
                completedBlock(image, error, finished);
            }
        }
    }];
}

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
