### ISSUE TITLE
集成 Devtools 到 Android,WXSDKEngine.reload();  报错

### ISSUE THREAD

**Issue by wslyy99** [alibaba/weex#2571]
android,sdk:0.9.5

我:
debug 在加上 MainActivity加入 WXSDKEngine.reload();
我:
报错： FATAL EXCEPTION: main
                  Process: com.dowin.homeaction, PID: 32052
                  java.lang.AbstractMethodError: abstract method "void com.taobao.weex.common.IWXDebugProxy.stop(boolean)"
                      at com.taobao.weex.bridge.WXBridgeManager.initWXBridge(WXBridgeManager.java:365)
                      at com.taobao.weex.bridge.WXBridgeManager.restart(WXBridgeManager.java:402)

Activity:
  WXSDKInstance mWXSDKInstance = new WXSDKInstance(this);
        mWXSDKInstance.registerRenderListener(this);
        //mWXSDKInstance.render(WXFileUtils.loadAsset("app.weex.js", this));
        mWXSDKInstance.renderByUrl("WeexSimpleMaster","http://192.168.0.101:8080/dist/app.weex.js",null, null, WXRenderStrategy.APPEND_ASYNC);

        WXSDKEngine.reload();
Application:
/** weex初始化 */
		initDebugEnvironment(true ,false, NohttpPath.getIP());
		InitConfig config=new InitConfig.Builder().setImgAdapter(new WeexImageAdapter()).build();
		WXSDKEngine.initialize(this,config);

**Comment by wslyy99** [comment]
weex_inspector的版本问题，官网的版本写的太低了导致的错误，自己关了吧，哎

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
