### ISSUE TITLE
pod install 报错啊  版本 0.9.5.1

### ISSUE THREAD

**Issue by houtou118** [alibaba/weex#2576]
podfile 如下 

source 'git@github.com:CocoaPods/Specs.git' 
target 'weexdemo' do
    platform :ios, '7.0' 
    pod 'WeexSDK', '0.9.5.1'   
end

pod install 报错  错误如下  
[!] Unable to satisfy the following requirements:

- `WeexSDK (= 0.9.5.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `WeexSDK (= 0.9.5.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by acton393** [comment]
hi @houtou118 
follow the instruction bellow , just try `pod repo update ` before `pod install`
```
You have either:

out-of-date source repos which you can update with pod repo update.
mistyped the name or version.
not added the source repo that hosts the Podspec to your Podfile.
```

or you can try `pod update` directly
