### ISSUE TITLE
生命周期ready 和init 代码不产生效果

### ISSUE THREAD

**Issue by 1021727984** [alibaba/weex#2580]
我在Weex Preview和weex playground 运行时，发现生命周期init 和ready的代码都没有运行，直接粘贴你们的代码也不行，只有created里面的才会运行，
<template>
  <div>
    <text>Hello</text>
    <div style="height: 500; width: 500; background-color: red" if={{xxx}}></div>
  </div>
</template>
<script>
  module.exports = {
    data: function () {
      return {
        xxx: false
      }
    },
    ready: function () {
      var stream = require('@weex-module/stream');
      var GET_URL = 'http://httpbin.org/get';
      console.log('sfsf')
      stream.fetch({
        method: 'GET',
        url: GET_URL,
      }, function (res) {
        this.xxx = true;
      }.bind(this), function (res) {
      });
    }
  };
</script>

**Comment by Hanks10100** [comment]
可否在 http://dotwe.org/vue 提供例子？ 注意明确 `.we` 和 `.vue` 的语法和用法。参考 [Vue 的生命周期](https://cn.vuejs.org/v2/guide/instance.html#生命周期图示)。 Vue 2.0 里没有 ready。

**Comment by 1021727984** [comment]
好的，vue2.0确实去掉了init 和ready的生命周期，
