### ISSUE TITLE
vue怎么调用input的blur方法

### ISSUE THREAD

**Issue by yfldj** [alibaba/weex#2587]
请问，vue怎么调用input的blur方法？用we那种写法发现不起作用哦
![Uploading C48CCF51-6B9B-4B02-8B25-0E57E2678E42.png…]()
this.$el(id).blur() 这样不行啊

**Comment by Neeeo** [comment]
图挂了
`this.$refs.id.blur();`

**Comment by Hanks10100** [comment]
看不到图，我看你写的方法是 `.we` 语法里的，Vue 里的用法按 @Neeeo 说的写。

注意区分 `.we` 和 `.vue` 是不同框架不同语法，写 `.vue` 可以参考 Vue 官方文档。
