### ISSUE TITLE
swift导入最新sdk时报错

### ISSUE THREAD

**Issue by SeongBrave** [alibaba/weex#2589]
# podfile 导入最新sdk
![999413a4-bd7b-401d-a849-7884119c4f85](https://cloud.githubusercontent.com/assets/10784393/23003315/daa55a6e-f42a-11e6-9340-ffec5cabed6d.PNG)

#然后编译的时候出现

![726a2bd4-e5a9-4911-8cf2-b2d64495179b](https://cloud.githubusercontent.com/assets/10784393/23003914/996dad04-f42e-11e6-82aa-c0e1979d19dc.png)

注释， 在oc下没问题的

**Comment by acton393** [comment]
hi @SeongBrave 建议手动加一下 `stdc++`, 在 buildPhase-->  Link Binary With Library，

weexSDK 在[podspec](https://github.com/alibaba/weex/blob/ios/ios/sdk/WeexSDK.podspec#L42) 中写了这几个依赖了，看起来源码引入的时候没有生效，建议都手动加一下
