### ISSUE TITLE
weex支不支持SVG？想在weex中用D3.js？

### ISSUE THREAD

**Issue by proshuai** [alibaba/weex#2590]
？

**Comment by JackPu** [comment]
@proshuai  weex 目前不支持SVG,但是有项目[weex-plugin-svg](https://github.com/weex-plugins/weex-plugin-svg)在支持，不过目前还在开发中，可以关注下。

**Comment by proshuai** [comment]
@JackPu OK，谢了，会持续关注

**Comment by JackPu** [comment]
@proshuai  [weex-svg](https://github.com/weex-plugins/weex-svg)可以使用啦，欢迎入坑。

**Comment by proshuai** [comment]
@JackPu 好的

**Comment by NoraGithub** [comment]
@proshuai  哥们，可以指导下怎么利用weex使用D3.js吗？

**Comment by proshuai** [comment]
@NoraGithub 最近在忙其他的，目前没研究这一块

**Comment by jimwmg** [comment]
这个现在还能用吗  weex-svg
