### ISSUE TITLE
如何跳转到下一个vue页面？

### ISSUE THREAD

**Issue by sandart** [alibaba/weex#2592]
我想实现a.vue跳转到b.vue的功能，类似APP中的【列表页】进入【详情页】。
我看了官方手册navigator的示例，并不知道其中的【url】怎么写。xxxxxxxx.js从何而来？
希望能有一个详细的实例Demo。

**Comment by DoranYun** [comment]
你可以参考 [weex-hackernews](https://github.com/weexteam/weex-hackernews)

**Comment by Hanks10100** [comment]
weex-hackernews 是“单页应用”，多页之间的跳转可以参考这两个例子 [Jump](http://dotwe.org/vue/99e43f5159f9fbf9966b25a8e4dc6e82) [Back](http://dotwe.org/vue/cf5b3399e744adc527e84bfa156784e8) 。用手机扫 Jump 页面中的二维码，点击按钮，可以跳到 Back 页面，然后点击 Back 按钮，可以跳回 Jump。

**Comment by sandart** [comment]
@Hanks10100 谢谢这两个例子。用iOS手机扫二维码，结果空白页；Android手机扫码，成功；
vue使用navigator.push的【url】是怎样组成的呢？案例中的url却是xxxxx.bundle.wx;
我尝试把.vue文件改写成.we文件，使用this.$getConfig().bundleUrl获取url,替换为b.js, 可以成功跳转；
在.vue下该如何完成？

**Comment by Hanks10100** [comment]
@sandart 页面空白可能是 SDK 不支持 Vue ，`.vue` 里依然可以使用 `this.$getConfig()`，navigator 的特性是 native 提供的，`.we` 和 `.vue` 都一样。

**Comment by zhushangwei** [comment]
.vue 可以做做多页面吗 具体怎么实现

**Comment by wslyy99** [comment]
android 跳转 A.vue 到B.vue用navigator.push 实现的，但是在很多的机型里会报activity not find exception的错误，请问怎么解决？？？？

**Comment by sandart** [comment]
@Hanks10100 我的项目是根据官方文档步骤创建的，build 后，并未见 dist下有vue文件相对应的js文件。
我需要做如何的配置呢？

**Comment by zhushangwei** [comment]
@Hanks10100 因为 vue-router 的设计和实现都是在同一个页面内的，是 SPA 概念里的产物。其实前端路由也是基于 SPA 产生的概念，在 Weex 或者原生应用这种多页跳转的场景里可能并不合适，慎重使用。虽然 weex-hackernews 项目里用了 vue-router ，但是依然在同一个 Weex 实例中，这个具体该怎解决

**Comment by segatecm** [comment]
vue用weex-toolkit打包后只有一个js文件了，这个跳转的js怎么写，给个说法吧。官方这么多人维护，这个问题没有答案么。

**Comment by Hanks10100** [comment]
Vue 当然可以写多页应用，和 Web 上的多页一样，不同的页面要有不同的 URL 地址的，对应不同的 js bundle。这些东西与代码部署有关，不是 WeexSDK 里的，网上可以搜到各种相关文章。

至于怎么生成多个 js bundle ，需要配置 Webpack ，写多个入口文件就行了。一般在调试代码或测试简单页面时采用 weex-toolkit 打包，真正项目里推荐配一个完整的打包环境。

**Comment by 519833649** [comment]
你找到答案了，我用weex init 创建了一个项目，这个项目是单页面的，我就不懂怎么跳转，有人知道吗

**Comment by yangtao168** [comment]
官网的文档看得确实很吃力。就不能写一个index-detail的demo吗？我也是用weex init创建了一个项目，然后想做页面跳转的时候就不懂了。更别说页面之间传参了。各种百度没有一个能说的清楚的。

**Comment by segatecm** [comment]
已经出坑，不再用weex，mui+vue，基本和weex差不多，运行速度还快。

**Comment by hsg4ok** [comment]
我也是在这个跳转上卡住两天了。抓狂中......

**Comment by shikechen** [comment]
Weex的学习资源确实很少，官网的“Android拓展”就只有一些零星的代码片段，而不是完整的例子。
话说淘宝、天猫都在用Weex，页面跳转是很基础的需求吧？
希望增加一些学习资料。

**Comment by imcloud** [comment]
再次询问如何获取需要跳转的URL？？？

请理解题意，并不是在问跳转方法，是跳转要用的url怎么确定的怎么生成的？

**Comment by mizhon** [comment]
weex页面跳转确实非常坑，我理解它们用的是绝对路径，这个url路径的获取方式可以通过在跳转的方法里加入`this.$getConfig().bundleUrl`获取，再拼接为要跳转的目标页。
