### ISSUE TITLE
Weex怎么加载到Fragment？

### ISSUE THREAD

**Issue by luckyjay09** [alibaba/weex#2593]
Android使用原生导航栏 怎么让Weex渲染加载到当前Activity的Fragment中
官方只有Activity的Weex实现

**Comment by CCC2016** [comment]
`MainActivity` 实现 [AbstractWeexActivity](https://github.com/alibaba/weex/blob/dev/android/commons/src/main/java/com/alibaba/weex/commons/AbstractWeexActivity.java)，
在 `MainActivity` 中使用 [FragmentTabHost](https://developer.android.google.cn/reference/android/support/v4/app/FragmentTabHost.html) 实现导航，
在 Fragment 中渲染：
``` java
MainActivity mainActivity = (MainActivity) getActivity();

@Nullable
@Override
public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
    @Nullable Bundle savedInstanceState) {
    mainActivity.setContainer(customView);
    return customView;
}

@Override
public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    mainActivity.renderPage(WXFileUtils.loadAsset("more-lists.js", getContext()));
}
```
😁

**Comment by luckyjay09** [comment]
楼上有没有完整点的代码  我撸不出来啊

**Comment by CCC2016** [comment]
`Activity` 集成 `AbstractWeexActivity`就好了，AbstractWeexActivity 虽然是抽象类，但没有抽象方法，不需要做额外处理；
customView 只需是 `ViewGroup` 子类即可；
你看一遍官方 `AbstractWeexActivity` 类的代码就会懂了。
🙂

**Comment by kevinTutu** [comment]
同问 现在如何将Weex渲染加载到当前Activity的Fragment中

**Comment by Tomdoog** [comment]
一样我也想问，怎么把 js 渲染到fragment里 求大神啊

**Comment by shinyjacklee** [comment]
Hi guys, try this demo  [weex-start-kit](https://github.com/w11p3333/weex-start-kit/tree/master/Android/Demo) to see how to load weex page in `Fragment(Android)`

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
