### ISSUE TITLE
android 中 navigator.push  http方式报错ActivityNotFoundException

### ISSUE THREAD

**Issue by xiaoqi951109** [alibaba/weex#2596]
![image](https://cloud.githubusercontent.com/assets/14103130/23007043/8cc982e6-f440-11e6-9331-8ea4452956f5.png)
android中会报错
![image](https://cloud.githubusercontent.com/assets/14103130/23007051/96153aac-f440-11e6-9426-16998d5c3690.png)
求解

**Comment by wslyy99** [comment]
我也是这个问题，我们加了<action android:name="com.taobao.android.intent.action.WEEX"/>

                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="com.taobao.android.intent.category.WEEX"/>
                <action android:name="android.intent.action.VIEW"/>

                <data android:scheme="http"/>
                <data android:scheme="https"/>
                <data android:scheme="file"/>
                <data android:scheme="wxpage" />

不报错了，但是又打开一次当前页，怎么解决啊？？？

**Comment by xiaoqi951109** [comment]
同求  我加了你的那些也不报错 @wslyy99

**Comment by lidehe** [comment]
当有多个待跳转页面的时候，会弹出要你选择跳转到哪一个页面的框框。你们怎么解决这个问题的呢？

**Comment by lonieHu** [comment]
+1

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
