### ISSUE TITLE
weex使用原生导航栏 通过自定义openURL vue界面怎么实现a.vue跳转到b.vue

### ISSUE THREAD

**Issue by SeongBrave** [alibaba/weex#2599]
需要使用原生的导航栏，所以跳转界面是通过自定义module，添加openURL方法实现具体使用如下
```
var event = weex.requireModule('event')
event.openURL('http://xxx/weex/app.weex.js');
```
现在想实现效果为
```
var event = weex.requireModule('event')
event.openURL('b.vue');
```
*swift端的实现是*
```
public extension WXEventModule {
    public func openURL(_ url:String) {
        var newUrl:String = url;
        if url.hasPrefix("//") {
            newUrl = String.init(format: "http://%@", url);
        }else if !url.hasPrefix("http") {
            //relative path
            newUrl = (NSURL.init(string: url, relativeTo: weexInstance.scriptURL)!.absoluteString)!
        }
        print(url)
        let storyboard = UIStoryboard.init(name: "Main", bundle: nil)
        let mainVc = storyboard.instantiateViewController(withIdentifier: "ViewController") as! ViewController
        mainVc.url = newUrl
        weexInstance.viewController.navigationController?.pushViewController(mainVc, animated:true)
    }
}
```
通过打断的知道直接**dist** 目录下找对应的**js**文件
![901040100-58a5467586012_articlex](https://cloud.githubusercontent.com/assets/10784393/23011437/f2c93f4e-f45b-11e6-8d0b-d629ab8b4312.png)

 这样我可以将b.vue对应的生成到dist目录下就可以实现，但是觉得这样太麻烦了，有没有更好的办法呢？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
