### ISSUE TITLE
Vue 中 this 作用域的问题，数据绑定不起作用

### ISSUE THREAD

**Issue by MrFuFuFu** [alibaba/weex#2607]
如下面代码：
native 传递数据到 JS 后 `nativeCall` 的回调里，data 数据改变后，界面没有实际刷新。

channel_list 实际是赋值成功的，但是界面没有重新渲染

Android 0.9.5 有问题，在 playground 上也是，并且只有第一次刷新才有。第二次界面都描述不出来
html5 是 OK 的

```
export default {
		data: {
			channel_list: []
		},
		methods: {
			click: function(value) {
				weex.requireModule('HWBizModule').themeClickEvent(JSON.stringify(value))
			}
		},
		created: function() {
			var _this = this;
			weex.requireModule('HWNativeCallModule').nativeCall(function(data) {
				_this.channel_list = JSON.parse(data);
			});
		}
	}
```

**Comment by Hanks10100** [comment]
能否在 http://dotwe.org/vue/ 上提供一个能复现问题的例子，也请你描述下问题复现过程。

**Comment by MrFuFuFu** [comment]
Hi,  找到问题了，是 JS 一段代码写法有问题，如果这么写，就会导致界面不刷新:

```
:class="((is_freshman=='YES' && value.type=='fresh_replace' ) || (is_freshman=='NO' && value.type=='fresh')) ? 'hide' : ''"

.hide{
		width: 0ps;
		height: 0ps;
		overflow: hidden;
		display: none;
	}
```

但是换个写法，写成如下这样，就能正常刷新界面了：

```
v-if="!((is_freshman=='YES' && value.type=='fresh_replace' ) || (is_freshman=='NO' && value.type=='fresh'))"
```


能帮忙解答下这个问题吗？第一种写法，为什么不可取么，看 FAQ 里有提到 `overflow: hidden` 的问题，不知道是否是这个问题？

我们的逻辑是，在 native 获取到数据后，数据回调给 JS，然后 JS 处理数据，根据 is_freshman 和 type 判断显示5个 icon 中的某四个。所以就有了以上的代码。issue 我暂时 close 掉，还望回答下，上面写法的问题。

**Comment by Hanks10100** [comment]
Weex 不支持 `display:none`，安卓默认 `overflow:hidden` 写了无效。

**Comment by MrFuFuFu** [comment]
@Hanks10100 好的，谢谢
