### ISSUE TITLE
接口请求之后更新数据没生效

### ISSUE THREAD

**Issue by 1021727984** [alibaba/weex#2609]
我通过stream模块请求接口数据后更新数据，发现并没有重新渲染dom，但是用modal的alert显示的属性已经是更新的了，但是如果把数据更新放到stream请求外面，不进行异步请求，就不会出现这个问题，这是为什么，

**Comment by Hanks10100** [comment]
参考这个例子： http://dotwe.org/vue/675a5ac90b88ef8e67d159920de0393b ，stream 模块和异步更新都是正常的。

如果你还测试失效，请在 http://dotwe.org/vue/ 上提供一个能复现的例子，并且提供你的运行环境。

**Comment by 1021727984** [comment]
谢谢回答，问题已经解决了，可以 关闭了

**Comment by 1021727984** [comment]
@Hanks10100 早上在安卓端的playground可以了，现在又不行了，用你的例子也不行，请问这是否跟网络有关，

**Comment by Hanks10100** [comment]
很可能是 playground 版本，或者系统的问题。也可能是网络，那得看具体的报错信息了。
