### ISSUE TITLE
在native中使用返回值作为回调参数

### ISSUE THREAD

**Issue by Demon-liao** [alibaba/weex#261]
之前咨询过关于native API的问题，native和JS之间传递数据也能通过回调函数进行执行。今天我尝试用另一种方式来返回数据给到JS，如下：
```java
 @WXModuleAnno(moduleMethod = true,runOnUIThread = true)
  public  String testText(String string){
    String _string="demo_"+string;
    return string;
  }
```
想在native里面注册一个方法直接return数据回来。貌似得到的结果是`undefined`。
可否考虑执行下这种方式呢？个人觉得这样同步操作，会更方便的获取一些信息。也能避免异步尝试的一些其他问题。

**Comment by Jinjiang** [comment]
最新整理了一份提案 #968 大家可以移步这里继续讨论
这个 issue 我先关掉了
谢谢
