### ISSUE TITLE
android 跳转 A.vue 到B.vue用navigator.push 实现的，部分机型会报错，IOS没问题。

### ISSUE THREAD

**Issue by wslyy99** [alibaba/weex#2616]
android 跳转 A.vue 到B.vue用navigator.push 实现的，但是在很多的机型里会报activity not find exception的错误，请问怎么解决？？？？

后来我添加了<intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <action android:name="com.alibaba.weex.protocol.openurl"/>

                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="com.taobao.android.intent.category.WEEX"/>

                <data android:scheme="http"/>
                <data android:scheme="https"/>
                <data android:scheme="file"/>
            </intent-filter>

在Androidmanifest中，虽然不报错了，但是并跳转到子页去，而是又打开了一次当前页。如何破，比较急。

**Comment by wslyy99** [comment]
没人理，哎，自己关了吧，在playground的项目里看的代码解决了。

**Comment by zk0301** [comment]
wxpageactivity里面，加载本地的话都是loadassets，如果是sdcard的话就要改改代码了。

**Comment by shenopkss** [comment]
@wslyy99 兄弟，说下怎么解决的的啊，功德无量。
