### ISSUE TITLE
基于vue的路由跳转问题

### ISSUE THREAD

**Issue by zhushangwei** [alibaba/weex#2621]
因为 vue-router 的设计和实现都是在同一个页面内的，是 SPA 概念里的产物。其实前端路由也是基于 SPA 产生的概念，在 Weex 或者原生应用这种多页跳转的场景里可能并不合适，慎重使用。虽然 weex-hackernews 项目里用了 vue-router ，但是依然在同一个 Weex 实例中，这个具体该怎解决？

**Comment by Hanks10100** [comment]
你复制的是我在社区写的[文章](https://segmentfault.com/a/1190000008366358)里的内容，不要以此开 issue。
