### ISSUE TITLE
iOS Playground 和Android Playground 对同一代码展现结果不同

### ISSUE THREAD

**Issue by Snoopy008** [alibaba/weex#2626]

**Comment by DoubleDa** [comment]
使用slider和indicator组件过程中，
遇到了同样的问题，
本来在chrome模拟时正常 跑到iOS、Android真机上面就什么都看不到了，
是因为代码适配问题 还是weex自己的问题呢？还是其他？

**Comment by Snoopy008** [comment]
我也遇到这个问题，目前图片需要指定宽和高，不能使用百分比形式

**Comment by Snoopy008** [comment]
![snip20170217_4](https://cloud.githubusercontent.com/assets/18001368/23056582/1270c3d2-f527-11e6-8911-fce672a16722.png)
![snip20170217_2](https://cloud.githubusercontent.com/assets/18001368/23056584/130e77a8-f527-11e6-95fb-213fdf2664bc.png)

**Comment by Snoopy008** [comment]
解决了，主要是CSS样式没有按照官方的标准进行编写，重新调整CSS样式，建议以iOS为准，这样就可以保证Android上显示的与iOS一致
