### ISSUE TITLE
事件函数传参数，怎么是undefined

### ISSUE THREAD

**Issue by chenyunecjtu** [alibaba/weex#2634]
<template>
<div>
    <div style="width: 700px;height: 100px;" repeat="{{item in lists}}" onclick="click(item)">
        <div >
            <text>{{item.num}}-{{item.text}}</text>
        </div>

    </div>
</div>
</template>

<script>
    module.exports = {
        data: {
            va:'fd',
            lists:[
                {num:1,text:'test1'},
                {num:2,text:'test2'},
                {num:3,text:'test3'},
                {num:4,text:'test4'},
                {num:5,text:'test5'},

            ]
        },
        methods: {
            click: function (item, e) {
                console.log(item);
            }
        }
    }
</script>

<style>

</style>
http://dotwe.org/vue/365faa522400e8cacd1ec350515d1a35
这种给事件函数传递参数，结果是undefined
![image](https://cloud.githubusercontent.com/assets/6322749/23064228/b42d6316-f549-11e6-9bcf-0b5d5798da39.png)

**Comment by vfasky** [comment]
你用的是旧版的 weex 语法， 应该这样用（刚开始也被坑得不要不要的）http://dotwe.org/weex/281c6b7c5858b9ce2c7df8f4a6dd315c

另： 建议使用新版的 vue 语法去写，会优雅很多

**Comment by chenyunecjtu** [comment]
好的 ，谢谢
