### ISSUE TITLE
<list> 组件如何监听或者获取滚动方向？

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2635]
竖向的<list>，在滑动过程中希望知道滚动的方向。向上或者向下。这个有属性可以获得吗？

本来想用Touch事件，但是看到文档中提示说，list中目前不支持Touch事件

**Comment by misakuo** [comment]
下一个版本将会提供list/scroll事件的onscroll回调，通过两次事件坐标差值的正负即可判断滚动方向

**Comment by jasonhe88** [comment]
nice!

**Comment by ko00wu** [comment]
现在无论是向上还是向下，event.contentOffset.y 都是递增的
没有办法去判断滚动是向上还是向下的
@misakuo
