### ISSUE TITLE
在iOS上出现 JSON.stringify cannot serialize cyclic structures. 

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#2639]
### 描述
在最新版的0.10.0的iOS SDK中，出现`Unhandled promise rejection TypeError: JSON.stringify cannot serialize cyclic structures. `的错误，这是在我本地的项目中出现错误，但是在最新版本的playground中却可以执行成功

执行的js代码如下:
util.js
```
module.exports.asyncReady = function asyncReady(func) {
  return function ready() {
    const that = this;

    co.wrap(function* () {
      if (has.call(that, 'userInfo')) {
        let userInfo = yield getItem('userInfo');
        try {
          userInfo = JSON.parse(userInfo);
        } catch (e) {
          userInfo = {};
        }
        that.userInfo = userInfo;
      }

      if (has.call(that, 'domain')) {
        let domain; // = yield getItem('domain');
        domain = parseDomain(that);
        yield setItem('domain', domain);
      }

      func.call(that);
      that.dataReady = true;
    })();
  };
};
```

然后在we文件的ready方法中引用这个这个方法如下
```
const { asyncReady, encodeURIComponent } = require('../../util.js');

ready: asyncReady(function () {
    console.log('asyncReady:', this);
    modal.toast({
      message: this.abc,
      duration: 1,
    })
  }),
```

### 求解
上述util中最后  `func.call(that);`方，只在0.10.0版本中才能够使用，想知道这个具体是哪一步的解析不成功，为什么我将SDK移到自己的项目中，这个问题还在，而playground扫描二维码后却能够显示

**Comment by emptywalker** [comment]
删除了一个console.log  竟然好了。迷之尴尬  -_-


还是想求解，关于这个传this参数是如何实现的

**Comment by acton393** [comment]
@emptywalker  看报错信息是对一个循环结构JSON 化的时候有问题， 应该是 this造成的

**Comment by emptywalker** [comment]
已经解决了  tks

**Comment by hacke2** [comment]
@acton393 这个怎么解决？

**Comment by ifibercc** [comment]
anyway 这个 issue 帮我解决了大问题  坑爹的 console.log - -

**Comment by yongyuanbudong** [comment]
anyway 这个 issue 帮我解决了大问题 坑爹的 console.log ...

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
