### ISSUE TITLE
我在子组件里用input用weex格式的能获得焦点，担下面的错，用vue的input无法获得焦点，谁有searchbar例子？

### ISSUE THREAD

**Issue by adu42** [alibaba/weex#2642]
当输入时报错：
VM2106 vue.runtime.js:525 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"
(found in component )
![qq 20170218151819](https://cloud.githubusercontent.com/assets/7587171/23091299/c58a0e4e-f5ed-11e6-967c-55bff667c4c6.png)
![qq 20170218152003](https://cloud.githubusercontent.com/assets/7587171/23091300/c5b14b26-f5ed-11e6-980b-459371edb953.png)

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
