### ISSUE TITLE
android版本的代码中，com.alibaba.weex.commons这系列的包在哪里定义的

### ISSUE THREAD

**Issue by segatecm** [alibaba/weex#2646]
在android的playground里面看到代码
import com.alibaba.weex.commons.adapter.DefaultWebSocketAdapterFactory;
import com.alibaba.weex.commons.adapter.ImageAdapter;
import com.alibaba.weex.extend.PlayDebugAdapter;
import com.alibaba.weex.extend.component.RichText;
import com.alibaba.weex.extend.component.WXComponentSyncTest;
import com.alibaba.weex.extend.module.GeolocationModule;
import com.alibaba.weex.extend.module.MyModule;
import com.alibaba.weex.extend.module.RenderModule;
import com.alibaba.weex.extend.module.SyncTestModule;
import com.alibaba.weex.extend.module.WXEventModule;

但是这些在weex_sdk里面没有，请问这些在哪里？

**Comment by misakuo** [comment]
https://github.com/alibaba/weex/tree/dev/android/commons

**Comment by segatecm** [comment]
好的谢谢
