### ISSUE TITLE
android WXModule onActivityResult

### ISSUE THREAD

**Issue by jinzunyue** [alibaba/weex#2649]
0.9.5版本
在WXModule中
调用(Activity)mWXSDKInstance.getContext().startActivityForResult()
在WXModule的onActivityResult方法中为什么接收不到回调呢？

**Comment by misakuo** [comment]
你需要覆盖Context对应的Activity的onActivityResult方法，然后手动触发WXSDKInstance#onActivityResult，这样才会一层层调用到WXModule的相应方法

**Comment by jinzunyue** [comment]
我现在是在做wx的一个拍照的plugin,调用的是系统的相机，通过onActivityResult获取是否拍照成功。
这种情况，我是不能去覆盖WXPageActivity中的方法的啊，因为是plugin。请问，这种情况具体应该如何实现呢。

**Comment by misakuo** [comment]
没太理解你的意思，你指的plugin是？为什么不能覆盖WXPageActivity中的方法

**Comment by jinzunyue** [comment]
weexpack plugin create aa就是开发plugin的
如果Plugin用覆盖WXPageActivity的方式实现的，那么ios, web端开发人员使用我的plugin写的代码，在android设备上运行，岂不是会崩溃了

**Comment by jinzunyue** [comment]
https://github.com/weex-plugins/weex-permissions就像你在维护的这个plugin,
假设它需要WXPageActivity的OnActivityResult()方法的回调，你会怎么处理呢？

**Comment by misakuo** [comment]
在WXPageActivity里调用WXSDKInstance#onActivityResult就好了

**Comment by jinzunyue** [comment]
sorry,可能我还是没有表达清楚我的意思。
官方文档：Weex 开发同一份代码，可以在不同的端上分别执行，避免了多端的重复研发成本。
那么一个web开发者，当他使用我的这个plugin。当他的代码编译运行在android端的时候，实际上是没有
“在WXPageActivity里调用WXSDKInstance#onActivityResult”的。应用BUG
这样的话，这个plugin 是有问题的

**Comment by jinzunyue** [comment]
3q,终于明白，我在readme中注释下，让开发者手动调用好了。
感觉 “WXSDKInstance#onActivityResult"可以自动集成比较好。

**Comment by zk0301** [comment]
能写清楚一点吗。WXSDKInstance#onActivityResult代码怎么写。 instance怎么获取来的。
