### ISSUE TITLE
iOS运行后底部有一大块空白为什么

### ISSUE THREAD

**Issue by ijry** [alibaba/weex#2661]
![img_0011](https://cloud.githubusercontent.com/assets/3102798/23115422/ba721dc4-f77f-11e6-8e72-3e7f48486b7c.PNG)

tabbar没有定位在最底部，感觉还留了一个tab的高度？

**Comment by acton393** [comment]
@ijry  检查设置一下你的instance frame 的height ， 你应该影藏掉了导航栏

**Comment by ijry** [comment]
怎么看呢，我是新建的项目，没改过东西，奇怪的是一旦我开启了调试链接chrome后，页面就正常，关闭就上面这样。。

**Comment by solaronke** [comment]
我也是遇到一样的问题，楼主解决了吗？

**Comment by solaronke** [comment]
@ijry 楼主我找到解决的办法了，
![en](https://cloud.githubusercontent.com/assets/22043032/23204110/3a28227e-f920-11e6-86f4-bf7974848461.png)

**Comment by ijry** [comment]
果然可以

**Comment by acton393** [comment]
暂时先关闭掉了，如果有问题，可以再打开, thx ~

**Comment by 501956430** [comment]
@acton393 @solaronke @ijry 为什么这样需要设置高度-64？  android 好像没有这个问题啊

**Comment by acton393** [comment]
@501956430   导航栏 高度 44 ， statusBar 20 的高度， 加起来64

**Comment by 501956430** [comment]
@acton393 -64就会出现底部菜单栏空白，我现在也修改了这个代码 为：-0  就正常了。
