### ISSUE TITLE
扩展 navbar 的问题？

### ISSUE THREAD

**Issue by sunorry** [alibaba/weex#2691]
看老的文档里有 [wxc-navpage](https://weex-project.io/cn/v-0.10/references/wxc/wxc-navpage.html) 组件，但是在新的文档里已经没有这个组件了。
如果我们 iOS，android，想自定义 `navbar` 的话，有什么方案吗？

**Comment by markzhai** [comment]
@sunorry 见 examples/vue/include/navbar

**Comment by sunorry** [comment]
@markzhai 我想你可能没理解到我的意思，你说的这个是前端模拟的，我想要的是像之前的版本的 `wxc-navpage` 组件那样。

**Comment by markzhai** [comment]
@sunorry 我想你可能没理解到我的意思，这不是前端模拟的，之前版本的 `wxc-navpage` 如果你细读过源码，就会发现也是一些基本组件组合起来的，跟这个一样。

**Comment by sunorry** [comment]
哦哦哦，知道啦。所以这个导航栏就不是一个 `navigationBar`，而是一个自定义的 view 了。

**Comment by markzhai** [comment]
@sunorry 是的，其实参照之前的，用 weex 新的基本组件组合一下就好了

**Comment by sunorry** [comment]
@markzhai 这样的话每次进来页面先是空白的，之后才有，体验很差啊，页面还有 list 的情况更差。是会出现这种情况吧。我们现在用的是 `navigationBar`，体验就很好，现在需求增加，要各种 rightItem 样式以及事件，想自己搞一个 weex 的 `navigationBar` 就感觉很无力了。

**Comment by sunorry** [comment]
@markzhai 自定义还有一个问题，点击返回，前端手动调 back，如果在这之前我有一个 beacon，恰巧代码写错了，页面卡死，如果是原生的是不是能避免这种问题。
如果你是 weex 开发成员，还有个小需求
1. 富文本，`<p><span>123</span></p>`，123 要是红色，这种需求再常见不过了吧，但是 weex 几乎没发做到，我之前在一个 issue 说 0.10 有，但是更新还是没有；
2. list 优化，进入页面，一个请求，20 条数据，明显看到先出现一条，后面再有，应该是 tabView 一条一条的插的吧，还是太慢了，我应该没有用错，也没有多余代码。
望回复。

**Comment by wangpeiyan** [comment]
遇到同样的问题啊，有计划解决么？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
