### ISSUE TITLE
weex,模式下使用input后报错

### ISSUE THREAD

**Issue by dongfanghu** [alibaba/weex#2706]
[main.js:1:16071] RangeError: Maximum call stack size exceeded.
get@main.js:1:16071
get@main.js:1:16912
value
get@main.js:4:13737
De@main.js:1:15139
pt@main.js:1:20309还有很多很多

**Comment by Hanks10100** [comment]
很可能是代码里存在循环调用，方便的话在 http://dotwe.org/weex/ 提供能复现问题的代码。

**Comment by dongfanghu** [comment]
并未解决,但是在dotwe上是好的,后来莫名就好了

**Comment by dongfanghu** [comment]
在dotwe上是好的,后来莫名就好了
