### ISSUE TITLE
weex自定义module，里面的方法也只能有一个参数吗？

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2717]
public class MyModule extends WXModule {
  @WXModuleAnno(runOnUIThread = true)
  public void printLog(String msg) {
    Toast.makeText(mWXSDKInstance.getContext(),msg,Toast.LENGTH_SHORT).show();
  }
}

比如上面这个模板，我想在pringLog中多加一个参数是否可以？

还有是否可以传对象跟native通信？

**Comment by AugHua** [comment]
可以啊
