### ISSUE TITLE
* [ios] 不支持 vue 的 class 绑定的对象语法

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#2733]
复现demo, web没有这个问题。所用的iOS WeexSDK是 0.10.0。
vuejs 文档：https://cn.vuejs.org/v2/guide/class-and-style.html

```vue
<template>
  <div class="wrapper">
    <image :src="logoUrl" class="logo"></image>
    <text :class="{'title':true,'color':true,'font':true}">Good!! {{target}}</text>
  </div>
</template>

<style>
  .wrapper { align-items: center; margin-top: 120px; }
  .title { font-size: 48px; }
  .logo { width: 360px; height: 82px; }
  .color {color: red;}
  .font {background-color: gray;}
</style>

<script>
  export default {
    data: {
      logoUrl: 'https://alibaba.github.io/weex/img/weex_logo_blue@3x.png',
      target: 'World',
      show: true,
    },
  };
</script>
```

**Comment by Somnusochi** [comment]
@Neeeo 现在有解决这个问题么？

**Comment by Somnusochi** [comment]
我搜了其他的issue，好像weex只支持:class的数组写法不支持对象写法

**Comment by Neeeo** [comment]
@Somnusochi 没有解决。只能自己变通的了。

**Comment by zhongdom** [comment]
也掉进这个坑了，`class` 动态绑定好像只支持数组写法

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
