### ISSUE TITLE
input  单击出现复制等浮悬框

### ISSUE THREAD

**Issue by chenyunecjtu** [alibaba/weex#2750]
![image](https://cloud.githubusercontent.com/assets/6322749/23288663/b47ab02c-fa7f-11e6-9919-1f6ec939344b.png)
input 处理软键盘弹出和隐藏有什么好的办法么

**Comment by kfeagle** [comment]
有focus 和blur 功能 @misakuo

**Comment by myyeshang** [comment]
@misakuo 这个问题我年前都反馈过了，现在还没有解决。安卓手机很多型号都有这个情况，努比亚，锤子，我的基本都用不了了，如果一个页面input多的话还会出现粘滞在input上不消失。请参考这个：[https://github.com/alibaba/weex/issues/2123](https://github.com/alibaba/weex/issues/2123)

**Comment by colys** [comment]
之前用0.8版本有这个问题，后面升级到0.9的sdk，就没这个问题了

**Comment by myyeshang** [comment]
可以确定0.10版本下很多手机还是有这个问题

**Comment by misakuo** [comment]
在魅族上复现了上述问题，我这边会跟进解决

**Comment by misakuo** [comment]
问题已解决，会在0.11版本中发布

**Comment by baixiaoji** [comment]
同时还有还会有一个问题，输入完成后在剪切出来，input并不会触发对应的change和input事件，导致校验的时候，该字段还有但是在界面上不显示的问题
