### ISSUE TITLE
initSDKEnviroment与weexpack platform add ios命令创建的项目调用不一致。

### ISSUE THREAD

**Issue by wightDom** [alibaba/weex#2768]
//weexpack platform add ios创建的项目中调用的是[WXSDKEngine initSDKEnvironment]
而SDK中的API是initSDKEnviroment，单词Enviroment少了个n。
+ (void)initSDKEnviroment;

**Comment by acton393** [comment]
hi @wightDom  抱歉，这个接口是由于我们失误，单词拼写错误，目前建议废弃掉的，但是暂时功能是可以用的，里面还是调用 `initSDKEnvironment`,建议调用正确的 `initSDKEnvironment`
