### ISSUE TITLE
之前在真机上是完全可以读取我后台的数据的，但是今天不知道怎么回事没加载数据

### ISSUE THREAD

**Issue by solaronke** [alibaba/weex#2771]
之前在真机上是完全可以读取我后台的数据的，但是今天不知道怎么回事没加载数据，我在后台log没看到发送的请求，但是在模拟器里是没问题的。另外，图片加载也是不行了，提示这个错误：<Weex>[error]WXImageComponent.m:218, Error downloading image: http://m.tbgame9.com/assets/mobile_500/index_icon-e5cad622e92a19a2a9af2a18e8daf727.png, detail:未能完成操作。（“NSURLErrorDomain”错误 503。） [;求解！项目很急，望早点回复，谢谢了！

**Comment by acton393** [comment]
hi， @solaronke  你前后使用的SDK的版本都是一样的么？  贴到浏览器里面看下，你的图片的路径是否可以正常显示

**Comment by solaronke** [comment]
@acton393 图片在浏览器里能打开，sdk我没改过什么

**Comment by solaronke** [comment]
@acton393 数据自己又能加载了。。。。。。但是图片还是没发加载出来

**Comment by acton393** [comment]
@solaronke  图片的handler是你自己复写的么

**Comment by solaronke** [comment]
@acton393 现在数据又不发请求了，怎么一会儿好一会不好呢？stream的原因吗?模拟器上一切都正常
![en](https://cloud.githubusercontent.com/assets/22043032/23326771/c7435278-fb3c-11e6-998d-e8c8ae26ad06.png)

**Comment by acton393** [comment]
hi @solaronke 你的js 抛错了，检查下堆栈对应的地方， `undefined is not an object(evaluating 'ret.user')`

**Comment by zk0301** [comment]
什么鬼

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
