### ISSUE TITLE
iOS使用字体文件还是有问题

### ISSUE THREAD

**Issue by xoxhk** [alibaba/weex#2778]
> iOS使用字体文件还是有问题，每次获取uifont

 都会读取字体文件。明显卡顿，内存飙升

> if (fontFamilyDic[@"localSrc"]){
        NSString *fpath = [((NSURL*)fontFamilyDic[@"localSrc"]) path];
        if ([self isFileExist:fpath]) {
            // if the font file is not the correct font file. it will crash by singal 9
            CFURLRef fontURL = CFURLCreateWithFileSystemPath(kCFAllocatorDefault, (__bridge CFStringRef)fpath, kCFURLPOSIXPathStyle, false);
            CGDataProviderRef fontDataProvider = CGDataProviderCreateWithURL(fontURL);
            CFRelease(fontURL);
            CGFontRef graphicFont = CGFontCreateWithDataProvider(fontDataProvider);
            CGDataProviderRelease(fontDataProvider);
            CTFontRef smallFont = CTFontCreateWithGraphicsFont(graphicFont, size, NULL, NULL);
            CFRelease(graphicFont);
            font = (__bridge_transfer UIFont*)smallFont;
        }else {
            [[WXRuleManager sharedInstance] removeRule:@"fontFace" rule:@{@"fontFamily": fontFamily}];
        }
    }

**Comment by xoxhk** [comment]
这个字体文件是不是需要缓存下来，使用xcode添加字体没有这个问题。

**Comment by acton393** [comment]
hi @xoxhk  字体文件是有做缓存的，添加对应的url 字体， 缓存到本地，每次使用的时候直接拿本地缓存

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
