### ISSUE TITLE
weex demo  index 界面 是如何点击 就可以 openUrl

### ISSUE THREAD

**Issue by JunyiXie** [alibaba/weex#2784]
weex demo  index 界面 是如何点击 就可以 openUrl 跳转界面的

**Comment by gaoyuqi** [comment]
有一个扩展方法来实现的。

**Comment by JunyiXie** [comment]
哪一个呢 方便告诉一下吗

**Comment by kfeagle** [comment]
event 这个module实现的

**Comment by JunyiXie** [comment]
这个我知道。
它是调用了event 的 openUrl方法 
我好奇的是，index.we 文件里只是简单的生成了列表
他对点击进行响应的 方法调用／代码 如何实现的？在哪里呢

**Comment by kfeagle** [comment]
@JunyiXie https://github.com/alibaba/weex/blob/dev/examples/include/example-list-item.we 这个文件是不是你需要找的？

**Comment by JunyiXie** [comment]
是的 谢谢
