### ISSUE TITLE
WX_EXPORT_METHOD_SYNC 例子

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#2790]
得知从0.10版本中组件和模块可以写同步方法了， 试了几下， 不成功， 有没有范例？

谢谢！！

**Comment by cxfeng1** [comment]
@jasonhe88  可以参考demo里的 WXSyncTestModule

**Comment by jasonhe88** [comment]
@cxfeng1 谢谢！找到了，我的写法和它一样，但是不行

可能我代码哪里出问题了，再试试看

**Comment by jasonhe88** [comment]
@cxfeng1  例子里有OC的写法， 但是找不到JS的写法，应该就是和调用普通JS函数一样有返回值，但是我的例子里总说返回的值是undefined, 我的写法如下:

var returnObj = anyModule.anyFunc();

不知道你是否碰到这个问题？谢谢啦

**Comment by kfeagle** [comment]
@cxfeng1 vue支持同步调用了吗？

**Comment by hayvane** [comment]
@jasonhe88  解决了吗？ 我也发现同样的问题！

**Comment by cxfeng1** [comment]
@jasonhe88 @kfeagle  @hayvane   目前 Vue 确实不支持同步调用， 会在 0.12 版本进行补齐

**Comment by zhaoguohui** [comment]
我也遇到同样的问题了，官方能不能给个demo出来，痛苦死了，调试了好久也没解决

**Comment by xiaohuapunk** [comment]
欲哭无泪，研究了好几天，都怀疑人生了我的天

**Comment by jasonhe88** [comment]
@xiaohuapunk @zhaoguohui  哈，我也研究了半天然后放弃，暂时异步吧 :-)

**Comment by cxfeng1** [comment]
文档和代码例子参见 https://weex.apache.org/references/advanced/extend-to-ios.html   export synchronous methods

**Comment by jasonhe88** [comment]
@cxfeng1  谢谢！

等0.12吧

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
