### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by wanghui0720** [alibaba/weex#2799]
ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-12e806c2!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/components/slider.vue
template syntax error <slider-page v-for="v in sliders[1].sliderPages">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-12e806c2!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/components/slider.vue
template syntax error <slider-page v-for="v in sliders[0].sliderPages">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-12e806c2!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/components/slider.vue
template syntax error <slider-page v-for="v in sliders[0].sliderPages">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-12e806c2!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/components/slider.vue
template syntax error <slider-page v-for="v in sliders[0].sliderPages">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-12e806c2!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/components/slider.vue
template syntax error <slider-page v-for="v in sliders[0].sliderPages">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-12e806c2!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/components/slider.vue
template syntax error <slider-page v-for="v in sliders[1].sliderPages">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-12e806c2!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/components/slider.vue
template syntax error <slider-page v-for="v in sliders[2].sliderPages">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-12e806c2!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/components/slider.vue
template syntax error <slider-page v-for="v in sliders[1].sliderPages">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-3147ff20!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/modules/stream.vue
template syntax error tag <panel> has no matching end tag.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-7dc61e48!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/include/slider-page.vue
template syntax error <slider-item v-for="v in items">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-312ba2e6!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/include/tabbar.vue
template syntax error <embed v-for="item in tabItems">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

ERROR in ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-312ba2e6!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./examples/vue/include/tabbar.vue
template syntax error <tabitem v-for="item in tabItems">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

**Comment by wanghui0720** [comment]
$ node -v
v8.0.0-pre

**Comment by wanghui0720** [comment]
/weex-android$ npm install

> weex@0.4.0 postinstall /home/wanghui/weex-android
> bash ./bin/install-hooks.sh

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN weex-vue-loader@0.2.11 requires a peer of css-loader@* but none was installed.
npm WARN You are using a pre-release version of node and things may not work as expected

**Comment by CaliosD** [comment]
我也遇到了同样的问题，临时注掉 `npm run dev:examples`一行，就跑过了。。

**Comment by NoraGithub** [comment]
居然没人处理。。

**Comment by wilsonssss** [comment]
still reporting the same error, over.

**Comment by NoraGithub** [comment]
@wilsonssss comment `npm run dev:examples` in start.js(i dont remember the exact file name) then it worked. it's caused by version confilict.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
