### ISSUE TITLE
weex@beta版input组件怎么都不能输入啊？

### ISSUE THREAD

**Issue by jqy518** [alibaba/weex#2806]
用`weex init`初始化项目；什么都没写，就在`foo.vue`里加了一个input组件：`<input  type="text"/>` demo跑起来后；input获得不了焦点，也输入不了内容。有人知道是什么问题吗？

**Comment by JackPu** [comment]
@jqy518  是鼠标下面模拟触点的圆圈挡住了么？

**Comment by jqy518** [comment]
@JackPu 好像是哎，在手机端使用playground测试可以，有办法解决吗？谢谢。

**Comment by JackPu** [comment]
@jqy518  后面升级的weex-toolkit会解决这个问题。

**Comment by jqy518** [comment]
@JackPu 好的，谢谢。
