### ISSUE TITLE
安卓 native 怎么调用weex方法

### ISSUE THREAD

**Issue by fyuu2016** [alibaba/weex#2809]
安卓 native 怎么调用weex方法 ， weex和原生怎么互相通信

**Comment by hanliuxin5** [comment]
weex和原生怎么互相通信 请参考https://weex-project.io/cn/references/advanced/extend-to-android.html

安卓 native 怎么调用weex方法 请参考https://weex-project.io/cn/references/modules/globalevent.html

**Comment by yuxingfafu** [comment]
https://weex-project.io/cn/references/modules/globalevent.html
没找到这个方法呀，android的
 Map<String,Object> params=new HashMap<>();
            params.put("key","value");
            WXSDKManager.getInstance().fireGlobalEventCallback("loginSuccess",params);

fireGlobalEventCallback 这个方法没找到

**Comment by hanliuxin5** [comment]
@yuxingfafu 没太懂你的意思，没找到是前端没找到还是原生没找到呢？

**Comment by yuxingfafu** [comment]
@hanliuxin5 原生的没找到这个方法

**Comment by hanliuxin5** [comment]
跟您确认一下weex SDK的版本
```
    compile 'com.alibaba:fastjson:1.1.46.android'
    compile 'com.taobao.android:weex_sdk:0.10.0'
    compile 'com.taobao.android:weex_inspector:0.10.0.5'
    compile 'com.aliyun.ams:alicloud-android-ut:5.0.0'
```
首先您应该理解一本情况下一个看到的app页面对应着一个weex的WXSDKInstance实例，所以应该是在某个原生activity页面中调用
```
            Map<String, Object> params = new HashMap<>();
            params.put("backEvent", "activity");
            mInstance.fireGlobalEventCallback(PlusConstant.FIRE_INTERCEPTBACKEVENT, params);
```
其中mInstance就是一个WXSDKInstance的具体实例
```
        mInstance = new WXSDKInstance(this);
```

**Comment by yuxingfafu** [comment]
原生：
  Map<String,Object> params=new HashMap<>();
        WXSDKInstance mInstance = new WXSDKInstance(getActivity());
        mInstance.fireGlobalEventCallback("loginSuccess", params);
    


var globalEvent = require('@weex-module/globalEvent');
            globalEvent.addEventListener("loginSuccess", function (e) {
                utilModule.showToastError("111111");
                this.getGoodList(false);
            });
--我在created 后面这样写，js没有调用到

**Comment by yuxingfafu** [comment]
@hanliuxin5 能在帮忙看看么谢谢

**Comment by yuxingfafu** [comment]
我是用源码依赖的方式的，dev分支 0.11.0

**Comment by hanliuxin5** [comment]
这个事件是页面级别的哦，不是应用级别的。
一个页面只能监听到该页面实例发送的event

**Comment by yuxingfafu** [comment]
1.还有个问题能否帮忙一起看下
  list的高度 在部分机型下底部被遮挡，（华为有虚拟键盘的）
2.list高度我是这样算的：
  屏幕高度-状态栏高度-底部高度-虚拟键盘高度-标题栏高度

**Comment by yuxingfafu** [comment]
这个事件是页面级别的哦，不是应用级别的。
一个页面只能监听到该页面实例发送的event
--情况是这样的：
我frament是原生的， frament加载远程的js， frament在用户重新登录情况下需要刷新数据，我在frament发送通知，js收不到。 
这样算 
一个页面只能监听到该页面实例发送的event？

**Comment by hanliuxin5** [comment]
你看这样，关于fireGlobalEventCallback，你把发送event的fragment所在的weex实例id打印出来和你的注册event页面的实例id做一个比较，它们应该相同。
list高度的问题我没有明白

**Comment by yuxingfafu** [comment]
你把发送event的fragment所在的weex实例id打印出来和你的注册event页面的实例id做一个比较，
---能说下怎么获取到实例id么？

**Comment by hanliuxin5** [comment]
原生页面
`mInstance.getInstanceId();`
vue里
`weex.document.id`

**Comment by yuxingfafu** [comment]
WXSDKInstance mInstance = new WXSDKInstance(getActivity());
mInstance.getInstanceId()
--每次获取的都不一样，我原生的一个按钮点击了，然后每次打印，打印的实例id每次都不一样，每次都递增

js里面打印出来的是3

**Comment by yuxingfafu** [comment]
![image](https://cloud.githubusercontent.com/assets/7764483/24987798/64aed764-2034-11e7-8984-711a19d5f03a.png)

**Comment by yuxingfafu** [comment]
list被遮挡的如图：
图1被遮挡:
![1js dnsir v0 q vta2no](https://cloud.githubusercontent.com/assets/7764483/24987819/872a5b38-2034-11e7-8370-4f583b6e1123.png)
图2没有被遮挡：
![bq rhjkxs6 hb4ugjpzxf4](https://cloud.githubusercontent.com/assets/7764483/24987821/8fa31a84-2034-11e7-9517-df3fe0aeeb59.jpg)

图1是华为手机（有虚拟键盘的）
list的高度我是这样算的：
getStatusHeight 这个是获取状态栏

var tabHostHeight = 100.0;
require('@weex-module/utilmodel').getStatusHeight(function (ret) {
                 var scale = env.scale;
                var deviceWidth = env.deviceWidth / scale;
                var navBarHeight = 48.0 * 750.0 / deviceWidth;
                var tabBarHeight = 48.0 * 750.0 / deviceWidth;
                this.pageHeight = env.deviceHeight * 750 / env.deviceWidth - navBarHeight - tabBarHeight - tabHostHeight-ret;
                self.tableHeight = self.pageHeight;
                });


提货标题和底部图标高度是48（原生），  商品和快递那一栏高度是100写死（weex），

**Comment by yuxingfafu** [comment]
华为mate8机型

**Comment by hanliuxin5** [comment]
id如果不一样是无法收到的哦，你要检查一下为什么会这样，一般来说一个页面的id除非刷新(重新创建实例)不会改变。
关于那个列表，我理解成你的下方的导航栏是原生的是吧？然后你写了4个fragmen，对吗？

**Comment by yuxingfafu** [comment]
恩，原生的，第三个fragment里面的内容是weex的，其他都是原生的， weex加载是在fragment里面的做的

**Comment by yuxingfafu** [comment]
那问题是为什么每次获取的实例id都不一样呀？我是在fragment顶部的标题点击打印出实例id
![image](https://cloud.githubusercontent.com/assets/7764483/24988111/5b849500-2036-11e7-8d21-4c7b409072b6.png)

**Comment by hanliuxin5** [comment]
亲，你每次都new了一个WXSDKInstance，当然每次都不同啦

**Comment by yuxingfafu** [comment]
原生打印出来实例是5，js打印出来的实例是3
![image](https://cloud.githubusercontent.com/assets/7764483/24988491/dea71898-2038-11e7-8afd-66281e16b7e9.png)

js和原生实例id怎么关联的？是通过这个方法么？

**Comment by yuxingfafu** [comment]
@hanliuxin5 非常感谢，已经可以了。

https://github.com/alibaba/weex/issues/2715
我们这边ios还有个问题，就是使用BroadcastChannel的时候会报错，导致页面无法炫染展示出来，能否帮忙找相关同事看下

**Comment by hanliuxin5** [comment]
关于你说的list高度那个问题，我提供给你一个项目你说不定可以参考一下思路https://github.com/hanliuxin5/ControllerView
这样我们就不用自己去算高度再手动去设置

**Comment by yuxingfafu** [comment]
你这个是底部的4个都用weex的吧，我们这边暂时是就打算一个用weex的，看下效果，
ios的问题能否帮忙看下谢谢！

**Comment by yuxingfafu** [comment]
@hanliuxin5  最后这样处理的：
判断list item是否最后一个，最后一个的话就在底部多显示一个div，这样底部就不会被遮挡了，
应该list原生控件的的高度的那个计算有问题应该，非常感谢给予的帮忙

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
