### ISSUE TITLE
Android通过WXSDKInstance.render传一些数据之后，在weex文件中该如何获取呢？

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2812]
在Android代码中通过mWXSDKInstance.render(template, null, "{test:1}");传了一些数据到weex页面，但是在weex文件中，该在那个方法中去获取这些数据呢？init还是created？

**Comment by alex1226** [comment]
通过options传入进去 再通过getconfig获取子成员变量 可以通过调试观察到需要的变量的

**Comment by hanliuxin5** [comment]
`        console.log(weex);`
    `     console.log(weex.config.bundleUrl);`
       `  console.log(weex.config);`

你试着在把这几句话打印出来看看

**Comment by shangcongrong** [comment]
@alex1226 确实可以，多谢了
