### ISSUE TITLE
input警告

### ISSUE THREAD

**Issue by youksi** [alibaba/weex#2819]
`weex init  && npm install`

`npm run dev && npm run serve`

替换foo.vue代码，在浏览器预览，console报警告。输入文字时也会重复警告。

**weex 版本：** v1.0.1-beta.6
**代码如下：**
`<template>
  <input type="text" autofocus="true" placeholder="hello">
</template>
`
**警告信息如下：**
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value" 
(found in <Input>)
warn @ vue.runtime.js:565
(anonymous) @ vue.runtime.js:2641
reactiveSetter @ vue.runtime.js:861
proxySetter @ vue.runtime.js:2598
eventMap.(anonymous function) @ event.js:50
invoker @ vue.runtime.js:1637

**Comment by kfeagle** [comment]
<input type="text" autofocus="true" placeholder="hello"> 这句代码写错了 正确的写法
<input type="text" autofocus="true" placeholder="hello" />
@DoranYun 能否把https://weex-project.io/cn/references/components/input.html 文档改下

**Comment by youksi** [comment]
@kfeagle 
按照你的写法修改后，仍然有warn,并没有产生变化。:(

**Comment by DoranYun** [comment]
@kfeagle 这里，对于自闭合标签，根据 W3C 标准，两种写法都应该兼容，此处文档没有问题。如果出现两种写法不支持的情况，应该是 BUG。在编译阶段可进行兼容这两种写法，loader 已经提交相关 PR https://github.com/vuejs/vue/pull/5052。

**Comment by acgpiano** [comment]
@youksi @kfeagle @DoranYun 这不扯淡吗，这个问题明明是vue2的单向数据流造成的，不允许修改子组件的属性

**Comment by youksi** [comment]
@acgpiano 冒昧的问一下，虽然如此，如何使用input才不会产生warn？

**Comment by acgpiano** [comment]
@youksi 这个是weex问题，他封装的input不是原生的input，目前好像是无解的，可以忽略这个warn。你可以试试用纯vue来写，没有warn就是weex的问题，不然就是你写的组件有问题。
[twoWay-Prop-的参数-移除](https://cn.vuejs.org/v2/guide/migration.html#twoWay-Prop-的参数-移除)

**Comment by grasslandKiss** [comment]
@acgpiano 这个问题出现的很奇怪,如果入口的index.html不引入weex-vue-render这个库,vue2的v-model数据流都不会有这个warn,一旦引用,warn就会出现,weex-vue-render这个库跟vue2是不是有冲突啊?亲测过demo!

**Comment by acgpiano** [comment]
@grasslandKiss 应该是的，weex-vue-render作用是将weex的标签转换为html标签，可能里面改变了什么结构吧。

**Comment by grasslandKiss** [comment]
@acgpiano,weex在实际项目中,关于input这个标签的问题真的是太多了,三端不统一的呈现,失焦聚焦等等,这些问题后续会有改进吗?感觉要弃坑了 .......

**Comment by acgpiano** [comment]
@grasslandKiss 坑是多，很多东西还要用原生的去实现，所以我早就弃坑了。。。。

**Comment by grasslandKiss** [comment]
@acgpiano  是啊,坑好多,bug提问都无人回答,修复更新也不快,还不如直接写原生呢........

**Comment by MrRaindrop** [comment]
@acgpiano @youksi  这个报错确实是由于对 prop 的赋值引起的， 这个问题已经修复过了，详见 https://github.com/MrRaindrop/weex/commit/07aded2822296f777cf96f85615bdca046256be5#diff-b2ab5f7ca93a307cbf41571c26ec68f7L61

**Comment by grasslandKiss** [comment]
@MrRaindrop 问题仍然存在.........

**Comment by MrRaindrop** [comment]
@grasslandKiss 你用的哪个分支？这里的代码比较老...

**Comment by MrRaindrop** [comment]
@grasslandKiss  check 这个分支试一试，这里是最新的代码 https://github.com/MrRaindrop/weex/tree/html5-feature-vue-render 或者直接 npm install weex-vue-render 这个包目前发布到 0.11.0

**Comment by grasslandKiss** [comment]
@MrRaindrop 新的bug如下:[vue-render] warn: should add loader config using $processStyle to enable inline styles's auto-prefixing. see https://gist.github.com/MrRaindrop/5a805a067146609e5cfd4d64d775d693#file-weex-vue-render-config-for-vue-loader-js

**Comment by MrRaindrop** [comment]
@grasslandKiss 如果这个 gist 看不了，可以看这里 https://github.com/MrRaindrop/weex/issues/14 这一步的工作是把 inline style 和 binding style 的 autoprefix 处理放到了编译时进行绑定.

**Comment by misakuo** [comment]
@grasslandKiss 麻烦具体描述下input存在的问题

**Comment by grasslandKiss** [comment]
@misakuo 手机运行playground,input.js测试看看就知道了,主要的问题有可能是因为weex里面的input是原生的那种类型,不像浏览器中的input呈现,对于一个比较擅长web开发的人来说,就会觉得三端这种统一,有些许奇怪......话有点多,莫怪哈......

**Comment by bluetomlee** [comment]
@MrRaindrop npm install weex-vue-render升级后，weex报错没定义

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
