### ISSUE TITLE
请问有没有拍照和二维码的组件

### ISSUE THREAD

**Issue by zjsxfly** [alibaba/weex#282]
请问有没有拍照和二维码的组件

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
