### ISSUE TITLE
[Android] input 使用 focus 方法获取焦点，不会出现光标

### ISSUE THREAD

**Issue by karynsong** [alibaba/weex#2821]
手动调用 focus 方法获取焦点，引导输入的光标没有出现

**Comment by JackPu** [comment]
@karynsong  新版本的weex-toolkit去掉模拟手势触点，你可以重新安装weex-toolkit修复这个问题

**Comment by karynsong** [comment]
跟 weex-toolkit 没有关系吧，真机上的问题，点击 input 是会有光标的，但是 input 的可点区域太小了，而且不支持更改 input 高度，所以在用户点 input 附近区域时，使用 focus 方法使 input 获取焦点，但是安卓获取了焦点呼起了键盘，没有光标，iOS 都是对的

**Comment by misakuo** [comment]
input高度小于font-size的时候是不会显示光标的，这是一个已知的问题，和focus没关系

**Comment by karynsong** [comment]
真的有关系，使用 this.$refs.input.focus() 能呼起键盘，但是没有光标。直接点是有光标的

**Comment by karynsong** [comment]
@misakuo 安卓这个问题复现了么？

**Comment by misakuo** [comment]
@karynsong 在我手上的设备上都没复现，能否提供一个demo？

**Comment by misakuo** [comment]
@karynsong 看这个demo http://dotwe.org/vue/e97e0e8ffcaffa88d63d873e22d5c2e7
还是我之前说的问题，当input控件中内容的高度大于控件本身的高度时光标会被隐藏，具体的逻辑在 [WXEditText.java#L271](https://github.com/alibaba/weex/blob/v0.10.0/android/sdk/src/main/java/com/taobao/weex/ui/view/WXEditText.java#L271)，后面我们或许可以改进input的实现，在用户未指明高度时将高度自动设置为内容高度

**Comment by karynsong** [comment]
@misakuo 非常感谢你的解答。问题解决了

**Comment by langxianfu** [comment]
你怎么解决？ 还有我看到现在光标闪的颜色是红色？怎么改变颜色？

**Comment by karynsong** [comment]
input 高度写死成 60

**Comment by langxianfu** [comment]
还有我看到现在光标闪的颜色是红色？怎么改变颜色？
