### ISSUE TITLE
iOS  跳转界面 为空白

### ISSUE THREAD

**Issue by limeidong** [alibaba/weex#2835]
我在用weex 的 navigator push 方法跳转到新界面是，URL 为：
{
    animated = true;
    url = "http://weex.yy365.cn/notice-item.js?key=http://im.yiyao365.cn/Appnotice?GUID=589929229a0581486432546&token=ODg4ODg4fEA1NjYwNzA2ODAyZjZlfEA4OGM1ZGE5NTA0NDBiYzgyZmUyMWVlM2QxZDE1NmZhZQ--&title=2017_\U96e8\U8bfa\U5de5\U4f5c\U5708&author=\U51af\U5f20\U9f99&date=2017-02-07 09:55:46";
}

，我发现sdk里边 在解析 url 这个字符串的时候，NSURL * pusnUrl=[NSURL URLWithString:param[@"url"]] ，获得的 pusnUrl 为nil，这是什么情况？

**Comment by zk0301** [comment]
打断点一步步看，是哪里搞丢了

**Comment by acton393** [comment]
url  格式非法， 建议encode 之后再传入
