### ISSUE TITLE
ios中下来刷新控件我可以用第三方mjrefresh的吗

### ISSUE THREAD

**Issue by SeongBrave** [alibaba/weex#2843]
现在weex提供的刷新感觉自定义不高，我能自己通过原生代码扩展吗？我想用第三方mjrefresh扩展可以吗？

**Comment by kfeagle** [comment]
理论上可以，可以试试我个人写的插件容器，集成自动注册，通过pod引用
插件容器：https://github.com/kfeagle/WeexPlugin
使用插件容器的例子：https://github.com/kfeagle/weex-action-sheet
有好的建议也可以讨论

**Comment by SeongBrave** [comment]
@kfeagle 这得自己写一个list了，完了准备试试

**Comment by SeongBrave** [comment]
@kfeagle 您好，我建的试了下，直接修改了WXTableView代码，直接给tableview 加上mjrfresh的mj_header，然后跑了下，效果是有，但是有个bug 
![b8002e4a-c26d-4a9c-8ba5-0ff142089be9](https://cloud.githubusercontent.com/assets/10784393/23587891/f92f7dac-01ef-11e7-83e8-a467c636d346.png)
 
是不是`WXTableView`本身的bug了还是需要专门重新修改下它的frame了？




![b8002e4a-c26d-4a9c-8ba5-0ff142089be9](https://cloud.githubusercontent.com/assets/10784393/23587891/f92f7dac-01ef-11e7-83e8-a467c636d346.png)

**Comment by SeongBrave** [comment]
ok了，我再刷新结束后主动调用了下
 [tableView setContentOffset:CGPointMake(self.contentOffset.x, 0) animated:YES];
但是不知道会不会引起其它问题呢

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
