### ISSUE TITLE
有无意向参考sass的import link提高便捷性

### ISSUE THREAD

**Issue by liuzhiyi1992** [alibaba/weex#2852]
sass对组件，script，style  的 文件导入，链接，很好的重用页内重复的标签编写，script代码分文件，提高script公用性减低.we文件臃肿度

**Comment by hayvane** [comment]
现在最新的版本中，使用vue 编写是支持 sass的
 `<style lang="sass" scoped>`
`@import "../../../style/common.scss";`
`...`

**Comment by liuzhiyi1992** [comment]
@hayvane  请问下为什么会有.vue .we两种编码方式?

**Comment by liuzhiyi1992** [comment]
@hayvane 
使用weex-tool编译报错，需要如何引入sass-loader支持吗？

**Comment by anrananran** [comment]
是否支持 <style lang="scss" scoped> ？
