### ISSUE TITLE
Android平台不支持switch组件

### ISSUE THREAD

**Issue by hphua** [alibaba/weex#2863]
官方示例：http://dotwe.org/vue/06b1d740fb69d04f9ebe9eaf730974d1，
用Playground扫描打开，switch区域没效果。

**Comment by jizhongyang** [comment]
设个宽度应该就可以了

**Comment by hphua** [comment]
`
 <div class="example">
      <text class="label">checkeddfdf</text>
      <switch checked="true" style="height:20px;width=30px;"></switch>
    </div>
    <div class="example">
      <text class="label">disabled</text>
      <switch disabled="true" checked="true"  style="height:20px;"></switch>
      <switch disabled="true"  style="height:20px;width=30px;"></switch>
    </div>
    <div class="example">
      <text class="label">onchange</text>
      <switch @change="onchange"  style="height:20px;width=30px;"></switch>
      <text class="info">{{checked}}</text>
    </div>
`
添加宽高后，没效果

**Comment by jizhongyang** [comment]
<switch style="width: 100;" checked="true"></switch>

**Comment by hphua** [comment]
谢谢jizhongyang，可以了。
