### ISSUE TITLE
weex debug 异常

### ISSUE THREAD

**Issue by langxianfu** [alibaba/weex#2864]
执行weex debug 

![image](https://cloud.githubusercontent.com/assets/12893281/23605151/88eb5122-0296-11e7-8229-b1ca3b83c43f.png)
  
问题一：  点击 Inspector ，ElementMode切换选中的native 和vdom 都是显示 native组件树，没有区分native和DSL(HTML)组件树  求解
问题二：  点击debugger
![image](https://cloud.githubusercontent.com/assets/12893281/23604984/e2e8761a-0295-11e7-8bba-702924e67e4e.png)

![image](https://cloud.githubusercontent.com/assets/12893281/23605008/f837f644-0295-11e7-89fa-32c4c8b65e03.png)

**Comment by exolution** [comment]
问题一 你切换之后 要刷新一下inspector
问题二 你是用playground？如果是尝试用最新的playground试试

**Comment by langxianfu** [comment]
问题一：刷新解决不了。
问题二：换成 10.0 同样也解决不了
![image](https://cloud.githubusercontent.com/assets/12893281/23637825/ce77c86a-0318-11e7-9ba4-4dafb51f115c.png)

**Comment by langxianfu** [comment]
感谢 松影和蒲欢  大神的帮助。 最后是因为升级了weex-toolkit,  浏览器的版本太低造成的。
