### ISSUE TITLE
demo 运行不起来怎么回事

### ISSUE THREAD

**Issue by MacSzh** [alibaba/weex#2867]
clone 下来之后 直接运行脚本start 就出现了下面的问题
`zaihongdeiMac:incubator-weex zaihongshen$ . start 
/bin ~/Work/weex/incubator-weex
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.7.1/bin/node" "/usr/local/bin/npm" "run" "build:native"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! path /bin/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/bin/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/bin/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.7.1/bin/node" "/usr/local/bin/npm" "run" "build:native"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! path npm-debug.log.496771843
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'npm-debug.log.496771843'
npm ERR!  { Error: EPERM: operation not permitted, open 'npm-debug.log.496771843'
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.496771843' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /bin/npm-debug.log
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.7.1/bin/node" "/usr/local/bin/npm" "run" "build:browser"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! path /bin/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/bin/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/bin/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
`
求大神赐教

**Comment by kfeagle** [comment]
需要 先 npm install

**Comment by likenow** [comment]
首先，package.json 同级目录下运行 npm install
如果运行 iOS 工程，先安装cocoapods，然后 podfile 同级目录 运行 pod install
