### ISSUE TITLE
list的bug，使用list在下面添加了一个div，发现这个div会在list中的cell中显示并且复用

### ISSUE THREAD

**Issue by shangcongrong** [alibaba/weex#2869]
<div>
        <list style="answer_detail_list_style">
            <refresh class="refresh" onrefresh="listonrefresh" onpullingdown="onpullingdown" display="{{refreshing}}">
                <text class="indicator">Refreshing ...</text>
            </refresh>
            <cell id="question_detail_item">
                <div>
                    <div style="flex-direction:row;padding:10px;">
                        <img style="width:40px;height:40px;" src="local://res/kaola_dou" resize="contain"></img>
                        <text style="font-size:28px;">适当放宽斯蒂芬？</text>
                    </div>
                </div>
            </cell>
            <cell id="answer_detail_item-{{$index}}" repeat="question in questionList" onclick="onItemClick">
                <div style="flex-direction:row;padding:10px;">
                    <img style="width:40px;height:40px;" src="local://res/kaola_dou" resize="contain"></img>
                    <text class="answer_user_name_style" >吃货宋民国</text>
                    <text class="answer_user_label_style">小编</text>
                    <text>2017-03-07</text>
                </div>
            </cell>
        </list>
        <div id="input_div" style="flex-direction:row;">
            <p style="flex:1;height:40px;background-color:#f0f0f0;"</p>
            <input type="text" placeholder="input something" value="" onchange="onchange" oninput="oninpot">
            </input>
        </div>
	</div>

类似于上面的代码，我发现最下面的input_div会在list中出现，而且会重复多个。不知道是不是个bug

**Comment by shangcongrong** [comment]
发现是自己使用了<p>标签引起的，不知道为什么会有这种情况，难道不能用<p>吗？

**Comment by DaphneChang** [comment]
是的，不能用<p>标签呀，因为weex的内建组件里就没有提供<p>

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
