### ISSUE TITLE
不是很理解手册里的weex和vue 2.x的语法差异这一节

### ISSUE THREAD

**Issue by lili21** [alibaba/weex#2876]
[Weex和Vue 2.x的语法差异](https://weex.apache.org/cn/references/migration/difference.html)

如果有语法差异的话，怎么会做到一次撰写，多端运行呢？

而且看[weex-hackernews](https://github.com/weexteam/weex-hackernews)这个项目，并没有语法差异啊，不还是用的`v-if`跟`v-for`吗？

是我理解的有问题吗？

**Comment by JackPu** [comment]
@lili21  差异的对比是老版本.we文件与.vue文件写法的差异，

**Comment by lili21** [comment]
@JackPu 哦，原来是这样啊。谢谢。
