### ISSUE TITLE
带出参的Module 扩展方法在vue版本中无效

### ISSUE THREAD

**Issue by lltemplar** [alibaba/weex#2882]
之前使用we版本可以调用带出参的Module方法，如下所示。切换成vue版本后，方法返回为空。是否vue版本只支持在回调函数中传递参数？
```
public class SyncTestModule extends WXModule {

    @JSMethod(uiThread = false)
    public ArrayList getArray(){
        ArrayList list = new ArrayList();
        list.add("ArrayList test 1");
        list.add("ArrayList test 2");
        return list;
    }
    @JSMethod(uiThread = false)
    public String  getString(){

        return "getString :i am string ";
    }

    @JSMethod(uiThread = false)
    public int getNumber(){
        return 1111;
    }

    /**
     * JSON NOT allow KeyValue  as  non-string value
     * @return
     */
    @JSMethod(uiThread = false)
    public Object getObject(){
        ArrayList list = new ArrayList();
        list.add("222");
        list.add("test");
        Map map = new HashMap();
        map.put(11,"test11");
        map.put("22","test22");
        list.add(map);
        return list;

    }

}
```

**Comment by hayvane** [comment]
从我自己做的demo和网上的反馈来看，的确是如此。在vue中调用native同步返回为undefined.

**Comment by zk0301** [comment]
幸好一直用callback，没遇到改问题。

**Comment by cafexuan** [comment]
@zk0301 你好，请问使用callback 有能够确保同步执行的方法么。

**Comment by acton393** [comment]
hi 如果有遇到问题，欢迎在邮件组中交流  
  http://mail-archives.apache.org/mod_mbox/#weex.incubator

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
