### ISSUE TITLE
weexpack run android/  build andorid异常

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#2885]
编译报错：Unsupported major.minor version 52.0
系统jdk是1.7
adb 1.0.36

![image](https://cloud.githubusercontent.com/assets/20204491/23733448/f1222724-04b3-11e7-98f9-1429dd86ba8b.png)

**Comment by imnemo** [comment]
出现同样的问题~

**Comment by imnemo** [comment]
把jdk换成1.8

**Comment by 501956430** [comment]
jdk 换成1.8就好了，能说说为什么嘛？  难道以后只能在1.8 jdk才能保证正常运行，希望能解答下 谢谢。

**Comment by 501956430** [comment]
@imnemo jdk 换成1.8就好了，能说说为什么嘛？ 难道以后只能在1.8 jdk才能保证正常运行，希望能解答下 谢谢。
