### ISSUE TITLE
为什么用navbar 的右侧图标 点击事件没有反应？有人遇到过这个问题没？

### ISSUE THREAD

**Issue by CTOSPACE** [alibaba/weex#2889]
navbar右侧图标点击事件没有反应，这个是什么原因？

![image](https://cloud.githubusercontent.com/assets/1892162/23734578/e13f6234-04ba-11e7-927a-0c0bca0939b0.png)

右侧的点击事件没有反应？？

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
