### ISSUE TITLE
不知道工程里有没main.js混淆前的源码

### ISSUE THREAD

**Issue by xiaozi4624** [alibaba/weex#2891]
不知道工程里有没iOS版的main.js的源码，不是sdk里的混淆过的文件

**Comment by Hanks10100** [comment]
前端相关的代码都在这个目录下 https://github.com/apache/incubator-weex/tree/master/html5

SDK 里的 main.js 源文件也在 `html5` 目录下，入口文件是 [html5/render/native/index.js](https://github.com/apache/incubator-weex/blob/master/html5/render/native/index.js)

**Comment by xiaozi4624** [comment]
收到，关闭问题吧
