### ISSUE TITLE
哪一个文档更新更准确？

### ISSUE THREAD

**Issue by lili21** [alibaba/weex#2903]
中文文档与英文文档存在一定的出入。应该与哪个文档为准？

文档是不是应该标明对应的版本？不然反而会让用户更疑惑。

比如通用样式这一章，定位这一节，中文文档里有说明z-index是不支持的，但英文文档里并没有。所有z-index是现在是支持了吗？从哪个版本开始支持的？

好像也没有CHANGELOG?

**Comment by DoranYun** [comment]
中英文文档确实有一定的同步问题，一般中文文档的更新会更及时一些，我们也在和开发同学推进中英文文档同步发布的问题。特定版本才可使用的 API ，都有标明支持的版本号，如图所示：

![image](https://cloud.githubusercontent.com/assets/16359169/23792228/05c5baca-05c1-11e7-852c-ab922d90e9b1.png)

如有精力，非常欢迎与我们一起推进文档的改进工作，期待你的 PR。

就这个例子，所有支持的通用样式都已经说明，未说明的样式均不支持，所以，z-index 并未支持。

Weex 的 changelog 是有的，欢迎[查看](https://github.com/alibaba/weex/releases)

**Comment by acton393** [comment]
@lili21  暂时先关掉了，如果有问题可以再打开
