### ISSUE TITLE
【bug】BroadcastChannel is not defined

### ISSUE THREAD

**Issue by xiaohuapunk** [alibaba/weex#2906]
weex 版本 0.10.1, js使用vue编码,按照官方教程引入BroadcastChannel，报错BroadcastChannel is not defined！忘回复谢谢！

**Comment by jasonhe88** [comment]
@xiaohuapunk  我也遇到同样问题，解决了吗？

**Comment by luckcoding** [comment]
@xiaohuapunk +1

**Comment by yzcoder** [comment]
我们的应用在安卓端也遇到了这个问题, weex sdk 0.11.0
在引用BroadcastChannel时抛出异常
ReferenceError: Can't find variable: BroadcastChannel

**Comment by xiaohuapunk** [comment]
BroadcastChannel 在app客户端不支持， web 端应该是可以的，不过我们现在只需要考虑客户端
