### ISSUE TITLE
iOS SDK   pod:0.10.2版本后，启动应用强制打开“手机淘宝”！是什么原因？

### ISSUE THREAD

**Issue by xztl** [alibaba/weex#2911]

**Comment by Juice007** [comment]
刚刚也遇到了，不过现在已经好了。

**Comment by shmy** [comment]
这是暗门吗？😂

**Comment by xispower** [comment]
同遇到

**Comment by xztl** [comment]
表示安装了“手机淘宝”的，启动应用就会提示打开“手机淘宝”，必须卸载“手机淘宝”才能用自己的应用！

**Comment by acton393** [comment]
hi  @xztl   不好意思  这边有一行误提交， 这个commit 是当时修复覆盖注册的问题， 估计是当时在测试 url 拦截的问题， 测试代码误提交导致的
[错误地方](https://github.com/apache/incubator-weex/commit/1e4105f633693b26f7d73b818418ce643040de60)



已经在[pr](https://github.com/apache/incubator-weex/pull/94/files) 这边修复, 给大家带来困扰， 实在抱歉.. 


如果还发现类似问题，可以直接邮件我..
