### ISSUE TITLE
import css style support

### ISSUE THREAD

**Issue by liuzhiyi1992** [alibaba/weex#2912]
像引入组件，模块，js那样，目前或者是否考虑支持引入样式？

**Comment by CTOSPACE** [comment]
可以的呀 比如  <style src='path/style.css'></style>，也可以引入 less，比如 <style src='path/style.less' lang='less'></style>，less一定要加入 less-loader就可以了。

**Comment by CTOSPACE** [comment]
具体请查看 webpack的使用，这个跟weex关系不大，weex支持的css样式比较少

**Comment by liuzhiyi1992** [comment]
@CTOSPACE 就是说可以多个并列层级的style来引入.css吗?

**Comment by CTOSPACE** [comment]
是的，可以的，官方例子没有这些东西，自己发掘下就可以了，并列层级导入，跟html一样，但是不同文件的相同样式名会覆盖，而不是合并，同一个文件里面相同的样式名，如果用less的话会自动合并，否则也是覆盖。

**Comment by liuzhiyi1992** [comment]
@CTOSPACE 好的感谢，之前用lang='sass'是用@import的方式，换lang='css'就不行了

**Comment by liuzhiyi1992** [comment]
@CTOSPACE 在.we中的表现有点可怕，只认一个style标签，如果import进来的在首位，则其余的style样式全部无效了。
在.vue中正常

**Comment by liuzhiyi1992** [comment]
@CTOSPACE  在.we中的表现有点可怕，只认一个style标签，如果import进来的在首位，则其余的style样式全部无效了。

在.vue中正常

**Comment by CTOSPACE** [comment]
放弃we吧

**Comment by guoshengwang** [comment]
@CTOSPACE 为什么我通过<style src='path/style.css'></style> 引入样式 后
style 内部的样式不生效啦? 求教/(ㄒoㄒ)/~~

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
