### ISSUE TITLE
android的scroller的scroll-direction="horizontal"不起作用

### ISSUE THREAD

**Issue by SeongBrave** [alibaba/weex#2917]
需要横向滑动，然后使用scroller，查看api 设置scroll-direction="horizontal"即可实现横向滑动，然后ios的可以，但是android 没有任何效果
demo 效果 ： http://dotwe.org/vue/3327cbb2aa2ea69799b56a7e06cc816b

**Comment by qianlifeng** [comment]
我也发现不能？怎么关闭了？

**Comment by JackZhang1988** [comment]
需要在父容器设置flex-direction: row;
看例子：http://dotwe.org/vue/1d8e626c8c474e5768f3cb7fce7dec6f
