### ISSUE TITLE
IWXHttpAdapter里面怎么获取Context。

### ISSUE THREAD

**Issue by zk0301** [alibaba/weex#2923]
如题，我自己写一个httpadapter，用的是android-async-http。要用到Context，怎么获取。

**Comment by misakuo** [comment]
很不幸不能直接获取到，不过可以通过WXStreamModule获取到

**Comment by misakuo** [comment]
另外，如果可以使用ApplicationContext，可以通过`WXEnvironment.sApplication`获取到

**Comment by zk0301** [comment]
@misakuo 通过module方法来做的话，js就要用require自定义module。三端统一麻烦。我还是想通过adapter来实现。

**Comment by misakuo** [comment]
StreamModule会去调用你注册的HttpAdapter

**Comment by zk0301** [comment]
@misakuo 这个当然知道。。。

**Comment by zk0301** [comment]
从构造函数传进来就可以了。
