### ISSUE TITLE
后一个页面如何向前一个页面传递参数

### ISSUE THREAD

**Issue by coderminer** [alibaba/weex#2927]
想实现类似Android中startActivityForResult的效果，后一个页面完成操作之后，给上一个页面返回结果，前一个页面刷新显示对应的数据，请教如何实现？？

**Comment by zk0301** [comment]
传不了。跳转打开的Activity都是WXPageActivity的实例，难区分谁是谁。
当然了，有其他的方法。weex里可以用broadcastchannel，vue暂不支持。
或者用一些其他的方法比如先存文件再取出来。

**Comment by coderminer** [comment]
恩，已经通过broadcastchannel实现
