### ISSUE TITLE
weex 没有--qr命令

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#2928]
官网的环境搭建图片：
![default](https://cloud.githubusercontent.com/assets/20204491/23986539/ada45f24-0a5f-11e7-9742-ad75e450048c.png)

本地执行: weex 命令:
![default](https://cloud.githubusercontent.com/assets/20204491/23986521/91b72e5e-0a5f-11e7-9577-85fe653d3f0f.png)

为什么本地没有--qr ？ 有点不明白，同样都是安装weex-toolkit 为什么会存在差异？

**Comment by 501956430** [comment]
![default](https://cloud.githubusercontent.com/assets/20204491/23986689/66911d1a-0a60-11e7-81e5-f01586fd5acb.png)
记得之前不是这样的，运行后会自动挂起，命令不会结束，生成的地址也是无法用浏览器访问的

**Comment by JackPu** [comment]
@501956430  我们更新了weex-toolkit 的文档 https://weex.apache.org/cn/guide/tools/toolkit.html

我们取消--qr命令参数，然后你可以使用`compile`

第二个问题是你的服务已经启动了，你可以尝试换个端口

``` bash
weex index.vue --port 8089 --waport 8090
```

**Comment by 501956430** [comment]
@JackPu 谢谢
