### ISSUE TITLE
animation  transformOrigin设置中心点无效

### ISSUE THREAD

**Issue by AugHua** [alibaba/weex#2935]
animation的style只是单纯的改变width height，不使用transform的情况下，transformOrigin设置中心点无效；代码如下：

```
animation.transition(target, {
  styles: {
    opacity: '0.95',
    transformOrigin: 'right top',//这里都是left top
    width: 300,
    height: 292
  },
  duration: 300,
  timingFunction: 'ease-out',
  delay: 0
}, function() {

})
```

无论怎么设置transformOrigin在Android端都是和left top效果一样。

调测环境：
weex sdk 0.10.0
Android

**Comment by YorkShen** [comment]
`transformOrigin`必须和`transform`组合使用，否则该字段无意义。

**Comment by AugHua** [comment]
@YorkShen 谢谢 明白了 和CSS3 transform-origin 是一样的吗

**Comment by YorkShen** [comment]
是的，`transform-origin`遵循CSS3 标准。

**Comment by 501956430** [comment]
transformOrigin和transform组合使用,Android、ios端都是left top效果,只有H5效果正常，请问你是怎么处理的。
demo地址：http://dotwe.org/vue/fc9f526b13a3e6341eba9eed918e89d3
