### ISSUE TITLE
 npm run dev 进度卡住不动

### ISSUE THREAD

**Issue by LanCat** [alibaba/weex#2939]
![73687784-6e43-47f8-ae72-868dbea1d7e7](https://cloud.githubusercontent.com/assets/17734684/24133573/daf6582e-0e38-11e7-8098-fe2f8045ac59.png)
npm run dev

> awesome-project@0.1.0 dev /Users/apple/awesome-project
> webpack --watch

Hash: 75431730f55e6417e0c2
Version: webpack 1.14.0
Time: 1798ms
      Asset     Size  Chunks             Chunk Names
app.weex.js  4.39 kB       0  [emitted]  app
    + 5 hidden modules
Hash: 8c832d157f9e840d3d61
Version: webpack 1.14.0
Time: 1977ms
     Asset     Size  Chunks             Chunk Names
app.web.js  15.4 kB       0  [emitted]  app
    + 10 hidden modules
卡住不动了 是怎么回事啊

**Comment by 501956430** [comment]
建议去了解下这个命令实际作用，你就明白了。

**Comment by a-voyager** [comment]
我也遇到这个问题了，请问解决了吗

**Comment by yaya81540** [comment]
我也遇到了，请问怎么解决的

**Comment by ifyour** [comment]
正常的, 此时 Ctrl + C 终止, 根目录下会生成一个 dist 目录：

```
dist
├── app.web.js
└── app.weex.js // 这个文件就是以后供移动端访问的
```

运行 `npm run serve` 启动静态服务器, 然后打开 `http://localhost:8080/index.html` 预览项目.

**Comment by belover1111** [comment]
分别在 2 个 终端 中 输入 npm run dev 和 npm run serve 就好了。 注意 是serve 不是 server。

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
