### ISSUE TITLE
有木有对weex子页面做处理的？就是跳转进去 还没加载出来，给一个加载的菊花。。。

### ISSUE THREAD

**Issue by ZeroJson** [alibaba/weex#2940]
现在跳转子页面的时候 如果网络比较慢，或者在js没加载前是白屏，感觉体验不好，尝试在网络请求的扩充里，进行添加不行，在weex依托的控制器上添加也不可以。求解决方案

**Comment by ZeroJson** [comment]
补充一下 iOS的

**Comment by 501956430** [comment]
同求解决方案

**Comment by acton393** [comment]
@ZeroJson  建议你可以在 iOS native view  create的回调里面  可以自己加一下，网络请求完成的时候移除掉，
