### ISSUE TITLE
weex  如何隐藏和显示文件，比如隐藏一个图片，点击按钮再显示这个图片

### ISSUE THREAD

**Issue by beghujam** [alibaba/weex#2943]

**Comment by JackPu** [comment]
.we use `if` 
.vue use `v-if`
view: https://vuejs.org/v2/guide/conditional.html#v-if

**Comment by beghujam** [comment]
谢谢

**Comment by acton393** [comment]
if  或者直接设置css 的值 hide掉

**Comment by i7soft** [comment]
<div :if="show"></div>

这样写没效果的。。。

**Comment by i7soft** [comment]
`<div :if="show"></div>`
