### ISSUE TITLE
关于fireEvent(fireModuleEvent以及fireGlobalEventCallback)的使用

### ISSUE THREAD

**Issue by Mhina007** [alibaba/weex#2948]
最新的文档以及demo中没有看到关于fireEvent的直接调用方法，在playground的demo里面，只有WXEventModule中的openURL中使用了这个方法，没有看到直接调用 frieEvent的方法，文档中也没有fireEvent的具体使用说明

**Comment by SeongBrave** [comment]
据说vue 现在还不支持呢

**Comment by Mhina007** [comment]
@SeongBrave 不应该吧

**Comment by luoyang125024608** [comment]
vue暂不支持

**Comment by hanliuxin5** [comment]
应该是可以的，如果你的vue页面写成如下
`<lycheeButton class="lychee" text="1ss24"  @onLychee="onLychee"></lycheeButton>`

对应的原生代码应该是类似下面的样子

```
public class LycheeButton extends WXComponent {
    public LycheeButton(WXSDKInstance instance, WXDomObject dom, WXVContainer parent) {
        super(instance, dom, parent);
    }

    @Override
    protected View initComponentHostView(@NonNull Context context) {
        Button button = new Button(context);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Map<String, Object> params = new HashMap<>();
                params.put("birthday", "19930224");
                fireEvent("onLychee", params);
            }
        });
        return button;
    }

    @WXComponentProp(name = "text")
    public void setText(String text) {
        Button button = (Button) getRealView();
        button.setText(text);
    }
}
```
最后记得在application初始化时注册该自定义标签控件哦

**Comment by hanliuxin5** [comment]
关于fireGlobEvent事件
如果你vue页面有如下注册
```
  var globalEvent=weex.requireModule('globalEvent');

  globalEvent.addEventListener("interceptBackEvent", function (result) {
          console.log("get interceptBackEvent---"+result.backEvent);
    });
```
那么你的原生代码应该是如下的样子
```
Map<String, Object> params = new HashMap<>();
params.put("backEvent", "activity");
mInstance.fireGlobalEventCallback(“interceptBackEvent”, params);
```

**Comment by zhaoPengInGithub** [comment]
@hanliuxin5 你好，我想问一下，我的globalevent事件那天触发后vue端没有响应，看了你给的实例代码之后，这个mInstance是怎样定义的？

**Comment by hanliuxin5** [comment]
@zhaoPengInGithub 这个 mInstance 是指的当前页面级别的实例，是在 android 里的代码

**Comment by zhaoPengInGithub** [comment]
@hanliuxin5 嗯嗯，我现在的weex是用vue-router实现的页面，现在想在native页面获取数据时加这个fireGlobalEventCallBack去主动向js提交一个事件，但是不起作用；在这个页面还有一个监听返回事件的fireGlobalEventCallBack，这个是能用的，弄了好久也没搞定，代码如下：
//安卓端代码
public void onBackPressed(){
        long mNowTime = System.currentTimeMillis();
        if((mNowTime - mPressedTime) > 2000){
            Toast.makeText(this, "再按一次退出程序"+mWXSDKInstance.getInstanceId(), Toast.LENGTH_SHORT).show();
            mPressedTime = mNowTime;
        }else {
            Map<String, Object> params = new HashMap<>();
            params.put("name", "jzyq");
            mWXSDKInstance.fireGlobalEventCallback("androidback", params);
        }
    }

@Override
    protected void onResume() {
        super.onResume();
        if(mWXSDKInstance!=null){
            mWXSDKInstance.onActivityResume();
            try {
                SharedPreferences pref = getSharedPreferences("data",0);
                String code = pref.getString("code","");
                if(!code.equals("")){
                    Map<String, Object> wxCode = new HashMap<>();
                    wxCode.put("code", code);
                    mWXSDKInstance.fireGlobalEventCallback("wxcode",wxCode);
                    Toast.makeText(this, "事件传递完毕"+mWXSDKInstance.getInstanceId(), Toast.LENGTH_SHORT).show();
                    SharedPreferences.Editor editor = pref.edit();
                    editor.putString("code","");
                    editor.apply();
                }
            }catch (Exception e){
                e.printStackTrace();
            }
        }
    }

//vue端代码
index.vue(入口)
<template>
  <div class="wrapper" @androidBack='back'>

      <router-view style="flex:1"></router-view>

  </div>
</template>
mounted(){
    globalEvent.addEventListener('androidback', function (e) {
          close.closeApp();
    })
  }
这个是可以实现的

login.vue(登录页面)
 mounted(){
    const globalEvent = weex.requireModule('globalEvent');
    globalEvent.addEventListener('wxcode', function (e) {
          this.code = e.code;
          modal.toast({
              message:'测试code：'+e.code,
              duration:2
          })
    })
  }
没找到问题，看到你之前的issue提到id的问题，所以把id打印出来看，都是1~~~能帮忙看一下吗？谢谢了

**Comment by zhaoPengInGithub** [comment]
@hanliuxin5 补充，好像解决了，在login.vue页面的mounted周期内加个一个storage.getItem()，而且在里面的回调函数必须执行一个语句，然后就好了，也没搞懂原理

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
