### ISSUE TITLE
Mac 运行npm run dev 报错

### ISSUE THREAD

**Issue by subo-romens** [alibaba/weex#2950]
bbs:local_weex sunbo$ npm run dev

> local_weex@0.1.0 dev /Users/sunbo/Desktop/weex/local_weex
> webpack --watch

/usr/local/lib/node_modules/webpack/lib/BannerPlugin.js:19
			throw new Error("BannerPlugin only takes one argument (pass an options object)");
			^

Error: BannerPlugin only takes one argument (pass an options object)
    at new BannerPlugin (/usr/local/lib/node_modules/webpack/lib/BannerPlugin.js:19:10)
    at Object.<anonymous> (/Users/sunbo/Desktop/weex/local_weex/webpack.config.js:14:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:96:18)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! local_weex@0.1.0 dev: `webpack --watch`
npm ERR! Exit status 1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! local_weex@0.1.0 dev: `webpack --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! local_weex@0.1.0 dev: `webpack --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the local_weex@0.1.0 dev script 'webpack --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the local_weex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs local_weex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls local_weex
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sunbo/Desktop/weex/local_weex/npm-debug.log
谢谢帮忙看看

**Comment by fkysly** [comment]
你运行的是什么分支，node什么版本，npm什么版本。

**Comment by subo-romens** [comment]
解决了 谢谢

**Comment by jameschopin** [comment]
how to fix it?

**Comment by cb269267** [comment]
@subo-romens 怎么解决的，兄弟
