### ISSUE TITLE
WXModuleCallback 频繁调用问题

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#2964]
有一个场景是上传下载文件，想用WXModuleCallback回调显示上传或下载进度。

发现只有第一次进度回调成功，后续的调用都没有了。

进一步测试发现， 回调参数传一个简单的常量比如 @"test", 可以，传其他的参数都只能第一次成功。

能否查看一下这个问题？谢谢！！

**Comment by acton393** [comment]
@jasonhe88   如果需要多次使用 回调 ，可以尝试下 `WXModuleKeepAliveCallback`

**Comment by jasonhe88** [comment]
@acton393 谢谢！
