### ISSUE TITLE
Guys, please use English!

### ISSUE THREAD

**Issue by nikis05** [alibaba/weex#2967]
I respect Chinese developers and understand that it always feels more comfortable to use your native language, but it is a public open source project hosted on GitHub. Moreover, this is a framework, i.e. an instrument that is meant to be used by other developers. That's why, I suppose, the ecosystem is vital for it. English happened to be lingua franca for developers, it helps developers from different countries share their experience and cooperate in order to achieve their aims. Although my native language is russian, I wouldn't be happy if all issues in the Redux repo (Redux is designed by a developer who stames from Russia) were written in Russian. Hope you will understand me.

**Comment by zhougonglai** [comment]
^_^ sorry about that..we are very conservative

**Comment by albert-kam** [comment]
I think this is the best time to start learning mandarin. Readers Digest Chinese Edition, here i come ! After that, weex .. here i come !

**Comment by anasred** [comment]
We as developers use frameworks to not re-invent the wheel and cut-off the headache of learning new programming language. And you guys asked us to learn Mandarin to use your framework?!!
What an idea ...

We love vuejs and its simplicity, but as you propose this framework to the world you have (at least) to write your comments/issues in English do we can contribute effectively.

Peace from Syria

**Comment by JackPu** [comment]
Not agree more! If developers want to show some problems that they must use Mandarin they can go [segmentfault](https://segmentfault.com/t/weex).

**Comment by QzwJuHao** [comment]
We will try my best.
Peace from China.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
