### ISSUE TITLE
weex构建iOS项目图片无法显示

### ISSUE THREAD

**Issue by shihuacivis** [alibaba/weex#2971]
weexpack版本0.3.13。执行下面操作创建一个实例DEMO项目：
```bash
weexpack creeate app
cd app && npm install
weexpack platform add ios
weexpack run ios
```
第一次执行时，在选择设备后会报一次错，然后会继续执行一长段指令后再报错，终止:
```bash
project is building ...
** BUILD FAILED **


The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/WeexDemo.app/WeexDemo normal x86_64
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/WeexDemo.app/WeexDemo normal x86_64
(1 failure)


User defaults from command line:
    IDEDerivedDataPathOverride = /Users/shihua/Documents/workspace/app/platforms/ios/build

Build settings from command line:
    SDKROOT = iphonesimulator10.3

=== CLEAN TARGET WeexDemo OF PROJECT WeexDemo WITH CONFIGURATION Debug ===

……
……
……

clang: error: linker command failed with exit code 1 (use -v to see invocation)


** BUILD FAILED **


The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/WeexDemo.app/WeexDemo normal x86_64
(1 failure)

```
重新运行一遍后编译成功，进入模拟器。

但是DEMO项目中的的图片无法显示，即以DEMO中weex的logo无法显示：
```html
      <image src="http://ata2-img.cn-hangzhou.img-pub.aliyun-inc.com/7d42775b8f0d0c86589082dc9ee179c2.png" class="bannar-image"/>
```
但是该DEMO在web和android环境中图片均能显示。

**Comment by 501956430** [comment]
iOS 下木有封装图片下载接口，所以……

**Comment by zhj1002** [comment]
ios 没有 图片下载显示
要自己 去完成 图片显示 下载 我导入了SDWebImg

![image](https://cloud.githubusercontent.com/assets/19491491/24845509/2ce8956e-1de5-11e7-92aa-34003927bcfa.png)

1 .h
#import <Foundation/Foundation.h>
#import "WXImgLoader.h"
#import <WeexSDK/WXImgLoaderProtocol.h>
@interface WXImgLoader : NSObject<WXImgLoaderProtocol,WXModuleProtocol>

@end

2.m
#import "WXImgLoader.h"
#import <WeexSDK/WXImgLoaderProtocol.h>
#import "WXImgLoader.h"
#import <SDWebImage/UIImageView+WebCache.h>

#define MIN_IMAGE_WIDTH 36
#define MIN_IMAGE_HEIGHT 36

#if OS_OBJECT_USE_OBJC
#undef  WXDispatchQueueRelease
#undef  WXDispatchQueueSetterSementics
#define WXDispatchQueueRelease(q)
#define WXDispatchQueueSetterSementics strong
#else
#undef  WXDispatchQueueRelease
#undef  WXDispatchQueueSetterSementics
#define WXDispatchQueueRelease(q) (dispatch_release(q))
#define WXDispatchQueueSetterSementics assign
#endif

@interface WXImgLoader()

@property (WXDispatchQueueSetterSementics, nonatomic) dispatch_queue_t ioQueue;

@end

@implementation WXImgLoader

#pragma mark -
#pragma mark WXImgLoaderProtocol

- (id<WXImageOperationProtocol>)downloadImageWithURL:(NSString *)url imageFrame:(CGRect)imageFrame userInfo:(NSDictionary *)userInfo completed:(void(^)(UIImage *image,  NSError *error, BOOL finished))completedBlock
{
    if ([url hasPrefix:@"//"]) {
        url = [@"http:" stringByAppendingString:url];
    }
    
    SDWebImageManager *imgWeb = [SDWebImageManager sharedManager];
    
    
    return (id<WXImageOperationProtocol>)[imgWeb loadImageWithURL:[NSURL URLWithString:url] options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) {
        
    } completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL) {
        if(completedBlock) {
            completedBlock(image, error, finished);
        };
    }];
}

@end

然后去 appDelegate里注册一下
   [WXSDKEngine registerHandler:[WXImgLoader new] withProtocol:@protocol(WXImgLoaderProtocol)];

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
