### ISSUE TITLE
android 跳转 A.vue 到B.vue用navigator.push 实现的，部分机型会报错，IOS没问题。

### ISSUE THREAD

**Issue by ambitionJz** [alibaba/weex#2985]
android 跳转 A.vue 到B.vue用navigator.push 实现的，但是在很多的机型里会报activity not find exception的错误，请问怎么解决？？？？

后来我添加了

            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="com.taobao.android.intent.category.WEEX"/>

            <data android:scheme="http"/>
            <data android:scheme="https"/>
            <data android:scheme="file"/>
        </intent-filter>
在Androidmanifest中，虽然不报错了，但是并跳转到子页去，而是又打开了一次当前页。如何破，比较急。

**Comment by zk0301** [comment]
没遇到过。我是在官方playground工程基础上做的，push没遇到问题。 为什么你要自己起项目呢，会有坑的啊哈哈。

**Comment by heiren0926** [comment]
请问，这个问题是咋解决的啊？
