### ISSUE TITLE
vue文件如何生成jsbundle文件?

### ISSUE THREAD

**Issue by py389172739** [alibaba/weex#2987]
我是做android原生开发的，对webpack知道一点点，我想做一个页面跳转，利用navigator组件，但是这个组件是js间跳转，所以我想那么应该是把对应的vue文件写成对应的两个js文件：
我的思路是：写两个vue文件，然后生成对应的jsbundle文件，但是我生成的dist下只有一个js文件，我想问一下，怎么配置webpack才可以给每个vue生成对应jsbundle文件？
还有想问下：
weex-vue-loader 、weex-vue-render、vue-loader、weex-loader在处理文件的过程中，分别是起什么作用的？

**Comment by JackPu** [comment]
@py389172739  webpack 对 vue的多文件打包可以看这里: https://github.com/weex-plugins/weex-app-seed/blob/master/webpack.config.js

然后 weex-vue-render 你可以看做 weex的 vue sdk，weex-loader 和 vue-loader是正对不同平台(native web)在webpack配置里的加载器

**Comment by py389172739** [comment]
@JackPu  非常感谢你提供的资料，我现在可以生成多个js文件了，我整理了一下思路，大概是这样的，遍历vue文件，然后按照固定的规则生成.js文件，大概格式是这样的：
var App = require('..\createLive.vue')
App.el = '#root'
new Vue(App)
然后在把对应生成的js文件转成jsbundle文件
我的这个理解对吗？

但是转成多个js文件在跳转的过程中我又遇到新的问题了：
我在用navigator做跳转的时候，传入的js的路径是“file://assets/dist/createLive.weex.js”,我检查了一下platforms\android\app\src\main\assets下文件的路径和文件名是对的，但是我跳转过去之后显示：render error：-2013，我怀疑是我的jsbundle没有按照正确的方式生成还是我的跳转路径有问题呢？

我的vue文件的内容为：
<template>
  <div class="wrapper" append="node">
    <text>跳转后的页面</text>
  </div>
</template>

<style>
  .wrapper { 
    display: flex;
    flex-direction: column;
    width: 750px;
    position: absolute;
    top: 90px;
    bottom: 120px;
  }
</style>
<script>
  export default {
  }
</script>

麻烦帮忙看下，这个问题困扰我好久了

**Comment by py389172739** [comment]
@JackPu 抱歉，vue文件的内容刚刚不全，我再重现贴一下：
<template>
  <div class="wrapper" append="node">
    <text>跳转后的页面</text>
  </div>
</template>

<style>
  
  .wrapper { 
    display: flex;
    flex-direction: column;
    width: 750px;
    position: absolute;
    top: 90px;
    bottom: 120px;
  }
</style>

<script>
  export default {
   
  }
</script>

**Comment by py389172739** [comment]
@JackPu 非常感谢，是我理解错了，web端的时候才需要将vue按照固定的规则转成js文件，而native端的时候是直接用weex-loader转成js，现在跳转已经ok了，但是在跳转的过程中有个正在加载的的圆圈，这个可以去掉吗？我看官方的源码例子里面跳转的时候都没有这个正在加载的圆圈

**Comment by zhangjing123** [comment]
@py389172739 我也是做原生android的，能请教下打包方面的一些问题吗 q2453480777

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
