### ISSUE TITLE
官方examples里面的vue的例子tabbar.vue问题咨询

### ISSUE THREAD

**Issue by py389172739** [alibaba/weex#2991]
我是做安卓的应用，在看了官方的examples里面的vue的例子tabbar.vue后，在使用过程中发现
` <embed
      v-for="item in tabItems"
      :src="item.src"
      type="weex"
      :style="{ visibility: item.visibility }"
      class="content"
      ></embed>`
使用embed标签时如果内部使用了v-for就渲染不出来，我只好写好几个<embed>标签，然后我想通过visibility控制显示和隐藏，但是好像不起作用，每次都会全部渲染出来，而且tabitem切换也不起作用，无法切换(我查了一下embed是h5的标签，里面没有visility的属性，这个是自定义的属性吗？h5中embed有hidden属性，但是设置后在android上也不起作用)，后来我用v-if控制的显示和隐藏，但是每次切换的时候都会渲染页面，感觉体验不好，请问如果用vue写这种tabitem控制页面切换，还有更好的办法吗?
还有一种思路：vue中有一个keep-alive的特性 + 动态组件好像可以实现这种切换并缓存页面，第二次之后的切换就只是显示和隐藏了，但是我加了keep-alive之后，页面就渲染不出来了，变成空白了，去掉keep-alive可以渲染出来，但是并没有缓存页面

还有一个疑问？我在看官方的tabbar.vue例子源码的时候发现切换item的时候，切换的src是这种的：
'component/tabbar/tabbar-item.js?itemId=tab1',
'component/tabbar/tabbar-item.js?itemId=tab2',
'component/tabbar/tabbar-item.js?itemId=tab3',
请问这种在js后面带参数是怎么弄的 ? 切换的时候对应的不应该是每个填充页面内容的js文件吗？怎么是这种tab-item.js结尾的文件呢，有点疑惑

**Comment by hanliuxin5** [comment]
可以参考一下这个项目的思路
https://github.com/hanliuxin5/ControllerView

**Comment by wqjGitHub** [comment]
Vue  我组要在web端使用tabbar组件，但是demo中的那个tabbar在web端不适应，怎么实现一个在embed的web组件，weex本身提供的wxc-tabbar中的embed编译后在web中显示的div。我需要在Vue中也实现一个这样子的web compoent

**Comment by totzcc** [comment]
@hanliuxin5 主要是在H5上不支持.这个是Android拓展了一个View组建吧?

**Comment by totzcc** [comment]
我解决了在H5 不能显示的问题. 同时兼容 iOS 和 Android

https://github.com/totzcc/weex-tabbar

**Comment by bsed** [comment]
哈哈，

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
