### ISSUE TITLE
相同的代码在playground里面没有问题，集成到iOS中就会出现崩溃

### ISSUE THREAD

**Issue by MGXu** [alibaba/weex#2994]
这里的代码：http://dotwe.org/weex/ec8c6ad3fcea258dd14e410e6b1c686b
修改了请求接口和参数能够请求到数据，但是集成到iOS中点击请求按钮就会崩溃，
[WXStreamModule fetch:callback:progressCallback:]
Thread1:EXC_BAD_ACCESS(code =1,address=0x10)

**Comment by MGXu** [comment]
重新导入库就好了。。。

**Comment by pranshuagrawal** [comment]
Hi @MGXu 
I am facing this exact same issue. Can you please help me telling that which Library did you re-import? How did you fix this?
