### ISSUE TITLE
普通的js文件是怎么转换成bundlejs的?

### ISSUE THREAD

**Issue by py389172739** [alibaba/weex#2999]
我的src里面是用vue写的，里面有js文件，比如app.js

`import App from './pages/home/index.vue';
import router from './router';
new Vue(Vue.util.extend({ el: '#root', router}, App));

在编译的过程中这个app.js是用什么loader加载编译的，我看webpack里的配置文件中js文件使用'babel-loader'处理的，但是怎么转换之后的js是这样的：

`/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}

/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ (function(module, exports) {

	import App from './pages/home/index.vue';
	import router from './router';
	new Vue(Vue.util.extend({ el: '#root', router}, App));

/***/ })
/******/ ]);`

这个肯定不对，请问如何才能正确转换app.js这个文件呢？是使用weex-loader吗？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
