### ISSUE TITLE
如何实现点击list的某一个item，用动画缩小该div，放手之后还原这种效果？

### ISSUE THREAD

**Issue by beghujam** [alibaba/weex#3000]

**Comment by Alimjan2009** [comment]
提供一下demo

**Comment by beghujam** [comment]
<list class="wl-list">
        <cell class="wl-cell" v-for="item in lists">
          <div class="wl-div-box">
            <div class="wl-div-item" :ref="item.id" @touchstart="touchstart(item.id)" @touchend="touchend(item.id)" @click="clickitem(item.id)">
              <image v-if="show_left" class="wl-img-icon wl-img-left" :src="item.icon"></image>
              <text v-if="showtxt" class="wl-txt-title wl-ug">{{item.name}}</text>
              <image v-if="show_right" class="wl-img-icon wl-img-right" :src="item.icon"></image>
            </div>
          </div>
        </cell>
      </list>

touchstart: function (id) {
      var animation = weex.requireModule('animation') || {};
      var target = self.$refs[id];
      console.log(target);
      var action1 = 'scaleX(0.9)';
      var action2 = 'scaleY(0.9)';
      var options = {
        styles: {
          transform: action1 + action2
        },
        duration: 300
      };
      var callback = function () {
      };
       animation.transition(target, options, callback);
    }
如上是代码，var target = self.$refs[id]; 可以获取控件，但是动画不能执行

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
