### ISSUE TITLE
WXImage的load命令回调默认实现存在兼容问题

### ISSUE THREAD

**Issue by HJ-Money** [alibaba/weex#3001]
首先，我在ImageAdapter加载图片方案修改成Glide。

然后，在WXImage处理load命令的默认实现中：
```
imageStrategy.setImageListener(new ImageListener() {
            public void onImageFinish(String url, ImageView imageView, boolean result, Map extra) {
                if(WXImage.this.getDomObject() != null && WXImage.this.getDomObject().getEvents().contains("load")) {
                    HashMap params = new HashMap();
                    HashMap size = new HashMap(2);
                    if(imageView != null && imageView.getDrawable() != null && imageView.getDrawable() instanceof ImageDrawable) {
                        size.put("naturalWidth", Integer.valueOf(((ImageDrawable)imageView.getDrawable()).getBitmapWidth()));
                        size.put("naturalHeight", Integer.valueOf(((ImageDrawable)imageView.getDrawable()).getBitmapHeight()));
                    } else {
                        size.put("naturalWidth", Integer.valueOf(0));
                        size.put("naturalHeight", Integer.valueOf(0));
                    }

                    if(WXImage.this.getDomObject() != null && WXImage.this.containsEvent("load")) {
                        params.put("success", Boolean.valueOf(result));
                        params.put("size", size);
                        WXImage.this.fireEvent("load", params);
                    }
                }

            }
        });
```

可以看到，imageView.getDrawable() 进行了判断，如果不是ImageDrawable，宽高就是0，0。然而，Glide返回的Drawable都是GlideBitmapDrawable类型，导致宽高传回来的值都是不正确。

个人认为，此处不应该强行判断Drawable必须是ImageDrawable，其他类型都可以，只要是Drawable即可，宽高用Drawable.getIntrinsicWidth和getIntrinsicHeight获取。这样可以兼容更多图片加载库。

**Comment by acton393** [comment]
@HJ-Money   建议可以提pr 做修改下

**Comment by HJ-Money** [comment]
@acton393 请问是在这里提pr还是在https://github.com/apache/incubator-weex那边提？

**Comment by misakuo** [comment]
这里的本意是要返回图片的原始大小，0.13版本已针对非ImageDrawable类型的Drawable做了兼容

**Comment by acton393** [comment]
@HJ-Money 在apache 那边仓库提的~~

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
