### ISSUE TITLE
<iOS> 如何扩充weex的网络请求

### ISSUE THREAD

**Issue by ZeroJson** [alibaba/weex#3005]
之前我重写过WXNetworkProtocol的sendRequest方法来实现增加请求头的内容的，现在我那怎么做

**Comment by acton393** [comment]
可以描述扩充具体点么？

**Comment by ZeroJson** [comment]
@acton393 添加一个请求头 把位置信息放在请求头里面

**Comment by acton393** [comment]
hi @ZeroJson  可以直接在stream  option 字段设置

**Comment by ZeroJson** [comment]
@acton393  我是iOS开发，能不能告诉我在那个类添加请求头。

**Comment by acton393** [comment]
@ZeroJson 不需要在native的代码里面添加， js中调用stream 的地方，直接可以添加header

**Comment by motcwang** [comment]
网络请求，如果有特殊需求，那可以自己封装`module`，不是一定要用`stream`。

**Comment by ZeroJson** [comment]
@motcwang 对 我之前也是封装的module 但是现在更新了sdk，不知道该如何下手了，对WXResourceRequestHandler的- (void)sendRequest:(WXResourceRequest *)request withDelegate:(id<WXResourceRequestDelegate>)delegate方法进行处理，添加请求头，但是请求不到东西了，页面都打不开，一片空白。可不可以告诉我 如何处理。

**Comment by motcwang** [comment]
@ZeroJson 不好意思，iOS更新后我还没看过，暂时帮不了你。

**Comment by ZeroJson** [comment]
@motcwang 好吧，谢谢

**Comment by ZeroJson** [comment]
@acton393  你有办法吗

**Comment by acton393** [comment]
@ZeroJson  可以参考看下stream如何调用的，暂时没理解你的问题在哪边..

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
