### ISSUE TITLE
First view wrong height for iOS

### ISSUE THREAD

**Issue by enricodeleo** [alibaba/weex#3012]
Hi everyone,

playing with weex today (finally!) I found an unexpected behaviour: when I run the app on iOS (no matter the content) the first view's height is wrong 

![image](https://cloud.githubusercontent.com/assets/3534555/25599432/7898b162-2edc-11e7-935a-60c087db062b.png)

On apps that don't use router-view the issue disappears changing the view and even the first view became full-sized when I come back to it.

Any ideas?

**Comment by acton393** [comment]
hi  @enricodeleo  the container for missing height is just  the navigation bar which you hide it,   you can set the 
 `instance.frame` to change the current container Height

**Comment by enricodeleo** [comment]
thank you @acton393 I supposed that at first, but got confused seeing the height is calculated correctly on other views.
Is there any "weex way" to achieve the goal or should I have to change the source generated in `platforms/ios`?

**Comment by acton393** [comment]
hi @enricodeleo  if it only occurs on your first view, maybe you can check your `list/scroller` height in css value, you can also use [devtool](https://github.com/weexteam/weex-devtool) inspecting the views, as you must integrate it into your app at first.

**Comment by enricodeleo** [comment]
@acton393 it was one of my trial but even if the height is returned correctly from the `weex` object and I bind that height to the container nothing changes. Instead, removing the `-64` from `WXDemoViewController.m` solved the issue (even if not so portable since I need to re-edit that file whenever add the platform again).

Thank you for your help!
