### ISSUE TITLE
ios tabbar中添加了背景之后，中间会出现白线，请问是什么原因

### ISSUE THREAD

**Issue by coderminer** [alibaba/weex#3015]
ios tabbar中的每个item添加了背景颜色之后，在真机的显示效果会出现两个白线，ios版本有此问题，android显示是正常的

![result](https://cloud.githubusercontent.com/assets/22041739/25742546/84c5117c-31c2-11e7-8db5-615f54a875e1.png)

**Comment by acton393** [comment]
@coderminer 猜测 应该是浮点数误差的问题

**Comment by coderminer** [comment]
@acton393  有什么解决的方案吗？

**Comment by acton393** [comment]
@coderminer 尝试下你的css value 改变看下

**Comment by bsed** [comment]
you can change css width value

**Comment by beghujam** [comment]
请问下你的tabbar是用we文件写的还是vue写的，我用vue写了 展示不出来

**Comment by doyouno** [comment]
能分享一下源码吗？我这里tabbar设置为fix bottom 0 在ios里不是最底部。

**Comment by coderminer** [comment]
@beghujam 我是we写的，还没有转到vue

**Comment by coderminer** [comment]
@doyouno tabbar 本来不就是在底部吗？？

**Comment by doyouno** [comment]
我用了example里面的vue，就是这个效果，没在底部，坑

发自我的 iPhone

在 2017年6月29日，19:34，矿工 <notifications@github.com<mailto:notifications@github.com>> 写道：


@doyouno<https://github.com/doyouno> tabbar 本来不就是在底部吗？？

**Comment by coderminer** [comment]
@doyouno  参考一下 https://github.com/coderminer/GankIO_weex

**Comment by coderminer** [comment]
@beghujam 参考一下 https://github.com/coderminer/GankIO_weex

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
