### ISSUE TITLE
[提问] Android如何通过代码回到上一级页面

### ISSUE THREAD

**Issue by XImoon** [alibaba/weex#3022]
Android加载vuejs，因为想采用Fragment和viewpager+底部tab的页面结构，所以back键点击需要触发Fragment的页面回退。但是在Fragment无法找到效果等同于Activity的onBackPressed的方法，而且WXSDKInstance设定了INSTANCE_ID但无法回到指定id的页面。如何在Fragment通过代码回退上一级页面，类似于webview的webview.goback？

**Comment by zk0301** [comment]
安卓这边拦截返回键，给js发送fireglobalEvent("clickback" , map);  js自己判断是不是root，
如果是root，调用android的module.finish();
如果不是root,js自己goback

**Comment by XImoon** [comment]
经过实验，
Android端：
        mWXSDKInstance.fireGlobalEventCallback("clickback" , null);
weex端：
        var globalEvent = weex.requireModule('globalEvent');
        globalEvent.addEventListener("clickback", function(e) {
            navigator.pop()
        });

可以达到目的。
因为是单页面模式，因此可以注册在全局的template如navigation bar中

**Comment by XImoon** [comment]
经过实验，
Android端：
        mWXSDKInstance.fireGlobalEventCallback("clickback" , null);
weex端：
        var globalEvent = weex.requireModule('globalEvent');
        globalEvent.addEventListener("clickback", function(e) {
            navigator.pop()
        });

可以达到目的。
因为是单页面模式，因此可以注册在全局的template如navigation bar中

**Comment by XImoon** [comment]
如果是root，调用android的module.finish();
如果不是root，js自己goback

这里，如果是root的话，android利用register的module（WXModule）添加finish方法退出App；
如果不是root，js自己goback是采用history.back(-1)吗？

**Comment by zk0301** [comment]
我是做安卓的， js是同事写的，我看他的代码好像是_router2.default.back();    我也看不懂。。。

**Comment by XImoon** [comment]
我查了一下，是通过vuejs的route去配制相关信息，和android的ViewRootImpl的某些东西比较相似

**Comment by py389172739** [comment]
@XImoon  你好请问你是如何实现Fragment和viewpager+底部tab的页面结构的？我现在也有这样一个场景，用的是动态组件之间的切换，但是两个fragment的切换的时候老是有重叠然后正常的情况，不知道怎么解决好

**Comment by zk0301** [comment]
py389172739 我用的是老式TabActivity，tabhost+activity。没有重叠的问题。weex那么脆弱的东西，还用fragment，哇咔咔咔。

**Comment by XImoon** [comment]
我用的是fragmentList结合adapter和position的形式，在测试过程中没有发现有问题。因为使用vuejs_router回退需要改js，所以放弃了fragment+tab的方式。

**Comment by py389172739** [comment]
@zk0301  @XImoon  原来你们是用安卓原生的控件实现的，我以为能用weex实现，我还想着能不能用weex实现呢？还有，@zk0301，weex很脆弱嘛，我还想着整个应用用weex开发呢

**Comment by zk0301** [comment]
@py389172739 我们公司采用weex和vue做了3个项目了。 各种坑。还不够稳定，再等几个版本吧。。。

**Comment by Tomdoog** [comment]
啊 请问怎么在fragment中加载 js 页面，文档里只有activity的示例。。。。。。。哪位大佬能帮帮我 感激不尽

**Comment by XImoon** [comment]
@Tomdoog  和activity没啥区别呀

**Comment by Tomdoog** [comment]
@XImoon  嗯嗯 我现在搞出来了 谢谢回复~  对了 你现在也在用weex做项目吗

**Comment by reverseAndroid** [comment]
@XImoon 你好，问一下，现在我遇到的问题是 js页面从A跳转到B，从B跳转到C，从C跳转到D，然后点击返回，D返回上一页到C，正常，但是再从C返回到B，就直接把B跳过了，会直接跳转到A，我打印log看了下，js这边会在点击back键时，在每个页面都运行globalEvent这个监听，这块你是怎么解决的？

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
