### ISSUE TITLE
我想在weex里面使用vue的UI框架

### ISSUE THREAD

**Issue by acodercat** [alibaba/weex#3023]
import MuseUI from 'muse-ui'
我这样引入以后程序没有错误提醒，但是打不开。

**Comment by qifenshu** [comment]
if u keep using vue-ui, ur app will lost cross ability. h5 ui cant math android and ios componect.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
