### ISSUE TITLE
vue-router和weex-router有什么区别，都只能用在web端吗？

### ISSUE THREAD

**Issue by 501956430** [alibaba/weex#3024]
vue-router和weex-router 是不是都只能用在web 不能用在native的？
现在想做个tab切换的效果，每个tab内容是独立的vue,native端应该有什么组件可以实现？
有个人说用vue-router和vue动态组件，好像只能用在web端啊

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
