### ISSUE TITLE
stream.fetch 函数在option.method=="get" 请求无 body 时，url 后面会添加 undefined

### ISSUE THREAD

**Issue by newdefence** [alibaba/weex#3027]
很明显，下面的代码如果 body 没有传入，则在 url 中会出现 undefined  
  // validate body content for method 'GET'.
    if (config.method.toUpperCase() === 'GET') {
      var body = config.body;
      if (utils.isPlainObject(body)) {
        body = index.stringify(body);
      }
      var url = config.url;
      var hashIdx = url.indexOf('#');
      hashIdx <= -1 && (hashIdx = url.length);
      var hash = url.substr(hashIdx);
      hash && (hash = '#' + hash);
      url = url.substring(0, hashIdx);
      url += (config.url.indexOf('?') <= -1 ? '?' : '&') + body + hash;
      config.url = url;
    }

**Comment by 452MJ** [comment]
@newdefence 哥们，有办法解决吗

**Comment by bsed** [comment]
移除掉啊。

**Comment by newdefence** [comment]
body 写一个空字符串即可；
这里只是建议 修改bug

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
