### ISSUE TITLE
slider在web版有问题，添加了点击事件一直不进入该事件，点击图片自动滚动，每点击一次就滚动一次就不进入点击事件，而且第一个图片空白，图片不显示

### ISSUE THREAD

**Issue by beghujam** [alibaba/weex#3028]
<slider class="slider" interval="3000" auto-play="true" @change="sliderChange">
      <div class="frame" v-for="img in imageList">
        <image class="image" resize="cover" :src="img.src" @click="click"></image>
      </div>
    </slider>

click:function(){
          console.log('click');
          // this.text = 'img=='+this.eventCnt
          var version = weex.config.env.weexVersion;
         this.text = 'img=='+version
        }

**Comment by MrRaindrop** [comment]
可以参考一下这个例子：http://dotwe.org/vue/2fadefbe5a946125000f3991e234f9a0 点击图片，可以看到响应，并且下面的提示会指出点击的是第几张图片

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
