### ISSUE TITLE
android video在scoll里面

### ISSUE THREAD

**Issue by zk0301** [alibaba/weex#3031]
奇怪的现象，当scrollview滚动的时候，video的控制器mediacontroller会悬浮起来，脱离videoview。

= =！

**Comment by zk0301** [comment]
想了个办法，抓scroll的滚动事件，给wxvideo添加一个属性hide。当滚动事件的时候，设置这个hide，把mediacontroller隐藏掉。

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
