### ISSUE TITLE
weex vue2 不支持 v-html, 如何通过其他方式实现相同功能

### ISSUE THREAD

**Issue by xiaogaofudao** [alibaba/weex#3032]
求助个问题，weex vue2 不支持 v-html, 如何通过其他方式实现相同功能。
iconfont 使用 遇到这个问题

**Comment by SphinxVon** [comment]
这个问题最后解决了吗

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
