### ISSUE TITLE
android home windows

### ISSUE THREAD

**Issue by des1roer** [alibaba/weex#3033]
i try use this tutor

https://hackernoon.com/how-to-create-a-weex-vue2-project-6b94981bee4e

but i have

![image](https://cloud.githubusercontent.com/assets/10970793/26527708/2dcb8c4a-43b3-11e7-9141-7c875e8a05ca.png)
![image](https://cloud.githubusercontent.com/assets/10970793/26527722/69e97804-43b3-11e7-930c-eea0cc48fbb6.png)

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
