### ISSUE TITLE
有哪位大神用vue写过tabbar的demo吗，我写了但是不知道哪里出错，没能展示出来

### ISSUE THREAD

**Issue by beghujam** [alibaba/weex#3039]
<template>
  <div style="flex-direction: column;">
    <tabbar :tabItems="tabItems" @tabBarOnClick="tabBarOnClick"></tabbar>
  </div>
</template>
<script>
  var getBaseURL = require('../include/base-url.js').getBaseURL
  module.exports = {
    data: function () {
      return {
        dir: 'examples',
        tabItems: [
          {
            index: 2,
            title: 'tab3',
            titleColor: '#000000',
            icon: '',
            image: 'http://gtms01.alicdn.com/tps/i1/TB1B0v5MpXXXXcvXpXX9t7RGVXX-46-46.png',
            selectedImage: 'http://gtms04.alicdn.com/tps/i4/TB1NxY5MpXXXXcrXpXX9t7RGVXX-46-46.png',
            src: 'component/tabbar/tabbar-item.js?itemId=tab3',
            visibility: 'hidden',
          }
        ],
      }
    },
    components: {
      tabbar: require('../include/tabbar.vue')
    },
    created: function() {
      var baseURL = getBaseURL(this)
      for(var i = 0; i < this.tabItems.length; i++) {
        var tabItem = this.tabItems[i];
        tabItem.src = baseURL + 'http://60.13.131.106:8899/boghda/build/home_nav.js';
      }
},
    methods: {
    }
  }
</script>

**Comment by coderminer** [comment]
参考一下  https://github.com/coderminer/GankIO_weex

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
