### ISSUE TITLE
weex-vue-render 更新到 weex-vue-render@^0.11.2版本，界面默认宽度就不是750px了吗？ 设置750px 就不对了呀超出边缘了，是h5测试的

### ISSUE THREAD

**Issue by beghujam** [alibaba/weex#3043]
代码如下 

<template>
  <div  class="row" style="padding: 5px; ">
    <div class="dvi">
    </div>
  </div>
</template>
<style>
.row{
  width: 720px;
  height: 750px;
background-color:#0ff;
}
.dvi{
  flex: 1;
  background-color: #f0f;
  width: 600px;
}
</style>
<script>
</script>

**Comment by cb269267** [comment]
我的也是这样，我用的0.11.44版本，也是左侧和顶部有十来像素的留白，主体部分被顶到了右下方向

**Comment by beghujam** [comment]
这个问题解决了，解决方法：在index.html 添加
<style>
  html, body, #weex {
      width: 100%;
      height: 100%;
    }
    html, body {
      -ms-overflow-style: scrollbar;
      -webkit-tap-highlight-color: transparent;
      padding: 0;
      margin: 0;
      width: 100%;
      height: 100%;
      overflow-x: hidden;
    }
  </style>

**Comment by motcwang** [comment]
我在`index.html`里面加了，还是不好用，我的版本是`0.12.16`，不知道有没有什么解决办法

**Comment by motcwang** [comment]
是我自己webpack配置的问题，`options`中要增加如下配置
```
compilerModules: [
        {
            postTransformNode: el => {
                el.staticStyle = `$processStyle(${el.staticStyle})`
                el.styleBinding = `$processStyle(${el.styleBinding})`
            }
        }
    ]
```

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
