### ISSUE TITLE
weex run android提示Environment variable $ANDROID_HOME not found

### ISSUE THREAD

**Issue by qq511340079** [alibaba/weex#3049]
在项目下执行weex run android的时候提示
Environment variable $ANDROID_HOME not found
You should set $ANDROID_HOME first
我已经把ANDRID_HOME配置到sdk目录了呀！

**Comment by 766** [comment]
Open the terminal and type :

export ANDROID_HOME=/Applications/ADT/sdk
Add this to the PATH environment variable

export PATH=$PATH:$ANDROID_HOME/bin
If the terminal doesn't locate the added path(s) from the .bash_profile, please run this command

source ~/.bash_profile

Hope it works to you!

**Comment by mhpm** [comment]
please help! i have the same issue on windows, im using visual code, when i run the command: weex run android.  
resulte:
Environment variable $ANDROID_HOME not found !
You should set ANDROID_HOME in your environment first.
See https://spring.io/guides/gs/android/
'adb' is not recognized as an internal or external command,
operable program or batch file.
'adb' is not recognized as an internal or external command,
operable program or batch file.
The batch file cannot be found.

**Comment by LynanBreeze** [comment]
@mhpm Got the same issue. First try with weex and I have already had Android Studio installed and set the environment variable right. Guessing the problem comes from '$' For environment variable starts with '%'.

Just guessing.

**Comment by sudarshanc** [comment]
@mhpm  Just restart command prompt after adding paths

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
