### ISSUE TITLE
[iOS]<text/>不能根据props接收到的内容长度自动换行

### ISSUE THREAD

**Issue by 452MJ** [alibaba/weex#3051]
@acton393 英语太渣。这么说吧，我要做一个弹幕列表，弹幕内容长度是不确定的，所以text要自适应内容长度，然后我发现在iOS上并不能自适应宽度（在android上是可以达到预期效果的），无论我设置了
```
lines:0;
max-height:300px
```
在iOS上都不成功，只有将高度写死比如height:500px的情况下才能显示出多行内容。

![image](https://user-images.githubusercontent.com/13673008/27679780-49c3490e-5cec-11e7-8ecd-2668202c9d6d.png)

**Comment by 501956430** [comment]
text 默认应该是会自动换行的,可能由你的布局影响的

**Comment by 452MJ** [comment]
@501956430 可能吧，明天我再检查检查

**Comment by 452MJ** [comment]
`danmuWidth="(danmu.content.length + 0) * px_12 > px_360 ? px_360 : (danmu.content.length + 1) * px_12"`

解决了iOS不能自动换行的问题，通过计算

width = danmu.length * font-size

来动态设置不同长度弹幕的text宽度
