### ISSUE TITLE
在weex scroller设置了横向滑动属性scroll-direction="horizontal"后，在safari打开 不显示，在chrome浏览器可以，iPhone微信打开也不现实，Android的微信可以

### ISSUE THREAD

**Issue by beghujam** [alibaba/weex#3055]

**Comment by beghujam** [comment]
<scroller scroll-direction="horizontal" show-scrollbar="false" class="expert-main">
  <div class="ei-div">
    <div class="ei-div-book" v-for="(item, index) in book_data.items" :ref="'item'+index" @click="click_book(index)">
      <image class="ei-book-image" :src="item.img"></image>
      
      <div class="ei-div-text mar-top">
        <text class="ei-book-name">{{item.name}}</text>
        <text class="ei-book-author">{{item.author}}</text>
        <div class="ei-div-prece">
          <text class="ei-book-price-new ei-price-rmb-right">¥</text>
          <text class="ei-book-price-new">{{item.price_new}}</text>
          <div class="ei-div-price-old">
            <text class="ei-book-price-old">{{item.price_old}}</text>
            <div class="ei-div-line-center"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

**Comment by beghujam** [comment]
代码如下：`<scroller scroll-direction="horizontal" show-scrollbar="false" class="expert-main">
  <div class="ei-div">
    <div class="ei-div-book" v-for="(item, index) in book_data.items" :ref="'item'+index" @click="click_book(index)">
      <image class="ei-book-image" :src="item.img"></image>
      
      <div class="ei-div-text mar-top">
        <text class="ei-book-name">{{item.name}}</text>
        <text class="ei-book-author">{{item.author}}</text>
        <div class="ei-div-prece">
          <text class="ei-book-price-new ei-price-rmb-right">¥</text>
          <text class="ei-book-price-new">{{item.price_new}}</text>
          <div class="ei-div-price-old">
            <text class="ei-book-price-old">{{item.price_old}}</text>
            <div class="ei-div-line-center"></div>
          </div>
        </div>
      </div>
    </div>
  </div>`

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
