### ISSUE TITLE
swipe和click事件冲突

### ISSUE THREAD

**Issue by fengqingxiuyi** [alibaba/weex#3058]
现象：一个item具有左滑删除和点击跳转的功能，现在想要实现左滑删除的功能，我使用了swipe事件，但是同时也触发了click事件，导致问题发生

**Comment by fengqingxiuyi** [comment]
通过event.type判断

**Comment by FelixXG** [comment]
event.type这个怎么判断?连事件都没有触发

**Comment by fengqingxiuyi** [comment]
你注册事件了吗

**Comment by FelixXG** [comment]
在div下写了相关事件@swipe和@click事件，但是此时只会触发click事件，要触发swipe事件，就要把click事件去掉才行。

**Comment by fengqingxiuyi** [comment]
@FelixXG 抱歉抱歉，后来发现swipe和click事件的确有你说的问题，然后通过另一种方式解决了：注册touchstart和touchend，在touchstart事件中记录起始点击位置，在touchend事件中记录结束点击位置，然后判断两个值的大小，如果相等则是点击事件，否则就是滑动事件，不过可能不适合你的业务场景。

**Comment by FelixXG** [comment]
行,不管怎么样,还是感谢你的耐心解答,谢谢。
