### ISSUE TITLE
define self-defined Compone extentds WXComponent whereas empty result

### ISSUE THREAD

**Issue by cableyang** [alibaba/weex#3061]
/****************************************************************************
     **************************   JAVA FILE HERE  ******************************
****************************************************************************/
public class MyTabMenu extends WXComponent<View> {

    public MyTabMenu(WXSDKInstance instance, WXDomObject dom, WXVContainer parent) {
        super(instance, dom, parent);
    }

    @Override
    protected View initComponentHostView(@NonNull Context context) {
        View rootView = LayoutInflater.from(context).inflate(R.layout.myview_layout,null);
        return rootView;
    }
    @WXComponentProp(name = "msg")
    public void setMsg(String msg){
        Log.e("cable",msg);
    }
}

`/****************************************************************************
     **************************   LAYOUT FILE HERE  ******************************
****************************************************************************/
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:id="@+id/ll"
    android:layout_width="300dp"
    android:layout_height="300dp">
    <TextView
        android:padding="8dp"
        android:textColor="#444444"
        android:text="Tab1"
        android:textSize="16sp"
        android:id="@+id/tv"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
</LinearLayout>`

/****************************************************************************
     **************************   VUE File below ******************************
****************************************************************************/
      <mytabmenu msg="test">tab</mytabmenu>

HERE IS MY CONTACT INFO :Wechart: 15295508253 PLZ help ME

**Comment by cableyang** [comment]
/****************************************************************************
     **************************   LAYOUT FILE HERE  ******************************
****************************************************************************/
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:id="@+id/ll"
    android:layout_width="300dp"
    android:layout_height="300dp">
    <TextView
        android:padding="8dp"
        android:textColor="#444444"
        android:text="Tab1"
        android:textSize="16sp"
        android:id="@+id/tv"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
</LinearLayout>

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
