### ISSUE TITLE
android weexSDK应该支持各版本的.so文件

### ISSUE THREAD

**Issue by allanhuang1109** [alibaba/weex#3070]
目前weex只提供了armeabi和x86的so，通过增加abiFilters "armeabi", "armeabi-v7a", "x86"之后能支持64位的手机，但是如果引入其他第三方库的so文件就有问题，会强制其他第三方的库也会强制加载这 "armeabi", "armeabi-v7a", "x86"三种库，放弃其他版本so。作为一个开源SDK，支持全平台更符合自身定位，用户想输出哪些APK由它们自己选择。

**Comment by jasonhe88** [comment]
强烈赞成

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
