### ISSUE TITLE
How can i transform it from weex init to weex create?

### ISSUE THREAD

**Issue by LinShouGui** [alibaba/weex#3072]
current project :
--package.json
--index.html
--webpack.config.js
--.babelrc
--.eslintrc
--.gitignore
--README.md
--node_modules
--dist
         ----index.web.js
         ----index.weex.js
--src
         ----components
         ----mixins
         ----router
         ----store
         ----app.js
         ----App.vue

Now i want to transform the vue project which is created by weex init to android project,
but as far as i know, i have to use weexpack to reach the goal.However,the weexpack accept the project which is created by weex create.How can i do ?

- 

- 

1.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
