### ISSUE TITLE
<slider>组件设置了auto-play后安卓端不会循环轮播，播放到最后一张图片就停住了。

### ISSUE THREAD

**Issue by JenningFan** [alibaba/weex#3073]
IOS端则可以循环轮播

**Comment by neo198603** [comment]
这个需要根据视图的可见性动态设置，可见的时候设置为true，不可见的时候设置为false，可以解决。

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
