### ISSUE TITLE
Android 中 console.log 输出看不到

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#3074]
我用的是weex sdk 0.13.0

在Android Sutdio中死活看不到 javascript 中 console.log 输出的信息，用了 Verbose 也不行

有碰到同样问题的吗？

**Comment by jasonhe88** [comment]
用weex devtool可以看到了

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
