### ISSUE TITLE
ios image组件图片下载失败时，没有清空UIImageView

### ISSUE THREAD

**Issue by majunhui** [alibaba/weex#3079]
在代码WXImageComponent.m的updateContentImageWithFailedBlock方法中，失败时没有清空UIImageView，导致如果在list组件中使用image组件，当原来cell有图片，更新数据后新数据对应image地址图片刷新失败的话，还是现实老数据的图片，正常应该显示为空，代码如下：
                    if (error) {
                        downloadFailedBlock(imageSrc, error);
                        [strongSelf readyToRender];
                        return ;
                    }
我自己改为
//                        [strongSelf readyToRender];
                        if ([strongSelf isViewLoaded]) {
                            ((UIImageView *)strongSelf.view).image = nil;
                            [strongSelf readyToRender];
                        } else if (strongSelf->_isCompositingChild) {
                            strongSelf->_image = nil;
                            [strongSelf setNeedsDisplay];
                        }
                        return ;
就正常了

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
