### ISSUE TITLE
头疼的Scroller/List refresh/loading 之我的解决办法

### ISSUE THREAD

**Issue by jasonhe88** [alibaba/weex#3085]
折腾refresh/loading很头疼，最后我的解决办法如下，期望有更好的方案：

首先发现这些事实: 

1. 要想有拉动回弹效果，就必须加上refresh/loading
2. 安卓的 Display 属性必须成对出现， 就是 'show' : 'hide'  (文档里说明了)
3. iOS里Dispaly属性可以不用成对出现，这个意外解决了一个问题： 在iOS里数据不满一屏时拉动会跳动，没法用，但是把refreshing / loading 固定设为 'hide' 就没有跳动效果
4. @refresh 事件没有问题
5. list上的@loadmore 事件似乎和 loading上的@loading 事件冲突， 用loading的话就不能用list上的loadmore 事件， 不用loading的话见第一条
6. 用@loading的不好的地方就是松手时才会触发， 不像@loadmore到一定offset就会触发
7. 对于refresh/loading里面元素的显示/隐藏太难搞，索性不要，自己写个头尾

基于以上事实，我同时用了refresh 和 loading ，自己写提示头尾。用@refresh 和 @loading 事件
对于Display属性, 安卓写 show/hide, ios 写死hide

抛砖引玉， 请指正！

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
