### ISSUE TITLE
运行npm run dev命令，报missing script: dev的错误。

### ISSUE THREAD

**Issue by yoni520** [alibaba/weex#3087]
配置完环境，准备运行项目时碰到了以下问题，请各位大哥指点一下。

WangYideMini:~ wangyi$ cd awesome-project
WangYideMini:awesome-project wangyi$ npm run dev
npm ERR! missing script: dev
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wangyi/.npm/_logs/2017-09-12T08_33_31_633Z-debug.log

**Comment by fwk1010** [comment]
没有这个脚本的，看package.json的scripts里有哪些命令

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
