### ISSUE TITLE
npm install得到的node_modules无法正常工作

### ISSUE THREAD

**Issue by 452MJ** [alibaba/weex#3088]
不少朋友也反应，不管是新项目旧项目，只要是npm install得到新的依赖库，都不能正常编译工作。用旧项目的node_modules替换掉的话就可以正常编译运行。

**Comment by 452MJ** [comment]
![1](https://user-images.githubusercontent.com/13673008/30510253-f1acf6bc-9af2-11e7-9275-59fdca03da25.jpg)
![Uploading 2.jpg…]()

**Comment by 452MJ** [comment]
![2](https://user-images.githubusercontent.com/13673008/30510264-24a15cb6-9af3-11e7-81d4-4f203ba46132.jpg)

**Comment by fwk1010** [comment]
同样的问题，是ERROR in index.web.js from UglifyJs这个错误。不知道怎么解决

**Comment by 452MJ** [comment]
@fwk1010 你这个是ES6的问题，搜一下es6转es5就解决了

**Comment by fwk1010** [comment]
@452MJ 不是啊，这是直接使用官方提供的weexpack生成的。理论上不会报错才对。而且几个月前是可以的。异常结果和你图中一致

**Comment by 452MJ** [comment]
@fwk1010 群里有人在webpack.config里面把这个UglifyJS插件注释掉后就没错误提示了，你可以试试

**Comment by rccoder** [comment]
`npm i vue@2.4.2 vue-template-compiler@2.4.2 -S`
@452MJ @fwk1010

**Comment by 452MJ** [comment]
@rccoder nice!!!!
