### ISSUE TITLE
<text>组件 在 ios 端 ,如果文字换行过多,会造成 text 组件底部大量留白

### ISSUE THREAD

**Issue by suanmei** [alibaba/weex#3090]
书写如下
\<text class="justify-center"\>
作曲 : 金玟岐
作词 : 金玟岐

吉他：薛峰
贝斯：郑骅骅
打击乐：王斌
能够握紧的就别放了
能够拥抱的就别拉扯
时间着急的
冲刷着
剩下了什么
原谅走过的那些曲折
原来留下的都是真的
纵然似梦啊 半醒着
笑着哭着都快活
谁让
时间是让人猝不及防的东西
晴时有风阴有时雨
争不过朝夕
又念着往昔
偷走了青丝却留住一个你
岁月是一场有去无回的旅行
好的坏的都是风景
别怪我贪心
只是不愿醒
因为你只为你愿和我一起
看云淡风轻
\</text\>

底部会有很大的留白，仅ios

**Comment by Yincongxiao** [comment]
+1

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
