### ISSUE TITLE
vue-class-component / typescript support?

### ISSUE THREAD

**Issue by schoening** [alibaba/weex#3092]
I would like to write my vue components in a [class based fashion](https://github.com/vuejs/vue-class-component):

```
import Vue from "vue"
import Component from "vue-class-component"

@Component
class MyComponent extends Vue {
    message = "Hello world!"
}
```

Has anyone gotten it to work this way or has any ideas how to make it work?

**Comment by Zaaksam** [comment]
@schoening This might help you.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
