### ISSUE TITLE
android中Scroller 嵌套 web 导致web组件无法滑动，自定义WebView也不行

### ISSUE THREAD

**Issue by zhuyonghao134123** [alibaba/weex#3093]

**Comment by weisiwu** [comment]
我也遇到了这个问题，情况是这样的:
在 scroller 标签中引用一些自定义组件，然后再加一个web标签引用网页，这个网页的高度较高。会出现web标签无法滚动的问题。

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
