### ISSUE TITLE
weex init项目中H5页面不适配， 在路由跳前是适配的跳转后就会出现不适配问题！ 刷新下页面又正常，不适配的情况下chrome审查元素，显示宽度750px，刷新后正常就显示414px，请大神指点！

### ISSUE THREAD

**Issue by Yuamo** [alibaba/weex#3095]
weex init项目中H5页面不适配，
在路由跳前是适配的跳转后就会出现不适配问题！
刷新下页面又正常，不适配的情况下chrome审查元素，显示宽度750px，刷新后正常就显示414px，请大神指点！

**Comment by zhangwenzw** [comment]
我也遇到这个问题了，你的解决没？

**Comment by Yuamo** [comment]
没有啊解决啊，等更新吧

**Comment by liealis** [comment]
你不适配的是什么内容就正常的div还是image？

**Comment by wax1026** [comment]
请参考这个问答：https://segmentfault.com/q/1010000012394781
