### ISSUE TITLE
weex 版本升级说明在哪 ？

### ISSUE THREAD

**Issue by xiaolongyuan** [alibaba/weex#3097]
https://weex.apache.org/cn/releasenote.html
 这里只有 0.13

**Comment by xiaolongyuan** [comment]
已经更新了  关掉

**Comment by gurisxie** [comment]
HI @xiaolongyuan ,thanks for watch weex ! Weex has joined apache, so we can discuss about weex on https://issues.apache.org/jira/projects/WEEX.

**Comment by chenzefeng09** [comment]
hi @gurisxie i'm told that i have no permission to login
![image](https://user-images.githubusercontent.com/7556537/31044019-b7c2d8fa-a58c-11e7-92c8-f9c63eee82be.png)
how can i discuss about weex on https://issues.apache.org/jira/projects/WEEX.  ?

**Comment by gurisxie** [comment]
@chenzefeng09   I'm sorry for that jira' user is not synchronized with github。 You need register one.
