### ISSUE TITLE
weex 集成是怎么弄？作为前端开发者也不懂啊？

### ISSUE THREAD

**Issue by vcxiaohan** [alibaba/weex#3098]
小白一个，没明白，weex 旨意在一套代码，可以打包成android 和iOS 的安装包了，那这里面还这么集成是什么意思呢？这样搞，不是还需要iOS 和android 分开搞两套？纯属请求解答，不是吐槽，望赐教！

**Comment by xiaoyong0312** [comment]
因为 android，iOS 是两个不同 的运行平台，比如ied 工具 idea，有 window版的，也有mac，Linux版的。weex 的一套代码是指 只需要用一套js代码实现，js 跑在 android，iOS上。你应该先搞清楚 类 weex 框架(还有 Facebook 的RN)。

做过java web开发嘛？给你举个简单的例子，
                    tomcat(解压版的)
                    |         |
        .bat启动       .sh 启动
可以把 android包 当作.bat，ios包 当作.ios， tomcat当作weex，
这种多平台运行一套核心代码。
其实，tomcat 这个例子举的也不十分确切，希望没有误导你。

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
