### ISSUE TITLE
请问Android JSCalllback.invoke中的数据有大小限制吗？

### ISSUE THREAD

**Issue by 1903514970** [alibaba/weex#3101]
我使用invoke方法，数据大的时候，js中的function方法接收不到回调。数据小的时候正常。
两次invoke，区别只有result的长度。

private void setResult(JSCallback callback, boolean success, String result, String msg) {
          if (callback != null) {
              HashMap<String, Object> map = new HashMap<>();
              map.put("state", success ? "success" : "error");
              try {
                  if (result.contains("Msg=")) {
                      map.put("result", result);
                  } else {
                      map.put("result", JSON.parse(result));
                  }
              } catch (Exception e) {
                  e.printStackTrace();
                  map.put("result", result);
              }
              map.put("msg", msg);
              callback.invoke(map);
          }
    }`

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
