### ISSUE TITLE
@click="update" not working in browser need @click.native to work

### ISSUE THREAD

**Issue by joseiriarte1982** [alibaba/weex#3102]
@click="update" not working in browser need @click.native to work, on the other hand @click.native not working on android. If someone can explain, since it would be good @click= worked for both. This issue I find it when creating a new project... Actually I dont know if it is an issue or there is something I should be aware...

**Comment by sushilparajuli** [comment]
I think this will help you. I got same issue and found that @click won't work on web with weex components.
<button @click="login" v-if="plafform ==='Web'" class="login-button"> Login Account </button>
    <text @click="login" class="login-button" v-else> Login Account </text>

data() {
      return {
        plafform: weex.config.env.platform,
       }
    }

**Comment by joseiriarte1982** [comment]
Thanks @sushilparajuli  it seems we;ll have to work around it until it is ready

**Comment by MrRaindrop** [comment]
@joseiriarte1982 Did you use [weex-vue-render](https://www.npmjs.com/package/weex-vue-render) in your web page? Check this demo here: http://dotwe.org/vue/863c4f6ba69d88094ecb980575a01f85.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
