### ISSUE TITLE
weex run ios后报错simList is not defined

### ISSUE THREAD

**Issue by yy0608** [alibaba/weex#3108]

**Comment by deot** [comment]
[here](https://github.com/weexteam/weex-pack/issues/133#issuecomment-338359426)

**Comment by dseeker** [comment]
have the same issue, adding let simList fixed
## Environment:
- weex -v   v1.1.0-beta.5
 - weexpack : v0.4.7-beta.11
 - weex-builder : v0.2.13-beta.2
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.5
- node -v: v8.8.0
- npm -v: 5.4.2

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
