### ISSUE TITLE
v-if或是vue-router在android下有个重新定位的过程

### ISSUE THREAD

**Issue by juneleaf** [alibaba/weex#3109]
当 v-if内部内容有多个元素的时候，特别是list，安卓上就会有一个刷新的过程，过程中可以看见原生控件重新定位的过程。
简书里有个解决方案是在created中hidden，然后mounted在visible，这样不会有抖动但是切换画面就会空白一个可见的时间
然而ios可能因为机制所以没有这个抖动过程，速度非常快
请问是自身代码问题，还是安卓机制上有这样的缺点

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
