### ISSUE TITLE
When I use Socket.io , there is an error on Android project "Render error : -2013"

### ISSUE THREAD

**Issue by RoyalDeveloper2015** [alibaba/weex#3110]
I used Socket.io for Vue named "Vue-socket.io"

like this .

import VueSocketio from 'vue-socket.io';
Vue.use(VueSocketio, 'http://localhost:3000');

and compile with this command 

weex compile src dest
and copy the index.js file to android assets folder and run the android project.

E/jsengine:  ReportException : Exception: ReferenceError: Can't find variable: document
                                                            doPoll@(global function):172:45945
                                                            poll@(global function):172:15991
                                                            doOpen@(global function):172:15460
                                                            open@(global function):172:9418
                                                            open@(global function):172:39466
                                                            n@(global function):172:37998
                                                            n@(global function):172:36043
                                                            connect@(global function):172:21184
                                                            n@(global function):172:19606
                                                            n@(global function):172:18848
                                                            n@(global function):172:66442
                                                            t@(global function):172:31420
                                                            install@(global function):172:29806
                                                            use@(weex framework):2:29966
                                                            (global function):133:9
                                                            __webpack_require__@(global function):23:34
                                                            (global function):58:39
                                                            __webpack_require__@(global function):23:34
                                                            (global function):43:37
                                                            (global function):44:12
                                                            anonymous@(global function):199:4
                                                            a@(weex framework):3:30112
                                                            (weex framework):8:22648
10-27 05:27:52.486 32123-32137/com.alibaba.weex E/weex: reportJSException >>>> instanceId:1, exception function:createInstance, exception:Exception: ReferenceError: Can't find variable: document
                                                        doPoll@(global function):172:45945
                                                        poll@(global function):172:15991
                                                        doOpen@(global function):172:15460
                                                        open@(global function):172:9418
                                                        open@(global function):172:39466
                                                        n@(global function):172:37998
                                                        n@(global function):172:36043
                                                        connect@(global function):172:21184
                                                        n@(global function):172:19606
                                                        n@(global function):172:18848
                                                        n@(global function):172:66442
                                                        t@(global function):172:31420
                                                        install@(global function):172:29806
                                                        use@(weex framework):2:29966
                                                        (global function):133:9
                                                        __webpack_require__@(global function):23:34
                                                        (global function):58:39
                                                        __webpack_require__@(global function):23:34
                                                        (global function):43:37
                                                        (global function):44:12
                                                        anonymous@(global function):199:4
                                                        a@(weex framework):3:30112
                                                        (weex framework):8:22648

**Comment by RoyalDeveloper2015** [comment]
I think this issue will be happened for every using Node_modules for vue.js project.
and the project for Web is running without any problem

**Comment by lerit** [comment]
i think it because this library use some variable such as document,only can work in vue or weex h5 enviroment,so not support native

**Comment by ntsd** [comment]
I got this error too have you try 'socket.io-client'?

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
