### ISSUE TITLE
动画修改宽高值，然后用dom.getComponentRect获取，ios能获取到正确值，安卓不行

### ISSUE THREAD

**Issue by hodgevk** [alibaba/weex#3112]
动画修改宽高值，然后用dom.getComponentRect获取，ios能获取到正确值，安卓获取到的还是原来的值
[Demo](http://dotwe.org/vue/c5f31b6a524090af6648f97fafa8be63)

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
