### ISSUE TITLE
iOS 在sdk0.12版本之后picker就获取不到值

### ISSUE THREAD

**Issue by aoping** [alibaba/weex#3113]
iOS 在sdk0.12版本之后picker就获取不到值

**Comment by aoping** [comment]
0.11可以， 0.12， 0.16.0都不可以，应该是bug吧？

**Comment by thecorsair** [comment]
ios 11 有bug  好像11.1 已经修复了 是苹果的锅

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
