### ISSUE TITLE
最新Android sdk第一次打开是渲染失败

### ISSUE THREAD

**Issue by watermelonRind** [alibaba/weex#3114]
最新Android sdk第一次打开是渲染失败

**Comment by T-Tenma** [comment]
我也遇到这个问题了
手机型号，红米4x
Android version： 7.1.2
weex version：0.17.0

切换成0.16.0就行了。

**Comment by fangxiaopeng** [comment]
两种解决办法，亲测有效：
（1）设置延时渲染；
try{
// 渲染之前延时1秒（解决页面空白问题）
Thread.sleep(1000);
mWXSDKInstance.render(TAG, WXFileUtils.loadAsset(path, this.getContext()), options, null, -1, -1, WXRenderStrategy.APPEND_ASYNC);
}catch (Exception e){
e.printStackTrace();
}

（2）切换回V0.16版本；

**Comment by fangxiaopeng** [comment]
问题原因：子线程中initFramework，js framework（main.js）初始化尚未成功，执行return导致创建WXSDKInstance实例失败。

解决办法（第三种）：
com.taobao.weex.bridge.WXBridgeManager类createInstance方法中如下代码片段

if (!isJSFrameworkInit() && reInitCount == 1 && !WXEnvironment.sDebugServerConnectable) {
Log.e("fxp", "instance.onRenderError");
instance.onRenderError(
WXRenderErrorCode.DegradPassivityCode.WX_DEGRAD_ERR_INSTANCE_CREATE_FAILED.getDegradErrorCode(),
WXRenderErrorCode.DegradPassivityCode.WX_DEGRAD_ERR_INSTANCE_CREATE_FAILED.getDegradErrorMsg() +
" isJSFrameworkInit==" + isJSFrameworkInit() + " reInitCount == 1" );
post(new Runnable() {
@override
public void run() {
initFramework("");
}
}, instanceId);
// return; // 注销return即可
}

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
