### ISSUE TITLE
weex 项目，Android sdk0.16.2版本，打开app第一次加载首页时，几率性的出现在屏幕左上角“render error: wx_create_instance_error”这段错误，背景白屏

### ISSUE THREAD

**Issue by 1404zlz** [alibaba/weex#3115]

**Comment by 1404zlz** [comment]
确认是升级sdk引起的这个问题，android studio中没有发现有用的错误日志

**Comment by 1903514970** [comment]
我也遇到这个问题了。求助

**Comment by 1903514970** [comment]
可能是0.16.2版本weex sdk初始化有时候会慢一点，一般只会在第一个页面出现这种错误情况，所以可以在渲染之前可以判断一下，如果初始化成功了，渲染页面，如果没有成功，延时几秒再渲染页面。

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
