### ISSUE TITLE
 weex 在虚拟机上无法运行ReportException : Exception: ReferenceError: Can't find variable: Vue

### ISSUE THREAD

**Issue by xiyuanyuan** [alibaba/weex#3116]
playgroud 和浏览器都没有问题但是虚拟机无法运行
11-14 13:00:15.295 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.298 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.299 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.302 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.307 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.308 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.309 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.311 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.312 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.313 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.314 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.314 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.316 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:15.317 5081-5098/com.alibaba.weex E/weex: [WXBridgeManager] invokeRegisterModules: framework.js uninitialized.
11-14 13:00:16.808 5081-5081/com.alibaba.weex E/WXTBUtil: isSupportSmartBar:false
11-14 13:00:16.850 5081-5098/com.alibaba.weex E/jsengine:  ReportException : Exception: ReferenceError: Can't find variable: Vue
                                                          (global function):8:1356
                                                          e@(global function):8:105
                                                          (global function):8:4452
                                                          e@(global function):8:105
                                                          (global function):8:478
                                                          (global function):8:486
                                                          anonymous@(global function):15:3
                                                          Et@(weex framework):1:25336
                                                          At@(weex framework):1:26414
                                                          (weex framework):8:22648
11-14 13:00:16.851 5081-5098/com.alibaba.weex E/weex: reportJSException >>>> instanceId:1, exception function:createInstance, exception:Exception: ReferenceError: Can't find variable: Vue
                                                      (global function):8:1356
                                                      e@(global function):8:105
                                                      (global function):8:4452
                                                      e@(global function):8:105
                                                      (global function):8:478
                                                      (global function):8:486
                                                      anonymous@(global function):15:3
                                                      Et@(weex framework):1:25336
                                                      At@(weex framework):1:26414
                                                      (weex framework):8:22648

**Comment by clotee** [comment]
我也碰到同样的问题了，请问解决了吗？

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
