### ISSUE TITLE
weex sdk 0.16版本IOS模拟机运行正常，真机安装运行却白屏

### ISSUE THREAD

**Issue by kacakong** [alibaba/weex#3118]
weex sdk 0.16版本IOS模拟机运行正常，真机安装运行却白屏
断点调试，发现真机js文件已经读取成功并执行了onCreate，但是没执行WXSDKInstance renderFinish
有人遇到类似问题吗？ 

android 模拟器和真机都正常。 只有ios是模拟器正常，真机不正常。

**Comment by coolhihi** [comment]
@kacakong 我也遇到同样问题，请问有找到解决办法吗？

**Comment by coolhihi** [comment]
@kacakong 找到原因了，因为缺少native-bundle-main.js文件
native-bundle-main.js需手动建立到WeexSDK/Resources中
请参考：http://www.jianshu.com/p/50482373f34e
源码：https://raw.githubusercontent.com/apache/incubator-weex/master/pre-build/native-bundle-main.js

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
