### ISSUE TITLE
[eros] | module 扩展太少？开发环境各种问题？无法解决？不妨来看看隔壁 eros。

### ISSUE THREAD

**Issue by PerseveranceZ** [alibaba/weex#3132]
## Intro
eros 是基于 [weex](https://weex-project.io/cn/) 封装面向前端的 vue 写法的解决方案，由于 app 开发的特殊性，eros 则更偏重关心于整个 app 项目。

> eros 只支持客户端。

## Demo

![工作原理](http://upload.ouliu.net/i/20180122162536pcw67.gif)

## Docs
* [eros 文档地址](https://bmfe.github.io/eros-docs/) (持续更新中...)

## Advantage
* 详细的文档来解决环境搭建过程中的坑。
* 一套代码编译成 ios，android 两端原生应用。
* 封装了大量 module，让前端开发方便进行原生的操作。
* 提供 `appboard` 机制来减少包体积，并可以对其实时修改。
* 内置了一套完整的 widget ，可根据业务自行修改。
* 中介者模式来集中管理业务。
* 提供了服务器端增量发布更新逻辑。
* 脚手架可直接生成开发最新模板。
* 脚手架启动服务进行实时开发效果查看和 debug 调试。
* 脚手架更新开发平台所需 eros 依赖。
* 脚手架支持打对应平台内置包。
* 脚手架支持生成全量包，增量包，并内置与更新服务器交互逻辑。
* 脚手架支持同步更新模板内容。
* 脚手架支持 weex 的 vue 入口和 js 入口两种开发方式。
* 支持 `weex debug`

## Disadvantage
> eros 开发中也有很多限制，需要开发者自行斟酌。
* weex 代码在浏览器端还有很多兼容性问题，所有 eros 目前不支持浏览器端
* eros 不能使用 weex 市场，如果您有原生开发经验可以自行接入
* 由于 eros 对 **JS Bundle** 运行机制采用了 appboard 机制来减少了 js bundle 的大小，导致 weex debug 需要特定的处理。
* eros 打出来的包体积稍大，为解决这个问题，eros 客户端动态加载依赖正在开发中。
* 如果遇到复杂的页面，如 IM 之类的，eros 建议用原生实现，weex 应付此类需求还是比较吃力。

## Situation
目前 `eros` 已有数十个 app 在开发中和上线的状态，其中有正在开发中的国外应用 **starLife（100+页面）**，也有国内正在开发的**蜂觅（60+ 页面）**，还有**已上线的应用都在 0-50+ 页面不等**，涉及行业分布于资讯，医疗，招商，购物，政府，办公等等。

而本木医疗（京医通）技术团队本身也基于 weex 开发了三个已上线的 app，均可在苹果商店和应用宝下载：
* 健康首都（京医通 app版，100+页面，很多功能还未开放）
* 本木医疗助手（30+页面）
* 本木医生助理（20+页面）

所以开发者大可放心，这不是一个 KPI 项目（公司没有 KPI ），已基于 MIT 协议开源。

> weex 还是有点脆弱，但不代表它不会长大。

**Comment by flicat** [comment]
这个 issue 侧面说明了 weex 还存在许多问题。。。

**Comment by chenzefeng09** [comment]
这个 issue 也说明了 weex 良好的可拓展性。。。

**Comment by baneyue** [comment]
请问你们weex基础库升级的策略是什么

**Comment by PerseveranceZ** [comment]
@baneyue 客户端上层框架自行控制sdk升级 每个版本对应一个分支 一般出来后会先放出来让大部分正在开发的同学使用 如果有问题 比如安卓 0.17.0 so库有较大变动在有些模拟器上 weex 实例化直接失败之类的问题 我们就自行退回版本

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
