### ISSUE TITLE
Android 打包apk安装，有默认导航栏，怎么去掉？

### ISSUE THREAD

**Issue by zhaoji223** [alibaba/weex#3134]

**Comment by zhaoji223** [comment]
![wechatimg26](https://user-images.githubusercontent.com/19246607/34661935-ec46716e-f487-11e7-9770-7ef266362ea2.jpeg)

**Comment by QzwJuHao** [comment]
在Android的Mainifest中该Activity的theme设置为NoActionBar。
android:theme="@style/AppTheme.NoActionBar"

**Comment by zhaoji223** [comment]
用https://github.com/weexteam/weex-hackernews.git  这个项目做模版是没有  头部 问题的。 算是曲线解决问题吧。  O_0
