### ISSUE TITLE
How to use css library like vuetify with weex. 

### ISSUE THREAD

**Issue by manjuk41** [alibaba/weex#3142]

**Comment by sudeepdk** [comment]
you can not you because you have to use weex component If you wants to create build in IOS and Android , weex component also work on web so you can user weex-ui  [](https://alibaba.github.io/weex-ui/#/)  if you wants Good look and feel ..

thanks

**Comment by manjuk41** [comment]
thank you sudeep

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
