### ISSUE TITLE
navigator.push跳转本地文件页面空白

### ISSUE THREAD

**Issue by zhang0ZGC** [alibaba/weex#3144]
我使用
`navigator.push({url:'http://someurl.com/xxx/test.js'})`
的时候页面正常跳转，显示正常，但是用weex build android | weex run android生成的app里面我跳到本地文件:
`navigator.push({url:"file://assets/dist/test.js"})`
回调显示跳转成功，但是页面是空白

**Comment by RickonST** [comment]
参考
http://blog.csdn.net/violetjack0808/article/details/74390249

**Comment by Hideer** [comment]
请问您的问题解决了么，还有就是test.js文件您是怎么产生的呢，为什么我构建的时候只有入口的vue文件被打包成了js文件 @zhang0ZGC

**Comment by zhang0ZGC** [comment]
@Hideer 我给我同事看了，他是按楼上的方案可以跳转了。test.vue跟index.vue放在同一级目录呀

**Comment by Hideer** [comment]
你好，我是放置在同一级目录中，但是只有入口的vue文件被打包成了js，其他的vue文件，并没有被打包
![image](https://user-images.githubusercontent.com/31301552/36837642-eb638fac-1d77-11e8-899b-346bf00c4dac.png)

jumpNative是我想用来测试的native跳转的页面

![image](https://user-images.githubusercontent.com/31301552/36837654-f4035bf6-1d77-11e8-8042-0206ed206dd5.png)
这是d打包后的文件

**Comment by zhang0ZGC** [comment]
@Hideer 额。。我不知道你这个是什么版本的。。应该是你这个为了做单页应用做过处理了，只处理entry.js

**Comment by Hideer** [comment]
我是通过weexpack进行构建的，版本应该没有问题，弄的我一头雾水好晕饿 @zhang0ZGC

**Comment by asd8855** [comment]
@zhang0ZGC  必须和index.vue 放在同一目录下，才能在bundlejs中显示出来是这样吗？

**Comment by zhang0ZGC** [comment]
@asd8855 是的，不知道什么原因

**Comment by asd8855** [comment]
是不是要改webpack.config中的路径

**Comment by zhang0ZGC** [comment]
@asd8855 是的吧。我搞错了，我是直接用最新版的weex生成的项目，我运行`npm run build`，是可以把其他未排除的目录里面的文件也编译的，不存在上面 @Hideer 的情况 ，受不了的是后面如果用`weex build android`去编译安卓app，这个weex只会移动dist根目录里面的文件，而忽略其它目录.....这个改都不知道在哪儿改....

**Comment by asd8855** [comment]
那你现在好了没？怎么修改可以做到，把dist中的所有js都导到bundlejs中

**Comment by zhang0ZGC** [comment]
@asd8855 没做到。。。。看weex的库文件也没看懂。。。然后就妥协了，要么都放一级目录，要么自己拷过去。。。

**Comment by asd8855** [comment]
好吧

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
