### ISSUE TITLE
对cell或cell内元素使用fixed布局，list的loadmore事件无法触发

### ISSUE THREAD

**Issue by phillyx** [alibaba/weex#3146]
事情是这样的，我在`cell`内包裹`scroll-to-top`插件，该插件fixed布局，然后`list.loadmore`触发不了，web可触发
```html
<cell>
    <to-top v-if="isUseScroll2Top"
    ref="scroll2Top"
    scroll-el="scell"
    @back2Top="scroll2Top"></to-top>
</cell>
```
我又对`cell`做`fixed`测试，也发现了同样的问题
```js
    <cell style="height:400px;width:200px;position:fixed;right:0;top:0;background-color:#FFF">
      <text>{{testData}}</text>
    </cell>
```
官方文档中
**由于 <cell> 本身是一个容器，其布局由 <list> 进行管理，你不能给 <cell> 设定flex值。 <cell>的宽度等于父组件 <list> 的宽度，并且 <cell> 高度自适应，指定 margin 样式也不起作用。

通用样式：支持所有通用样式**

说明并不清晰，支持`position`,宽度自然就可定义

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
