### ISSUE TITLE
css loading gives "Error: undefined:12:20: property missing ':', Error: undefined: 12:180: property missing '}' "

### ISSUE THREAD

**Issue by lopugit** [alibaba/weex#3152]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [x] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [x] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [x] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
- platform (Win/Mac/Ubuntu..) linux
- weex: v1.2.9
- weexpack : v1.1.5
- weex-builder : v0.3.14
- weex-previewer : v1.4.6

## The key error stack message.

`
(Emitted value instead of an instance of Error) Error: undefined:4:67: property missing ':',Error: undefined:4:67: missing '}',Error: undefined:4:212: property missing ':',Error: undefined:4:212: missing '}',Error: undefined:4:279: property missing ':',Error: undefined:4:279: missing '}',Error: undefined:11:5: property missing ':',Error: undefined:11:5: missing '}',Error: undefined:13:10: property missing ':',Error: undefined:13:10: missing '}',Error: undefined:13:66: property missing ':',Error: undefined:13:66: missing '}',Error: undefined:13:211: property missing ':',Error: undefined:13:211: missing '}',Error: undefined:13:278: property missing ':',Error: undefined:13:278: missing '}',Error: undefined:14:10: property missing ':',Error: undefined:14:10: missing '}',Error: undefined:14:75: property missing ':',Error: undefined:14:75: missing '}',Error: undefined:14:220: property missing ':',Error: undefined:14:220: missing '}',Error: undefined:14:287: property missing ':',Error: undefined:14:287: missing '}',Error: undefined:20:40: property missing ':',Error: undefined:20:40: missing '}',Error: undefined:21:2: missing '{'

 @ ./src/components/register.vue 5:20-385
 @ ./.temp/router/index.js
 @ ./.temp/entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.188:8081 ./.temp/entry.js

 error  in ./src/components/ico/ico.vue

(Emitted value instead of an instance of Error) Error: undefined:4:70: property missing ':',Error: undefined:4:70: missing '}',Error: undefined:4:221: property missing ':',Error: undefined:4:221: missing '}',Error: undefined:4:291: property missing ':',Error: undefined:4:291: missing '}',Error: undefined:11:5: property missing ':',Error: undefined:11:5: missing '}',Error: undefined:13:10: property missing ':',Error: undefined:13:10: missing '}',Error: undefined:13:69: property missing ':',Error: undefined:13:69: missing '}',Error: undefined:13:220: property missing ':',Error: undefined:13:220: missing '}',Error: undefined:13:290: property missing ':',Error: undefined:13:290: missing '}',Error: undefined:14:10: property missing ':',Error: undefined:14:10: missing '}',Error: undefined:14:78: property missing ':',Error: undefined:14:78: missing '}',Error: undefined:14:229: property missing ':',Error: undefined:14:229: missing '}',Error: undefined:14:299: property missing ':',Error: undefined:14:299: missing '}',Error: undefined:20:40: property missing ':',Error: undefined:20:40: missing '}',Error: undefined:21:2: missing '{'

 @ ./src/components/ico/ico.vue 5:20-389
 @ ./.temp/router/index.js
 @ ./.temp/entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.188:8081 ./.temp/entry.js

 error  in ./src/components/ico/icoThings.vue

(Emitted value instead of an instance of Error) Error: undefined:4:70: property missing ':',Error: undefined:4:70: missing '}',Error: undefined:4:221: property missing ':',Error: undefined:4:221: missing '}',Error: undefined:4:291: property missing ':',Error: undefined:4:291: missing '}',Error: undefined:11:5: property missing ':',Error: undefined:11:5: missing '}',Error: undefined:13:10: property missing ':',Error: undefined:13:10: missing '}',Error: undefined:13:69: property missing ':',Error: undefined:13:69: missing '}',Error: undefined:13:220: property missing ':',Error: undefined:13:220: missing '}',Error: undefined:13:290: property missing ':',Error: undefined:13:290: missing '}',Error: undefined:14:10: property missing ':',Error: undefined:14:10: missing '}',Error: undefined:14:78: property missing ':',Error: undefined:14:78: missing '}',Error: undefined:14:229: property missing ':',Error: undefined:14:229: missing '}',Error: undefined:14:299: property missing ':',Error: undefined:14:299: missing '}',Error: undefined:20:40: property missing ':',Error: undefined:20:40: missing '}',Error: undefined:21:2: missing '{'

 @ ./src/components/ico/icoThings.vue 5:20-395
 @ ./.temp/router/index.js
 @ ./.temp/entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.188:8081 ./.temp/entry.js

 error  in ./src/components/ico/icoThingsStyles.vue

(Emitted value instead of an instance of Error) Error: undefined:4:70: property missing ':',Error: undefined:4:70: missing '}',Error: undefined:4:221: property missing ':',Error: undefined:4:221: missing '}',Error: undefined:4:291: property missing ':',Error: undefined:4:291: missing '}',Error: undefined:11:5: property missing ':',Error: undefined:11:5: missing '}',Error: undefined:13:10: property missing ':',Error: undefined:13:10: missing '}',Error: undefined:13:69: property missing ':',Error: undefined:13:69: missing '}',Error: undefined:13:220: property missing ':',Error: undefined:13:220: missing '}',Error: undefined:13:290: property missing ':',Error: undefined:13:290: missing '}',Error: undefined:14:10: property missing ':',Error: undefined:14:10: missing '}',Error: undefined:14:78: property missing ':',Error: undefined:14:78: missing '}',Error: undefined:14:229: property missing ':',Error: undefined:14:229: missing '}',Error: undefined:14:299: property missing ':',Error: undefined:14:299: missing '}',Error: undefined:20:40: property missing ':',Error: undefined:20:40: missing '}',Error: undefined:21:2: missing '{'

 @ ./src/components/ico/icoThingsStyles.vue 5:20-401
 @ ./.temp/router/index.js
 @ ./.temp/entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.188:8081 ./.temp/entry.js

 error  in ./src/components/ico/inventoryStyles.vue

(Emitted value instead of an instance of Error) Error: undefined:4:70: property missing ':',Error: undefined:4:70: missing '}',Error: undefined:4:221: property missing ':',Error: undefined:4:221: missing '}',Error: undefined:4:291: property missing ':',Error: undefined:4:291: missing '}',Error: undefined:11:5: property missing ':',Error: undefined:11:5: missing '}',Error: undefined:13:10: property missing ':',Error: undefined:13:10: missing '}',Error: undefined:13:69: property missing ':',Error: undefined:13:69: missing '}',Error: undefined:13:220: property missing ':',Error: undefined:13:220: missing '}',Error: undefined:13:290: property missing ':',Error: undefined:13:290: missing '}',Error: undefined:14:10: property missing ':',Error: undefined:14:10: missing '}',Error: undefined:14:78: property missing ':',Error: undefined:14:78: missing '}',Error: undefined:14:229: property missing ':',Error: undefined:14:229: missing '}',Error: undefined:14:299: property missing ':',Error: undefined:14:299: missing '}',Error: undefined:20:40: property missing ':',Error: undefined:20:40: missing '}',Error: undefined:21:2: missing '{'

 @ ./src/components/ico/inventoryStyles.vue 5:20-401
 @ ./.temp/router/index.js
 @ ./.temp/entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.188:8081 ./.temp/entry.js

 error  in ./src/components/ico/icoThingsOptions.vue

(Emitted value instead of an instance of Error) Error: undefined:4:70: property missing ':',Error: undefined:4:70: missing '}',Error: undefined:4:221: property missing ':',Error: undefined:4:221: missing '}',Error: undefined:4:291: property missing ':',Error: undefined:4:291: missing '}',Error: undefined:11:5: property missing ':',Error: undefined:11:5: missing '}',Error: undefined:13:10: property missing ':',Error: undefined:13:10: missing '}',Error: undefined:13:69: property missing ':',Error: undefined:13:69: missing '}',Error: undefined:13:220: property missing ':',Error: undefined:13:220: missing '}',Error: undefined:13:290: property missing ':',Error: undefined:13:290: missing '}',Error: undefined:14:10: property missing ':',Error: undefined:14:10: missing '}',Error: undefined:14:78: property missing ':',Error: undefined:14:78: missing '}',Error: undefined:14:229: property missing ':',Error: undefined:14:229: missing '}',Error: undefined:14:299: property missing ':',Error: undefined:14:299: missing '}',Error: undefined:20:40: property missing ':',Error: undefined:20:40: missing '}',Error: undefined:21:2: missing '{'

 @ ./src/components/ico/icoThingsOptions.vue 5:20-402
 @ ./.temp/router/index.js
 @ ./.temp/entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.188:8081 ./.temp/entry.js

 error  in ./src/components/ico/icoSandboxThing.vue

(Emitted value instead of an instance of Error) Error: undefined:4:70: property missing ':',Error: undefined:4:70: missing '}',Error: undefined:4:221: property missing ':',Error: undefined:4:221: missing '}',Error: undefined:4:291: property missing ':',Error: undefined:4:291: missing '}',Error: undefined:11:5: property missing ':',Error: undefined:11:5: missing '}',Error: undefined:13:10: property missing ':',Error: undefined:13:10: missing '}',Error: undefined:13:69: property missing ':',Error: undefined:13:69: missing '}',Error: undefined:13:220: property missing ':',Error: undefined:13:220: missing '}',Error: undefined:13:290: property missing ':',Error: undefined:13:290: missing '}',Error: undefined:14:10: property missing ':',Error: undefined:14:10: missing '}',Error: undefined:14:78: property missing ':',Error: undefined:14:78: missing '}',Error: undefined:14:229: property missing ':',Error: undefined:14:229: missing '}',Error: undefined:14:299: property missing ':',Error: undefined:14:299: missing '}',Error: undefined:20:40: property missing ':',Error: undefined:20:40: missing '}',Error: undefined:21:2: missing '{'

 @ ./src/components/ico/icoSandboxThing.vue 5:20-401
 @ ./.temp/router/index.js
 @ ./.temp/entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.188:8081 ./.temp/entry.js

 error  in ./src/components/ico/icoManifestThing.vue

(Emitted value instead of an instance of Error) Error: undefined:4:70: property missing ':',Error: undefined:4:70: missing '}',Error: undefined:4:221: property missing ':',Error: undefined:4:221: missing '}',Error: undefined:4:291: property missing ':',Error: undefined:4:291: missing '}',Error: undefined:11:5: property missing ':',Error: undefined:11:5: missing '}',Error: undefined:13:10: property missing ':',Error: undefined:13:10: missing '}',Error: undefined:13:69: property missing ':',Error: undefined:13:69: missing '}',Error: undefined:13:220: property missing ':',Error: undefined:13:220: missing '}',Error: undefined:13:290: property missing ':',Error: undefined:13:290: missing '}',Error: undefined:14:10: property missing ':',Error: undefined:14:10: missing '}',Error: undefined:14:78: property missing ':',Error: undefined:14:78: missing '}',Error: undefined:14:229: property missing ':',Error: undefined:14:229: missing '}',Error: undefined:14:299: property missing ':',Error: undefined:14:299: missing '}',Error: undefined:20:40: property missing ':',Error: undefined:20:40: missing '}',Error: undefined:21:2: missing '{'

 @ ./src/components/ico/icoManifestThing.vue 5:20-402
 @ ./.temp/router/index.js
 @ ./.temp/entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.188:8081 ./.temp/entry.js

 error  in ./src/components/ico/status.vue

(Emitted value instead of an instance of Error) Error: undefined:4:70: property missing ':',Error: undefined:4:70: missing '}',Error: undefined:4:221: property missing ':',Error: undefined:4:221: missing '}',Error: undefined:4:291: property missing ':',Error: undefined:4:291: missing '}',Error: undefined:11:5: property missing ':',Error: undefined:11:5: missing '}',Error: undefined:13:10: property missing ':',Error: undefined:13:10: missing '}',Error: undefined:13:69: property missing ':',Error: undefined:13:69: missing '}',Error: undefined:13:220: property missing ':',Error: undefined:13:220: missing '}',Error: undefined:13:290: property missing ':',Error: undefined:13:290: missing '}',Error: undefined:14:10: property missing ':',Error: undefined:14:10: missing '}',Error: undefined:14:78: property missing ':',Error: undefined:14:78: missing '}',Error: undefined:14:229: property missing ':',Error: undefined:14:229: missing '}',Error: undefined:14:299: property missing ':',Error: undefined:14:299: missing '}',Error: undefined:20:40: property missing ':',Error: undefined:20:40: missing '}',Error: undefined:21:2: missing '{'

 @ ./src/components/ico/status.vue 5:20-392
 @ ./.temp/router/index.js
 @ ./.temp/entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.188:8081 ./.temp/entry.js
`

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)
npm i --save-dev sass-loader node-sass 

then make a component with 

```
<style lang="sass">
.style
  height: 100px
  width: 20px
</style>
```

and it should give the error

This is an example of one of my components, all of my components are erroring

https://pastebin.com/ksGdftaB

I can create a repo so you can see the package.json, config.js, util.js, webpack.common.conf.js files if you'd like?

has anyone run into this?

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
