### ISSUE TITLE
import and not found any module in entry.js

### ISSUE THREAD

**Issue by leeziiAtCn** [alibaba/weex#3159]
when i import any module in entry.js, i get an error
'This relative module was not found:
./router in ./.temp/index.js, ./.temp/components/bill/index.js and 2 others'

i can't find 'router.js' in '.temp', but i have a 'router.js' in 'src'

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
