### ISSUE TITLE
weex 使用mixin

### ISSUE THREAD

**Issue by pcwang0205** [alibaba/weex#3161]
无法使用mixin，build完之后，压根就没有Vue.mixin()相关的调用，如何解决？

**Comment by linda8167** [comment]
You can do this！
import mixin from '@/mixins/index'
export default {
  mixins: [mixin],
  data() {
    return {}
  }
}

**Comment by pcwang0205** [comment]
@linda8167

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
