### ISSUE TITLE
Vue routing?

### ISSUE THREAD

**Issue by DylanC** [alibaba/weex#3165]
Does Weex have its own way of doing routing? 

Using **weex create** it says:
Use vue-router to manage your view router **(not recommended)**

So, if I don't use Vue router... what do I use for routing?

**Comment by dcohenb** [comment]
Ran into the same issue, You should probably use the weex navigator. explained in the docs:
https://weex.incubator.apache.org/references/modules/navigator.html

**Comment by DylanC** [comment]
@dcohenb - Thanks!

**Comment by pranshuagrawal** [comment]
@dcohenb can you tell me how to pass the URL while navigating? As the docs do not say much about that. Say I have set up a route "/example", opening a certain component then how should I put it in the navigation object?

Or is it completely unrelated to routing and if so then how exactly it will identify which component to load and where to load?

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
