### ISSUE TITLE
weex如何跳转原生页面

### ISSUE THREAD

**Issue by liangxiaobo** [alibaba/weex#3168]
weex集成到现有项目开发，如何在weex中跳转到原生页面？

**Comment by varSmallRookie** [comment]
我们客户端开发人员重写了navigator这个module的push方法，通过scheme跳转原生

**Comment by liangxiaobo** [comment]
谢谢您的回复，我已经在客户端实现了，包括把jsbundle下载到客户端执行。



liangxiaobo2009@yeah.net
 
发件人： 奉诗轩(Jack)
发送时间： 2018-05-18 14:48
收件人： alibaba/weex
抄送： liangxiaobo; State change
主题： Re: [alibaba/weex] weex如何跳转原生页面 (#3168)
我们客户端开发人员重写了navigator这个module的push方法，通过scheme跳转原生
