### ISSUE TITLE
WX_KEY_EXCEPTION_SDK_INIT_JSFM_INIT_FAILED，显示空白

### ISSUE THREAD

**Issue by liangxiaobo** [alibaba/weex#3169]
在ios上运行,看到log错误:<Weex>[error]WXMonitor.m:250, [WX_KEY_EXCEPTION_SDK_INIT_JSFM_INIT_FAILED] script don't exist:(null)，显示空白。

**Comment by Crazyang** [comment]
me too !!

WeexDemo[42071:9139198] <Weex>[error]WXMonitor.m:250, [WX_KEY_EXCEPTION_WXBRIDGE] [undefined:4507:47] ReferenceError: Can't find variable: document

__webpack_require__

__webpack_require__

__webpack_require__

__webpack_require__

__webpack_require__

__webpack_require__


__webpack_require__

__webpack_require__

__webpack_require__

__webpack_require__

__webpack_require__


anonymous
native-bundle-main.js:1:40926
createInstance@native-bundle-main.js:1:40937
native-bundle-main.js:1:255299
2018-06-09 03:08:06.445066+0800 WeexDemo[42071:9140131] [] nw_connection_get_connected_socket 1 Connection has no connected handler
2018-06-09 03:08:06.447359+0800 WeexDemo[42071:9140131] TCP Conn 0x60400016e100 Failed : error 0:60 [60]
fire

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
