### ISSUE TITLE
weex如何使用2级子路由

### ISSUE THREAD

**Issue by JunWuHui** [alibaba/weex#3171]
/*global Vue*/
import Router from 'vue-router'

//一级路由
import Quotation from '@/components/quotation/Quotation'
import NewsFlash from '@/components/newsflash/NewsFlash'
import PersonalCenter from '@/components/personalcenter/PersonalCenter'
//二级路由
import QuoatationPage from '@/components/quotation/QuoatationPage'
import Optional from '@/components/quotation/Optional'

import Message from '@/components/singlepage/Message'
import Contact from '@/components/singlepage/Contact'
import PublicNum from '@/components/singlepage/PublicNum'
import Login from '@/components/member/Login'
import Register from '@/components/member/Register'
import ForgetPassword from '@/components/member/ForgetPassword'

Vue.use(Router)

module.exports = new Router({
  routes: [
    {
      path: '/',
      name: 'quotation',
      component: Quotation,
      redirect: '/quoatationpage',
      children: [
        {
          path: '/quoatationpage',
          name: 'quoatationpage',
          component: QuoatationPage
        },
        {
          path: '/optional',
          name: 'optional',
          component: Optional
        }
      ]
    },
    {
      path: '/newsflash',
      name: 'newsflash',
      component: NewsFlash
    },
    {
      path: '/personalcenter',
      name: 'personalcenter',
      component: PersonalCenter,
      children: [
        {
          path: '/personalcenter/message',
          name: 'message',
          component: Message
        },
        {
          path: '/personalcenter/contact',
          name: 'contact',
          component: Contact
        },
        {
          path: '/personalcenter/publicnum',
          name: 'publicnum',
          component: PublicNum
        },
        {
          path: '/personalcenter/login',
          name: 'login',
          component: Login
        },
        {
          path: '/personalcenter/register',
          name: 'register',
          component: Register
        },
        {
          path: '/personalcenter/forgetpassword',
          name: 'forgetpassword',
          component: ForgetPassword
        }
      ]
    }
  ]
})

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
