### ISSUE TITLE
EXC_BAD_ACCESS Error (on iOS) when using Stream

### ISSUE THREAD

**Issue by pranshuagrawal** [alibaba/weex#3183]
I am using stream in my weex project, the apps crash everytime I try to run it on iOS simulator. It works fine on android though.

If I comment out the stream code (viz commenting the code where I am using stream and import is still uncommented) the application works fine on both the platform.

Considering that stream code is working fine on android concludes that there is nothing wrong with my Vue code (maybe I am not doing some iOS specific thingy).

Here is the code:

           stream.fetch({
                method: 'GET',
                type: 'json',
                url: 'https://example.com/someUrl.json'
            }, res => {
                if(res.ok){
                    this.isLoading = false;
                    this.isError = false;
                    
                    this.number = res.data.number;
                    this.name = res.data.name;
                }else{
                    this.isLoading = false;
                    this.isError = true;
                }      
            });

The error which I get is on the following line:

            callbackRsp setObject:@{ @"OPENED": @1 } forKey:@"readyState"];
            progressCallback(callbackRsp, TRUE);

The error is: 

            Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)

Occuring on `progressCallback` line.

What I can think of is that it could be because of some package which I need to install or maybe version number of something is messed up because on playground it is working absolutely fine.

Any help would greatly appreciated.

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
