### ISSUE TITLE
Xcode 9 pod install 集成weexSDK 编译报错

### ISSUE THREAD

**Issue by likenow** [alibaba/weex#3193]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GLKView", referenced from:
      objc-class-ref in WeexSDK(WXCanvasComponent.o)
  "_OBJC_CLASS_$_GLKTextureLoader", referenced from:
      objc-class-ref in WeexSDK(WXCanvasComponent.o)
  "_OBJC_CLASS_$_GLKBaseEffect", referenced from:
      objc-class-ref in WeexSDK(WXCanvasComponent.o)
  "_GLKTextureLoaderApplyPremultiplication", referenced from:
      -[WXCanvasComponent getTexture:] in WeexSDK(WXCanvasComponent.o)
  "_GLKMatrix4Identity", referenced from:
      -[WXCanvasComponent viewDidLoad] in WeexSDK(WXCanvasComponent.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing All Messages
  "_OBJC_CLASS_$_GLKView", referenced from:

      objc-class-ref in WeexSDK(WXCanvasComponent.o)

  "_OBJC_CLASS_$_GLKTextureLoader", referenced from:

      objc-class-ref in WeexSDK(WXCanvasComponent.o)

  "_OBJC_CLASS_$_GLKBaseEffect", referenced from:

      objc-class-ref in WeexSDK(WXCanvasComponent.o)

  "_GLKTextureLoaderApplyPremultiplication", referenced from:

      -[WXCanvasComponent getTexture:] in WeexSDK(WXCanvasComponent.o)

  "_GLKMatrix4Identity", referenced from:

      -[WXCanvasComponent viewDidLoad] in WeexSDK(WXCanvasComponent.o)

ld: symbol(s) not found for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by likenow** [comment]
Other linker Flags -ObjC 已添加

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
