### ISSUE TITLE
weex-androw（sdk:0.19.0.7）:webview message prompt 实现错误

### ISSUE THREAD

**Issue by zcl0001** [alibaba/weex#3203]
com.taobao.weex.ui.view.WXWebView 247行到254行，DOWNGRADE_JS_INTERFACE 逻辑貌似写反了

  if (mOnMessageListener != null) {
                    evaluateJS("javascript:(window.postMessage = function(message, targetOrigin) {"
                        + "if (message == null || !targetOrigin) return;"
                        + (DOWNGRADE_JS_INTERFACE
                        ? "prompt('" + BRIDGE_NAME + "://postMessage?message=' + JSON.stringify(message) + '&targetOrigin=' + targetOrigin)"
                        : BRIDGE_NAME + ".postMessage(JSON.stringify(message), targetOrigin);")
                        + "})");
                }

**Comment by zcl0001** [comment]
DOWNGRADE_JS_INTERFACE 为false时候 ，android 貌似调用的是web，应该是prompt('" + BRIDGE_NAME + "://postMessage?message=' + JSON.stringify(message) + '&targetOrigin=' + targetOrigin)，这样webviewClient 才能拦击，分发消息

**Comment by zcl0001** [comment]
`<template>
  <div class="wrapper">
    <web ref ="webview" style="width: 730px; height: 500px" src="./chart.html"
      @pagestart="onPageStart" @pagefinish="onPageFinish" @error="onError"
      @message="onMessage"></web>
    <text test-id='pagestart'>pagestart: {{pagestart}}</text>
    <text test-id='pagefinish'>pagefinish: {{pagefinish}}</text>
    <text test-id='title'>title: {{title}}</text>
    <text test-id='error'>error: {{error}}</text>
    <text test-id='message'>message: {{message}}</text>
  </div>
</template>

<style scoped>
  .wrapper {
		flex-direction: column;
		padding: 10px;
	}
</style>

<script>
  	var webview = weex.requireModule('webview');
  /*	var webElement = this.$el('webview');*/
  	module.exports = {
	    data: {
	      pagestart: '',
	      pagefinish: '',
	      title: '',
	      error: '',
	      message:'',
	    },
	    methods: {
	      	onPageStart: function(e) {
	        	this.pagestart = e.url;
	      	},
	      	onPageFinish: function(e) {
	        	this.pagefinish = e.url;
	   			if (e.title) {
	      			this.title = e.title;
	    		}
	    		var ref = this.$refs[`webview`];
	    		webview.postMessage(ref,{message: 'message to Web page'});
	      	},
	      	onError: function(e) {
	        	this.error = e.url;
	      	},
	      	onMessage: function(e) {
	        	this.message = e;
	      	},
	    }
	}
</script>`

**Comment by zcl0001** [comment]
`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    
    <script src="./echarts.min.js"></script>
</head>
<body>
    
    <div id="main" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        window.addEventListener('message', event => {
            alert(event.data.message)
            console.log(event.data.message) // message to Web page
        })
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 20]
            }]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
        myChart.on('click', function (params) {
            var message=JSON.stringify(
                {
                    key1:params.componentType,
                    key2:params.seriesIndex,
                    key3:{
                        key1:params.componentType,
                        key2:params.seriesIndex,
                    },
                    key4:[
                        {
                            key1:params.componentType,
                            key2:params.seriesIndex,
                        }
                    ]
                }
            )
            var targetOrigin="demo"
            var result=prompt("__WEEX_WEB_VIEW_BRIDGE://postMessage?message="+message+"&targetOrigin="+targetOrigin);
            //window.postMessage(params.componentType, "http://example.org");
            alert("demo " +  result);
            //alert(params.componentType)
          if (params.componentType === 'markPoint') {
              // 点击到了 markPoint 上
              if (params.seriesIndex === 5) {
                  // 点击到了 index 为 5 的 series 的 markPoint 上。
              }
          }
          else if (params.componentType === 'series') {
              if (params.seriesType === 'graph') {
                  if (params.dataType === 'edge') {
                      // 点击到了 graph 的 edge（边）上。
                  }
                  else {
                      // 点击到了 graph 的 node（节点）上。
                  }
              }
          }
        });
    </script>
</body>
</html>
`

**Comment by YorkShen** [comment]
This PR/issue doesn't received response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
