### ISSUE TITLE
两年没更新了，是不是要放弃了啊！

### ISSUE THREAD

**Issue by banfengcanyue** [alibaba/weex#3208]

**Comment by totzcc** [comment]
迁到 apache去了啊

**Comment by YorkShen** [comment]
This PR has been closed since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
又迁回来了。
