### ISSUE TITLE
Publish a new SDK version

### ISSUE THREAD

**Issue by Hanks10100** [alibaba/weex#3214]
Publish Android and iOS binary SDK to cocoapods and maven from the latest code, as well as tags, release notes.

**Comment by kang558** [comment]
既然已经从 Apache 迁移回这里了，什么时候合并完成并发布新版本呢，已经好久没更新版本了

**Comment by jianhan-he** [comment]
> 既然已经从 Apache 迁移回这里了，什么时候合并完成并发布新版本呢，已经好久没更新版本了

最快下周会基于最新代码发个0.30.0版本

**Comment by jianhan-he** [comment]
社区版本0.30.0版本已经发布，暂时还是apache的包名，预计下个版本会改成taobao报名。iOS可以通过pod update拉到最新的版本

**Comment by joy2helloworld** [comment]
taobao包名的版本大概是什么时候能发布呢

**Comment by jianhan-he** [comment]
> taobao包名的版本大概是什么时候能发布呢

具体计划还没出来，初步预计两周左右，等这周计划定下来后我会在这里更新

**Comment by penglin101** [comment]
已经过了一个周了，大佬们，拜托快快更新了，公司使用了weex，导致按地段欧创版本一直没办法升级

**Comment by penglin101** [comment]
已经过了一个周了，大佬们，拜托快快更新了，公司使用了weex，导致Android target版本一直没办法升级

**Comment by kang558** [comment]
> 已经过了一个周了，大佬们，拜托快快更新了，公司使用了weex，导致Android target版本一直没办法升级

已经更新了啊 [https://github.com/alibaba/weex/releases/tag/0.30.0](https://github.com/alibaba/weex/releases/tag/0.30.0)

**Comment by jianhan-he** [comment]
> 已经过了一个周了，大佬们，拜托快快更新了，公司使用了weex，导致Android target版本一直没办法升
由于jcenter服务停用了，现在正在将weexsdk迁移到maven上，导致时间有点延期，maven上预计这两天应该就能搞定了

**Comment by penglin101** [comment]
> > 已经过了一个周了，大佬们，拜托快快更新了，公司使用了weex，导致Android target版本一直没办法升级
> 
> 已经更新了啊 https://github.com/alibaba/weex/releases/tag/0.30.0

我们使用了
implementation 'com.taobao.android:weex_sdk:0.30.0'
以及
implementation 'org.apache.weex:sdk:0.30.0'
implementation 'org.apache.weex:sdk_legacy:0.30.0'
三种方式添加依赖，发现都不能导入相应的依赖包，编译直接报错无法访问依赖地址
请问大神有更好的解决方案嘛

**Comment by katherine95s** [comment]
Android依赖包正在向maven迁移，迁移完成后会在maven上发布0.30.0。稍等下，这两天就会发布的。

**Comment by joy2helloworld** [comment]
> Android依赖包正在向maven迁移，迁移完成后会在maven上发布0.30.0。稍等下，这两天就会发布的。

周五了，今天能发吗。。。[捂脸]

**Comment by Stanllley** [comment]
请问Android 0.30.0还需要多久啊？

**Comment by miomin** [comment]
Android Weex SDK 已经迁移至 Maven 仓库，需添加依赖
`
maven {
    url "https://s01.oss.sonatype.org/content/repositories/releases/"
}
`

在你的 Android 工程中，按如下方式引入依赖
`
implementation 'io.weex:weex_sdk: 0.30.0'
`

**Comment by xyl70** [comment]
加入 依赖：
maven { url "https://s01.oss.sonatype.org/content/repositories/releases/" }
implementation 'io.weex:weex_sdk: 0.30.2'
无法更新呀。

**Comment by joy2helloworld** [comment]
Unable to resolve dependency for ':lib@debug/compileClasspath': Could not resolve io.weex:weex_sdk: 0.30.2.
引用不到

**Comment by joy2helloworld** [comment]
> Android Weex SDK 已经迁移至 Maven 仓库，需添加依赖：
> `maven { url "https://s01.oss.sonatype.org/content/repositories/releases/" }`
> 
> 在你的 Android 工程中，按如下方式引入依赖：
> `implementation 'io.weex:weex_sdk: 0.30.2'`
> 
> 新版本在使用上遇到问题，请在这条评论下留言。

Unable to resolve dependency for ':lib@debug/compileClasspath': Could not resolve io.weex:weex_sdk: 0.30.2.
引用不到

**Comment by joy2helloworld** [comment]
> > Android Weex SDK 已经迁移至 Maven 仓库，需添加依赖：
> > `maven { url "https://s01.oss.sonatype.org/content/repositories/releases/" }`
> > 在你的 Android 工程中，按如下方式引入依赖：
> > `implementation 'io.weex:weex_sdk: 0.30.2'`
> > 新版本在使用上遇到问题，请在这条评论下留言。
> 
> Unable to resolve dependency for ':lib@debug/compileClasspath': Could not resolve io.weex:weex_sdk: 0.30.2.
> 引用不到

可以了，你给的代码里，implementation 'io.weex:weex_sdk: 0.30.2' 多了个空格。。。
