### ISSUE TITLE
[Android]什么时候更新0.30呢

### ISSUE THREAD

**Issue by DoctorWiseman** [alibaba/weex#3217]
Android X 的兼容问题，亟待解决
有其它办法可以现在解决这个问题不

**Comment by miomin** [comment]
Android Weex SDK 已经迁移至 Maven 仓库，需添加依赖：
`
maven {
    url "https://s01.oss.sonatype.org/content/repositories/releases/"
}
`

在你的 Android 工程中，按如下方式引入依赖：
`
implementation 'io.weex:weex_sdk: 0.30.1'
`

新版本在使用上遇到问题，请在这条评论下留言。

**Comment by Hanks10100** [comment]
安卓已经发了 0.30.2 (和 0.30.1 代码是一样的)，具体用法参考 [io.weex:weex_sdk:0.30.2](https://search.maven.org/artifact/io.weex/weex_sdk/0.30.2/jar) 右侧的范例。

**Comment by AnyLifeZLB** [comment]
@Hanks10100 @miomin 

0.30.2 在android 工程中使用targetSDK=30 没问题吧？ 准备升级了

**Comment by firekyrin** [comment]
来信收悉，非常感谢！============http://www.firekyrin.com
