### ISSUE TITLE
[Android][iOS]现在官网打不开了

### ISSUE THREAD

**Issue by niesai** [alibaba/weex#3222]
现在官网打不开了

**Comment by jianhan-he** [comment]
http://emas.weex.io/ 先用这个地址，内部还在迁移中

**Comment by aotian16** [comment]
> http://emas.weex.io/ 先用这个地址，内部还在迁移中

这文档貌似很老的啊

**Comment by Hanks10100** [comment]
emas.weex.io 网站已经不再更新，最新文档挂在了 http://doc.weex.io/ （内容也比较旧），接下来持续更新。
