### ISSUE TITLE
据说week被阿里放弃啦，我觉得这个框架很nice，为什么不继续做呢？

### ISSUE THREAD

**Issue by Tianwen9579** [alibaba/weex#3227]

**Comment by jianhan-he** [comment]
weex没放弃，只是从apache上退休了，重新放回到alibaba下进行维护，后续还会进行weex2.0升级

**Comment by Tianwen9579** [comment]
呃呃  我就説  這麽优秀的项目

**Comment by Tianwen9579** [comment]
希望成为未来app开发主流

**Comment by zhangdengdeng** [comment]
一直在用他开发，熟悉掌握了它的特点之后觉得它蛮有生产力的。顶起WEEX！

**Comment by zhangdengdeng** [comment]
一直在用他开发，熟悉掌握了它的特点之后觉得它蛮有生产力的。顶起WEEX！

**Comment by ssw1992** [comment]
@Tianwen9579 weex缺乏社区，想成为主流很困难的

**Comment by Tianwen9579** [comment]
@ssw1992  当它足够优秀的时候，社区自然就有了，weex加油

**Comment by JeremyYvv** [comment]
建议参考Vue，好好写一下文档

**Comment by 25juan** [comment]
什么升级2.0，有什么新特性呢

**Comment by zhangdengdeng** [comment]
Weex忠粉，好期待2.0，又有组织啦！

**Comment by chinaltz** [comment]
weex 当前版本支持 64位 so 了么.需要上架 GP

**Comment by siwangqishiq** [comment]
阿里的KPI项目罢了 维护的人升高P了  自然不管了

**Comment by fisherlee** [comment]
上面这些评论，怎么那么像淘宝刷好评的。

**Comment by JeremyYvv** [comment]
就希望像，就越看越像



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月17日(周四) 下午4:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/weex] 据说week被阿里放弃啦，我觉得这个框架很nice，为什么不继续做呢？ (#3227)




 
上面这些评论，怎么那么像淘宝刷好评的。

**Comment by roronoaxyz** [comment]
是真的有线上产品用这套框架的，阿里的同事请不要放弃；

**Comment by Tianwen9579** [comment]
现在有点期待weex支持华为鸿蒙了

**Comment by lovederh** [comment]
weex 深度用户+1

**Comment by Hanks10100** [comment]
感谢支持，issue 先关掉了。
