### ISSUE TITLE
v-if闪动问题

### ISSUE THREAD

**Issue by w-z-y** [alibaba/weex#3235]
使用v-if对组件进行切换显隐，出现布局错位闪动

**Comment by w-z-y** [comment]
给组件设置v-if="false"，组件的生命周期还是走了

**Comment by Txink** [comment]
可以试下只在子组件构造的时候使用v-if，后续的显隐父组件通过属性修改子组件visibility样式属性来控制；子组件默认是hidden，在mounted的时候如果希望显示修改为visible
