### ISSUE TITLE
textarea support 

### ISSUE THREAD

**Issue by zhangmengxue** [alibaba/weex#324]
well, Whether to support \<textarea\> ? I was reading this:[components](https://github.com/alibaba/weex/blob/dev/doc/components/main.md)  . It's not mentioned.

**Comment by Jinjiang** [comment]
This component is working in progress. Thanks very much.

**Comment by Jinjiang** [comment]
同步一下
目前 iOS 和 Android 已经支持，@MrRaindrop 这边会尽快完成 HTML5 的版本

**Comment by acton393** [comment]
textarea 已经支持 ，暂时先关闭了， https://github.com/weexteam/article/issues/95
