### ISSUE TITLE
如何全局引入自己封装的组件，按照官网说的实现不了

### ISSUE THREAD

**Issue by w-z-y** [alibaba/weex#3240]

**Comment by jianhan-he** [comment]
http://doc.weex.io/zh/guide/extend/extend-ios.html#扩展组件 按这个文档实现不了，有报啥错误吗

**Comment by farmerhanxin** [comment]
可以的啊 我这里正常

**Comment by Hanks10100** [comment]
没有后续回复，issue 先关掉了。如果依然有疑问，请提供详细的信息并新建 issue。
