### ISSUE TITLE
[Android]安装包aab格式，运行时无法正常加载页面。安装包apk格式，正常

### ISSUE THREAD

**Issue by hshm** [alibaba/weex#3241]
## Describe the bug
google play 要求8月份新上架的app，须采用aab格式(非apk)发布。
生成官方playgroud的aab格式安装包，无法正常加载weex页面

## Environment
* Device: [sm]
* OS: [android]
* Build from source [yes]

## Expected behavior
正常展示页面

**Comment by hshm** [comment]
研究了下，已经解决了一半问题：android 9(包含)以下，aab的安装包能正常加载weex页面。

**Comment by hshm** [comment]
原因：aab格式安装包，通过bundletool安装到手机，根据cpu等维度，拆分了。如下
![image](https://user-images.githubusercontent.com/3402827/125275059-25b60f80-e341-11eb-834f-8c422cbaf275.png)
即：base.apk中不再包含so文件, so文件全部在 split_config.arm64_v8a.apk中。

但代码中还是去base.apk中获取，如下，所以导致了问题出现：
WXEnvironment.java
![image](https://user-images.githubusercontent.com/3402827/125275606-d45a5000-e341-11eb-9c25-e5b7989415b9.png)

**Comment by hshm** [comment]
我现在的问题：在Android 10 和 Android 11上，还是无法加载weex，其他android版本无问题。
JsFrameworkInit 没有初始化成功，日志：
![image](https://user-images.githubusercontent.com/3402827/125276087-62ced180-e342-11eb-971d-98919c08dab1.png)

**Comment by hshm** [comment]
最后追踪到下面这个方法没返回成功。看了会c++代码，没太懂，没思路了...,求救
mWXBridge.initFrameworkEnv(framework, assembleDefaultOptions(), crashFile, pieSupport)

**Comment by JeremyYvv** [comment]
> 最后追踪到下面这个方法没返回成功。看了会c++代码，没太懂，没思路了...,求救
> mWXBridge.initFrameworkEnv(framework, assembleDefaultOptions(), crashFile, pieSupport)

framework 入参有值吗

**Comment by joy2helloworld** [comment]
也遇到了相同问题，有什么解决方案吗？

**Comment by katherine95s** [comment]
> 测试机型适配时发现了**问题**：在Android 10 和 Android 11上，还是无法加载weex，其他android版本无问题。
> JsFrameworkInit 没有初始化成功，日志：
> ![image](https://user-images.githubusercontent.com/3402827/125276087-62ced180-e342-11eb-971d-98919c08dab1.png)

确认下com.taobao.weex.WXEnvironment.java是否被混淆过

**Comment by miomin** [comment]
aab格式之前不支持，问题我们内部在看了。

**Comment by hshm** [comment]
> aab格式之前不支持，问题我们内部在看了。

希望我上面的对你们有帮忙，通过重新拷贝一份so文件，android 10以下没问题了，10以上有问题。

**Comment by hshm** [comment]
> > 最后追踪到下面这个方法没返回成功。看了会c++代码，没太懂，没思路了...,求救
> > mWXBridge.initFrameworkEnv(framework, assembleDefaultOptions(), crashFile, pieSupport)
> 
> framework 入参有值吗
有值，如下：
![image](https://user-images.githubusercontent.com/3402827/126479981-481308a4-abc5-4801-ba9e-d53a3cec0533.png)

**Comment by hshm** [comment]
一直以为so路径问题，通过打印C++端的代码，各种so路径又符合预期
![image](https://user-images.githubusercontent.com/3402827/126734513-03b95f97-b258-4bce-93b4-2136383bf258.png)

**Comment by hshm** [comment]
通过进一步在C++打印日志，在关闭文件是报错：
![image](https://user-images.githubusercontent.com/3402827/126734623-77dd9fb1-3870-407e-bbb3-db4e8acd90ce.png)

报错信息：
![image](https://user-images.githubusercontent.com/3402827/126734651-d8c337a7-3928-477e-ad84-acefb685f573.png)

尝试把 关闭文件的代码去掉，结果还是一样，初始化不成功：

![image](https://user-images.githubusercontent.com/3402827/126734769-d7613251-8c4a-4778-9692-06f21395d751.png)

**Comment by katherine95s** [comment]
weex初始化时需要执行weexjsb.so拉起js子进程。Android gradle plugin 3.3.0对aab做了优化，默认不拷贝native library至libs路径，导致weexjsb.so执行失败。可通过关闭此优化绕过。

According to the Gradle release note
> When building an Android App Bundle, APKs generated from that app bundle that target Android 6.0 (API level 23) or higher now include uncompressed versions of your native libraries by default. This optimization avoids the need for the device to make a copy of the library and thus reduces the on-disk size of your app. If you'd rather disable this optimization, add the following to your gradle.properties file:

`android.bundle.enableUncompressedNativeLibs = false`

**Comment by hshm** [comment]
已经验证，上述方案能解决问题
