### ISSUE TITLE
[iOS] weex 0.30.0 在iOS 15 beta3 下 WXTableview 会出现空白显示问题

### ISSUE THREAD

**Issue by ldkfreetoplay** [alibaba/weex#3244]
## Describe the bug

[iOS] weex 0.30.0 在iOS 15 beta3 下 WXTableview  会出现空白显示问题，触发了加载更新会出现。

表现为有一个tableViewCell 上没有subviews 

## Environment

device：模拟器  iOS 15，5 th，ipad pro 12.9-inch

**Comment by zymxxxs** [comment]
请问该问题解决了嘛？

**Comment by ldkfreetoplay** [comment]
> 请问该问题解决了嘛？

看起来像是 iOS 15 tableview 底层机制改变导致weex 在上下滑动的时候响应 didEndDisplayingCell 代理 提前释放了 cell 的wxview。

不知道是不是iOS 15 beta的bug，更新了最新的beta版本了这个问题还存在

我准备的临时解决方案是在 tableView willDisplayCell 代理里面 再调用一遍 cellForRowAtIndexPath 设置 wxview 的代码，显示是正常了，但是看内存数据 ，这样处理内存释放会没那么及时。

**Comment by zymxxxs** [comment]
prefetchingEnable 设置为 false 就可以了，iOS 15 新属性。

**Comment by ldkfreetoplay** [comment]
> prefetchingEnable 设置为 false 就可以了，iOS 15 新属性。

有效果，谢谢

**Comment by ldkfreetoplay** [comment]
可以在 ui 渲染前 设置UITableView全局appearance 来解决这个问题
      
if #available(iOS 15.0, *) {
      UITableView.appearance().isPrefetchingEnabled = false
} else { /* do nothing */ }
