### ISSUE TITLE
[Android][iOS][Dev-tool] iOS15下List的Header组件会有上边距

### ISSUE THREAD

**Issue by niesai** [alibaba/weex#3258]
iOS15下List的Header组件会有上边距

**Comment by Txink** [comment]
iOS15下UITableView新加了一个属性sectionHeaderTopPadding，你在[WXListComponent viewDidLoad]里设置该属性为0即可，后面我们会发布适配iOS15的版本

**Comment by Txink** [comment]
https://github.com/alibaba/weex/pull/3263
