### ISSUE TITLE
weex web @message no use

### ISSUE THREAD

**Issue by wuxq** [alibaba/weex#3259]
您好，
 我在weex中需要用到web组件，由于需要与web组件交互，我查询发现以前在weex中可以用 
`  <web :src="src" ref="webview" @pagefinish="onPageFinish" @error="onError" @message="onMessage" :style="webStyle"></web>` 
 的形式，通过@message 来获取web中postMessage过来的数据，但实际我在ios上没能收到web端发给weex的数据，请问是这个功能改了么。
谢谢！

**Comment by wuxq** [comment]
能帮我解决一下吗， 谢谢
@Txink

**Comment by Txink** [comment]
> 能帮我解决一下吗， 谢谢 @Txink

Weex web组件底层实现在升级到WKWebView后不支持这种方式了，这周我会提个PR修复问题

**Comment by wuxq** [comment]
好的 谢谢

**Comment by Txink** [comment]
@wuxq  https://github.com/alibaba/weex/pull/3264
