### ISSUE TITLE
[iOS]侧滑奔溃

### ISSUE THREAD

**Issue by tiankongzhishang** [alibaba/weex#3262]
侧滑后，component销毁，异步请求返回数据，调起不存在的component方法导致奔溃
目前 我在 WXComponentMethod 类里面  if (!component) {} 里面不存在 component 就return

**Comment by Txink** [comment]
有复现demo么

**Comment by tiankongzhishang** [comment]
没有，就我们的项目，而且返回的时候WeexViewController打印销毁了，然后这个时候应该请求（我做的是二维码请求）才结束，weex那边的代码自动调起了我的已销毁的component展示二维码的方法

**Comment by Txink** [comment]
> 侧滑后，component销毁，异步请求返回数据，调起不存在的component方法导致奔溃 目前 我在 WXComponentMethod 类里面 if (!component) {} 里面不存在 component 就return

已参考你的改动修复 https://github.com/alibaba/weex/pull/3274
