### ISSUE TITLE
[iOS]list在iOS上滑动 部分内容会消失   iOS15的BUG

### ISSUE THREAD

**Issue by 995996812** [alibaba/weex#3266]
list在iOS上滑动 部分内容会消失   iOS15的BUG

**Comment by zymxxxs** [comment]
#3244

**Comment by yy981998440** [comment]
这个问题怎么解决啊

**Comment by yy981998440** [comment]
我也遇到了

**Comment by 995996812** [comment]
> 我也遇到了

在WXListComponent的viewDidLoad里加 
 if (@available(iOS 15.0, *)) {
        _tableView.sectionHeaderTopPadding = 0;
        _tableView.prefetchingEnabled = NO;
   }

**Comment by topcloud-xx** [comment]
> > 我也遇到了
> 
> 在WXListComponent的viewDidLoad里加 if (@available(iOS 15.0, *)) { _tableView.sectionHeaderTopPadding = 0; _tableView.prefetchingEnabled = NO; }
果然有效，感谢
