### ISSUE TITLE
weex 2.0

### ISSUE THREAD

**Issue by JeremyYvv** [alibaba/weex#3270]
After attending the [2021 XITU developer conference](https://www.bagevent.com/event/7481268?aId=1743343) where weex team show us the new powerful weex framework, 
So will the weex 2.0 project be open source? Is there any plan for it?

Thanks for your response, expecting!!!

**Comment by Hanks10100** [comment]
Yes, Weex 2.0 will be open source, but not now. It's already used in production, documents, devtools, and compilers are still under development, which is not ready for open source yet.

We plan to release the alpha version internally in early 2022, depending on the feedback, then decide when to open source.

**Comment by yangtianrui95** [comment]
@Hanks10100  Hi ,  Is there any progress about Weex 2.0 ?

**Comment by Hanks10100** [comment]
@yangtianrui95 The project goes well, and the usage is growing.

**Comment by eagle518** [comment]
Any news for 2.0?

**Comment by plainfire** [comment]
Any news for 2.0?

**Comment by ScathonLin** [comment]
> 

It's 2023 now, weex hasn't been open source

**Comment by a83988029** [comment]
cold了
