### ISSUE TITLE
pre-build 文件生成说明文档有吗？

### ISSUE THREAD

**Issue by gongcf** [alibaba/weex#3276]
您好
有没有pre-build 文件生成说明文档，如何自己修改相关内容

**Comment by Hanks10100** [comment]
在 [HOW-TO-BUILD.md](https://github.com/alibaba/weex/blob/master/HOW-TO-BUILD.md#build-javascript-framework) 有介绍，在 `npm install` 安装好依赖之后，执行 `npm run build:jsfm` 可以构建。

**Comment by Hanks10100** [comment]
源码文件在 runtime 目录中。
