### ISSUE TITLE
[iOS]textarea组件，rows设置成100，获取焦点的时候会顶出屏幕  weex version is 0.9.5

### ISSUE THREAD

**Issue by yuditxj** [alibaba/weex#3278]
## To Reproduce
<scroller>
<textarea style="background-color: darkred;"  rows="100"></textarea>
</scroller>

## Expected behavior

获取焦点时焦点所在的位置超出了屏幕最上方

**Comment by Txink** [comment]
试下更新到最新版本，0.30.0

**Comment by yuditxj** [comment]
也是依然有问题

**Comment by Txink** [comment]
```vue
<template>
  <textarea class="text" rows="100"></textarea>
</template>

<style scoped>
.text {
  background-color: blue;
  width: 500px;
  height: 500px;
}
</style>
```

我试了下OK的，超出屏幕，我怀疑和你ViewController有关，你需要确保WXRootView是在屏幕内，没有被导航栏部分挡住
