### ISSUE TITLE
[Discuss] The lifecycle of weex.

### ISSUE THREAD

**Issue by terrykingcha** [alibaba/weex#331]
# Lifecycle

### createInstance
![createInstance](http://gw.alicdn.com/mt/TB1NL3tJVXXXXaLXVXXXXXXXXXX-1024-768.jpg)

### refreshInstance
![refreshInstance](http://gw.alicdn.com/mt/TB1HsoQJVXXXXcyXXXXXXXXXXXX-1024-768.jpg)

### fireEvent/callback
![fireEvent/callback](http://gw.alicdn.com/mt/TB1BKUFJVXXXXXIXFXXXXXXXXXX-1024-768.jpg)

### destoryInstance
![destoryInstance](http://gw.alicdn.com/mt/TB1je7BJVXXXXbyXFXXXXXXXXXX-1024-768.jpg)

### navigate
![navigate](http://gw.alicdn.com/mt/TB1YTwmJVXXXXb6XVXXXXXXXXXX-1024-768.jpg)

## The API for Native

```javascript
/**
 * @param {string} instanceId - the instance id
 * @param {string} name - the notified name(appear/disppear/destory/created/updated/refreshed)
 * @param {object} options - any options
 */
global.notifyInstance(instanceId, name, options)
```

## The API in DSL

```javascript
/**
 * @param {string} name - the notified name
 * @param {function} callback - call when notified
 */
vm.$observe(name, callback)
```

**Comment by Jinjiang** [comment]
Hi, this issue will be collected into #1494 temporarily
Thanks.
