### ISSUE TITLE
Weex 不再维护了嘛？

### ISSUE THREAD

**Issue by yaoyue** [alibaba/weex#3332]

**Comment by j717273419** [comment]
已经从apache退休了，大概率是要停止了

**Comment by myfllower** [comment]
会等来weex2的

**Comment by ICECHN** [comment]
> 会等来weex2的

不可能了，他们已经不更新了

**Comment by loumzy** [comment]
可以考虑一下腾讯的 hippy 了，

**Comment by firekyrin** [comment]
来信收悉，非常感谢！============http://www.firekyrin.com

**Comment by alterass** [comment]
阿里巴巴经常中断开源计划，不建议再使用他们家产品

**Comment by xiongchen2012** [comment]
yes baby

**Comment by mengqutaoyuan** [comment]
没事，只要保证你在这家公司的时间没有他们维护世界长就好。很多公司的寿命没有开源框架维护世界长

**Comment by abrahamgreyson** [comment]
贵公司发起的开源项目，一直以来都像个 JOKE， 无一例外。

**Comment by loumzy** [comment]
> 贵公司发起的开源项目，一直以来都像个 JOKE， 无一例外。

改用 hippy 吧，我们迁移过来了，成本还可以，大于用了两个月的时间
