### ISSUE TITLE
[Android][iOS] Slider内嵌的子组件 添加了 touchmove事件，左右滑动子组件时，子组件的滑动事件并不会被消费，而是触发了Slider自身的滑动，这个怎么处理？

### ISSUE THREAD

**Issue by AnFxy** [alibaba/weex#3335]
Slider内嵌的子组件 添加了 touchmove事件，左右滑动子组件时，子组件的滑动事件并不会被消费，而是触发了Slider自身的滑动，这个怎么处理？

**Comment by firekyrin** [comment]
来信收悉，非常感谢！============http://www.firekyrin.com
