### ISSUE TITLE
IOS css3属性transition 不生效

### ISSUE THREAD

**Issue by guoxi1994** [alibaba/weex#3345]
<div ref="an1" class="scene-head" :class="[isTurnOnAnimate && 'isTurnOnAnimate']" :style="{ height: imgHeight + 'px' }">
          <image
            ref="an2"
            class="scene-head-image"
            :class="[isTurnOnAnimate && 'isTurnOnAnimate']"
            :style="{ transform: `scale(${scaleMultiple})`, height: imgHeight + 'px' }"
            :src="scene.picUrl"
            placeholder="./assets/image/home/ad-default.png"
          />
          <div class="scene-head-linear"></div>
          <div class="scene-head-con">
            <text class="scene-name"></text>
            <text class="scene-desc"></text>
          </div>
        </div>

.isTurnOnAnimate {
    transition: height,transform 0.5s ease-in-out;
}

**Comment by firekyrin** [comment]
来信收悉，非常感谢！============http://www.firekyrin.com

**Comment by guoxi1994** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by guoxi1994** [comment]
animation.transition(this.$refs.an1, {
          styles: {
            height: 508
          },
          duration: 500, //ms
          timingFunction: 'linear',
          needLayout: true,
          delay: 0 //ms
        })
 用这种方式可以实现回弹动画，但是会导致另外一个问题！先执行完动画，布局再改变（给人一个跳动的感觉），应该是needLayout没有生效

**Comment by guoxi1994** [comment]
animation.transition(this.$refs.an1, {
styles: {
height: 508
},
duration: 500, //ms
timingFunction: 'linear',
needLayout: true,
delay: 0 //ms
})
用这种方式可以实现回弹动画，但是会导致另外一个问题！先执行完动画，布局再改变（给人一个跳动的感觉），应该是needLayout没有生效

**Comment by guoxi1994** [comment]
> 来信收悉，非常感谢！============http://www.firekyrin.com

animation.transition(this.$refs.an1, {
styles: {
height: 508
},
duration: 500, //ms
timingFunction: 'linear',
needLayout: true,
delay: 0 //ms
})
用这种方式可以实现回弹动画，但是会导致另外一个问题！先执行完动画，布局再改变（给人一个跳动的感觉），应该是needLayout没有生效

**Comment by Hanks10100** [comment]
在 Weex 1.0 里不支持 css 的 transition。

**Comment by guoxi1994** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
