### ISSUE TITLE
emoji 代码需要在底层里过滤处理

### ISSUE THREAD

**Issue by oncity** [alibaba/weex#350]
JSON 含有 emoji 代码，会引起 utf8 crash ，希望能处理这个严重问题

**Comment by LiushuiXiaoxia** [comment]
怎么解决的？确实，如果好友表情，就会出现这个错误。

**Comment by YorkShen** [comment]
@LiushuiXiaoxia  这是Android 6.0以下，系统NDK的一个bug。在6.0以下，NDK只能处理Modified UTF-8，如果处理了非BMP字符，就会导致crash。emoji属于SMP字符，所以会触发上述问题。
参考 https://github.com/alibaba/weex/issues/313

**Comment by Jinjiang** [comment]
这个问题由于长期没有讨论，所以做关闭处理
如果有后续讨论可以在这里继续
谢谢支持
