### ISSUE TITLE
[Discuss] setTimeout/clearTimeout capability

### ISSUE THREAD

**Issue by terrykingcha** [alibaba/weex#351]
According to async process, Weex Render can't return a timer id synchronously. So we will try to take  the way below of returning the function id and mapping it to a real timer id:

@cxfeng1 

![timer](http://gw.alicdn.com/mt/TB1SHR_KXXXXXbbXXXXXXXXXXXX-1024-768.png)

**Comment by cxfeng1** [comment]
supported in v0.6.1
