### ISSUE TITLE
[Discuss] The standard spec for jsfm and transformer to follow.

### ISSUE THREAD

**Issue by terrykingcha** [alibaba/weex#398]
In transformer, give every feature or syntax a bitmask. For example,  a `(k, v) in list` repeat syntax is 1 as bitmask, and a `track-by` feature is 2 as bitmask.

Then check and sum these bitmasks of features while transforming the source code, and give the result in the top of bundle file like:

```
'use spec: 3'

define(...)
...
```

So that jsfm can check the spec and warn to handle the exceptions if some specs are not supported yet in current version of jsfm.

**Comment by Jinjiang** [comment]
Finally we used #856 way instead. And this issue can be reopened again if more discussion needed.
Thanks.
