### ISSUE TITLE
Geolocation API supported

### ISSUE THREAD

**Issue by JakeLin** [alibaba/weex#422]
I have looked through the documentation at http://alibaba.github.io/weex/doc/ and can't find how weex can support Geolocation. I am making a Weather app using Weex like 
- Swift Weather: https://github.com/JakeLin/SwiftWeather 
- React Native Weather: https://github.com/JakeLin/ReactNativeWeather

I need to get the current location to display the weather info. In React Native, we can do it like https://github.com/JakeLin/ReactNativeWeather/blob/master/src/components/WeatherView.js#L75

```
 startLocationSearch() {
    navigator.geolocation.getCurrentPosition(
      location => {
        this.queryOpenWeatherMap(location);
      },
      error => {
        this.setState({
          message: error.message || error
        });
      },
      {enableHighAccuracy: true, timeout: 2000, maximumAge: 1000}
    );
  }
```

Thanks
Jake

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
