### ISSUE TITLE
Cannot resolve module '@weex-module/modal'

### ISSUE THREAD

**Issue by Rowandjj** [alibaba/weex#452]
```
//sample.js
var stream = require('@weex-module/stream');
var modal = require('@weex-module/modal');
...
```

is `require` statement can only use in `.we` file?

**Comment by Jinjiang** [comment]
Hi please check this faq "Dependencies in frontend" http://alibaba.github.io/weex/doc/faq.html

> We will bring a better syntax design in the future.

Thanks.
