### ISSUE TITLE
box-shadow not work

### ISSUE THREAD

**Issue by Rowandjj** [alibaba/weex#478]
does weex support css3 box-shadow?

**Comment by Jinjiang** [comment]
Hi, this issue will be closed and collected into #1494 which collects all new feature requests and inactive open discussions. We hope to do this to make sure the open issues represent current focus and active jobs in community and the team. If we decide to resolve this problem or make it active. It will be reopened again.
Thanks for your support.

**Comment by kfeagle** [comment]
https://github.com/alibaba/weex/pull/2709

**Comment by kfeagle** [comment]
#2709
