### ISSUE TITLE
Toast(modal) behavior is different from native toast

### ISSUE THREAD

**Issue by markzhai** [alibaba/weex#49]
In Android native Toast, if one toast is still showing, and the second one comes, the first one will soon be replaced (may with a crash animation)

While in weex, the second toast (or you may call it modal) can appear only if the first completes its showing duration. This problem is more serious if we have a sequence of toast, which makes user have a wait a long long time to see all toasts.

**Comment by zshshr** [comment]
fixed ，please check the latest version @markzhai
