### ISSUE TITLE
[Discuss] Support more scheme and relative path

### ISSUE THREAD

**Issue by luics** [alibaba/weex#497]
Support relative/local path in components or modules:
## Components
1. image
   - relative + local
2. video
   - relative + local
3. a
4. web
## Modules
1. stream
   1. sendHttp
   2. fetch (0.6)
2. webview
3. navigator

**Comment by sospartan** [comment]
相对路径可以简单的使用bundle js的url 作为base来实现,在开发期(或者使用远程bundle js文件时)使用server的地址;在使用手机本地bundle js文件时,使用对应的文件相对路劲.

**Comment by sospartan** [comment]
## draft
### Supported url format and common rules:
- relative path:   
Path start with `/` will normally trade as related to the url of page, which can get by api `sth api`. 

- `http(s)` scheme url:
Content with http url will get by http request.

- other scheme url:
It's unknown for weex framework, will not try process by default. Application with these urls have to process by custom component or module.

**Comment by luics** [comment]
0. relative path 
    0. includes `.`, `..` and composed one like `./.././..`.
    0. `/` should be trade as related to **root** of the page url got from `this.$getConfig`
0.  #808 baseUrl
0. `file:///path/to/stuff` , see https://tools.ietf.org/html/rfc3986#section-1.1

**Comment by lzyzsd** [comment]
@sospartan @luics how about Android&iOS resource images, which will get 1x or 2x or 3x pic depends on device

**Comment by sospartan** [comment]
@lzyzsd these resource files can not use cross-platform. It's not a recommend way to use image. So first version of our path spec will not cover that.

**Comment by sospartan** [comment]
## Proposal：
Reference： w3c HTML 4.01 Specification [Basic HTML data types : uri](https://www.w3.org/TR/html4/types.html#type-uri)

Basic http-scheme URL is already supported, this proposal is going to make up weex spec with necessary URI support.

**These spec should apply to components/modules with URI attributes or resource location. Such as `image`,`video`,`web` etc.**

### relative URI:   
As defined in W3C spec
> Relative URIs are resolved to full URIs using a base URI

In Weex `base URI` is the page url, return by `$getConfig(). bundleUrl`. It's provided by native.

Weex will supoort relative URI start with `/`(relative root of base URI), `.`, `..`.

### URI-Adapter
New URI-Adapter will let application to customize URI handle, such as custom URL scheme, file location in disk etc.


The default URI-Adapter privoded by SDK will cover common needs:

- `http(s)` scheme url:
Content with `http://..` url will get by http request.

- `file` scheme url:
Content with `file:///path/to/stuff` url will fetch by local file path. see https://tools.ietf.org/html/rfc3986#section-1.1

- other scheme url:
It's unknown for weex framework, will not try process by default. Application with these urls have to process by custom component or module.

Or developers can override default URI-adapter by own implementation.

**Comment by spiritelf** [comment]
现在支持加载本地图片了吗？

**Comment by sospartan** [comment]
@spiritelf 支持了 支持本地文件 也只是res目录的文件 ，0.9版本发布，就在这几天。

**Comment by spiritelf** [comment]
以前的需要做什么处理？如何和html5统一？

**Comment by sospartan** [comment]
@spiritelf 不需要做处理 以前不支持相对路径和本地路径  ，html5不支持本地路径，相对路径这些是标准，都支持的

**Comment by spiritelf** [comment]
不太明白你说的？ @sospartan

**Comment by spiritelf** [comment]
现在版本用相对路径表示都可以吗？ 还是？

**Comment by sospartan** [comment]
@spiritelf 要等0.9版本，当前的0.8是不支持的

**Comment by spiritelf** [comment]
好的  那现在有什么办法避过这个吗？

**Comment by sospartan** [comment]
@spiritelf 现在没有其他办法，目前只支持绝对路径的url。

**Comment by spiritelf** [comment]
感觉要做一个app出来还有很长路啊。。

**Comment by liujianying** [comment]
0.9版本发布，就在这几天,这才是好消息, 不过list 控件说实话才是大问题, 自定义刷新效果太差了

**Comment by yulinho** [comment]
升级0.94了。咋写啊。file:///assets/img/test.png 没有显示呢

**Comment by chinafootballyu** [comment]
@sospartan  加载本地图片的话，有demo吗？现在weex项目的examples还没有关于如何使用的demo！能否更新下。

**Comment by talliujobs** [comment]
现在可以加载android工程内的图片吗？有demo吗？

**Comment by chinafootballyu** [comment]
@talliujobs 
```
<div class="local-img">
	<text>加载本地图片</text>
	<image style="width: 20; height: 30" src="local:///fileName"></image>
</div>
```
加载本地图片使用路径local:///fileName，不要加文件后缀（如.png这种），文件放在android工程的drawable目录下。文档不全，都是自己试的！原来之前自己也提过这个问题！

**Comment by hphua** [comment]
@chinafootballyu 
local:///fileName方式，Android可用，iOS验证无效。

**Comment by chinafootballyu** [comment]
@hphua 嗯，这个是android的，ios的没整过。。。我这边只有windows系统

**Comment by hphua** [comment]
加载js同级目录下的图片，应用于js文件和图片资源随APP一起发布的场景。
【Android】
eg:<img src="images/image.jpg" style="width: 100px;height: 100px"/>
其中images目录与js是同级。
注：weexsdk android 使用Picasso加载图片。加载assets的图片，路径是以file:///android_asset开始。所以要改造ImageAdapter代码，将file://assets替换为file:///android_asset。
`public void setImage(final String url, final ImageView view,
                         WXImageQuality quality, final WXImageStrategy strategy) {

        WXSDKManager.getInstance().postOnUiThread(new Runnable() {

            @Override
            public void run() {
                if (view == null || view.getLayoutParams() == null) {
                    return;
                }
                if (TextUtils.isEmpty(url)) {
                    view.setImageBitmap(null);
                    return;
                }
                String temp = url;
                if (url.startsWith("//")) {
                    temp = "http:" + url;
                }

                if (temp.startsWith("./")) {
                    String localUrl = AppConfig.getLocalUrl();
                    String basePath = localUrl.substring(0, localUrl.lastIndexOf("/"));
                    temp = String.format("%s%s", basePath, url.substring(1, url.length()));
                }

                if (temp.startsWith("file://assets")) {
                    temp = url.replace("file://assets", "file:///android_asset");
                    Log.d("ImageAdapter", "url:" + temp);
                }
                if (view.getLayoutParams().width <= 0 || view.getLayoutParams().height <= 0) {
                    return;
                }

                if (!TextUtils.isEmpty(strategy.placeHolder)) {
                    Picasso.Builder builder = new Picasso.Builder(WXEnvironment.getApplication());
                    Picasso picasso = builder.build();
                    picasso.load(Uri.parse(strategy.placeHolder)).into(view);

                    view.setTag(strategy.placeHolder.hashCode(), picasso);
                }


                Picasso.with(WXEnvironment.getApplication())
                        .load(temp)
                        .into(view, new Callback() {
                            @Override
                            public void onSuccess() {
                                if (strategy.getImageListener() != null) {
                                    strategy.getImageListener().onImageFinish(url, view, true, null);
                                }

                                if (!TextUtils.isEmpty(strategy.placeHolder)) {
                                    ((Picasso) view.getTag(strategy.placeHolder.hashCode())).cancelRequest(view);
                                }
                            }

                            @Override
                            public void onError() {
                                if (strategy.getImageListener() != null) {
                                    strategy.getImageListener().onImageFinish(url, view, false, null);
                                }
                            }
                        });
            }
        }, 0);
    }`

【iOS】
[iOS集成weex 实现加载网络图片](http://www.jianshu.com/p/9daa4735926a)
