### ISSUE TITLE
visibility:hidden need enhancement

### ISSUE THREAD

**Issue by amdgigabyte** [alibaba/weex#498]
`visibility:hidden;` can hide an element, but the hidden element can still be 'clicked', Is there any way to hide the element,but also hide the behavior of the element?

**Comment by boboning** [comment]
hi，what is your platform？ android or ios ?
Could you provide us the your code block， we can debug for you.

**Comment by amdgigabyte** [comment]
@boboning android and ios both have this problem。

**Comment by Jinjiang** [comment]
Hi, this issue will be closed and collected into #1494 which collects all new feature requests and inactive open discussions. We hope to do this to make sure the open issues represent current focus and active jobs in community and the team. If we decide to resolve this problem or make it active. It will be reopened again.
Thanks for your support.
