### ISSUE TITLE
text组件位置不对 

### ISSUE THREAD

**Issue by shiying** [alibaba/weex#506]
在text组件 align-items H5执行水平效果 native没有效果
justify-content 没有效果

**Comment by luics** [comment]
请贴个图和代码

> 如果是 ***Bug***，请提供：复现步骤（推荐有截图）、error/crash log、设备型号、OS 版本、App 版本（playground 版本或自己的 app）。

**Comment by shiying** [comment]
http://weex.alibaba-inc.com/playground/375c11fc576d0edf6eda4b77d15916ac

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
