### ISSUE TITLE
border-style 在native只支持solid

### ISSUE THREAD

**Issue by shiying** [alibaba/weex#507]
border-style 在native只支持solid,

**Comment by luics** [comment]
方便贴个图和代码吗？

> 如果是 ***Bug***，请提供：复现步骤（推荐有截图）、error/crash log、设备型号、OS 版本、App 版本（playground 版本或自己的 app）。

**Comment by YorkShen** [comment]
Android已支持， https://github.com/sospartan/weex/tree/tb-dev， 尚未合并到主分支。 @shiying

https://github.com/alibaba/weex/issues/499
