### ISSUE TITLE
E/jsengine

### ISSUE THREAD

**Issue by muyuren** [alibaba/weex#522]
com.alibaba.weex E/jsengine:  ReportException :undefined:3: SyntaxError: Unexpected token < 
![screenshot_2016-06-20-23-38-33-262_weex](https://cloud.githubusercontent.com/assets/3434402/16200519/47ca050c-3740-11e6-984d-c20ed5ed4b8b.png)

**Comment by luics** [comment]
@muyuren does this exist?

**Comment by Jinjiang** [comment]
Because it's such a long time no more response received. This issue would be closed.
More discussion is welcome on Gitter chat room https://gitter.im/weexteam/cn or https://gitter.im/weexteam
Thanks.
