### ISSUE TITLE
关于适配不同屏幕的一个问题

### ISSUE THREAD

**Issue by shendy1991** [alibaba/weex#524]
现在出现一个问题，就是在不同的屏幕，我根据不同的屏幕，计算好每个区域块的高度，然后运行到设备里，渲染出来之后，内容区域高度和我计算出来的高度出现误差，以至于我下方需要衔接的uiview和渲染出来的页面中间出现一段空白区域。

做了几个测试，6s屏幕的渲染出高度和计算高度一样，5s和4s渲染出来的高度小于计算出的高度，plus渲染出高度要高于计算出高度。

plus出现的问题主要因为是在设备里取到屏幕的宽度是828，而config.env.deviceWidth取到的高度是1242，两者不一样，所以基于width算出的高度就有偏差；但是5s和4s无论native取出的宽度还是config.env.deviceWidth 取出的宽度都是一样的，但是渲染出来后还是按一定比例缩小了，不知道什么机制导致的。

**Comment by asd8855** [comment]
@cxfeng1 我需要将scroller 的高度设置为屏宽-64 应该怎么设置
