### ISSUE TITLE
Tutorial 里的how-tos 少了好几篇文档啊

### ISSUE THREAD

**Issue by devilthrone** [alibaba/weex#543]
How-tos

Manage Your File Structure
Maintain Your Component Code
Require 3rd-party Libs
Transform Code Into JS Bundle
Preview in Browser
Preview in Playground App
Customize a Native Component
Customize Native APIs
Debug with HTML5
Debug with Native
Debug with Remote Tools
Manage Data with a High-level CMS

现在只有 3 4 5 三篇文档  其它文档都没有？

**Comment by JohnWong** [comment]
@lvscar Maintain Your Component Code 仍然缺失。http://alibaba.github.io/weex/doc/how-to/maintain-your-component-code.md

**Comment by DoranYun** [comment]
@devilthrone Hi，中文文档正在整理中，目前Preview in Browser，Preview in Playground App 已经合并到 [如何在本地开发 Weex 页面](http://alibaba.github.io/weex/cn/doc/develop-on-your-local-machine.html)。 Customize a Native Component 和 Customize Native APIs 移到了 [高阶知识](http://alibaba.github.io/weex/cn/doc/advanced/main.html) 当中。Debug with HTML5 还在 [在浏览器中调试](http://alibaba.github.io/weex/cn/doc/how-to/debug-with-html5.html)，Debug with Native 和 Debug with Remote Tools 内容太旧已经弃用，新的 debug 文档在 [如何使用 Devtools 调试 Weex 页面](http://alibaba.github.io/weex/cn/doc/how-to/debug-with-devtools.html)
