### ISSUE TITLE
wxc-navpage title-color invalid

### ISSUE THREAD

**Issue by nicefe** [alibaba/weex#548]
```
<wxc-navbar class="navbar" title="nice" background-color="#ffd900" title-color="#000000"></wxc-navbar>
```

the color of title in my page is still white.

---
otherwise,The doc says the background-color of wxc-navpage is default white and the  title-color is default black , but in reality both are opposite.

**Comment by boboning** [comment]
hi, we have checked our code. As we described in the document, it is ok. 
Can you try again or provide us the .we  file,  we can debug for you.

**Comment by Jinjiang** [comment]
Because there is no more discuss such a long time, this issue would be closed.
And it could be reopen anytime if more information supplied.
Also we could talk about the usage in Gitter.
Thanks.
