### ISSUE TITLE
建议支持图片加载事件

### ISSUE THREAD

**Issue by AnnZ** [alibaba/weex#553]
建议图片加载支持 load complete error readystatechange 等 js 事件；同时考虑对图片(audio/video)预加载的支持。

**Comment by acton393** [comment]
#975  增加了 图片的onload 事件， 可以获得是否成功加载图片

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
