### ISSUE TITLE
Playground 不能正常运行示例模块

### ISSUE THREAD

**Issue by yyxy** [alibaba/weex#574]
![screenshot_2016-06-24-11-53-42](https://cloud.githubusercontent.com/assets/5263136/16327553/e2d23c80-3a02-11e6-878c-dbb91c03660e.png)
![screenshot_2016-06-24-11-54-03](https://cloud.githubusercontent.com/assets/5263136/16327552/e2d06b6c-3a02-11e6-9bf6-b3bfb552948a.png)
![screenshot_2016-06-24-11-54-44](https://cloud.githubusercontent.com/assets/5263136/16327554/e2d38810-3a02-11e6-92c1-9bce88c4fe8d.png)

Playground 最新版，首页显示错乱， 另外扫码js, 不能正常运行， 空白。
型号：
Huawei x2 , GEM-703L , Android 5.0

之前的版本安装提示设备不支持weex。

**Comment by xkli** [comment]
新版本已经修复这个问题，下载地址：http://alibaba.github.io/weex/download.html，请验证，如果还有问题，麻烦反馈给我们
