### ISSUE TITLE
对于loadmore数据建议

### ISSUE THREAD

**Issue by overcls** [alibaba/weex#577]
对于list加载loadmore javascript 有没用简单的实例，

可以从实用角度来优化下demo 从远程api获取数据并展示

**Comment by QETHAN** [comment]
@MrRaindrop 

第一个list demo在iOS模拟器上有问题，上拉看不到加载更多。而且往下来返回顶部，还会自动回到底部。

![image](https://cloud.githubusercontent.com/assets/3423104/17124824/7e9e1996-5320-11e6-87ae-10bf25f93349.png)

**Comment by MrRaindrop** [comment]
@xkli https://github.com/alibaba/weex/pull/920 should fix this.
