### ISSUE TITLE
eclipse android 项目中怎样集成WEEX SDK

### ISSUE THREAD

**Issue by zxssteven** [alibaba/weex#588]
eclipse android 项目中怎样集成WEEX SDK？ 有人做过吗？能否提供一个简单的demo?

**Comment by sospartan** [comment]
你用maven来build的么?

**Comment by xkli** [comment]
可以把WEEX AAR文件转换成一个Library，方法请参考：http://www.jianshu.com/p/ccf306e08d5b

WEEX  AAR下载地址 https://bintray.com/alibabaweex/maven/weex_sdk
