### ISSUE TITLE
环境搭建问题

### ISSUE THREAD

**Issue by maomaoking** [alibaba/weex#591]
不知道环境搭建问题可不可以提？
我在 npm install 后启动 ./start 报错如下
![image](https://cloud.githubusercontent.com/assets/16420919/16371399/e9130d22-3c78-11e6-9703-bff9f9c608e6.png)
环境是mac环境，求大神解答

**Comment by Jinjiang** [comment]
@maomaoking 更多问题请移步到中文聊天室 https://gitter.im/weexteam/cn
这里我先关掉了

谢谢支持：）
