### ISSUE TITLE
modal执行alert方法时如何message是整数则native客户端crash

### ISSUE THREAD

**Issue by charlescui** [alibaba/weex#601]
0. It's ***RECOMMENDED*** to [submit PR](https://github.com/alibaba/weex/pulls) for typo, new demo or tiny bugfix.
0. If this's a ***BUG***, pls provide: course repetition, error/crash log, device model, OS version, App version (playground or other apps).
0. If this's a ***FEATURE***, pls provide: details, pseudo codes if necessary.

---

0. 我们***推荐***小问题直接[提 PR](https://github.com/alibaba/weex/pulls)，如错别字、新 demo 或 bugfix。
0. 如果是 ***Bug***，请提供：复现步骤（推荐有截图）、error/crash log、设备型号、OS 版本、App 版本（playground 版本或自己的 app）。
0. 如果是***新需求***，请提供：详细描述、应用场景、适当的伪代码（如有）。

BUG：

- 设备：iphon6p
- App版本：weex没有version参数，我也不知道什么版本。

modal执行alert的话，如果message是数字，那么native客户端会crash，比如如下代码：
```js
        var modal = require('@weex-module/modal');
        modal.alert({
          message: 0,
          okTitle: "OK"
        }, function() {
          // TODO after the alert is complete.
        })
```

改成字符串则没这个问题，以下代码OK：
```js
        var modal = require('@weex-module/modal');
        modal.alert({
          message: '0',
          okTitle: "OK"
        }, function() {
          // TODO after the alert is complete.
        })
```

这个问题会让调试代码非常困难，如果一不小心给message赋值为整数，根据crash信息去调查是查不到线索的。

**Comment by acton393** [comment]
hi @charlescui , #697   这个修复掉这个bug了，会把number 转换为string处理
