### ISSUE TITLE
new implementation advice of timer APIs in native

### ISSUE THREAD

**Issue by Jinjiang** [alibaba/weex#627]
* module: `timer`
* method:
  * `setTimeout(fnId: number, timeout: number)`
  * `setInterval(fnId: number, interval: number)`
  * `clearTimeout(fnId: number)`
  * `clearInterval(fnId: number)`

see more in [`ctrl.js`](https://github.com/alibaba/weex/blob/jsfm-feature-timer/html5/default/app/ctrl.js#L66:L88) in `jsfm-feature-timer` branch

**Comment by YorkShen** [comment]
Android finished.

**Comment by YorkShen** [comment]
`timeout` or `interval` should be a non-negative integer(the max of integer is 0x7FFFFFFF). If `timeout` or `interval` is negative, then it will be reset to zero.
