### ISSUE TITLE
631a91f8960dc28c2df1e23cb9a90d7ea10de73d 版本的 component/list/list-basic 显示错误。

### ISSUE THREAD

**Issue by sunbohong** [alibaba/weex#632]
631a91f8960dc28c2df1e23cb9a90d7ea10de73d 版本的 component/list/list-basic 显示错误。
tableview的高度为0。

![qq20160629-0 2x](https://cloud.githubusercontent.com/assets/7285119/16440327/6da9da86-3df3-11e6-8702-fa7820ca5e9a.png)

**Comment by acton393** [comment]
#664 fix list-basic.we height, please try again

**Comment by sunbohong** [comment]
@acton393  已经暂时正常了。
