### ISSUE TITLE
Why 'weex -s .' didn't work

### ISSUE THREAD

**Issue by johnzheng00** [alibaba/weex#636]
➜  weex git:(dev) weex -s .
info Wed Jun 29 2016 15:57:14 GMT+0800 (CST)http  is listening on port 8081 
info we file in local path . will be transformer to JS bundle
please access http://10.1.36.129:8081/

**Comment by shylauc** [comment]
同问，这个问题有没有解决掉？weex -s 出来的是文档，不是能渲染出的页面。

**Comment by lvscar** [comment]
目前的 -s  设计意图就是仅仅进行js bundle 转换.   直接渲染页面的需求我们后续会考虑，谢谢反馈  也欢迎提PR ：-）
