### ISSUE TITLE
navigator的push和pop方法中，设置'animated' : 'false'无效

### ISSUE THREAD

**Issue by charlescui** [alibaba/weex#651]
在`examples的navigator-demo.we`文件中

```js
    methods: {
      push: function() {
        var vm = this;
        var params = {
          'url':  this.baseURL + 'component/navigator-demo.js?test=1',
          'animated' : 'false',
        }
        vm.$call('navigator','push',params, function () {});
      },

      pop: function() {
        var vm = this;
        var params = {
          'animated' : 'false',
        }
        vm.$call('navigator','pop',params, function () {});
      },
    }
```

设置animated的参数为false，但动画效果依然有。期望结果应该是瞬间切换页面，无动画移动效果。

**Comment by boboning** [comment]
sorry，this is a bug in WXNavigationDefaultImp.m.    
`NSString *obj = [[param objectForKey:@"animated"] uppercaseString]; `  
UppercaseString should be lowercaseString.  If it is convenient, you can resolve this problem.  We will correct this mistake soon.
