### ISSUE TITLE
使用require('@weex-module/stream').fetch发起http请求，body参数丢失

### ISSUE THREAD

**Issue by wufenglover** [alibaba/weex#665]
详情代码如下：
var reqobj = {pageparam:{pageindex:1,rownumperpage:2},paper:{nodeid:"黑板报"}};
  			reqobj.pageparam.pageindex = this.pageindex;
  			reqobj.pageparam.rownumperpage = this.rownumperpage;
  			
  			require('@weex-module/stream').fetch({
				method: 'GET',
				url: 'http://app.finedo.cn/developer_service/service/developer/paper/querylist',
				body:"HTTPJSONKEY="+encodeURIComponent(JSON.stringify(reqobj)),
				type:'json'
			}, function(retdata) {
				retdata = JSON.stringify(retdata);
                                nativeLog(retdata);
	        }.bind(this),function(response){
			  
			});

**Comment by luics** [comment]
请补充信息：

> 如果是 ***Bug***，请提供：复现步骤（推荐有截图）、error/crash log、设备型号、OS 版本、App 版本（playground 版本或自己的 app）。

**Comment by sospartan** [comment]
请提供必要的信息

**Comment by acton393** [comment]
这个我来跟，之前有在qq上聊过

**Comment by acton393** [comment]
已经交流， 开发者使用 GET 方式提交Body数据， 改为用POST

**Comment by MrRaindrop** [comment]
感觉body应该改为data，然后GET请求可以把data带到url里面去，这样更方便使用。否则GET请求数据还要开发者自己去拼接url

**Comment by vczero** [comment]
@MrRaindrop data有一定的合理性。
