### ISSUE TITLE
http://weex.help 中文开发者社区欢迎你！

### ISSUE THREAD

**Issue by JerroldLee** [alibaba/weex#666]
http://weex.help 中文开发者社区欢迎你！

**Comment by luics** [comment]
手工点赞！

**Comment by wszgxa** [comment]
在issues发这个真的好吗？

**Comment by nick-ma** [comment]
不用备案？

2016-06-30 22:32 GMT+08:00 Hilu luke <notifications@github.com>:

**Comment by sablib** [comment]
500 status

**Comment by acton393** [comment]
500了

**Comment by Stephenhuashao** [comment]
刚接触这个Weex

**Comment by luics** [comment]
迁移至 https://github.com/alibaba/weex/wiki/Weex-Community
