### ISSUE TITLE
修改weex examples 内的 index.we 没有改变

### ISSUE THREAD

**Issue by 2010jing** [alibaba/weex#667]
修改weex examples 内的 index.we 里面的 {name: 'hello', title: 'Hello World-1111'}, 但是运行到 android 手机时， 没有发生变化，第一行 还是 Hello World, 并不是我修改的 Hello World-111

其二 
然后我也参考 https://github.com/dodola/WeexOne 这个例子 按照 作者说明那样 将weexone 放置于 examples 内 并且在 index.we 内添加了     {name: ‘WeexOne/index.js’, title: ‘WeexOne’}
, 再次安装在android手机上 还是不行，没有发生变化，并没有新增的 WeexOne

运行环境 
windows 7
android 小米3  4.4.4版本
android studio 2.1.2

---

0. 我们***推荐***小问题直接[提 PR](https://github.com/alibaba/weex/pulls)，如错别字、新 demo 或 bugfix。
0. 如果是 ***Bug***，请提供：复现步骤（推荐有截图）、error/crash log、设备型号、OS 版本、App 版本（playground 版本或自己的 app）。
0. 如果是***新需求***，请提供：详细描述、应用场景、适当的伪代码（如有）。

**Comment by yanyutao** [comment]
你写的不是严格的json数据好不，就是个普通对象

**Comment by 2010jing** [comment]
@yanyutao weex examples 内的 index.we 里面就是这样写的呀，我只是简单修改了一下title值，却没有改变， 请问一下 严格的json应该是要怎样写？

**Comment by Jinjiang** [comment]
example 修改之后需要一个编译的过程，运行 `npm run build:examples` 就可以看到效果了，实际运行的文件是一个同名的js

**Comment by 2010jing** [comment]
@Jinjiang  我已经重新 npm run build :examples 还是不行；
然后 我先 npm run clean  再 npm run build 也还是没有改变

**Comment by Jinjiang** [comment]
你预览的方式是什么

**Comment by Jinjiang** [comment]
使用问题来这里讨论吧 https://gitter.im/weexteam/cn github issues 新功能或开放讨论会多一些
谢谢支持
