### ISSUE TITLE
恢复vue的指令语法

### ISSUE THREAD

**Issue by transtone** [alibaba/weex#668]
vue的v指令语法简介高效，什么双大括号的插值实在的用不习惯，有童鞋支持一下么，据说人气高了官方会考虑一下的:)

**Comment by Jinjiang** [comment]
我们现在有一个 vue 2.0 的分支，感兴趣可以自己试试看体验一下 `jsfm-feature-vue`

**Comment by comtewu** [comment]
在package.json中devDependencies部分需要增加一行：	
    "entities": "^1.1.1",
才能完成编译
