### ISSUE TITLE
[gh-pages]Whether the word HTML5 should be replaced with WEB (at homepage)?

### ISSUE THREAD

**Issue by mc-zone** [alibaba/weex#671]
哈哈，第三个是不是写 Web 比较好一点？HTML5 是不有点不合适，好国内特色的感觉。。
![image](http://alibaba.github.io/weex/img/weex_show.png)

（小建议而已。图片这个也没法提 PR... 😄 ）

**Comment by Jinjiang** [comment]
Web, Web Application, HTML5 , WebPlatform 都是 W3C 官方推广的用词，h5 是中国特色，HTML5 一直没问题
