### ISSUE TITLE
weex在什么情况下，app中会渲染失败？

### ISSUE THREAD

**Issue by duqian291902259** [alibaba/weex#673]
遇到的问题是：weex编写的代码，在pc上面用chrome模拟手机显示都正常，但是用playground扫描对应的js文件，android端却渲染失败（js的链接没问题，二维码没问题），有哪些可能的原因？
有的页面正常，有的不正常。用了动画，大图片，会不会是尺寸问题？还是transfromer后生成的代码有问题？

**Comment by luics** [comment]
请贴一下代码

**Comment by luics** [comment]
请在给出代码后 reopen

**Comment by duqian291902259** [comment]
`<template>
    
  <div class="wrap">
    <text class="title">{{title}}</text>
    <slider class="slider" interval="{{intervalValue}}" auto-play="{{isAutoPlay}}" >
      <indicator class="indicator"></indicator>
      <div class="slider-pages" repeat="{{itemList}}" onclick="goNext" >
        <image class="thumb" src="{{pictureUrl}}" resize="stretch"></image>
      </div>
    </slider>
    
    <text class='btn' onclick="goNext">{{txt}}</text>

  </div>
</template>

<style>
 .wrap{
    width: 100%; height: 100%;
    margin:0 auto;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    background-color: #2B2D2F;
  }
  .slider {
    margin: 0;
    width: 750;
    height: 1000px;
    background-color: transparent;;
    margin:0 auto;
    align-items: center;
    justify-content: center;
  }
  .thumb {
    width: 720px; height: 1280px;
    margin:0 auto;
    align-items: center;
    justify-content: center;
  }
  .title { text-align: center ; color: grey; font-size: 50; }

  .slider-pages {
    flex-direction: row;
    width: 720;
    height: 1000px;
    margin:0 auto;
    align-items: center;
    justify-content: center;
  }
  .indicator {
    position: absolute;  top: 970;
    width: 720;
    height: 30px;
    margin:0 auto;
    itemColor: #dddddd;
    itemSelectedColor: rgb(40, 96, 144);
  }
  .btn{
    /*position: absolute;  top: 990; #ffc832;*/
    width: 350;
    height: 50px;
    margin:0 auto;
    background:#0096FF;
    font-size:25;margin-top:25px;height:50px;
    align-items: center;
    justify-content: center;
    border-radius: 50px;
    font-weight: bold;
    color:#fff;
  }
</style>

<script>
module.exports = {
    data: {
      txt:"开始体验－Start Weex",
      intervalValue:"1000",
      isShowIndicators:"true",
      isAutoPlay:"true",
      itemList: [
        {title: 'A', pictureUrl: 'https://duqian291902259.github.io/dusan/oair/bg1.png'},
        {title: 'B', pictureUrl: 'https://duqian291902259.github.io/dusan/oair/bg2.png'},
        {title: 'C', pictureUrl: 'https://duqian291902259.github.io/dusan/oair/bg1.png'}
      ]
    },
    methods: {
      goNext: function () {
        this.$openURL('http://localhost:8080/index.html?page=./src/build/home.js')
      }
    }
}
</script>
`

**Comment by duqian291902259** [comment]
<template>
    
  <div class="wrap">
    <text class="title">{{title}}</text>
    <slider class="slider" interval="{{intervalValue}}" auto-play="{{isAutoPlay}}" >
      <indicator class="indicator"></indicator>
      <div class="slider-pages" repeat="{{itemList}}" onclick="goNext" >
        <image class="thumb" src="{{pictureUrl}}" resize="stretch"></image>
      </div>
    </slider>
    
    <text class='btn' onclick="goNext">{{txt}}</text>

  </div>
</template>

<style>
 .wrap{
    width: 100%; height: 100%;
    margin:0 auto;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    background-color: #2B2D2F;
  }
  .slider {
    margin: 0;
    width: 750;
    height: 1000px;
    background-color: transparent;;
    margin:0 auto;
    align-items: center;
    justify-content: center;
  }
  .thumb {
    width: 720px; height: 1280px;
    margin:0 auto;
    align-items: center;
    justify-content: center;
  }
  .title { text-align: center ; color: grey; font-size: 50; }

  .slider-pages {
    flex-direction: row;
    width: 720;
    height: 1000px;
    margin:0 auto;
    align-items: center;
    justify-content: center;
  }
  .indicator {
    position: absolute;  top: 970;
    width: 720;
    height: 30px;
    margin:0 auto;
    itemColor: #dddddd;
    itemSelectedColor: rgb(40, 96, 144);
  }
  .btn{
    /*position: absolute;  top: 990; #ffc832;*/
    width: 350;
    height: 50px;
    margin:0 auto;
    background:#0096FF;
    font-size:25;margin-top:25px;height:50px;
    align-items: center;
    justify-content: center;
    border-radius: 50px;
    font-weight: bold;
    color:#fff;
  }
</style>

<script>
module.exports = {
    data: {
      txt:"开始体验－Start Weex",
      intervalValue:"1000",
      isShowIndicators:"true",
      isAutoPlay:"true",
      itemList: [
        {title: 'A', pictureUrl: 'https://duqian291902259.github.io/dusan/oair/bg1.png'},
        {title: 'B', pictureUrl: 'https://duqian291902259.github.io/dusan/oair/bg2.png'},
        {title: 'C', pictureUrl: 'https://duqian291902259.github.io/dusan/oair/bg1.png'}
      ]
    },
    methods: {
      goNext: function () {
        this.$openURL('http://localhost:8080/index.html?page=./src/build/home.js')
      }
    }
}
</script>

**Comment by XTaoWang** [comment]
<template>
  <list class="list" @loadmore="fetch" loadmoreoffset="10">
    <cell class="cell" v-for="num in lists">
      <div class="panel">
        <text class="text">{{num}}</text>
      </div>
    </cell>
  </list>
</template>
<script>
  const modal = weex.requireModule('modal')
  const LOADMORE_COUNT = 4
  export default {
    data () {
      return {
        lists: [1, 2, 3, 4, 5]
      }
    },
    methods: {
      fetch (event) {
        modal.toast({ message: 'loadmore', duration: 1 })
        setTimeout(() => {
          const length = this.lists.length
          for (let i = length; i < length + LOADMORE_COUNT; ++i) {
            this.lists.push(i + 1)
          }
        }, 800)
      }
    }
  }
</script>
<style scoped>
  .panel {
    width: 600px;
    height: 250px;
    margin-left: 75px;
    margin-top: 35px;
    margin-bottom: 35px;
    flex-direction: column;
    justify-content: center;
    border-width: 2px;
    border-style: solid;
    border-color: rgb(162, 217, 192);
    background-color: rgba(162, 217, 192, 0.2);
  }
  .text {
    font-size: 50px;
    text-align: center;
    color: #41B883;
  }
</style>

官方代码我在本地html 渲染不出为什么
