### ISSUE TITLE
FEATURE:希望支持获取设备的键值，比如Android盒子的遥控器键值

### ISSUE THREAD

**Issue by charlescui** [alibaba/weex#678]
目前盒子越来越流行，我们在开发Android和AppleTV上面的产品。
期望在某个milestone能支持以下能力：

- 键值
  - 目前WEEX没有内置的方法获取外接设备的键值，比如盒子遥控器按下确认后，WEEX能否捕捉确认件的keycode。
- 焦点框
  - 目前WEEX针对的是移动端，移动端使用触屏，所以WEEX目前还不支持焦点框，希望能支持控件上获取焦点以及焦点移动的能力。
  - 盒子和移动端不同，使用的是遥控器，通过遥控器的上下左右来控制焦点、光标的移动，移动到某个控件上按下确认，从而激活某个功能。

**Comment by luics** [comment]
键值可以单独提一个issue： input 组件 onchange/oninput 事件参数增加 keycode
TV 短期内没有计划；

**Comment by JackyAndroid** [comment]
其实这个可以通过Native 主动发送事件到JS实现相应功能，但是我看文档没有相应说明。
Native 主动发送事件到js应该怎么做？？
