### ISSUE TITLE
请问weexcore for Android的native代码实现在哪里？

### ISSUE THREAD

**Issue by vmlinz** [alibaba/weex#679]
你好，我对这个项目很有兴趣，想了解下weexcore的实现，所以看了下代码组织。

但是没有找到weexcore的android本地源码，只有编译好的二进制库文件。

请告知一下怎么获取这个代码，如果是我没有找到，请指出，我来关闭issue。

谢谢。

**Comment by luics** [comment]
这部分暂时没开源计划。

**Comment by TreasureU** [comment]
请问现在还是没有开源的计划吗？

**Comment by misakuo** [comment]
https://github.com/alibaba/weex_v8core @TreasureU

**Comment by TreasureU** [comment]
感谢回复。

**Comment by rivalnhwc** [comment]
https://github.com/alibaba/weex_v8core 已经很久没更新了 @misakuo 请问现在还能看到最新的native代码？
