### ISSUE TITLE
BUG require we 時 webpack 噴錯

### ISSUE THREAD

**Issue by david50407** [alibaba/weex#682]
我嘗試著用 `weex init` 建了新專案之後，往生成的 main.we 添加了 `require('./foo.we');` ，並建立新的 foo.we 檔案在裡面填上一些 `hello world`，下 `weex build` `weex serve` 後，browser 拋出的錯誤如下：

```
TypeError: __webpack_require__(2) is not a function. (In '__webpack_require__(2)(module)', '__webpack_require__(2)' is an instance of Object)
```

![2016-07-02 08 55 35](https://cloud.githubusercontent.com/assets/841969/16537337/c5ce1920-4032-11e6-879a-3ba282511e07.png)

**Comment by coolicer** [comment]
有没有运行npm install

**Comment by david50407** [comment]
@coolicer 有的，先 `npm install` 後確定自動生成的 main.we 運作正常後才開始修改的

**Comment by david50407** [comment]
後來找到問題了……

因爲我把 `module.exports` 打成 `module.export` 導致整個 module 是 `undefined` ，不過這錯誤提示還真的沒頭緒啊XDDDD
