### ISSUE TITLE
slider bug

### ISSUE THREAD

**Issue by 121595113** [alibaba/weex#685]
slider动画有点小问题，transform: translate3d的值一直累加，到最后动画效果就变成一闪而过的的，下面是截图，这里是不是要优化一下
![bug](https://cloud.githubusercontent.com/assets/9419773/16539507/e202a8c8-4077-11e6-977c-f661185cb0b0.jpg)

**Comment by MrRaindrop** [comment]
hi, 不是很确定你说的到最后变成一闪而过是什么情况，有没有什么稳定的复现手段？。。translate3d一直累加的原因是保持slider滑动方向不变，且不想造成slider页面的抖动。如果只是累加，在数值安全上并不会有什么太大的问题，假设每次滑动750px，每1秒滑动1次，那么距离滑到最大安全整型值还需要 Number.MAX_SAFE_INTEGER / 750 / 60 / 60 / 24 / 365 ＝ 380821.886298875年，如果用Number.MAX_VALUE来计算这个值就是个天文数字了。

**Comment by 121595113** [comment]
复现手段很简单。就是你写一个demo在浏览器中运行，页面不要关，两个小时后再看动画效果。

**Comment by MrRaindrop** [comment]
确实是有这个问题，目前slider锁屏以后会自动停播，所以移动端基本很少碰到这样的场景。如果有优化方案，欢迎给我们提pr : )
