### ISSUE TITLE
怎么动态的设置image的图片啊？急！

### ISSUE THREAD

**Issue by sunnyyin** [alibaba/weex#689]
在布局中有这个标签<image class="image"  src="{{img}}"></image>，在event.changeimage("com.xx.xx.epa",function(resp){
 .........
  });
  在这个changeimage的回调里面怎么动态的改变image的背景啊？

**Comment by sospartan** [comment]
你的贴图看不到

**Comment by sunnyyin** [comment]
@sospartan 在布局中有这个标签<image class="image"  src="{{img}}"></image>，event.changeimage(...){
																																	…
																															}
																								module.exports = {

data:{
    img:'xxxxxxx';
}
																																	…
																															}

在这个changeimage的回调里面怎么动态的改变image的背景啊？

**Comment by luics** [comment]
```
event.changeimage(...){
   this.img = 'new url'
}
```
