### ISSUE TITLE
android studio  run  build failed，报错如下

### ISSUE THREAD

**Issue by lisiyizu** [alibaba/weex#690]
![image](https://cloud.githubusercontent.com/assets/12014252/16549923/027e3bc0-41d7-11e6-900d-8b053f1b9621.png)

![image](https://cloud.githubusercontent.com/assets/12014252/16549954/95116570-41d7-11e6-9217-05d5d5a9f831.png)

**Comment by sospartan** [comment]
使用'SDK Manager' 对SDK进行更新先 要安装对应版本的support library   或者你把项目的依赖版本改成你本地已经安装的
