### ISSUE TITLE
lack the source code of libweexcore.so

### ISSUE THREAD

**Issue by imcaspar** [alibaba/weex#691]
Thanks for the awesome work first.
I notice that the source code of libweexcore.so ( in android/sdk/libs ) can't be find in this repo. Will you upload related source code soon?

**Comment by luics** [comment]
We has plan to update

**Comment by luics** [comment]
`libweexcore.so` consists of almost v8 code, so you can get source code from https://github.com/v8/v8 .

**Comment by imcaspar** [comment]
Thanks for help. Could you kindly help to provide an **armeabi-v7a** version of libweexcore.so? armeabi version do not have hard float support.

**Comment by luics** [comment]
@sospartan 

> Thanks for help. Could you kindly help to provide an armeabi-v7a version of libweexcore.so? armeabi version do not have hard float support.
