### ISSUE TITLE
[discuss]是否可以添加cfg等编码格式化的配置文件？

### ISSUE THREAD

**Issue by sunbohong** [alibaba/weex#692]
为了统一项目中的编码规范，是否可以添加cfg等编码格式化的配置文件？

**Comment by luics** [comment]
可以考虑在 org https://github.com/weexteam 或个人 repo 维护类似的配置、插件，然后在 https://github.com/alibaba/weex/wiki/Weex-Community 中添加一个链接，已有类似的例子。
