### ISSUE TITLE
weex 官方源码 android 中介绍的  WXMainActivity.java 文件应该换成 IndexActivity.java

### ISSUE THREAD

**Issue by lisiyizu** [alibaba/weex#701]
![image](https://cloud.githubusercontent.com/assets/12014252/16555768/dc1bf404-4208-11e6-9c6b-780f9ad2af1d.png)

**Comment by luics** [comment]
pls submit a pr :)

**Comment by luics** [comment]
done https://github.com/alibaba/weex/blob/dev/README.md#android
