### ISSUE TITLE
什么时候支持可以直接打包 什么时候可以直接调用系统API???

### ISSUE THREAD

**Issue by yanyutao** [alibaba/weex#705]

**Comment by luics** [comment]
是指类似 cordova 的插件和打包机制吧？ 
https://cordova.apache.org/

**Comment by dodola** [comment]
@luics 我觉得可以只提供一个接口，这个接口使用反射调用系统api，

**Comment by nunnly** [comment]
感觉打包特别麻烦，之前并没有做过苹果和android的相关工作，想尝试着做一个APP，完成了之后发现并不会打包成APP，如果可以像Hbuilder的发布功能一样，交由云主机打包，因为环境都是一模一样的，会不会更好。难度系数也比命令行来的简单，开发周期也短。

**Comment by theseawolves** [comment]
@nunnly 同感 :+1: 。估计weex用户中有不少像@nunnly 和我这样的用户，对ios和android app都了解的不是很深入，只是希望能独立完成一个app。希望weex无论文档还是功能设计，假如能让我们这类人很快上手的话，weex离成功就越近了。当然weex已经不错了 继续加油 呵呵

**Comment by luics** [comment]
未来我们有计划做一键打包（可能也是命令行），目前通过 IDE 可以打包，可能稍复杂一些，请参考
http://weex.help/topic/5777227a344fc12e349baa73

**Comment by iloveyo123u1** [comment]
目前可能还是ionic好一些吧

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！

**Comment by MaryWu** [comment]
weex打包已经有工具支持，请见 https://github.com/weexteam/weex-pack
