### ISSUE TITLE
[Discuss] Simplify branch management

### ISSUE THREAD

**Issue by luics** [alibaba/weex#706]
We'll simplify [current Branch Management](https://github.com/alibaba/weex/blob/dev/CONTRIBUTING.md) recently.

```
master
 ↑
dev         <--- PR(hotfix/typo/3rd-PR)
 ↑ PR
{domain}-feature-{date}
```  
Weex Branches

0. `master` branch
    0. `master` is the latest (pre-)release branch.
0. `dev` branch
    0. `dev` is the stable developing branch. [Github Release](https://help.github.com/articles/creating-releases/) is used to publish a (pre-)release version to `master` branch.
    0. ***It's RECOMMENDED to commit hotfix (like typo) or feature PR to `dev`***.
0. `{domain}-feature-{date}` branch
    0. The branch for a developing iteration, e.g. `android-feature-20160607` is an android developing iteration which is done at 2016.06.07. `{domain}` consists of `android`, `ios`, `jsfm` and `html5`. 
    0. **DO NOT commit any PR to such a branch**.

**Comment by gurisxie** [comment]
get √
