### ISSUE TITLE
stream中fetch方法参数header无效

### ISSUE THREAD

**Issue by zct1989** [alibaba/weex#707]
stream中fetch方法参数header设置无效

文档中写着`headers(object): the HTTP request headers.`

``` javascript
        var stream = require('@weex-module/stream');
        stream.fetch({
            method: 'GET',
            url: "http://apis.baidu.com/acman/zhaiyanapi/tcrand",
            type: 'json'
            headers:{
              "apikey":"this is a token"
            }
        }, function(response) {
            console.log(response)
        });
```

发送请求如下

![请求数据](http://7xn3fd.com1.z0.glb.clouddn.com/weex-bug-1.png)

没有发现该请求头

**Comment by luics** [comment]
@MrRaindrop @sospartan

**Comment by zct1989** [comment]
找到问题了，我是通过weex init 创建项目，依赖 `"weex-html5": "0.2.18"`,在npm上最新的版本是0.2.22这个是两周前更新的，但是stream.js里面代码是在6月27号修改，里面stream正常，希望更新一下npm上的包

**Comment by sospartan** [comment]
@lvscar npm上的weex-html5版本需要更新

**Comment by zct1989** [comment]
npm上面的weex-html5刚才已经更新为0.2.23-beta但是我看node_modules里面的steam代码依然不是最新的

**Comment by stardew516** [comment]
你解决这个问题了吗，我也遇到了。
