### ISSUE TITLE
[iOS]当有select元素时，无法正确的显示视图

### ISSUE THREAD

**Issue by sunbohong** [alibaba/weex#711]
```
<template>
    <div>
        <text style="font-size:100px;">Sun.</text>
        <select style="width:100;height:100">
            <option value="volvo">Volvo</option>
            <option value="saab">Saab</option>
        </select>
    </div>
</template>
```
![qq20160705-0 2x](https://cloud.githubusercontent.com/assets/7285119/16574569/f5e90ce6-42b2-11e6-893c-5d2bb2d7cb05.png)

**Comment by cxfeng1** [comment]
@sunbohong  Weex对外可用的组件均以文档为准。 目前select组件iOS和Android都还没完成， 所以暂时无法使用。

**Comment by acton393** [comment]
hi @sunbohong   select 的组件 暂时是在playground 中作为引导大家扩展 component 提供的一个example，不是正式完成， 具体实现在 WXSelectComponent.h/m 中， Android暂时应该还是没有这个组件的，所以暂时还不能使用，也可以自己扩展使用

**Comment by sunbohong** [comment]
是需要修改js转换部分才可以使用吗？

如果只有app端没有完成，应该只有select自身无法正常显示并使用，但是现在的情况是js代码解析会出现问题。导致前一个view不停地显示并最终报错
```
2016-07-05 15:08:51.760 WeexDemo[72430:10395111] [fg255,0,0; <Weex>[error]WXSDKError.m:39, [undefined:1:21922] RangeError: Maximum call stack size exceeded.
```

**Comment by acton393** [comment]
@sunbohong  嗯，是的， 在native端 select 没有完成，是 select不能使用

这 ` Maximum call stack size exceeded.` 是另外一个问题， 
 这个问题得 @Jinjiang 看下

**Comment by luics** [comment]
`Maximum call stack size exceeded` see #721
