### ISSUE TITLE
[Discuss] Support sticky header on list

### ISSUE THREAD

**Issue by cxfeng1** [alibaba/weex#712]
A list can  contain multiple headers，next header will push previous header.

If a header is defined, the default behavior is sticky and can not be changed. If a no-sticky header is wanted, just wrap your content with `cell`,  not `header`.

```
<list>
      <header></header>
      <cell></cell>
      <cell></cell>
      ...
      <cell></cell>
</list>
```

**Comment by cxfeng1** [comment]
Supported in [v0.6.1](https://github.com/alibaba/weex/releases/tag/v0.6.1).

**Comment by erguotou520** [comment]
web端不支持？版本0.11
