### ISSUE TITLE
设置了max-height后在H5、IOS中不能启作用，最新playground和手淘包均无效

### ISSUE THREAD

**Issue by LeeJay0226** [alibaba/weex#714]

**Comment by luics** [comment]
直接贴代码吧

**Comment by MrRaindrop** [comment]
h5是起作用的，给包裹的div设置`overflow:hidden;`能看到效果。默认的overflow为`visible`，所以即使子元素超出了包裹div的`max-height`，仍然被显示了出来

**Comment by LeeJay0226** [comment]
增加overflow: hidden;后在Android和ios上都正常了，但貌似这个属性在文档中都没有提到

**Comment by luics** [comment]
合并至 #796
