### ISSUE TITLE
如何部署翻译好的js文件到服务器

### ISSUE THREAD

**Issue by yahooyee** [alibaba/weex#715]
我transfrom we文件之后，用weex －s ，访问的时候不能看到页面，而是具体文件，请问该如何处理

**Comment by zct1989** [comment]
http://localhost:12580/?page=[翻译后的js文件路径]

这样试试 page对应transfrom后的js文件路径

**Comment by lvscar** [comment]
#636 

weex -s 目前仅仅只是输出js bundle ，是不会自动生成最终页面的。 这个feature我们后续会考虑。

如果你想把Weex集成于现有的 web程序，参考   http://alibaba.github.io/weex/doc/advanced/integrate-to-html5.html  这个文档
