### ISSUE TITLE
Unable to find a specification for SDWebImage

### ISSUE THREAD

**Issue by daochouwangu** [alibaba/weex#717]
操作系统:mac OS 10.11.5
当我在ios/playground 下运行pod install的时候
报错 [!] Unable to find a specification for `SDWebImage (= 3.7.5)`
![image](https://cloud.githubusercontent.com/assets/4903149/16578107/50efc504-42cb-11e6-850e-97da71458470.png)
xcode里打开的时候，发现提示3个报错
![image](https://cloud.githubusercontent.com/assets/4903149/16578134/72e0026e-42cb-11e6-9ba7-8e454940582f.png)
应该是pod install没有成功的原因。
那么请问为什么SDWebImage安装失败了

**Comment by acton393** [comment]
hi  @daochouwangu   你的cocoaPods repo 应该比较久了没有更新，
 推荐先试试
 `pod update`

如果依然有问题 尝试：
`pod repo remove master`
`pod repo add master git@github.com:CocoaPods/Specs.git`
