### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by luics** [alibaba/weex#721]
```
WeexDemo[72430:10395111] �[fg255,0,0; <Weex>[error]WXSDKError.m:39, [undefined:1:21922] RangeError: Maximum call stack size exceeded”
```

**Comment by lvscar** [comment]
any function recursive call case chould raise "Maximum call stack size exceeded"  error.

need more information for debug

**Comment by Jinjiang** [comment]
This bug has been fixed through weex-loader https://github.com/weexteam/weex-loader/pull/5
And reopening this issue is welcome if any other case happens.
Thanks.
