### ISSUE TITLE
关于样式是否支持background-image

### ISSUE THREAD

**Issue by OliverVin** [alibaba/weex#724]
.root {
    background-image: url(//);
    background-repeat:no-repeat;
    background-size: 100% 100%;
    position: fixed;
    top: 0;
  }

我用如上的样式来设置了一个背景图，网页端正常，客户端不能显示背景图，不知道是否支持background-image 来设背景

**Comment by luics** [comment]
赞不支持 background-image，建议通过 `image` 配合 `position:absolute` 来实现

weex 支持的样式请参考 http://alibaba.github.io/weex/doc/references/common-style.html

**Comment by duqian291902259** [comment]
我也尝试过，确实不行，只能绝对定位的形式，但是复杂的UI这样布局还是挺难适配的。

**Comment by rccoder** [comment]
Thx

**Comment by aoping** [comment]
求支持
