### ISSUE TITLE
是否支持css,js,html分离？

### ISSUE THREAD

**Issue by zct1989** [alibaba/weex#728]
之前看这篇文章说[http://www.w2bc.com/article/155728](http://www.w2bc.com/article/155728)支持把css,js,html分离书写以实现对类似less的支持。

尝试了一下一直无法读取对应 `html` 文件

想问一下是不是支持这种书写方式:

``` javascript
//--foo.we.js
module.exports = {
  template: require('./foo.we.html'),
  style: require('./foo.we.css'),
  data: {
    name: 'Weex'
  }
}
```

**Comment by Jinjiang** [comment]
请移步到这里了解 https://github.com/weexteam/weex-loader
