### ISSUE TITLE
modal.toast文字大小太小

### ISSUE THREAD

**Issue by zct1989** [alibaba/weex#731]
浏览器使用modal.toast弹出提示信息，文字太小

``` javascript
modal.toast({'message': 'I am toast!', 'duration': 100});
```

浏览器打开效果如下:

![picture](http://7xn3fd.com1.z0.glb.clouddn.com/20865555-E60F-40DA-87F2-C36AB336B680.png)

提示文字太小小到看不见

**Comment by Jinjiang** [comment]
Hi 是浏览器中的版本吗？请确定一下 https://github.com/alibaba/weex/blob/dev/index.html#L17:L19 这行代码是否在页面中，这段是代码 lib.flexible https://github.com/amfe/lib-flexible 的 min 版

**Comment by zct1989** [comment]
通过 weex init 创建的项目，没有这行代码
加上就正常了 。
