### ISSUE TITLE
调用stream.fetch，浏览器和android返回response结构不一致

### ISSUE THREAD

**Issue by zct1989** [alibaba/weex#734]
调用`stream.fetch`请求数据
```
stream.fetch({
            url: "http://apis.baidu.com/acman/zhaiyanapi/tcrand",
            type: "json",
        }, function(response) {
            vm.data = response.data.taici;
        });
```

在浏览器运行正常 response 为json对象，response.data同样是object对象；
在android上运行  response 为json对象，response.data为string类型

**Comment by sospartan** [comment]
这个问题已经修复 c529dcb3ad93bb367f0ab9a8ec47840ab368fdac

**Comment by d200820205051** [comment]
android和ios的json数据类型不一致，ios的是字符串，android的object

**Comment by acton393** [comment]
hi @d200820205051 ，抱歉，才看到这个，
我提了pr #894 ,fix 这个问题
如果有问题，继续反馈~~
