### ISSUE TITLE
求教:动态加载一段string，内容为元素标签，如何渲染在页面上？

### ISSUE THREAD

**Issue by UselessGuy** [alibaba/weex#736]
例如这段string为"<a class='alink'><text>link</text></a>"

**Comment by luics** [comment]
pls use [weex-toolkit](https://www.npmjs.com/package/weex-toolkit) generator.

```bash
weex init
```

or

```html
<template>
  <div>
    <text>{{txt}}</text>
  </div>
</template>

<script>
  module.exports = {
    data: {
      txt: ''
    },
    ready: function() {
      this.txt = 'hi weex';
    },
    methods: {}
  };
</script> 
```

**Comment by UselessGuy** [comment]
@luics  我的意思是 类似于zepto中的append方法，把后端返回的`<a class='alink'><text>1111</text></a>`动态渲染到页面中

**Comment by theseawolves** [comment]
@UselessGuy  好像不支持 {{{}}}操作，另外template里的标签都是自定义组件，不是普通的html标签。不知道可不可以在ready或者create的时候通过实例api ,append进去

**Comment by theseawolves** [comment]
@Jinjiang vue2.0支持是否可以用了，是否会成为未来官方支持的方向？或者不采用是不是因为性能问题呢？

**Comment by theseawolves** [comment]
@Jinjiang <template>里面不能随意写html标签，还是限制不小哈 ：）

**Comment by Jinjiang** [comment]
@UselessGuy

1. 直接贴 html 片段有很多问题，包括安全和解析成本上的，维护上的
2. 总体上，我们倾向于通过管理数据或状态 (即 ViewModel `data` options) 来管理视图，appendChild 这种 API 我们十分不推荐

以上两方面今天比较新的 JS 框架都在做很强的限制，也是因为提供这个功能和灵活度带来的负面影响也很多

@theseawolves 现在的 `jsfm-feature-vue` 分支其实就是 Vue 2.0 的最新状态

HTML 标签最简单的支持方式就是通过自定义组件注明一下它的样式，比如：

```
<element name="h1">
  <template>
    <text style="font-size: 64px; font-weight: bold;">
      <content></content>
    </text>
  </template>
</element>
```

这稍微有点违背 Weex 把前端语法和 Native 渲染(组件)和功能 (API) 结合起来的初衷，我们会认真考虑一下这方面的问题

更多讨论请二位移步到中文聊天室吧，我这边先关掉了
https://gitter.im/weexteam/cn
谢谢
