### ISSUE TITLE
img doesn't support data url

### ISSUE THREAD

**Issue by axbing** [alibaba/weex#74]
.i { width:20px; height:20px;}

&lt;img class='i' src='data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7' / &gt;
Nothing show.

**Comment by Jinjiang** [comment]
Hi, this issue will be collected into #1494 which collects all new feature requests and inactive open discussions. We hope to do this to make sure the open issues represent current focus and active jobs in community and the team. If we decide to resolve this problem or make it active. It will be reopened again.
Thanks for your support.

**Comment by wssgcg1213** [comment]
Weex playground app in android not support base64 image now?  but works in taobao.app both ios + android.

https://github.com/alibaba/rax/issues/186
