### ISSUE TITLE
Android 启动weex-devtool调试工具，ip地址为什么是undefined？

### ISSUE THREAD

**Issue by hzq877437275** [alibaba/weex#741]
weex-devtool
![image](https://cloud.githubusercontent.com/assets/20315378/16644071/a9e5a7c8-444c-11e6-9556-869caf7469e7.png)

![image](https://cloud.githubusercontent.com/assets/20315378/16644130/14ec5904-444d-11e6-9aab-a3aaf406ba1a.png)
debugger和inspector按钮都不可点击

**Comment by hzq877437275** [comment]
debugger和inspector按钮都不可点击

**Comment by luics** [comment]
请转移到合适的 repo 中 https://github.com/weexteam/weex-devtool/issues

**Comment by hzq877437275** [comment]
好的  谢谢




------------------ 原始邮件 ------------------
发件人: "luics";<notifications@github.com>;
发送时间: 2016年7月7日(星期四) 下午2:39
收件人: "alibaba/weex"<weex@noreply.github.com>; 
抄送: "追风少年"<877437275@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/weex] Android 启动weex-devtool调试工具，ip地址为什么是undefined？ (#741)




请转移到合适的 repo 中 https://github.com/weexteam/weex-devtool/issues
