### ISSUE TITLE
activity之间数据怎么传递

### ISSUE THREAD

**Issue by ronniesun** [alibaba/weex#763]
使用weex  activity之间数据怎么传递

**Comment by sospartan** [comment]
传递数据的方式与native一样  可以包装成module 欢迎发PR添加到android的common库里

**Comment by ronniesun** [comment]
能给个具体链接吗

**Comment by ronniesun** [comment]
或者demo

**Comment by sospartan** [comment]
如果你是android开发，你肯定对`Intent`会比较熟悉，这个就是最常用的方式。
如果不是，那这块的实现需要一些native的开发集成基础，建议先了解一下。
这个问题的答案可以参考一下：
http://stackoverflow.com/questions/2091465/how-do-i-pass-data-between-activities-on-android

**Comment by ronniesun** [comment]
谢谢您的解答，我是android开发，请问onactivityResult这种，怎么处理，例如选择一个城市后把值回调，那activity不就等于写死了吗 ？   weex 的目的只是加载页面吗

**Comment by ronniesun** [comment]
加入说我有个 个人信息编辑页面 1.0版本只加入了 省份；1.1版本又想省份后选择城市   是不是需要版本升级才能做到   weex能解决吗  因为1。0版本省份的activity没有接受城市的回调

**Comment by sospartan** [comment]
@ronniesun 可以写一个module来处理转发回调 http://alibaba.github.io/weex/doc/advanced/extend-to-android.html
