### ISSUE TITLE
scroller，slider,list  用到这些的页面都显示白屏。。。

### ISSUE THREAD

**Issue by niyige** [alibaba/weex#771]
每次在以显示有内容的页面，替换成带有slider等的代码官方的demo，weex   xxx.we     显示的页面是白屏，，去掉又好了。。。

**Comment by lvscar** [comment]
你可以看一下代码中是否有    
`require('weex-components') ` 
如果有，请对应源码目录执行
`npm install weex-components`

我们后面会对这种情况增加提示， 谢谢反馈

**Comment by cooperding** [comment]
ios中加载含有scroller组件的js文件，页面空白，Swift编码的，oc的没有问题  #847
