### ISSUE TITLE
Supporting require native module in .js file required by .we file

### ISSUE THREAD

**Issue by carmelosui** [alibaba/weex#774]
Say that I have a `A.we` file, inside which I have:  
`
require("./my_api.js");
`
  
in` my_api.js` I have:  
`
require("@weex-module/myNativeModule");
`  
By now when running `weex A.we`, it complains about cannot find the `myNativeModule` module.

This blocks the way of encapsulating native modules into Javascript API, please add this feature.

**Comment by luics** [comment]
https://github.com/weexteam/article/issues/20

**Comment by Jinjiang** [comment]
Also you can checkout "dependencies in frontend" in the faq page: http://alibaba.github.io/weex/doc/faq.html

for more questions please see: weex-loader issues https://github.com/weexteam/weex-loader/issues or gitter chat room https://gitter.im/weexteam/cn

Thanks
