### ISSUE TITLE
[Discuss] 点击效果

### ISSUE THREAD

**Issue by BoluoPi** [alibaba/weex#782]
希望weex可以支持点击效果的配置。
如android L以上点击时有水波纹效果，或者支持点击时候置灰也好。
感觉这个可以更体现出native的优势。

**Comment by acton393** [comment]
嗯，跟你在qq上沟通一样，
android L以上点击时有水波纹效果，这个涉及到三端一致性的问题， 这个体验欢迎你提pr,

onclick 后置灰色这个会考虑在native上实现

**Comment by luics** [comment]
@acton393 android 可以有 matirial UI 的风格，iOS 有自己的风格，这个差异性是合理的；和三端一致性不冲突； 可以和 @xkli 一起看下

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
