### ISSUE TITLE
Input组件获取焦点的时候弹出键盘会挡住Input视图

### ISSUE THREAD

**Issue by Rowandjj** [alibaba/weex#784]

**Comment by sospartan** [comment]
能提供你的测试代码么 我们修改后也需要验证一下你的场景。

**Comment by wengfei** [comment]
也有这个问题。

**Comment by sospartan** [comment]
这个问题已经在android分支修复,manifest中对应的activity设置`android:windowSoftInputMode="adjustResize"`,即可解决这个问题.
