### ISSUE TITLE
建议：能否把Weex捐献给Apache？

### ISSUE THREAD

**Issue by leenux** [alibaba/weex#787]
在不影响阿里内部管理的情况下，能否把weex捐献给Apache？
对weex观察了很久，但是对项目维护持续性略有担心，衷心期望阿里能给予开发者足够的信心，放心大胆采用weex，期望weex的明天会更好

**Comment by xiaolongyuan** [comment]
apache ? 什么鬼

**Comment by xiaolongyuan** [comment]
还不如直接捐给 vuejs 好了  亲儿子

**Comment by yiqing95** [comment]
为毛要捐 是不信任马云么  aliceui 是黄了么？

**Comment by luics** [comment]
@leenux 我们会考虑的，谢谢你的建议。 
关于投入的持续性，建议从 commit 时间轴和参与提交的人数上，pulse 统计和 graph 中的相关数据综合来看。
