### ISSUE TITLE
html5 modal.toast 太小根本看不见

### ISSUE THREAD

**Issue by tjhyupo505** [alibaba/weex#790]
html5 modal.toast 太小根本看不见，只显示在最下方的中键一丁点小框，几乎完全看不见。android 手机浏览器和PC chrome 浏览器都是同样的看不见。

测试环境：WEEX HTML5: 0.2.23 Build 20160713

**Comment by MrRaindrop** [comment]
hi 
1. 你的入口文件是否是weex项目根目录底下的index.html ? 如果是自己写的入口html文件，需要确保正确引入[lib.flexible](https://github.com/alibaba/weex/blob/html5/index.html#L16-L19)
2. 你可以通过修改amfe-toast这个类的样式修改它的字体大小，比如

```css
.amfe-toast {
  font-size: 0.48rem;
}
```

**Comment by tjhyupo505** [comment]
是直接使用的项目根目录下的index.html，见附件。

[index.html.txt](https://github.com/alibaba/weex/files/363453/index.html.txt)

**Comment by tjhyupo505** [comment]
我使用的index.html是直接拷贝自最新的0.6.1下，居然和你给的链接的不一样，改用你的链接中的模板，toast大小正常了，谢谢，问题解决!

**Comment by xubodreamsky** [comment]
@tjhyupo505 请问你是如何解决的？  我目前也遇到了这个问题
