### ISSUE TITLE
html5-list不能上下滑动

### ISSUE THREAD

**Issue by tjhyupo505** [alibaba/weex#791]
list在html5环境下不能上下滑动，不管是使用pc的chrome浏览器，还是在android手机的浏览器上面都不能上下滑动。只有在pc chrome上面可以使用鼠标中键滚动。但是同样的代码在android native上面是正常的。

测试版本：WEEX HTML5: 0.2.23 Build 20160713

**Comment by MrRaindrop** [comment]
hi 我在#792里回复了你这个问题，需要给最外层的list设置一个高度. 后续会修复这个example.
