### ISSUE TITLE
[bug]html5-loading 显示为半屏或者全屏

### ISSUE THREAD

**Issue by tjhyupo505** [alibaba/weex#792]
loading控件在html5环境下显示太大了，只要轻轻一上拉，就会至少占用半屏甚至是全屏。

测试代码：https://github.com/alibaba/weex/blob/example/examples/component/list/list-basic.we
测试环境：START WEEX HTML5: 0.2.23 Build 20160705， PC+Chrome
截图：
![qq 20160714154621](https://cloud.githubusercontent.com/assets/11606362/16831981/9fd7115c-49da-11e6-9b15-5fbea9796fd0.png)

**Comment by MrRaindrop** [comment]
hi 你看下console下有没有报错 ?
另外你给的代码是不工作的，需要给list一个的高度值（或者通过计算得到也可以），比如

```
.list {
  height: 800px;
}
```

**Comment by MrRaindrop** [comment]
hi 我这边没有在pc的chrome模拟器里复现这个bug. 你试试拉最新的dev分支下来，再build一遍看还有没有这个问题。另外list-baisc代码里最外层的list需要设置一个高度，未来如果没有设置高度会自动适应容器高度，但是现在还没有实现这个功能。

```
//  设置list的高度
.list { height: 810px; }
```
example这个高度的问题很快会fix.

**Comment by tjhyupo505** [comment]
//  设置list的高度
.list { height: 810px; } 

这个确实管用，可以上下滑动，并且loading的大小也是正常的，2个问题都能解决。但是指定高度如果大于显示的高度，也不行，问题依旧。另外，只能指定小于显示高度的list高度的话就会下面一段空白，肯定不行的，期待你们尽快fix掉这个bug。

**Comment by MrRaindrop** [comment]
@tjhyupo505

直接设置height只是其中一个办法，如果你想要设置全屏高度，可以给`.list`设置一个`flex:1;`:
```css
.list {
  flex: 1;
}
```
或者利用绝对定位：
```css
.list {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}
```
以上是目前比较常用的设置高度的办法，后续会考虑加上一个自动判断的机制，如果计算出来的高度超过viewport的高度则自动缩减为父容器的高度，即自动加上`flex:1;`；但是目前仍然推荐用上述方法自定义控制高度。
