### ISSUE TITLE
[bug] android下 line-height 无效

### ISSUE THREAD

**Issue by tjhyupo505** [alibaba/weex#793]
android 下对一个 text 设置 line-height 无效，但是在html5环境下有效。

测试环境：0.6.1 android native。

**Comment by luics** [comment]
下载最新的 playground http://alibaba.github.io/weex/download.html
https://github.com/alibaba/weex/blob/dev/examples/component/text-demo.we#L49

看了下是正常的
![demo](https://gw.alicdn.com/tps/TB1SNK8KVXXXXcUXpXXXXXXXXXX-1080-1920.png)

**Comment by tjhyupo505** [comment]
确实demo里面是正常的，因为指定的是具体的值，而我使用的时候是指定的百分比，例如：line-height:150%;  ，在使用百分比的时候无效，不知道是没有设计支持还是bug。希望能够支持百分比。

**Comment by luics** [comment]
目前单位还未支持百分比，百分比可以单独提一个 issue。
