### ISSUE TITLE
关于开发出来的weex页面，在手机里分享到微信，分享出去的是一个js地址，分享后在浏览器里怎么打开？

### ISSUE THREAD

**Issue by wufenglover** [alibaba/weex#798]
您好：
我们在用weex开发一个应用时，页面需要通过微信分享到朋友圈，分享出去后其实分享的是js的地址，那在浏览器里打开这个js是无法渲染的，这个问题应该怎么解决？谢谢！

**Comment by MrRaindrop** [comment]
如果是在纯web环境下可以使用我们的h5 render来渲染，只需要在页面里引入weex-html5的库代码，并把上述js地址做为参数传递给初始化函数即可，weex-html5的具体使用方式参见文档 [接入weex-html5](https://github.com/weexteam/article/issues/10)

**Comment by Jinjiang** [comment]
这个问题长期没有讨论，我这里做关闭处理，更多使用上的疑问可以移步中文聊天室 https://gitter.im/weexteam/cn
谢谢
