### ISSUE TITLE
weex-loader cann't work with other webpack loaders elegantly

### ISSUE THREAD

**Issue by qingying** [alibaba/weex#803]
when I use webpack pack my weex file, I can only use weex-loader. if I need to use other webpack loaders, I must separate the weex file to tpl file, style file and javascript file, I don‘t think it's a good way to manage my modules, so would you support more elegantly

**Comment by qingying** [comment]
the weex-devtool can only support watch the changes about the weex file,when the saparated files changed, I must restart the debug serve,so the current way is not apply to debug on native。

**Comment by Jinjiang** [comment]
https://github.com/weexteam/weex-loader/pull/6 solved

**Comment by Jinjiang** [comment]
more discussions please go to https://github.com/weexteam/weex-loader/
thx
