### ISSUE TITLE
可否把baseURL作为组件属性？

### ISSUE THREAD

**Issue by zhoukekestar** [alibaba/weex#808]
可否把baseURL作为组件属性，而不是每次都在created方法自己手动去设置baseURL属性（这段代码貌似不少，获取bundleUrl，然后判断运行环境，最后设置baseURL）
ps：
如果考虑组件效率的话，能否设置标志位什么来指定组件需要baseURL属性，如：needBaseURL。

**Comment by luics** [comment]
和 #497  相关

**Comment by luics** [comment]
后续请关注 #497
