### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by eldyvoon** [alibaba/weex#809]
weex vs ionic vs react, what's the differences? Never heard of weex before. It's so smooth in iOS, just like native, good job.

**Comment by cxfeng1** [comment]
1. Both [Ionic](http://ionicframework.com/) and [React](https://facebook.github.io/react/) are **web-based** frameworks, which means you are creating a web page, you are using your system browser called WebView to render your app. Ionic is based on [Cordova](http://cordova.apache.org/), with which you have the ability to make calls to native APIs, but the bulk of your app will still be HTML, JavaScript and CSS inside a WebView. WebView is slow and it still has a noticeable performance difference compared to native, like navigation, scrolling acceleration, animation and gesture, which are significantly important for the **user experience**.

2. Weex is one of the new generation cross-platform mobile frameworks that are NOT using the WebView. It is using the **truly native** UI components from the native OS. Although you still write HTML, JavaScript and CSS, the components you define will end up rendering as native platform widgets. This have a very positive effect on the user experience of the app. 

3. Despite the advantages of using truly native UI components, we also make a lot of efforts to improve Weex's performance. We optimize our js-native communication to render the first screen faster, we also use a lot of asynchronous rendering techniques to ensure 60fps most of the time. You can dig out more from the source code.

And finally, thanks for sharing your experience on Weex,  we appreciate all your feedbacks.

**Comment by garrettmac** [comment]
@cxfeng1 this part about React is misleading
> Both Ionic and React are web-based frameworks, which means you are creating a web page, you are using your system browser called WebView to render your app. 

Yes React is for web but I think what @eldyvoon meant to say is 
> weex vs ionic vs react **native**

and React Native does not use WebView and uses native iOS and Android UI.
From a SO answer https://stackoverflow.com/a/33480329/4642530

>React Native uses a JavaScript runtime, but the UI is not HTML and it doesn't use a WebView. You use JSX and React Native specific components to define the UI.


Also worth noting Facebook, Instagram, Tesla, Skype and more are built in React Native.
see https://facebook.github.io/react-native/showcase.html
