### ISSUE TITLE
"ds": "webpack --watch && serve -p 8080" 无法同时启动服务

### ISSUE THREAD

**Issue by 15951836388** [alibaba/weex#814]
&&或者&，都只能打包，不能启动
系统：win7，其余的小伙伴们用这个命令 可以 打包+启动

**Comment by hugojing** [comment]
其他平台可使用 `webpack --watch && serve -p 8080` 进行自动打包与启动本地服务。Windows 不可以，疑似为 Node for Windows 的 BUG，建议去 Node 项目的 Issues 提问。

**Comment by Jinjiang** [comment]
这个问题长时间没有更多讨论，我先关掉了
如果再有问题可以随时继续讨论
谢谢

**Comment by hugojing** [comment]
说错了。其他平台应为 `webpack --watch & serve -p 8080`
