### ISSUE TITLE
通过openUrl,两个页面之间如何进行数据交互？   页面是否可见的回调有没有？   

### ISSUE THREAD

**Issue by loser007** [alibaba/weex#816]
1.还有 在后一个页面 更新上一个页面的数据，如何处理?
2.生命周期里没有没有 onresume 和onpause 这些回调
3.手势

**Comment by luics** [comment]
1. A openUrl to B， 通过 url 参数可以在 B 中获得 A 传递的参数，反向还未支持，可以关注 #550 
2. 页面可见性 http://alibaba.github.io/weex/doc/references/common-event.html#page-event
3. 手势 ，开放了部分功能 https://github.com/alibaba/weex/blob/v0.6.1/doc/references/gesture.md

**Comment by loser007** [comment]
1.AB 页面间的数据传递，希望能传递Object
2.BaseURL 能否做成内置
