### ISSUE TITLE
用 weex 做微信公众号的应用，像授权、微信支付、获取用户信息、JSSDK 之类的没有问题吧？

### ISSUE THREAD

**Issue by Yunlong2cn** [alibaba/weex#818]
如题，有没有将 weex 应用于微信公众号的朋友，上面提到的几部分内容是否有坑？最近要启用新项目，涉及到 webapp(主要是手机浏览器，微信浏览器)以及 android / ios 因此这里选型，希望能得到大家的意见，谢谢

**Comment by Jinjiang** [comment]
技术体系不一样，暂无法确认。更多方案应用讨论和答疑请移步至中文聊天室 https://gitter.im/weexteam/cn
issue 更多用来记录bug和功能讨论和追踪
谢谢

**Comment by hupanfeng** [comment]
嗨，哥们，踩到坑了没？

**Comment by yuangu** [comment]
同问，我也有类似想法。
