### ISSUE TITLE
请问 run build 后，怎么发布到ftp服务器上？

### ISSUE THREAD

**Issue by 15951836388** [alibaba/weex#819]
1.希望有详细的步骤，让手机web和pc 的web都能访问。

**Comment by 15951836388** [comment]
我发现，手机上访问空白，好像是有的浏览器可以。有的浏览器不行。 我测试的时候，红米自带的浏览器可以访问显示正常。 但是华为荣耀自带浏览器和装的qq浏览器，都是空白

**Comment by 15951836388** [comment]
http://www.richtechsystem.com/vr/   就是这个网址

**Comment by VoVAllen** [comment]
为什么要发布到ftp服务器而不是http服务器？

**Comment by Jinjiang** [comment]
发布一个weex页面生成码的方式和发布一个前端静态资源的方式没有差别，可以沿用前端代码发布的方式
不知道是否解答了你的问题
更多讨论可以移步至中文聊天室 https://gitter.im/weexteam/cn
谢谢
