### ISSUE TITLE
stream.fetch时候报has no method 'fetch'

### ISSUE THREAD

**Issue by bringmehome** [alibaba/weex#823]
**具体错误如下**

07-19 15:02:40.817 18079-18119/com.taobao.weex.sample.app D/jsengine: jsLog>>>>:stream | 
07-19 15:02:40.818 18079-18119/com.taobao.weex.sample.app E/jsengine:  ReportException :undefined:238: TypeError: Object [object Object] has no method 'fetch'
07-19 15:02:40.822 18079-18119/com.taobao.weex.sample.app E/jsengine:  ReportException : TypeError: Object [object Object] has no method 'fetch'
                                                                          at Vm.__weex_module__.exports.methods.fetchFunc (eval at init (unknown source), <anonymous>:238:18)
                                                                          at Vm.fetchFunc (<anonymous>:2:14588)
                                                                          at Node.<anonymous> (<anonymous>:2:14588)
                                                                          at EventManager.fire (<anonymous>:4:20716)
                                                                          at AppInstance.fireEvent (<anonymous>:4:14296)
                                                                          at fireEvent (<anonymous>:2:8142)
                                                                          at <anonymous>:2:8882
                                                                          at Array.forEach (native)
                                                                          at Object.callJS (<anonymous>:2:8654)
                                                                          at _loop.global.(anonymous function) (<anonymous>:1:1377)
07-19 15:02:40.822 18079-18119/com.taobao.weex.sample.app E/weex: reportJSException >>>> instanceId:1, exception function:callJS, exception:TypeError: Object [object Object] has no method 'fetch'

**调用方法**
        var stream1 = require('@weex-module/stream');
        stream1.fetch({
          method: 'POST',
          url: 'https://v2.fogcloud.io/enduser/getVerCode/',
          type:'json',
          body: {
            loginname:"88635334@qq.com",
            appid:"db456b4a-17fc-11e6-a739-00163e0204c0"
          }   
        }, function(response) {
          console.log("res 1:"+JSON.stringify(response));
        },function(response){
          console.log("bytes received:"+response.length);
        });

**通过chrome打开H5页面调用是可以的**

**Comment by sospartan** [comment]
你是在哪里使用  集成的SDK版本是?

**Comment by bringmehome** [comment]
上面的错误是0.5.0的版本，之后我换成0.6.1版本，可以调用fetch了，不报找不到method的了，但是调用会出问题：

**Comment by bringmehome** [comment]
HTML正确返回的示例：
res 1:{"status":200,"ok":true,"statusText":"OK","data":{"login_id":"13122112211","token":"b27b6c4c-a17e-4e43-8a7c-3e3c5129af89"},"headers":{"Content-Language":"en","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-cache, must-revalidate","Expires":"0"}}

**Comment by sospartan** [comment]
出的问题是?

**Comment by bringmehome** [comment]
**1、HTML调用fetch可以返回正确的信息：**
如上{"status":200,"ok":true,"statusText":"OK","data":{"login_id":"13122112211","token":"b27b6c4c-a17e-4e43-8a7c-3e3c5129af89"},"headers":{"Content-Language":"en","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-cache, must-revalidate","Expires":"0"}}

**2、但是用android的playgroundAPP扫描打开，返回的是**
{"headers":{"Cache-Control":"no-cache, must-revalidate","Connection":"keep-alive","Content-Language":"en","Content-Type":"application/json; charset=utf-8","Date":"Tue, 19 Jul 2016 07:45:33 GMT","Expires":"0","Server":"openresty/1.7.10.1","Transfer-Encoding":"chunked","Vary":"Accept","X-Android-Received-Millis":"1468914334247","X-Android-Response-Source":"NETWORK 400","X-Android-Sent-Millis":"1468914334217","X-Powered-By":"Luracast Restler v3.0.0rc6","_":"HTTP/1.1 400 Bad Request"},"ok":false,"status":"400","statusText":"Bad Request"} | __LOG |


**400的错误，看起来是参数不对，但是参数是对的，HTML可以用**

stream1.fetch({
method: 'POST',
url: 'http://www.easylink.io/v1/user/login',
type:'json',
body: {
login_id:"13122112211",
password:"123456"
},
headers:{
"X-Application-Id":"7ffbec46-7ff9-46fc-bb55-ec1dda89f40c"
}
}, function(response) {
console.log("res 1:"+JSON.stringify(response));
//process response
},function(response){
console.log("bytes received:"+response.length);
});

**Comment by bringmehome** [comment]
我和服务器同事一起测了下，发现android的stream.fetch方法会把body里的数据转换成一个字符串发送给服务器，但是HTML发送给服务器的是一个对象。

**Comment by sospartan** [comment]
是的  我调试了一下 是因为默认多了一个`Content-Type: application/x-www-form-urlencoded`的header,你改成
```
headers:{
          "X-Application-Id":"7ffbec46-7ff9-46fc-bb55-ec1dda89f40c",
          "Content-Type": "application/json"
        }
```

**Comment by bringmehome** [comment]
是这样的，现在好了，非常感谢。

**Comment by bringmehome** [comment]
加了这句（"Content-Type": "application/json"）以后，android端是好了，但是HTML端又出问题了，服务器端调试发现body里为空

{"status":400,"ok":false,"statusText":"Bad Request","data":{"detail":"JSON parse error - No JSON object could be decoded"},"headers":{"Content-Language":"zh-hans","Content-Type":"application/json"}}

**Comment by sospartan** [comment]
@MrRaindrop 你来看看H5上是什么原因

**Comment by bringmehome** [comment]
@MrRaindrop 亲，请教个问题

我发现HTML使用stream.fetch(发送数据
如果添加了headers：
headers:{
            "Content-Type":"application/json"
          }

那么body里json数据会变成
[object Object]

如果不添加headers，那么正常的
{loginname: "88635653@qq.com", appid: "db456b4a-17fc-11e6-a739-00163e0204c0"}

**Comment by MrRaindrop** [comment]
h5的bug，手动设置了Content-Type这个header的情况下没有将body里的plainObject转成字符串。在此bug修复之前，你可以试试将body设置为
```javascript
body: JSON.stringify({
  loginname:"88635334@qq.com",
  appid:"db456b4a-17fc-11e6-a739-00163e0204c0"
  })
```
试一试，应该是可以的

**Comment by bringmehome** [comment]
嗯，刚刚试了下是可以的，谢谢
