### ISSUE TITLE
使用 Swift 开发 iOS 扩展的问题

### ISSUE THREAD

**Issue by Bijiabo** [alibaba/weex#824]
关于 Extend to iOS 部分， OC 有一部分看不懂，特别是 `WX_EXPORT_METHOD(@selector(openURL:callback))` 这一部分不知使用 Swift 如何实现，能否提供一下使用 Swift 实现扩展示例代码？

**Comment by acton393** [comment]
hi @Bijiabo , 可以参考下这个[issue](https://github.com/weexteam/article/issues/55)
