### ISSUE TITLE
Cannot resolve 'file' or 'directory' ./config

### ISSUE THREAD

**Issue by liangjl76** [alibaba/weex#826]
ERROR in ./html5/runtime/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./config in I:\1\weex\html5\runtime
 @ ./html5/runtime/index.js 8:14-33

经过搜索发现build\config.frameworks.js会生成指定的文件
所以先运行node build\config.frameworks.js
然后再运行./start就正常了

**Comment by zhoukekestar** [comment]
我也出现这样的问题了，虽然`npm run build:config`之后的好了

建议把`npm run build`的script从

`npm run build:native && npm run build:browser && npm run build:examples && npm run build:test`

改为

`npm run build:config && npm run build:native && npm run build:browser && npm run build:examples && npm run build:test`

**Comment by Jinjiang** [comment]
多补充一下

`npm run build:native` 和 `npm run build:browser` 都包含了对 `html5/runtime/config.js` 文件的检测，一旦发现文件不存在就会自动运行 `npm run build:config`

所以直接运行 `./start` 也不应该产生这个问题

@zhangguochun @liangjl76 可否帮忙再看看当时出问题的时候是否有别的情况是我们没有考虑到的？

如果有新的情况发现，这个 issue 可以随时再打开

谢谢

**Comment by zhoukekestar** [comment]
@Jinjiang 本人屌丝，机器是Windows的，所以，是不是应该加个**start.cmd**给windows用户？关于`config.js`的检测，确定是`dev`分支的最新版吗？我早上刚pull过的

**Comment by gfwfail** [comment]
@zhoukekestar  babun/cygwin

**Comment by Jinjiang** [comment]
@zhoukekestar 现在 dev 分支的 `npm run build:browser` 和 `npm run build:native` 都会进行判断，代码在：

https://github.com/alibaba/weex/blob/dev/build/webpack.browser.config.js#L4:L8
https://github.com/alibaba/weex/blob/dev/build/webpack.native.config.js#L4:L8

想有劳你协助诊断一下，是否运行到了，是否工作正常

谢谢

**Comment by zhoukekestar** [comment]
OK, debuging...

**Comment by Jinjiang** [comment]
got，你的运行环境是windows默认的终端吗？还是cygwin？cmder？默认终端问题应该不止这一个地方，写成 npm.cmd 又有个兼容性问题

**Comment by zhoukekestar** [comment]
我是直接用系统的cmd的，和`Win + R`输入`cmd`一样
![qq 20160801163735](https://cloud.githubusercontent.com/assets/7157346/17288204/62a9dfaa-5806-11e6-9dc7-b42fe4359d56.png)

**Comment by Jinjiang** [comment]
了解了，系统 cmd 局限性确实还是太大了，我个人推荐换用 [cmder](http://cmder.net/)

**Comment by zhoukekestar** [comment]
不错，cmder+1

**Comment by RoadsInFarAway** [comment]
我也是window是系统，也出现这个问题了

**Comment by Jinjiang** [comment]
我实测 Windows 环境下确实 https://github.com/alibaba/weex/blob/dev/build/webpack.browser.config.js#L7 这句代码没有被执行

不过 Windows 我也有点生疏了，我试着想想办法，对 Windows 环境比较熟悉的同学也可以帮忙解解

谢谢大家的反馈

**Comment by zhoukekestar** [comment]
我表示系统默认终端和cmder都能通过==
