### ISSUE TITLE
weex-loader升级到0.3.0-alpha后，原来所有的js文件都报“Template block is required”错误，怎么解决？

### ISSUE THREAD

**Issue by JerroldLee** [alibaba/weex#827]
weex-loader升级到0.3.0-alpha后，原来所有的js文件都报“Template block is required”错误，怎么解决？

**Comment by Jinjiang** [comment]
weex-loader 的问题我迁移到了 https://github.com/weexteam/weex-loader/issues/8 这里做关闭处理
谢谢
