### ISSUE TITLE
几个疑问

### ISSUE THREAD

**Issue by Danielpog** [alibaba/weex#828]
1.为什么不遵循w3c标准，生成出来的html结果都是div+span，毫无语义化
2.如何使用字体图标，而不是图片
3.很多css的选择器无法使用，调样式的难度大大提高了
4.用绝对定位或固定定位时，如何让div居中，left，top，bottom，right这些的值用不了百分比
5.textarea不支持，该用什么标签？

**Comment by Jinjiang** [comment]
1. 我们遵循 html 语法，你说的 div 和 span 是标签定义的部分，不完全是语法 (syntax)，weex 用到的标签会考虑 native view 的特点做结合，同样是语义化的
2. 可以移步至 #825 这个问题正在讨论中
3. 复杂选择器的执行效率难以保证，我们这里从避免低性能运算被滥用，比较谨慎的只提供了 single class selector，私下里已经有一些同学在尝试在当前实现的基础上支持更多选择器，相信会在适当的时候开放出来给大家试用
4. 传统用到百分比的地方我们倾向于通过 flexbox 来解决，百分比这个单位我们将来会考虑
5. textarea 近期会支持
