### ISSUE TITLE
组件嵌套中数据传递的机制

### ISSUE THREAD

**Issue by moldauder** [alibaba/weex#831]
参考代码如下：

```
<div repeat="{{v in data.items}}">
            <item data-item="{{v.data}}"></item>
</div>
```

然后在item组件中，需要使用`dataItem`来获取`v.data`对应的数据，这个机制是什么？文档中未见阐述

**Comment by Jinjiang** [comment]
就是在 `<Item>` 定义的方法中访问 `this.dataItem`
更多使用上的疑问请移步中文聊天室 https://gitter.im/weexteam/cn
谢谢
