### ISSUE TITLE
[Discuss] Proposal to support rich text and view embeding in text

### ISSUE THREAD

**Issue by luics** [alibaba/weex#835]

**Comment by uixdk** [comment]
能不能给点思路啊 ？

**Comment by luics** [comment]
@uixdk 浮动准备通过 richtext 支持，我们会尽快把初步方案同步出来

**Comment by cxfeng1** [comment]
### 目前需要实现的功能
1. 不同样式的文字组合排列(支持font-size/font-style/color/background-color/decoration)
2. 文字中支持内嵌image和a链接

目前有几种方案可供讨论:

### 改造目前的Text组件

* 前端使用方式

```
<text style="style1">
    some words
    <text style="style2">some other words</text>
    <image src="image-url"></image>
    <a>a link</a>
<text>
```

* js-native 数据交互格式

```
{
    ref : xxx,
    type : text,
    style : {style1}
    children : [{
        ref : xxx, 
        type : text,
        style : {}, // if no style use super text's style
        attr : {value:some words}
    },{
        ref : xxx, 
        type : text,
        style : {style2}
        attr : {value:some other words}
    },
    ...
    ]
}
```

* Native 处理方案
  * 在text组件基础上改动，需要将text的children转换为NSAttributedString(iOS)和SpannableString(Android)的属性
  * 同时需要特殊考虑text子元素(未来还会支持嵌套子元素)在产生变更的时候要通知到text，使得text能够重绘

* 优势
  * 前端友好，使用便捷

* 劣势
    * 对现有的渲染机制有侵入性，对于text节点来说需要特殊处理，不再是一个标签对应一个view的模式。
    * 对现有text组件侵入较大，inline的引入，可能会为后续纯text组件的性能优化以及功能升级带来额外的负担。

**Comment by cxfeng1** [comment]
### 增加新的组件

* 前端使用方式

```
<rich-text style="style1">
    some words
    <span style="style2">some other words</span>
    <image src="image-url"></image>
    <a>a link</a>
<rich-text>
```

* js-native 数据交互格式

```
{
    ref : xxx,
    type : richText,
    style : {style1}
    children : [{
        ref : xxx, 
        type : span,
        style : {}, // if no style use super text's style
        attr : {value:some words}
    },{
        ref : xxx, 
        type : span,
        style : {style2}
        attr : {value:some other words}
    },
    ...
    ]
}
```

* Native 处理方案
  * 扩展一个rich-text组件
  * 其他同上一个方案

* 优势
  * 对前端使用相对友好
  * 和text实现解耦分离

* 劣势
  * 对现有的渲染机制有侵入性，对于rich-text节点来说需要特殊处理，不再是一个标签对应一个view的模式
  * 增加一个组件略微增加使用成本

**Comment by cxfeng1** [comment]
### 使用标记语言

* 前端使用方式

```
<rich-text style="style1">
    <!-- markdow or other markup language-->
    some words
    **bold words**
    ![](image-url)
    [link-word](link-url)
<rich-text>
```

* js-native 数据交互格式

```
{
    ref : xxx,
    type : richText,
    style : {style1},
    attr : {
        value:"some words\n**bold words**\n![](image-url)\n     [link-word](link-url)"
    }
}
```

* Native 处理方案
  * 扩展一个rich-text组件
  * 直接解析attr中的value，绘制出对应的native text

* 优势
  * Native处理简单， rich-text的所有属性作为一个整体， 对渲染流程和其他组件没有侵入

* 劣势
  * 前端使用相对不方便
  * 不易支持View的嵌入

**Comment by cxfeng1** [comment]
### 编译期转换为JSON

* 前端使用方式

```
<text style="style1">
    some words
    <text style="style2">some other words</span>
    <image src="image-url"></image>
    <a>a link</a>
<text>
```

* js-native 数据交互格式

```
{
    ref : xxx,
    type : richText,
    style : {style1}
    attr : {
        value: [
            // JSON
            {
                start:0,
                end:10,
                style:{}
                
            },
            {
                start:10,
                end:26,
                style:{style2}
            }
            ...
        ]
    }
}
```

* Native 处理方案
  * 如果value是JSON结构，按照富文本处理

* 优势
  * Native处理简单， 所有属性作为一个整体， 对渲染流程和其他组件没有侵入

* 劣势
  * 前端transformer要对rich-text做特殊化处理，不易于后续RX等其他JS框架的扩展
  * JSON协议相对非标准

**Comment by boiawang** [comment]
我比较倾向于第二种，第一种把text的语义都改了。而且增加一个标签我并不觉得增加了使用成本

**Comment by 0326** [comment]
倾向方案2，毕竟开发用户主要还是前端，不赞成内嵌标记语言，还是统一风格好，不然代码看起来很怪异呢：）

**Comment by MrRaindrop** [comment]
倾向方案2，建议`<rich-text>`改为`<rich>`更简洁

**Comment by yfldj** [comment]
方案2＋1

**Comment by gitone** [comment]
根据做类似项目的经验 倾向于方案4， 对前端开发者来说最方便

**Comment by LeeJay0226** [comment]
提供一个思路看看可不可行。可以给text标签增加一种添加rule的方式增加text的符文本样式,例如addrule({
start:0;
end:5;
style:{
type: color;
value:#ff000;
}
})
可以在网络返回数据后动态得添加rule，也可以在text标签的attr中增加一个叫rules的属性，属性的值是一个json求组，在创建标签的时候可以解析该属性。
ps：前段时间在Android上做了一个自定义font-family的功能，也是通过addRule的方式来实现的

**Comment by Jinjiang** [comment]
周末仔细想了想，可能未来想支持 SVG 的时候，还会碰到类似的问题需要纠结，就是 native 渲染的颗粒度和标签的颗粒度不一致，如果可以在标签上加一个通用的 attribute，比如 `append="once"`，语法解析器在解析到这个 attribute 之后，子元素全部等价转换为 `value` 的 attribute，并且格式是 JSON 而不是 string，问题也可以得到解决。

换句话说，是基于方案4抽象一个通用规则，尽量通过标准和规范若化不利方面的影响

**Comment by seajean** [comment]
如果richText里边再嵌套richText的情况也需要考虑一下~

**Comment by Jinjiang** [comment]
如果基于方案2的话，需要 JS Framework 被注册每个组件的信息时，多一个字段，比如 `atom`，如果为 `true` 则表示强制任何子元素的更新都会导致整个大元素重新生成。比如：

```javascript
registerComponents([{ type: 'richtext', atom: true }])
```

同时 virtual-DOM 实现的时候能够识别这个标识，遇到这样的元素的子元素发生更改，就向上追溯到大元素，把子元素都删掉，再创建新的元素添加进去。比如：

```html
<template>
  <div>
    <richtext>
      {{xxx}}
      <span style="color: {{yyy}}">abc</span>
      <image src="{{zzz}}"></image>
    </richtext>
  </div>
</template>
<script>
  module.exports = {
    data: function () {
      return { xxx, yyy, zzz }
    }
  }
</script>
```

任何数据变更，都会触发 `<richtext>` 删掉所有的子结点，然后重新生成所有子节点，相应的 `callNative()` 命令类似：

```javascript
callNative(<instanceId>, [
  { module: 'dom', method: 'removeElement', args: [<oldRichTextNodeRef>]}
])
callNative(<instanceId>, [
  { module: 'dom', method: 'addElement', args: [<refOfRichTextParent>, <newRichTextJSON>, <oldRichTextIndex>]}
])
```

或

```javascript
callNative(<instanceId>, [
  { module: 'dom', method: 'removeElement', args: [<oldTextNodeRef>]},
  { module: 'dom', method: 'removeElement', args: [<oldSpanRef>]},
  { module: 'dom', method: 'removeElement', args: [<oldImageRef>]}
])
callNative(<instanceId>, [
  { module: 'dom', method: 'addElement', args: [<refOfRichText>, <oldTextNodeRef>, -1]},
  { module: 'dom', method: 'removeElement', args: [<refOfRichText>, <oldSpanRef>, -1]},
  { module: 'dom', method: 'removeElement', args: [<refOfRichText>, <oldImageRef>, -1]}
])
```

**Comment by Jinjiang** [comment]
基于方案4：

```html
<richtext>
  {{xxx}}
  <span style="color: {{yyy}}">abc</span>
  <image src="{{zzz}}"></image>
</richtext>
```

经过 transformer 转换之后会变成

```javascript
{
  type: 'richtext',
  attr: {
    value: function () {
      return [
        { type: 'text', attr: { value: this.xxx }},
        { type: 'text', style: { color: this.yyy }, children: [
          { type: 'text', {...}},
          { type: 'text', {...}}
        ]},
        { type: 'image', attr: { src: this.zzz }}
      ]
    }
  }
}
```

**Comment by YorkShen** [comment]
Android的实现需要考虑下面的额外因素
* 是否需要支持`line-height`，目前text的`line-height`的实现依赖于text是block元素，不存在inline特性。如果需要富文本支持`line-height`，android之前的`line-height`实现需要重构。
* 富文本中的image如何与文字对齐，用户可以在image上设置`vertical-align`对齐么，目前android只能做到图片和文本的baseline或bottom对齐。
* 富文本内嵌如果内嵌`<a>`元素，`<a>`元素的点击跳转行为可能和富文本的`onclick`事件冲突。

关于image元素，有以下几个因素需要考虑
* 富文本中的image元素，其宽高是必选项还是可选项？
* 富文本中的image元素，在渲染完成后，图片下载的网络请求尚未返回的时候，是否需要显示一个placehoder。

**Comment by Jinjiang** [comment]
根据方案4例子完整的 JS Bundle 大概是这样的：

```javascript
__weex_define__('@weex-component/richtext-demo', function(require, exports, module) {
  exports.template = {
    "type": "div",
    "children": [{
      "type": "richtext",
      "attr": {
        "value": function () {
          return [
            { type: 'text', attr: { value: this.xxx }},
            { type: 'text', attr: { value: "abc" }, style: { color: this.yyy }},
            { type: 'image', attr: { src: this.zzz }}
          ]
        }
      }
    }]
  }
  exports.data = function() {
      return {
        xxx: 'aaa',
        yyy: '#000099',
        zzz: 'ccc'
      }
    }
  }
})

__weex_bootstrap__('@weex-component/richtext-demo', {
  "transformerVersion": "0.3.1"
})
```

**Comment by YorkShen** [comment]
有以下几个问题， @Jinjiang 
* 形如下面这样的形式，子节点可否继承父节点的style     

        {
         type: 'image',  attr: { src: this.zzz }，style: { color: this.yyy }, children:[
            { type: 'text', attr: { value: this.xxx }
          ]
        }

* 如果image的src或text的value为空或type为空/非法，子节点可否继承父节点的style

**Comment by YorkShen** [comment]
@Jinjiang 
需要一个更复杂的JS bundle，包含所有支持的type类型以及text节点嵌套text节点这样的case。

**Comment by Jinjiang** [comment]
同步一个在 Transformer 里发现的问题：Transformer 在实现的时候遇到一个之前没有充分讨论的场景，就是如果 `<richtext>` 中有 `if` 和 `repeat` 的时候，转换规则会比较复杂，详见这里的讨论：https://github.com/weexteam/weex-templater/pull/1

**Comment by Jinjiang** [comment]
@YorkShen 支持的类型应该就是 text 和 image 和 a，我写了个更复杂的例子：

```html
<richtext>
  {{xxx}}
  <a style="color: blue" href="...">
    456
    <image src="{{yyy}}"></image>
    <text style="font-weight: {{zzz}};">789</text>
  </a>
</richtext>
```

转出来的 JavaScript 是：

```javascript
{
  "type": "richtext",
  "attr": {
    "value": function () {
      return [
        { type: 'text', attr: { value: this.xxx }},
        { type: 'a', attr: { href: '...', value: [
          { type: 'text', attr: { value: '456' }},
          { type: 'image', attr: { src: this.yyy }}
          { type: 'text', attr: { value: '789' }, style: { fontWeight: this.zzz }}
        ] }, style: { color: "blue" }}
      ]
    }
  }
}
```

**Comment by Jinjiang** [comment]
端上的理解建议 @boboning @MrRaindrop 多参与一点吧

**Comment by YorkShen** [comment]
Hi, all.

现存在如下未约定问题及已知问题，需要尽快对未约定的问题进行约定，并解决已知问题。

## 待约定问题
### Image
* 富文本中的image元素，其宽高是必选项还是可选项。
* 富文本中的image元素，在解析完成后，图片下载的网络请求尚未返回的时候，是否需要显示一个placehoder。
* 富文本中的image如何与文字对齐，目前android默认是和文本的baseline对齐。

### Style
* 形如下面这样的形式，子节点可否继承父节点的style

        {
         type: 'image',  attr: { src: this.zzz }，style: { color: this.yyy }, children:[
            { type: 'text', attr: { value: this.xxx }
          ]
        }
        
* 是否需要区分终端节点(terminate node)和非终端节点(non-terminate)。
* 富文本的text需要支持哪些style，有些style，如`line-height`，其实现依赖于text是block元素，无法应用于富文本，需要给出富文本支持的style列表。

## 已知问题
* 构建富文本js-bundle，目前tranformer不支持富文本，也不存在一个富文本js-bundle，需要手动构建js-bundle, 即目前不存在富文本的user case，需要编写富文本的user case
* 需要修改图片库接口，使得通过图片库可以操作drawable而不是imageView。
* 富文本内嵌`<a>`元素（**不是**普通的a标签）的点击事件和富文本的`onclick`事件冲突。

**Comment by imsobear** [comment]
这个问题现在有具体的计划吗？

**Comment by YorkShen** [comment]
@imsobear 下一个版本会支持此功能

**Comment by yujiangshui** [comment]
@YorkShen 大概是一种什么样的使用方法？看上面的评论感觉像是这样的思路：所有内容都是 inline 排下来，然后在 span 上面附加的 styles 可以被读取到作为当前 span 的样式渲染，然后支持嵌套，比如 a 这样的。图片使用 inline-block ？

看到的有点晚，早看到的话我可能会推荐下 draft-js 数据描述方案。它只有一个平级的 block 的概念，里面有文本或者 block 本身是一个类型（图片、blockquote等），block 上面的 text 区分 entity 和 styles 两个概念，均使用 offset 和 length 来描述生效范围。这样 styles 可以叠加描述，对于 a 这种 entity 也不需要使用嵌套了。

https://medium.com/@rajaraodv/how-draft-js-represents-rich-text-data-eeabb5f25cf2

**Comment by YorkShen** [comment]
* js端使用json描述inline或inline-block的概念，js对length，offset的概念无感知。
* native端将js端的json描述解析成[interval tree](https://en.wikipedia.org/wiki/Interval_tree)的形式，并进行渲染。offset和length需要以一种更合理的数据结构组合，以利于search，add，delete操作。android这里使用了基于红黑树的interval tree构建了这个数据结构。
@yujiangshui

**Comment by YorkShen** [comment]
See a Naive implementation of richtext in [weex android](https://github.com/sospartan/weex/commits/android-feature-richtext), it will not be merged into master brach until it is stable.

**Comment by XuDouWei** [comment]
weex现在支持自定义的字体库吗？@YorkShen@Jinjiang

**Comment by YorkShen** [comment]
@XuDouWei Ref https://github.com/alibaba/weex/issues/825

**Comment by zfha** [comment]
@YorkShen 请问下，现在有iOS的实现分支么？

**Comment by YorkShen** [comment]
@zfha This thread will no longer be active as weex has been moved to [apache group](https://github.com/apache/incubator-weex)

**Comment by Jack-In** [comment]
请问下现在这个问题是如何解决的呢

**Comment by YorkShen** [comment]
This PR/issue doesn't receive response since Weex migrated to [Apache](http://incubator.apache.org/projects/weex.html) two years ago and this repository is no longer active yet.

Feel free to ask question in [new repository](https://github.com/apache/incubator-weex) and thanks for your contribution.

**Comment by Hanks10100** [comment]
This issue is outdated for a long time and will be closed now. You can create a new one if you still have questions.
