### ISSUE TITLE
border在ios设备上面不显示，怎么给整个页面设置背景色啊

### ISSUE THREAD

**Issue by uixdk** [alibaba/weex#839]
border: solid 1px #e7e6f0;   在浏览器显示边框，在ios设备上不显示。

weex页面没有body，怎么给整个页面设背景色啊？？

**Comment by cxfeng1** [comment]
目前不支持composed style， 所以还需要你通过分支设置border-style, border-width, border-color来实现

**Comment by Jinjiang** [comment]
1. `border-width: 1; border-color: #e7e6f0; border-style: solid;`
2. 直接给根元素设置背景色即可，比如 `<template><div style="background-color: #fff>...</div></template>`

更多使用问题请移步到中文聊天室 https://gitter.im/weexteam/cn
谢谢
