### ISSUE TITLE
weex sdk pods源什么时候能正式开源

### ISSUE THREAD

**Issue by cooperding** [alibaba/weex#841]
在工程的Podfile文件中加入weex sdk的依赖。
pod 'WeexSDK', '0.6.0' //CocoaPods需要关联的WeexSDK依赖，目前最新的版本号为0.6.0
这个在cocoapods上大概什么时候能开源
https://open.taobao.com/doc2/detail?spm=a219a.7629140.0.0.lorcsy&&docType=1&articleId=104829

**Comment by acton393** [comment]
hi @cooperding  WeexSDK 的pod 源已经提交，可以直接使用，目前有两个版本 `0.6.0` 和 `0.6.1`
你可以直接使用

`pod 'WeexSDK', '0.6.1' ` 引入Weex iOS SDK 到你的工程中
