### ISSUE TITLE
Android 根布局backgroundColor是否有必要

### ISSUE THREAD

**Issue by LeeJay0226** [alibaba/weex#843]
[discuss] Android的下面这段代码是否可以去掉，目前加上这段代码之后存在两个问题：
1. 多一层background，导致过渡绘制增加一层。
2. 在装载weex的布局文件layout中设置了backgroundColor 会不起作用，必须在weex 的template的根布局设置backgroundColor才能设置为真正看得到的backgroundColor

```
Class WXDomStatement 
void createBody(JSONObject element) {
if (domObject.style == null || !domObject.style.containsKey(WXDomPropConstant.WX_BACKGROUNDCOLOR)) {
      style.put(WXDomPropConstant.WX_BACKGROUNDCOLOR, "#ffffff");
    }
}
```

**Comment by zshshr** [comment]
这个背景色，跟ios统一逻辑以后，下个版本去掉
