### ISSUE TITLE
整合iOS项目，图片不显示

### ISSUE THREAD

**Issue by QETHAN** [alibaba/weex#844]
Podfile:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'WeexSample' do
    platform :ios, '7.0'
    pod 'WeexSDK', :path=>'./sdk/'
    pod 'SDWebImage', '3.7.5'
end

安装SDWebImage后，图片还是不显示。

<Weex>[debug]WXImageComponent.m:170, Updating image, component:347, image source:https://img.alicdn.com/tps/i2/TB1hRb1IXXXXXX3XVXXXQaP.pXX-87-87.jpeg, userInfo:{
    imageQuality = 0;
    imageSharp = 0;
}

**Comment by acton393** [comment]
.we文件里面有给宽高么

**Comment by QETHAN** [comment]
样式有写宽高。现在解决了。
#import <Foundation/Foundation.h>
#import <WeexSDK/WeexSDK.h>

@interface WeexImageDownloader : NSObject<WXImgLoaderProtocol>

@end

#import "WeexImageDownloader.h"
#import <SDWebImage/SDWebImageManager.h>

@implementation WeexImageDownloader

- (id<WXImageOperationProtocol>)downloadImageWithURL:(NSString *)url
                                          imageFrame:(CGRect)imageFrame
                                            userInfo:(NSDictionary *)options
                                           completed:(void(^)(UIImage *image,  NSError *error, BOOL finished))completedBlock {
    return (id<WXImageOperationProtocol>)[[SDWebImageManager sharedManager] downloadImageWithURL:[NSURL URLWithString:url] options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) {
    } completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
        if (completedBlock) {
            completedBlock(image, error, finished);
        }
    }];
}

@end

AppDelegate.m:
 
    [WXSDKEngine registerHandler:[WeexImageDownloader new] withProtocol:@protocol(WXImgLoaderProtocol)];
