### ISSUE TITLE
support onPressIn onPressOut

### ISSUE THREAD

**Issue by pcxiong** [alibaba/weex#848]
Just like React Native.
[http://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#onpressin](url)

**Comment by MrRaindrop** [comment]
Hi there,

Currently we support

* `touchstart`
* `touchmove`
* `touchend`
* `touchcancel`

for device touching events, and

* `panstart`
* `panmove`
* `panend`
* `swipe`
* `longpress`

for advanced touch gestures.

Maybe `touchstart` and `touchend` is what you need.

**Comment by pcxiong** [comment]
Thanks for your reply.
That's awesome, I will have a try.
Is the documentation missing something?
I just can not find any details about touch* events in this page [http://alibaba.github.io/weex/doc/references/common-event.html](url)

**Comment by Jinjiang** [comment]
We will review our docs and fix it. Thx.
