### ISSUE TITLE
WXUtility.h  error declaration of anonymous class must be a definition

### ISSUE THREAD

**Issue by QETHAN** [alibaba/weex#849]
![image](https://cloud.githubusercontent.com/assets/3423104/17081313/b5ace166-5185-11e6-941f-5b21a9128b12.png)

环境: xcode7

**Comment by acton393** [comment]
hi @QETHAN  你这个问题还存在么，源码编译Weex SDK 的时候出现的么？

**Comment by acton393** [comment]
先暂时关闭了~，如果有问题再打开

**Comment by QETHAN** [comment]
现在没有了。按照文档步骤之后，谢谢。

**Comment by feijiwa** [comment]
xcode8 也出这个问题了

**Comment by chengweipeng123** [comment]
修改项目任何.m文件为.mm文件再编译，可reproduce。

**Comment by chengweipeng123** [comment]
修改项目任何.m文件为.mm文件再编译，可reproduce。
估计是变量名class与c++关键字冲突，所以需要改个变量名。

**Comment by MagicNew** [comment]
遇到同样的问题了，重命名变量名class吧
