### ISSUE TITLE
没有一键打包工具吗，必须要会开发原生应用，才可以使用weex吗

### ISSUE THREAD

**Issue by iloveyo123u1** [alibaba/weex#850]
发现官方没有提供 一键打包工具，提供的教程，教了如何集成到安卓里，还要学java语言

**Comment by bryantwu** [comment]
@iloveyo123u1 一键打包在排期开发中，很快出来。

**Comment by Jinjiang** [comment]
#705 这个问题重复了，先做关闭处理，更多讨论可以移步 #705 
谢谢
