### ISSUE TITLE
WeexSDK framework 整合iOS报错

### ISSUE THREAD

**Issue by QETHAN** [alibaba/weex#852]
按照下边步骤做的：  
![image](https://cloud.githubusercontent.com/assets/3423104/17088540/305d8464-524f-11e6-8f5e-9ba3f81fce51.png)

出错：  
![image](https://cloud.githubusercontent.com/assets/3423104/17088549/5560ce1a-524f-11e6-96f2-6485a2232374.png)

**Comment by MrDragonn** [comment]
我也报这个错了  怎么解决啊

**Comment by acton393** [comment]
hi @MrDragonn , @QETHAN , 这主要是缺少依赖，SocketRocket和系统的一些framework，

解决方法： 
 - SocketRocket依赖：copy [这里](https://github.com/alibaba/weex/tree/dev/ios/sdk/WeexSDK/dependency) `SRWebSocket.h/m` 到自己的工程  （如果你的工程使用了cocoaPods，添加 `pod 'SocketRocket'` 到Podfie 中即可）

-  系统库依赖，添加如下图framework([文档](https://open.taobao.com/doc2/detail?spm=a219a.7629140.0.0.tFddsV&&docType=1&articleId=104829))到自己的工程，
 ![img](http://img1.tbcdn.cn/L1/461/1/ce309c54c7b3dd3607d7a3d07c44bfd0e0e10f86)

**Comment by QETHAN** [comment]
@acton393 谢谢

**Comment by QETHAN** [comment]
![image](https://cloud.githubusercontent.com/assets/3423104/17091394/812d50d2-526c-11e6-906d-fb481063b1e2.png)

@acton393 现在这种情况怎么破啊

**Comment by QETHAN** [comment]
WeexSDK 和 ALBBSDK 里边有一样的文件. 这如何是好啊
@acton393

**Comment by QETHAN** [comment]
上边那个问题解决了。rename WeexSDK里WXModuleManager.h / m的文件名 to WXModuleManager1.h / m, 然后又编译生成了新的framework

**Comment by acton393** [comment]
hi， @QETHAN  ,  你应该是集成了百川的 旺信SDK，旺信SDK里面也有`WXModuleManager` 这个符号，与WeexSDK 的取名冲突， 可以建议你在 Weex SDK 里面更换一下这个类的名字， 改成 `WXModulesManager` 或者其他

**Comment by QETHAN** [comment]
@acton393  是的，改名字了
