### ISSUE TITLE
ios 集成的时候显示XCTest/XCTest.h 文件找不到

### ISSUE THREAD

**Issue by MrDragonn** [alibaba/weex#854]
ios 集成项目的时候按照给的文档提示:

![image](https://cloud.githubusercontent.com/assets/15952009/17089147/ff79362a-5255-11e6-80df-544c2be50f64.png)

**Comment by acton393** [comment]
hi， @MrDragonn  你是到了哪一步骤出现了这个问题

**Comment by MrDragonn** [comment]
@acton393  我是先git colne 到本地,将ios目录下的sdk拷贝到项目下 然后编译了一下就出现这个错误了

**Comment by limeidong** [comment]
请问楼主解决了没有，我现在也是遇到了这个问题
