### ISSUE TITLE
weex项目在PC端本地运行错误上周就反馈了还没有解决

### ISSUE THREAD

**Issue by 1459416736** [alibaba/weex#855]
我是clone 下来的项目
运行截图如下
![qq 20160725110242](https://cloud.githubusercontent.com/assets/6478087/17089159/1e852a42-5256-11e6-9f7d-416a665af920.png)

**Comment by Jinjiang** [comment]
Could you please check `html5/runtime/config.js` file generated when you run `npm run build:config`?

**Comment by Jinjiang** [comment]
This command will execute `/build/config.frameworks.js`. If you find something wrong please tell us. And also welcome fix it and send a pr to us.

有劳运行 `npm run build:config` 并确认一下 `html5/runtime/config.js` 是否被创建，如果这部分代码在 PC 下存在问题请告诉我们，同时也欢迎您直接修复问题并 pull request 给我们。谢谢

**Comment by 1459416736** [comment]
ok,已解决

**Comment by linuxing3** [comment]
也被同样的问题坑了半天
