### ISSUE TITLE
WXSDKError: framework loading is failure

### ISSUE THREAD

**Issue by QETHAN** [alibaba/weex#858]
错误：  
<Weex>[error]WXSDKError.m:39, framework loading is failure! [;

**Comment by acton393** [comment]
hi ， @QETHAN ，如果是通过导入SDK framework 的方式，得把 main.js(在 WeexSDK.framework 中) 添加到 bundle 中  按照[这个](http://open.taobao.com/doc2/detail?&docType=1&articleId=104829)地方文档

如图 ![img](http://img1.tbcdn.cn/L1/461/1/bb3998595bafe9c9336411160c0b6bd3eeb843ef)

**Comment by QETHAN** [comment]
@acton393 you're my life saver! it works. thx
