### ISSUE TITLE
对整个weex重新build和dist后，输出weex-html5中的weex.js出现兼容性问题

### ISSUE THREAD

**Issue by rhizx** [alibaba/weex#861]
对整个weex重新build和dist后，输出weex-html5中的weex.js出现兼容性问题
除了safar浏览器，其他浏览器中均出现
Uncaught TypeError: undefined is not a function 
检查后发现是
Object.assign出现问题

然后通过和原始weex.js文件进行对比，发现很对代码在新packing的weex.js中不存在，怀疑可能是某些模块未成功打包，求能够完整编译打包的方法和教程，谢谢

**Comment by rhizx** [comment]
看来还得靠自己，研读源码后发现了猫腻，已经解决了

**Comment by MrRaindrop** [comment]
hi 能说在下出现问题的环境么？包括os版本及浏览器版本号. 
源码中应该已经去掉了所有`Object.assign`, [转而使用`extend`方法代替](https://github.com/alibaba/weex/blob/dev/html5/shared/index.js#L12-L26)。

**Comment by Jinjiang** [comment]
可能是 weex-loader 打包之后用到了 `Object.assign` 导致的 @terrykingcha 也麻烦留意一下

**Comment by rhizx** [comment]
我已经查出原因了，是由于weex-transformer不是0.3.1版本，我把weex-transformer升级到0.3.1就可以了，相应的weex init生成的工程package.json也要做相应的依赖版本升级才能正常使用新打包的weex.js，主要修改内容如下：
**"transformer": "^0.3"**
**"weex-loader": "^0.2.0"**
还有就是在做test 的时候，会提示selenium-server-standalone-jar不存在的错误，需要将对应版本的jar包copy到相应server目录的lib文件夹下即可

**Comment by Jinjiang** [comment]
weex-js-framework@0.15.2 已经加上了 Object.assign，selenium-server-standalone-jar 版本也更新了，这个 issue 我先关掉了

谢谢
