### ISSUE TITLE
[Feature Request] hook function 'destroyed' in component lifecycle 

### ISSUE THREAD

**Issue by daxingplay** [alibaba/weex#862]
As described in the [doc](http://alibaba.github.io/weex/doc/references/component-defs.html), Weex provide three lifecycle options: `init`, `created`, `ready`. But I need `destroyed` hook function when component was destroyed to do some cleanup work to prevent memory leak.

```
module.exports = {
  data: ...,
  methods: ...,
  destroyed: function () {
    console.log('this component was destroyed.')
  },
  ...
}
```

**Comment by Jinjiang** [comment]
You are right. Sometimes it need to hook something when component destroyed.
Well would you please have a little try to support this feature :-)
