### ISSUE TITLE
list demo在iOS模拟器上有问题

### ISSUE THREAD

**Issue by QETHAN** [alibaba/weex#863]
下边是那个示例代码：
https://github.com/alibaba/weex/blob/example/examples/component/list/list-basic.we

在iOS模拟器里，pull refresh之后，再去pull就不行了；load more之后，就回不到顶部了，自动回到底部。

**Comment by acton393** [comment]
hi @QETHAN  pull refresh  dev 分支 是这样： 第一次pull的时候， indicator 没有影藏，可以看到，放开之后才真正的影藏（取决于.we 文件中对refresh status的更新），所以下次，再拉的时候，是处于影藏状态的，就看不到了， list-basic 中对refresh 的status 变更太快， 建议你可以加一个 settimout ，3 s 之后再去变更status ,就可以看到效果，

针对，首次下拉没有影藏indicator 的问题，新的版本已经修复

loading 确实存在这个 回不到顶部的问题，在新版本中将统一修复一下，待修复之后我再关闭该issue

**Comment by acton393** [comment]
hi @QETHAN  这个已经fix 了在最新的dev 分支 #975

可以试试下，如果有问题，继续open issue 并回复

实现刷新的效果，可以增加settimout   可以先暂时参考下[这个](https://github.com/alibaba/weex/blob/doc/doc/modules/timer.md)文档， 后面会更新到官网doc
