### ISSUE TITLE
页面加载显示能否优化？

### ISSUE THREAD

**Issue by iniwf** [alibaba/weex#864]
每次打开新的页面，都是先显示空白页面，再加载数据由上往下刷新显示。能否做到页面从右往左打开的时候就有数据内容在页面上面？

**Comment by luics** [comment]
好建议，如果不影响转场流畅性是可以考虑的

**Comment by iniwf** [comment]
@luics，我觉得这个体验不太好，希望改进。。。

**Comment by iniwf** [comment]
@luics 大神，有另外一个问题，顺便问了，weex能不能调用第三方so库？有没相关的例子？

**Comment by zshshr** [comment]
@iniwf 扩展moudle就好啦，把第三方的so封装jni接口，然后在自定义的moulde中调用

**Comment by zshshr** [comment]
@iniwf 你的意思Activity的转场动画吗？这个动画是activity级别的，你们可以给予playground自己定义，出来就有数据的话，可以监听渲染完成的回调去控制转场动画的时机

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
