### ISSUE TITLE
安卓的SDK 有hlist 和list iOS的只有list 这个怎么弄啊

### ISSUE THREAD

**Issue by MrDragonn** [alibaba/weex#865]
安卓的SDK 有hlist 和list iOS的只有list 这个怎么弄啊

**Comment by luics** [comment]
hlist 应该还是实验特性，文档中也没放出来 http://alibaba.github.io/weex/doc/components/list.html
@MrDragonn 你是看源码发现的 :)

**Comment by LeeJay0226** [comment]
@luics 其实我建议去掉hlist, 应该对外提供统一的list component组件，通过orientation来控制水平or垂直，通过direction控制从左至右or从右至左等。另外由于目前Android SDK 中的list通过RecyclerView实现，后期可能还会有加入GridLayoutManager、StaggeredGridLayoutManager等布局，通过attr的设置来实现不同展示更为合理一些。

**Comment by sospartan** [comment]
@LeeJay0226 分成两个组件是因为,实现的限制导致 'orientation'不能动态修改.

**Comment by LeeJay0226** [comment]
@sospartan 分成两个组件之后就是为了只能在初始化时设置orientation，不给用户动态修改orientation的权限？我的理解目前Android 上的RecyclerView虽然可以动态的设置LayoutManager，但很少有业务会去动态改LayoutManager，只会在RecyclerView创建完后设置一次LayoutManager吧

**Comment by sospartan** [comment]
@LeeJay0226  我说的限制,不一定是android,H5/iOS也必须要考虑~~

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
