### ISSUE TITLE
【新需求】Weex中native主动发送事件到JS

### ISSUE THREAD

**Issue by JackyAndroid** [alibaba/weex#866]
Weex中是否有类似react native “原生模块可以在没有被调用的情况下往JavaScript发送事件通知” 的功能。 我在文档中和源码中没有发现。 

我们现在需要在android native 端截取键值然后主动发送给JS,JS实现相应的界面变化，这种需求能满足吗？

**Comment by sospartan** [comment]
类似的'全局事件'方案目前还没有,可以通过自定义module来实现,在计划中,你可以具体描述一下你的需求.

**Comment by JackyAndroid** [comment]
@sospartan 但是自定义module是js--native--js这个流程吧，我们需要native--js
我们目前需要在电视上面通过遥控器的键值控制页面元素的移动选择，所以需要**主动**发送上下左右键值给js，以前使用react native 方案是可以主动发送事件传递键值，不知道weex是否支持？如果目前不支持那计划大概是什么样的？

**Comment by sospartan** [comment]
目前可以通过在page的created事件时去调用native module,并把js的callback注册给native,native存为变量,然后在需要调用时通过callback触发js的处理函数

**Comment by sospartan** [comment]
系统的内置的'全局事件',实现上会与我说的这个类似,只是我们会把它做在框架内,然后更加通用.

**Comment by JackyAndroid** [comment]
@sospartan 好的，那我试试这种方式，多谢🙂

**Comment by sospartan** [comment]
@JackyAndroid 恩  如果问题可以reopen这个问题 我来及时跟进.

**Comment by Jinjiang** [comment]
补充一下，目前 native 可以在没有被调用的情况下对 JavaScript 执行 refreshInstance，有机会修改 data 对象，应该同样可以满足你的需求

**Comment by Bijiabo** [comment]
@sospartan 你说的这种方式尝试了一下是可以的，但是 native 保存的 callback 只能调用执行一次，请问有没有办法可以调用多次呢？

**Comment by Bijiabo** [comment]
@sospartan 目前在 native 内保存为变量的 callback 只能运行一次，第二次调用的时候就没有执行了（看起来是这样的），希望能重复使用。

**Comment by sospartan** [comment]
@Bijiabo 回调js有两种方式,你用的直接使用callbackID去调用么,还是使用`JSCallback`?

**Comment by Bijiabo** [comment]
@sospartan 保存JSCallback为闭包之后，只能调用一次。你提到的使用callbackID去调用，我先前是不知道的，参考 https://github.com/alibaba/weex/blob/doc/doc/how-to/cuszomize-native-apis.md 尝试了一下：

```
-(void) openUrl: (NSString*)url withCallbackId:(NSString*)callbackId {
    NSDictionary *HashMap = @{
                              @"firstKey": @"balabala"
                              };
    NSError *err;
    NSData *jsonData = [NSJSONSerialization dataWithJSONObject:HashMap options:0 error:&err];
    NSString *HashMapString = [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
    [[[WXBridgeManager alloc] init] callBack:weexInstance.instanceId funcId:callbackId params:HashMapString];
}
```
没有看到有相关效果运行，在类中保存 callbackID 在其他地方调用也不可以。不知是否是我调用 API 的方法不当？

**Comment by sospartan** [comment]
@Bijiabo `JSCallback`有两个方法,你使用'invokeAndKeepAlive`,就可以多次调用的

**Comment by Bijiabo** [comment]
@sospartan 能否提供一下 iOS 相关示例代码？实在有点不知所措。
除了上面提到的 callbackID 和直接保存 callback 闭包的方法，尝试了一下在 module 中添加一个方法将 WXModuleCallback 直接保存之后调用：
```
-(void)testContent: (NSString*)content forCallback:(WXModuleCallback)callback {
    self.callback = callback;
}
```
依然只能执行一次

**Comment by acton393** [comment]
hi @Bijiabo  iOS的 多次服用module  可以参考 [这里](https://github.com/alibaba/weex/blob/dev/ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m)的实现


这里面的fetch 方法实现，第二个参数是progressCallback 是多次可以调用的，这里的progressCallback 是一个function id，是在.we 里面js的function的实现运行时注入之后 保存的function id

**Comment by Bijiabo** [comment]
@acton393 可以了，感谢！

**Comment by Bijiabo** [comment]
```
[[WXSDKManager bridgeMgr] callBack:self.weexInstance.instanceId funcId:callback params:@{@"login": @TRUE} keepAlive:true];
```
这里的`params`要求是 NSString，实际使用中包括官方的代码也传入的是 NSDictionary，是否需要更改一下呢？

**Comment by acton393** [comment]
@Bijiabo  这个已经fix ,现在是参 params 参数要求是id ， 参见 #900

**Comment by Bijiabo** [comment]
@acton393 好的，这样 params 支持的参数类型是 NSDictionary, NSString, NSArray, Int, Float, Bool ?

**Comment by acton393** [comment]
0.8 已经添加支持 [doc](http://alibaba.github.io/weex/doc/modules/globalevent.html) ， 这个issue先关了，如果有问题可以重新打开

**Comment by yuxingfafu** [comment]
有无android的democode,
我这边是这样的：
fragment是原生的，fragment里面加载js，eventbus通知到fragment，js里面需要重新查询调用接口，有没有类似的解决方案？？谢谢

**Comment by 766** [comment]
文档 404了

**Comment by acton393** [comment]
https://weex-project.io/cn/references/modules/globalevent.html  @766   已经更新

**Comment by yuxingfafu** [comment]
@acton393 这个问题是否能够帮忙看下呀？非常感谢，这个问题排查了好久
https://segmentfault.com/q/1010000009423828
