### ISSUE TITLE
devtool 更新代码未生效

### ISSUE THREAD

**Issue by yuanzhaohao** [alibaba/weex#867]
bug：使用这个工具，更新代码时，通过这个工具查看并没有生效。（不知道是不是这个工具使用了某种缓存）
https://github.com/alibaba/weex/blob/dev/doc/tools/devtools.md

**Comment by exolution** [comment]
请问，你是怎样使用的？
请简单描述下你的场景（源代码在哪放着），执行的命令是什么？

**Comment by Jinjiang** [comment]
由于长时间没有后续讨论，这个 issue 暂时做关闭处理
更多讨论可以移步到 https://github.com/weexteam/weex-devtool/issues 讨论
谢谢
