### ISSUE TITLE
最新的input.js组件源码有代码错误,请修正

### ISSUE THREAD

**Issue by rhizx** [alibaba/weex#872]
原始代码：
// updatable styles
Input.prototype.style = extend(
  **Object.create(Atomic.prototype.style, {**
    placeholderColor: function (val) {
      this.setPlaceholderColor(val)
    }
  }))

修改后的代码：
// updatable styles
Input.prototype.style = extend(
  **Object.create(Atomic.prototype.style), {**
    placeholderColor: function (val) {
      this.setPlaceholderColor(val)
    }
  })
这个问题会直接导致placeholder-color不生效

**Comment by luics** [comment]
如果方便，请直接提交 pr 到 dev 分支 ：）

**Comment by rhizx** [comment]
好的

**Comment by MrRaindrop** [comment]
This will be fixed when the next refactor branch is merged. https://github.com/alibaba/weex/pull/973

**Comment by Jinjiang** [comment]
merged
