### ISSUE TITLE
为何android的inspect不提供aar，必须源码依赖？

### ISSUE THREAD

**Issue by 750813987** [alibaba/weex#873]
**inspect**部分的文档这样描述的：
<img width="383" alt="2016-07-27 10 46 34" src="https://cloud.githubusercontent.com/assets/19163532/17162328/b611c572-53e7-11e6-9ea6-e5b4b852fc6f.png">

为何都不说一下需要下载android/inspect目录下的源码，放在app同级目录。直接这样？开发者感觉莫名其妙。

**况且**，文档也写错了，应该是
```java
dependencies {
      compile project(':inspector')
}
```
作者不检查一下？一行代码两处错误，十分的不负责任

**还有**，需要在工程的根目录下的settings.gradle下添加inspector，比如：
```java
include ':app', ':inspector'
```

**Comment by littleseven** [comment]
thanks，the issue have fixed～

Inspector for android has moved to https://github.com/weexteam/weex_devtools_android，the aar depedency is under testing now, you can have a taste with 
```
compile 'com.taobao.android:weex_inspector:0.0.2.1-alpha'
```
if any bugs you find, please report to https://github.com/weexteam/weex_devtools_android/issues
