### ISSUE TITLE
使用箭头函数this指向不对

### ISSUE THREAD

**Issue by mickeyinfoshan** [alibaba/weex#876]
在`computed`和`methods`中使用箭头函数会导致函数`this`指向不对。

例子：
```es6
module.exports = {
        data : {
               firstName: 'John',
               lastName: 'Smith'
        },
        computed : {
              fullName : {
                   get : ()=>`${this.firstName} ${this.lastName}` // "undefined undefined"
               }
        },
        methods : {
              sayHello : ()=>alert(this.fullName) //undefined
        }
    }

```
会不会是vue本身的问题？我没试验过

**Comment by Jinjiang** [comment]
箭头函数本身不应该这样使用的，一旦你这样写，相当于是吧this指向了最外层。用正常的函数写法就没有问题了，你可以试试看

**Comment by mickeyinfoshan** [comment]
为什么不学react那样autobinding呢？

**Comment by Jinjiang** [comment]
这是 JavaScript 语法本身的问题，我们默认直接写 this 肯定没问题，但是你 arrow function 用错地方了……

多说一点，React 里面每个组件描述就是一个 ES Class，Vue/Weex 使用的是 options，然后通过通用的构造函数运行组件的实例，理念上有不太一样的地方，如果你比较纠结这个问题，可以直接到 Vue 的社区多问问看：）
