### ISSUE TITLE
绑定disappear event的元素位置更新之后，判定触发disappear的位置没有跟着更新

### ISSUE THREAD

**Issue by kmCha** [alibaba/weex#879]
![](http://7xoxzw.com1.z0.glb.clouddn.com/16-7-27/55927919.jpg)

如图所示，anchor上绑了disappear事件处理函数，当上面的div高度改变（也就是anchor的位置改变）之后，触发disappear事件的位置并不是新anchor的位置。

问题demo: [weex-issue](https://github.com/kmCha/weex-issue)
运行
```bash
weex src/disappear-event.we --qr
```

**Comment by acton393** [comment]
hi @kmCha  这确实是我们的一个bug，后面会修复掉

**Comment by cxfeng1** [comment]
已在0.7版本修复
