### ISSUE TITLE
[indicator]Indicator component did not have a default width&height

### ISSUE THREAD

**Issue by LululuSir** [alibaba/weex#883]
The doc says the indicator default width and height is the parent slider's width and height.
But there's no default width and height. If we did not set a width&height when use indicator,  the indicator cannot render normal.

**Comment by boboning** [comment]
感谢反馈，我们确认后会修复此问题，并更新文档，建议先设置上宽高。

**Comment by Jinjiang** [comment]
@DoranYun 留意一下文档的相关工作

**Comment by DoranYun** [comment]
已加入文档。
