### ISSUE TITLE
render error: createInstance fail!

### ISSUE THREAD

**Issue by peirancao** [alibaba/weex#885]
---
07-28 15:06:35.279 28735-28781/com.baixing.ejia E/art: No implementation found for int com.taobao.weex.bridge.WXBridge.execJS(java.lang.String, java.lang.String, java.lang.String, com.taobao.weex.bridge.WXJSObject[]) (tried Java_com_taobao_weex_bridge_WXBridge_execJS and Java_com_taobao_weex_bridge_WXBridge_execJS__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2_3Lcom_taobao_weex_bridge_WXJSObject_2)

**Comment by zshshr** [comment]
@peirancao 给个详细点的信息哈，初步估计你的so加载失败了

**Comment by Jinjiang** [comment]
咱们 gitter 继续，这里我先关掉了
谢谢
