### ISSUE TITLE
2 error when I compile my first app

### ISSUE THREAD

**Issue by xiaoao** [alibaba/weex#892]
"_OBJC_CLASS_$_JSContext", referenced from:

      objc-class-ref in libWeexSDK.a(WXJSCoreBridge.o)

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by acton393** [comment]
hi @xiaoao  , 你需要添加下  系统库    `JavaScriptCore.framework`到你的工程中

或者现在可以直接使用  pod 引入， 参见 #841 ，集成问题欢迎直接在gitter上提~~

**Comment by xiaoao** [comment]
Thank you! @acton393
