### ISSUE TITLE
如何部署类似RN的code push和如何动态加载we文件

### ISSUE THREAD

**Issue by zjsxfly** [alibaba/weex#895]
我现在的需求是类似支付宝主页，进去后有很多应用，点具体应用时，动态加载应用页面（不打包至APP），请问:
1.如何部署类似RN的code push和如何动态加载we文件
2.如果我将应用页面的网络请求使用独立的js文件来处理，是否可以一起动态加载，然后调用。
3.这样子动态加载文件是否不安全，会被劫持，还是通过https加载

**Comment by cxfeng1** [comment]
1. code push目前还不支持Weex，想要获得类似"预加载"的效果，App可以做一下简单的处理，对于你的场景， 在进入"类似支付宝主页"的时候就可以提前判断是否有应用的JS有更新，并提前下载到本地。 未来alibaba应该也会推出类似的预加载服务。 另外如果只是单纯地部署Weex的JS， 任何服务器和CDN都是可以的， 只需要按照部署普通JS资源的方式处理即可。
2. 对于你的场景， 每个应用可以对应一个JS， 打开具体的应用就动态下载具体的JS来渲染， 这也是非常适合用Weex的一种模式
3. 网络通道层的安全性，建议直接用https来保证， 当然你也可以将JS压缩成zip，然后使用非对称算法在服务端加密和在客户端解密。
