### ISSUE TITLE
Support for modern CSS layout

### ISSUE THREAD

**Issue by zoomclub** [alibaba/weex#896]
Will Weex support CSS-Grid? The Web can expect this revolutionary layout solution very soon as it is already working behind the flags of all major browsers.

Having a quick look around I saw that Weex makes use of CSS-Layout from Facebook. That is not what I had expected (maybe as a stop gap only) because the Facebook API is only based on a subset of the Flexbox spec.

Essentially, CSS-Grid is suitable for robust X, Y and Z layout, while Flexbox is a more one dimensional option. Thanks for your interest in the future, here are a few links to consider:

http://gridbyexample.com/examples/page-layout
http://igalia.github.io/css-grid-layout/index.html

**Comment by Jinjiang** [comment]
Yes you are right grid layout is awesome, absolutely.

Support this feature means we need some consideration and preparations more:

1. Know-how for front-end engineers, not very much developers familiar with grid layout today.
2. Efficiency, wide and strong enough implementation in mobile browsers http://caniuse.com/css-grid and native view (css-layout)
3. The simplification of tech design of a framework/solution.

Maybe the research should be continued as anyway anyone like. And the discussion could be made again in a more appropriate time when the stuff above come true.

Thanks.

**Comment by zoomclub** [comment]
Thanks, it is good to have this on the radar. CSS-Grid is something to anticipate with certainty and learning it for frontend engineers is very easy, there are already numerous tutorials. In addition frontend engineers will drop what they know as soon as they see how incredibly efficient layout has become with CSS-Grid.

Likely an enhancement to the CSS-Layout library is in order ASAP. Maybe a translation of CSS-Grid semantics to something the CSS-Layout requires is a start.
