### ISSUE TITLE
"chromedriver": "^2.21.2" 在 mac 下用npm安装失败

### ISSUE THREAD

**Issue by transtone** [alibaba/weex#897]
https://github.com/giggio/node-chromedriver/issues/44

是否应该更新一下 package.json

**Comment by Jinjiang** [comment]
ci 跑挂了有可能和这个有关 @MrRaindrop 关注一下

**Comment by Jinjiang** [comment]
#902 fixed this issue
Thanks

**Comment by transtone** [comment]
why not update the package.josn in `jsfm-feature-vue` branch?
