### ISSUE TITLE
jsfm-feature-vue 分支跑不起来

### ISSUE THREAD

**Issue by transtone** [alibaba/weex#898]
localhost:12580 打开之后，点击任何地方都提示：
`index.js:84 Uncaught TypeError: Cannot read property 'apply' of undefined`

**Comment by Jinjiang** [comment]
Thanks for report, I will check this out.

**Comment by Jinjiang** [comment]
如果 `html5/runtime/config.js` 已经生成过了，麻烦重新运行一下 `npm run build:config -- Vue`，应该就可以了

**Comment by Jinjiang** [comment]
另外留意一下 `weex-vue-framework`, `weex-vue-loader`以及 `weex-vue-loader` 里依赖的  `weex-vue-framework` 的版本，`weex-vue-loader` 最新的版本是 0.1.0， `weex-vue-framework` 最新的版本是 0.1.2，如果这个版本不完全对得上，把 `node_modules` 文件夹删掉重新 `cnpm i` 安装一遍应该就好了

**Comment by Jinjiang** [comment]
这个 issue 我先关掉了，如果还有问题可以在中文聊天室里探讨 https://gitter.im/weexteam/cn
谢谢

**Comment by transtone** [comment]
重新运行了 ` npm run build:config -- Vue ` 还是同样的错误。`node_modules` 已经删掉重装好几次了。

package.json 里的版本都没有修改过。刚检查了一下，都是最新版。

**Comment by transtone** [comment]
fixed，must update `weex-vue-framework` to  `0.1.3`。
