### ISSUE TITLE
weex_debug  libs/class.jar 

### ISSUE THREAD

**Issue by dssljt** [alibaba/weex#899]
This jar package source code open source? In what place
I　can not fond it

**Comment by zshshr** [comment]
@dssljt 这个jar是内部工具类，用于查看weex的debug信息的，还没有开源

**Comment by luics** [comment]
playground 中会用到了（界面上的悬浮按钮），不会打包到 sdk；
可以根据你们的实际情况决定使用或不使用，不影响 weex sdk 的接入。

**Comment by dssljt** [comment]
对于android6.0的适配有问题，andriod6.0上面显示不出来
