### ISSUE TITLE
Android模块开发WXBridgeManager.getInstance().callback()的data

### ISSUE THREAD

**Issue by bringmehome** [alibaba/weex#906]
Hi，
请问android模块开发里返回给前端的参数必须是Map<String, Object>格式的吗？
我使用Json或者String或者JSONArray前端收到的都是空的。
如下：
native：
                public void onDevicesFind(JSONArray deviceStatus) {
                    Log.d("---fog---", deviceStatus.toString());
                    WXBridgeManager.getInstance().callback(instanceId, callbackId, deviceStatus, true);
                }

js：
        fog.startSearchDevices("test",function(ret){
            console.log(" js fog ----- ", JSON.stringify(ret));
        });

log：
07-29 18:16:37.119 4797-4838/com.taobao.weex.sample.app D/jsengine: jsLog>>>>: js fog -----  | {} | __LOG | 
07-29 18:16:37.119 4797-4838/com.taobao.weex.sample.app D/jsLog:  js fog -----  | {} | __LOG |

**Comment by bringmehome** [comment]
这个map其实是可以当作json用就是了

**Comment by bringmehome** [comment]
我能不能把“**{\"message\":\"success\"}**”这样一个字符串转为json传给js呢，目前传的都是字符串，没找到com.alibaba.fastjson.JSONObject的string转json的方法

**Comment by xkli** [comment]
@bringmehome 必须是Map格式的，因为这个函数的参数就是Map，你传入其他的参数类型，这个方法是没有办法执行的。

JSONObject jsonObject= JSON.parseObject("你要转换的字符串")

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
