### ISSUE TITLE
[bug] Android上网络数据返回后js抛出了异常页面crash退出，使用本地同样的数据mock后正常

### ISSUE THREAD

**Issue by LeeJay0226** [alibaba/weex#907]
![1fa0af23-0904-4cb7-a8fa-73c501ac65db](https://cloud.githubusercontent.com/assets/7502237/17245405/eb3238d6-55b8-11e6-9355-7cad84cd8002.jpg)

**Comment by YorkShen** [comment]
crash日志截全一些，现在看不到crash原因

**Comment by YorkShen** [comment]
看起来像Continue bye的问题，现已修复，如果有问题，再打开问题。 @LeeJay0226
