### ISSUE TITLE
Android模块 js端提交的参数均会转为String

### ISSUE THREAD

**Issue by bringmehome** [alibaba/weex#908]
请问开发模块的时候js提交的参数均会转为String格式吗，

js：
       fog.startEasyLink(**{
          ssid:"feeling",
          password:"00000000",
        }**,function(ts){
            console.log(" js fog ----- ", JSON.stringify(ts));
        });

native：
1、如果这样接收parameters是有参数的
 @WXModuleAnno
    public void startEasyLink(**String** parameters, String callbackId) {}

2、如果这样接收，parameters就是个空json（"{}"）
 @WXModuleAnno
    public void startEasyLink(**JSONObject** parameters, String callbackId) {}

**Comment by bringmehome** [comment]
为什么没有人回答呃？

**Comment by zshshr** [comment]
@bringmehome 说明你你依赖的版本或分支，如果再最新的分支上，请检查一下public void startEasyLink(JSONObject parameters, String callbackId) {} 中这个JSONObject 这个包引用的是不是com.alibaba.fastjson.JSONObject

**Comment by bringmehome** [comment]
果然是这个原因，引入的包不对，现在好了，谢谢了
