### ISSUE TITLE
能否把weex作为一个类似Vue.js的MVVM框架运用于PC网页，如果可以请问怎么做？

### ISSUE THREAD

**Issue by JayWii** [alibaba/weex#913]
之前的项目中使用了Vue.js作为框架，很是喜欢，但Vue.js不支持IE8，听说WEEX是兼容IE8的，但是找了很久没找到合适的文档说明，所以想知道weex能否类似Vue那样通过引入一个JS文件实现对数据的绑定等操作，假如可以请问怎么实现？需要注意哪些地方？

**Comment by Jinjiang** [comment]
Weex 也不兼容 IE8，数据绑定的原理和 Vue 是一样的，都基于 `Object.defineProperty`，而这个 API IE8 不支持……

如果想支持 IE8，推荐另外一个 JS 框架，叫 Knockout http://knockoutjs.com/
