### ISSUE TITLE
html5 navigator完善

### ISSUE THREAD

**Issue by qifuren1985** [alibaba/weex#918]
现在html5版本的navigtor是通过页面跳转做到的, 是否可以做到用单页面方式, 这样在微信里面运行的时候就不至于每次进新页面都白一下然后再出现页面. 现在这种做法还一个问题是每次页面back的时候滚动条都会被滚到最上面.

**Comment by MrRaindrop** [comment]
目前navigator只是一个页面导航的工具，并不是一个router组件，它设计是用来做页面导航跳转，但是不保证页面跳转的页面仍然是一个weex页面，所以在weex页面内部没办法管理这个页面栈。

我觉得你的需求应该是要一个router组件，目前weex team还没有将这个列入日程，如果你有好的实现欢迎给我们提pr，我们随时欢迎社区共建 : )
