### ISSUE TITLE
一些不合适的属性设置在root上导致的crash bug

### ISSUE THREAD

**Issue by LeeJay0226** [alibaba/weex#922]
今天在改一个线上页面时发生了一个未预料到的bug。我精简了一下复现bug的代码：
```
<template>
  <container if="{{visible}}" style="background-color: height: 100; width: 750;">
  </container>
</template>  
<script>
  module.exports = {
    data: {
      visible: true
    }
  }
</script>
```
上述代码由于在root元素上设置了if逻辑，导致js-framework 处理不了这种异常逻辑，在ios的某个版本上出现了crash。
后面如何避免类似bug出现：
1. 首先该bug已经反馈给weex开发团队，后面会完善framework的异常处理机制，同时更新文档，说明尽量在root上不要设置if、repeat这样的属性。
2. 后面涉及到修改root属性，或者变动root的需要慎重（这次bug由于变动root的层级引起），需要对旧版本的客户端进行回归测（其实其他的一些小改动最好也都经行版本回归）
3. 希望weex开发团队能给出一些除语法文档之外的，类似注意事项的说明，避免业务踩坑。

**Comment by Jinjiang** [comment]
#927 has been merged into JS Framework.

**Comment by Jinjiang** [comment]
#934 has been merged into docs
