### ISSUE TITLE
扩展component问题

### ISSUE THREAD

**Issue by walid1992** [alibaba/weex#926]
组件扩展出现问题，使用时所有周期方法都走了，不过显示不出来，

**Comment by luics** [comment]
请提供一下代码

**Comment by walid1992** [comment]
就是将input的代码copy过去，想扩展一个支持多行的，然后按照文档的代码粘贴过去也不可以，android设备上

**Comment by walid1992** [comment]
扩展时，直接覆盖原声的组件，input就可以
WXSDKEngine.registerComponent("input", MultiInput.class,false);

**Comment by sospartan** [comment]
支持多行的textarea已经开发完了 可以看一下android分支,会在v0.7提供
之前有问题时,你是怎么注册的?

**Comment by walid1992** [comment]
@sospartan 
就这样
WXSDKEngine.registerComponent("input", MultiInput.class,false);

**Comment by sospartan** [comment]
那你是怎么用的?

**Comment by walid1992** [comment]
@sospartan  
 <input class="input-cell-content" style="max-width:{{cellContentMaxWidth}};" singleline="false" maxlength="10" autofocus="true" placeholder="..." value="{{cellContent}}"></input>

**Comment by walid1992** [comment]
@sospartan 这个还需要require吗？

**Comment by walid1992** [comment]
@sospartan QQ交流下可以么 541280314 这上面效率太低了

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢

**Comment by jiantao88** [comment]
调用demo里的richtext android 端无法显示

**Comment by sospartan** [comment]
@jiantao88 请新建issue来讨论你反馈的问题。谢谢。
