### ISSUE TITLE
input输入框 oninput方法 与onchange方法都失效

### ISSUE THREAD

**Issue by walid1992** [alibaba/weex#935]
获取input输入框内容，没有好的办法，用 `oninput` 方法 与 `onchange` 都不调用回调方法；
1、`onchange="onchange" `
2、
```
onchange: function(event) {
    utils.toastDebug("event" + event)
},
```

**Comment by Jinjiang** [comment]
方便提供一下重现的完整例子以及平台 (iOS/Android/HTML5) 吗？

(别介意我帮你美化了一下正文的格式)

**Comment by walid1992** [comment]
@Jinjiang 我这边采用oninput之后可以了，onchange没反应，是dev分之，
<template>

    <div class="div" style="height:{{height}};">
        <input id="input-phone" oninput="onInputPhone" class="input-phone" style="height:{{cellHeight}}" type="tel" autofocus="true" placeholder="{{placeHolderPhone}}"></input>
        <div style="height:{{cellHeight}};flex-direction: row;">
            <input oninput="onInputCode" class="input-code" style="height:{{cellHeight}};width:550;" placeholder="{{placeHolderCode}}"></input>
            <wld-text class="txt-tip" bg-color="#a1dccc" color="white" font-size="30" value="{{btnTip}}" onclick="btnGetCodeClick"></wld-text>
        </div>
    </div>

</template>

<style>
    .div {
        width: 750;
        position: relative;
        background-color: #ffffff;
        border-top-width: 1;
        border-top-color: #cccccc;
    }

    .input-phone {
        font-size: 30;
        padding-left: 20;
        color: #666666;
    }

    .input-code {
        font-size: 30;
        padding-left: 20;
        color: #666666;
        background-color: #ffffff;
        border-top-width: 1;
        border-bottom-width: 1;
        border-top-color: #cccccc;
        border-bottom-color: #cccccc;
    }

    .txt-tip {
        width: 200;
    }
</style>

<script>
    require('weex-components')
    require('ui/common/wld-text.we')
    var constants = require('util/constants')
    var utils = require('util/utils')

    module.exports = {
        data: {
            placeHolderPhone: "请输入手机号",
            placeHolderCode: "请输入验证码",
            btnTip: "获取验证码",
            cellHeight: "88",
            phoneNumber: '',
        },
        methods: {
            btnGetCodeClick: function(ref) {
                var params = {
                    phoneNumber: this.phoneNumber,
                }
                this.$dispatch('btnGetCodeClick', params)
            },

            onInputPhone: function(event) {
                this.phoneNumber = event.value
            },

            onInputCode: function(event) {
                this.$dispatch('onInputCode', event.value)
            },
        }
    };
</script>

**Comment by Jinjiang** [comment]
哪个平台？iOS 还是 Android？

**Comment by walid1992** [comment]
android 与 ios 都不好用

**Comment by Nicole870606** [comment]
android 输入框 只支持 input事件，change,focus,blur都监听不到

**Comment by Nicole870606** [comment]
输入时无光标提示

**Comment by sospartan** [comment]
事件的问题已经在v0.7修复,光标问题在v0.8修复
