### ISSUE TITLE
支持PUT请求

### ISSUE THREAD

**Issue by moonChenHaohui** [alibaba/weex#936]
hi,在使用weex的过程中发现不支持put请求，请问会列入需求中吗

**Comment by luics** [comment]
是指fetch 吗？ http://alibaba.github.io/weex/doc/modules/stream.html

**Comment by moonChenHaohui** [comment]
是的，

> method(string): the HTTP method GET or POST. 
参数method并没有对put进行支持- - ，求一波指导

**Comment by acton393** [comment]
hi， @moonChenHaohui  文档暂时还没有更新

使用方式，你可以直接使用  put 的 method

可以参考 [demo](https://github.com/alibaba/weex/blob/dev/examples/module/stream-demo.we)

**Comment by acton393** [comment]
暂时先关闭issue了，如果有问题再打开继续回复~~
