### ISSUE TITLE
tech_list.we示例打成APK安装之后，图片访问不了

### ISSUE THREAD

**Issue by cdhjava** [alibaba/weex#941]
1、打成APK之后，安装在android手机上，图片显示不出来，如图：
![1](https://cloud.githubusercontent.com/assets/5310178/17394786/84e6a02c-5a5d-11e6-948a-c229e7955ca6.png)

2、playground则可以
![2](https://cloud.githubusercontent.com/assets/5310178/17394797/8de5ecf0-5a5d-11e6-966d-9b71367091ec.png)

**Comment by alex1226** [comment]
初始化的时候需要指定setImgAdapter 用于处理图片相关加载

**Comment by Jinjiang** [comment]
这个问题长时间没有讨论和反馈，如果有更多讨论仍然可以在这里继续，但这里会做close处理
谢谢
