### ISSUE TITLE
support es6?

### ISSUE THREAD

**Issue by moldauder** [alibaba/weex#944]
可有计划支持es6？

**Comment by luics** [comment]
试试这个 https://www.npmjs.com/package/weex-loader

**Comment by Jinjiang** [comment]
`weex-loader@0.3.0-alpha` 已经可以支持 es6 语法了，背后是通过 babel 转换的，但是仅限于语法糖的部分，可以试试看。

新的类型、对象和方法我们做了有限的 polyfill，具体可以看：http://alibaba.github.io/weex/doc/faq.html "About ECMAScript Version" 的部分

谢谢
