### ISSUE TITLE
[Feature Request]viewport height  希望加入视口高度获取接口

### ISSUE THREAD

**Issue by SimonTal** [alibaba/weex#947]
目前$getConfig().env只提供了设备高度的获取，希望能提供一个 视口高度 获取的api，因为某些应用场景下需要用到视口高度。比如：不可滚动的全屏页面。

**Comment by cxfeng1** [comment]
@SimonTal  在environment中加入视口宽高已经在计划中了， 最早会在0.8.0版本提供， 同时也非常欢迎直接提PR.

**Comment by luics** [comment]
统一到 #421
