### ISSUE TITLE
官方 list 组件 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Bijiabo** [alibaba/weex#948]
官方 list 例子：https://github.com/alibaba/weex/blob/example/examples/component/list/list-basic.we

playground 扫描二维码打开一片空白。
本地浏览器中查看也是一片空白，JS运行报错：

```
events.js:22Uncaught RangeError: Maximum call stack size exceeded  $emit 
@ events.js:22Vm 
@ index.js:64_compileCustomComponent 
@ compiler.js:273_compile 
@ compiler.js:96(anonymous function) 
@ compiler.js:348forEach 
@ (program):839_compileChildren 
@ compiler.js:347_compileNativeComponent 
@ compiler.js:331_compile 
@ compiler.js:100_build 
@ compiler.js:47
```

望指点一下，谢谢！

**Comment by Bijiabo** [comment]
个人失误...命名文件的时候写成了 list.we，升级 weed-toolkit 之后 debug 命令有一个提示 `[Warn]: "./list.we" cannot include <list> itself.` 才找到原因。

**Comment by zk0301** [comment]
我遇到这个问题是<myrichtext。。。不行，要改成<my_richtext。。。
无语
