### ISSUE TITLE
程序启动起来之后为啥不能刷新？

### ISSUE THREAD

**Issue by zhangfengGH** [alibaba/weex#949]
程序启动起来之后,只要一刷新就卡死？难道要看一次就要重启一次？用安卓playground扫描也一样不能刷新，且改动源码，页面并没有热更新。所有例子都一样，环境如下：
node : v6.2.0
npm : v3.8.9
win64
git : v2.9.2

**Comment by Jinjiang** [comment]
安卓的具体环境可不可以提供一下？比如机型、系统版本
谢谢

**Comment by zhangfengGH** [comment]
这个和安卓没啥关系，我用浏览器打开页面也一样，一直在pending，很长时间才能出来。应该是你们内置的web服务器有问题，我把编译生成的weex_temp放到nginx里面，一切正常！

**Comment by Jinjiang** [comment]
好，我们会准备一份 Windows 的环境试试看，感谢反馈

**Comment by Jinjiang** [comment]
Hi，我实际找了一台 windows 测试，没有发现你描述的问题
我有几个细节想更多了解：1 你是否是在虚拟机环境下；2 是否本地有别的服务共享或影响了系统资源；3 你的使用的命令行工具是默认的cmd还是cygwin或别的什么工具
谢谢

**Comment by Jinjiang** [comment]
这个问题比较久了没有收到答复，这里先做关闭处理了
如果有更多情况，可以随时留意 reopen 继续讨论

谢谢
