### ISSUE TITLE
目前Weex的语法已经定稿了么？后续是否会随着Vue的语法变化而变化？

### ISSUE THREAD

**Issue by paoloo1995** [alibaba/weex#950]
目前Weex的语法更像早期版本的Vue，为什么不提升一下对Vue 1.0语法的支持呢？是本来就这样设计的，还是在等Vue 2.0定稿？

**Comment by Jinjiang** [comment]
我们会针对 native 环境下的特殊情况对 API 做一些取舍，没有刻意要和 1.0 语法抹平，同时 Vue 2.0 的接入已经在同步进行中了，最新的进展在 `jsfm-feature-vue` 分支
