### ISSUE TITLE
新版本weex-loader： js--> require问题

### ISSUE THREAD

**Issue by walid1992** [alibaba/weex#952]
function extend(dest, src) {
  for (var key in src) {
    dest[key] = src[key]
  }
}
exports.extend = extend

这种引入方法：
var xbBridge = require('util/xb-bridge'
xbBridge.extend 报方法找不到异常

**Comment by vczero** [comment]
确保相对路径正确。
可以参考：http://alibaba.github.io/weex/doc/how-to/require-3rd-party-libs.html

**Comment by walid1992** [comment]
能确保相对路径正确，配的别名，之前没问题的，是更新了最新的weex出现的问题，希望尽快解决下，qq群里很多遇到这个问题的

**Comment by walid1992** [comment]
强调一下:
       之前运行没有任何问题，更新最新weex出现的问题，希望你们先自测一下

**Comment by terrykingcha** [comment]
@walid1992   你所说的最新版本的weex-loader，指的是0.3.0-alpha吗？

**Comment by Jinjiang** [comment]
应该是使用问题，我直接联系你小窗解决
这里先关掉了

**Comment by huangang** [comment]
求分享解决方案

**Comment by Jinjiang** [comment]
之前的 webpack loader 配置设计得不直观，已经在 0.3.1 做了更新
