### ISSUE TITLE
现在不支持textarea定义的多行文本输入？

### ISSUE THREAD

**Issue by Lurkyli** [alibaba/weex#955]
你好，

我现在想在页面中想创建一个多行的文本输入框，HTML5中可以用textarea定义。但在weex的内建组件中没有textarea，我该如何定义这样的文本输入框？或者这个需要使用自定义组件?

**Comment by acton393** [comment]
hi， @Lurkyli  textarea 在接下来发布的这个版本中会支持

**Comment by Lurkyli** [comment]
^_^多谢！

**Comment by luics** [comment]
合为一个 #324

**Comment by acton393** [comment]
hi  @Lurkyli   textarea 在Android和iOS 上已经支持， h5 也会尽快支持，你可以先体验下
