### ISSUE TITLE
当宽度设为$getConfig().env.deviceWidth时，与实际显示宽度不一致。游览器和native显示不一致

### ISSUE THREAD

**Issue by zhoukekestar** [alibaba/weex#956]
`display:flex;` 和`postion:fixed`，在游览器和app中的显示效果不同
```html
<template>
  <div>

    <div class='flex'>
      <div class='flex-item'>
        <text>1</text>
      </div>
      <div class='flex-item'>
        <text>1</text>
      </div>
      <div class='flex-item'>
        <text>1</text>
      </div>
    </div>

    <div class='flex' style='position: fixed; bottom: 0; width: {{$getConfig().env.deviceWidth}}px;'>
      <div class='flex-item'>
        <text>2</text>
      </div>
      <div class='flex-item'>
        <text>2</text>
      </div>
      <div class='flex-item'>
        <text>2</text>
      </div>
    </div>
  </div>
</template>


<style>
  .flex {
    display: flex;
    flex-direction: row;
    border-style: solid;
    border-width: 1px;
    border-color: #f00;
  }
  .flex-item {
    flex: 1;
    border-style: solid;
    border-width: 1px;
    border-color: #333;
  }

</style>

```
游览器效果：
![qq 20160808160240](https://cloud.githubusercontent.com/assets/7157346/17473204/cc225446-5d81-11e6-9cd9-b5d8ac256160.png)

app效果（android和ios都一样）
![img_1003](https://cloud.githubusercontent.com/assets/7157346/17473206/cd9cbf00-5d81-11e6-9433-fd2a0a8ff032.PNG)

**Comment by vczero** [comment]
1）其实weex支持的属性和样式如下：
https://github.com/alibaba/weex/blob/dev/doc/references/cheatsheet.md

2）还有就是官方文档：
http://alibaba.github.io/weex/doc/references/common-style.html

Flexbox is the default and only style model in Weex, so you don't have to add display: flex; in a container.
flexbox在weex中是默认的布局模型；同时weex做了Native和浏览器的一致性兼容

**Comment by zhoukekestar** [comment]
我写的样式属性不是应该都是可以的吗？哪个不行吗？望指正。。。

**Comment by vczero** [comment]
@zhoukekestar 应该是这样的：
1）Weex实现了自己的布局模型：Flexbox + 盒子模型
    可以参考：http://alibaba.github.io/weex/doc/references/common-style.html
2）Weex实现了字体的样式，比如行数控制(lines)
   可以参考：http://alibaba.github.io/weex/doc/references/text-style.html    
3)Weex实现了position、opacity, background-color等
  可以参考：position: values relative | absolute | fixed | sticky, default value relative         

所以，开发App的时候，就需要遵循Weex的规范，Weex样式是W3C样式子集，比其掌握起来要容易的多。
希望可以帮到你，：）

**Comment by zhoukekestar** [comment]
。。。跟我要反应的问题好像没关系吧，我应该都是按规范写的 吧？是我太笨了吗？
我重新说一下，我想说的问题是，app上的显示效果和理想效果不一致。是我哪里写错了，还是说这就是一个特性？
![cd9cbf00-5d81-11e6-9433-fd2a0a8ff032](https://cloud.githubusercontent.com/assets/7157346/17475043/95f37094-5d8b-11e6-99e4-e6478d0cf9a3.PNG)

**Comment by vczero** [comment]
我这里实验了一致，去掉display: flex; 如果还有报一下设备号

**Comment by zhoukekestar** [comment]
```html
<style>
  .flex {
    
    flex-direction: row;
    border-style: solid;
    border-width: 1px;
    border-color: #f00;
  }
  .flex-item {
    flex: 1;
    border-style: solid;
    border-width: 1px;
    border-color: #333;
  }

</style>
```
去除`display: flex`后，还是一样的结果
weex version: 0.4.4
ios weex version: 1.1 (iPhone 5s)
android weex version: weex_playgroud_10006024.apk (官网最新下载) (Android 4.3)

**Comment by vczero** [comment]
@zhoukekestar 我来还原下场景

**Comment by zhoukekestar** [comment]
我大概知道了
```html
<template>
  <div>
    <text class='hello'>hello</text>
    <text class='hello' style='width: {{$getConfig().env.deviceWidth}}px;'>hello</text>
  </div>
</template>

<style>
  .hello {
   border-style: solid;
    border-width: 1px;
    border-color: #333;
  }
</style>
```

**Comment by zhoukekestar** [comment]
Bug fixed?
