### ISSUE TITLE
数据绑定的新问题

### ISSUE THREAD

**Issue by myhirra** [alibaba/weex#958]
```
<template>
    <div onclick="click()">
      <text>test</text>
      <text repeat="{{(i,v) in wrap.keys}}">{{v.key}}</text>
    </div>
</template>

<script>
    module.exports = {
        data: {
          wrap:{
            keys: [{
              key:1
            },{
              key:2
            }]
          }
        },

        methods: {
            click:function () {
              this.wrap.keys.$set(0, {key:'a'});
              this.wrap.keys.$set(1, {key:'b'});
              nativeLog(JSON.stringify(this.wrap))
            }
          }
    };
</script>
```

最新的jsframwork，点击之后并没有发生改变，但数据已经发生了变化

**Comment by Hanks10100** [comment]
初步测了一下，在 web 中没有问题，Andriod 上和你描述的一样，可能是移动端未能及时响应更新事件。

**Comment by Jinjiang** [comment]
我实测dev分支下，iOS 端用最新 build 出来的 JS Framework 也是没有问题的

**Comment by Jinjiang** [comment]
同步一下今天下午当面讨论的部分结论：

1. 直接修改数组每一项里的字段，比如 `this.wrap.keys[1].key = '...'` 是肯定没有问题的
2. 直接增减数组项目也是没有问题的，比如 `this.wrap.keys.push({ key: '...' })` 也是肯定没有问题的
3. 设置数组中的某一项目在低版本的 JS Framework 上不同程度存在 bug，我们之前陆续做了修复了，目前最新版相对比较稳定
4. 在 Promise 和 timer APIs 中产生的数据修改，在低版本的 JS Framework 会出现更新不及时的情况，老版本的变通方案是在修改数据之后补一个 `this._app.updateActions()` 的“黑魔法”

更多细节我接下来详细整理一下，把每个版本的问题罗列出来，同时提供多个版本兼容的最佳实践

多谢大家，这个 issue 我先关掉了
