### ISSUE TITLE
weex支持SPA开发理念和页面路由组件支持

### ISSUE THREAD

**Issue by brunoduan** [alibaba/weex#959]
详细需求：用weex写页面应用，用open url方式打开一个个的页面，需要自己写容器管理前进后退。这种方式类似于比较原始的web页面，点击不同链接打开新的页面，只不过浏览器帮忙管理了页面堆栈。但前端开发这块貌似用单页面应用（SPA）的理念来开发web应用，做到无页面重新加载或跳转就可以动态刷新页面。weex作为一种动态化方案，不支持SPA的话，那么需要重新加载或调整页面，用户体验不好。
weex支持SPA开发理念，需要提供路由机制实现页面跳转。

应用场景：weex页面切换，不要重新加载或跳转

**Comment by Jinjiang** [comment]
Weex 在这里确实做了一些取舍，SPA 追求的是页面之前无中断无重置的切换，当然也有相应的代价：

1. 页面之间的耦合会一定程度增加，这种耦合是开发到发布到运行整套流程中，还有浏览历史记录的模拟等等。
2. 还有一点是页面切换体验的增强是牺牲了首次加载的时间的，因为相关代码和资源需要提前准备好，比一般页面加载了额外的东西。
3. 今天很多App都是一部分native、一部分 html5的，而且相互之间会产生一定的转换，SPA 之后这样的转换和融合变得困难

Weex 在这方面也一直在思考，我没有比较轻量的 navpage 和 tabbar 组件支持简单的路由管理，但支持更复杂的场景一定是在有比较合适的解决方案的基础上。

谢谢

**Comment by MrRaindrop** [comment]
https://github.com/alibaba/weex/issues/918

**Comment by brunoduan** [comment]
我的一些看法。
1、页面之间耦合度增加是存在的，需要业务方多做模块化的设计，页面之间肯定有交互，同时weex需要提供页面之间高效通信的机制？
2、首次加载时间属于性能问题，可以放在以后慢慢优化。比如结合服务端渲染技术，或者首页模块化设计等？
3、navpage目前是activity之间的切换，实际利用的是android的路由机制，但我们不能假定页面容器是activity，利用activity这个方案过重？
4、native和web页面共存的话，可以结合浏览器的navigator，满足weex页面和web页面之间的切换，可以说这个时候weex容器变成了浏览器。由于weex容器可以有很多种，weex本身应该提供路由机制将URI和容器页面对应起来，不能交给容器去做？

**Comment by Jinjiang** [comment]
回答你的几个问题：

1. 我们已经有另外的 issue 在讨论了，这里不再展开
2. “可以放在以后慢慢优化”，显然你把问题想简单了，团队现在非常注重这部分的性能问题，性能的提升对业务价值和整体用户体验同样很重要，后面你举的两个例子和现在团队做的事情不冲突
3. navpage 和 tabbar 确实有改进空间，“方案过重”这一点你可以再展开一下，听听你更具体的判断和想法
4. 我不赞成以浏览器navigator为路由中心的设计，路由控制在视图层上一定是 native 的更灵活可靠

**Comment by brunoduan** [comment]
理了一下思路：

假设weex页面a,b,c,d分别对应不同uri 理想情况是a b c d都在同一个容器X，对于这种情况我们可以做通用的navigator，在该容器内部可以自由进行页面切换。需要weex给外面增加一个切换通知的接口，告诉容器根据uri进行容器内部的页面切换。

对于页面a b在容器X，c d在容器Y的情况，weex内部的navigator是管不了容器X和Y之间的切换的，并且过场动画要做成什么样子是业务方定的，weex根本不清楚。更加麻烦的是，从Y容器的d页面切换到X容器的a页面，weex的navigator更加无能为力。

动态框架的navigator这块确实比较难搞。。

**Comment by Jinjiang** [comment]
没错。你说的这个现象一定程度和我们的担忧是吻合的，现在在我们的工作中更现实的情况是a,b,c,d四个界面，a和c是Weex的，b是纯native的，d是WebView的，这种情况我们现在是比较难做的，也就是你说的“weex内部的navigator管不了容器X和Y之间的切换”，只能把路由交给通用的native导航来处理，所以SPA的策略比较难实现。
我们可以保持探讨

**Comment by Jinjiang** [comment]
该 issue 长期没有讨论&Action，这里先做关闭处理
团队后续会在这块有更多的思考，并在有成熟的想法后重启这方面讨论

谢谢：）

**Comment by wulie88** [comment]
依然建议重启SPA方案，现在2017年都结束了，小程序平台也应该出来了。

1 页面间的跳转请先考虑Weex自身
2 加载性能通过本地包来解决

@Jinjiang
