### ISSUE TITLE
weex如何让text标签随里面的文字大小而变化？

### ISSUE THREAD

**Issue by jiwenfei** [alibaba/weex#961]
想实现下面的布局：
![image](https://cloud.githubusercontent.com/assets/14801991/17484072/fcd983aa-5dba-11e6-86f5-f80669bca28e.png)

但是图中中text并没有随着文字大小而变化，造成最后一句“我知道了”仍然占据了满行，请问如何让weex的text标签随着文字的而自动变化？

**Comment by luics** [comment]
请关注一下富文本 #835

**Comment by YorkShen** [comment]
@jiwenfei 文字不要设置width，这个时候会根据文字内容自动计算宽度。如果设置了width，用户设置的width优先级更高，自适应功能此时将失效
