### ISSUE TITLE
[Discus] is it possible to set fixed length value

### ISSUE THREAD

**Issue by daxingplay** [alibaba/weex#965]
It seems that current length value works like rem. When I set a text style as `font-size: 32`, it seems ok in iPhone6, but for earlier devices such as iPhone 5S or iPhone 5, the text becomes smaller than iPhone6. That's why I think weex current length works as rem in html5.

So my question is, is it possible to set a fixed length value which works as normal `px` in the browser?

**Comment by Jinjiang** [comment]
Thanks for your advice. Actually there has been an issue to discuss this #421
We will solve it at a appropriate time and also please move into this issue for more discussion.
