### ISSUE TITLE
[Feature Request] list增加下拉进度动画

### ISSUE THREAD

**Issue by LeeKM** [alibaba/weex#967]
目前list的下拉刷新效果只有在下拉松手的时候有一个系统菊花，能不能增加下拉进度的动画：在下拉的时候有个进度动画，到达下拉刷新点的时候动画停止，触发下拉刷新；或者增加下拉刷新进度的回调？

**Comment by acton393** [comment]
cool， 会尽快支持下拉事件~

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
