### ISSUE TITLE
ios demo中的podfile无法更新

### ISSUE THREAD

**Issue by pengdonghua** [alibaba/weex#970]
提示Unable to find a specification for `ATSDK-Weex`,这个库不提供更新了吗？

**Comment by acton393** [comment]
hi @pengdonghua   在[weex.help](http://weex.help/topic/57aac7eba16ef6026b9c756e) 已经回复你了

主要是因为你本地的cocoaPods 的库太久没有更新，尝试如下操作：

- 先执行 `pod repo update`

- 按照 [readme](https://github.com/alibaba/weex#ios) 在playground 目录下执行 
`pod install`

如果还有问题reopen issue，继续回复
