### ISSUE TITLE
please make stream cors

### ISSUE THREAD

**Issue by havefive** [alibaba/weex#974]
详细描述：当前weex 好像还不支持跨域，可否先提供开源支持
应用场景：本地开发调试

**Comment by sospartan** [comment]
native不存在跨域的问题,你说的是h5? 能说一下具体问题么,或者贴一下相关代码片段

**Comment by havefive** [comment]
对，native不存在跨域的问题，是h5调试时出现，比如
stream.fetch({
        method: 'GET',
        url: 'http://192.168.3.6:1340/api/weather ',
        type:'json'
      }
出现 No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.3.6:12580' is therefore not allowed access

**Comment by sospartan** [comment]
支持的,使用`type:'jsonp'`

**Comment by havefive** [comment]
OK

**Comment by MrRaindrop** [comment]
目前`stream.fetch`支持两种跨域方式：
1. 使用jsonp跨域，即`type:'jsonp'`，服务器端可以从参数`callback`解析到回调函数名称
2. 使用cors跨域，需要服务器支持输出"Access-Control-Allow-Origin"协议头

**Comment by havefive** [comment]
谢谢你们，服务器使用了express，改动点话麻烦点，先关闭好了

**Comment by havefive** [comment]
可以了，备注一下express服务器输出"Access-Control-Allow-Origin"协议头方法：
app.js
//设置跨域访问
app.all('*', function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "X-Requested-With");
    res.header("Access-Control-Allow-Methods","PUT,POST,GET,DELETE,OPTIONS");
    res.header("X-Powered-By",' 3.2.1')
    res.header("Content-Type", "application/json;charset=utf-8");
    next();
});

**Comment by sudeepdk** [comment]
did anyone got solution .. ?  , for now I have added CORS extension and consuming node API using stream.fetch but this is not a Fix ...right
