### ISSUE TITLE
android 传值给 Js页面 的两个问题

### ISSUE THREAD

**Issue by mynameispp** [alibaba/weex#980]
1.在自己写的工程里面使用JsCallBack无法回调给JS,使用wxBridgeManager.callback才能回调过去。
2.android 怎么直接传值给 Js页面。不要js--native--js.而是native--js.

**Comment by sospartan** [comment]
2.目前还没有直接发事件给js的机制,正在做.

第一个问题,能贴一下你native上的代码片段么?

**Comment by mynameispp** [comment]
android=========可传================== 
@WXModuleAnno(runOnUIThread = true)
    public void printLog(String msg,String callback) {
        Toast.makeText(mWXSDKInstance.getContext(),msg,Toast.LENGTH_SHORT).show();
        Map<String,Object> resp = new HashMap();
        resp.put("result","ok");
        resp.put("stata","ssssss");
        wxBridgeManager.callback(mWXSDKInstance.getInstanceId(), callback, "jjjjjjjjj");
    }
Js======================================
var mode=__weex_require__('@weex-module/myModule');
		mode.printLog("weex is bicth",function (res){
		self.titleName=res;
		mode.log(res);
			modal.toast({
	                  message: res,
	                  duration: 2
	                });
		});
android=========不可传================== 
@WXModuleAnno(runOnUIThread = true)
    public void printLog(String msg,JSCallback callback) {
        Toast.makeText(mWXSDKInstance.getContext(),msg,Toast.LENGTH_SHORT).show();
        Map<String,Object> resp = new HashMap();
        resp.put("result","ok");
        resp.put("stata","ssssss");
        callback.invoke(res);
    }
Js======================================
var mode=__weex_require__('@weex-module/myModule');
		mode.printLog("weex is bicth",function (res){
		self.titleName=res;
		mode.log(res);
			modal.toast({
	                  message: res.result,
	                  duration: 2
	                });
		});

**Comment by sospartan** [comment]
我查一下.
btw: 代码里有typo,应该是`bitch`

**Comment by mynameispp** [comment]
哈哈，大侠好眼力，查完麻烦回复一下，以免其他小伙伴踩坑

**Comment by sospartan** [comment]
@mynameispp  我试了一下JSCallback没问题的

不过你第二部分代码我改了两个地方:
0. java里`callback.invoke(res);`的`res`,这个变量应该是写错了
0. js部分`mode.log`没有这个函数,我改成了`console.log`

**Comment by mynameispp** [comment]
我试了下，还是不行，麻烦看看我的代码对不对：
java==============================
 @WXModuleAnno(runOnUIThread = true)
    public void printLog(String msg,JSCallback callback) {
        Toast.makeText(mWXSDKInstance.getContext(),msg,Toast.LENGTH_SHORT).show();
        Map<String,Object> res = new HashMap();
        res.put("result","ok");
        res.put("stata","ssssss");
        callback.invoke(res);
//        wxBridgeManager.callback(mWXSDKInstance.getInstanceId(), callback, "jjjjjjjjj");
    }
    @WXModuleAnno
    public void log(String msg){
        //implement your module logic here
        Log.e("Log..",msg);
    }
js========================================
 methods: {
	      goWeexSite: function () {
         		var self=this;
         		var mode=__weex_require__('@weex-module/myModule');
		         mode.printLog("weex is beach",function (res){
		                self.titleName=res.result;
                		mode.log(res.stata);
         		});
	   }

运行点击：E/weex: [WXModalUIModule] toast param parse is null

**Comment by sospartan** [comment]
你把native logcat内容贴上来吧  肯定是哪里报错了

**Comment by mynameispp** [comment]
08-11 14:17:29.872 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:29.882 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:29.882 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.media.session.MediaController', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:29.882 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.widget.Toolbar', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:29.892 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:29.892 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:29.902 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:29.932 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:29.952 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.app.assist.AssistContent', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:29.962 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.view.SearchEvent', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:29.982 20179-20179/com.feifanzhixing.weexandroid E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.feifanzhixing.weexandroid.MainActivity.access$super
08-11 14:17:30.412 20179-20210/com.feifanzhixing.weexandroid E/jsengine:  send_request send_request url:http://gm.mmstat.com/weex.1003?appname=WeexAndroid server:(null):0 proxy:(null):0 is_transparent_proxy:0

这是运行的时候打印出来的，但点击没有log
==========实在不行你可以私密给我QQ号，我把demo发给你看看===============

**Comment by jieshadow** [comment]
请问wxBridgeManager这个是怎么来的？

**Comment by sospartan** [comment]
@mynameispp 这个问题最终解决了么？已经有段时间没更新了，我先关闭，如果还未解决，请reopen。

**Comment by zk0301** [comment]
我的版本是0.10.x， 我传的是string，没有问题，map我没试。
android的是  callback.invoke("please wait ...");
js的是
__weex_require__('@weex-module/my_camera').takePhoto(function (res) {
          var modal = __weex_require__('@weex-module/modal');
          modal.toast({
                      message: res,
                      duration: 2
                    });
	      });
