### ISSUE TITLE
在pod中搜索不到WXDevtool  

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex#981]
我在自己的项目中使用WXDevtool去调试代码，但是在安装的过程出现错误,Podfile如下
![image](https://cloud.githubusercontent.com/assets/12522809/17578301/ce218c50-5fb9-11e6-9925-dbccd155cfbb.png)
安装错误提示如下:
![image](https://cloud.githubusercontent.com/assets/12522809/17578314/f779d878-5fb9-11e6-81c0-26546205283b.png)

我在pod中搜索WXDevtool 结果如下：
![image](https://cloud.githubusercontent.com/assets/12522809/17578284/9a86bf0a-5fb9-11e6-9cac-deb02c2f3ba9.png)

不知道是不是beta版 造成的   等下再试试正式版的   但是其他的都可以搜到

**Comment by acton393** [comment]
hi  @emptywalker   WXDevtool 在 cocoaPods 的repo 上暂时还没有提交， WeexSDK 提交了0.6.0 和0.6.1，
所以 pod search 时候搜不到 WXDevtool， devtool 目前只能源码依赖， WeexSDK 可以直接写正式的版本号依赖

**Comment by emptywalker** [comment]
thanks, 是我没了解pods中path的用法，后来明白了，略显尴尬 -_-

**Comment by acton393** [comment]
我先关了，如果有问题再打开
