### ISSUE TITLE
Cannot resolve 'file' or 'directory' ./config

### ISSUE THREAD

**Issue by RoadsInFarAway** [alibaba/weex#985]
ERROR in ./html5/runtime/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./config in D:\IT\workspace\WeexProject\weex\html5\runtime
 @ ./html5/runtime/index.js 8:14-33

**Comment by vczero** [comment]
@RoadsInFarAway 请描述你的工程详细信息，初步看是是否是打包配置问题？

**Comment by Jinjiang** [comment]
It seems that you should run `npm run build:config` first. I found this bug earlier in Windows (In Mac/Linux it will be run automatically). We will try to fix soon.

Thanks.

**Comment by Jinjiang** [comment]
duplicated with #826
this issue would be closed
