### ISSUE TITLE
在style属性中 三元运算失效

### ISSUE THREAD

**Issue by Mrluobo** [alibaba/weex#986]
如题：
```
<div style="color:{{test?'red':'blue"}}"></div>
<text>{{test?'red':'blue"}}</text>
```

这种情况下  style中的三元运算就失效了

**Comment by Hanks10100** [comment]
目前还不支持这种场景，以后可以考虑支持这种用法。

**Comment by vczero** [comment]
@建议使用computed计算好后使用

**Comment by vczero** [comment]
@Mrluobo 建议使用computed计算好后使用

**Comment by songsiqi** [comment]
@Mrluobo style里面的三目运算符现在也是支持的。看一下你的weex-laoder依赖的weex-templater版本是不是0.3.0
