### ISSUE TITLE
WXScrollerProtocol缺少监听偏移量的接口

### ISSUE THREAD

**Issue by zlit** [alibaba/weex#990]
WXScrollerProtocol缺少监听偏移量的接口.
很多业务,诸如上拉,下拉刷新的箭头变化,以及文案变化,都需要这个功能.
目前我在iOS这里是拿到parentView,对给contentOffset添加观察者,来监听偏移量变化的.

**Comment by Jinjiang** [comment]
该 issue 将会汇总到 #1494 ，那里记录了所有新需求和不活跃的开放讨论。我们希望通过此举让社区和团队更加聚焦在活跃的和当前正在解决的问题。如果这个问题在未来会被解决或重新讨论，我们会适时做 reopen 操作。
再次感谢您的支持！
