### ISSUE TITLE
a标签 ios，安卓功能不一致

### ISSUE THREAD

**Issue by joebnb** [alibaba/weex#994]
同样是 a 标签

```
<a onClick="javascriptCall" href="someLocation" ></a>
```

就这个 a 标签，如果在 ios 下，onClick 事件是可以监听到的，但是到了安卓下 onClick 就监听不到了，虽然说，href 会覆盖 onClick 事件，herf 可以通过 onClick 模拟出来，但是用起来确实没有 ios 下方便

比如一个最常见的 由 React 搭建的 SPA 场景
* 我要通过锚点切换页面（但这个切换却是同步的），切换前需要执行一段 js 代码设置下 state

**Comment by acton393** [comment]
@YorkShen

**Comment by YorkShen** [comment]
目前weex android的a标签是底层实现是通过在java层的div上绑定onclick事件，在事件回调中调用openURL做的。这个方案会和onClick事件冲突。如果需要在a标签上自定义onClick事件，建议通过在.we层div上绑定onClick事件，并在里面调用openURL和其他相应逻辑进行处理。

**Comment by joebnb** [comment]
作为用户很少关心安卓内部具体如何实现这个功能，只是在api 层面接触，目前来看，ios 和 android 体验不一样，很难做到 write once run everywhere

**Comment by luics** [comment]
@joebnb 这只是个细节，既然提出来了，后续请 @YorkShen 和 @acton393 统一下实现细节，避免上层的差异。

**Comment by YorkShen** [comment]
@joebnb 你代码写错了
`
<a onClick="javascriptCall" href="someLocation" ></a>
`

应该是这样，onclick全小写。
`
<a onclick="javascriptCall" href="someLocation" ></a>
`

https://github.com/sospartan/weex/tree/tb-dev 分支已支持此feature，尚未合并到主分支。
