### ISSUE TITLE
Preview in Browser doesn't work

### ISSUE THREAD

**Issue by hpsoar** [alibaba/weex#999]
weex examples/hello.we

by execute the above, the browser automatically opens
http://127.0.0.1:8081/weex_tmp/h5_render/?hot-reload_controller&page=hello.js&loader=xhr

unfortunately, got the following:

The 127.0.0.1 page isn’t working

127.0.0.1 didn’t send any data.

BR

**Comment by lvscar** [comment]
please check network configuration of  your computer, on Linux or Mac ,the cmd is:
```
ifconfig 
```

find your localhost IP from result of above cmd.

then you can use -h argument of weex-toolkit change the default ip , eg:
```
weex xxx.we  -h 127.0.0.2
```

**Comment by hpsoar** [comment]
This works now.
It may be that I was using VPN, or some other strange reason.
Thanks.
